#!/usr/bin/env node
// Generates supabase/seed/learn_demo.sql from the demo curriculum JSON (single source of truth).
// The seed is NOT a migration and refuses to run unless the session opts in:
// 1) a staging-only marker table must exist (`npm run staging:db:marker`; never created by migrations, so production
//    can never satisfy this guard), AND
// 2) the session must opt in: set app.allow_demo_seed = 'on'.
// supabase/seed/learn_demo.staging-run.sql = the opt-in line + this seed, for `npm run staging:db:seed`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const q = (s) => (s === null || s === undefined ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const arr = (a) => (a?.length ? `array[${a.map(q).join(",")}]::text[]` : "'{}'::text[]");

const out = [];
out.push(`-- GENERATED by scripts/learn/generate-seed.mjs — DEMO DATA ONLY. Do not edit by hand.
-- Refuses to run unless the staging marker table exists AND app.allow_demo_seed = 'on'.
begin;
do $$ begin
  if to_regclass('public.learn_seed_allowed') is null then
    raise exception 'demo seed refused: this database has no staging marker (public.learn_seed_allowed). Never seed production.';
  end if;
  if coalesce(current_setting('app.allow_demo_seed', true), '') <> 'on' then
    raise exception 'demo seed refused: set app.allow_demo_seed = on';
  end if;
end $$;
-- Demo content is treated as reviewed by the project team; bypass the human-review trigger for this load only.
alter table public.learn_questions disable trigger learn_questions_publish_flow;
insert into public.learn_countries(code, name) values ('KR', '대한민국') on conflict do nothing;
insert into public.learn_subjects(code, name) values ('math', '수학'), ('english', '영어') on conflict do nothing;`);

for (const site of ["math", "english"]) {
  const { catalog, questions } = JSON.parse(readFileSync(path.join(root, `lib/learn/content/demo/${site}.json`), "utf8"));
  const subj = `(select id from public.learn_subjects where code = ${q(site)})`;
  out.push(`\n-- ${site}`);
  out.push(`insert into public.learn_curricula(code, country_code, name, status) values (${q(catalog.curriculum)}, ${q(catalog.country)}, ${q(catalog.curriculum)}, 'PUBLISHED') on conflict (code) do nothing;`);
  for (const s of catalog.skills) {
    out.push(`insert into public.learn_skills(code, subject_id, title) values (${q(s.id)}, ${subj}, ${q(s.title)}) on conflict (code) do nothing;`);
  }
  for (const s of catalog.skills.filter((x) => x.prerequisiteId)) {
    out.push(`update public.learn_skills set prerequisite_skill_id = (select id from public.learn_skills where code = ${q(s.prerequisiteId)}) where code = ${q(s.id)};`);
  }
  catalog.courses.forEach((c, ci) => {
    out.push(`insert into public.learn_courses(code, curriculum_id, subject_id, school_level, grade, title, world_name, world_emoji, world_tagline, sort_order, status)
  values (${q(c.id)}, (select id from public.learn_curricula where code = ${q(catalog.curriculum)}), ${subj}, ${q(c.grade.startsWith("M") ? "middle" : "high")}, ${q(c.grade)}, ${q(c.title)}, ${q(c.world.name)}, ${q(c.world.emoji)}, ${q(c.world.tagline)}, ${ci}, 'PUBLISHED') on conflict (code) do nothing;`);
    c.units.forEach((u, ui) => {
      out.push(`insert into public.learn_units(code, course_id, title, sort_order, status) values (${q(u.id)}, (select id from public.learn_courses where code = ${q(c.id)}), ${q(u.title)}, ${ui}, 'PUBLISHED') on conflict (code) do nothing;`);
      u.lessons.forEach((l, li) => {
        out.push(`insert into public.learn_lessons(code, unit_id, title, concept, example, sort_order, status) values (${q(l.id)}, (select id from public.learn_units where code = ${q(u.id)}), ${q(l.title)}, ${q(l.concept)}, ${q(l.example)}, ${li}, 'PUBLISHED') on conflict (code) do nothing;`);
        for (const sid of l.skillIds) out.push(`insert into public.learn_lesson_skills(lesson_id, skill_id) select (select id from public.learn_lessons where code = ${q(l.id)}), (select id from public.learn_skills where code = ${q(sid)}) on conflict do nothing;`);
      });
    });
  });
  for (const qu of questions) {
    out.push(`insert into public.learn_questions(code, subject_id, skill_id, type, difficulty, prompt, latex, role, family, expected_seconds, audio_text, tags, status)
  values (${q(qu.id)}, ${subj}, (select id from public.learn_skills where code = ${q(qu.skillId)}), ${q(qu.type)}, ${qu.difficulty}, ${q(qu.prompt)}, ${q(qu.latex)}, ${q(qu.role)}, ${q(qu.family)}, ${qu.expectedSeconds ?? "null"}, ${q(qu.audioText)}, ${arr(qu.tags)}, ${q(qu.status)}) on conflict (code) do nothing;`);
    const id = `(select id from public.learn_questions where code = ${q(qu.id)})`;
    out.push(`insert into public.learn_question_answers(question_id, answer) values (${id}, ${q(JSON.stringify(qu.answer))}::jsonb) on conflict do nothing;`);
    out.push(`insert into public.learn_question_explanations(question_id, body) values (${id}, ${q(qu.explanation)}) on conflict do nothing;`);
    qu.hints.forEach((h, i) => out.push(`insert into public.learn_question_hints(question_id, level, body) values (${id}, ${i + 1}, ${q(h)}) on conflict do nothing;`));
    (qu.options ?? []).forEach((o, i) => out.push(`insert into public.learn_question_options(question_id, option_key, body, sort_order) values (${id}, ${q(o.id)}, ${q(o.text)}, ${i}) on conflict do nothing;`));
  }
  // Lesson question lists (order preserved, challenge flagged).
  for (const c of catalog.courses) for (const u of c.units) for (const l of u.lessons) {
    [...l.questionIds.map((x) => [x, false]), ...(l.challengeId ? [[l.challengeId, true]] : [])].forEach(([qid, ch], i) => {
      out.push(`insert into public.learn_lesson_questions(lesson_id, question_id, sort_order, is_challenge) values ((select id from public.learn_lessons where code = ${q(l.id)}), (select id from public.learn_questions where code = ${q(qid)}), ${i}, ${ch}) on conflict do nothing;`);
    });
  }
}
out.push(`alter table public.learn_questions enable trigger learn_questions_publish_flow;\ncommit;\n`);
mkdirSync(path.join(root, "supabase/seed"), { recursive: true });
const body = out.join("\n");
writeFileSync(path.join(root, "supabase/seed/learn_demo.sql"), body);
writeFileSync(path.join(root, "supabase/seed/learn_demo.staging-run.sql"), "-- STAGING ONLY (still refused unless the staging marker table exists)\nset app.allow_demo_seed = 'on';\n" + body);
console.log("wrote supabase/seed/learn_demo.sql and learn_demo.staging-run.sql");
