/**
 * Multilingual UI Translations for Region Selection and Display (36 Languages)
 * 
 * Rules:
 * 1. Korean (`ko`): Korean text only (e.g. "내 거주 지역 (시·도 / 구·군·시 / 동·읍·면)", "지역 변경 ▾")
 * 2. Foreign languages: `[Native] · [Korean]` format for clarity and bilingual support
 * 3. Administrative divisions:
 *    - "시도" -> "시·도"
 *    - "구군" -> "구·군·시"
 *    - "동읍면" -> "동·읍·면"
 */

export interface RegionUITexts {
  yourLocation: string;
  changeLocation: string;
  activeArea: string;
  selectLocation: string;
  selectDescription: string;
  sidoCategory: string;
  gunguCategory: string;
  dongCategory: string;
  selecting: string;
  typeTown: string;
  townPlaceholder: string;
  cancel: string;
  confirmLocation: string;
}

export interface RegionCategoryHeaders {
  sidoTitle: string;
  gunguTitle: string;
  dongTitle: string;
}

export const REGION_UI_TRANSLATIONS: Record<string, RegionUITexts> = {
  ko: {
    yourLocation: "내 거주 지역 (시·도 / 구·군·시 / 동·읍·면)",
    changeLocation: "지역 변경하기 ▾",
    activeArea: "현재 선택 지역",
    selectLocation: "내 지역 선택",
    selectDescription: "시·도, 구·군·시, 동·읍·면을 차례로 선택해 주세요.",
    sidoCategory: "시·도",
    gunguCategory: "구·군·시",
    dongCategory: "동·읍·면",
    selecting: "선택 중",
    typeTown: "목록에 없는 동/읍 직접 입력",
    townPlaceholder: "예: 중앙동, 어양동",
    cancel: "취소",
    confirmLocation: "이 지역으로 설정하기",
  },
  en: {
    yourLocation: "Your Location in Korea · 내 지역",
    changeLocation: "Change Location · 지역 변경 ▾",
    activeArea: "Active Area · 선택 지역",
    selectLocation: "Select Your Location · 내 지역 선택",
    selectDescription: "Select your Province, City/District, and Town · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Province / Metropolitan City · 시·도",
    gunguCategory: "City / District / County · 구·군·시",
    dongCategory: "Town / Village (Dong/Eup/Myeon) · 동·읍·면",
    selecting: "Selecting... · 선택 중",
    typeTown: "Or type your town · 직접 입력",
    townPlaceholder: "e.g. Sin-dong · 예: 신동",
    cancel: "Cancel · 취소",
    confirmLocation: "Confirm Location · 이 지역으로 설정",
  },
  vi: {
    yourLocation: "Vị trí của bạn tại Hàn Quốc · 내 지역",
    changeLocation: "Thay đổi khu vực · 지역 변경 ▾",
    activeArea: "Khu vực hoạt động · 선택 지역",
    selectLocation: "Chọn vị trí của bạn · 내 지역 선택",
    selectDescription: "Chọn Tỉnh/Thành phố, Quận/Huyện/Thị xã và Phường/Xã · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Tỉnh / Thành phố · 시·도",
    gunguCategory: "Quận / Huyện / Thị xã · 구·군·시",
    dongCategory: "Phường / Xã / Thị trấn · 동·읍·면",
    selecting: "Đang chọn... · 선택 중",
    typeTown: "Hoặc nhập trực tiếp phường/xã · 직접 입력",
    townPlaceholder: "VD: Sin-dong · 예: 신동",
    cancel: "Hủy · 취소",
    confirmLocation: "Xác nhận vị trí này · 이 지역으로 설정",
  },
  "zh-Hans": {
    yourLocation: "您在韩国的位置 · 내 지역",
    changeLocation: "更改地区 · 지역 변경 ▾",
    activeArea: "当前活动区域 · 선택 지역",
    selectLocation: "选择您的地区 · 내 지역 선택",
    selectDescription: "请依次选择省/直辖市、市/郡/区及洞/邑/面 · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "省 / 直辖市 (道/市) · 시·도",
    gunguCategory: "市 / 郡 / 区 · 구·군·시",
    dongCategory: "洞 / 邑 / 面 · 동·읍·면",
    selecting: "选择中... · 선택 중",
    typeTown: "或直接输入洞/邑/面 · 직접 입력",
    townPlaceholder: "例: 新洞 (Sin-dong) · 예: 신동",
    cancel: "取消 · 취소",
    confirmLocation: "设定此地区 · 이 지역으로 설정",
  },
  "zh-Hant": {
    yourLocation: "您在韓國的位置 · 내 지역",
    changeLocation: "變更地區 · 지역 변경 ▾",
    activeArea: "當前活動區域 · 선택 지역",
    selectLocation: "選擇您的地區 · 내 지역 선택",
    selectDescription: "請依序選擇省/直轄市、市/郡/區及洞/邑/面 · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "省 / 直轄市 (道/市) · 시·도",
    gunguCategory: "市 / 郡 / 區 · 구·군·시",
    dongCategory: "洞 / 邑 / 面 · 동·읍·면",
    selecting: "選擇中... · 선택 중",
    typeTown: "或直接輸入洞/邑/面 · 직접 입력",
    townPlaceholder: "例: 新洞 (Sin-dong) · 예: 신동",
    cancel: "取消 · 취소",
    confirmLocation: "設定此地區 · 이 지역으로 설정",
  },
  ja: {
    yourLocation: "韓国内の現在地 · 내 지역",
    changeLocation: "地域を変更 · 지역 변경 ▾",
    activeArea: "選択中の地域 · 선택 지역",
    selectLocation: "お住まいの地域を選択 · 내 지역 선택",
    selectDescription: "広域自治体、市/郡/区、洞/邑/面を順に選択してください · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "広域自治体 (道/市) · 시·도",
    gunguCategory: "市 / 郡 / 区 · 구·군·시",
    dongCategory: "洞 / 邑 / 面 · 동·읍·면",
    selecting: "選択中... · 선택 중",
    typeTown: "または洞/邑/面を直接入力 · 직접 입력",
    townPlaceholder: "例: 新洞 (Sin-dong) · 예: 신동",
    cancel: "キャンセル · 취소",
    confirmLocation: "この地域に設定 · 이 지역으로 설정",
  },
  ru: {
    yourLocation: "Ваше местоположение в Корее · 내 지역",
    changeLocation: "Изменить регион · 지역 변경 ▾",
    activeArea: "Активная зона · 선택 지역",
    selectLocation: "Выберите ваш регион · 내 지역 선택",
    selectDescription: "Выберите провинцию/город, район и квартал · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Провинция / Город · 시·도",
    gunguCategory: "Район / Округ · 구·군·시",
    dongCategory: "Поселок / Квартал · 동·읍·면",
    selecting: "Выбор... · 선택 중",
    typeTown: "Или введите квартал вручную · 직접 입력",
    townPlaceholder: "напр. Синдон · 예: 신동",
    cancel: "Отмена · 취소",
    confirmLocation: "Подтвердить регион · 이 지역으로 설정",
  },
  uk: {
    yourLocation: "Ваше місцезнаходження в Кореї · 내 지역",
    changeLocation: "Змінити регіон · 지역 변경 ▾",
    activeArea: "Активна зона · 선택 지역",
    selectLocation: "Оберіть ваш регіон · 내 지역 선택",
    selectDescription: "Оберіть провінцію/місто, район та квартал · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Провінція / Місто · 시·도",
    gunguCategory: "Район / Округ · 구·군·시",
    dongCategory: "Селище / Квартал · 동·읍·면",
    selecting: "Вибір... · 선택 중",
    typeTown: "Або введіть квартал вручну · 직접 입력",
    townPlaceholder: "напр. Сіндон · 예: 신동",
    cancel: "Скасувати · 취소",
    confirmLocation: "Підтвердити локацію · 이 지역으로 설정",
  },
  kk: {
    yourLocation: "Кореядағы мекенжайыңыз · 내 지역",
    changeLocation: "Аймақты өзгерту · 지역 변경 ▾",
    activeArea: "Белсенді аймақ · 선택 지역",
    selectLocation: "Аймағыңызды таңдаңыз · 내 지역 선택",
    selectDescription: "Облыс/қала, аудан және кентті таңдаңыз · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Провинция / Қала · 시·도",
    gunguCategory: "Ауданы / Округ · 구·군·시",
    dongCategory: "Кент / Ықшамаудан · 동·읍·면",
    selecting: "Таңдалуда... · 선택 중",
    typeTown: "Немесе аймақты өзіңіз жазыңыз · 직접 입력",
    townPlaceholder: "мыс. Синдон · 예: 신동",
    cancel: "Бас тарту · 취소",
    confirmLocation: "Аймақты бекіту · 이 지역으로 설정",
  },
  mn: {
    yourLocation: "Солонгос дахь таны байршил · 내 지역",
    changeLocation: "Байршил өөрчлөх · 지역 변경 ▾",
    activeArea: "Идэвхтэй бүс · 선택 지역",
    selectLocation: "Байршлаа сонгоно уу · 내 지역 선택",
    selectDescription: "Аймаг/хот, дүүрэг, хороогоо дараалан сонгоно уу · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Муж / Хот · 시·도",
    gunguCategory: "Дүүрэг / Бүс · 구·군·시",
    dongCategory: "Хороо / Тосгон · 동·읍·면",
    selecting: "Сонгож байна... · 선택 중",
    typeTown: "Эсвэл хороогоо шууд бичнэ үү · 직접 입력",
    townPlaceholder: "ж нь: Шиндон · 예: 신동",
    cancel: "Цуцлах · 취소",
    confirmLocation: "Байршлыг баталгаажуулах · 이 지역으로 설정",
  },
  uz: {
    yourLocation: "Koreyadagi manzilingiz · 내 지역",
    changeLocation: "Hududni o'zgartirish · 지역 변경 ▾",
    activeArea: "Faol hudud · 선택 지역",
    selectLocation: "Hududingizni tanlang · 내 지역 선택",
    selectDescription: "Viloyat/shahar, tuman va mahallani tanlang · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Viloyat / Shahar · 시·도",
    gunguCategory: "Tuman / Shaharcha · 구·군·시",
    dongCategory: "Mahalla / Qishloq · 동·읍·면",
    selecting: "Tanlanmoqda... · 선택 중",
    typeTown: "Yoki mahallangizni yozing · 직접 입력",
    townPlaceholder: "masalan, Sin-dong · 예: 신동",
    cancel: "Bekor qilish · 취소",
    confirmLocation: "Hududni tasdiqlash · 이 지역으로 설정",
  },
  th: {
    yourLocation: "ตำแหน่งของคุณในเกาหลี · 내 지역",
    changeLocation: "เปลี่ยนพื้นที่ · 지역 변경 ▾",
    activeArea: "พื้นที่ปัจจุบัน · 선택 지역",
    selectLocation: "เลือกพื้นที่ของคุณ · 내 지역 선택",
    selectDescription: "เลือกจังหวัด/มหานคร, เขต/อำเภอ และตำบล/แขวง · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "จังหวัด / มหานคร · 시·도",
    gunguCategory: "เขต / อำเภอ · 구·군·시",
    dongCategory: "ตำบล / แขวง · 동·읍·면",
    selecting: "กำลังเลือก... · 선택 중",
    typeTown: "หรือพิมพ์แขวง/ตำบลโดยตรง · 직접 입력",
    townPlaceholder: "เช่น ชินดง · 예: 신동",
    cancel: "ยกเลิก · 취소",
    confirmLocation: "ยืนยันพื้นที่นี้ · 이 지역으로 설정",
  },
  my: {
    yourLocation: "ကိုရီးယားရှိ သင့်တည်နေရာ · 내 지역",
    changeLocation: "ဒေသပြောင်းရန် · 지역 변경 ▾",
    activeArea: "လက်ရှိဒေသ · 선택 지역",
    selectLocation: "သင့်ဒေသကို ရွေးချယ်ပါ · 내 지역 선택",
    selectDescription: "ပြည်နယ်/မြို့၊ ခရိုင်နှင့် ရပ်ကွက်ကို ရွေးပါ · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "ပြည်နယ် / မြို့တော် · 시·도",
    gunguCategory: "ခရိုင် / မြို့နယ် · 구·군·시",
    dongCategory: "ရပ်ကွက် / ကျေးရွာ · 동·읍·면",
    selecting: "ရွေးချယ်နေသည်... · 선택 중",
    typeTown: "သို့မဟုတ် ရပ်ကွက်တိုက်ရိုက်ရိုက်ထည့်ပါ · 직접 입력",
    townPlaceholder: "ဥပမာ- ဆင်ဒုံ · 예: 신동",
    cancel: "ပယ်ဖျက်မည် · 취소",
    confirmLocation: "ဤတည်နေရာကို အတည်ပြုမည် · 이 지역으로 설정",
  },
  km: {
    yourLocation: "ទីតាំងរបស់អ្នកនៅកូរ៉េ · 내 지역",
    changeLocation: "ផ្លាស់ប្តូរតំបន់ · 지역 변경 ▾",
    activeArea: "តំបន់សកម្ម · 선택 지역",
    selectLocation: "ជ្រើសរើសទីតាំងរបស់អ្នក · 내 지역 선택",
    selectDescription: "ជ្រើសរើសខេត្ត/ក្រុង ស្រុក/ខណ្ឌ និងឃុំ/សង្កាត់ · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "ខេត្ត / ក្រុង · 시·도",
    gunguCategory: "ខណ្ឌ / ស្រុក · 구·군·시",
    dongCategory: "សង្កាត់ / ឃុំ · 동·읍·면",
    selecting: "កំពុងជ្រើសរើស... · 선택 중",
    typeTown: "ឬវាយបញ្ចូលសង្កាត់ដោយផ្ទាល់ · 직접 입력",
    townPlaceholder: "ឧ. ស៊ីនដុង · 예: 신동",
    cancel: "បោះបង់ · 취소",
    confirmLocation: "បញ្ជាក់ទីតាំងនេះ · 이 지역으로 설정",
  },
  hi: {
    yourLocation: "कोरिया में आपका स्थान · 내 지역",
    changeLocation: "स्थान बदलें · 지역 변경 ▾",
    activeArea: "सक्रिय क्षेत्र · 선택 지역",
    selectLocation: "अपना स्थान चुनें · 내 지역 선택",
    selectDescription: "प्रांत/शहर, जिला और इलाका चुनें · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "प्रांत / महानगर · 시·도",
    gunguCategory: "शहर / जिला / काउंटी · 구·군·시",
    dongCategory: "कस्बा / मोहल्ला · 동·읍·면",
    selecting: "चयन किया जा रहा है... · 선택 중",
    typeTown: "या अपना मोहल्ला सीधे टाइप करें · 직접 입력",
    townPlaceholder: "उदा. सिन-डोंग · 예: 신동",
    cancel: "रद्द करें · 취소",
    confirmLocation: "स्थान की पुष्टि करें · 이 지역으로 설정",
  },
  ne: {
    yourLocation: "कोरियामा तपाईंको स्थान · 내 지역",
    changeLocation: "स्थान परिवर्तन गर्नुहोस् · 지역 변경 ▾",
    activeArea: "सक्रिय क्षेत्र · 선택 지역",
    selectLocation: "तपाईंको स्थान चयन गर्नुहोस् · 내 지역 선택",
    selectDescription: "प्रदेश/शहर, जिल्ला र टोल चयन गर्नुहोस् · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "प्रदेश / महानगर · 시·도",
    gunguCategory: "शहर / जिल्ला · 구·군·시",
    dongCategory: "टोल / गाउँ · 동·읍·면",
    selecting: "चयन गर्दै... · 선택 중",
    typeTown: "वा आफ्नो टोल सिधै टाइप गर्नुहोस् · 직접 입력",
    townPlaceholder: "जस्तै: सिन-डोङ · 예: 신동",
    cancel: "रद्द गर्नुहोस् · 취소",
    confirmLocation: "स्थान पुष्टि गर्नुहोस् · 이 지역으로 설정",
  },
  bn: {
    yourLocation: "কোরিয়ায় আপনার অবস্থান · 내 지역",
    changeLocation: "এলাকা পরিবর্তন করুন · 지역 변경 ▾",
    activeArea: "বর্তমান এলাকা · 선택 지역",
    selectLocation: "আপনার এলাকা নির্বাচন করুন · 내 지역 선택",
    selectDescription: "প্রদেশ/মহানগর, জেলা এবং এলাকা নির্বাচন করুন · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "প্রদেশ / মহানগর · 시·도",
    gunguCategory: "শহর / জেলা · 구·군·시",
    dongCategory: "এলাকা / গ্রাম · 동·읍·면",
    selecting: "নির্বাচন করা হচ্ছে... · 선택 중",
    typeTown: "অথবা সরাসরি আপনার এলাকা লিখুন · 직접 입력",
    townPlaceholder: "উদা: শিন-দং · 예: 신동",
    cancel: "বাতিল · 취소",
    confirmLocation: "অবস্থান নিশ্চিত করুন · 이 지역으로 설정",
  },
  ta: {
    yourLocation: "கொரியாவில் உங்கள் இருப்பிடம் · 내 지역",
    changeLocation: "இருப்பிடத்தை மாற்று · 지역 변경 ▾",
    activeArea: "செயலில் உள்ள பகுதி · 선택 지역",
    selectLocation: "உங்கள் இருப்பிடத்தைத் தேர்ந்தெடுக்கவும் · 내 지역 선택",
    selectDescription: "மாகாணம்/நகரம், மாவட்டம் மற்றும் பகுதியைத் தேர்ந்தெடுக்கவும் · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "மாகாணம் / பெருநகரம் · 시·도",
    gunguCategory: "நகரம் / மாவட்டம் · 구·군·시",
    dongCategory: "கிராமம் / பகுதி · 동·읍·면",
    selecting: "தேர்ந்தெடுக்கிறது... · 선택 중",
    typeTown: "அல்லது உங்கள் பகுதியை நேரடியாக உள்ளிடவும் · 직접 입력",
    townPlaceholder: "எ.கா: சின்-டாங் · 예: 신동",
    cancel: "ரத்து செய் · 취소",
    confirmLocation: "இருப்பிடத்தை உறுதிப்படுத்து · 이 지역으로 설정",
  },
  si: {
    yourLocation: "කොරියාවේ ඔබගේ ස්ථානය · 내 지역",
    changeLocation: "ප්‍රදේශය වෙනස් කරන්න · 지역 변경 ▾",
    activeArea: "ක්‍රියාකාරී ප්‍රදේශය · 선택 지역",
    selectLocation: "ඔබගේ ප්‍රදේශය තෝරන්න · 내 지역 선택",
    selectDescription: "පළාත/නගරය, දිස්ත්‍රික්කය සහ ගම තෝරන්න · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "පළාත / මහා නගරය · 시·도",
    gunguCategory: "නගරය / දිස්ත්‍රික්කය · 구·군·시",
    dongCategory: "ගම / කොට්ඨාසය · 동·읍·면",
    selecting: "තෝරමින් පවතී... · 선택 중",
    typeTown: "හෝ ඔබගේ ගම සෘජුවම ලියන්න · 직접 입력",
    townPlaceholder: "උදා: සින්-ඩොං · 예: 신동",
    cancel: "අවලංගු කරන්න · 취소",
    confirmLocation: "ස්ථානය තහවුරු කරන්න · 이 지역으로 설정",
  },
  ar: {
    yourLocation: "موقعك في كوريا · 내 지역",
    changeLocation: "تغيير المنطقة · 지역 변경 ▾",
    activeArea: "المنطقة الحالية · 선택 지역",
    selectLocation: "اختر منطقتك · 내 지역 선택",
    selectDescription: "يرجى اختيار المقاطعة/المدينة، المنطقة والحي · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "مقاطعة / مدينة كبرى · 시·도",
    gunguCategory: "مدينة / مقاطعة / حي · 구·군·시",
    dongCategory: "بلدة / قرية · 동·읍·면",
    selecting: "جارٍ الاختيار... · 선택 중",
    typeTown: "أو اكتب الحي مباشرة · 직접 입력",
    townPlaceholder: "مثال: سين-دونغ · 예: 신동",
    cancel: "إلغاء · 취소",
    confirmLocation: "تأكيد الموقع · 이 지역으로 설정",
  },
  arz: {
    yourLocation: "مكانك في كوريا · 내 지역",
    changeLocation: "تغيير المكان · 지역 변경 ▾",
    activeArea: "المنطقة الشغالة · 선택 지역",
    selectLocation: "اختار مكانك · 내 지역 선택",
    selectDescription: "اختار المحافظة/المدينة والحي · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "محافظة / مدينة كبرى · 시·도",
    gunguCategory: "قسم / منطقة · 구·군·시",
    dongCategory: "حي / قرية · 동·읍·면",
    selecting: "بيختار... · 선택 중",
    typeTown: "أو اكتب حيك على طول · 직접 입력",
    townPlaceholder: "مثلاً: سين-دونغ · 예: 신동",
    cancel: "إلغاء · 취소",
    confirmLocation: "تأكيد المكان · 이 지역으로 설정",
  },
  fa: {
    yourLocation: "موقعیت شما در کره · 내 지역",
    changeLocation: "تغییر منطقه · 지역 변경 ▾",
    activeArea: "منطقه فعال · 선택 지역",
    selectLocation: "منطقه خود را انتخاب کنید · 내 지역 선택",
    selectDescription: "استان/شهر، ناحیه و محله را انتخاب کنید · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "استان / کلان‌شهر · 시·도",
    gunguCategory: "شهر / شهرستان / بخش · 구·군·시",
    dongCategory: "محله / دهستان · 동·읍·면",
    selecting: "در حال انتخاب... · 선택 중",
    typeTown: "یا نام محله را بنویسید · 직접 입력",
    townPlaceholder: "مثال: شین-دونگ · 예: 신동",
    cancel: "لغو · 취소",
    confirmLocation: "تأیید موقعیت · 이 지역으로 설정",
  },
  he: {
    yourLocation: "המיקום שלך בקוריאה · 내 지역",
    changeLocation: "שנה אזור · 지역 변경 ▾",
    activeArea: "אזור פעיל · 선택 지역",
    selectLocation: "בחר את האזור שלך · 내 지역 선택",
    selectDescription: "בחר מחוז/עיר, נפה ושכונה · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "מחוז / מטרופולין · 시·도",
    gunguCategory: "עיר / נפה / מחוז · 구·군·시",
    dongCategory: "שכונה / עיירה · 동·읍·면",
    selecting: "בוחר... · 선택 중",
    typeTown: "או הקלד את שם השכונה · 직접 입력",
    townPlaceholder: "לדוגמה: סין-דונג · 예: 신동",
    cancel: "ביטול · 취소",
    confirmLocation: "אשר מיקום זה · 이 지역으로 설정",
  },
  am: {
    yourLocation: "በኮሪያ ውስጥ ያለዎት ቦታ · 내 지역",
    changeLocation: "አካባቢ ቀይር · 지역 변경 ▾",
    activeArea: "ንቁ አካባቢ · 선택 지역",
    selectLocation: "አካባቢዎን ይምረጡ · 내 지역 선택",
    selectDescription: "ግዛት/ከተማ፣ ወረዳ እና መንደር ይምረጡ · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "ግዛት / ዋና ከተማ · 시·도",
    gunguCategory: "ከተማ / ወረዳ · 구·군·시",
    dongCategory: "መንደር / ሰፈር · 동·읍·면",
    selecting: "በመምረጥ ላይ... · 선택 중",
    typeTown: "ወይም ሰፈርዎን በቀጥታ ያስገቡ · 직접 입력",
    townPlaceholder: "ምሳሌ፡ ሲን-ዶንግ · 예: 신동",
    cancel: "ሰርዝ · 취소",
    confirmLocation: "ቦታውን አረጋግጥ · 이 지역으로 설정",
  },
  fr: {
    yourLocation: "Votre localisation en Corée · 내 지역",
    changeLocation: "Changer de région · 지역 변경 ▾",
    activeArea: "Zone active · 선택 지역",
    selectLocation: "Sélectionnez votre région · 내 지역 선택",
    selectDescription: "Sélectionnez la province, la ville/district et le quartier · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Province / Métropole · 시·도",
    gunguCategory: "Ville / Arrondissement / District · 구·군·시",
    dongCategory: "Quartier / Commune · 동·읍·면",
    selecting: "Sélection... · 선택 중",
    typeTown: "Ou entrez directement votre quartier · 직접 입력",
    townPlaceholder: "ex. Sin-dong · 예: 신동",
    cancel: "Annuler · 취소",
    confirmLocation: "Confirmer cette localisation · 이 지역으로 설정",
  },
  de: {
    yourLocation: "Ihr Standort in Korea · 내 지역",
    changeLocation: "Region ändern · 지역 변경 ▾",
    activeArea: "Aktiver Bereich · 선택 지역",
    selectLocation: "Wählen Sie Ihren Standort · 내 지역 선택",
    selectDescription: "Wählen Sie Provinz, Stadt/Kreis und Stadtteil · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provinz / Großstadt · 시·도",
    gunguCategory: "Stadtkreis / Bezirk / Landkreis · 구·군·시",
    dongCategory: "Stadtteil / Gemeinde · 동·읍·면",
    selecting: "Auswahl läuft... · 선택 중",
    typeTown: "Oder Stadtteil direkt eingeben · 직접 입력",
    townPlaceholder: "z.B. Sin-dong · 예: 신동",
    cancel: "Abbrechen · 취소",
    confirmLocation: "Standort bestätigen · 이 지역으로 설정",
  },
  es: {
    yourLocation: "Tu ubicación en Corea · 내 지역",
    changeLocation: "Cambiar región · 지역 변경 ▾",
    activeArea: "Área activa · 선택 지역",
    selectLocation: "Selecciona tu ubicación · 내 지역 선택",
    selectDescription: "Selecciona provincia, ciudad/distrito y barrio · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provincia / Metrópoli · 시·도",
    gunguCategory: "Ciudad / Distrito / Condado · 구·군·시",
    dongCategory: "Barrio / Municipio · 동·읍·면",
    selecting: "Seleccionando... · 선택 중",
    typeTown: "O escribe tu barrio directamente · 직접 입력",
    townPlaceholder: "ej. Sin-dong · 예: 신동",
    cancel: "Cancelar · 취소",
    confirmLocation: "Confirmar ubicación · 이 지역으로 설정",
  },
  it: {
    yourLocation: "La tua posizione in Corea · 내 지역",
    changeLocation: "Cambia regione · 지역 변경 ▾",
    activeArea: "Area attiva · 선택 지역",
    selectLocation: "Seleziona la tua posizione · 내 지역 선택",
    selectDescription: "Seleziona provincia, città/distretto e quartiere · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provincia / Città metropolitana · 시·도",
    gunguCategory: "Città / Distretto / Contea · 구·군·시",
    dongCategory: "Quartiere / Comune · 동·읍·면",
    selecting: "Selezione in corso... · 선택 중",
    typeTown: "Oppure inserisci il quartiere · 직접 입력",
    townPlaceholder: "es. Sin-dong · 예: 신동",
    cancel: "Annulla · 취소",
    confirmLocation: "Conferma posizione · 이 지역으로 설정",
  },
  nl: {
    yourLocation: "Uw locatie in Korea · 내 지역",
    changeLocation: "Regio wijzigen · 지역 변경 ▾",
    activeArea: "Actief gebied · 선택 지역",
    selectLocation: "Selecteer uw locatie · 내 지역 선택",
    selectDescription: "Selecteer provincie, stad/district en wijk · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provincie / Metropool · 시·도",
    gunguCategory: "Stad / District / Gemeente · 구·군·시",
    dongCategory: "Wijk / Dorp · 동·읍·면",
    selecting: "Selecteren... · 선택 중",
    typeTown: "Of voer wijk rechtstreeks in · 직접 입력",
    townPlaceholder: "bijv. Sin-dong · 예: 신동",
    cancel: "Annuleren · 취소",
    confirmLocation: "Locatie bevestigen · 이 지역으로 설정",
  },
  pl: {
    yourLocation: "Twoja lokalizacja w Korei · 내 지역",
    changeLocation: "Zmień region · 지역 변경 ▾",
    activeArea: "Aktywny obszar · 선택 지역",
    selectLocation: "Wybierz swoją lokalizację · 내 지역 선택",
    selectDescription: "Wybierz prowincję, miasto/powiat i dzielnicę · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Prowincja / Metropolia · 시·도",
    gunguCategory: "Miasto / Dzielnica / Powiat · 구·군·시",
    dongCategory: "Dzielnica / Miejscowość · 동·읍·면",
    selecting: "Wybieranie... · 선택 중",
    typeTown: "Lub wpisz dzielnicę bezpośrednio · 직접 입력",
    townPlaceholder: "np. Sin-dong · 예: 신동",
    cancel: "Anuluj · 취소",
    confirmLocation: "Zatwierdź lokalizację · 이 지역으로 설정",
  },
  sv: {
    yourLocation: "Din plats i Korea · 내 지역",
    changeLocation: "Ändra plats · 지역 변경 ▾",
    activeArea: "Aktivt område · 선택 지역",
    selectLocation: "Välj din plats · 내 지역 선택",
    selectDescription: "Välj provins, stad/distrikt och stadsdel · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provins / Storstad · 시·도",
    gunguCategory: "Stad / Distrikt / Kommun · 구·군·시",
    dongCategory: "Stadsdel / By · 동·읍·면",
    selecting: "Väljer... · 선택 중",
    typeTown: "Eller ange stadsdel direkt · 직접 입력",
    townPlaceholder: "t.ex. Sin-dong · 예: 신동",
    cancel: "Avbryt · 취소",
    confirmLocation: "Bekräfta plats · 이 지역으로 설정",
  },
  da: {
    yourLocation: "Din placering i Korea · 내 지역",
    changeLocation: "Skift område · 지역 변경 ▾",
    activeArea: "Aktivt område · 선택 지역",
    selectLocation: "Vælg din placering · 내 지역 선택",
    selectDescription: "Vælg provins, by/distrikt og bydel · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provins / Storby · 시·도",
    gunguCategory: "By / Distrikt / Amt · 구·군·시",
    dongCategory: "Bydel / Landsby · 동·읍·면",
    selecting: "Vælger... · 선택 중",
    typeTown: "Eller indtast bydel direkte · 직접 입력",
    townPlaceholder: "f.eks. Sin-dong · 예: 신동",
    cancel: "Annuller · 취소",
    confirmLocation: "Bekræft placering · 이 지역으로 설정",
  },
  no: {
    yourLocation: "Din plassering i Korea · 내 지역",
    changeLocation: "Endre region · 지역 변경 ▾",
    activeArea: "Aktivt område · 선택 지역",
    selectLocation: "Velg din plassering · 내 지역 선택",
    selectDescription: "Velg fylke/by, distrikt og bydel · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Fylke / Storby · 시·도",
    gunguCategory: "By / Distrikt / Kommune · 구·군·시",
    dongCategory: "Bydel / Tettsted · 동·읍·면",
    selecting: "Velger... · 선택 중",
    typeTown: "Eller skriv inn bydel direkte · 직접 입력",
    townPlaceholder: "f.eks. Sin-dong · 예: 신동",
    cancel: "Avbryt · 취소",
    confirmLocation: "Bekreft plassering · 이 지역으로 설정",
  },
  tr: {
    yourLocation: "Kore'deki Konumunuz · 내 지역",
    changeLocation: "Bölgeyi Değiştir · 지역 변경 ▾",
    activeArea: "Aktif Bölge · 선택 지역",
    selectLocation: "Konumunuzu Seçin · 내 지역 선택",
    selectDescription: "İl/Büyükşehir, İlçe ve Mahallenizi seçin · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "İl / Büyükşehir · 시·도",
    gunguCategory: "Şehir / İlçe · 구·군·시",
    dongCategory: "Mahalle / Köy · 동·읍·면",
    selecting: "Seçiliyor... · 선택 중",
    typeTown: "Veya mahalleyi doğrudan yazın · 직접 입력",
    townPlaceholder: "ör. Sin-dong · 예: 신동",
    cancel: "İptal · 취소",
    confirmLocation: "Konumu Onayla · 이 지역으로 설정",
  },
  tet: {
    yourLocation: "Ita-nia Fatin iha Koreia · 내 지역",
    changeLocation: "Muda Fatin · 지역 변경 ▾",
    activeArea: "Área Ativu · 선택 지역",
    selectLocation: "Hili Ita-nia Fatin · 내 지역 선택",
    selectDescription: "Hili Provínsia, Sidade/Distritu no Suku · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provínsia / Sidade Boot · 시·도",
    gunguCategory: "Sidade / Distritu · 구·군·시",
    dongCategory: "Suku / Aldeia · 동·읍·면",
    selecting: "Hili daudaun... · 선택 중",
    typeTown: "Ka hakerek suku rasik · 직접 입력",
    townPlaceholder: "ez. Sin-dong · 예: 신동",
    cancel: "Kansela · 취소",
    confirmLocation: "Konfirma Fatin · 이 지역으로 설정",
  },
  id: {
    yourLocation: "Lokasi Anda di Korea · 내 지역",
    changeLocation: "Ubah Wilayah · 지역 변경 ▾",
    activeArea: "Wilayah Aktif · 선택 지역",
    selectLocation: "Pilih Lokasi Anda · 내 지역 선택",
    selectDescription: "Pilih Provinsi/Kota, Distrik/Kabupaten dan Kelurahan · 시·도/구·군·시/동·읍·면 선택",
    sidoCategory: "Provinsi / Kota Metropolitan · 시·도",
    gunguCategory: "Kota / Distrik / Kabupaten · 구·군·시",
    dongCategory: "Kelurahan / Desa · 동·읍·면",
    selecting: "Memilih... · 선택 중",
    typeTown: "Atau ketik kelurahan langsung · 직접 입력",
    townPlaceholder: "contoh: Sin-dong · 예: 신동",
    cancel: "Batal · 취소",
    confirmLocation: "Konfirmasi Lokasi · 이 지역으로 설정",
  },
};

export function getRegionUIText(key: keyof RegionUITexts, locale: string): string {
  const texts = REGION_UI_TRANSLATIONS[locale] || REGION_UI_TRANSLATIONS["en"];
  return texts[key] || REGION_UI_TRANSLATIONS["en"][key];
}

export function getRegionCategoryHeaders(locale: string): RegionCategoryHeaders {
  const texts = REGION_UI_TRANSLATIONS[locale] || REGION_UI_TRANSLATIONS["en"];
  return {
    sidoTitle: `1. ${texts.sidoCategory}`,
    gunguTitle: `2. ${texts.gunguCategory}`,
    dongTitle: `3. ${texts.dongCategory}`,
  };
}

