import { T, tex, ONE, DEC, won, round, join } from "../util.mjs";

const F = (steps, abstraction, context, novelty, recall, distractor, numberSize) => ({ steps, abstraction, context, novelty, recall, distractor, numberSize });
const C = (n, k) => { if (k < 0 || k > n) return 0; let r = 1; for (let i = 1; i <= k; i++) r = (r * (n - k + i)) / i; return Math.round(r); };
const lin = (a, b) => `${a === 1 ? "" : a === -1 ? "-" : a}x${b === 0 ? "" : b > 0 ? `+${b}` : b}`;

/* ------------------------------------------------------------------ 9. solving equations */
const algebra = {
  id: "algebra-solve", short: "alg", cognitive: "PROCEDURE", levels: [5, 9], title: T("방정식 풀이", "Giải phương trình"),
  make(rand, level) {
    if (level <= 5) {
      const x = rand.int(-6, 9), a = rand.int(3, 9), c = rand.int(1, a - 1), b = rand.int(-9, 9), d = (a - c) * x + b;
      return { type: "numeric", prompt: join(T(`방정식 ${tex(`${lin(a, b)}=${lin(c, d)}`)} 의 해를 구하세요.`, `Giải phương trình ${tex(`${lin(a, b)}=${lin(c, d)}`)}.`), ONE), value: x, hints: [T("x가 들어간 항을 한쪽으로 모아요.", "Gom các số hạng chứa x về một vế."), T("옮길 때 부호가 바뀌는 것에 주의해요.", "Chú ý đổi dấu khi chuyển vế.")], expl: T(`${a - c}x = ${d - b} 이므로 x = ${x}`, `${a - c}x = ${d - b} nên x = ${x}`), tags: ["numbers"], features: F(3, 3, 0, 0, 0, 0, 1), verify: () => a * x + b === c * x + d };
    }
    if (level === 6) {
      const x = rand.int(-4, 6), y = rand.int(-4, 6), a1 = rand.int(1, 4), b1 = rand.int(1, 4), a2 = rand.int(1, 4), b2 = -rand.int(1, 4);
      if (a1 * b2 - a2 * b1 === 0) return algebra.make(rand, level);
      const c1 = a1 * x + b1 * y, c2 = a2 * x + b2 * y, value = x - y;
      const t = (a, b) => `${a}x${b < 0 ? "-" : "+"}${Math.abs(b)}y`;
      return { type: "numeric", prompt: join(T(`연립방정식 ${tex(`${t(a1, b1)}=${c1}`)}, ${tex(`${t(a2, b2)}=${c2}`)} 의 해를 (x, y)라 할 때 x − y의 값은?`, `Hệ phương trình ${tex(`${t(a1, b1)}=${c1}`)}, ${tex(`${t(a2, b2)}=${c2}`)} có nghiệm (x, y). Giá trị của x − y là?`), ONE), value, hints: [T("한 문자를 없애도록 두 식을 더하거나 빼요.", "Cộng hoặc trừ hai phương trình để khử một ẩn."), T("x, y를 모두 구한 뒤 x − y를 계산해요.", "Tìm cả x và y rồi mới tính x − y.")], expl: T(`해는 x=${x}, y=${y} 이므로 x − y = ${value}`, `Nghiệm là x=${x}, y=${y} nên x − y = ${value}`), tags: ["multistep"], features: F(4, 3, 0, 1, 0, 0, 1), verify: () => a1 * x + b1 * y === c1 && a2 * x + b2 * y === c2 };
    }
    if (level === 7) {
      const r1 = rand.int(-5, 6), r2 = rand.int(-5, 6);
      if (r1 === r2) return algebra.make(rand, level);
      const s = r1 + r2, p = r1 * r2, wantSq = rand.chance(0.5), value = wantSq ? r1 * r1 + r2 * r2 : Math.max(r1, r2);
      const eq = `x^2${s === 0 ? "" : `${-s > 0 ? "+" : "-"}${Math.abs(s)}x`}${p === 0 ? "" : `${p > 0 ? "+" : "-"}${Math.abs(p)}`}=0`;
      return { type: "numeric", prompt: join(T(`이차방정식 ${tex(eq)} 의 두 근에 대하여 ${wantSq ? "두 근의 제곱의 합" : "더 큰 근"}을(를) 구하세요.`, `Với hai nghiệm của phương trình ${tex(eq)}, hãy tìm ${wantSq ? "tổng bình phương hai nghiệm" : "nghiệm lớn hơn"}.`), ONE), value, hints: [T("인수분해로 두 근을 먼저 구해요.", "Phân tích thành nhân tử để tìm hai nghiệm trước."), T(wantSq ? "근을 각각 제곱해서 더해요." : "두 근을 비교해요.", wantSq ? "Bình phương từng nghiệm rồi cộng." : "So sánh hai nghiệm.")], expl: T(`근은 ${r1}, ${r2} → ${wantSq ? `${r1 * r1} + ${r2 * r2} = ${value}` : value}`, `Nghiệm là ${r1}, ${r2} → ${wantSq ? `${r1 * r1} + ${r2 * r2} = ${value}` : value}`), tags: ["multistep"], features: F(3, 4, 0, 1, 0, 0, 1), verify: () => r1 * r1 - s * r1 + p === 0 && r2 * r2 - s * r2 + p === 0 };
    }
    if (level === 8) {
      const a = rand.int(2, 5), b = rand.int(-6, 6), cc = rand.int(2, 9) * a, value = round(-2 * b / a, 3);
      return { type: "numeric", prompt: join(T(`방정식 ${tex(`|${lin(a, b)}|=${cc}`)} 의 모든 해의 합을 구하세요.`, `Tìm tổng tất cả nghiệm của phương trình ${tex(`|${lin(a, b)}|=${cc}`)}.`), DEC), value, tol: 0.01, hints: [T("절댓값 안의 식이 +c 또는 −c인 두 경우로 나눠요.", "Chia hai trường hợp: biểu thức trong dấu giá trị tuyệt đối bằng +c hoặc −c."), T("두 해를 각각 구한 뒤 더해요.", "Tìm hai nghiệm rồi cộng lại.")], expl: T(`${a}x+${b} = ${cc} 또는 ${-cc} → x = ${round((cc - b) / a, 3)}, ${round((-cc - b) / a, 3)}, 합 ${value}`, `${a}x+${b} = ${cc} hoặc ${-cc} → x = ${round((cc - b) / a, 3)}, ${round((-cc - b) / a, 3)}, tổng ${value}`), tags: ["reasoning"], features: F(3, 4, 0, 2, 0, 1, 1), verify: () => Math.abs(Math.abs(a * ((cc - b) / a) + b) - cc) < 1e-9 };
    }
    const bb = rand.int(2, 5), k = rand.int(2, 4), r1 = bb + k, r2 = bb + 1 - k, aa = bb * bb - r1 * r2;
    return { type: "numeric", prompt: join(T(`방정식 ${tex(`\\sqrt{x+${aa}}=x-${bb}`)} 을 만족하는 실수 x를 구하세요. (양변을 제곱하면 답이 아닌 값이 생길 수 있습니다)`, `Tìm số thực x thỏa mãn ${tex(`\\sqrt{x+${aa}}=x-${bb}`)}. (Bình phương hai vế có thể sinh nghiệm ngoại lai.)`), ONE), value: r1, hints: [T("양변을 제곱해 이차방정식을 풀되, 얻은 해를 처음 식에 꼭 다시 넣어 보세요.", "Bình phương hai vế để giải phương trình bậc hai, nhưng phải thay nghiệm vào phương trình ban đầu để kiểm tra."), T("제곱근은 0 이상이므로 x − " + bb + " ≥ 0 이어야 해요.", "Căn bậc hai không âm nên cần x − " + bb + " ≥ 0.")], expl: T(`제곱하면 x = ${r1} 또는 ${r2}. x − ${bb} ≥ 0 이므로 ${r2}는 버리고 x = ${r1}.`, `Bình phương cho x = ${r1} hoặc ${r2}. Vì x − ${bb} ≥ 0 nên loại ${r2}, x = ${r1}.`), tags: ["reasoning", "multistep"], features: F(4, 4, 0, 3, 0, 2, 1), verify: () => Math.abs(Math.sqrt(r1 + aa) - (r1 - bb)) < 1e-9 && Math.abs(Math.sqrt(Math.max(0, r2 + aa)) - (r2 - bb)) > 1e-9 };
  },
};

/* ------------------------------------------------------------------ 10. counting and probability */
const probability = {
  id: "counting-probability", short: "prob", cognitive: "ANALYZE", levels: [5, 10], title: T("경우의 수와 확률", "Đếm và xác suất"),
  make(rand, level) {
    if (level <= 5) { const s = rand.int(4, 10); let ways = 0; for (let i = 1; i <= 6; i++) for (let j = 1; j <= 6; j++) if (i + j === s) ways++; return { type: "numeric", prompt: join(T(`서로 다른 두 주사위를 던질 때 눈의 합이 ${s}인 경우는 모두 몇 가지인가요?`, `Tung hai con xúc xắc khác nhau, có bao nhiêu trường hợp tổng số chấm bằng ${s}?`), ONE), value: ways, hints: [T("(첫째 눈, 둘째 눈)의 순서쌍으로 빠짐없이 적어 보세요.", "Liệt kê đầy đủ các cặp (mặt thứ nhất, mặt thứ hai)."), T("합이 같아도 순서가 다르면 다른 경우예요.", "Cùng tổng nhưng khác thứ tự là trường hợp khác nhau.")], expl: T(`합이 ${s}인 순서쌍은 ${ways}개`, `Có ${ways} cặp có tổng ${s}`), tags: ["reasoning"], features: F(2, 1, 1, 1, 0, 0, 0), verify: () => ways > 0 }; }
    if (level === 6) { const n = rand.int(6, 9), k = rand.int(2, 4), value = C(n - 1, k - 1); const who = "Mina"; return { type: "numeric", prompt: join(T(`학생 ${n}명 중에서 ${k}명의 대표를 뽑으려고 합니다. ${who} 학생이 반드시 포함되는 뽑는 방법은 모두 몇 가지인가요?`, `Chọn ${k} đại diện trong ${n} học sinh. Có bao nhiêu cách chọn sao cho bạn ${who} chắc chắn được chọn?`), ONE), value, hints: [T("한 명이 이미 정해졌으니 나머지 자리만 생각해요.", "Một bạn đã được chọn nên chỉ xét các vị trí còn lại."), T("순서가 없으므로 조합이에요.", "Không tính thứ tự nên đây là tổ hợp.")], expl: T(`나머지 ${n - 1}명 중 ${k - 1}명을 고르는 방법: ${value}`, `Chọn ${k - 1} trong ${n - 1} bạn còn lại: ${value}`), tags: ["reasoning", "context"], features: F(3, 2, 2, 2, 0, 1, 1), verify: () => value === C(n - 1, k - 1) }; }
    if (level === 7) { const boys = rand.int(3, 5), girls = rand.int(3, 5), k = rand.int(3, 4), value = C(boys + girls, k) - C(boys, k); return { type: "numeric", prompt: join(T(`남학생 ${boys}명, 여학생 ${girls}명 중에서 ${k}명을 뽑을 때, 여학생이 적어도 1명 포함되도록 뽑는 방법은 모두 몇 가지인가요?`, `Chọn ${k} bạn trong ${boys} nam và ${girls} nữ sao cho có ít nhất 1 nữ. Có bao nhiêu cách?`), ONE), value, hints: [T("‘적어도 1명’은 전체에서 ‘한 명도 없는 경우’를 빼면 쉬워요.", "‘Ít nhất 1’ dễ hơn nếu lấy tổng trừ trường hợp ‘không có’."), T("한 명도 없는 경우는 모두 남학생만 뽑는 경우예요.", "Trường hợp không có nữ là chỉ chọn nam.")], expl: T(`${C(boys + girls, k)} − ${C(boys, k)} = ${value}`, `${C(boys + girls, k)} − ${C(boys, k)} = ${value}`), tags: ["reasoning"], features: F(3, 2, 2, 2, 0, 1, 1), verify: () => value > 0 }; }
    if (level === 8) { const a = rand.int(8, 20), b = rand.int(6, 18), c = rand.int(5, 15), d = rand.int(10, 25), value = round(a / (a + b), 4); return { type: "numeric", prompt: join(T(`한 학교 동아리 신청 현황입니다. 여학생: 신청 ${a}명, 미신청 ${b}명 / 남학생: 신청 ${c}명, 미신청 ${d}명. 여학생 한 명을 무작위로 뽑았을 때 동아리를 신청했을 확률은?`, `Tình hình đăng ký câu lạc bộ: nữ: đã đăng ký ${a}, chưa ${b} / nam: đã đăng ký ${c}, chưa ${d}. Chọn ngẫu nhiên một bạn nữ, xác suất bạn đó đã đăng ký là bao nhiêu?`), DEC), value, tol: 0.005, hints: [T("전체가 아니라 ‘여학생’만이 기준이에요.", "Cơ sở là ‘các bạn nữ’ chứ không phải tất cả."), T("확률 = (여학생 중 신청) ÷ (여학생 전체)", "Xác suất = (nữ đã đăng ký) ÷ (tổng số nữ)")], expl: T(`${a} ÷ (${a} + ${b}) = ${value}`, `${a} ÷ (${a} + ${b}) = ${value}`), tags: ["reasoning", "context"], features: F(3, 2, 3, 2, 0, 2, 2), verify: () => a + b > 0 && c + d > 0 }; }
    if (level === 9) { const prizes = rand.pick([[0, 0, 0, 1000, 2000, 3000], [0, 0, 500, 500, 1500, 3500], [0, 0, 0, 0, 1200, 3600]]), cost = rand.pick([500, 800, 1000]); const ev = round(prizes.reduce((a, b) => a + b, 0) / 6 - cost, 2); return { type: "numeric", prompt: join(T(`참가비 ${won(cost)}원을 내고 주사위를 한 번 굴려, 눈이 1, 2, 3, 4, 5, 6일 때 각각 ${prizes.map(won).join(", ")}원을 받는 게임이 있습니다. 한 번 할 때 기대되는 순이익(받는 돈 − 참가비)은 몇 원인가요?`, `Trò chơi: trả ${won(cost)} won rồi tung một con xúc xắc; ra mặt 1, 2, 3, 4, 5, 6 thì lần lượt nhận ${prizes.map(won).join(", ")} won. Lợi nhuận kỳ vọng mỗi lần chơi (tiền nhận − phí tham gia) là bao nhiêu won?`), DEC), value: ev, tol: 0.5, hints: [T("각 결과의 상금 × 확률을 모두 더해요(기댓값).", "Cộng (tiền thưởng × xác suất) của mọi kết quả (kỳ vọng)."), T("참가비를 마지막에 빼요.", "Cuối cùng trừ phí tham gia.")], expl: T(`기댓값 ${round(prizes.reduce((a, b) => a + b, 0) / 6, 2)} − ${cost} = ${ev}원`, `Kỳ vọng ${round(prizes.reduce((a, b) => a + b, 0) / 6, 2)} − ${cost} = ${ev} won`), tags: ["reasoning", "multistep"], features: F(4, 3, 3, 3, 0, 1, 3), verify: () => Math.abs(ev - (prizes.reduce((a, b) => a + b, 0) / 6 - cost)) < 0.01 }; }
    const red = rand.int(3, 6), white = rand.int(3, 6), n = red + white; let hit = 0, all = 0;
    for (let a = 0; a < n; a++) for (let b = 0; b < n; b++) for (let c2 = 0; c2 < n; c2++) { if (a === b || b === c2 || a === c2) continue; all++; const rc = [a, b, c2].filter((i) => i < red).length; if (rc === 2) hit++; }
    const value = round(hit / all, 4);
    return { type: "numeric", prompt: join(T(`주머니에 빨간 공 ${red}개와 흰 공 ${white}개가 있습니다. 공을 한 개씩 3번 꺼낼 때(꺼낸 공은 다시 넣지 않음) 빨간 공이 정확히 2개 나올 확률은?`, `Túi có ${red} bóng đỏ và ${white} bóng trắng. Lấy lần lượt 3 quả (không hoàn lại), xác suất có đúng 2 quả đỏ là bao nhiêu?`), DEC), value, tol: 0.005, hints: [T("‘어느 순서로 나오든’ 경우를 모두 세어야 해요(조합으로 한 번에).", "Phải đếm mọi thứ tự có thể (dùng tổ hợp cho gọn)."), T("확률 = (빨강 2, 흰 1을 뽑는 방법) ÷ (3개를 뽑는 모든 방법)", "Xác suất = (số cách chọn 2 đỏ, 1 trắng) ÷ (số cách chọn 3 quả bất kỳ)")], expl: T(`${C(red, 2)} × ${white} ÷ ${C(n, 3)} = ${value}`, `${C(red, 2)} × ${white} ÷ ${C(n, 3)} = ${value}`), tags: ["reasoning", "multistep"], features: F(4, 3, 3, 3, 0, 2, 2), verify: () => Math.abs(value - (C(red, 2) * C(white, 1)) / C(n, 3)) < 0.001 };
  },
};

/* ------------------------------------------------------------------ 11. modelling with functions */
const functionModel = {
  id: "function-model", short: "fun", cognitive: "ANALYZE", levels: [6, 10], title: T("함수로 모델링하기", "Mô hình hóa bằng hàm số"),
  make(rand, level) {
    if (level <= 6) { const h0 = rand.int(5, 20), rate = rand.int(2, 6), d1 = rand.int(2, 5), d2 = d1 + rand.int(3, 6), d3 = d2 + rand.int(4, 10); const f = (d) => h0 + rate * d; return { type: "numeric", prompt: join(T(`식물의 키를 쟀더니 ${d1}일째 ${f(d1)} cm, ${d2}일째 ${f(d2)} cm였습니다. 같은 속도로 자란다면 ${d3}일째 키는 몇 cm일까요?`, `Đo chiều cao cây: ngày ${d1} cao ${f(d1)} cm, ngày ${d2} cao ${f(d2)} cm. Nếu cây lớn với tốc độ không đổi thì ngày ${d3} cao bao nhiêu cm?`), ONE), value: f(d3), hints: [T("하루에 자라는 양(기울기)을 먼저 구해요.", "Tìm trước lượng cây lớn mỗi ngày (hệ số góc)."), T("그 값을 이용해 일차식을 세워요.", "Dùng giá trị đó để lập hàm bậc nhất.")], expl: T(`하루 ${rate} cm → ${f(d2)} + ${rate} × ${d3 - d2} = ${f(d3)}`, `Mỗi ngày ${rate} cm → ${f(d2)} + ${rate} × ${d3 - d2} = ${f(d3)}`), tags: ["context", "multistep"], features: F(3, 3, 2, 1, 0, 0, 1), verify: () => (f(d2) - f(d1)) / (d2 - d1) === rate }; }
    if (level === 7) { const Lf = rand.pick([24, 32, 40, 44, 48, 60]); return { type: "numeric", prompt: join(T(`길이 ${Lf} m의 울타리로 한쪽이 벽에 붙은 직사각형 모양의 우리를 만들려고 합니다(벽 쪽에는 울타리가 필요 없음). 우리의 넓이를 가장 크게 할 때의 넓이는 몇 m²인가요?`, `Dùng ${Lf} m hàng rào để làm chuồng hình chữ nhật có một cạnh là bức tường (cạnh sát tường không cần rào). Diện tích lớn nhất của chuồng là bao nhiêu m²?`), ONE), value: (Lf * Lf) / 8, hints: [T("벽에 수직인 변을 x, 벽에 평행한 변을 (전체 − 2x)로 놓아요.", "Gọi cạnh vuông góc với tường là x, cạnh song song là (tổng − 2x)."), T("넓이 x(전체 − 2x)는 이차함수예요. 꼭짓점에서 최대가 돼요.", "Diện tích x(tổng − 2x) là hàm bậc hai, đạt lớn nhất tại đỉnh.")], expl: T(`x = ${Lf / 4}일 때 넓이 = ${Lf / 4} × ${Lf / 2} = ${(Lf * Lf) / 8}`, `Khi x = ${Lf / 4}, diện tích = ${Lf / 4} × ${Lf / 2} = ${(Lf * Lf) / 8}`), tags: ["reasoning", "context"], features: F(4, 4, 2, 3, 0, 0, 1), verify: () => { let best = 0; for (let x = 0; x <= Lf / 2; x += 0.5) best = Math.max(best, x * (Lf - 2 * x)); return Math.abs(best - (Lf * Lf) / 8) < 1e-9; } }; }
    if (level === 8) { const n0 = rand.pick([50, 100, 200]), mult = rand.pick([2, 3]), h = rand.pick([2, 3, 4]), k = rand.int(2, 4), t = h * k, value = n0 * mult ** k; return { type: "numeric", prompt: join(T(`세균 ${n0}마리가 ${h}시간마다 ${mult}배로 늘어납니다. ${t}시간 뒤에는 몇 마리일까요?`, `${n0} con vi khuẩn cứ ${h} giờ lại tăng gấp ${mult} lần. Sau ${t} giờ có bao nhiêu con?`), ONE), value, hints: [T("‘몇 번 늘어났는지’를 먼저 구해요.", "Trước hết tìm xem tăng bao nhiêu lần."), T("곱하는 횟수가 지수가 돼요.", "Số lần nhân chính là số mũ.")], expl: T(`${t} ÷ ${h} = ${k}번 → ${n0} × ${mult}^${k} = ${value}`, `${t} ÷ ${h} = ${k} lần → ${n0} × ${mult}^${k} = ${value}`), tags: ["context", "multistep"], features: F(3, 3, 2, 2, 0, 0, 2), verify: () => value === n0 * Math.pow(mult, t / h) }; }
    if (level === 9) { const P = rand.pick([1000000, 2000000, 5000000]), r = rand.pick([3, 4, 5, 6]), n = rand.int(2, 3), value = Math.round(P * (1 + r / 100) ** n); return { type: "numeric", prompt: join(T(`${won(P)}원을 연 ${r}%의 복리로 ${n}년 동안 예금합니다. 만기에 받는 원리합계는 몇 원인가요? (원 단위에서 반올림)`, `Gửi ${won(P)} won với lãi kép ${r}% mỗi năm trong ${n} năm. Số tiền cả gốc lẫn lãi khi đáo hạn là bao nhiêu won? (làm tròn đến won)`), ONE), value, tol: 1, hints: [T("복리는 매년 ‘이자가 붙은 금액’에 이자가 붙어요.", "Lãi kép: mỗi năm lãi được tính trên số tiền đã cộng lãi."), T(`매년 ${100 + r}%를 곱해요.`, `Mỗi năm nhân với ${100 + r}%.`)], expl: T(`${won(P)} × ${1 + r / 100}^${n} ≈ ${won(value)}원`, `${won(P)} × ${1 + r / 100}^${n} ≈ ${won(value)} won`), tags: ["context", "multistep"], features: F(3, 3, 3, 2, 0, 1, 4), verify: () => Math.abs(value - P * (1 + r / 100) ** n) <= 0.5 }; }
    const kind = rand.pick(["lin", "geo", "quad"]), a = rand.int(2, 6), d = rand.int(2, 5), q = rand.int(1, 3), y0 = rand.int(2, 6);
    const f = { lin: (x) => y0 + d * x, geo: (x) => y0 * 2 ** x, quad: (x) => y0 + q * x * x + a * x }[kind];
    const ys = [0, 1, 2, 3].map(f), value = f(4);
    return { type: "numeric", prompt: join(T(`어떤 앱의 날짜별 사용자 수(만 명)를 기록했더니 0일차부터 3일차까지 ${ys.join(", ")}이었습니다. 이 변화에 가장 알맞은 일정한 규칙(차가 일정, 비가 일정, 차의 차가 일정 중 하나)을 찾아 4일차 사용자 수를 예측하세요.`, `Số người dùng một ứng dụng theo ngày (vạn người) từ ngày 0 đến ngày 3 là ${ys.join(", ")}. Hãy tìm quy luật phù hợp nhất (hiệu không đổi, tỉ số không đổi hoặc hiệu của hiệu không đổi) và dự đoán số người dùng ngày 4.`), ONE), value, hints: [T("이웃한 값의 차와 비를 모두 구해 보세요.", "Tính cả hiệu và tỉ số của các giá trị liên tiếp."), T("차가 일정하지 않으면 ‘차의 차’도 확인해요.", "Nếu hiệu không đổi chưa đúng, hãy xét ‘hiệu của hiệu’.")], expl: T(`${kind === "lin" ? "차가 일정(일차)" : kind === "geo" ? "비가 일정(지수)" : "차의 차가 일정(이차)"} → 4일차 ${value}`, `${kind === "lin" ? "Hiệu không đổi (bậc nhất)" : kind === "geo" ? "Tỉ số không đổi (mũ)" : "Hiệu của hiệu không đổi (bậc hai)"} → ngày 4: ${value}`), tags: ["reasoning", "multistep"], features: F(4, 4, 2, 4, 0, 1, 1), verify: () => f(4) === value };
  },
};

/* ------------------------------------------------------------------ 12. geometry in real situations */
const geometry = {
  id: "geometry-real", short: "geo", cognitive: "APPLY", levels: [3, 9], title: T("생활 속 도형과 측정", "Hình học và đo lường trong thực tế"),
  make(rand, level) {
    if (level <= 3) { const W = rand.int(6, 12), H = rand.int(5, 10), w = rand.int(2, W - 3), h = rand.int(2, H - 2); return { type: "numeric", prompt: join(T(`가로 ${W} m, 세로 ${H} m인 직사각형 모양의 방에서 한쪽 구석의 가로 ${w} m, 세로 ${h} m인 직사각형 부분에는 바닥재를 깔지 않습니다. 바닥재를 깔 넓이는 몇 m²인가요?`, `Căn phòng hình chữ nhật dài ${W} m, rộng ${H} m, có một góc hình chữ nhật ${w} m × ${h} m không lát sàn. Diện tích cần lát sàn là bao nhiêu m²?`), ONE), value: W * H - w * h, hints: [T("전체 넓이에서 빼는 부분의 넓이를 빼요.", "Lấy diện tích cả phòng trừ diện tích phần không lát."), T("각 직사각형의 넓이는 가로 × 세로예요.", "Diện tích mỗi hình chữ nhật là dài × rộng.")], expl: T(`${W} × ${H} − ${w} × ${h} = ${W * H - w * h}`, `${W} × ${H} − ${w} × ${h} = ${W * H - w * h}`), tags: ["context", "multistep"], features: F(2, 0, 2, 0, 0, 0, 1), verify: () => W * H - w * h > 0 }; }
    if (level === 4) { const a = rand.int(4, 10), b = a + rand.int(2, 8), h = rand.mult(4, 12, 2), value = ((a + b) * h) / 2; return { type: "numeric", prompt: join(T(`윗변 ${a} m, 아랫변 ${b} m, 높이 ${h} m인 사다리꼴 모양의 꽃밭이 있습니다. 이 꽃밭의 넓이는 몇 m²인가요?`, `Một bồn hoa hình thang có đáy trên ${a} m, đáy dưới ${b} m, chiều cao ${h} m. Trước hết hãy tính diện tích bồn hoa (m²).`), ONE), value, hints: [T("사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2", "Diện tích hình thang = (đáy trên + đáy dưới) × chiều cao ÷ 2"), T("단위 m²를 확인해요.", "Kiểm tra đơn vị m².")], expl: T(`(${a} + ${b}) × ${h} ÷ 2 = ${value}`, `(${a} + ${b}) × ${h} ÷ 2 = ${value}`), tags: ["context"], features: F(2, 1, 2, 0, 0, 0, 1), verify: () => value === ((a + b) * h) / 2 }; }
    if (level === 5) { const k = rand.int(5, 12), tri = rand.pick([[3, 4, 5], [5, 12, 13], [8, 15, 17]]), kk = tri[2] > 13 ? 4 : k, [x, y, z] = tri.map((v) => v * kk); return { type: "numeric", prompt: join(T(`가로 ${x} cm, 세로 ${y} cm인 직사각형 모양의 태블릿 화면이 있습니다. 화면의 대각선 길이는 몇 cm인가요?`, `Màn hình máy tính bảng hình chữ nhật có chiều ngang ${x} cm, chiều dọc ${y} cm. Đường chéo màn hình dài bao nhiêu cm?`), ONE), value: z, hints: [T("대각선은 직각삼각형의 빗변이에요.", "Đường chéo là cạnh huyền của tam giác vuông."), T("빗변² = 가로² + 세로²", "Cạnh huyền² = ngang² + dọc²")], expl: T(`√(${x}² + ${y}²) = ${z}`, `√(${x}² + ${y}²) = ${z}`), tags: ["context"], features: F(3, 2, 2, 1, 0, 0, 2), verify: () => x * x + y * y === z * z }; }
    if (level === 6) { const hh = rand.pick([150, 160, 170]), s = rand.pick([60, 80, 100]), S = s * rand.int(4, 9); const value = round((hh * S) / s, 1); return { type: "numeric", prompt: join(T(`키 ${hh} cm인 사람의 그림자 길이가 ${s} cm일 때, 같은 시각에 나무의 그림자 길이가 ${S} cm였습니다. 나무의 높이는 몇 cm인가요?`, `Người cao ${hh} cm có bóng dài ${s} cm; cùng lúc đó bóng của một cái cây dài ${S} cm. Cây cao bao nhiêu cm?`), ONE), value, hints: [T("같은 시각에는 물체와 그림자의 비가 같아요(닮음).", "Cùng thời điểm, tỉ số giữa vật và bóng bằng nhau (đồng dạng)."), T("비례식: 키 : 그림자 = 나무 : 나무 그림자", "Tỉ lệ thức: cao : bóng = cây : bóng cây")], expl: T(`${hh} : ${s} = x : ${S} → x = ${value}`, `${hh} : ${s} = x : ${S} → x = ${value}`), tags: ["context", "reasoning"], features: F(3, 2, 2, 2, 0, 0, 2), verify: () => Math.abs(value * s - hh * S) < 0.5 }; }
    if (level === 7) { const r = rand.pick([5, 6, 10, 12]), ang = rand.pick([60, 90, 120, 180]), arc = round(2 * 3.14 * r * (ang / 360), 2); return { type: "numeric", prompt: join(T(`반지름이 ${r} cm인 원 모양 피자를 중심각 ${ang}°가 되게 한 조각 잘랐습니다. 이 조각의 바깥쪽 둘레(호)의 길이는 몇 cm인가요? (원주율 3.14)`, `Chiếc bánh pizza tròn bán kính ${r} cm được cắt một miếng có góc ở tâm ${ang}°. Độ dài cung ngoài của miếng bánh là bao nhiêu cm? (π = 3,14)`), DEC), value: arc, tol: 0.05, hints: [T("호의 길이 = 원주 × (중심각 ÷ 360)", "Độ dài cung = chu vi × (góc ở tâm ÷ 360)"), T("원주 = 2 × 3.14 × 반지름", "Chu vi = 2 × 3,14 × bán kính")], expl: T(`2 × 3.14 × ${r} × ${ang}/360 = ${arc}`, `2 × 3,14 × ${r} × ${ang}/360 = ${arc}`), tags: ["context", "multistep"], features: F(3, 2, 2, 1, 0, 0, 3), verify: () => Math.abs(arc - 2 * 3.14 * r * ang / 360) < 0.01 }; }
    if (level === 8) { const d = rand.mult(20, 60, 10), ang = rand.pick([45, 60]), eyes = rand.pick([1.5, 1.6, 1.7]), t = ang === 45 ? 1 : 1.73, value = round(d * t + eyes, 2); return { type: "numeric", prompt: join(T(`눈높이가 ${eyes} m인 사람이 건물에서 ${d} m 떨어진 곳에서 건물 꼭대기를 올려다본 각이 ${ang}°입니다. 건물의 높이는 약 몇 m인가요? (tan 45° = 1, tan 60° = 1.73)`, `Một người có mắt ở độ cao ${eyes} m đứng cách tòa nhà ${d} m, nhìn lên đỉnh tòa nhà với góc ngẩng ${ang}°. Tòa nhà cao khoảng bao nhiêu mét? (tan 45° = 1, tan 60° = 1,73)`), DEC), value, tol: 0.2, hints: [T("건물 높이는 ‘눈높이 + (거리 × tan 각)’이에요.", "Chiều cao tòa nhà = chiều cao mắt + (khoảng cách × tan góc)."), T("눈높이를 더하는 것을 잊지 마세요.", "Đừng quên cộng chiều cao của mắt.")], expl: T(`${d} × ${t} + ${eyes} = ${value}`, `${d} × ${t} + ${eyes} = ${value}`), tags: ["context", "multistep"], features: F(3, 3, 3, 2, 0, 1, 3), verify: () => Math.abs(value - (d * t + eyes)) < 0.01 }; }
    const r1 = rand.pick([4, 6, 8]), r2 = rand.pick([2, 3, 4]), h1 = rand.pick([9, 12, 18]);
    if (r1 <= r2) return geometry.make(rand, level);
    const value = round((r1 * r1 * h1) / (r2 * r2), 2);
    return { type: "numeric", prompt: join(T(`밑면의 반지름이 ${r1} cm인 원기둥 모양 컵에 물이 ${h1} cm 높이로 들어 있습니다. 이 물을 밑면의 반지름이 ${r2} cm인 가늘고 긴 원기둥 모양 통에 모두 부으면 물의 높이는 몇 cm가 되나요? (물은 넘치지 않음)`, `Cốc hình trụ bán kính đáy ${r1} cm chứa nước cao ${h1} cm. Rót hết nước sang ống hình trụ nhỏ hơn có bán kính đáy ${r2} cm thì nước cao bao nhiêu cm? (nước không tràn)`), DEC), value, tol: 0.05, hints: [T("물의 부피는 그대로예요: 밑넓이 × 높이.", "Thể tích nước không đổi: diện tích đáy × chiều cao."), T("π는 양쪽에서 약분돼요.", "π được giản ước ở hai vế.")], expl: T(`π·${r1}²·${h1} = π·${r2}²·h → h = ${value}`, `π·${r1}²·${h1} = π·${r2}²·h → h = ${value}`), tags: ["reasoning", "multistep"], features: F(3, 4, 2, 3, 0, 0, 3), verify: () => Math.abs(value * r2 * r2 - r1 * r1 * h1) < 0.05 * r2 * r2 };
  },
};

/* ------------------------------------------------------------------ 13. estimating with stated assumptions */
const estimation = {
  id: "estimation", short: "est", cognitive: "CREATE", levels: [4, 10], title: T("가정을 세워 어림하기", "Ước lượng dựa trên giả định"),
  make(rand, level) {
    const scenarios = [
      { range: [[400, 1200, 50], [150, 300, 10], [150, 190, 10]], out: ["kg", "kg"], conv: 1000,
        text: (n, per, days) => T(`한 학교에 학생이 ${won(n)}명 있고, 한 명이 하루에 먹는 밥의 양은 ${per} g입니다. 급식을 하는 날은 모두 ${days}일입니다.`, `Một trường có ${won(n)} học sinh, mỗi em ăn ${per} g cơm mỗi ngày. Số ngày có bữa ăn là ${days}.`) },
      { range: [[60, 300, 10], [200, 600, 10], [30, 90, 10]], out: ["m³", "m³"], conv: 1000,
        text: (n, per, days) => T(`한 마을에 ${won(n)}가구가 있고, 한 가구가 하루에 쓰는 물은 ${per} L입니다. 조사 기간은 ${days}일입니다.`, `Một ngôi làng có ${won(n)} hộ, mỗi hộ dùng ${per} L nước mỗi ngày. Thời gian khảo sát là ${days} ngày.`) },
      { range: [[100, 300, 10], [10, 40, 10], [10, 30, 10]], out: ["연(1연 = 500장)", "ream (1 ream = 500 tờ)"], conv: 500,
        text: (n, per, days) => T(`한 학년에 학생이 ${won(n)}명 있고, 한 명이 한 주에 쓰는 종이는 ${per}장입니다. 학기는 ${days}주입니다.`, `Một khối lớp có ${won(n)} học sinh, mỗi em dùng ${per} tờ giấy mỗi tuần. Học kỳ kéo dài ${days} tuần.`) },
    ];
    const s = rand.pick(scenarios), n = rand.mult(...s.range[0]), per = rand.mult(...s.range[1]), days = rand.mult(...s.range[2]);
    const extra = level >= 6, rate = extra ? rand.pick([80, 90]) : 100, waste = level >= 8 ? rand.pick([10, 20]) : 0, round10 = level >= 9;
    let raw = (n * per * days * rate) / 100;
    if (waste) raw = (raw * (100 + waste)) / 100;
    let value = raw / s.conv;
    value = round10 ? Math.round(value / 10) * 10 : round(value, 1);
    const tol = Math.max(0.6, Math.abs(value) * 0.03);
    const base = s.text(n, per, days), ko = [base.ko], vi = [base.vi];
    if (extra) { ko.push(`실제로 참여하는 사람은 전체의 ${rate}%입니다.`); vi.push(`Thực tế chỉ có ${rate}% số người tham gia.`); }
    if (waste) { ko.push(`준비할 때는 쓰는 양보다 ${waste}% 더 마련합니다.`); vi.push(`Khi chuẩn bị, cần chuẩn bị nhiều hơn lượng dùng ${waste}%.`); }
    ko.push(`필요한 전체 양은 약 몇 ${s.out[0]}인가요?${round10 ? " (십의 자리까지 어림하여 쓰세요)" : ""}`);
    vi.push(`Tổng lượng cần khoảng bao nhiêu ${s.out[1]}?${round10 ? " (làm tròn đến hàng chục)" : ""}`);
    const factors = 3 + (extra ? 1 : 0) + (waste ? 1 : 0) + (round10 ? 1 : 0);
    const chain = `${won(n)} × ${per} × ${days}${extra ? ` × ${rate}%` : ""}${waste ? ` × ${100 + waste}%` : ""} ÷ ${s.conv} ≈ ${value} ${s.out[1]}`;
    return { type: "numeric", prompt: join(T(ko.join(" "), vi.join(" ")), DEC), value, tol, hints: [T("주어진 수를 곱하는 순서를 먼저 적어 보세요. 필요 없는 정보는 없는지도 살펴요.", "Hãy viết ra thứ tự các phép nhân. Xem có thông tin nào thừa không."), T("마지막에 단위를 바꾸는 것을 잊지 마세요.", "Cuối cùng đừng quên đổi đơn vị.")], expl: T(chain.replace(s.out[1], s.out[0]), chain), tags: ["context", "multistep"], features: F(Math.min(6, factors), 1, 3, level >= 7 ? 4 : 3, 0, 1, 3), verify: () => value >= 0 };
  },
};

/* ------------------------------------------------------------------ 14. choosing the best plan under constraints */
const optimize = {
  id: "optimize-constraints", short: "opt", cognitive: "CREATE", levels: [6, 10], title: T("조건 속에서 최선 고르기", "Chọn phương án tốt nhất trong ràng buộc"),
  make(rand, level) {
    const n = level <= 7 ? 4 : level <= 9 ? 5 : 6;
    const names = ["A", "B", "C", "D", "E", "F"].slice(0, n);
    const items = names.map(() => ({ cost: rand.int(2, 9) * 1000, value: rand.int(3, 12), weight: rand.int(1, 6) }));
    const budget = Math.round(items.reduce((a, b) => a + b.cost, 0) * 0.55 / 1000) * 1000, weightCap = level >= 8 ? Math.round(items.reduce((a, b) => a + b.weight, 0) * 0.55) : Infinity;
    let best = 0;
    for (let m = 0; m < 1 << n; m++) { let c = 0, v = 0, w = 0, grp = 0; for (let i = 0; i < n; i++) if (m & (1 << i)) { c += items[i].cost; v += items[i].value; w += items[i].weight; if (i < 2) grp++; } if (c <= budget && w <= weightCap && (level < 10 || grp <= 1)) best = Math.max(best, v); }
    if (best === 0) return optimize.make(rand, level);
    const lines = items.map((it, i) => `${names[i]}: ${won(it.cost)}원, 만족도 ${it.value}${level >= 8 ? `, 무게 ${it.weight}kg` : ""}`).join(" / ");
    const linesVi = items.map((it, i) => `${names[i]}: ${won(it.cost)} won, mức hài lòng ${it.value}${level >= 8 ? `, nặng ${it.weight}kg` : ""}`).join(" / ");
    return { type: "numeric", prompt: join(T(`캠핑 용품을 고릅니다. ${lines}. 예산은 ${won(budget)}원${level >= 8 ? `, 가방에 넣을 수 있는 무게는 ${weightCap}kg 이하` : ""}${level >= 10 ? `이고, A와 B는 같은 종류라 둘 중 하나만 살 수 있습니다` : ""}입니다. 각 용품은 한 개씩만 살 수 있을 때, 만족도의 합을 가장 크게 하면 얼마인가요?`, `Chọn đồ cắm trại. ${linesVi}. Ngân sách ${won(budget)} won${level >= 8 ? `, túi chỉ chứa tối đa ${weightCap}kg` : ""}${level >= 10 ? `; A và B cùng loại nên chỉ được mua một trong hai` : ""}. Mỗi món chỉ mua được một cái; tổng mức hài lòng lớn nhất là bao nhiêu?`), ONE), value: best, hints: [T("모든 조합을 다 보기 어려우면, 가성비(만족도 ÷ 가격)가 높은 것부터 시도하고 다른 조합과 비교해요.", "Nếu khó xét mọi tổ hợp, thử món có tỉ lệ hài lòng/giá cao trước rồi so với các tổ hợp khác."), T("조건(예산, 무게, 같은 종류)을 하나라도 어기면 안 돼요.", "Không được vi phạm điều kiện nào (ngân sách, cân nặng, cùng loại).")], expl: T(`가능한 모든 조합을 따져 보면 최대 만족도는 ${best}`, `Xét mọi tổ hợp hợp lệ, mức hài lòng lớn nhất là ${best}`), tags: ["reasoning", "multistep"], features: F(Math.min(6, 3 + Math.floor(level / 3)), 2, 3, 4, 0, 2, 2), verify: () => best > 0 };
  },
};

/* ------------------------------------------------------------------ 15. generalising a pattern */
const pattern = {
  id: "pattern-general", short: "pat", cognitive: "ANALYZE", levels: [4, 10], title: T("규칙 찾아 일반화하기", "Tìm quy luật và tổng quát hóa"),
  make(rand, level) {
    if (level <= 4) { const a = rand.int(3, 9), d = rand.int(2, 5), n = rand.int(8, 15); return { type: "numeric", prompt: join(T(`성냥개비로 탑을 쌓습니다. 1층은 ${a}개, 한 층 올라갈 때마다 ${d}개씩 더 필요합니다. ${n}층을 만들 때 맨 위층에 필요한 성냥개비는 몇 개인가요?`, `Xếp tháp bằng que diêm: tầng 1 cần ${a} que, mỗi tầng lên cao cần thêm ${d} que. Tầng thứ ${n} (trên cùng) cần bao nhiêu que?`), ONE), value: a + d * (n - 1), hints: [T("처음 몇 층을 직접 적어 규칙을 찾아요.", "Viết vài tầng đầu để tìm quy luật."), T("n층이면 ${d}개씩 (n−1)번 늘어요.".replace("${d}", String(d)), `Tầng n tăng ${d} que, (n−1) lần.`)], expl: T(`${a} + ${d} × ${n - 1} = ${a + d * (n - 1)}`, `${a} + ${d} × ${n - 1} = ${a + d * (n - 1)}`), tags: ["context"], features: F(2, 2, 2, 1, 0, 0, 1), verify: () => true }; }
    if (level <= 6) { const a = rand.int(1, 3), b = rand.int(1, 4), c = rand.int(0, 3), f = (n) => a * n * n + b * n + c, terms = [1, 2, 3, 4].map(f), n = rand.int(9, 14); return { type: "numeric", prompt: join(T(`타일을 놓아 만든 도형의 타일 수가 1번째부터 4번째까지 ${terms.join(", ")}개입니다. 이 규칙이 계속될 때(타일 수의 증가량이 일정하게 커짐) ${n}번째 도형의 타일은 몇 개인가요?`, `Số ô gạch của các hình xếp lần lượt từ thứ 1 đến thứ 4 là ${terms.join(", ")}. Nếu quy luật tiếp tục (mức tăng của số ô gạch tăng đều), hình thứ ${n} có bao nhiêu ô gạch?`), ONE), value: f(n), hints: [T("이웃한 항의 차, 그리고 그 차의 차를 구해 보세요.", "Tính hiệu của các số hạng liên tiếp rồi hiệu của hiệu."), T("차의 차가 일정하면 이차식이에요.", "Hiệu của hiệu không đổi thì là biểu thức bậc hai.")], expl: T(`n번째 = ${a}n² + ${b}n + ${c} → ${n}번째 = ${f(n)}`, `Hình thứ n = ${a}n² + ${b}n + ${c} → hình thứ ${n} = ${f(n)}`), tags: ["reasoning", "multistep"], features: F(3, 3, 2, 3, 0, 0, 1), verify: () => f(1) === terms[0] }; }
    if (level === 7) { const a = rand.int(2, 5), r = rand.pick([2, 3]), terms = [0, 1, 2, 3].map((i) => a * r ** i), n = rand.int(6, 8); return { type: "numeric", prompt: join(T(`어떤 영상의 조회수가 매일 일정한 배로 늘어 첫 4일 동안 ${terms.join(", ")}회였습니다. ${n}일째 조회수는 몇 회일까요?`, `Lượt xem một video tăng gấp đều mỗi ngày; 4 ngày đầu là ${terms.join(", ")}. Ngày thứ ${n} có bao nhiêu lượt xem?`), ONE), value: a * r ** (n - 1), hints: [T("이웃한 항의 비가 일정한지 확인해요.", "Kiểm tra xem tỉ số các số hạng liên tiếp có không đổi không."), T("n일째 = 첫 항 × (공비)^(n−1)", "Ngày n = số hạng đầu × (công bội)^(n−1)")], expl: T(`${a} × ${r}^${n - 1} = ${a * r ** (n - 1)}`, `${a} × ${r}^${n - 1} = ${a * r ** (n - 1)}`), tags: ["reasoning"], features: F(3, 3, 2, 2, 0, 0, 2), verify: () => true }; }
    if (level === 8) { const a = rand.int(2, 6), b = rand.int(1, 3), X = rand.int(100, 400); let n = 1; while (a * n * n + b * n <= X) n++; return { type: "numeric", prompt: join(T(`n번째 그림에 점이 ${a}n² + ${b}n개 있습니다. 점이 처음으로 ${X}개를 넘는 것은 몇 번째 그림인가요?`, `Hình thứ n có ${a}n² + ${b}n điểm. Hình đầu tiên có hơn ${X} điểm là hình thứ mấy?`), ONE), value: n, hints: [T("식에 n을 차례로 넣거나, 부등식으로 범위를 좁혀요.", "Thay lần lượt n hoặc dùng bất phương trình để thu hẹp."), T("‘처음으로 넘는’ 가장 작은 n이에요.", "Cần n nhỏ nhất thỏa mãn.")], expl: T(`n=${n - 1}: ${a * (n - 1) ** 2 + b * (n - 1)} ≤ ${X}, n=${n}: ${a * n * n + b * n} > ${X}`, `n=${n - 1}: ${a * (n - 1) ** 2 + b * (n - 1)} ≤ ${X}, n=${n}: ${a * n * n + b * n} > ${X}`), tags: ["reasoning", "multistep"], features: F(3, 4, 1, 3, 0, 0, 2), verify: () => a * n * n + b * n > X && a * (n - 1) ** 2 + b * (n - 1) <= X }; }
    if (level === 9) { const a1 = rand.int(1, 4), a2 = rand.int(2, 6), n = rand.int(7, 9); const seq = [a1, a2]; for (let i = 2; i < n; i++) seq.push(seq[i - 1] + seq[i - 2]); return { type: "numeric", prompt: join(T(`수열의 첫째 항은 ${a1}, 둘째 항은 ${a2}이고, 셋째 항부터는 바로 앞의 두 항의 합입니다. ${n}번째 항은 얼마인가요?`, `Số hạng thứ nhất là ${a1}, số hạng thứ hai là ${a2}; từ số hạng thứ ba, mỗi số hạng bằng tổng hai số hạng liền trước. Số hạng thứ ${n} là bao nhiêu?`), ONE), value: seq[n - 1], hints: [T("규칙대로 차례로 적어 내려가요.", "Viết lần lượt từng số hạng theo quy tắc."), T("계산 실수를 막으려면 표로 정리해요.", "Ghi vào bảng để tránh nhầm.")], expl: T(`${seq.join(", ")} → ${n}번째 ${seq[n - 1]}`, `${seq.join(", ")} → số hạng thứ ${n}: ${seq[n - 1]}`), tags: ["reasoning", "multistep"], features: F(5, 3, 1, 3, 0, 0, 2), verify: () => seq.length === n };
    }
    const k = rand.int(2, 4), n = rand.int(10, 15), f = (m) => m * m + k * m + 1, terms = [1, 2, 3].map(f);
    return { type: "numeric", prompt: join(T(`성냥개비 도형을 만들었더니 1, 2, 3번째 도형의 개수가 ${terms.join(", ")}개였습니다. 도형의 개수는 항상 n² + (일정한 수)×n + (일정한 수) 꼴이라고 할 때, ${n}번째 도형의 개수는 몇 개일까요?`, `Xếp hình bằng que diêm, hình thứ 1, 2, 3 có ${terms.join(", ")} que. Biết số que luôn có dạng n² + (hằng số)×n + (hằng số). Hình thứ ${n} có bao nhiêu que?`), ONE), value: f(n), hints: [T("n² 계수가 1이므로 나머지 두 수만 찾으면 돼요. 세 값을 식에 넣어 연립해요.", "Hệ số của n² là 1 nên chỉ cần tìm hai hằng số còn lại bằng cách thay ba giá trị."), T("두 식을 빼면 한 문자가 사라져요.", "Trừ hai phương trình thì mất một ẩn.")], expl: T(`n² + ${k}n + 1 → ${n}번째 ${f(n)}`, `n² + ${k}n + 1 → hình thứ ${n}: ${f(n)}`), tags: ["reasoning", "multistep"], features: F(5, 4, 2, 4, 0, 0, 2), verify: () => f(1) === terms[0] };
  },
};

/* ------------------------------------------------------------------ 16. exponential and logarithmic reasoning */
const expLog = {
  id: "exp-log-model", short: "exl", cognitive: "ANALYZE", levels: [8, 10], title: T("지수·로그 모델", "Mô hình mũ và logarit"),
  make(rand, level) {
    const n0 = rand.pick([640, 800, 960, 1280]), h = rand.pick([3, 5, 8]);
    if (level === 8) { const k = rand.int(2, 5), t = h * k; return { type: "numeric", prompt: join(T(`방사성 물질의 반감기가 ${h}일입니다. ${n0} mg이 ${t}일 뒤에는 몇 mg 남나요?`, `Một chất phóng xạ có chu kỳ bán rã ${h} ngày. ${n0} mg còn lại bao nhiêu mg sau ${t} ngày?`), DEC), value: round(n0 / 2 ** k, 3), tol: 0.01, hints: [T("반감기가 몇 번 지났는지 세요.", "Đếm xem đã trải qua bao nhiêu chu kỳ bán rã."), T("그 횟수만큼 반으로 줄어요.", "Lượng giảm một nửa đúng số lần đó.")], expl: T(`${t} ÷ ${h} = ${k}번 → ${n0} ÷ 2^${k} = ${round(n0 / 2 ** k, 3)}`, `${t} ÷ ${h} = ${k} lần → ${n0} ÷ 2^${k} = ${round(n0 / 2 ** k, 3)}`), tags: ["context"], features: F(3, 3, 2, 2, 0, 0, 2), verify: () => true }; }
    if (level === 9) { const k = rand.int(2, 6), target = n0 / 2 ** k; if (!Number.isInteger(target)) return expLog.make(rand, level); return { type: "numeric", prompt: join(T(`반감기가 ${h}일인 물질 ${n0} mg이 ${target} mg으로 줄어들려면 며칠이 걸리나요?`, `Chất có chu kỳ bán rã ${h} ngày. Cần bao nhiêu ngày để ${n0} mg còn ${target} mg?`), ONE), value: k * h, hints: [T(`${n0} ÷ ${target} = 2의 몇 제곱인지 구해요.`, `${n0} ÷ ${target} bằng 2 mũ mấy?`), T("그 지수에 반감기를 곱해요.", "Nhân số mũ đó với chu kỳ bán rã.")], expl: T(`2^${k} = ${n0 / target} 이므로 ${k} × ${h} = ${k * h}일`, `2^${k} = ${n0 / target} nên ${k} × ${h} = ${k * h} ngày`), tags: ["reasoning"], features: F(3, 4, 2, 3, 0, 0, 2), verify: () => n0 / 2 ** k === target }; }
    const r = rand.pick([3, 4, 5, 6, 7, 8]), ln = { 3: 0.0296, 4: 0.0392, 5: 0.0488, 6: 0.0583, 7: 0.0677, 8: 0.0770 }[r], n = Math.floor(0.693 / ln) + 1; // strictly more than double: when the quotient is exactly a whole number the answer is the NEXT year
    return { type: "numeric", prompt: join(T(`연 ${r}% 복리로 예금하면 원금이 처음으로 2배를 넘는 것은 몇 년 뒤인가요? (ln 2 ≈ 0.693, ln 1.0${r} ≈ ${ln}로 계산하고, 정수 년 단위로 답하세요)`, `Gửi tiết kiệm với lãi kép ${r}%/năm. Sau bao nhiêu năm thì số tiền gốc lần đầu tiên vượt gấp 2 lần? (Dùng ln 2 ≈ 0,693 và ln 1,0${r} ≈ ${String(ln).replace(".", ",")}; trả lời bằng số năm nguyên)`), ONE), value: n, hints: [T("1.0" + r + "^n > 2 의 양변에 로그를 취해요.", "Lấy logarit hai vế của bất phương trình 1,0" + r + "^n > 2."), T("n > ln 2 ÷ ln 1.0" + r + " 이므로 올림해요.", "n > ln 2 ÷ ln 1,0" + r + " nên làm tròn lên.")], expl: T(`n > 0.693 ÷ ${ln} ≈ ${round(0.693 / ln, 2)} → ${n}년`, `n > 0,693 ÷ ${ln} ≈ ${round(0.693 / ln, 2)} → ${n} năm`), tags: ["reasoning", "multistep"], features: F(4, 4, 3, 3, 0, 0, 3), verify: () => (1 + r / 100) ** n > 2 && (1 + r / 100) ** (n - 1) <= 2 + 1e-9 };
  },
};

export const MATH_B = [algebra, probability, functionModel, geometry, estimation, optimize, pattern, expLog];
