import { T, BLANK, DIALOG, WRONG, READ, READ_TF, TF, FILL, makeEnglishKit } from "./english-kit.mjs";

/** High 3 English: parallelism and agreement, tone and purpose, sentence order and insertion, collocations and idioms, summary completion. */
export function enH3(b) {
  const S = { par: "e.h3.par", tone: "e.h3.tone", ins: "e.h3.ins", col: "e.h3.col", sum: "e.h3.sum" };
  b.skill(S.par, T("병렬 구조와 수일치", "Cấu trúc song song và hòa hợp chủ vị"));
  b.skill(S.tone, T("글의 분위기·어조·목적", "Không khí, giọng điệu và mục đích của bài"), S.par);
  b.skill(S.ins, T("문장 순서와 삽입", "Sắp xếp và chèn câu"), S.tone);
  b.skill(S.col, T("연어와 관용 표현", "Kết hợp từ và thành ngữ"), S.ins);
  b.skill(S.sum, T("요약문 완성", "Hoàn thành đoạn tóm tắt"), S.col);
  const k = makeEnglishKit(b, "h3", S);
  const { mc, tf, write } = k;
  const G = ["grammar"], GC = ["grammar", "context"], GR = ["grammar", "reasoning"], RD = ["reading"];

  /* ------------------------------ 1. parallelism and agreement ------------------------------ */
  const R1 = T("and, but, or 로 연결되는 어구는 같은 형태여야 해요(병렬). 동사는 주어의 핵심 명사에 수를 일치시키고, with / together with 뒤의 말은 수에 영향을 주지 않아요.", "Các thành phần nối bằng and, but, or phải cùng dạng (song song). Động từ hòa hợp với danh từ chính của chủ ngữ; cụm sau with / together with không ảnh hưởng đến số.");
  const l1 = [
    mc("par", 1, "core", 1, G, BLANK("She likes singing, dancing, and ____."), ["swimming", "to swim", "swim", "swam"], 0, R1, T("singing, dancing 과 같은 -ing 형태로 맞춰요.", "Dùng dạng -ing giống singing, dancing."), T("병렬 구조: singing, dancing, and swimming.", "Cấu trúc song song: singing, dancing, and swimming.")),
    mc("par", 2, "core", 2, G, BLANK("The number of students in the class ____ twenty."), ["is", "are", "were", "have been"], 0, R1, T("the number of ~ 는 단수 취급해요(a number of ~ 는 복수).", "the number of ~ được coi là số ít (a number of ~ là số nhiều)."), T("주어의 핵심은 The number 예요.", "Trọng tâm của chủ ngữ là The number."), T("The number of ... is ...", "The number of ... is ...")),
    mc("par", 3, "core", 2, GR, WRONG, ["He is tall, handsome, and kindness.", "She enjoys hiking, camping, and fishing.", "The books on the table are mine.", "Neither Tom nor his friends were late."], 0, R1, T("나열된 어구의 품사와 형태가 같은지 확인해요.", "Kiểm tra các thành phần liệt kê có cùng từ loại và dạng không."), T("tall, handsome 은 형용사인데 kindness 는 명사예요.", "tall, handsome là tính từ còn kindness là danh từ."), T("kindness 를 kind 로 고쳐야 해요.", "Phải sửa kindness thành kind.")),
    mc("par", 4, "core", 3, GC, DIALOG("A: What do you do on weekends? B: I usually go jogging, read books, and ____ my friends."), ["meet", "meeting", "to meet", "met"], 0, R1, T("go jogging, read books 와 같은 동사원형 형태로 맞춰요.", "Dùng dạng động từ nguyên mẫu giống go jogging, read books."), T("습관이므로 현재형 동사원형 meet 이 와요.", "Là thói quen nên dùng động từ nguyên mẫu meet.")),
    mc("par", 5, "core", 3, ["grammar", "multistep", "reasoning"], BLANK("The manager, together with his assistants, ____ the plan every week."), ["reviews", "review", "are reviewing", "have reviewed"], 0, R1, T("together with ~ 는 수에 영향을 주지 않아요. 핵심 주어를 먼저 찾아요.", "together with ~ không ảnh hưởng đến số. Hãy tìm chủ ngữ chính trước."), T("핵심 주어 The manager 는 단수이고, every week 는 반복되는 현재의 일이에요.", "Chủ ngữ chính The manager là số ít và every week chỉ việc lặp lại ở hiện tại."), T("단수 + 현재 습관 → reviews.", "Số ít + thói quen hiện tại → reviews.")),
  ];
  mc("par", "v1", "variant", 1, G, BLANK("He likes reading, writing, and ____."), ["drawing", "to draw", "draw", "drew"], 0, R1, T("-ing 형태로 맞춰요.", "Dùng dạng -ing."), T("drawing.", "drawing."));
  tf("par", "v2", "variant", 2, GR, TF("Each of the students have a different answer."), false, R1, T("each of ~ 는 단수 취급해요.", "each of ~ được coi là số ít."), T("have 가 아니라 has 를 써야 해요.", "Phải dùng has chứ không dùng have."));
  mc("par", "v3", "variant", 2, G, BLANK("Neither the teacher nor the students ____ ready."), ["were", "was", "is", "has been"], 0, T("neither A nor B 는 B 에 동사의 수를 맞춰요.", "Với neither A nor B, động từ hòa hợp với B."), T("B 는 the students(복수)예요.", "B là the students (số nhiều)."), T("were.", "were."));
  mc("par", "d1", "diagnostic", 1, G, BLANK("The books on the shelf ____ mine."), ["are", "is", "was", "has"], 0, R1, T("핵심 주어는 The books(복수)예요.", "Chủ ngữ chính là The books (số nhiều)."), T("are.", "are."));
  mc("par", "d2", "diagnostic", 3, GR, WRONG, ["The teacher told us to open our books and to read the text carefully.", "She is not only smart but also works hard.", "He likes to cook, to read, and to travel.", "Having finished the work, they went home."], 1, R1, T("not only A but also B 에서 A 와 B 는 같은 형태여야 해요.", "Trong not only A but also B, A và B phải cùng dạng."), T("smart(형용사)와 works hard(동사구)가 맞지 않아요.", "smart (tính từ) và works hard (cụm động từ) không song song."), T("not only smart but also hardworking 처럼 맞춰요.", "Phải viết như not only smart but also hardworking."));

  /* ------------------------------ 2. mood, tone and purpose ------------------------------ */
  const R2 = T("분위기는 감각을 나타내는 묘사(냄새, 빛, 소리)와 감정 어휘로, 목적은 글 전체가 요청·안내·설득 중 무엇을 하는지로 판단해요.", "Không khí được nhận ra qua các mô tả giác quan (mùi, ánh sáng, âm thanh) và từ chỉ cảm xúc; mục đích được xác định xem cả bài đang đề nghị, thông báo hay thuyết phục.");
  const CAFE = "The little café on the corner smelled of fresh bread. Sunlight spilled across the wooden tables, and a few customers chatted softly. I took a deep breath and felt every worry slip away.";
  const NOTICE = "Attention, all residents: the water supply will be turned off on Friday from 9 a.m. to 1 p.m. for pipe repairs. Please store enough water in advance. We apologize for any inconvenience.";
  const l2 = [
    mc("tone", 1, "core", 1, RD, READ(CAFE, "What is the mood of the passage?"), ["Peaceful and warm", "Tense and scary", "Angry and noisy", "Sad and lonely"], 0, R2, T("fresh bread, Sunlight, chatted softly 같은 묘사를 모아 봐요.", "Hãy gom các mô tả như fresh bread, Sunlight, chatted softly."), T("따뜻하고 평온한 장면이에요.", "Đó là khung cảnh ấm áp và yên bình.")),
    mc("tone", 2, "core", 2, RD, READ(CAFE, "Which word best describes the writer's feeling?"), ["Relieved", "Furious", "Bored", "Jealous"], 0, R2, T("마지막 문장에서 글쓴이의 감정을 확인해요.", "Xem cảm xúc của tác giả ở câu cuối."), T("every worry slip away 는 걱정이 사라졌다는 뜻이에요.", "every worry slip away nghĩa là mọi lo lắng tan biến."), T("걱정이 사라져 안도했으므로 Relieved.", "Mọi lo lắng tan biến nên cảm xúc là Relieved (nhẹ nhõm).")),
    tf("tone", 3, "core", 2, ["reading", "reasoning"], READ_TF(CAFE, "The café is crowded and noisy."), false, R2, T("customers 를 묘사한 부분을 확인해요.", "Xem phần mô tả khách hàng."), T("a few customers chatted softly 는 한산하고 조용하다는 뜻이에요.", "a few customers chatted softly nghĩa là vắng và yên tĩnh.")),
    mc("tone", 4, "core", 3, ["reading", "context", "reasoning"], READ(NOTICE, "What is the purpose of this notice?"), ["To inform residents of a temporary water shutdown", "To advertise a new product", "To invite residents to a party", "To ask for donations"], 0, R2, T("Attention 으로 시작하고 일정과 요청을 알리는 안내문이에요.", "Bắt đầu bằng Attention và thông báo lịch cùng lời đề nghị."), T("금요일 오전 9시부터 오후 1시까지 단수된다고 알려요.", "Thông báo cắt nước từ 9 giờ sáng đến 1 giờ chiều thứ Sáu."), T("목적은 일시적 단수 안내예요.", "Mục đích là thông báo cắt nước tạm thời.")),
    mc("tone", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(NOTICE, "Mina needs water at 11 a.m. on Friday. What should she have done?"), ["Stored water in advance", "Called a plumber on Friday morning", "Waited until 9 a.m.", "Moved out of the building"], 0, R2, T("① 11시가 단수 시간(9시~1시)에 포함되는지 확인하고 ② 안내문의 요청을 찾아요.", "① Kiểm tra 11 giờ có nằm trong giờ cắt nước (9 giờ–1 giờ) không, ② tìm lời đề nghị trong thông báo."), T("Please store enough water in advance.", "Please store enough water in advance."), T("11시는 단수 시간 안이므로 미리 물을 받아 두어야 해요.", "11 giờ nằm trong giờ cắt nước nên phải tích nước từ trước.")),
  ];
  mc("tone", "v1", "variant", 1, RD, READ(NOTICE, "When will the water be turned off?"), ["On Friday morning to early afternoon", "On Monday night", "All weekend", "Every morning"], 0, R2, T("Friday 와 시간이 들어 있는 부분을 확인해요.", "Xem phần có Friday và giờ."), T("Friday from 9 a.m. to 1 p.m.", "Friday from 9 a.m. to 1 p.m."));
  tf("tone", "v2", "variant", 2, ["reading", "reasoning"], READ_TF(NOTICE, "The writer apologizes for the inconvenience."), true, R2, T("마지막 문장을 확인해요.", "Xem câu cuối."), T("We apologize for any inconvenience.", "We apologize for any inconvenience."));
  mc("tone", "v3", "variant", 2, RD, READ(CAFE, "What does the writer feel after entering the café?"), ["Calm", "Afraid", "Angry", "Sleepy"], 0, R2, T("마지막 문장의 동작과 감정을 확인해요.", "Xem hành động và cảm xúc ở câu cuối."), T("took a deep breath and felt every worry slip away.", "took a deep breath and felt every worry slip away."));
  mc("tone", "d1", "diagnostic", 1, RD, READ(NOTICE, "Why will the water be turned off?"), ["For pipe repairs", "For a party", "For a holiday", "For a test"], 0, R2, T("for 로 시작하는 이유를 찾아요.", "Tìm lý do bắt đầu bằng for."), T("for pipe repairs.", "for pipe repairs."));
  mc("tone", "d2", "diagnostic", 3, ["reading", "reasoning"], READ(NOTICE, "Which word best describes the tone of the notice?"), ["Polite and informative", "Humorous", "Angry", "Sad"], 0, R2, T("Please 와 We apologize 같은 표현을 살펴요.", "Hãy xem các cách nói như Please và We apologize."), T("정중하게 정보를 알려 줘요.", "Thông báo lịch sự và cung cấp thông tin."));

  /* ------------------------------ 3. sentence order and insertion ------------------------------ */
  const R3 = T("첫 문장은 배경, 뒤 문장은 연결어·지시어(however, this, he)로 이어져요. 주어진 문장은 앞뒤와 논리가 맞는 자리에 넣어요.", "Câu đầu thường nêu bối cảnh; các câu sau nối bằng từ nối hoặc từ chỉ định (however, this, he). Câu cho sẵn phải được chèn vào chỗ hợp lý với câu trước và sau.");
  const FISH = "(A) As a result, the fish population slowly recovered. (B) Last year, the town banned fishing in the river for six months. (C) For years, too many fish had been caught, and the river was almost empty.";
  const WALK = "Many people believe that walking is too slow to be good exercise. (①) In fact, a brisk 30-minute walk can lower blood pressure. (②) It also improves mood and sleep. (③) Moreover, it needs no special equipment. (④)";
  const SAM = "Sam was nervous about his first day at the new school. (A) He took a deep breath and walked in. (B) However, a friendly girl smiled and showed him the way. (C) At the gate, he saw crowds of strange faces.";
  const l3 = [
    mc("ins", 1, "core", 1, RD, READ("(A) Then she put the cake in the oven. (B) First, Mia mixed flour, eggs, and sugar.", "Which sentence comes first?"), ["(B)", "(A)", "Both at the same time", "Neither"], 0, R3, T("First 와 Then 같은 순서 표현을 찾아요.", "Tìm các từ chỉ thứ tự như First và Then."), T("First 가 있는 (B) 가 먼저예요.", "(B) có First nên đứng trước.")),
    mc("ins", 2, "core", 2, RD, READ(FISH, "What is the best order of (A), (B), (C)?"), ["(C)-(B)-(A)", "(A)-(B)-(C)", "(B)-(C)-(A)", "(A)-(C)-(B)"], 0, R3, T("원인(문제) → 조치 → 결과 순서예요. As a result 는 결과를 이끌어요.", "Thứ tự là nguyên nhân (vấn đề) → biện pháp → kết quả. As a result dẫn vào kết quả."), T("(C) 물고기가 너무 많이 잡힘 → (B) 낚시 금지 → (A) 개체 수 회복", "(C) đánh bắt quá mức → (B) cấm đánh bắt → (A) quần thể phục hồi."), T("순서는 (C)-(B)-(A) 예요.", "Thứ tự đúng là (C)-(B)-(A).")),
    tf("ins", 3, "core", 2, ["reading", "reasoning"], READ_TF(FISH, "Sentence (A) should come before sentence (C)."), false, R3, T("As a result 가 있는 문장은 결과이므로 뒤쪽에 와요.", "Câu có As a result là kết quả nên đứng sau."), T("(C) 의 문제가 먼저 있어야 (A) 의 회복이 가능해요.", "Phải có vấn đề ở (C) trước thì mới có sự phục hồi ở (A).")),
    mc("ins", 4, "core", 3, ["reading", "context", "reasoning"], READ(WALK, "Where does 'Studies, however, show the opposite.' fit best?"), ["①", "②", "③", "④"], 0, R3, T("however 는 앞 문장과 반대되는 내용 앞에 와요. 앞 문장이 통념인지 확인해요.", "however đứng trước nội dung trái với câu trước. Hãy xem câu trước có phải quan niệm phổ biến không."), T("첫 문장은 '걷기는 운동이 되기에 너무 느리다' 는 통념이에요.", "Câu đầu là quan niệm 'đi bộ quá chậm để là bài tập tốt'."), T("통념 바로 뒤인 ① 에 들어가야 In fact 로 이어져요.", "Phải đặt ngay sau quan niệm, tại ①, để nối được với In fact.")),
    mc("ins", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(SAM, "What is the best order of (A), (B), (C)?"), ["(C)-(A)-(B)", "(A)-(C)-(B)", "(B)-(A)-(C)", "(B)-(C)-(A)"], 0, R3, T("① 처음 본 장면 → ② 들어가는 행동 → ③ However 로 반전, 순으로 따져 봐요.", "Xét lần lượt: ① cảnh đầu tiên → ② hành động bước vào → ③ đảo chiều với However."), T("However 는 불안한 분위기와 반대되는 사건 앞에 와요.", "However đứng trước sự kiện trái với không khí lo lắng."), T("(C) 정문에서 낯선 얼굴들 → (A) 숨을 깊이 쉬고 들어감 → (B) 그러나 친절한 소녀.", "(C) ở cổng thấy nhiều gương mặt lạ → (A) hít sâu bước vào → (B) tuy nhiên có cô gái thân thiện.")),
  ];
  mc("ins", "v1", "variant", 1, RD, READ("(A) Finally, they reached the top. (B) At dawn, the group began to climb.", "Which sentence comes first?"), ["(B)", "(A)", "Both at the same time", "Neither"], 0, R3, T("Finally 는 마지막을 뜻해요.", "Finally nghĩa là cuối cùng."), T("(B) 가 먼저예요.", "(B) đứng trước."));
  mc("ins", "v2", "variant", 2, RD, READ(WALK, "Which sentence supports the idea that walking is easy to start?"), ["Moreover, it needs no special equipment.", "In fact, a brisk 30-minute walk can lower blood pressure.", "It also improves mood and sleep.", "Many people believe that walking is too slow."], 0, R3, T("'시작하기 쉽다' 는 내용이 담긴 문장을 찾아요.", "Tìm câu có ý 'dễ bắt đầu'."), T("특별한 장비가 필요 없다는 말이에요.", "Câu nói không cần dụng cụ đặc biệt."));
  tf("ins", "v3", "variant", 2, ["reading", "reasoning"], READ_TF(SAM, "Sentence (B) should come before sentence (C)."), false, R3, T("However 가 있는 (B) 는 앞에 어떤 상황이 먼저 나와야 해요.", "Câu (B) có However cần một tình huống đi trước."), T("(C) 의 낯선 얼굴들 다음에 (B) 의 친절한 소녀가 나와요.", "Sau những gương mặt lạ ở (C) mới đến cô gái thân thiện ở (B)."));
  mc("ins", "d1", "diagnostic", 1, RD, READ("(A) After that, we had dinner. (B) First, we visited the museum.", "Which sentence comes first?"), ["(B)", "(A)", "Both at the same time", "Neither"], 0, R3, T("First 와 After that 을 비교해요.", "So sánh First và After that."), T("(B).", "(B)."));
  mc("ins", "d2", "diagnostic", 3, ["reading", "reasoning"], READ(FISH, "What does 'As a result' connect?"), ["The fishing ban and the recovery of fish", "The river and the town", "Six months and one year", "Fishing and swimming"], 0, R3, T("As a result 앞의 원인과 뒤의 결과를 찾아요.", "Tìm nguyên nhân trước As a result và kết quả sau nó."), T("낚시 금지 → 개체 수 회복", "cấm đánh bắt → quần thể phục hồi."));

  /* ------------------------------ 4. collocations and idioms ------------------------------ */
  const R4 = T("단어는 자주 함께 쓰이는 짝(연어)이 있어요. make a decision, take a risk, heavy rain 처럼 통째로 익혀요.", "Từ thường đi thành cặp cố định (kết hợp từ): make a decision, take a risk, heavy rain... Hãy học theo cụm.");
  const JACK = "Jack missed the deadline again. His boss said, \"This is the last straw.\" Jack was fired the next day.";
  const l4 = [
    write("col", 1, "core", 1, ["vocab"], FILL(T("빈칸에 알맞은 동사를 한 단어로 쓰세요.", "Điền một động từ thích hợp vào chỗ trống."), "I need to ____ a decision by tomorrow."), ["make"], R4, T("'결정을 내리다' 는 make a decision 이에요.", "'Đưa ra quyết định' là make a decision."), T("do 가 아니라 make 를 써요.", "Dùng make chứ không dùng do.")),
    mc("col", 2, "core", 2, ["vocab"], BLANK("We had ____ rain all night."), ["heavy", "strong", "big", "thick"], 0, R4, T("'폭우' 는 heavy rain 이라고 해요.", "'Mưa lớn' là heavy rain."), T("heavy.", "heavy.")),
    mc("col", 3, "core", 2, ["vocab", "reasoning"], WRONG, ["She did a mistake in the report.", "He made a lot of money last year.", "I took a photo of the sunset.", "They had a great time."], 0, R4, T("'실수를 하다' 는 어떤 동사와 짝인지 떠올려 봐요.", "Hãy nhớ động từ nào đi với 'mắc lỗi'."), T("mistake 는 do 가 아니라 make 와 함께 써요.", "mistake đi với make chứ không đi với do."), T("make a mistake 가 맞아요.", "Phải là make a mistake.")),
    mc("col", 4, "core", 3, ["vocab", "context"], DIALOG("A: Are you going to start your own company? B: Yes. It's a big risk, but I'm ready to ____ it."), ["take", "make", "do", "give"], 0, R4, T("'위험을 감수하다' 는 take a risk 예요.", "'Chấp nhận rủi ro' là take a risk."), T("risk 와 짝이 되는 동사를 골라요.", "Chọn động từ đi với risk."), T("take it (= take the risk).", "take it (= take the risk).")),
    mc("col", 5, "core", 3, ["vocab", "multistep", "reasoning"], READ(JACK, "What does 'the last straw' mean?"), ["The final problem that makes someone lose patience", "A tool for drinking", "A lucky chance", "A small gift"], 0, T("관용 표현은 글자 그대로가 아니라 상황으로 뜻을 추론해요.", "Thành ngữ không hiểu theo nghĩa đen mà suy từ tình huống."), T("또 마감을 어기자 상사가 말했고 다음 날 해고되었어요.", "Jack lại trễ hạn, sếp nói câu đó và hôm sau cậu ấy bị đuổi."), T("참을성이 바닥나게 하는 마지막 문제라는 뜻이에요.", "Nghĩa là vấn đề cuối cùng khiến người ta hết kiên nhẫn.")),
  ];
  mc("col", "v1", "variant", 1, ["vocab"], BLANK("She will ____ a speech tomorrow."), ["give", "do", "say", "tell"], 0, R4, T("'연설하다' 는 give a speech 예요.", "'Phát biểu' là give a speech."), T("give.", "give."));
  tf("col", "v2", "variant", 2, ["vocab", "reasoning"], TF("He did a big mistake yesterday."), false, R4, T("mistake 는 make 와 짝이에요.", "mistake đi với make."), T("made a big mistake 가 맞아요.", "Phải là made a big mistake."));
  mc("col", "v3", "variant", 2, ["vocab"], BLANK("It's ____ a piece of cake. (= very easy)"), ["a piece of", "a slice of", "a part of", "a bit of"], 0, T("'식은 죽 먹기' 는 a piece of cake 라고 해요.", "'Dễ như ăn bánh' là a piece of cake."), T("관용 표현은 통째로 외워요.", "Thành ngữ nên học nguyên cụm."), T("a piece of cake.", "a piece of cake."));
  mc("col", "d1", "diagnostic", 1, ["vocab"], BLANK("Please ____ attention to the teacher."), ["pay", "give up", "make", "take"], 0, R4, T("'주의를 기울이다' 는 pay attention 이에요.", "'Chú ý' là pay attention."), T("pay.", "pay."));
  mc("col", "d2", "diagnostic", 3, ["vocab", "reasoning"], BLANK("The company decided to ____ the plan because of the high cost."), ["cancel", "keep up with", "hand in", "take after"], 0, T("문맥(비용이 높다)에 어울리는 동사를 골라요.", "Chọn động từ phù hợp ngữ cảnh (chi phí cao)."), T("비용이 높아서 계획을 어떻게 했을지 생각해요.", "Hãy nghĩ xem vì chi phí cao nên công ty làm gì với kế hoạch."), T("cancel the plan.", "cancel the plan."));

  /* ------------------------------ 5. summary completion ------------------------------ */
  const R5 = T("요약문의 빈칸은 글의 핵심 내용을 한 문장으로 줄인 것이에요. 글에서 반복되는 개념과 대조 표현(although)을 찾아요.", "Chỗ trống trong đoạn tóm tắt là nội dung chính của bài rút gọn thành một câu. Hãy tìm khái niệm lặp lại và từ nối đối lập (although).");
  const ROOF = "Many cities are building green roofs, which are roofs covered with plants. These roofs keep buildings cooler in summer and warmer in winter, so they reduce energy use. They also absorb rainwater, which helps prevent floods. Although green roofs cost more to build, they save money in the long run.";
  const l5 = [
    mc("sum", 1, "core", 1, RD, READ(ROOF, "What is a green roof?"), ["A roof covered with plants", "A roof painted green", "A roof made of glass", "A roof with solar panels"], 0, R5, T("which are ... 로 정의하는 부분을 찾아요.", "Tìm phần định nghĩa bằng which are ..."), T("roofs covered with plants.", "roofs covered with plants.")),
    mc("sum", 2, "core", 2, RD, READ(ROOF, "Why do green roofs reduce energy use?"), ["They keep buildings cooler in summer and warmer in winter.", "They produce electricity.", "They block all sunlight.", "They are very light."], 0, R5, T("so they reduce energy use 의 앞부분이 이유예요.", "Phần trước so they reduce energy use là lý do."), T("여름엔 시원하고 겨울엔 따뜻하게 해 줘요.", "Giúp mát vào mùa hè và ấm vào mùa đông.")),
    tf("sum", 3, "core", 2, ["reading", "reasoning"], READ_TF(ROOF, "Green roofs make floods more likely."), false, R5, T("rainwater 가 들어 있는 문장을 확인해요.", "Xem câu có rainwater."), T("빗물을 흡수해 홍수를 막아 줘요.", "Chúng hấp thụ nước mưa và giúp ngăn lũ.")),
    mc("sum", 4, "core", 3, ["reading", "context", "reasoning"], READ(ROOF, "What relation does 'Although' signal in the last sentence?"), ["Contrast", "Cause", "Example", "Time order"], 0, R5, T("Although 는 '~이긴 하지만' 이라는 뜻이에요.", "Although nghĩa là 'mặc dù'."), T("비용은 더 들지만 장기적으로는 절약돼요.", "Tốn kém hơn nhưng về lâu dài tiết kiệm."), T("서로 반대되는 두 내용을 잇는 대조 관계예요.", "Nối hai nội dung trái ngược nhau nên là quan hệ đối lập.")),
    mc("sum", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(ROOF, "Complete the summary: Green roofs, though more ____ to build, bring ____ benefits such as lower energy use and flood prevention."), ["expensive / long-term", "cheap / short-term", "difficult / harmful", "popular / useless"], 0, R5, T("첫 빈칸은 Although 앞부분(비용), 둘째 빈칸은 in the long run 과 관련돼요.", "Chỗ trống đầu liên quan phần sau Although (chi phí), chỗ trống thứ hai liên quan in the long run."), T("cost more = more expensive, long run = long-term", "cost more = more expensive, long run = long-term."), T("더 비싸지만 장기적인 이점이 있어요.", "Đắt hơn nhưng mang lại lợi ích lâu dài.")),
  ];
  mc("sum", "v1", "variant", 1, RD, READ(ROOF, "What else do green roofs do besides saving energy?"), ["They absorb rainwater.", "They make noise.", "They block the road.", "They grow food only."], 0, R5, T("also 가 들어 있는 문장을 찾아요.", "Tìm câu có also."), T("They also absorb rainwater.", "They also absorb rainwater."));
  mc("sum", "v2", "variant", 2, RD, READ(ROOF, "Which is the best title for the passage?"), ["The Benefits of Green Roofs", "How to Paint a Roof", "Why Cities Are Noisy", "A History of Rain"], 0, R5, T("글 전체를 대표하는 제목을 골라요.", "Chọn tiêu đề đại diện cho cả bài."), T("녹색 지붕의 장점들을 설명해요.", "Bài giải thích các lợi ích của mái nhà xanh."));
  tf("sum", "v3", "variant", 2, ["reading", "reasoning"], READ_TF(ROOF, "Green roofs are cheaper to build than normal roofs."), false, R5, T("Although 절을 확인해요.", "Xem mệnh đề Although."), T("cost more to build 라고 했어요.", "Bài nói cost more to build."));
  mc("sum", "d1", "diagnostic", 1, RD, READ(ROOF, "What do green roofs absorb?"), ["Rainwater", "Sunlight only", "Snow only", "Noise"], 0, R5, T("absorb 가 들어 있는 문장을 찾아요.", "Tìm câu có absorb."), T("absorb rainwater.", "absorb rainwater."));
  mc("sum", "d2", "diagnostic", 3, ["reading", "reasoning"], READ(ROOF, "Which statement best summarizes the passage?"), ["Green roofs cost more at first but offer lasting benefits.", "Green roofs are only for decoration.", "Cities should stop building roofs.", "Plants cannot grow on roofs."], 0, R5, T("Although 이하가 글의 결론을 담고 있어요.", "Phần sau Although chứa kết luận của bài."), T("비용↑ 하지만 장기적 절약.", "Chi phí cao nhưng tiết kiệm lâu dài."));

  k.course({
    slug: "reading-summary", title: T("고3 영어: 병렬·어조·순서 삽입·요약", "Tiếng Anh lớp 12: Song song, giọng điệu, sắp xếp câu và tóm tắt"),
    world: { name: T("수능 정상", "Đỉnh kỳ thi"), emoji: "🏆", tagline: T("글의 구조를 읽고 순서를 잡고 요약까지 완성해요.", "Đọc cấu trúc bài, sắp xếp câu và hoàn thành bản tóm tắt.") }, unitTitle: T("고3 영어", "Tiếng Anh lớp 12"),
    lessons: [
      k.lesson(1, "par", T("병렬 구조와 수일치", "Song song và hòa hợp chủ vị"), T("and/but/or 로 이어지는 어구는 같은 형태로, 동사는 핵심 주어에 일치시켜요.", "Các thành phần nối bằng and/but/or phải cùng dạng; động từ hòa hợp với chủ ngữ chính."), T("singing, dancing, and swimming", "singing, dancing, and swimming"), l1),
      k.lesson(2, "tone", T("분위기·어조·목적", "Không khí, giọng điệu và mục đích"), T("묘사와 감정 어휘로 분위기를, 요청·안내·설득 여부로 글의 목적을 파악해요.", "Nhận ra không khí qua mô tả và từ chỉ cảm xúc; xác định mục đích qua việc bài đề nghị, thông báo hay thuyết phục."), T("Please store enough water. → 안내", "Please store enough water. → thông báo"), l2),
      k.lesson(3, "ins", T("문장 순서와 삽입", "Sắp xếp và chèn câu"), T("연결어·지시어·시간 순서를 단서로 문장을 배열하고 주어진 문장이 들어갈 자리를 찾아요.", "Dùng từ nối, từ chỉ định và trật tự thời gian để sắp xếp câu và tìm chỗ chèn câu cho sẵn."), T("원인 → 조치 → 결과", "nguyên nhân → biện pháp → kết quả"), l3),
      k.lesson(4, "col", T("연어와 관용 표현", "Kết hợp từ và thành ngữ"), T("make a decision, take a risk, heavy rain 처럼 함께 쓰이는 짝을 익히고, 관용 표현은 상황으로 뜻을 추론해요.", "Học các cặp từ như make a decision, take a risk, heavy rain; suy nghĩa thành ngữ từ tình huống."), T("the last straw = 마지막 참을성의 한계", "the last straw = giọt nước tràn ly"), l4),
      k.lesson(5, "sum", T("요약문 완성", "Hoàn thành tóm tắt"), T("글의 핵심 개념과 대조 표현을 찾아 한 문장으로 줄여요.", "Tìm khái niệm chính và từ nối đối lập rồi rút gọn thành một câu."), T("cost more ↔ save money in the long run", "cost more ↔ save money in the long run"), l5),
    ],
  });
}
