import { T, BLANK, DIALOG, WRONG, READ, READ_TF, TF, FILL, makeEnglishKit } from "./english-kit.mjs";

/** High 2 English: inversion and emphasis, subjunctive mood, compound relatives and concession, vocabulary in context, logical development. */
export function enH2(b) {
  const S = { inv: "e.h2.inv", subj: "e.h2.subj", wh: "e.h2.wh", vocab: "e.h2.vocab", logic: "e.h2.logic" };
  b.skill(S.inv, T("도치와 강조 구문", "Đảo ngữ và cấu trúc nhấn mạnh"));
  b.skill(S.subj, T("가정법", "Câu giả định"), S.inv);
  b.skill(S.wh, T("복합관계사와 양보절", "Từ quan hệ ghép và mệnh đề nhượng bộ"), S.subj);
  b.skill(S.vocab, T("문맥 속 어휘", "Từ vựng trong ngữ cảnh"), S.wh);
  b.skill(S.logic, T("글의 논리 전개", "Mạch lập luận của bài"), S.vocab);
  const k = makeEnglishKit(b, "h2", S);
  const { mc, tf, write } = k;
  const G = ["grammar"], GC = ["grammar", "context"], GR = ["grammar", "reasoning"], RD = ["reading"], VC = ["vocab", "context"];

  /* ------------------------------ 1. inversion and emphasis ------------------------------ */
  const R1 = T("never, hardly, only then 같은 부정·제한 부사가 문두에 오면 조동사가 주어 앞으로 나가요. It is ~ that 구문은 강조하고 싶은 부분을 ~ 자리에 둬요.", "Khi trạng từ phủ định hoặc hạn định như never, hardly, only then đứng đầu câu, trợ động từ đứng trước chủ ngữ. Cấu trúc It is ... that đặt thành phần cần nhấn mạnh vào chỗ ....");
  const l1 = [
    mc("inv", 1, "core", 1, G, BLANK("Never ____ I seen such a beautiful sunset."), ["have", "do", "am", "was"], 0, R1, T("Never 가 문두에 있고 완료 시제예요.", "Never đứng đầu câu và câu ở thì hoàn thành."), T("Never have I seen ... (조동사 + 주어 + p.p.).", "Never have I seen ... (trợ động từ + chủ ngữ + p.p.).")),
    mc("inv", 2, "core", 2, G, BLANK("Only then ____ I realize my mistake."), ["did", "do", "have", "was"], 0, R1, T("Only then 이 문두에 오면 도치가 일어나요. 과거의 일이에요.", "Only then đứng đầu câu thì xảy ra đảo ngữ; việc ở quá khứ."), T("Only then did I realize ...", "Only then did I realize ...")),
    mc("inv", 3, "core", 2, GR, WRONG, ["Hardly I had left home when it began to rain.", "Hardly had I left home when it began to rain.", "Never have I felt so happy.", "Not only is he smart, but he is also kind."], 0, R1, T("Hardly 가 문두에 있는 문장의 어순을 비교해 보세요.", "Hãy so sánh trật tự của các câu có Hardly đứng đầu."), T("Hardly 뒤에는 had + 주어 + p.p. 순서예요.", "Sau Hardly là had + chủ ngữ + p.p."), T("Hardly had I left home ... 가 맞아요.", "Phải là Hardly had I left home ...")),
    mc("inv", 4, "core", 3, GC, DIALOG("A: Who broke the window? B: It was Tom ____ broke it."), ["that", "which", "what", "whose"], 0, T("It is/was ~ that ... 에서 ~ 가 사람이면 who 도 쓸 수 있고, that 은 모두 쓸 수 있어요.", "Trong It is/was ... that ..., nếu ... chỉ người có thể dùng who; that dùng được trong mọi trường hợp."), T("강조 구문의 that 자리예요.", "Đây là vị trí của that trong cấu trúc nhấn mạnh."), T("It was Tom that broke it.", "It was Tom that broke it.")),
    write("inv", 5, "core", 3, ["grammar", "multistep", "reasoning"], FILL(T("강조 구문으로 바꿔 빈칸에 한 단어를 쓰세요.", "Chuyển sang cấu trúc nhấn mạnh, điền một từ vào chỗ trống."), "Mina found the key in the garden. → It was the key ____ Mina found in the garden."), ["that", "which"], R1, T("the key 를 강조하고 있어요.", "Câu đang nhấn mạnh the key."), T("강조 구문의 that(사물이면 which 도 가능).", "that của cấu trúc nhấn mạnh (với vật cũng có thể dùng which).")),
  ];
  mc("inv", "v1", "variant", 1, G, BLANK("Rarely ____ he visit his hometown."), ["does", "do", "is", "has"], 0, R1, T("Rarely 가 문두에 있고 현재 일반 사실이에요.", "Rarely đứng đầu câu, nói về thói quen hiện tại."), T("Rarely does he visit ...", "Rarely does he visit ..."));
  tf("inv", "v2", "variant", 2, GR, TF("Not only he is smart but also kind."), false, R1, T("Not only 가 문두에 오면 도치돼요.", "Khi Not only đứng đầu thì đảo ngữ."), T("Not only is he smart but also kind. 가 맞아요.", "Phải viết Not only is he smart but also kind."));
  mc("inv", "v3", "variant", 2, G, BLANK("It was in Paris ____ they first met."), ["that", "what", "where it", "who"], 0, R1, T("장소 in Paris 를 강조하는 구문이에요.", "Cấu trúc nhấn mạnh cụm chỉ nơi chốn in Paris."), T("It was in Paris that ...", "It was in Paris that ..."));
  mc("inv", "d1", "diagnostic", 1, G, BLANK("Never ____ she been late for school."), ["has", "have", "is", "does"], 0, R1, T("she 는 3인칭 단수예요.", "she là ngôi thứ ba số ít."), T("Never has she been ...", "Never has she been ..."));
  mc("inv", "d2", "diagnostic", 3, GR, BLANK("Little ____ he know about the surprise party."), ["did", "does he", "had he", "was"], 0, T("Little(거의 ~ 않다)도 문두에 오면 도치돼요. 과거의 일이에요.", "Little (hầu như không) đứng đầu câu cũng gây đảo ngữ; việc ở quá khứ."), T("Little did he know ...", "Little did he know ..."), T("Little did he know ...", "Little did he know ..."));

  /* ------------------------------ 2. subjunctive ------------------------------ */
  const R2 = T("현재 사실의 반대는 I wish + 과거, 과거 사실의 반대는 I wish + had p.p. 예요. If 절도 같은 규칙으로 시제를 한 단계씩 뒤로 보내요.", "Ước trái với hiện tại: I wish + quá khứ; trái với quá khứ: I wish + had p.p. Mệnh đề If cũng lùi thì tương tự.");
  const l2 = [
    mc("subj", 1, "core", 1, G, BLANK("I wish I ____ a bird."), ["were", "am", "will be", "had been"], 0, R2, T("지금은 새가 아니라서 현재 사실의 반대를 소망해요.", "Hiện tại tôi không phải chim nên ước điều trái ngược."), T("I wish + 과거형(were).", "I wish + quá khứ (were).")),
    mc("subj", 2, "core", 2, G, BLANK("I wish I ____ the exam last week."), ["had passed", "passed", "would pass", "have passed"], 0, R2, T("last week 는 이미 지나간 일이에요. 과거 사실의 반대예요.", "last week đã qua rồi nên đây là điều trái với quá khứ."), T("I wish + had p.p.", "I wish + had p.p.")),
    mc("subj", 3, "core", 2, GR, WRONG, ["I wish I would have a car.", "I wish I had a car.", "If I were you, I would go.", "I wish I had studied harder."], 0, R2, T("I wish 뒤에는 would have 형태가 오지 않아요.", "Sau I wish không dùng dạng would have."), T("'차가 있으면 좋겠다' 는 현재 소망이에요.", "'Ước có xe' là mong ước ở hiện tại."), T("I wish I had a car. 가 맞아요.", "Phải viết I wish I had a car.")),
    mc("subj", 4, "core", 3, GC, DIALOG("A: I failed the test. B: If you ____ harder, you would have passed."), ["had studied", "studied", "study", "would study"], 0, T("과거 사실의 반대: If + had p.p., would have p.p.", "Trái với quá khứ: If + had p.p., would have p.p."), T("뒤에 would have passed 가 있어요.", "Phía sau là would have passed."), T("If you had studied harder, ...", "If you had studied harder, ...")),
    mc("subj", 5, "core", 3, ["reading", "multistep", "reasoning"], READ("Ann didn't wear a coat, so she caught a cold.", "Which sentence has the same meaning?"), ["If Ann had worn a coat, she wouldn't have caught a cold.", "If Ann wore a coat, she wouldn't catch a cold.", "If Ann has worn a coat, she won't catch a cold.", "Ann wore a coat, so she caught a cold."], 0, R2, T("과거의 사실(코트를 입지 않았다 → 감기에 걸렸다)을 반대로 가정해요.", "Giả định ngược với sự thật quá khứ (không mặc áo → bị cảm)."), T("두 부분 모두 부정과 긍정을 뒤집어요.", "Cả hai vế đều đổi khẳng định thành phủ định và ngược lại.")),
  ];
  mc("subj", "v1", "variant", 1, G, BLANK("I wish it ____ warmer today."), ["were", "is", "will be", "had been"], 0, R2, T("오늘 춥다는 현재 사실의 반대예요.", "Trái với thực tế hôm nay lạnh."), T("were.", "were."));
  tf("subj", "v2", "variant", 2, GR, TF("If I had known, I would told you."), false, R2, T("would 뒤에는 have + p.p. 가 와야 해요.", "Sau would phải có have + p.p."), T("I would have told you. 가 맞아요.", "Phải viết I would have told you."));
  mc("subj", "v3", "variant", 2, G, BLANK("She talks as if she ____ the boss."), ["were", "will be", "had being", "is being"], 0, R2, T("as if 가정법 과거는 현재 사실과 반대되는 느낌을 줘요.", "as if ở quá khứ giả định gợi nghĩa trái với thực tế hiện tại."), T("as if she were.", "as if she were."));
  mc("subj", "d1", "diagnostic", 1, G, BLANK("I wish I ____ taller."), ["were", "am", "will be", "have been"], 0, R2, T("현재 사실과 반대되는 소망이에요.", "Mong ước trái với hiện tại."), T("were.", "were."));
  mc("subj", "d2", "diagnostic", 3, GR, BLANK("If he ____ the bus, he wouldn't have been late."), ["had caught", "caught", "catches", "would catch"], 0, R2, T("뒤에 wouldn't have been 가 있어요.", "Phía sau là wouldn't have been."), T("If + had p.p.", "If + had p.p."), T("had caught.", "had caught."));

  /* ------------------------------ 3. compound relatives and concession ------------------------------ */
  const R3 = T("whatever, whoever, whichever 는 '~든지' 의 뜻으로 명사절이나 양보절을 이끌어요. however + 형용사 + 주어 + 동사 는 '아무리 ~해도' 예요.", "whatever, whoever, whichever mang nghĩa 'dù ... nào' và dẫn mệnh đề danh từ hoặc nhượng bộ. however + tính từ + chủ ngữ + động từ nghĩa là 'cho dù ... đến đâu'.");
  const l3 = [
    mc("wh", 1, "core", 1, G, BLANK("____ you say, I won't change my mind."), ["Whatever", "Whoever", "However", "Wherever"], 0, R3, T("'무엇을 말하든' 이라는 뜻이에요.", "Nghĩa là 'dù bạn nói gì'."), T("what 의 복합관계사 Whatever.", "Từ quan hệ ghép của what: Whatever.")),
    mc("wh", 2, "core", 2, G, BLANK("____ comes first will get the prize."), ["Whoever", "Whatever", "However", "Whenever"], 0, R3, T("'누구든지' 라는 뜻이에요. 사람이 주어예요.", "Nghĩa là 'bất cứ ai'; chủ ngữ là người."), T("Whoever comes first ...", "Whoever comes first ...")),
    mc("wh", 3, "core", 2, GR, WRONG, ["However hard is the task, we must finish it.", "However hard the task is, we must finish it.", "Whatever happens, I will stay with you.", "You can sit wherever you like."], 0, R3, T("however 뒤에는 형용사 + 주어 + 동사 순서예요.", "Sau however là tính từ + chủ ngữ + động từ."), T("hard 다음에 주어가 와야 해요.", "Sau hard phải là chủ ngữ."), T("However hard the task is, ... 가 맞아요.", "Phải là However hard the task is, ...")),
    mc("wh", 4, "core", 3, GC, DIALOG("A: There are three restaurants nearby. Which one? B: ____ you choose is fine with me."), ["Whichever", "Whenever", "However", "Whoever"], 0, R3, T("정해진 선택지(세 식당) 중 '어느 것이든' 이에요.", "Chọn trong số lựa chọn xác định (ba nhà hàng): 'cái nào cũng được'."), T("Whichever restaurant you choose ...", "Whichever restaurant you choose ...")),
    mc("wh", 5, "core", 3, ["reading", "multistep", "reasoning"], READ("No matter how tired Jin is, he always finishes his homework.", "Which sentence has the same meaning?"), ["However tired Jin is, he always finishes his homework.", "Whatever tired Jin is, he always finishes his homework.", "Whoever tired Jin is, he always finishes his homework.", "Whenever Jin is tired, he never finishes his homework."], 0, R3, T("no matter how ~ = however ~ 이에요.", "no matter how ~ = however ~."), T("형용사(tired)를 꾸미는 정도 표현이 필요해요.", "Cần từ chỉ mức độ bổ nghĩa cho tính từ tired.")),
  ];
  mc("wh", "v1", "variant", 1, G, BLANK("____ you go, I will follow you."), ["Wherever", "Whatever", "Whoever", "However"], 0, R3, T("'어디에 가든' 이라는 뜻이에요.", "Nghĩa là 'dù bạn đi đâu'."), T("Wherever.", "Wherever."));
  tf("wh", "v2", "variant", 2, GR, TF("Whatever you do, do your best."), true, R3, T("'무엇을 하든' 이라는 양보절이에요.", "Đây là mệnh đề nhượng bộ 'dù làm gì'."), T("옳은 문장이에요.", "Câu đúng."));
  mc("wh", "v3", "variant", 2, G, BLANK("You can give the ticket to ____ wants it."), ["whoever", "whatever", "however", "whenever"], 0, R3, T("전치사 to 뒤의 명사절 안에서 주어 역할을 해요.", "Làm chủ ngữ trong mệnh đề danh từ đứng sau giới từ to."), T("whoever wants it.", "whoever wants it."));
  mc("wh", "d1", "diagnostic", 1, G, BLANK("____ you call, I will answer."), ["Whenever", "Whatever", "Whoever", "However"], 0, R3, T("'언제 전화하든' 이라는 뜻이에요.", "Nghĩa là 'bất cứ khi nào bạn gọi'."), T("Whenever.", "Whenever."));
  mc("wh", "d2", "diagnostic", 3, GR, BLANK("____ rich he is, he is not happy."), ["However", "Whatever", "Whoever", "Whichever"], 0, R3, T("뒤에 형용사 rich 가 와요.", "Phía sau là tính từ rich."), T("However + 형용사.", "However + tính từ."), T("However rich he is, ...", "However rich he is, ..."));

  /* ------------------------------ 4. vocabulary in context ------------------------------ */
  const R4 = T("모르는 단어는 앞뒤 문장의 단서(대조, 예시, 원인)로 뜻을 추론해요. 접두사·어근도 도움이 돼요.", "Hãy suy ra nghĩa từ lạ từ manh mối trong câu (đối lập, ví dụ, nguyên nhân). Tiền tố và gốc từ cũng giúp ích.");
  const LENA = "Lena was reluctant to speak in public. She never raised her hand, and her voice shook whenever she presented.";
  const SCI = "The scientist's claim was met with skepticism. Many experts doubted the results and asked for more evidence.";
  const LAW = "The new law is controversial. Some people support it strongly, while others oppose it just as strongly.";
  const l4 = [
    mc("vocab", 1, "core", 1, ["vocab"], T("'unhappy'의 뜻으로 알맞은 것은?", "Nghĩa phù hợp của 'unhappy' là?"), ["not happy", "very happy", "happy again", "before happy"], 0, R4, T("접두사 un- 은 '아닌' 이라는 뜻이에요.", "Tiền tố un- nghĩa là 'không'."), T("un + happy = 행복하지 않은.", "un + happy = không hạnh phúc.")),
    mc("vocab", 2, "core", 2, VC, READ(LENA, "What does 'reluctant' mean?"), ["unwilling", "eager", "proud", "angry"], 0, R4, T("뒤 문장에서 Lena 의 행동(손을 들지 않음, 목소리가 떨림)을 단서로 삼아요.", "Dùng hành vi của Lena (không giơ tay, giọng run) ở câu sau làm manh mối."), T("발표를 꺼리는 모습이에요.", "Đó là biểu hiện e ngại phát biểu."), T("reluctant = 꺼리는, 마음이 내키지 않는.", "reluctant = miễn cưỡng, không muốn.")),
    mc("vocab", 3, "core", 2, ["vocab", "reasoning"], T("밑줄 친 단어 bear 의 문맥상 뜻은? \"I can't bear this noise any longer.\"", "Nghĩa của từ bear trong ngữ cảnh? \"I can't bear this noise any longer.\""), ["tolerate", "carry", "give birth to", "produce"], 0, T("같은 단어도 문맥에 따라 뜻이 달라져요. 목적어(noise)와 can't 에 주목해요.", "Cùng một từ có thể có nghĩa khác nhau tùy ngữ cảnh. Chú ý tân ngữ (noise) và can't."), T("'소음을 더는 ~ 못 하겠다' 는 뜻이에요.", "Nghĩa là 'không thể ... tiếng ồn này nữa'."), T("can't bear = 참을 수 없다 (tolerate).", "can't bear = không chịu đựng nổi (tolerate).")),
    mc("vocab", 4, "core", 3, ["vocab", "context", "reasoning"], READ(SCI, "What does 'skepticism' mean?"), ["doubt", "excitement", "support", "fear"], 0, R4, T("뒤 문장 Many experts doubted ... 이 바로 뜻을 설명해요.", "Câu sau Many experts doubted ... giải thích trực tiếp nghĩa."), T("전문가들이 의심하고 증거를 더 요구했어요.", "Các chuyên gia nghi ngờ và đòi thêm bằng chứng."), T("skepticism = 회의, 의심.", "skepticism = sự hoài nghi.")),
    mc("vocab", 5, "core", 3, ["vocab", "multistep", "reasoning"], READ(LAW, "Which word is closest in meaning to 'controversial'?"), ["causing disagreement", "very popular", "completely secret", "easy to understand"], 0, R4, T("while 이 이끄는 대조 구문을 이용해요: 어떤 사람은 찬성, 어떤 사람은 반대.", "Dùng cấu trúc đối lập với while: người ủng hộ, người phản đối."), T("의견이 갈린다는 뜻이에요.", "Nghĩa là ý kiến chia rẽ."), T("controversial = 논란이 많은.", "controversial = gây tranh cãi.")),
  ];
  mc("vocab", "v1", "variant", 1, ["vocab"], T("'unfair'의 뜻으로 알맞은 것은?", "Nghĩa phù hợp của 'unfair' là?"), ["not fair", "very fair", "fair again", "before fair"], 0, R4, T("접두사 un- 은 '아닌' 이라는 뜻이에요.", "Tiền tố un- nghĩa là 'không'."), T("un + fair.", "un + fair."));
  mc("vocab", "v2", "variant", 2, VC, READ(SCI, "Why did experts ask for more evidence?"), ["Because they doubted the results.", "Because they loved the results.", "Because they were afraid.", "Because they were bored."], 0, R4, T("doubted 가 들어 있는 문장을 확인해요.", "Xem câu có từ doubted."), T("Many experts doubted the results.", "Many experts doubted the results."));
  tf("vocab", "v3", "variant", 2, ["vocab", "reasoning"], READ_TF(LENA, "Lena enjoys speaking in public."), false, R4, T("reluctant 의 뜻과 Lena 의 행동을 비교해요.", "So sánh nghĩa của reluctant với hành vi của Lena."), T("손을 들지 않고 목소리가 떨려서 즐기지 않아요.", "Không giơ tay và giọng run nên cô ấy không thích."));
  mc("vocab", "d1", "diagnostic", 1, ["vocab"], T("'impossible'의 뜻으로 알맞은 것은?", "Nghĩa phù hợp của 'impossible' là?"), ["not possible", "very possible", "possible again", "before possible"], 0, R4, T("접두사 im- 도 '아닌' 이라는 뜻이에요.", "Tiền tố im- cũng nghĩa là 'không'."), T("im + possible.", "im + possible."));
  mc("vocab", "d2", "diagnostic", 3, ["vocab", "reasoning"], READ(LAW, "What can we infer about the law?"), ["People have different opinions about it.", "Everyone agrees with it.", "Nobody knows about it.", "It will be cancelled tomorrow."], 0, R4, T("some ... while others ... 구조는 의견이 나뉜다는 뜻이에요.", "Cấu trúc some ... while others ... cho thấy ý kiến bị chia rẽ."), T("찬성과 반대가 모두 강해요.", "Cả ủng hộ và phản đối đều mạnh."));

  /* ------------------------------ 5. logical development ------------------------------ */
  const R5 = T("지시어(this, they)가 가리키는 것을 앞 문장에서 찾고, 대조·인과의 연결어로 글의 흐름을 따라가요.", "Tìm đối tượng mà các từ chỉ định (this, they) nói đến ở câu trước, rồi lần theo mạch văn bằng các từ nối đối lập, nhân quả.");
  const BEE = "Honeybees communicate by dancing. When a bee finds food, it returns to the hive and performs a 'waggle dance'. The angle of the dance shows the direction of the food, and its length shows the distance. In this way, the whole colony can find food quickly.";
  const l5 = [
    mc("logic", 1, "core", 1, RD, READ(BEE, "How do honeybees communicate?"), ["By dancing", "By singing", "By writing", "By flying away"], 0, R5, T("첫 문장을 확인해요.", "Xem câu đầu."), T("Honeybees communicate by dancing.", "Honeybees communicate by dancing.")),
    mc("logic", 2, "core", 2, RD, READ(BEE, "What does the angle of the dance show?"), ["The direction of the food", "The distance to the food", "The size of the hive", "The type of flower"], 0, R5, T("angle 이 들어 있는 문장을 찾아요.", "Tìm câu có từ angle."), T("The angle of the dance shows the direction of the food.", "The angle of the dance shows the direction of the food.")),
    tf("logic", 3, "core", 2, ["reading", "reasoning"], READ_TF(BEE, "The length of the dance shows the direction of the food."), false, R5, T("angle 과 length 가 각각 무엇을 알려 주는지 구별해요.", "Phân biệt angle và length mỗi cái cho biết điều gì."), T("length 는 거리(distance)를 알려 줘요.", "length cho biết khoảng cách (distance).")),
    mc("logic", 4, "core", 3, ["reading", "context", "reasoning"], READ(BEE, "What does 'this way' in the last sentence refer to?"), ["Sharing food information through dance", "Flying to the hive", "Making honey", "Protecting the colony"], 0, R5, T("지시어는 보통 바로 앞 내용을 가리켜요.", "Từ chỉ định thường chỉ nội dung ngay phía trước."), T("앞 문장은 춤으로 방향과 거리를 알려 주는 방법이에요.", "Câu trước nói về cách báo hướng và khoảng cách bằng điệu nhảy."), T("this way = 춤으로 먹이 정보를 알리는 방식.", "this way = cách báo thông tin thức ăn bằng điệu nhảy.")),
    mc("logic", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(BEE, "Which is the best conclusion of the passage?"), ["Bees share food information with their colony through dance.", "Bees dance only for fun.", "Honey is made by dancing.", "Only one bee ever finds food."], 0, R5, T("세부 정보(각도, 길이)를 모아 하나의 결론으로 묶어요.", "Gom các chi tiết (góc, độ dài) thành một kết luận."), T("방향과 거리를 춤으로 알려 군집 전체가 먹이를 찾아요.", "Điệu nhảy cho biết hướng và khoảng cách để cả đàn tìm thức ăn."), T("결론은 춤을 통한 정보 공유예요.", "Kết luận là chia sẻ thông tin qua điệu nhảy.")),
  ];
  mc("logic", "v1", "variant", 1, RD, READ(BEE, "Where does a bee go after it finds food?"), ["Back to the hive", "To the river", "To a new city", "To sleep"], 0, R5, T("returns 가 들어 있는 문장을 찾아요.", "Tìm câu có returns."), T("it returns to the hive.", "it returns to the hive."));
  tf("logic", "v2", "variant", 2, ["reading", "reasoning"], READ_TF(BEE, "The whole colony can find food quickly in this way."), true, R5, T("마지막 문장을 확인해요.", "Xem câu cuối."), T("글에 그대로 나와 있어요.", "Có trong bài đúng như vậy."));
  mc("logic", "v3", "variant", 2, RD, READ(BEE, "What does 'its length' show?"), ["The distance to the food", "The direction of the food", "The time of day", "The weather"], 0, R5, T("its 가 가리키는 것은 the dance 예요.", "its chỉ the dance."), T("its length shows the distance.", "its length shows the distance."));
  mc("logic", "d1", "diagnostic", 1, RD, READ(BEE, "What is the 'waggle dance'?"), ["A dance bees use to share information", "A kind of flower", "A type of honey", "A game"], 0, R5, T("performs a 'waggle dance' 앞뒤를 확인해요.", "Xem câu chứa performs a 'waggle dance'."), T("벌이 정보를 알리는 춤이에요.", "Đó là điệu nhảy ong dùng để báo thông tin."));
  mc("logic", "d2", "diagnostic", 3, ["reading", "reasoning"], READ(BEE, "Which can we infer from the passage?"), ["Dancing helps the colony save time when looking for food.", "Bees cannot find food alone.", "The hive is far from every flower.", "Honeybees never leave the hive."], 0, R5, T("quickly 라는 표현에 주목해요.", "Chú ý từ quickly."), T("춤으로 먹이를 빨리 찾게 돼요.", "Nhờ điệu nhảy mà tìm thức ăn nhanh hơn."));

  k.course({
    slug: "advanced-grammar-logic", title: T("고2 영어: 도치·가정법·어휘 추론·논리 독해", "Tiếng Anh lớp 11: Đảo ngữ, giả định, suy luận từ vựng và đọc hiểu logic"),
    world: { name: T("수사학의 탑", "Tháp tu từ"), emoji: "🗼", tagline: T("강조와 가정의 문법을 익히고 글의 논리를 따라가요.", "Nắm ngữ pháp nhấn mạnh, giả định và lần theo lập luận của bài.") }, unitTitle: T("고2 영어", "Tiếng Anh lớp 11"),
    lessons: [
      k.lesson(1, "inv", T("도치와 강조 구문", "Đảo ngữ và nhấn mạnh"), T("Never/Hardly/Only then 이 문두에 오면 조동사 + 주어 순서가 돼요. It is ~ that 으로 강조해요.", "Never/Hardly/Only then đứng đầu câu thì trợ động từ đứng trước chủ ngữ. Dùng It is ... that để nhấn mạnh."), T("Never have I seen such a view.", "Never have I seen such a view."), l1),
      k.lesson(2, "subj", T("가정법", "Câu giả định"), T("I wish / as if / If 절에서 현재 반대는 과거형, 과거 반대는 had p.p. 를 써요.", "Trong I wish / as if / If, trái với hiện tại dùng quá khứ, trái với quá khứ dùng had p.p."), T("I wish I had studied harder.", "I wish I had studied harder."), l2),
      k.lesson(3, "wh", T("복합관계사와 양보절", "Từ quan hệ ghép và nhượng bộ"), T("whatever, whoever, whichever, however + 형용사 는 '~든지, 아무리 ~해도' 라는 뜻이에요.", "whatever, whoever, whichever, however + tính từ nghĩa là 'dù ... nào / dù ... đến đâu'."), T("However hard it is, I will try.", "However hard it is, I will try."), l3),
      k.lesson(4, "vocab", T("문맥 속 어휘", "Từ vựng trong ngữ cảnh"), T("대조·예시·원인의 단서와 접두사로 낯선 단어의 뜻을 추론해요.", "Suy ra nghĩa từ lạ nhờ manh mối đối lập, ví dụ, nguyên nhân và tiền tố."), T("un-, im- = 아닌", "un-, im- = không"), l4),
      k.lesson(5, "logic", T("글의 논리 전개", "Mạch lập luận của bài"), T("지시어의 대상과 연결어로 글의 흐름을 따라가고, 세부 정보를 모아 결론을 잡아요.", "Lần theo mạch văn nhờ đối tượng của từ chỉ định và từ nối, gom chi tiết thành kết luận."), T("In this way = 이런 방식으로", "In this way = bằng cách này"), l5),
    ],
  });
}
