import { T, BLANK, DIALOG, WRONG, READ, READ_TF, TF, FILL, makeEnglishKit } from "./english-kit.mjs";

/** Middle 2 English: present perfect, passive voice, to-infinitive vs gerund, comparison, reading for topic and detail. */
export function enM2(b) {
  const S = { perf: "e.m2.perf", pass: "e.m2.pass", inf: "e.m2.inf", comp: "e.m2.comp", read: "e.m2.read" };
  b.skill(S.perf, T("현재완료", "Thì hiện tại hoàn thành"));
  b.skill(S.pass, T("수동태", "Câu bị động"), S.perf);
  b.skill(S.inf, T("to부정사와 동명사", "To + động từ nguyên mẫu và V-ing"), S.pass);
  b.skill(S.comp, T("비교급과 최상급", "So sánh hơn và so sánh nhất"), S.inf);
  b.skill(S.read, T("독해: 주제와 세부 정보", "Đọc hiểu: chủ đề và chi tiết"), S.comp);
  const k = makeEnglishKit(b, "m2", S);
  const { mc, tf, write } = k;
  const G = ["grammar"], GC = ["grammar", "context"], GR = ["grammar", "reasoning"];

  /* ------------------------------ 1. present perfect ------------------------------ */
  const RULE1 = T("현재완료는 have/has + 과거분사로 써요. since 는 시작 시점, for 는 기간과 함께 써요.", "Hiện tại hoàn thành dùng have/has + phân từ quá khứ. since đi với mốc thời gian, for đi với khoảng thời gian.");
  const rule1b = T("yesterday, ago 같은 분명한 과거 시점 표현은 현재완료와 함께 쓰지 않아요.", "Các từ chỉ thời điểm quá khứ rõ ràng như yesterday, ago không dùng với hiện tại hoàn thành.");
  const J = "Jisu moved to Daegu in 2021. It is 2026 now.";
  const l1 = [
    mc("perf", 1, "core", 1, G, BLANK("She ____ never eaten sushi."), ["has", "have", "is", "did"], 0, RULE1, T("She 는 3인칭 단수예요.", "She là ngôi thứ ba số ít."), T("주어가 She 이므로 has + eaten (현재완료).", "Chủ ngữ là She nên dùng has + eaten (hiện tại hoàn thành).")),
    mc("perf", 2, "core", 2, G, BLANK("I have studied English ____ three years."), ["for", "since", "from", "ago"], 0, RULE1, T("three years 는 기간이에요.", "three years là một khoảng thời gian."), T("기간(three years) 앞에는 for 를 써요.", "Trước một khoảng thời gian (three years) dùng for.")),
    mc("perf", 3, "core", 2, GR, WRONG, ["He has gone to Paris yesterday.", "She has lived here since 2019.", "They have just finished lunch.", "I have never seen a koala."], 0, rule1b, T("각 문장의 시간 표현을 확인해 보세요.", "Hãy kiểm tra cụm từ chỉ thời gian trong từng câu."), T("yesterday 는 과거 시점이므로 has gone 이 아니라 went 를 써야 해요.", "yesterday là thời điểm quá khứ nên phải dùng went chứ không dùng has gone.")),
    mc("perf", 4, "core", 3, GC, DIALOG("A: Have you ever been to Jeju? B: Yes, I have ____ there twice."), ["been", "gone", "went", "go"], 0, T("'~에 가 본 적이 있다' 는 have been to, '가 버렸다(지금 여기 없다)' 는 have gone to 예요.", "'Đã từng đến' là have been to, còn 'đã đi mất (không còn ở đây)' là have gone to."), T("B 는 제주에 두 번 다녀온 경험을 말하고 있어요.", "B đang nói về kinh nghiệm đã đến Jeju hai lần."), T("경험을 나타내므로 have been 이 알맞아요.", "Diễn tả kinh nghiệm nên dùng have been.")),
    mc("perf", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(J, "How long has Jisu lived in Daegu?"), ["For five years.", "Since five years.", "For 2021.", "Five years ago."], 0, RULE1, T("2026 − 2021 = 5 로 기간을 먼저 구한 뒤 for / since 를 골라요.", "Trước hết tính khoảng thời gian 2026 − 2021 = 5, sau đó chọn for / since."), T("기간 5년이므로 For five years. 가 알맞아요.", "Khoảng thời gian là 5 năm nên For five years. là đúng.")),
  ];
  mc("perf", "v1", "variant", 1, G, BLANK("We ____ lived here since 2018."), ["have", "has", "are", "were"], 0, RULE1, T("We 는 복수 주어예요.", "We là chủ ngữ số nhiều."), T("We + have + lived 로 써요.", "Dùng We + have + lived."));
  tf("perf", "v2", "variant", 2, GR, TF("I have seen him yesterday."), false, rule1b, T("yesterday 와 현재완료를 함께 썼어요.", "Câu dùng yesterday cùng với hiện tại hoàn thành."), T("I saw him yesterday. 처럼 과거형을 써야 해요.", "Phải dùng thì quá khứ: I saw him yesterday."));
  mc("perf", "v3", "variant", 2, G, BLANK("He has ____ his homework already."), ["finished", "finish", "finishing", "finishes"], 0, RULE1, T("has 뒤에는 과거분사가 와요.", "Sau has là phân từ quá khứ."), T("has finished 가 알맞아요.", "has finished là đúng."));
  mc("perf", "d1", "diagnostic", 1, G, BLANK("They ____ just arrived."), ["have", "has", "are", "did"], 0, RULE1, T("They 는 복수예요.", "They là số nhiều."), T("They have just arrived.", "They have just arrived."));
  mc("perf", "d2", "diagnostic", 3, GR, WRONG, ["I have visited Busan last summer.", "She has played the piano for ten years.", "We have already eaten dinner.", "He has never been late."], 0, rule1b, T("last summer 는 과거 시점이에요.", "last summer là thời điểm quá khứ."), T("last summer 와 함께는 visited(과거형)를 써야 해요.", "Với last summer phải dùng thì quá khứ visited."));

  /* ------------------------------ 2. passive voice ------------------------------ */
  const RULE2 = T("수동태는 be동사 + 과거분사(+ by 행위자)로 써요. 시제는 be동사가 결정해요.", "Câu bị động dùng be + phân từ quá khứ (+ by người làm). Thì của câu do động từ be quyết định.");
  const l2 = [
    mc("pass", 1, "core", 1, G, BLANK("The window ____ by Tom."), ["was broken", "broke", "breaks", "was break"], 0, RULE2, T("창문은 깨짐을 '당한' 쪽이에요.", "Cửa sổ là đối tượng bị tác động."), T("was + broken (과거분사) 로 써요.", "Dùng was + broken (phân từ quá khứ).")),
    mc("pass", 2, "core", 2, G, BLANK("English ____ in many countries."), ["is spoken", "speaks", "is speaking", "spoke"], 0, RULE2, T("영어는 '말해지는' 대상이고 현재의 일반적 사실이에요.", "Tiếng Anh là đối tượng được nói và đây là sự thật chung ở hiện tại."), T("현재 수동태 is + spoken.", "Bị động hiện tại: is + spoken.")),
    mc("pass", 3, "core", 2, GR, WRONG, ["The cake was eaten by my brother.", "This book was written by a famous author.", "The letter was send yesterday.", "The room is cleaned every day."], 2, T("수동태의 동사는 be + 과거분사예요. send 의 과거분사는 sent 예요.", "Động từ bị động là be + phân từ quá khứ. Phân từ quá khứ của send là sent."), T("과거분사 자리에 원형이 쓰인 문장을 찾아요.", "Hãy tìm câu dùng động từ nguyên mẫu ở chỗ phân từ quá khứ."), T("was send 가 아니라 was sent 가 맞아요.", "Phải là was sent chứ không phải was send.")),
    mc("pass", 4, "core", 3, GC, DIALOG("A: Who painted this picture? B: It ____ by Picasso."), ["was painted", "painted", "is painting", "was paint"], 0, RULE2, T("그림은 그려진 대상이고, 그린 사람은 by 뒤에 와요.", "Bức tranh là đối tượng được vẽ, người vẽ đứng sau by."), T("과거의 일이므로 was painted.", "Việc xảy ra trong quá khứ nên dùng was painted.")),
    write("pass", 5, "core", 3, ["grammar", "multistep", "reasoning"], FILL(T("능동태 문장을 수동태로 바꿔 빈칸을 채우세요.", "Chuyển câu chủ động sang bị động rồi điền vào chỗ trống."), "Mina cleans the room. → The room ____ by Mina."), ["is cleaned"], RULE2, T("목적어 the room 이 주어가 되고, cleans 는 is cleaned 로 바뀌어요.", "Tân ngữ the room trở thành chủ ngữ và cleans đổi thành is cleaned."), T("현재형이므로 is + cleaned 예요.", "Câu ở thì hiện tại nên dùng is + cleaned.")),
  ];
  mc("pass", "v1", "variant", 1, G, BLANK("The song ____ by millions of people."), ["is loved", "loves", "loved", "is loving"], 0, RULE2, T("노래는 사랑을 '받는' 쪽이에요.", "Bài hát là đối tượng được yêu thích."), T("is + loved.", "is + loved."));
  tf("pass", "v2", "variant", 2, GR, TF("The door was open by the wind."), false, RULE2, T("open 은 과거분사 형태가 아니에요.", "open không phải dạng phân từ quá khứ."), T("was opened by the wind 로 써야 해요.", "Phải viết was opened by the wind."));
  write("pass", "v3", "variant", 2, G, FILL(T("괄호 안의 동사를 알맞은 형태로 바꿔 쓰세요.", "Chia động từ trong ngoặc cho đúng dạng."), "These letters ____ by my grandfather. (write)"), ["were written"], RULE2, T("letters 는 복수이고 과거의 일이에요.", "letters là số nhiều và việc xảy ra trong quá khứ."), T("were + written.", "were + written."));
  mc("pass", "d1", "diagnostic", 1, G, BLANK("This bridge ____ in 1990."), ["was built", "built", "is built", "builds"], 0, RULE2, T("1990년은 과거예요.", "Năm 1990 là quá khứ."), T("was + built.", "was + built."));
  write("pass", "d2", "diagnostic", 3, ["grammar", "multistep"], FILL(T("능동태 문장을 수동태로 바꿔 빈칸을 채우세요.", "Chuyển câu chủ động sang bị động rồi điền vào chỗ trống."), "They made this chair. → This chair ____ by them."), ["was made"], RULE2, T("made 는 과거형이므로 수동태도 과거예요.", "made là thì quá khứ nên câu bị động cũng ở quá khứ."), T("was + made.", "was + made."));

  /* ------------------------------ 3. to-infinitive vs gerund ------------------------------ */
  const RULE3 = T("want, hope, decide 뒤에는 to부정사, enjoy, finish, mind 뒤에는 동명사(-ing)를 써요.", "Sau want, hope, decide dùng to + động từ nguyên mẫu; sau enjoy, finish, mind dùng V-ing.");
  const BEN = "Ben likes swimming. He wants to join the swimming team, but he has not decided when to start.";
  const l3 = [
    mc("inf", 1, "core", 1, G, BLANK("I want ____ a new bike."), ["to buy", "buying", "buy", "bought"], 0, RULE3, T("want 는 to부정사를 목적어로 취해요.", "want đi với to + động từ nguyên mẫu."), T("want to buy 가 알맞아요.", "want to buy là đúng.")),
    mc("inf", 2, "core", 2, G, BLANK("She enjoys ____ to music."), ["listening", "to listen", "listen", "listened"], 0, RULE3, T("enjoy 는 동명사를 목적어로 취해요.", "enjoy đi với V-ing."), T("enjoy listening 이 알맞아요.", "enjoy listening là đúng.")),
    mc("inf", 3, "core", 2, GR, WRONG, ["He decided going home early.", "I hope to see you soon.", "They finished cleaning the room.", "She wants to learn French."], 0, RULE3, T("decide 는 어느 쪽을 취하는지 확인해요.", "Hãy xác định decide đi với dạng nào."), T("decide 뒤에는 to부정사를 써서 decided to go 가 맞아요.", "Sau decide dùng to-V nên phải là decided to go.")),
    mc("inf", 4, "core", 3, ["grammar", "context", "reasoning"], DIALOG("A: Why did you stop on the way? B: I stopped ____ some water because I was thirsty."), ["to buy", "buying", "buy", "bought"], 0, T("stop + to부정사는 '~하기 위해 멈추다', stop + 동명사는 '~하는 것을 멈추다' 예요.", "stop + to-V nghĩa là 'dừng lại để làm gì', stop + V-ing nghĩa là 'ngừng làm việc gì'."), T("물을 사려는 '목적'으로 멈춘 거예요.", "Bạn ấy dừng lại với mục đích mua nước."), T("목적을 나타내므로 stopped to buy 예요.", "Diễn tả mục đích nên dùng stopped to buy.")),
    mc("inf", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(BEN, "Which sentence is TRUE?"), ["Ben wants to join the team.", "Ben has already joined the team.", "Ben dislikes swimming.", "Ben has decided when to start."], 0, T("각 보기를 글의 문장과 하나씩 비교해 보세요.", "Hãy so sánh từng đáp án với các câu trong đoạn văn."), T("'has not decided' 는 아직 정하지 않았다는 뜻이에요.", "'has not decided' nghĩa là chưa quyết định."), T("글에서 Ben 은 팀에 들어가고 싶어 해요(wants to join).", "Trong đoạn văn, Ben muốn tham gia đội (wants to join).")),
  ];
  mc("inf", "v1", "variant", 1, G, BLANK("They finished ____ the project."), ["doing", "to do", "do", "done"], 0, RULE3, T("finish 는 동명사를 취해요.", "finish đi với V-ing."), T("finished doing.", "finished doing."));
  tf("inf", "v2", "variant", 2, GR, TF("I enjoy to swim."), false, RULE3, T("enjoy 뒤에는 동명사를 써요.", "Sau enjoy dùng V-ing."), T("I enjoy swimming. 이 맞아요.", "Phải viết I enjoy swimming."));
  mc("inf", "v3", "variant", 2, G, BLANK("She hopes ____ abroad next year."), ["to study", "studying", "study", "studied"], 0, RULE3, T("hope 는 to부정사를 취해요.", "hope đi với to + động từ nguyên mẫu."), T("hopes to study.", "hopes to study."));
  mc("inf", "d1", "diagnostic", 1, G, BLANK("He avoids ____ late."), ["being", "to be", "be", "been"], 0, RULE3, T("avoid 는 동명사를 취해요.", "avoid đi với V-ing."), T("avoids being late.", "avoids being late."));
  mc("inf", "d2", "diagnostic", 3, GR, BLANK("I'm looking forward to ____ you."), ["seeing", "see", "to see", "saw"], 0, T("look forward to 의 to 는 전치사이므로 뒤에 동명사가 와요.", "Trong look forward to, to là giới từ nên theo sau là V-ing."), T("to 뒤에 동사원형이 아니라 -ing 형이 와야 해요.", "Sau to phải là V-ing chứ không phải động từ nguyên mẫu."), T("I'm looking forward to seeing you.", "I'm looking forward to seeing you."));

  /* ------------------------------ 4. comparison ------------------------------ */
  const RULE4 = T("짧은 형용사는 -er/-est, 긴 형용사는 more/most 를 써요. 비교 대상 뒤에는 than 을 써요.", "Tính từ ngắn thêm -er/-est, tính từ dài dùng more/most. Dùng than để so sánh hai đối tượng.");
  const AMY = "Amy is 150 cm tall. Ben is 158 cm tall. Chris is 154 cm tall.";
  const PRICE = "A bike costs $120. A scooter costs $180. A skateboard costs $90.";
  const l4 = [
    mc("comp", 1, "core", 1, G, BLANK("My bag is ____ than yours."), ["heavier", "heavy", "more heavy", "heaviest"], 0, RULE4, T("than 이 있으므로 비교급이에요. heavy 는 y → ier 로 바꿔요.", "Có than nên dùng so sánh hơn. heavy đổi y thành ier."), T("heavier than.", "heavier than.")),
    mc("comp", 2, "core", 2, G, BLANK("This is the ____ movie I have ever seen."), ["most interesting", "more interesting", "interestinger", "interesting"], 0, RULE4, T("'지금까지 본 것 중 가장' 이므로 최상급이에요. interesting 은 긴 형용사예요.", "'Hay nhất từ trước đến nay' là so sánh nhất. interesting là tính từ dài."), T("the most interesting.", "the most interesting.")),
    mc("comp", 3, "core", 2, GR, WRONG, ["Today is more hot than yesterday.", "He is the tallest in his class.", "This test was easier than the last one.", "She runs faster than me."], 0, RULE4, T("hot 은 짧은 형용사라 more 를 쓰지 않아요.", "hot là tính từ ngắn nên không dùng more."), T("hotter than 이 맞아요(t 를 한 번 더 써요).", "Phải là hotter than (gấp đôi chữ t).")),
    mc("comp", 4, "core", 3, ["grammar", "context", "reasoning"], READ(AMY, "Who is the tallest?"), ["Ben", "Amy", "Chris", "Amy and Chris"], 0, T("세 사람의 키를 모두 비교해 가장 큰 사람을 찾아요.", "So sánh chiều cao của cả ba người để tìm người cao nhất."), T("158 > 154 > 150 이에요.", "158 > 154 > 150."), T("158 cm 인 Ben 이 the tallest 예요.", "Ben cao 158 cm nên là the tallest.")),
    mc("comp", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(PRICE, "Which sentence is correct?"), ["The scooter is more expensive than the bike.", "The skateboard is the most expensive.", "The bike is cheaper than the skateboard.", "The scooter is cheaper than the bike."], 0, RULE4, T("세 가격 $90 < $120 < $180 을 순서대로 놓고 각 보기를 확인해요.", "Sắp xếp ba mức giá $90 < $120 < $180 rồi kiểm tra từng đáp án."), T("$180 > $120 이므로 scooter 가 bike 보다 더 비싸요.", "$180 > $120 nên scooter đắt hơn bike.")),
  ];
  mc("comp", "v1", "variant", 1, G, BLANK("Mt. Everest is the ____ mountain in the world."), ["highest", "higher", "high", "more high"], 0, RULE4, T("'세계에서 가장' 이므로 최상급이에요.", "'Cao nhất thế giới' là so sánh nhất."), T("the highest.", "the highest."));
  tf("comp", "v2", "variant", 2, GR, TF("He is more taller than me."), false, RULE4, T("taller 에는 이미 -er 이 있어요.", "taller đã có -er."), T("more 와 -er 을 함께 쓰지 않아요: taller than me.", "Không dùng cả more và -er: phải là taller than me."));
  mc("comp", "v3", "variant", 2, G, BLANK("She is the ____ student in our class."), ["best", "better", "goodest", "most good"], 0, T("good 의 최상급은 best 예요(불규칙).", "Dạng so sánh nhất của good là best (bất quy tắc)."), T("the 가 있으므로 최상급이에요.", "Có the nên là so sánh nhất."), T("the best student.", "the best student."));
  mc("comp", "d1", "diagnostic", 1, G, BLANK("This room is ____ than that one."), ["bigger", "big", "biggest", "more big"], 0, RULE4, T("than 이 있으므로 비교급이에요.", "Có than nên là so sánh hơn."), T("bigger than.", "bigger than."));
  mc("comp", "d2", "diagnostic", 3, GR, WRONG, ["He is the more famous singer in Korea.", "She is more careful than her brother.", "This is the cheapest shop in town.", "My dog is smaller than yours."], 0, RULE4, T("'~중에서 가장' 이라는 뜻에는 the + 최상급을 써요.", "Nghĩa 'nhất trong ...' dùng the + so sánh nhất."), T("in Korea 가 있으므로 최상급이어야 해요.", "Có in Korea nên phải dùng so sánh nhất."), T("the most famous singer 가 맞아요.", "Phải là the most famous singer."));

  /* ------------------------------ 5. reading: topic and detail ------------------------------ */
  const RULE5 = T("먼저 질문을 읽고, 글에서 단서가 되는 문장을 찾아 확인해요.", "Hãy đọc câu hỏi trước rồi tìm câu chứa manh mối trong đoạn văn.");
  const P1 = "Mina joined the school choir last month. She practices every Tuesday and Thursday after school. Next week, the choir will sing at the city festival. Mina is excited but also a little nervous.";
  const P2 = "Many students use their phones during class. This makes it hard to listen to the teacher. Some schools now ask students to keep their phones in a box until lunch. As a result, students talk more with each other.";
  const l5 = [
    mc("read", 1, "core", 1, ["reading"], READ(P1, "When does Mina practice?"), ["Every Tuesday and Thursday", "Every Monday", "Every weekend", "Every morning"], 0, RULE5, T("practices 가 들어 있는 문장을 찾아요.", "Tìm câu có từ practices."), T("글의 둘째 문장: every Tuesday and Thursday.", "Câu thứ hai: every Tuesday and Thursday.")),
    mc("read", 2, "core", 2, ["reading"], READ(P1, "What will the choir do next week?"), ["Sing at the city festival", "Practice at home", "Join a new school", "Have a party"], 0, RULE5, T("Next week 가 들어 있는 문장을 찾아요.", "Tìm câu có Next week."), T("Next week, the choir will sing at the city festival.", "Next week, the choir will sing at the city festival.")),
    tf("read", 3, "core", 2, ["reading", "reasoning"], READ_TF(P1, "Mina feels only excited."), false, RULE5, T("마지막 문장에서 Mina 의 기분을 확인해요.", "Kiểm tra cảm xúc của Mina ở câu cuối."), T("excited but also a little nervous 이므로 '신나기만 한 것'은 아니에요.", "Cô ấy excited but also a little nervous nên không phải chỉ có hào hứng.")),
    mc("read", 4, "core", 3, ["reading", "context"], READ(P2, "What is the best title for the passage?"), ["Phones in a Box: A New School Rule", "Why Teachers Like Phones", "The History of Smartphones", "How to Cook Lunch"], 0, T("글 전체를 대표하는 제목은 중심 내용을 모두 포함해요.", "Tiêu đề tốt bao quát toàn bộ nội dung chính."), T("학교의 새 규칙(휴대폰을 상자에)이 글의 중심이에요.", "Quy định mới của trường (cất điện thoại vào hộp) là trọng tâm."), T("휴대폰을 상자에 보관하는 새 규칙이 글의 중심 내용이에요.", "Nội dung chính là quy định mới cất điện thoại vào hộp.")),
    mc("read", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(P2, "What happened because of the new rule?"), ["Students talk more with each other.", "Students use phones more.", "Teachers stopped teaching.", "Lunch became longer."], 0, T("As a result 는 '그 결과' 라는 뜻으로, 원인과 결과를 이어 줘요.", "As a result nghĩa là 'kết quả là', nối nguyên nhân với kết quả."), T("새 규칙(원인) → 마지막 문장(결과)", "Quy định mới (nguyên nhân) → câu cuối (kết quả)."), T("As a result 뒤의 내용이 결과예요.", "Nội dung sau As a result chính là kết quả.")),
  ];
  mc("read", "v1", "variant", 1, ["reading"], READ(P1, "How does Mina feel?"), ["Excited and a little nervous", "Angry", "Bored", "Sleepy"], 0, RULE5, T("마지막 문장을 확인해요.", "Xem câu cuối."), T("excited but also a little nervous.", "excited but also a little nervous."));
  tf("read", "v2", "variant", 2, ["reading", "reasoning"], READ_TF(P2, "Some schools keep students' phones in a box until lunch."), true, RULE5, T("셋째 문장을 확인해요.", "Xem câu thứ ba."), T("keep their phones in a box until lunch 와 같은 내용이에요.", "Nội dung giống với keep their phones in a box until lunch."));
  mc("read", "v3", "variant", 2, ["reading"], READ(P2, "Why is it hard to listen to the teacher?"), ["Because students use phones in class.", "Because the room is noisy.", "Because lunch is early.", "Because the teacher is shy."], 0, RULE5, T("This makes it hard 의 This 가 무엇인지 앞 문장에서 찾아요.", "Tìm xem This trong This makes it hard chỉ điều gì ở câu trước."), T("앞 문장: students use their phones during class.", "Câu trước: students use their phones during class."));
  mc("read", "d1", "diagnostic", 1, ["reading"], READ(P1, "When did Mina join the choir?"), ["Last month", "Last year", "Yesterday", "Next week"], 0, RULE5, T("joined 가 있는 문장을 찾아요.", "Tìm câu có joined."), T("joined the school choir last month.", "joined the school choir last month."));
  mc("read", "d2", "diagnostic", 3, ["reading", "reasoning"], READ(P2, "What is the main idea of the passage?"), ["Phone rules can help students focus and talk.", "Phones should be given to teachers.", "Students hate lunch.", "Schools are too noisy."], 0, T("세부 내용이 아니라 글 전체의 요지를 골라요.", "Hãy chọn ý chính của cả đoạn chứ không phải chi tiết nhỏ."), T("문제(휴대폰) → 해결(상자) → 결과(대화)", "Vấn đề (điện thoại) → giải pháp (hộp) → kết quả (trò chuyện)."), T("글은 휴대폰 규칙이 집중과 대화에 도움이 된다고 말해요.", "Đoạn văn cho thấy quy định về điện thoại giúp tập trung và trò chuyện."));

  k.course({
    slug: "grammar-reading", title: T("중2 영어: 시제·수동태·비교·독해", "Tiếng Anh lớp 8: Thì, bị động, so sánh và đọc hiểu"),
    world: { name: T("문장 정원", "Khu vườn câu chữ"), emoji: "🌷", tagline: T("문법의 뼈대를 세우고 짧은 글의 핵심을 읽어요.", "Dựng khung ngữ pháp và nắm ý chính của đoạn văn ngắn.") }, unitTitle: T("중2 영어", "Tiếng Anh lớp 8"),
    lessons: [
      k.lesson(1, "perf", T("현재완료", "Hiện tại hoàn thành"), T("have/has + 과거분사. 경험, 완료, 계속을 나타내고, since(시점)와 for(기간)를 구별해요.", "have/has + phân từ quá khứ. Diễn tả kinh nghiệm, hoàn thành, tiếp diễn; phân biệt since (mốc) và for (khoảng)."), T("I have lived here for five years.", "I have lived here for five years."), l1),
      k.lesson(2, "pass", T("수동태", "Câu bị động"), T("be + 과거분사로 '~되다/당하다' 를 나타내요. 행위자는 by 로 덧붙여요.", "be + phân từ quá khứ diễn tả 'được/bị'. Người thực hiện được thêm bằng by."), T("The room is cleaned by Mina.", "The room is cleaned by Mina."), l2),
      k.lesson(3, "inf", T("to부정사와 동명사", "To-V và V-ing"), T("want, hope, decide + to부정사, enjoy, finish, avoid + 동명사. stop + to V 는 목적, stop + V-ing 는 중단이에요.", "want, hope, decide + to-V; enjoy, finish, avoid + V-ing. stop + to V chỉ mục đích, stop + V-ing chỉ sự ngừng lại."), T("I want to buy a bike. She enjoys singing.", "I want to buy a bike. She enjoys singing."), l3),
      k.lesson(4, "comp", T("비교급과 최상급", "So sánh hơn và nhất"), T("-er/-est 와 more/most. 비교급에는 than, 최상급에는 the 를 써요. good → better → best 는 불규칙이에요.", "-er/-est và more/most. So sánh hơn dùng than, so sánh nhất dùng the. good → better → best là bất quy tắc."), T("hot → hotter → the hottest", "hot → hotter → the hottest"), l4),
      k.lesson(5, "read", T("독해: 주제와 세부 정보", "Đọc hiểu: chủ đề và chi tiết"), T("질문을 먼저 읽고 단서 문장을 찾아요. 제목과 요지는 글 전체를 아우르는 내용이에요.", "Đọc câu hỏi trước rồi tìm câu manh mối. Tiêu đề và ý chính phải bao quát toàn bộ đoạn."), T("As a result = 그 결과", "As a result = kết quả là"), l5),
    ],
  });
}
