import { T, BLANK, DIALOG, WRONG, READ, READ_TF, TF, FILL, makeEnglishKit } from "./english-kit.mjs";

/** High 1 English: perfect tenses, relative adverbs and noun clauses, participial constructions, connectives, main idea and blank inference. */
export function enH1(b) {
  const S = { tense: "e.h1.tense", clause: "e.h1.clause", partc: "e.h1.partc", conn: "e.h1.conn", main: "e.h1.main" };
  b.skill(S.tense, T("완료시제와 완료진행", "Các thì hoàn thành và hoàn thành tiếp diễn"));
  b.skill(S.clause, T("관계부사와 명사절", "Trạng từ quan hệ và mệnh đề danh từ"), S.tense);
  b.skill(S.partc, T("분사구문", "Phân từ cú"), S.clause);
  b.skill(S.conn, T("연결어와 글의 흐름", "Từ nối và mạch văn"), S.partc);
  b.skill(S.main, T("요지 파악과 빈칸 추론", "Nắm ý chính và suy luận chỗ trống"), S.conn);
  const k = makeEnglishKit(b, "h1", S);
  const { mc, tf, write } = k;
  const G = ["grammar"], GC = ["grammar", "context"], GR = ["grammar", "reasoning"], RD = ["reading"];

  /* ------------------------------ 1. perfect tenses ------------------------------ */
  const R1 = T("과거완료(had + 과거분사)는 과거 어느 시점보다 앞선 일, 현재완료진행(have been + -ing)은 과거에 시작해 지금도 계속되는 동작을 나타내요.", "Quá khứ hoàn thành (had + phân từ quá khứ) diễn tả việc xảy ra trước một mốc trong quá khứ; hiện tại hoàn thành tiếp diễn (have been + V-ing) diễn tả hành động bắt đầu trong quá khứ và còn tiếp tục đến nay.");
  const YU = "Yuna started playing the piano in 2018. She still plays it every day. It is 2026 now.";
  const l1 = [
    mc("tense", 1, "core", 1, G, BLANK("When I arrived, the movie ____ already started."), ["had", "has", "have", "was"], 0, R1, T("내가 도착한 시점보다 영화가 먼저 시작했어요.", "Phim đã bắt đầu trước thời điểm tôi đến."), T("과거 시점보다 앞선 일이므로 had + started.", "Việc xảy ra trước mốc quá khứ nên dùng had + started.")),
    mc("tense", 2, "core", 2, G, BLANK("She ____ studying since 8 o'clock."), ["has been", "had", "is", "was been"], 0, R1, T("since 8 o'clock 은 과거에 시작해 지금까지 이어짐을 뜻해요.", "since 8 o'clock cho thấy hành động bắt đầu từ quá khứ và kéo dài đến nay."), T("has been + studying.", "has been + studying.")),
    mc("tense", 3, "core", 2, GR, WRONG, ["When he got home, his wife has cooked dinner.", "By the time we arrived, the bus had left.", "I have been waiting for you for an hour.", "She said that she had lost her wallet."], 0, R1, T("when he got home(과거)보다 요리가 먼저 끝난 일이에요.", "Việc nấu ăn xong trước thời điểm when he got home (quá khứ)."), T("과거 시점 앞선 일에는 has cooked 가 아니라 had cooked 를 써요.", "Việc xảy ra trước mốc quá khứ phải dùng had cooked chứ không dùng has cooked."), T("had cooked 로 고쳐야 해요.", "Phải sửa thành had cooked.")),
    mc("tense", 4, "core", 3, GC, DIALOG("A: Why were you late? B: The train ____ before I got to the station."), ["had left", "has left", "leaves", "was leaving"], 0, R1, T("내가 역에 도착하기 전에 기차가 이미 떠났어요.", "Tàu đã rời đi trước khi tôi đến ga."), T("과거의 한 시점보다 앞선 일이므로 had left.", "Việc xảy ra trước một mốc quá khứ nên dùng had left.")),
    mc("tense", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(YU, "Which sentence is correct?"), ["Yuna has been playing the piano for eight years.", "Yuna had been playing the piano since eight years.", "Yuna has played the piano in 2018.", "Yuna plays the piano for eight years ago."], 0, R1, T("2026 − 2018 = 8 로 기간을 먼저 구하고, 지금도 계속되므로 현재완료진행을 골라요.", "Trước hết tính 2026 − 2018 = 8 năm; vì vẫn tiếp tục nên chọn hiện tại hoàn thành tiếp diễn."), T("기간 앞에는 for, 시점 앞에는 since 를 써요.", "Trước khoảng thời gian dùng for, trước mốc thời gian dùng since.")),
  ];
  mc("tense", "v1", "variant", 1, G, BLANK("By the time he called, I ____ gone to bed."), ["had", "have", "am", "will"], 0, R1, T("그가 전화한 시점보다 내가 먼저 잠자리에 들었어요.", "Tôi đã đi ngủ trước khi anh ấy gọi."), T("had gone.", "had gone."));
  tf("tense", "v2", "variant", 2, GR, TF("I have been knowing her for ten years."), false, T("know 같은 상태동사는 진행형으로 쓰지 않아요.", "Động từ chỉ trạng thái như know không dùng ở dạng tiếp diễn."), T("have been knowing 이 어색해요.", "have been knowing không tự nhiên."), T("I have known her for ten years. 가 맞아요.", "Phải viết I have known her for ten years."));
  mc("tense", "v3", "variant", 2, G, BLANK("They ____ been working here for two years."), ["have", "has", "had been", "are"], 0, R1, T("They 는 복수이고 지금도 일하고 있어요.", "They là số nhiều và vẫn đang làm việc."), T("have been working.", "have been working."));
  mc("tense", "d1", "diagnostic", 1, G, BLANK("She ____ been crying for an hour."), ["has", "have", "had", "is"], 0, R1, T("She 는 3인칭 단수예요.", "She là ngôi thứ ba số ít."), T("has been crying.", "has been crying."));
  mc("tense", "d2", "diagnostic", 3, GR, WRONG, ["She told me that she has seen the film before.", "He had finished his homework before dinner.", "I've been learning Korean for a year.", "We had waited for an hour when the bus came."], 0, R1, T("told(과거)보다 앞선 일에는 과거완료를 써요.", "Việc xảy ra trước told (quá khứ) dùng quá khứ hoàn thành."), T("said / told 뒤의 종속절은 시제를 한 단계 앞으로 보내요.", "Mệnh đề phụ sau said / told lùi một thì."), T("she had seen the film before 로 고쳐야 해요.", "Phải sửa thành she had seen the film before."));

  /* ------------------------------ 2. relative adverbs and noun clauses ------------------------------ */
  const R2 = T("관계부사 where(장소), when(시간), why(이유)는 앞의 명사를 꾸미고 절 안에서 부사 역할을 해요. whether/that 은 명사절을 이끌어요.", "Trạng từ quan hệ where (nơi chốn), when (thời gian), why (lý do) bổ nghĩa cho danh từ phía trước và làm trạng ngữ trong mệnh đề. whether/that dẫn mệnh đề danh từ.");
  const l2 = [
    mc("clause", 1, "core", 1, G, BLANK("This is the town ____ I was born."), ["where", "which", "who", "whose"], 0, R2, T("the town 은 장소예요.", "the town là địa điểm."), T("장소를 나타내므로 where.", "Chỉ nơi chốn nên dùng where.")),
    mc("clause", 2, "core", 2, G, BLANK("I don't know ____ she will come or not."), ["whether", "that", "what", "which"], 0, R2, T("'or not' 과 함께 쓰여 '~인지 아닌지' 를 뜻해요.", "Đi với 'or not' mang nghĩa 'liệu ... hay không'."), T("whether ... or not.", "whether ... or not.")),
    mc("clause", 3, "core", 2, GR, WRONG, ["This is the house which I live.", "This is the house where I live.", "I remember the day when we met.", "Tell me the reason why you left."], 0, T("관계대명사 뒤에는 불완전한 절, 관계부사 뒤에는 완전한 절이 와요.", "Sau đại từ quan hệ là mệnh đề thiếu thành phần; sau trạng từ quan hệ là mệnh đề đầy đủ."), T("I live 는 완전한 절이에요(목적어가 필요 없어요).", "I live là mệnh đề đầy đủ (không cần tân ngữ)."), T("which 대신 where(또는 in which)를 써야 해요.", "Phải dùng where (hoặc in which) thay cho which.")),
    mc("clause", 4, "core", 3, GC, DIALOG("A: Do you know ____ he left so early? B: He had a doctor's appointment."), ["why", "where", "who", "whose"], 0, T("B 의 대답이 '이유' 를 알려 줘요.", "Câu trả lời của B cho biết lý do."), T("이유를 묻는 의문사 / 관계부사는 why.", "Từ để hỏi chỉ lý do là why."), T("why he left so early.", "why he left so early.")),
    write("clause", 5, "core", 3, ["grammar", "multistep", "reasoning"], FILL(T("두 문장을 관계부사를 써서 한 문장으로 만드세요(빈칸에 한 단어).", "Nối hai câu bằng trạng từ quan hệ (điền một từ)."), "This is the park. We played soccer in the park. → This is the park ____ we played soccer."), ["where", "in which"], R2, T("in the park 가 '장소의 부사구' 라서 관계부사로 바꿔요.", "in the park là cụm trạng ngữ chỉ nơi chốn nên đổi thành trạng từ quan hệ."), T("장소이므로 where (= in which).", "Chỉ nơi chốn nên dùng where (= in which).")),
  ];
  mc("clause", "v1", "variant", 1, G, BLANK("I remember the day ____ we first met."), ["when", "where", "why", "who"], 0, R2, T("the day 는 시간이에요.", "the day chỉ thời gian."), T("when.", "when."));
  tf("clause", "v2", "variant", 2, GR, TF("That is the reason why he was absent."), true, R2, T("the reason 뒤에는 why 를 써요.", "Sau the reason dùng why."), T("옳은 문장이에요.", "Câu đúng."));
  mc("clause", "v3", "variant", 2, G, BLANK("She asked ____ I wanted some tea."), ["if", "that", "what", "which"], 0, R2, T("'~인지' 를 뜻하는 if/whether 를 써요.", "Dùng if/whether mang nghĩa 'liệu ...'."), T("asked if.", "asked if."));
  mc("clause", "d1", "diagnostic", 1, G, BLANK("This is the room ____ I study."), ["where", "who", "whose", "what"], 0, R2, T("the room 은 장소예요.", "the room là địa điểm."), T("where.", "where."));
  mc("clause", "d2", "diagnostic", 3, GR, BLANK("The fact ____ he lied surprised everyone."), ["that", "which", "what", "where"], 0, T("fact 와 같은 명사 뒤의 that 절은 그 내용을 설명하는 동격절이에요.", "Mệnh đề that sau danh từ như fact là mệnh đề đồng vị giải thích nội dung của danh từ."), T("that 뒤의 절이 완전해요.", "Mệnh đề sau that đầy đủ thành phần."), T("The fact that he lied ...", "The fact that he lied ..."));

  /* ------------------------------ 3. participial constructions ------------------------------ */
  const R3 = T("분사구문은 접속사와 주어를 줄이고 동사를 -ing 로 바꿔요. 부사절과 주절의 주어가 같을 때 써요.", "Phân từ cú rút gọn liên từ và chủ ngữ, đổi động từ thành V-ing. Dùng khi hai mệnh đề có cùng chủ ngữ.");
  const l3 = [
    mc("partc", 1, "core", 1, G, BLANK("____ the news, she started to cry."), ["Hearing", "Heard", "Hear", "To hear"], 0, R3, T("'소식을 듣고(듣자마자)' 라는 뜻이에요.", "Nghĩa là 'khi nghe tin'."), T("능동이므로 -ing 형 Hearing.", "Mang nghĩa chủ động nên dùng dạng -ing: Hearing.")),
    mc("partc", 2, "core", 2, G, BLANK("____ TV, he fell asleep."), ["Watching", "Watched", "Watch", "Watches"], 0, R3, T("'TV를 보다가' 라는 뜻이에요.", "Nghĩa là 'trong lúc xem TV'."), T("Watching TV, he fell asleep.", "Watching TV, he fell asleep.")),
    mc("partc", 3, "core", 2, GR, WRONG, ["Walking down the street, a car hit me.", "Walking down the street, I saw an old friend.", "Feeling tired, she went to bed early.", "Having finished lunch, we went for a walk."], 0, T("분사구문의 의미상 주어는 주절의 주어와 같아야 해요.", "Chủ ngữ ngầm của phân từ cú phải trùng với chủ ngữ của mệnh đề chính."), T("'길을 걷고 있던' 것이 누구(무엇)인지 확인해요.", "Hãy xem ai (cái gì) đang đi bộ trên đường."), T("차가 걷고 있었다는 뜻이 되어 어색해요. Walking ..., I was hit by a car. 로 써야 해요.", "Câu thành nghĩa chiếc xe đang đi bộ nên sai. Phải viết: Walking ..., I was hit by a car.")),
    mc("partc", 4, "core", 3, GC, DIALOG("A: Why did you leave early? B: ____ sick, I went home."), ["Feeling", "Felt", "Feel", "To feel"], 0, R3, T("'아파서' 라는 이유를 나타내요.", "Diễn tả lý do 'vì thấy ốm'."), T("Because I felt sick → Feeling sick.", "Because I felt sick → Feeling sick.")),
    write("partc", 5, "core", 3, ["grammar", "multistep"], FILL(T("다음 문장을 분사구문으로 바꿔 빈칸에 한 단어를 쓰세요.", "Chuyển câu sau sang phân từ cú, điền một từ vào chỗ trống."), "Because she was tired, Mia went to bed early. → ____ tired, Mia went to bed early."), ["Being", "being"], R3, T("Because 와 she 를 지우고 was 를 -ing 형으로 바꿔요.", "Bỏ Because và she, đổi was thành dạng -ing."), T("was → Being.", "was → Being.")),
  ];
  mc("partc", "v1", "variant", 1, G, BLANK("____ the door, he went out."), ["Opening", "Opened", "Open", "To opened"], 0, R3, T("'문을 열고' 라는 뜻이에요.", "Nghĩa là 'mở cửa rồi'."), T("Opening.", "Opening."));
  tf("partc", "v2", "variant", 2, GR, TF("Seeing the police, the thief ran away."), true, R3, T("보고 도망친 사람이 같은 사람(도둑)이에요.", "Người nhìn thấy và người bỏ chạy là cùng một người (tên trộm)."), T("올바른 분사구문이에요.", "Phân từ cú đúng."));
  mc("partc", "v3", "variant", 2, G, BLANK("____ his homework, he went out to play."), ["Having finished", "Finish", "Finished having", "To finish"], 0, T("앞선 일은 having + 과거분사로 나타내요.", "Việc xảy ra trước dùng having + phân từ quá khứ."), T("숙제를 먼저 끝낸 뒤 놀러 나갔어요.", "Làm xong bài tập rồi mới đi chơi."), T("Having finished.", "Having finished."));
  mc("partc", "d1", "diagnostic", 1, G, BLANK("____ in Seoul, I visited many places."), ["Staying", "Stayed", "Stay", "To stay"], 0, R3, T("'서울에 머무는 동안' 이라는 뜻이에요.", "Nghĩa là 'trong lúc ở Seoul'."), T("Staying.", "Staying."));
  mc("partc", "d2", "diagnostic", 3, GR, BLANK("____ by the teacher, the student felt proud."), ["Praised", "Praising", "Praise", "To praise"], 0, T("의미상 주어가 '~을 받는' 입장이면 과거분사로 시작해요.", "Khi chủ ngữ ngầm là người nhận hành động thì bắt đầu bằng phân từ quá khứ."), T("학생은 칭찬을 '받은' 쪽이에요.", "Học sinh là người được khen."), T("Being praised → Praised (수동).", "Being praised → Praised (bị động)."));

  /* ------------------------------ 4. connectives ------------------------------ */
  const R4 = T("however(그러나), therefore(그러므로), for example(예를 들어), in addition(게다가)처럼 앞뒤 문장의 관계를 알려 주는 연결어를 골라요.", "Chọn từ nối cho biết quan hệ giữa các câu: however (tuy nhiên), therefore (vì vậy), for example (ví dụ), in addition (hơn nữa).");
  const PLASTIC = "Plastic bags are cheap and light. ____ they harm sea animals. ____ many cities now ban them.";
  const l4 = [
    mc("conn", 1, "core", 1, G, BLANK("I was hungry. ____, I made a sandwich."), ["So", "But", "Or", "Although"], 0, R4, T("배가 고픈 것이 원인이고 샌드위치를 만든 것이 결과예요.", "Đói là nguyên nhân, làm bánh sandwich là kết quả."), T("결과를 이끄는 연결어 So.", "Từ nối chỉ kết quả: So.")),
    mc("conn", 2, "core", 2, G, BLANK("He studied hard. ____, he failed the exam."), ["However", "Therefore", "In addition", "For example"], 0, R4, T("열심히 공부했는데 결과가 기대와 반대예요.", "Học chăm chỉ nhưng kết quả trái với mong đợi."), T("대조를 나타내는 However.", "Từ nối chỉ sự đối lập: However.")),
    mc("conn", 3, "core", 2, GR, BLANK("Many animals sleep a lot. ____, koalas sleep up to 20 hours a day."), ["For example", "However", "Therefore", "Instead"], 0, R4, T("뒤 문장이 앞 문장의 구체적인 사례인지 확인해요.", "Xem câu sau có phải ví dụ cụ thể cho câu trước không."), T("코알라는 '많이 자는 동물' 의 한 예예요.", "Koala là một ví dụ về động vật ngủ nhiều."), T("예시를 나타내는 For example.", "Từ nối chỉ ví dụ: For example.")),
    mc("conn", 4, "core", 3, GC, BLANK("Online classes are convenient. ____, some students find it hard to stay focused."), ["However", "Therefore", "For example", "In addition"], 0, R4, T("장점 뒤에 단점이 이어져요.", "Sau ưu điểm là nhược điểm."), T("대조의 연결어 However.", "Từ nối đối lập: However.")),
    mc("conn", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(PLASTIC, "Which pair fits the blanks in order?"), ["However / As a result", "Therefore / However", "For example / In addition", "In addition / Instead"], 0, R4, T("각 빈칸 앞뒤 문장의 관계(대조, 결과)를 차례로 파악해요.", "Lần lượt xác định quan hệ (đối lập, kết quả) giữa các câu quanh mỗi chỗ trống."), T("① 값싸다 ↔ 해롭다(대조) ② 해롭다 → 금지한다(결과)", "① rẻ ↔ có hại (đối lập) ② có hại → bị cấm (kết quả)."), T("첫째는 대조(However), 둘째는 결과(As a result)예요.", "Chỗ trống đầu là đối lập (However), chỗ thứ hai là kết quả (As a result).")),
  ];
  mc("conn", "v1", "variant", 1, G, BLANK("It was raining. ____, we stayed inside."), ["So", "But", "Or", "Although"], 0, R4, T("비가 와서 안에 머물렀어요.", "Trời mưa nên ở trong nhà."), T("So.", "So."));
  mc("conn", "v2", "variant", 2, G, BLANK("She is smart. ____, she is very kind."), ["In addition", "However", "Instead", "Otherwise"], 0, R4, T("긍정적인 내용을 덧붙여요.", "Bổ sung thêm một điều tích cực."), T("In addition.", "In addition."));
  tf("conn", "v3", "variant", 2, GR, TF("I like coffee. However, I drink it every day."), false, R4, T("However 는 앞 문장과 반대되는 내용 앞에 써요.", "However đứng trước nội dung trái ngược với câu trước."), T("앞뒤 내용이 반대가 아니에요.", "Hai câu không hề trái ngược."), T("So 나 In fact 가 더 자연스러워요.", "So hoặc In fact tự nhiên hơn."));
  mc("conn", "d1", "diagnostic", 1, G, BLANK("I'm tired. ____, I will go to bed early."), ["So", "But", "Or", "Although"], 0, R4, T("피곤해서 일찍 자겠다는 뜻이에요.", "Mệt nên sẽ đi ngủ sớm."), T("So.", "So."));
  mc("conn", "d2", "diagnostic", 3, GR, BLANK("The shop looked cheap. ____, the quality was excellent."), ["However", "Therefore", "For example", "As a result"], 0, R4, T("값싸 보이는 것과 품질이 훌륭하다는 것은 반대 방향이에요.", "Trông rẻ và chất lượng tuyệt vời là hai điều ngược nhau."), T("However.", "However."));

  /* ------------------------------ 5. main idea and blank inference ------------------------------ */
  const R5 = T("글의 요지는 반복되는 주장과 However 뒤의 내용에 드러나요. 빈칸은 앞뒤 문장의 논리 관계를 이어 추론해요.", "Ý chính thường nằm ở điều được lặp lại và nội dung sau However. Với chỗ trống, hãy suy luận từ quan hệ logic giữa các câu.");
  const PA = "People often think that being busy means being successful. However, research shows that people who take regular breaks solve problems faster and make fewer mistakes. Rest is not a waste of time; it is part of good work.";
  const PB = "A new café in our town gives a free drink to customers who bring their own cup. The café owner explained that they used to throw away hundreds of paper cups every day. By offering a reward, she hopes more people will ____.";
  const l5 = [
    mc("main", 1, "core", 1, RD, READ(PA, "According to the passage, what do people often think?"), ["Being busy means being successful.", "Breaks are necessary.", "Mistakes are good.", "Work is boring."], 0, R5, T("첫 문장을 확인해요.", "Xem câu đầu tiên."), T("People often think that ... 바로 뒤가 답이에요.", "Đáp án nằm ngay sau People often think that ...")),
    mc("main", 2, "core", 2, RD, READ(PA, "According to the research, people who take breaks ____."), ["solve problems faster", "work longer hours", "sleep less", "avoid all work"], 0, R5, T("research shows 가 들어 있는 문장을 찾아요.", "Tìm câu có research shows."), T("research shows that people who take regular breaks solve problems faster.", "research shows that people who take regular breaks solve problems faster.")),
    tf("main", 3, "core", 2, ["reading", "reasoning"], READ_TF(PA, "The writer thinks rest is a waste of time."), false, R5, T("마지막 문장에서 글쓴이의 의견을 확인해요.", "Xem ý kiến của tác giả ở câu cuối."), T("Rest is not a waste of time 이라고 분명히 말했어요.", "Tác giả nói rõ Rest is not a waste of time.")),
    mc("main", 4, "core", 3, ["reading", "context", "reasoning"], READ(PA, "What is the main idea of the passage?"), ["Taking regular breaks improves our work.", "Busy people are always successful.", "Research is not reliable.", "Mistakes cannot be avoided."], 0, R5, T("However 뒤의 내용과 마지막 문장이 글쓴이의 주장이에요.", "Nội dung sau However và câu cuối là quan điểm của tác giả."), T("통념(바쁨=성공)을 뒤집고 휴식의 가치를 말해요.", "Bài phản bác quan niệm (bận = thành công) và nói về giá trị của nghỉ ngơi."), T("요지는 규칙적인 휴식이 일의 질을 높인다는 것이에요.", "Ý chính là nghỉ ngơi đều đặn nâng cao chất lượng công việc.")),
    mc("main", 5, "core", 3, ["reading", "multistep", "reasoning"], READ(PB, "Which is best for the blank?"), ["reuse their cups", "buy more paper cups", "stop drinking coffee", "visit the café less often"], 0, R5, T("문제 상황(종이컵을 많이 버림) → 해결책(컵을 가져오면 보상) → 기대 효과를 이어서 생각해요.", "Nối vấn đề (vứt nhiều cốc giấy) → giải pháp (thưởng khi mang cốc) → kết quả mong đợi."), T("보상은 '자기 컵을 가져오는 행동' 을 늘리려는 거예요.", "Phần thưởng nhằm khuyến khích mang cốc riêng."), T("자기 컵을 다시 쓰도록(reuse) 하려는 것이므로 reuse their cups.", "Mục đích là khuyến khích dùng lại cốc nên đáp án là reuse their cups.")),
  ];
  mc("main", "v1", "variant", 1, RD, READ(PA, "What do breaks help people do?"), ["Solve problems faster", "Sleep all day", "Skip work", "Make more mistakes"], 0, R5, T("research shows 문장을 확인해요.", "Xem câu research shows."), T("solve problems faster.", "solve problems faster."));
  tf("main", "v2", "variant", 2, ["reading", "reasoning"], READ_TF(PB, "The café gives a free drink to customers who bring their own cup."), true, R5, T("첫 문장을 확인해요.", "Xem câu đầu."), T("글에 그대로 나와 있어요.", "Có trong bài đúng như vậy."));
  mc("main", "v3", "variant", 2, RD, READ(PB, "Why did the owner start this idea?"), ["She wanted to throw away fewer paper cups.", "She wanted to sell more coffee.", "She wanted to close the café.", "She wanted to hire more people."], 0, R5, T("owner explained 뒤의 내용을 확인해요.", "Xem nội dung sau owner explained."), T("hundreds of paper cups 를 버리고 있었어요.", "Quán vứt hàng trăm cốc giấy."));
  mc("main", "d1", "diagnostic", 1, RD, READ(PB, "What do customers get for bringing their own cup?"), ["A free drink", "A free meal", "A new cup", "Nothing"], 0, R5, T("첫 문장에서 보상이 무엇인지 확인해요.", "Xem phần thưởng ở câu đầu."), T("a free drink.", "a free drink."));
  mc("main", "d2", "diagnostic", 3, ["reading", "reasoning"], READ(PA, "Which sentence best matches the writer's opinion?"), ["Rest is part of good work.", "Work is more important than rest.", "Everyone should work without breaks.", "Research is a waste of time."], 0, R5, T("마지막 문장이 글쓴이의 의견을 요약해요.", "Câu cuối tóm tắt ý kiến của tác giả."), T("it is part of good work.", "it is part of good work."));

  k.course({
    slug: "grammar-reading", title: T("고1 영어: 시제·분사구문·연결어·요지 추론", "Tiếng Anh lớp 10: Thì, phân từ cú, từ nối và suy luận ý chính"),
    world: { name: T("논리의 다리", "Cây cầu logic"), emoji: "🌉", tagline: T("문장을 정교하게 다듬고 글의 흐름과 요지를 읽어요.", "Trau chuốt câu văn và đọc mạch văn cùng ý chính.") }, unitTitle: T("고1 영어", "Tiếng Anh lớp 10"),
    lessons: [
      k.lesson(1, "tense", T("완료시제와 완료진행", "Thì hoàn thành và tiếp diễn"), T("had + p.p. 는 과거보다 앞선 일, have been -ing 는 지금까지 계속되는 동작이에요.", "had + p.p. chỉ việc xảy ra trước một mốc quá khứ, have been -ing chỉ hành động kéo dài đến nay."), T("I have been waiting for an hour.", "I have been waiting for an hour."), l1),
      k.lesson(2, "clause", T("관계부사와 명사절", "Trạng từ quan hệ và mệnh đề danh từ"), T("where / when / why 는 부사 역할의 관계사이고, whether / that 은 명사절을 이끌어요.", "where / when / why là từ quan hệ làm trạng ngữ; whether / that dẫn mệnh đề danh từ."), T("This is the town where I was born.", "This is the town where I was born."), l2),
      k.lesson(3, "partc", T("분사구문", "Phân từ cú"), T("접속사와 주어를 줄이고 동사를 -ing 로 바꿔요. 의미상 주어가 같아야 해요.", "Rút gọn liên từ và chủ ngữ, đổi động từ thành V-ing; chủ ngữ ngầm phải trùng với chủ ngữ chính."), T("Feeling sick, I went home.", "Feeling sick, I went home."), l3),
      k.lesson(4, "conn", T("연결어와 글의 흐름", "Từ nối và mạch văn"), T("원인–결과(so, therefore), 대조(however), 예시(for example), 첨가(in addition)를 구별해요.", "Phân biệt nguyên nhân–kết quả (so, therefore), đối lập (however), ví dụ (for example), bổ sung (in addition)."), T("However = 그러나", "However = tuy nhiên"), l4),
      k.lesson(5, "main", T("요지 파악과 빈칸 추론", "Ý chính và suy luận chỗ trống"), T("통념을 뒤집는 However 이하와 마지막 문장에 요지가 있어요. 빈칸은 문제 → 해결 → 결과의 흐름으로 추론해요.", "Ý chính nằm sau However và ở câu cuối. Với chỗ trống, suy luận theo mạch vấn đề → giải pháp → kết quả."), T("문제 → 해결 → 효과", "vấn đề → giải pháp → hiệu quả"), l5),
    ],
  });
}
