import { T, tex, term, poly, makeMathKit, ONE, WHICH_WRONG } from "./math-kit.mjs";

const P = T;
const DEC = T("(소수로 써 주세요. 예: 0.25)", "(nhập dưới dạng số thập phân, ví dụ 0,25)");
const r4 = (x) => Number(x.toFixed(4));
/** definite integral of a polynomial given by descending coefficients */
const defInt = (cs, a, b) => { const n = cs.length - 1; return cs.reduce((acc, c, i) => { const p = n - i + 1; return acc + (c * (b ** p - a ** p)) / p; }, 0); };
const gcdI = (a, c) => (c === 0 ? a : gcdI(c, a % c));

/** High 3 (calculus II + probability and statistics): integrals and areas, geometric series, conditional probability, binomial and normal distributions. */
export function h3(b) {
  const S = { int: "m.h3.int", area: "m.h3.area", ser: "m.h3.ser", cond: "m.h3.cond", norm: "m.h3.norm" };
  b.skill(S.int, T("부정적분과 정적분", "Nguyên hàm và tích phân xác định"));
  b.skill(S.area, T("정적분의 활용", "Ứng dụng của tích phân"), S.int);
  b.skill(S.ser, T("등비급수", "Chuỗi cấp số nhân"), S.area);
  b.skill(S.cond, T("조건부확률과 독립", "Xác suất có điều kiện và độc lập"), S.ser);
  b.skill(S.norm, T("이항분포와 정규분포", "Phân phối nhị thức và phân phối chuẩn"), S.cond);
  const K = makeMathKit(b, "h3", S);
  const { numeric, choice, truefalse } = K;

  /* ------------------------------ 1. indefinite and definite integrals ------------------------------ */
  const defint = (n, role, d, cs, a, bb) => numeric({ k: "int", n, role, d, fam: "int-def", prompt: P(`${tex(`\\int_{${a}}^{${bb}} (${poly(cs)})\\,dx`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\int_{${a}}^{${bb}} (${poly(cs)})\\,dx`)} là bao nhiêu? ${ONE.vi}`), value: defInt(cs, a, bb), tol: 1e-6,
    hints: [P("각 항의 부정적분 $\\int x^n dx=\\frac{x^{n+1}}{n+1}$ 을 구해요.", "Tìm nguyên hàm từng hạng tử: $\\int x^n dx=\\frac{x^{n+1}}{n+1}$."), P("위끝 값에서 아래끝 값을 빼요.", "Lấy giá trị tại cận trên trừ giá trị tại cận dưới.")], expl: P(`계산하면 ${defInt(cs, a, bb)} 이에요.`, `Tính ra được ${defInt(cs, a, bb)}.`) });
  const primitive = (n, role, d, cs, c0, x0) => { const m = cs.length; const F = [...cs.map((c, i) => c / (m - i)), c0]; const val = F.reduce((acc, c) => acc * x0 + c, 0);
    return numeric({ k: "int", n, role, d, fam: "int-prim", tags: ["multistep"], prompt: P(`$f(x)=${poly(cs)}$ 이고 $F'(x)=f(x)$, $F(0)=${c0}$ 일 때 $F(${x0})$ 의 값은? ${ONE.ko}`, `Cho $f(x)=${poly(cs)}$ và $F'(x)=f(x)$, $F(0)=${c0}$. Tính $F(${x0})$. ${ONE.vi}`), value: val, tol: 1e-6,
    hints: [P("$F(x)=\\int f(x)dx$ 에 적분상수 $C$ 가 붙어요.", "$F(x)=\\int f(x)dx$ có thêm hằng số tích phân $C$."), P("$F(0)$ 값으로 $C$ 를 정한 뒤 $x$ 를 대입해요.", "Dùng $F(0)$ để xác định $C$ rồi thay $x$.")], expl: P(`$F(x)=${poly(F)}$ 이므로 $F(${x0})=${val}$.`, `$F(x)=${poly(F)}$ nên $F(${x0})=${val}$.`) }); };
  const wrongInt = (n, role, d, which) => { const trues = [tex("\\int_a^a f(x)\\,dx=0"), tex("\\int_a^b f(x)\\,dx=-\\int_b^a f(x)\\,dx"), tex("\\int_a^b f(x)\\,dx+\\int_b^c f(x)\\,dx=\\int_a^c f(x)\\,dx")]; const falses = [tex("\\int_a^b f(x)g(x)\\,dx=\\int_a^b f(x)\\,dx\\times\\int_a^b g(x)\\,dx"), tex("\\int_a^b f(x)\\,dx=\\int_b^a f(x)\\,dx")];
    return choice({ k: "int", n, role, d, fam: "int-wrong", tags: ["reasoning"], prompt: WHICH_WRONG, right: falses[which], wrong: trues,
      hints: [P("정적분의 기본 성질(위끝·아래끝 교환, 구간 나누기)을 떠올려 보세요.", "Hãy nhớ các tính chất cơ bản của tích phân xác định (đổi cận, chia khoảng)."), P("간단한 함수 $f(x)=1$ 로 각 식을 시험해 보세요.", "Thử từng đẳng thức với hàm đơn giản $f(x)=1$.")], expl: which === 0 ? P("곱의 적분은 적분의 곱과 같지 않아요. 예: $f=g=1$, $[0,2]$ 에서 좌변 2, 우변 4.", "Tích phân của tích không bằng tích của các tích phân. Ví dụ $f=g=1$ trên $[0,2]$: vế trái 2, vế phải 4.") : P("위끝과 아래끝을 바꾸면 부호가 바뀌어요.", "Đổi cận thì đổi dấu.") }); };
  const distance = (n, role, d, a) => numeric({ k: "int", n, role, d, fam: "int-dist", tags: ["context", "multistep"], prompt: P(`수직선 위를 움직이는 점의 속도가 $v(t)=${a}t-t^2$ (m/s)입니다. 출발 후 ${a}초 동안 점이 움직인 거리는 몇 m일까요? (이 구간에서 $v\\ge 0$) ${ONE.ko}`, `Một điểm chuyển động trên trục số có vận tốc $v(t)=${a}t-t^2$ (m/s). Quãng đường điểm đi được trong ${a} giây đầu là bao nhiêu mét? (Trên khoảng này $v\\ge 0$) ${ONE.vi}`), value: defInt([-1, a, 0], 0, a), tol: 1e-6,
    hints: [P("움직인 거리는 속도의 정적분이에요.", "Quãng đường đi được là tích phân xác định của vận tốc."), P(`$\\int_0^{${a}}(${a}t-t^2)dt$ 를 계산해요.`, `Tính $\\int_0^{${a}}(${a}t-t^2)dt$.`)], expl: P(`$\\left[\\frac{${a}}{2}t^2-\\frac{t^3}{3}\\right]_0^{${a}}=${defInt([-1, a, 0], 0, a)}$ (m).`, `$\\left[\\frac{${a}}{2}t^2-\\frac{t^3}{3}\\right]_0^{${a}}=${defInt([-1, a, 0], 0, a)}$ (m).`) });
  const combine = (n, role, d, i1, i2, c0, p) => numeric({ k: "int", n, role, d, fam: "int-combine", tags: ["multistep", "reasoning"], prompt: P(`$\\int_0^{${p}} f(x)\\,dx=${i1}$, $\\int_{${p}}^{${2 * p + 1}} f(x)\\,dx=${i2}$ 일 때 $\\int_0^{${2 * p + 1}} \\left(2f(x)+${c0}\\right)dx$ 의 값은? ${ONE.ko}`, `Biết $\\int_0^{${p}} f(x)\\,dx=${i1}$ và $\\int_{${p}}^{${2 * p + 1}} f(x)\\,dx=${i2}$. Tính $\\int_0^{${2 * p + 1}} \\left(2f(x)+${c0}\\right)dx$. ${ONE.vi}`), value: 2 * (i1 + i2) + c0 * (2 * p + 1),
    hints: [P("먼저 구간을 합쳐 $\\int_0^{" + (2 * p + 1) + "} f(x)dx$ 를 구해요.", "Trước hết gộp khoảng để tìm $\\int_0^{" + (2 * p + 1) + "} f(x)dx$."), P("상수 " + c0 + " 의 적분은 " + c0 + "×(구간의 길이)예요.", "Tích phân của hằng số " + c0 + " là " + c0 + "×(độ dài khoảng).")], expl: P(`$2(${i1}+${i2})+${c0}\\times ${2 * p + 1}=${2 * (i1 + i2) + c0 * (2 * p + 1)}$.`, `$2(${i1}+${i2})+${c0}\\times ${2 * p + 1}=${2 * (i1 + i2) + c0 * (2 * p + 1)}$.`) });
  const l1 = [defint(1, "core", 1, [2, 1], 0, 2), primitive(2, "core", 2, [6, -4, 1], 2, 1), wrongInt(3, "core", 2, 0), distance(4, "core", 3, 6), combine(5, "core", 3, 5, 7, 1, 2)];
  defint("v1", "variant", 1, [3, 0], 1, 3); primitive("v2", "variant", 2, [4, 2], 1, 2); wrongInt("v3", "variant", 2, 1); distance("v4", "variant", 3, 3);
  defint("d1", "diagnostic", 1, [1, 0], 0, 3); primitive("d2", "diagnostic", 2, [3, 0, 1], 0, 2); combine("d3", "diagnostic", 4, 3, 4, 2, 1);

  /* ------------------------------ 2. areas ------------------------------ */
  const areaUnder = (n, role, d, k, e) => numeric({ k: "area", n, role, d, fam: "area-under", prompt: P(`곡선 $y=x^${e}$ 과 $x$축, 직선 $x=${k}$ 로 둘러싸인 부분의 넓이는? ${ONE.ko}`, `Diện tích hình phẳng giới hạn bởi đường cong $y=x^${e}$, trục hoành và đường thẳng $x=${k}$ là bao nhiêu? ${ONE.vi}`), value: k ** (e + 1) / (e + 1), tol: 1e-6,
    hints: [P("넓이는 $\\int_0^k x^n dx$ 로 구해요.", "Diện tích bằng $\\int_0^k x^n dx$."), P(`$\\frac{${k}^{${e + 1}}}{${e + 1}}$`, `$\\frac{${k}^{${e + 1}}}{${e + 1}}$`)], expl: P(`$\\int_0^{${k}} x^${e}dx=\\frac{${k ** (e + 1)}}{${e + 1}}=${k ** (e + 1) / (e + 1)}$.`, `$\\int_0^{${k}} x^${e}dx=\\frac{${k ** (e + 1)}}{${e + 1}}=${k ** (e + 1) / (e + 1)}$.`) });
  const parabola = (n, role, d, k) => numeric({ k: "area", n, role, d, fam: "area-parabola", tags: ["multistep"], prompt: P(`곡선 $y=${k}x-x^2$ 과 $x$축으로 둘러싸인 부분의 넓이는? ${ONE.ko}`, `Diện tích hình phẳng giới hạn bởi đường cong $y=${k}x-x^2$ và trục hoành là bao nhiêu? ${ONE.vi}`), value: k ** 3 / 6, tol: 1e-6,
    hints: [P(`먼저 $x$축과의 교점 $x=0,\\ ${k}$ 를 구해요.`, `Trước hết tìm giao điểm với trục hoành: $x=0,\\ ${k}$.`), P(`$\\int_0^{${k}}(${k}x-x^2)dx$ 를 계산해요.`, `Tính $\\int_0^{${k}}(${k}x-x^2)dx$.`)], expl: P(`$\\left[\\frac{${k}}{2}x^2-\\frac{x^3}{3}\\right]_0^{${k}}=${k ** 3 / 6}$.`, `$\\left[\\frac{${k}}{2}x^2-\\frac{x^3}{3}\\right]_0^{${k}}=${k ** 3 / 6}$.`) });
  const signed = (n, role, d, k) => choice({ k: "area", n, role, d, fam: "area-signed", tags: ["reasoning"], prompt: P(`$f(x)=x-${k}$ 에 대하여 $\\int_0^{${2 * k}} f(x)\\,dx$ 의 값과, $y=f(x)$ 와 $x$축, $x=0$, $x=${2 * k}$ 로 둘러싸인 넓이를 바르게 짝지은 것은?`, `Với $f(x)=x-${k}$, cặp giá trị nào đúng cho $\\int_0^{${2 * k}} f(x)\\,dx$ và diện tích hình giới hạn bởi $y=f(x)$, trục hoành, $x=0$, $x=${2 * k}$?`), right: P(`정적분 $0$, 넓이 $${k * k}$`, `Tích phân $0$, diện tích $${k * k}$`),
    wrong: [P(`정적분 $${k * k}$, 넓이 $${k * k}$`, `Tích phân $${k * k}$, diện tích $${k * k}$`), P(`정적분 $0$, 넓이 $0$`, `Tích phân $0$, diện tích $0$`), P(`정적분 $${-k * k}$, 넓이 $${k * k}$`, `Tích phân $${-k * k}$, diện tích $${k * k}$`)],
    hints: [P("그래프가 $x$축 위·아래에 있는 부분의 정적분은 부호가 달라요.", "Tích phân phần đồ thị ở trên và dưới trục hoành có dấu khác nhau."), P("넓이는 구간을 나누어 절댓값을 취한 뒤 더해요.", "Diện tích: chia khoảng, lấy giá trị tuyệt đối rồi cộng lại.")], expl: P(`$[0,${k}]$ 에서는 $-${k * k / 2}$, $[${k},${2 * k}]$ 에서는 $+${k * k / 2}$ 라 정적분은 0이지만 넓이는 ${k * k / 2}+${k * k / 2}=${k * k}$ 예요.`, `Trên $[0,${k}]$ được $-${k * k / 2}$, trên $[${k},${2 * k}]$ được $+${k * k / 2}$ nên tích phân bằng 0 nhưng diện tích là ${k * k / 2}+${k * k / 2}=${k * k}$.`) });
  const tank = (n, role, d, q, c0, t) => numeric({ k: "area", n, role, d, fam: "area-tank", tags: ["context", "multistep"], prompt: P(`물탱크에 물이 들어오는 속도가 $r(t)=${q}t^2+${c0}$ (L/분)입니다. 처음 ${t}분 동안 들어온 물의 양은 몇 L일까요? ${ONE.ko}`, `Nước chảy vào bể với tốc độ $r(t)=${q}t^2+${c0}$ (L/phút). Trong ${t} phút đầu, lượng nước chảy vào là bao nhiêu lít? ${ONE.vi}`), value: defInt([q, 0, c0], 0, t), tol: 1e-6,
    hints: [P("들어온 양은 속도 $r(t)$ 의 정적분이에요.", "Lượng nước bằng tích phân của tốc độ $r(t)$."), P(`$\\int_0^{${t}}(${q}t^2+${c0})dt$`, `$\\int_0^{${t}}(${q}t^2+${c0})dt$`)], expl: P(`$\\left[${q / 3 === 1 ? "" : q / 3 === Math.floor(q / 3) ? q / 3 : `\\frac{${q}}{3}`}t^3+${c0}t\\right]_0^{${t}}=${defInt([q, 0, c0], 0, t)}$ (L).`, `$\\left[${q / 3 === 1 ? "" : q / 3 === Math.floor(q / 3) ? q / 3 : `\\frac{${q}}{3}`}t^3+${c0}t\\right]_0^{${t}}=${defInt([q, 0, c0], 0, t)}$ (L).`) });
  const between = (n, role, d, a, bb) => { const lo = Math.min(a, bb), hi = Math.max(a, bb); return numeric({ k: "area", n, role, d, fam: "area-between", tags: ["multistep", "reasoning"], prompt: P(`곡선 $y=x^2$ 과 직선 $y=${term(lo + hi, "x", true)}${term(-lo * hi)}$ 로 둘러싸인 부분의 넓이는? ${ONE.ko}`, `Diện tích hình phẳng giới hạn bởi đường cong $y=x^2$ và đường thẳng $y=${term(lo + hi, "x", true)}${term(-lo * hi)}$ là bao nhiêu? ${ONE.vi}`), value: (hi - lo) ** 3 / 6, tol: 1e-3,
    hints: [P("두 식을 연립해 교점의 $x$좌표를 구해요.", "Giải hệ hai phương trình để tìm hoành độ giao điểm."), P("(위쪽 식) − (아래쪽 식)을 적분해요.", "Tích phân của (hàm ở trên) − (hàm ở dưới).")], expl: P(`교점은 $x=${lo},\\ ${hi}$ 이고 넓이는 $\\frac{(${hi}-${lo})^3}{6}=${(hi - lo) ** 3 / 6}$.`, `Giao điểm là $x=${lo},\\ ${hi}$ và diện tích là $\\frac{(${hi}-${lo})^3}{6}=${(hi - lo) ** 3 / 6}$.`) }); };
  const l2 = [areaUnder(1, "core", 1, 3, 2), parabola(2, "core", 2, 6), signed(3, "core", 2, 2), tank(4, "core", 2, 3, 2, 4), between(5, "core", 3, -1, 2)];
  areaUnder("v1", "variant", 1, 2, 3); parabola("v2", "variant", 2, 12); signed("v3", "variant", 2, 3); tank("v4", "variant", 2, 6, 1, 3);
  areaUnder("d1", "diagnostic", 1, 4, 1); parabola("d2", "diagnostic", 3, 3); between("d3", "diagnostic", 4, 0, 6);

  /* ------------------------------ 3. geometric series ------------------------------ */
  const sum = (n, role, d, a, num_, den) => numeric({ k: "ser", n, role, d, fam: "ser-sum", prompt: P(`등비급수 ${tex(`${a}+${a}\\cdot\\frac{${num_}}{${den}}+${a}\\left(\\frac{${num_}}{${den}}\\right)^2+\\cdots`)} 의 합은? ${ONE.ko}`, `Tổng của chuỗi cấp số nhân ${tex(`${a}+${a}\\cdot\\frac{${num_}}{${den}}+${a}\\left(\\frac{${num_}}{${den}}\\right)^2+\\cdots`)} là bao nhiêu? ${ONE.vi}`), value: (a * den) / (den - num_), tol: 1e-6,
    hints: [P("$|r|<1$ 이면 합은 $\\frac{a}{1-r}$ 이에요.", "Khi $|r|<1$, tổng là $\\frac{a}{1-r}$."), P(`$r=\\frac{${num_}}{${den}}$ 이므로 $1-r=\\frac{${den - num_}}{${den}}$`, `Công bội $r=\\frac{${num_}}{${den}}$ nên $1-r=\\frac{${den - num_}}{${den}}$.`)], expl: P(`$\\frac{${a}}{1-\\frac{${num_}}{${den}}}=${(a * den) / (den - num_)}$.`, `$\\frac{${a}}{1-\\frac{${num_}}{${den}}}=${(a * den) / (den - num_)}$.`) });
  const converge = (n, role, d, m) => { let c = 0; const xs = []; for (let x = -3 * m; x <= 3 * m; x++) if (Math.abs(x / m) < 1) { c++; xs.push(x); }
    return numeric({ k: "ser", n, role, d, fam: "ser-conv", tags: ["multistep", "reasoning"], prompt: P(`급수 ${tex(`\\sum_{n=1}^{\\infty}\\left(\\frac{x}{${m}}\\right)^{n}`)} 이 수렴하도록 하는 정수 $x$는 모두 몇 개일까요? ${ONE.ko}`, `Có bao nhiêu số nguyên $x$ để chuỗi ${tex(`\\sum_{n=1}^{\\infty}\\left(\\frac{x}{${m}}\\right)^{n}`)} hội tụ? ${ONE.vi}`), value: c,
    hints: [P("등비급수는 공비의 절댓값이 1보다 작을 때 수렴해요.", "Chuỗi cấp số nhân hội tụ khi giá trị tuyệt đối của công bội nhỏ hơn 1."), P(`$\\left|\\frac{x}{${m}}\\right|<1$, 즉 $-${m}<x<${m}$ 이에요.`, `$\\left|\\frac{x}{${m}}\\right|<1$, tức là $-${m}<x<${m}$.`)], expl: P(`$-${m}<x<${m}$ 인 정수는 ${c}개예요.`, `Có ${c} số nguyên thỏa mãn $-${m}<x<${m}$.`) }); };
  const which = (n, role, d, ratioTop) => choice({ k: "ser", n, role, d, fam: "ser-which", tags: ["reasoning"], prompt: P("다음 중 수렴하는 급수는?", "Chuỗi nào sau đây hội tụ?"), right: tex(`\\sum_{n=1}^{\\infty}\\left(\\frac{${ratioTop}}{${ratioTop + 1}}\\right)^{n}`), wrong: [tex(`\\sum_{n=1}^{\\infty}\\left(\\frac{${ratioTop + 1}}{${ratioTop}}\\right)^{n}`), tex("\\sum_{n=1}^{\\infty}1^{n}"), tex("\\sum_{n=1}^{\\infty}(-1)^{n}")],
    hints: [P("공비가 $-1<r<1$ 인지 확인해요.", "Kiểm tra công bội có thỏa $-1<r<1$ không."), P("$r=1$ 이나 $r=-1$ 일 때는 수렴하지 않아요.", "Khi $r=1$ hoặc $r=-1$ chuỗi không hội tụ.")], expl: P(`공비 $\\frac{${ratioTop}}{${ratioTop + 1}}$ 이 $-1$ 과 $1$ 사이에 있는 급수만 수렴해요.`, `Chỉ chuỗi có công bội $\\frac{${ratioTop}}{${ratioTop + 1}}$ nằm giữa $-1$ và $1$ mới hội tụ.`) });
  const bounce = (n, role, d, h, num_, den) => { const total = h + (2 * h * (num_ / den)) / (1 - num_ / den); return numeric({ k: "ser", n, role, d, fam: "ser-ball", tags: ["context", "multistep"], prompt: P(`공을 ${h} m 높이에서 떨어뜨렸더니 바닥에 닿을 때마다 직전 높이의 $\\frac{${num_}}{${den}}$ 만큼 튀어 올랐습니다. 공이 멈출 때까지 움직인 거리의 총합은 몇 m일까요? ${ONE.ko}`, `Thả một quả bóng từ độ cao ${h} m; mỗi lần chạm đất bóng nảy lên bằng $\\frac{${num_}}{${den}}$ độ cao trước đó. Tổng quãng đường bóng đi được cho tới khi dừng hẳn là bao nhiêu mét? ${ONE.vi}`), value: total, tol: 1e-6,
    hints: [P("처음 낙하 거리에, 올라갔다 내려오는 거리(왕복)의 등비급수를 더해요.", "Cộng quãng đường rơi ban đầu với chuỗi cấp số nhân của các lần lên rồi xuống."), P(`첫 왕복은 $2\\times ${h}\\times\\frac{${num_}}{${den}}$ 이고 공비는 $\\frac{${num_}}{${den}}$ 예요.`, `Lần lên xuống đầu tiên là $2\\times ${h}\\times\\frac{${num_}}{${den}}$, công bội là $\\frac{${num_}}{${den}}$.`)], expl: P(`$${h}+\\frac{2\\times ${h}\\times ${num_}/${den}}{1-${num_}/${den}}=${total}$ (m).`, `$${h}+\\frac{2\\times ${h}\\times ${num_}/${den}}{1-${num_}/${den}}=${total}$ (m).`) }); };
  const recur = (n, role, d, ab) => { const g = gcdI(ab, 99); const p = ab / g, q = 99 / g; return numeric({ k: "ser", n, role, d, fam: "ser-recur", tags: ["multistep"], prompt: P(`순환소수 $0.\\dot{${Math.floor(ab / 10)}}\\dot{${ab % 10}}$ 을 기약분수 $\\frac{p}{q}$ 로 나타낼 때 $p+q$의 값은? ${ONE.ko}`, `Biểu diễn số thập phân tuần hoàn $0,\\dot{${Math.floor(ab / 10)}}\\dot{${ab % 10}}$ dưới dạng phân số tối giản $\\frac{p}{q}$. Tính $p+q$. ${ONE.vi}`), value: p + q,
    hints: [P(`$0.${ab}+0.00${ab}+\\cdots$ 은 첫째항 $0.${ab}$, 공비 $0.01$ 인 등비급수예요.`, `$0,${ab}+0,00${ab}+\\cdots$ là chuỗi cấp số nhân có số hạng đầu $0,${ab}$ và công bội $0,01$.`), P("합 $=\\frac{a}{1-r}$ 을 계산한 뒤 기약분수로 만들어요.", "Tính tổng $\\frac{a}{1-r}$ rồi rút gọn thành phân số tối giản.")], expl: P(`$\\frac{0.${ab}}{0.99}=\\frac{${ab}}{99}=\\frac{${p}}{${q}}$ 이므로 $p+q=${p + q}$.`, `$\\frac{0,${ab}}{0,99}=\\frac{${ab}}{99}=\\frac{${p}}{${q}}$ nên $p+q=${p + q}$.`) }); };
  const l3 = [sum(1, "core", 1, 3, 1, 2), converge(2, "core", 2, 2), which(3, "core", 2, 2), bounce(4, "core", 3, 8, 1, 2), recur(5, "core", 3, 36)];
  sum("v1", "variant", 1, 4, 1, 3); which("v2", "variant", 2, 3); bounce("v3", "variant", 3, 9, 2, 3); recur("v4", "variant", 3, 27); converge("v5", "variant", 2, 4);
  sum("d1", "diagnostic", 1, 6, 2, 3); converge("d2", "diagnostic", 3, 5); recur("d3", "diagnostic", 4, 12);

  /* ------------------------------ 4. conditional probability ------------------------------ */
  const condP = (n, role, d, pa, pab) => numeric({ k: "cond", n, role, d, fam: "cond-basic", prompt: P(`두 사건 $A,\\ B$ 에 대하여 $P(A)=${pa}$, $P(A\\cap B)=${pab}$ 일 때 $P(B\\mid A)$ 의 값은? ${DEC.ko}`, `Với hai biến cố $A,\\ B$ có $P(A)=${pa}$ và $P(A\\cap B)=${pab}$, giá trị của $P(B\\mid A)$ là bao nhiêu? ${DEC.vi}`), value: r4(pab / pa), tol: 0.001,
    hints: [P("조건부확률 $P(B\\mid A)=\\frac{P(A\\cap B)}{P(A)}$ 이에요.", "Xác suất có điều kiện $P(B\\mid A)=\\frac{P(A\\cap B)}{P(A)}$."), P(`$${pab}\\div ${pa}$`, `$${pab}\\div ${pa}$`)], expl: P(`$P(B\\mid A)=\\frac{${pab}}{${pa}}=${r4(pab / pa)}$.`, `$P(B\\mid A)=\\frac{${pab}}{${pa}}=${r4(pab / pa)}$.`) });
  const draw = (n, role, d, w, bl) => { const p = (w / (w + bl)) * ((w - 1) / (w + bl - 1)); return numeric({ k: "cond", n, role, d, fam: "cond-draw", tags: ["context", "multistep"], prompt: P(`흰 공 ${w}개, 검은 공 ${bl}개가 든 주머니에서 공을 한 개씩 두 번 꺼냅니다(꺼낸 공은 다시 넣지 않음). 두 번 모두 흰 공일 확률은? ${DEC.ko}`, `Túi có ${w} bóng trắng và ${bl} bóng đen. Lấy lần lượt hai quả (không hoàn lại). Xác suất cả hai quả đều trắng là bao nhiêu? ${DEC.vi}`), value: r4(p), tol: 0.001,
    hints: [P("첫 번째가 흰 공일 확률과, 그때 두 번째도 흰 공일 확률을 곱해요.", "Nhân xác suất quả đầu trắng với xác suất quả thứ hai trắng khi quả đầu đã trắng."), P(`$\\frac{${w}}{${w + bl}}\\times\\frac{${w - 1}}{${w + bl - 1}}$`, `$\\frac{${w}}{${w + bl}}\\times\\frac{${w - 1}}{${w + bl - 1}}$`)], expl: P(`$\\frac{${w}}{${w + bl}}\\times\\frac{${w - 1}}{${w + bl - 1}}=${r4(p)}$.`, `$\\frac{${w}}{${w + bl}}\\times\\frac{${w - 1}}{${w + bl - 1}}=${r4(p)}$.`) }); };
  const indep = (n, role, d, pa, pb, pab) => truefalse({ k: "cond", n, role, d, fam: "cond-indep", tags: ["reasoning"], truth: Math.abs(pa * pb - pab) < 1e-9, prompt: P(`$P(A)=${pa}$, $P(B)=${pb}$, $P(A\\cap B)=${pab}$ 일 때 두 사건 $A,\\ B$ 는 서로 독립이다.`, `Với $P(A)=${pa}$, $P(B)=${pb}$, $P(A\\cap B)=${pab}$, hai biến cố $A,\\ B$ độc lập với nhau.`),
    hints: [P("독립이면 $P(A\\cap B)=P(A)P(B)$ 예요.", "Độc lập thì $P(A\\cap B)=P(A)P(B)$."), P(`$${pa}\\times ${pb}$ 를 계산해 $P(A\\cap B)$ 와 비교해요.`, `Tính $${pa}\\times ${pb}$ rồi so sánh với $P(A\\cap B)$.`)], expl: P(`$${pa}\\times ${pb}=${r4(pa * pb)}$ 이므로 $P(A\\cap B)=${pab}$ 와 ${Math.abs(pa * pb - pab) < 1e-9 ? "같아서 독립이에요" : "달라서 독립이 아니에요"}.`, `$${pa}\\times ${pb}=${r4(pa * pb)}$ ${Math.abs(pa * pb - pab) < 1e-9 ? "bằng" : "khác"} $P(A\\cap B)=${pab}$ nên ${Math.abs(pa * pb - pab) < 1e-9 ? "hai biến cố độc lập" : "hai biến cố không độc lập"}.`) });
  const factory = (n, role, d, sa, fa, fb) => { const sb = 100 - sa; const pa = (sa / 100) * (fa / 100), pb = (sb / 100) * (fb / 100); const v = pa / (pa + pb); return numeric({ k: "cond", n, role, d, fam: "cond-bayes", tags: ["context", "multistep"], prompt: P(`어떤 제품의 ${sa}%는 A 공장, ${sb}%는 B 공장에서 만들고, 불량률은 A 공장 ${fa}%, B 공장 ${fb}%입니다. 임의로 고른 제품이 불량품일 때, 그것이 A 공장 제품일 확률은? ${DEC.ko}`, `${sa}% sản phẩm do nhà máy A làm ra, ${sb}% do nhà máy B; tỉ lệ lỗi của A là ${fa}% và của B là ${fb}%. Chọn ngẫu nhiên một sản phẩm bị lỗi, xác suất nó do nhà máy A làm ra là bao nhiêu? ${DEC.vi}`), value: r4(v), tol: 0.001,
    hints: [P("(불량이면서 A 공장) ÷ (불량 전체)로 구해요.", "Tính (lỗi và thuộc A) ÷ (tổng số lỗi)."), P(`A 불량 $${sa / 100}\\times ${fa / 100}$, B 불량 $${sb / 100}\\times ${fb / 100}$`, `Lỗi của A: $${sa / 100}\\times ${fa / 100}$; lỗi của B: $${sb / 100}\\times ${fb / 100}$.`)], expl: P(`$\\frac{${r4(pa)}}{${r4(pa)}+${r4(pb)}}=${r4(v)}$.`, `$\\frac{${r4(pa)}}{${r4(pa)}+${r4(pb)}}=${r4(v)}$.`) }); };
  const binomial = (n, role, d, nn, k, pn, pd) => { const C = (a, c) => { let r = 1; for (let i = 1; i <= c; i++) r = (r * (a - c + i)) / i; return Math.round(r); }; const p = pn / pd; const v = C(nn, k) * p ** k * (1 - p) ** (nn - k);
    return numeric({ k: "cond", n, role, d, fam: "cond-binom", tags: ["multistep", "reasoning"], prompt: P(`한 번 던져서 앞면이 나올 확률이 $\\frac{${pn}}{${pd}}$ 인 동전을 ${nn}번 던질 때, 앞면이 정확히 ${k}번 나올 확률은? ${DEC.ko}`, `Một đồng xu có xác suất ra mặt ngửa là $\\frac{${pn}}{${pd}}$. Tung ${nn} lần, xác suất để có đúng ${k} lần ngửa là bao nhiêu? ${DEC.vi}`), value: r4(v), tol: 0.001,
    hints: [P("독립시행의 확률 $_nC_k\\,p^k(1-p)^{n-k}$ 을 써요.", "Dùng công thức xác suất của phép thử độc lập $C(n,k)\\,p^k(1-p)^{n-k}$."), P(`$_{${nn}}C_{${k}}=${C(nn, k)}$`, `$C(${nn},${k})=${C(nn, k)}$.`)], expl: P(`$${C(nn, k)}\\times\\left(\\frac{${pn}}{${pd}}\\right)^{${k}}\\left(\\frac{${pd - pn}}{${pd}}\\right)^{${nn - k}}\\approx ${r4(v)}$.`, `$${C(nn, k)}\\times\\left(\\frac{${pn}}{${pd}}\\right)^{${k}}\\left(\\frac{${pd - pn}}{${pd}}\\right)^{${nn - k}}\\approx ${r4(v)}$.`) }); };
  const l4 = [condP(1, "core", 1, 0.5, 0.2), draw(2, "core", 2, 3, 2), indep(3, "core", 2, 0.4, 0.5, 0.2), factory(4, "core", 3, 60, 2, 3), binomial(5, "core", 3, 3, 2, 2, 3)];
  condP("v1", "variant", 1, 0.8, 0.6); draw("v2", "variant", 2, 4, 3); indep("v3", "variant", 2, 0.3, 0.5, 0.2); factory("v4", "variant", 3, 50, 2, 6);
  condP("d1", "diagnostic", 1, 0.6, 0.3); indep("d2", "diagnostic", 3, 0.5, 0.6, 0.3); binomial("d3", "diagnostic", 4, 4, 2, 1, 2);

  /* ------------------------------ 5. binomial and normal distributions ------------------------------ */
  const mean = (n, role, d, nn, p) => numeric({ k: "norm", n, role, d, fam: "norm-mean", prompt: P(`확률변수 $X$ 가 이항분포 $B(${nn},\\ ${p})$ 를 따를 때 $E(X)$ 의 값은? ${ONE.ko}`, `Biến ngẫu nhiên $X$ tuân theo phân phối nhị thức $B(${nn},\\ ${p})$. Giá trị của $E(X)$ là bao nhiêu? ${ONE.vi}`), value: r4(nn * p), tol: 0.001,
    hints: [P("이항분포의 평균은 $E(X)=np$ 예요.", "Kỳ vọng của phân phối nhị thức là $E(X)=np$."), P(`${nn}×${p}`, `${nn}×${p}`)], expl: P(`$E(X)=${nn}\\times ${p}=${r4(nn * p)}$.`, `$E(X)=${nn}\\times ${p}=${r4(nn * p)}$.`) });
  const sd = (n, role, d, nn, p) => { const v = nn * p * (1 - p); return numeric({ k: "norm", n, role, d, fam: "norm-sd", tags: ["multistep"], prompt: P(`확률변수 $X$ 가 이항분포 $B(${nn},\\ ${p})$ 를 따를 때 $X$ 의 표준편차 $\\sigma(X)$ 는? ${ONE.ko}`, `Biến ngẫu nhiên $X$ tuân theo $B(${nn},\\ ${p})$. Độ lệch chuẩn $\\sigma(X)$ bằng bao nhiêu? ${ONE.vi}`), value: Math.sqrt(v), tol: 0.001,
    hints: [P("분산 $V(X)=np(1-p)$ 를 먼저 구해요.", "Trước hết tính phương sai $V(X)=np(1-p)$."), P(`$V(X)=${nn}\\times ${p}\\times ${r4(1 - p)}=${r4(v)}$ 이고 $\\sigma=\\sqrt{V}$ 예요.`, `$V(X)=${nn}\\times ${p}\\times ${r4(1 - p)}=${r4(v)}$ và $\\sigma=\\sqrt{V}$.`)], expl: P(`$\\sigma(X)=\\sqrt{${r4(v)}}=${r4(Math.sqrt(v))}$.`, `$\\sigma(X)=\\sqrt{${r4(v)}}=${r4(Math.sqrt(v))}$.`) }); };
  const standardize = (n, role, d, m, s, x) => { const z = (x - m) / s; return choice({ k: "norm", n, role, d, fam: "norm-z", tags: ["reasoning"], prompt: P(`$X$ 가 정규분포 $N(${m},\\ ${s}^2)$ 을 따를 때, $P(X\\ge ${x})$ 를 표준정규분포를 따르는 $Z$ 로 바꾸면?`, `Khi $X\\sim N(${m},\\ ${s}^2)$, hãy chuyển $P(X\\ge ${x})$ sang biến chuẩn $Z$.`), right: tex(`P(Z\\ge ${z})`), wrong: [tex(`P(Z\\ge ${x - m})`), tex(`P(Z\\ge ${r4(z / s)})`), tex(`P(Z\\le ${z})`)],
    hints: [P("표준화: $Z=\\frac{X-m}{\\sigma}$", "Chuẩn hóa: $Z=\\frac{X-m}{\\sigma}$."), P(`$\\frac{${x}-${m}}{${s}}$ 를 계산해요.`, `Tính $\\frac{${x}-${m}}{${s}}$.`)], expl: P(`$Z=\\frac{${x}-${m}}{${s}}=${z}$ 이므로 $P(Z\\ge ${z})$.`, `$Z=\\frac{${x}-${m}}{${s}}=${z}$ nên $P(Z\\ge ${z})$.`) }); };
  const exam = (n, role, d, m, s, x, table) => { const z = (x - m) / s; return numeric({ k: "norm", n, role, d, fam: "norm-table", tags: ["context", "multistep"], prompt: P(`어느 시험의 점수 $X$ 는 평균 ${m}점, 표준편차 ${s}점인 정규분포를 따릅니다. 표준정규분포표에서 $P(0\\le Z\\le ${z})=${table}$ 일 때, ${x}점 이상을 받은 학생의 비율(확률)은? ${DEC.ko}`, `Điểm thi $X$ tuân theo phân phối chuẩn với trung bình ${m} và độ lệch chuẩn ${s}. Cho $P(0\\le Z\\le ${z})=${table}$; xác suất một học sinh được từ ${x} điểm trở lên là bao nhiêu? ${DEC.vi}`), value: r4(0.5 - table), tol: 0.0005,
    hints: [P("먼저 $Z=\\frac{X-m}{\\sigma}$ 로 표준화해요.", "Trước hết chuẩn hóa $Z=\\frac{X-m}{\\sigma}$."), P("$P(Z\\ge z)=0.5-P(0\\le Z\\le z)$ 예요.", "$P(Z\\ge z)=0.5-P(0\\le Z\\le z)$.")], expl: P(`$P(X\\ge ${x})=P(Z\\ge ${z})=0.5-${table}=${r4(0.5 - table)}$.`, `$P(X\\ge ${x})=P(Z\\ge ${z})=0.5-${table}=${r4(0.5 - table)}$.`) }); };
  const symmetry = (n, role, d, a, bb, s) => numeric({ k: "norm", n, role, d, fam: "norm-sym", tags: ["multistep", "reasoning"], prompt: P(`$X$ 가 정규분포 $N(m,\\ ${s}^2)$ 을 따르고 $P(X\\le ${a})=P(X\\ge ${bb})$ 일 때, $m+\\sigma$ 의 값은? ${ONE.ko}`, `$X\\sim N(m,\\ ${s}^2)$ và $P(X\\le ${a})=P(X\\ge ${bb})$. Tính $m+\\sigma$. ${ONE.vi}`), value: (a + bb) / 2 + s,
    hints: [P("정규분포 곡선은 평균 $m$ 에 대하여 대칭이에요.", "Đường cong phân phối chuẩn đối xứng qua giá trị trung bình $m$."), P(`$${a}$ 와 $${bb}$ 의 중점이 $m$ 이에요. $\\sigma=${s}$.`, `$m$ là trung điểm của $${a}$ và $${bb}$; $\\sigma=${s}$.`)], expl: P(`$m=\\frac{${a}+${bb}}{2}=${(a + bb) / 2}$, $\\sigma=${s}$ 이므로 $m+\\sigma=${(a + bb) / 2 + s}$.`, `$m=\\frac{${a}+${bb}}{2}=${(a + bb) / 2}$, $\\sigma=${s}$ nên $m+\\sigma=${(a + bb) / 2 + s}$.`) });
  const l5 = [mean(1, "core", 1, 20, 0.3), sd(2, "core", 2, 100, 0.2), standardize(3, "core", 2, 50, 10, 60), exam(4, "core", 3, 70, 10, 80, 0.3413), symmetry(5, "core", 3, 60, 76, 4)];
  mean("v1", "variant", 1, 50, 0.4); sd("v2", "variant", 2, 36, 0.5); standardize("v3", "variant", 2, 100, 15, 130); exam("v4", "variant", 3, 60, 5, 70, 0.4772);
  mean("d1", "diagnostic", 1, 10, 0.5); standardize("d2", "diagnostic", 3, 80, 8, 96); symmetry("d3", "diagnostic", 4, 40, 60, 5);

  K.course({
    slug: "calculus-statistics", title: T("고3 수학: 적분·급수·확률분포", "Toán lớp 12: Tích phân, chuỗi và phân phối xác suất"),
    world: { name: T("적분 평원과 통계 바다", "Đồng bằng tích phân và biển thống kê"), emoji: "🌊", tagline: T("넓이를 적분으로 재고, 불확실성을 확률분포로 읽어요.", "Đo diện tích bằng tích phân và đọc sự bất định bằng phân phối xác suất.") }, unitTitle: T("고3 수학", "Toán lớp 12"),
    lessons: [
      K.lesson(1, "int", T("부정적분과 정적분", "Nguyên hàm và tích phân xác định"), T("$\\int x^n dx=\\frac{x^{n+1}}{n+1}+C$, $\\int_a^b f(x)dx=F(b)-F(a)$. 위끝·아래끝을 바꾸면 부호가 바뀌고, 구간은 나눌 수 있어요.", "$\\int x^n dx=\\frac{x^{n+1}}{n+1}+C$, $\\int_a^b f(x)dx=F(b)-F(a)$. Đổi cận thì đổi dấu và có thể chia khoảng lấy tích phân."), T("$\\int_0^2 (2x+1)dx=[x^2+x]_0^2=6$", "$\\int_0^2 (2x+1)dx=[x^2+x]_0^2=6$"), l1),
      K.lesson(2, "area", T("정적분의 활용", "Ứng dụng của tích phân"), T("넓이는 $|f(x)|$ 를 적분해요. 그래프가 $x$축 아래에 있는 부분은 따로 나누고, 두 곡선 사이는 (위)−(아래)를 적분해요. 속도의 적분은 이동한 거리예요.", "Diện tích là tích phân của $|f(x)|$. Phần đồ thị dưới trục hoành cần tách riêng; giữa hai đường cong lấy tích phân (trên) − (dưới). Tích phân vận tốc là quãng đường."), T("$y=6x-x^2$ 과 $x$축 사이의 넓이 $=36$", "Diện tích giữa $y=6x-x^2$ và trục hoành là $36$"), l2),
      K.lesson(3, "ser", T("등비급수", "Chuỗi cấp số nhân"), T("$|r|<1$ 이면 $\\sum ar^{n-1}=\\frac{a}{1-r}$ 로 수렴하고, $|r|\\ge 1$ 이면 발산해요. 순환소수와 되풀이되는 운동에 쓰여요.", "Khi $|r|<1$, $\\sum ar^{n-1}=\\frac{a}{1-r}$ hội tụ; khi $|r|\\ge 1$ thì phân kỳ. Dùng cho số thập phân tuần hoàn và các chuyển động lặp lại."), T("$3+\\frac32+\\frac34+\\cdots=6$", "$3+\\frac32+\\frac34+\\cdots=6$"), l3),
      K.lesson(4, "cond", T("조건부확률과 독립", "Xác suất có điều kiện và độc lập"), T("$P(B\\mid A)=\\frac{P(A\\cap B)}{P(A)}$. 독립이면 $P(A\\cap B)=P(A)P(B)$ 이고, 독립시행은 $_nC_k\\,p^k(1-p)^{n-k}$ 예요.", "$P(B\\mid A)=\\frac{P(A\\cap B)}{P(A)}$. Độc lập thì $P(A\\cap B)=P(A)P(B)$; phép thử độc lập có xác suất $C(n,k)\\,p^k(1-p)^{n-k}$."), T("$P(B\\mid A)=\\dfrac{0.2}{0.5}=0.4$", "$P(B\\mid A)=\\dfrac{0,2}{0,5}=0,4$"), l4),
      K.lesson(5, "norm", T("이항분포와 정규분포", "Phân phối nhị thức và phân phối chuẩn"), T("$B(n,p)$ 의 평균은 $np$, 분산은 $np(1-p)$ 예요. 정규분포는 $Z=\\frac{X-m}{\\sigma}$ 로 표준화하고, 평균에 대하여 대칭이에요.", "$B(n,p)$ có kỳ vọng $np$ và phương sai $np(1-p)$. Phân phối chuẩn được chuẩn hóa bằng $Z=\\frac{X-m}{\\sigma}$ và đối xứng qua giá trị trung bình."), T("$X\\sim N(50,10^2)$ 이면 $P(X\\ge 60)=P(Z\\ge 1)$", "Nếu $X\\sim N(50,10^2)$ thì $P(X\\ge 60)=P(Z\\ge 1)$"), l5),
    ],
  });
}
