import { T, tex, term, poly, makeMathKit, ONE } from "./math-kit.mjs";

const P = T;
const DEC = T("(분수는 -0.75 처럼 소수로 써도 돼요)", "(có thể nhập phân số dưới dạng số thập phân, ví dụ -0,75)");
const evalP = (cs, x) => cs.reduce((acc, c) => acc * x + c, 0);
const pmul = (p, q) => { const out = Array(p.length + q.length - 1).fill(0); p.forEach((a, i) => q.forEach((c, j) => { out[i + j] += a * c; })); return out; };
const fact = (n) => (n <= 1 ? 1 : n * fact(n - 1));
const perm = (n, k) => fact(n) / fact(n - k);
const comb = (n, k) => perm(n, k) / fact(k);
const pt = (x, y) => `(${x},\\ ${y})`;

/** High 1 (common mathematics): polynomial division, complex numbers, quadratic inequalities, counting, equations of lines and circles. */
export function h1(b) {
  const S = { poly: "m.h1.poly", cplx: "m.h1.cplx", ineq: "m.h1.ineq", comb: "m.h1.comb", geom: "m.h1.geom" };
  b.skill(S.poly, T("다항식의 나눗셈과 나머지정리", "Chia đa thức và định lý số dư"));
  b.skill(S.cplx, T("복소수와 이차방정식", "Số phức và phương trình bậc hai"), S.poly);
  b.skill(S.ineq, T("이차부등식", "Bất phương trình bậc hai"), S.cplx);
  b.skill(S.comb, T("순열과 조합", "Hoán vị và tổ hợp"), S.ineq);
  b.skill(S.geom, T("직선과 원의 방정식", "Phương trình đường thẳng và đường tròn"), S.comb);
  const K = makeMathKit(b, "h1", S);
  const { numeric, choice } = K;

  /* ------------------------------ 1. polynomial division ------------------------------ */
  const remainder = (n, role, d, cs, r) => numeric({ k: "poly", n, role, d, fam: "poly-rem", prompt: P(`다항식 ${tex(`P(x)=${poly(cs)}`)} 을 $x${r >= 0 ? "-" : "+"}${Math.abs(r)}$ 로 나눈 나머지는? ${ONE.ko}`, `Số dư khi chia ${tex(`P(x)=${poly(cs)}`)} cho $x${r >= 0 ? "-" : "+"}${Math.abs(r)}$ là bao nhiêu? ${ONE.vi}`), value: evalP(cs, r),
    hints: [P("나머지정리: $P(x)$ 를 $x-a$ 로 나눈 나머지는 $P(a)$ 예요.", "Định lý số dư: số dư khi chia $P(x)$ cho $x-a$ là $P(a)$."), P(`$x=${r}$ 를 대입해요.`, `Thay $x=${r}$ vào.`)], expl: P(`$P(${r})=${evalP(cs, r)}$ 이므로 나머지는 ${evalP(cs, r)}.`, `$P(${r})=${evalP(cs, r)}$ nên số dư là ${evalP(cs, r)}.`) });
  const findA = (n, role, d, r, bb, cc) => { const a = -(r ** 3 + bb * r + cc) / (r * r); return numeric({ k: "poly", n, role, d, fam: "poly-factor", tags: ["multistep"], prompt: P(`다항식 ${tex(`P(x)=x^3+ax^2${term(bb, "x")}${term(cc)}`)} 이 $x-${r}$ 로 나누어떨어질 때, 상수 $a$의 값은? ${ONE.ko}`, `Đa thức ${tex(`P(x)=x^3+ax^2${term(bb, "x")}${term(cc)}`)} chia hết cho $x-${r}$. Tìm hằng số $a$. ${ONE.vi}`), value: a,
    hints: [P("인수정리: $x-r$ 로 나누어떨어지면 $P(r)=0$ 이에요.", "Định lý nhân tử: chia hết cho $x-r$ thì $P(r)=0$."), P(`$P(${r})=0$ 으로 식을 세워 $a$를 구해요.`, `Lập phương trình $P(${r})=0$ rồi tìm $a$.`)], expl: P(`$P(${r})=${r ** 3}+${r * r}a${term(bb * r)}${term(cc)}=0$ 에서 $a=${a}$.`, `Từ $P(${r})=${r ** 3}+${r * r}a${term(bb * r)}${term(cc)}=0$ ta có $a=${a}$.`) }); };
  const hasFactor = (n, role, d, r, extra) => { const right = pmul(pmul([1, -1], [1, -r]), [1, -extra]); const mod = (dc) => right.map((c, i) => (i === right.length - 1 ? c + dc : c));
    return choice({ k: "poly", n, role, d, fam: "poly-which", tags: ["reasoning"], prompt: P("다음 중 $x-1$ 을 인수로 갖는 다항식은?", "Đa thức nào sau đây có $x-1$ là một nhân tử?"), right: tex(poly(right)), wrong: [tex(poly(mod(1))), tex(poly(mod(-2))), tex(poly(mod(3)))],
      hints: [P("각 다항식에 $x=1$ 을 대입해 0이 되는지 확인해요.", "Thay $x=1$ vào từng đa thức xem có bằng 0 không."), P("$P(1)=0$ 이면 $x-1$ 이 인수예요.", "Nếu $P(1)=0$ thì $x-1$ là nhân tử.")], expl: P(`$P(1)=${evalP(right, 1)}$ 인 것은 ${tex(poly(right))} 하나뿐이에요.`, `Chỉ ${tex(poly(right))} có $P(1)=${evalP(right, 1)}$.`) }); };
  const volume = (n, role, d, x0, rts) => { const [r1, r2] = rts; const vol = pmul(pmul([1, -1], [1, -r1]), [1, -r2]); const base = pmul([1, -r1], [1, -r2]);
    return numeric({ k: "poly", n, role, d, fam: "poly-volume", tags: ["context", "multistep"], prompt: P(`직육면체의 부피가 ${tex(poly(vol))}, 높이가 $x-1$ 입니다. $x=${x0}$ 일 때 밑면의 넓이는? ${ONE.ko}`, `Hình hộp chữ nhật có thể tích ${tex(poly(vol))} và chiều cao $x-1$. Khi $x=${x0}$ thì diện tích đáy bằng bao nhiêu? ${ONE.vi}`), value: evalP(base, x0),
      hints: [P("밑면의 넓이 = 부피 ÷ 높이. 다항식의 나눗셈(조립제법)을 해요.", "Diện tích đáy = thể tích ÷ chiều cao. Thực hiện chia đa thức (sơ đồ Horner)."), P("몫을 구한 뒤 $x$ 값을 대입해요.", "Tìm thương rồi thay giá trị của $x$.")], expl: P(`몫은 ${tex(poly(base))} 이므로 $x=${x0}$ 일 때 ${evalP(base, x0)}.`, `Thương là ${tex(poly(base))} nên khi $x=${x0}$ ta được ${evalP(base, x0)}.`) }); };
  const linRem = (n, role, d, r1, v1, r2, v2) => { const a = (v1 - v2) / (r1 - r2); const bb = v1 - a * r1;
    return numeric({ k: "poly", n, role, d, fam: "poly-linrem", tags: ["multistep", "reasoning"], prompt: P(`다항식 $P(x)$ 를 $x${r1 >= 0 ? "-" : "+"}${Math.abs(r1)}$ 로 나눈 나머지가 ${v1}, $x${r2 >= 0 ? "-" : "+"}${Math.abs(r2)}$ 로 나눈 나머지가 ${v2}입니다. $P(x)$ 를 $(x${r1 >= 0 ? "-" : "+"}${Math.abs(r1)})(x${r2 >= 0 ? "-" : "+"}${Math.abs(r2)})$ 로 나눈 나머지를 $ax+b$ 라 할 때 $a+b$의 값은? ${ONE.ko}`, `Số dư khi chia $P(x)$ cho $x${r1 >= 0 ? "-" : "+"}${Math.abs(r1)}$ là ${v1} và cho $x${r2 >= 0 ? "-" : "+"}${Math.abs(r2)}$ là ${v2}. Số dư khi chia $P(x)$ cho $(x${r1 >= 0 ? "-" : "+"}${Math.abs(r1)})(x${r2 >= 0 ? "-" : "+"}${Math.abs(r2)})$ là $ax+b$. Tính $a+b$. ${ONE.vi}`), value: a + bb,
      hints: [P(`$P(x)=Q(x)(x${r1 >= 0 ? "-" : "+"}${Math.abs(r1)})(x${r2 >= 0 ? "-" : "+"}${Math.abs(r2)})+ax+b$ 로 쓸 수 있어요.`, `Có thể viết $P(x)=Q(x)(x${r1 >= 0 ? "-" : "+"}${Math.abs(r1)})(x${r2 >= 0 ? "-" : "+"}${Math.abs(r2)})+ax+b$.`), P(`$P(${r1})=${v1}$, $P(${r2})=${v2}$ 를 이용해 $a$, $b$ 에 대한 연립방정식을 세워요.`, `Dùng $P(${r1})=${v1}$ và $P(${r2})=${v2}$ để lập hệ phương trình theo $a$, $b$.`)], expl: P(`$${r1}a+b=${v1}$, $${r2}a+b=${v2}$ 를 풀면 $a=${a}$, $b=${bb}$ 이므로 $a+b=${a + bb}$.`, `Giải $${r1}a+b=${v1}$ và $${r2}a+b=${v2}$ ta được $a=${a}$, $b=${bb}$ nên $a+b=${a + bb}$.`) }); };
  const l1 = [remainder(1, "core", 1, [1, 3, 2], 1), findA(2, "core", 2, 2, -1, 6), hasFactor(3, "core", 2, 2, 4), volume(4, "core", 3, 4, [2, -3]), linRem(5, "core", 3, 1, 3, -2, -3)];
  remainder("v1", "variant", 1, [2, -1, 5], 2); findA("v2", "variant", 2, 1, 2, 3); hasFactor("v3", "variant", 2, 3, 5); linRem("v4", "variant", 3, 1, 7, -1, 1);
  remainder("d1", "diagnostic", 1, [1, 0, -4, 1], 2); findA("d2", "diagnostic", 3, 3, -2, 6); hasFactor("d3", "diagnostic", 4, 5, 2);

  /* ------------------------------ 2. complex numbers & discriminant ------------------------------ */
  const cx = (re, im) => `${re}${im >= 0 ? "+" : "-"}${Math.abs(im) === 1 ? "" : Math.abs(im)}i`;
  const cadd = (n, role, d, a, bb, c, dd) => numeric({ k: "cplx", n, role, d, fam: "cplx-add", prompt: P(`${tex(`(${cx(a, bb)})+(${cx(c, dd)})`)} 의 실수부분과 허수부분의 합은? ${ONE.ko}`, `Tổng của phần thực và phần ảo của ${tex(`(${cx(a, bb)})+(${cx(c, dd)})`)} là bao nhiêu? ${ONE.vi}`), value: a + c + bb + dd,
    hints: [P("실수부분끼리, 허수부분끼리 더해요.", "Cộng phần thực với phần thực, phần ảo với phần ảo."), P(`${a}+${c}, ${bb}+${dd}`, `${a}+${c}, ${bb}+${dd}`)], expl: P(`합은 $${cx(a + c, bb + dd)}$ 이므로 ${a + c}+${bb + dd}=${a + c + bb + dd}.`, `Tổng là $${cx(a + c, bb + dd)}$ nên ${a + c}+${bb + dd}=${a + c + bb + dd}.`) });
  const cmul = (n, role, d, a, bb, c, dd) => { const re = a * c - bb * dd, im = a * dd + bb * c; return numeric({ k: "cplx", n, role, d, fam: "cplx-mul", tags: ["multistep"], prompt: P(`${tex(`(${cx(a, bb)})(${cx(c, dd)})`)} 의 실수부분과 허수부분의 합은? ${ONE.ko}`, `Tổng của phần thực và phần ảo của ${tex(`(${cx(a, bb)})(${cx(c, dd)})`)} là bao nhiêu? ${ONE.vi}`), value: re + im,
    hints: [P("분배법칙으로 전개하고 $i^2=-1$ 을 써요.", "Khai triển bằng tính chất phân phối và dùng $i^2=-1$."), P("실수부분: $ac-bd$, 허수부분: $ad+bc$", "Phần thực: $ac-bd$, phần ảo: $ad+bc$.")], expl: P(`곱은 $${cx(re, im)}$ 이므로 ${re}+${im}=${re + im}.`, `Tích là $${cx(re, im)}$ nên ${re}+${im}=${re + im}.`) }); };
  const ipow = (n, role, d, e) => { const m = e % 4; const val = ["1", "i", "-1", "-i"]; const all = ["1", "i", "-1", "-i"]; return choice({ k: "cplx", n, role, d, fam: "cplx-pow", tags: ["reasoning"], prompt: P(`${tex(`i^{${e}}`)} 의 값은? (단, $i=\\sqrt{-1}$)`, `Giá trị của ${tex(`i^{${e}}`)} là? (với $i=\\sqrt{-1}$)`), right: tex(val[m]), wrong: all.filter((_, i) => i !== m).map((s) => tex(s)),
    hints: [P("$i, i^2, i^3, i^4$ 의 값이 4개마다 되풀이돼요.", "Các giá trị $i, i^2, i^3, i^4$ lặp lại sau mỗi 4 lũy thừa."), P(`${e}를 4로 나눈 나머지는 ${m} 이에요.`, `${e} chia 4 dư ${m}.`)], expl: P(`$i^4=1$ 이고 ${e}=4×${Math.floor(e / 4)}+${m} 이므로 $i^{${e}}=${val[m]}$.`, `$i^4=1$ và ${e}=4×${Math.floor(e / 4)}+${m} nên $i^{${e}}=${val[m]}$.`) }); };
  const rectMax = (n, role, d, perim) => { const s = perim / 2; const kk = Math.floor((s * s) / 4); return numeric({ k: "cplx", n, role, d, fam: "cplx-rect", tags: ["context", "multistep"], prompt: P(`둘레의 길이가 ${perim} cm인 직사각형의 넓이를 $k$ cm² 로 만들 수 있다고 합니다. 이를 만족하는 가장 큰 정수 $k$는? ${ONE.ko}`, `Hình chữ nhật có chu vi ${perim} cm. Diện tích có thể bằng $k$ cm². Số nguyên $k$ lớn nhất thỏa mãn là bao nhiêu? ${ONE.vi}`), value: kk,
    hints: [P(`가로를 $x$ 라 하면 세로는 $${s}-x$ 이고 $x(${s}-x)=k$ 예요.`, `Gọi chiều dài là $x$ thì chiều rộng là $${s}-x$ và $x(${s}-x)=k$.`), P("$x^2-" + s + "x+k=0$ 이 실근을 가져야 하므로 판별식 $D\\ge 0$ 이에요.", "Phương trình $x^2-" + s + "x+k=0$ phải có nghiệm thực nên $D\\ge 0$.")], expl: P(`$D=${s * s}-4k\\ge 0$ 에서 $k\\le ${(s * s) / 4}$ 이므로 가장 큰 정수는 ${kk}.`, `Từ $D=${s * s}-4k\\ge 0$ ta có $k\\le ${(s * s) / 4}$ nên số nguyên lớn nhất là ${kk}.`) }); };
  const conjRoot = (n, role, d, a, bb) => numeric({ k: "cplx", n, role, d, fam: "cplx-conj", tags: ["multistep", "reasoning"], prompt: P(`실수 $p,\\ q$ 에 대하여 이차방정식 ${tex(`x^2+px+q=0`)} 의 한 근이 $${cx(a, bb)}$ 일 때 $p+q$의 값은? ${ONE.ko}`, `Với $p,\\ q$ thực, phương trình ${tex(`x^2+px+q=0`)} có một nghiệm là $${cx(a, bb)}$. Tính $p+q$. ${ONE.vi}`), value: -2 * a + a * a + bb * bb,
    hints: [P("계수가 실수이면 켤레복소수도 근이에요.", "Hệ số thực thì số phức liên hợp cũng là nghiệm."), P("근과 계수의 관계: 합 $=-p$, 곱 $=q$", "Hệ thức Vi-ét: tổng $=-p$, tích $=q$.")], expl: P(`다른 근은 $${cx(a, -bb)}$. 합 ${2 * a} 이므로 $p=${-2 * a}$, 곱 ${a * a + bb * bb} 이므로 $q=${a * a + bb * bb}$. $p+q=${-2 * a + a * a + bb * bb}$.`, `Nghiệm còn lại là $${cx(a, -bb)}$. Tổng là ${2 * a} nên $p=${-2 * a}$; tích là ${a * a + bb * bb} nên $q=${a * a + bb * bb}$. Vậy $p+q=${-2 * a + a * a + bb * bb}$.`) });
  const l2 = [cadd(1, "core", 1, 2, 3, 4, -1), cmul(2, "core", 2, 1, 2, 3, -1), ipow(3, "core", 2, 10), rectMax(4, "core", 3, 8), conjRoot(5, "core", 3, 1, 2)];
  cadd("v1", "variant", 1, 5, -2, 1, 6); ipow("v2", "variant", 2, 15); rectMax("v3", "variant", 3, 10); cmul("v4", "variant", 2, 2, -1, 1, 3);
  cadd("d1", "diagnostic", 1, 3, 1, 2, 2); ipow("d2", "diagnostic", 3, 2026); conjRoot("d3", "diagnostic", 4, -2, 3);

  /* ------------------------------ 3. quadratic inequalities ------------------------------ */
  const between = (n, role, d, r1, r2) => numeric({ k: "ineq", n, role, d, fam: "ineq2-count", prompt: P(`이차부등식 ${tex(`${poly([1, -(r1 + r2), r1 * r2])} < 0`)} 을 만족하는 정수 $x$는 모두 몇 개일까요? ${ONE.ko}`, `Có bao nhiêu số nguyên $x$ thỏa mãn bất phương trình ${tex(`${poly([1, -(r1 + r2), r1 * r2])} < 0`)}? ${ONE.vi}`), value: r2 - r1 - 1,
    hints: [P("좌변을 인수분해해 두 근을 구해요.", "Phân tích vế trái để tìm hai nghiệm."), P("$(x-a)(x-b)<0$ 의 해는 두 근 사이예요. 근은 포함하지 않아요.", "Nghiệm của $(x-a)(x-b)<0$ nằm giữa hai nghiệm; không lấy hai đầu mút.")], expl: P(`$(x-${r1})(x-${r2})<0$ 이므로 $${r1}<x<${r2}$. 정수는 ${r2 - r1 - 1}개.`, `$(x-${r1})(x-${r2})<0$ nên $${r1}<x<${r2}$ và có ${r2 - r1 - 1} số nguyên.`) });
  const outside = (n, role, d, r1, r2) => choice({ k: "ineq", n, role, d, fam: "ineq2-set", prompt: P(`이차부등식 ${tex(`${poly([1, -(r1 + r2), r1 * r2])} \\ge 0`)} 의 해는?`, `Nghiệm của bất phương trình ${tex(`${poly([1, -(r1 + r2), r1 * r2])} \\ge 0`)} là?`), right: P(`$x\\le ${r1}$ 또는 $x\\ge ${r2}$`, `$x\\le ${r1}$ hoặc $x\\ge ${r2}$`),
    wrong: [tex(`${r1}\\le x\\le ${r2}`), P(`$x\\le ${-r2}$ 또는 $x\\ge ${-r1}$`, `$x\\le ${-r2}$ hoặc $x\\ge ${-r1}$`), tex(`${r1}<x<${r2}`)],
    hints: [P("$(x-a)(x-b)\\ge 0$ 이면 $x$가 두 근의 바깥에 있어요.", "Nếu $(x-a)(x-b)\\ge 0$ thì $x$ nằm ngoài khoảng hai nghiệm."), P("등호가 있으므로 근도 포함돼요.", "Có dấu bằng nên lấy cả hai nghiệm.")], expl: P(`$(x-${r1})(x-${r2})\\ge 0$ 이므로 $x\\le ${r1}$ 또는 $x\\ge ${r2}$.`, `$(x-${r1})(x-${r2})\\ge 0$ nên $x\\le ${r1}$ hoặc $x\\ge ${r2}$.`) });
  const always = (n, role, d, m) => numeric({ k: "ineq", n, role, d, fam: "ineq2-always", tags: ["multistep", "reasoning"], prompt: P(`모든 실수 $x$ 에 대하여 ${tex(`x^2-${2 * m}x+k>0`)} 이 성립하도록 하는 가장 작은 정수 $k$의 값은? ${ONE.ko}`, `Số nguyên $k$ nhỏ nhất để ${tex(`x^2-${2 * m}x+k>0`)} đúng với mọi số thực $x$ là bao nhiêu? ${ONE.vi}`), value: m * m + 1,
    hints: [P("항상 성립하려면 아래로 볼록한 그래프가 $x$축과 만나지 않아야 해요.", "Để luôn đúng, parabol quay lên không được cắt trục hoành."), P("판별식 $D<0$ 으로 $k$의 범위를 구해요.", "Dùng biệt thức $D<0$ để tìm miền của $k$.")], expl: P(`$D=${4 * m * m}-4k<0$ 에서 $k>${m * m}$ 이므로 가장 작은 정수는 ${m * m + 1}.`, `Từ $D=${4 * m * m}-4k<0$ ta có $k>${m * m}$ nên số nguyên nhỏ nhất là ${m * m + 1}.`) });
  const land = (n, role, d, dif, area) => { let x = 1; while (x * (x + dif) < area) x++; return numeric({ k: "ineq", n, role, d, fam: "ineq2-land", tags: ["context", "multistep"], prompt: P(`가로가 세로보다 ${dif} m 더 긴 직사각형 모양의 땅의 넓이를 ${area} m² 이상으로 하려고 합니다. 세로의 길이는 최소 몇 m(자연수)이어야 할까요? ${ONE.ko}`, `Một mảnh đất hình chữ nhật có chiều dài hơn chiều rộng ${dif} m và cần có diện tích ít nhất ${area} m². Chiều rộng (số tự nhiên) nhỏ nhất là bao nhiêu mét? ${ONE.vi}`), value: x,
    hints: [P(`세로를 $x$ m라 하면 $x(x+${dif})\\ge ${area}$ 예요.`, `Gọi chiều rộng là $x$ m thì $x(x+${dif})\\ge ${area}$.`), P("부등식을 풀고 $x>0$ 인 자연수 중 가장 작은 값을 찾아요.", "Giải bất phương trình rồi tìm số tự nhiên $x>0$ nhỏ nhất.")], expl: P(`$x(x+${dif})\\ge ${area}$ 를 만족하는 가장 작은 자연수는 ${x} 이에요.`, `Số tự nhiên nhỏ nhất thỏa $x(x+${dif})\\ge ${area}$ là ${x}.`) }); };
  const noMeet = (n, role, d, bb, cc, m) => { const bound = cc - ((bb - m) ** 2) / 4; const kmax = Math.ceil(bound) - 1; return numeric({ k: "ineq", n, role, d, fam: "ineq2-line", tags: ["multistep", "reasoning"], prompt: P(`이차함수 ${tex(`y=${poly([1, bb, cc])}`)} 의 그래프와 직선 ${tex(`y=${term(m, "x", true)}+k`)} 가 만나지 않도록 하는 정수 $k$ 중 가장 큰 값은? ${ONE.ko}`, `Parabol ${tex(`y=${poly([1, bb, cc])}`)} và đường thẳng ${tex(`y=${term(m, "x", true)}+k`)} không có điểm chung. Số nguyên $k$ lớn nhất thỏa mãn là bao nhiêu? ${ONE.vi}`), value: kmax,
    hints: [P("두 식을 연립해 $x$에 대한 이차방정식을 만들어요.", "Lập phương trình bậc hai theo $x$ từ hai biểu thức."), P("만나지 않으면 판별식 $D<0$ 이에요.", "Không có điểm chung thì $D<0$.")], expl: P(`$x^2${term(bb - m, "x")}${term(cc, "")}-k=0$ 의 $D<0$ 에서 $k<${bound}$ 이므로 가장 큰 정수는 ${kmax}.`, `Từ $D<0$ của $x^2${term(bb - m, "x")}${term(cc, "")}-k=0$ ta có $k<${bound}$ nên số nguyên lớn nhất là ${kmax}.`) }); };
  const l3 = [between(1, "core", 1, 1, 6), outside(2, "core", 2, -1, 3), always(3, "core", 2, 2), land(4, "core", 2, 2, 35), noMeet(5, "core", 3, -2, -3, 1)];
  between("v1", "variant", 1, -2, 3); outside("v2", "variant", 2, 2, 5); always("v3", "variant", 2, 3); land("v4", "variant", 2, 3, 40);
  between("d1", "diagnostic", 2, -3, 4); noMeet("d2", "diagnostic", 3, -4, 1, 2); always("d3", "diagnostic", 4, 5);

  /* ------------------------------ 4. permutations and combinations ------------------------------ */
  const lineUp = (n, role, d, nn, r) => numeric({ k: "comb", n, role, d, fam: "comb-perm", prompt: P(`서로 다른 ${nn}명 중에서 ${r}명을 뽑아 일렬로 세우는 방법의 수는? ${ONE.ko}`, `Có bao nhiêu cách chọn ${r} trong ${nn} người khác nhau rồi xếp thành một hàng? ${ONE.vi}`), value: perm(nn, r),
    hints: [P("순서가 있으므로 순열 $_nP_r$ 이에요.", "Có tính thứ tự nên đây là chỉnh hợp $P(n,r)$."), P(`${nn}부터 ${r}개의 수를 차례로 곱해요.`, `Nhân ${r} số liên tiếp, bắt đầu từ ${nn} giảm dần.`)], expl: P(`$_{${nn}}P_{${r}}=${perm(nn, r)}$.`, `$P(${nn},${r})=${perm(nn, r)}$.`) });
  const choose = (n, role, d, nn, r) => numeric({ k: "comb", n, role, d, fam: "comb-choose", prompt: P(`서로 다른 ${nn}개의 구슬 중에서 ${r}개를 고르는 방법의 수는? ${ONE.ko}`, `Có bao nhiêu cách chọn ${r} trong ${nn} viên bi khác nhau? ${ONE.vi}`), value: comb(nn, r),
    hints: [P("순서와 상관없이 고르므로 조합 $_nC_r$ 이에요.", "Không tính thứ tự nên đây là tổ hợp $C(n,r)$."), P("$_nC_r=\\frac{_nP_r}{r!}$", "$C(n,r)=\\frac{P(n,r)}{r!}$")], expl: P(`$_{${nn}}C_{${r}}=${comb(nn, r)}$.`, `$C(${nn},${r})=${comb(nn, r)}$.`) });
  const which = (n, role, d, wantComb) => { const C = [T("5명 중 청소 당번 2명을 뽑는 경우", "Chọn 2 trong 5 bạn làm trực nhật"), T("구슬 6개 중 3개를 고르는 경우", "Chọn 3 trong 6 viên bi"), T("7명의 팀에서 3명을 대표로 뽑는 경우", "Chọn 3 đại diện trong đội 7 người")];
    const Pm = [T("5명 중 회장과 부회장을 뽑는 경우", "Chọn lớp trưởng và lớp phó trong 5 bạn"), T("5명을 한 줄로 세우는 경우", "Xếp 5 bạn thành một hàng"), T("서로 다른 숫자로 세 자리 비밀번호를 만드는 경우", "Lập mật khẩu 3 chữ số đôi một khác nhau")];
    return choice({ k: "comb", n, role, d, fam: "comb-which", tags: ["reasoning"], prompt: wantComb ? P("다음 중 조합 $_nC_r$ 로 구해야 하는 것은?", "Tình huống nào sau đây cần tính bằng tổ hợp $C(n,r)$?") : P("다음 중 순열 $_nP_r$ 로 구해야 하는 것은?", "Tình huống nào sau đây cần tính bằng chỉnh hợp $P(n,r)$?"), right: wantComb ? C[0] : Pm[0], wrong: wantComb ? Pm : [C[0], C[1], C[2]],
      hints: [P("뽑은 사람(물건)의 순서를 바꾸면 다른 경우가 되는지 따져 봐요.", "Hãy xét xem đổi thứ tự những người (vật) được chọn có tạo ra trường hợp khác không."), P("순서가 중요하면 순열, 중요하지 않으면 조합이에요.", "Thứ tự quan trọng thì là chỉnh hợp, không quan trọng thì là tổ hợp.")], expl: wantComb ? P("당번 2명은 누가 먼저든 같은 결과이므로 순서가 없는 조합이에요.", "2 bạn trực nhật không phân biệt thứ tự nên đây là tổ hợp.") : P("회장과 부회장은 역할이 다르므로 순서가 있는 순열이에요.", "Lớp trưởng và lớp phó có vai trò khác nhau nên có tính thứ tự, đây là chỉnh hợp.") }); };
  const team = (n, role, d, m, w, a, c) => numeric({ k: "comb", n, role, d, fam: "comb-team", tags: ["context", "multistep"], prompt: P(`남학생 ${m}명, 여학생 ${w}명 중에서 남학생 ${a}명, 여학생 ${c}명을 뽑는 방법의 수는? ${ONE.ko}`, `Có ${m} nam và ${w} nữ. Có bao nhiêu cách chọn ${a} nam và ${c} nữ? ${ONE.vi}`), value: comb(m, a) * comb(w, c),
    hints: [P("남학생과 여학생을 각각 조합으로 뽑아요.", "Chọn nam và chọn nữ riêng bằng tổ hợp."), P("곱의 법칙: 두 경우의 수를 곱해요.", "Quy tắc nhân: nhân hai số cách với nhau.")], expl: P(`$_{${m}}C_{${a}}\\times {}_{${w}}C_{${c}}=${comb(m, a)}\\times ${comb(w, c)}=${comb(m, a) * comb(w, c)}$.`, `$C(${m},${a})\\times C(${w},${c})=${comb(m, a)}\\times ${comb(w, c)}=${comb(m, a) * comb(w, c)}$.`) });
  const atLeastOne = (n, role, d, m, w, k) => numeric({ k: "comb", n, role, d, fam: "comb-compl", tags: ["multistep", "reasoning"], prompt: P(`남학생 ${m}명, 여학생 ${w}명 중에서 ${k}명을 뽑을 때, 여학생이 적어도 1명 포함되는 방법의 수는? ${ONE.ko}`, `Có ${m} nam và ${w} nữ. Chọn ${k} người sao cho có ít nhất 1 nữ thì có bao nhiêu cách? ${ONE.vi}`), value: comb(m + w, k) - comb(m, k),
    hints: [P("전체에서 '여학생이 한 명도 없는 경우'를 빼면 편해요.", "Dễ hơn nếu lấy tổng số cách trừ đi số cách 'không có nữ nào'."), P(`전체 $_{${m + w}}C_{${k}}$ 에서 남학생만 뽑는 $_{${m}}C_{${k}}$ 를 빼요.`, `Lấy $C(${m + w},${k})$ trừ $C(${m},${k})$ (chỉ chọn nam).`)], expl: P(`$_{${m + w}}C_{${k}}-{}_{${m}}C_{${k}}=${comb(m + w, k)}-${comb(m, k)}=${comb(m + w, k) - comb(m, k)}$.`, `$C(${m + w},${k})-C(${m},${k})=${comb(m + w, k)}-${comb(m, k)}=${comb(m + w, k) - comb(m, k)}$.`) });
  const l4 = [lineUp(1, "core", 1, 5, 2), choose(2, "core", 2, 7, 3), which(3, "core", 2, true), team(4, "core", 3, 4, 3, 2, 1), atLeastOne(5, "core", 3, 4, 3, 3)];
  lineUp("v1", "variant", 1, 6, 3); choose("v2", "variant", 2, 8, 2); which("v3", "variant", 2, false); team("v4", "variant", 3, 5, 4, 2, 2);
  lineUp("d1", "diagnostic", 2, 7, 3); choose("d2", "diagnostic", 2, 6, 4); atLeastOne("d3", "diagnostic", 4, 5, 4, 3);

  /* ------------------------------ 5. lines and circles ------------------------------ */
  const dist = (n, role, d, x1, y1, x2, y2) => numeric({ k: "geom", n, role, d, fam: "geom-dist", prompt: P(`두 점 $A${pt(x1, y1)}$, $B${pt(x2, y2)}$ 사이의 거리는? ${ONE.ko}`, `Khoảng cách giữa hai điểm $A${pt(x1, y1)}$ và $B${pt(x2, y2)}$ là bao nhiêu? ${ONE.vi}`), value: Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2),
    hints: [P("두 점 사이의 거리 공식 $\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$ 를 써요.", "Dùng công thức khoảng cách $\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$."), P(`$(${x2 - x1})^2+(${y2 - y1})^2$ 를 계산해요.`, `Tính $(${x2 - x1})^2+(${y2 - y1})^2$.`)], expl: P(`$\\sqrt{${(x2 - x1) ** 2}+${(y2 - y1) ** 2}}=${Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)}$.`, `$\\sqrt{${(x2 - x1) ** 2}+${(y2 - y1) ** 2}}=${Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)}$.`) });
  const lineDist = (n, role, d, x0, y0, c) => { const v = Math.abs(3 * x0 + 4 * y0 + c) / 5; return numeric({ k: "geom", n, role, d, fam: "geom-pline", tags: ["multistep"], prompt: P(`점 $${pt(x0, y0)}$ 와 직선 $3x+4y${term(c)}=0$ 사이의 거리는? ${ONE.ko}`, `Khoảng cách từ điểm $${pt(x0, y0)}$ đến đường thẳng $3x+4y${term(c)}=0$ là bao nhiêu? ${ONE.vi}`), value: v,
    hints: [P("점과 직선 사이의 거리 $\\frac{|ax_0+by_0+c|}{\\sqrt{a^2+b^2}}$ 를 써요.", "Dùng công thức khoảng cách từ điểm đến đường thẳng $\\frac{|ax_0+by_0+c|}{\\sqrt{a^2+b^2}}$."), P("분모는 $\\sqrt{3^2+4^2}=5$ 예요.", "Mẫu số là $\\sqrt{3^2+4^2}=5$.")], expl: P(`$\\frac{|3\\times ${x0}+4\\times ${y0}${term(c)}|}{5}=${v}$.`, `$\\frac{|3\\times ${x0}+4\\times ${y0}${term(c)}|}{5}=${v}$.`) }); };
  const center = (n, role, d, A, B, C) => { const cx_ = -A / 2, cy_ = -B / 2; const f = (x, y) => tex(pt(x, y)); return choice({ k: "geom", n, role, d, fam: "geom-center", tags: ["reasoning"], prompt: P(`원의 방정식 ${tex(`x^2+y^2${term(A, "x")}${term(B, "y")}${term(C)}=0`)} 의 중심의 좌표는?`, `Tâm của đường tròn ${tex(`x^2+y^2${term(A, "x")}${term(B, "y")}${term(C)}=0`)} có tọa độ là?`), right: f(cx_, cy_), wrong: [f(-cx_, -cy_), f(A, B), f(cx_, -cy_)].filter((s) => s !== f(cx_, cy_)),
    hints: [P("$x$끼리, $y$끼리 묶어 완전제곱식으로 바꿔요.", "Nhóm các hạng tử theo $x$ và $y$ rồi đưa về bình phương hoàn chỉnh."), P("$(x-a)^2+(y-b)^2=r^2$ 의 중심은 $(a,\\ b)$ 예요.", "Tâm của $(x-a)^2+(y-b)^2=r^2$ là $(a,\\ b)$.")], expl: P(`$(x${term(-cx_)})^2+(y${term(-cy_)})^2=\\cdots$ 이므로 중심은 $${pt(cx_, cy_)}$.`, `Đưa về $(x${term(-cx_)})^2+(y${term(-cy_)})^2=\\cdots$ nên tâm là $${pt(cx_, cy_)}$.`) }); };
  const lake = (n, role, d, cx_, cy_, r, px, py) => { const dd = Math.sqrt((px - cx_) ** 2 + (py - cy_) ** 2); const at = Math.abs(dd - r) < 1e-9 ? 1 : dd < r ? 0 : 2; const names = [T("호수 안쪽", "bên trong hồ"), T("호수의 경계 위", "trên bờ hồ"), T("호수 바깥쪽", "bên ngoài hồ")];
    return choice({ k: "geom", n, role, d, fam: "geom-lake", tags: ["context", "multistep"], prompt: P(`원형 호수의 중심이 $${pt(cx_, cy_)}$ 이고 반지름이 ${r}입니다. 점 $${pt(px, py)}$ 에 있는 배는 어디에 있을까요? (단위: km)`, `Hồ tròn có tâm $${pt(cx_, cy_)}$ và bán kính ${r} (km). Chiếc thuyền tại điểm $${pt(px, py)}$ đang ở đâu?`), right: names[at], wrong: [...names.filter((_, i) => i !== at), T("알 수 없다", "Không xác định được")],
      hints: [P("점과 중심 사이의 거리를 구해 반지름과 비교해요.", "Tính khoảng cách từ điểm đến tâm rồi so sánh với bán kính."), P("거리 < 반지름이면 안, = 이면 경계, > 이면 바깥이에요.", "Khoảng cách < bán kính: bên trong; bằng: trên đường tròn; lớn hơn: bên ngoài.")], expl: P(`중심과의 거리는 ${Number.isInteger(dd) ? dd : `$\\sqrt{${(px - cx_) ** 2 + (py - cy_) ** 2}}$`} 이고 반지름은 ${r} 이므로 ${names[at].ko}.`, `Khoảng cách tới tâm là ${Number.isInteger(dd) ? dd : `$\\sqrt{${(px - cx_) ** 2 + (py - cy_) ** 2}}$`} còn bán kính là ${r} nên thuyền ở ${names[at].vi}.`) }); };
  const tangent = (n, role, d, cx_, cy_, dx, dy) => { const px = cx_ + dx, py = cy_ + dy; const m = -dx / dy; const r2 = dx * dx + dy * dy;
    return numeric({ k: "geom", n, role, d, fam: "geom-tangent", tags: ["multistep", "reasoning"], prompt: P(`원 ${tex(`(x${term(-cx_)})^2+(y${term(-cy_)})^2=${r2}`)} 위의 점 $${pt(px, py)}$ 에서의 접선의 기울기는? ${DEC.ko}`, `Hệ số góc của tiếp tuyến của đường tròn ${tex(`(x${term(-cx_)})^2+(y${term(-cy_)})^2=${r2}`)} tại điểm $${pt(px, py)}$ là bao nhiêu? ${DEC.vi}`), value: Number(m.toFixed(4)), tol: 0.001,
      hints: [P("접선은 접점과 중심을 잇는 반지름에 수직이에요.", "Tiếp tuyến vuông góc với bán kính nối tâm và tiếp điểm."), P(`반지름의 기울기는 $\\frac{${dy}}{${dx}}$ 이고, 수직인 직선의 기울기는 그 음의 역수예요.`, `Hệ số góc của bán kính là $\\frac{${dy}}{${dx}}$; tiếp tuyến có hệ số góc là số đối nghịch đảo của nó.`)], expl: P(`기울기는 $-\\frac{${dx}}{${dy}}=${Number(m.toFixed(4))}$.`, `Hệ số góc là $-\\frac{${dx}}{${dy}}=${Number(m.toFixed(4))}$.`) }); };
  const l5 = [dist(1, "core", 1, 1, 2, 4, 6), lineDist(2, "core", 2, 1, 2, -21), center(3, "core", 2, -4, 6, -3), lake(4, "core", 2, 2, 1, 5, 5, 5), tangent(5, "core", 3, 2, 1, 3, 4)];
  dist("v1", "variant", 1, -1, 1, 4, 13); lineDist("v2", "variant", 2, 2, -1, -7); center("v3", "variant", 2, 6, -2, 1); lake("v4", "variant", 2, 0, 0, 5, 2, 3); tangent("v5", "variant", 3, -1, 2, 4, 3);
  dist("d1", "diagnostic", 2, 0, 0, 6, 8); center("d2", "diagnostic", 3, -8, -10, 5); lake("d3", "diagnostic", 4, 1, 1, 5, 4, 5);

  K.course({
    slug: "common-math-1", title: T("고1 수학: 다항식·복소수·경우의 수·도형의 방정식", "Toán lớp 10: Đa thức, số phức, tổ hợp và hình học tọa độ"),
    world: { name: T("공통수학 협곡", "Hẻm núi Toán chung"), emoji: "🏔️", tagline: T("다항식에서 도형의 방정식까지, 고등 수학의 기초를 다져요.", "Từ đa thức đến phương trình hình học: xây nền tảng cho toán phổ thông.") }, unitTitle: T("고1 수학", "Toán lớp 10"),
    lessons: [
      K.lesson(1, "poly", T("다항식의 나눗셈과 나머지정리", "Chia đa thức và định lý số dư"), T("$P(x)$ 를 $x-a$ 로 나눈 나머지는 $P(a)$ 이고, $P(a)=0$ 이면 $x-a$ 는 인수예요.", "Số dư khi chia $P(x)$ cho $x-a$ là $P(a)$; nếu $P(a)=0$ thì $x-a$ là một nhân tử."), T("$x^2+3x+2$ 를 $x-1$ 로 나눈 나머지 $=P(1)=6$", "Số dư khi chia $x^2+3x+2$ cho $x-1$ là $P(1)=6$"), l1),
      K.lesson(2, "cplx", T("복소수와 이차방정식의 판별", "Số phức và biệt thức"), T("$i^2=-1$ 이고, 판별식 $D=b^2-4ac<0$ 이면 허근을 가져요. 실계수 이차방정식의 허근은 켤레복소수끼리 쌍으로 나타나요.", "$i^2=-1$; khi $D=b^2-4ac<0$ phương trình có nghiệm phức. Nghiệm phức của phương trình hệ số thực xuất hiện thành cặp liên hợp."), T("$(1+2i)(3-i)=5+5i$", "$(1+2i)(3-i)=5+5i$"), l2),
      K.lesson(3, "ineq", T("이차부등식", "Bất phương trình bậc hai"), T("이차함수의 그래프와 $x$축의 위치로 해를 읽어요. $(x-a)(x-b)<0$ 은 두 근 사이, $>0$ 은 두 근 바깥이에요.", "Đọc nghiệm từ vị trí parabol so với trục hoành. $(x-a)(x-b)<0$ là giữa hai nghiệm, $>0$ là ngoài hai nghiệm."), T("$x^2-4x+3<0 \\Rightarrow 1<x<3$", "$x^2-4x+3<0 \\Rightarrow 1<x<3$"), l3),
      K.lesson(4, "comb", T("순열과 조합", "Hoán vị và tổ hợp"), T("순서를 생각하면 순열 $_nP_r$, 생각하지 않으면 조합 $_nC_r$ 이에요. '적어도 하나'는 전체에서 여사건을 빼요.", "Có thứ tự thì dùng chỉnh hợp $P(n,r)$, không thứ tự thì dùng tổ hợp $C(n,r)$. Với 'ít nhất một' hãy lấy tổng trừ trường hợp đối."), T("$_5P_2=20,\\ _5C_2=10$", "$P(5,2)=20,\\ C(5,2)=10$"), l4),
      K.lesson(5, "geom", T("직선과 원의 방정식", "Phương trình đường thẳng và đường tròn"), T("점과 직선 사이의 거리 $\\frac{|ax_0+by_0+c|}{\\sqrt{a^2+b^2}}$, 원 $(x-a)^2+(y-b)^2=r^2$, 접선은 반지름에 수직이에요.", "Khoảng cách điểm–đường thẳng $\\frac{|ax_0+by_0+c|}{\\sqrt{a^2+b^2}}$, đường tròn $(x-a)^2+(y-b)^2=r^2$; tiếp tuyến vuông góc với bán kính."), T("원 $x^2+y^2=25$ 위의 점 $(3,\\ 4)$ 에서의 접선의 기울기 $=-\\frac34$", "Tiếp tuyến của đường tròn $x^2+y^2=25$ tại $(3,\\ 4)$ có hệ số góc $-\\frac34$"), l5),
    ],
  });
}
