import { T, tex, term, poly, makeMathKit, ONE, WHICH_WRONG } from "./math-kit.mjs";

const P = T;
const evalP = (cs, x) => cs.reduce((acc, c) => acc * x + c, 0);

/** High 2 (algebra + calculus I): exponents and logarithms, trigonometric functions, sequences, limits, derivatives. */
export function h2(b) {
  const S = { log: "m.h2.log", trig: "m.h2.trig", seq: "m.h2.seq", lim: "m.h2.lim", der: "m.h2.der" };
  b.skill(S.log, T("지수와 로그", "Lũy thừa và logarit"));
  b.skill(S.trig, T("삼각함수", "Hàm số lượng giác"), S.log);
  b.skill(S.seq, T("등차수열과 등비수열", "Cấp số cộng và cấp số nhân"), S.trig);
  b.skill(S.lim, T("함수의 극한과 연속", "Giới hạn và tính liên tục của hàm số"), S.seq);
  b.skill(S.der, T("미분과 그 활용", "Đạo hàm và ứng dụng"), S.lim);
  const K = makeMathKit(b, "h2", S);
  const { numeric, choice } = K;

  /* ------------------------------ 1. exponents and logarithms ------------------------------ */
  const logVal = (n, role, d, base, e) => numeric({ k: "log", n, role, d, fam: "log-value", prompt: P(`${tex(`\\log_{${base}} ${base ** e}`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\log_{${base}} ${base ** e}`)} là bao nhiêu? ${ONE.vi}`), value: e,
    hints: [P("$\\log_a b=x$ 는 $a^x=b$ 라는 뜻이에요.", "$\\log_a b=x$ nghĩa là $a^x=b$."), P(`$${base}^{?}=${base ** e}$ 를 찾아요.`, `Tìm số mũ để $${base}^{?}=${base ** e}$.`)], expl: P(`$${base}^{${e}}=${base ** e}$ 이므로 $\\log_{${base}} ${base ** e}=${e}$.`, `Vì $${base}^{${e}}=${base ** e}$ nên $\\log_{${base}} ${base ** e}=${e}$.`) });
  const expLaw = (n, role, d, a, p, q, r) => numeric({ k: "log", n, role, d, fam: "log-law", tags: ["multistep"], prompt: P(`${tex(`\\frac{${a}^{${p}} \\times ${a}^{${q}}}{${a}^{${r}}} = ${a}^{k}`)} 일 때 $k$의 값은? ${ONE.ko}`, `Nếu ${tex(`\\frac{${a}^{${p}} \\times ${a}^{${q}}}{${a}^{${r}}} = ${a}^{k}`)} thì $k$ bằng bao nhiêu? ${ONE.vi}`), value: p + q - r,
    hints: [P("곱은 지수를 더하고, 나눗셈은 지수를 빼요.", "Nhân thì cộng số mũ, chia thì trừ số mũ."), P(`${p}+${q}-${r}`, `${p}+${q}-${r}`)], expl: P(`$${a}^{${p}+${q}-${r}}=${a}^{${p + q - r}}$ 이므로 $k=${p + q - r}$.`, `$${a}^{${p}+${q}-${r}}=${a}^{${p + q - r}}$ nên $k=${p + q - r}$.`) });
  const wrongLog = (n, role, d, bs, m, e) => { const t = [`\\log_{${bs}} ${bs ** m}+\\log_{${bs}} ${bs ** e}=\\log_{${bs}} ${bs ** (m + e)}`, `\\log_{${bs}} ${bs ** (m + e)}-\\log_{${bs}} ${bs ** e}=${m}`, `\\log_{${bs}} ${bs ** m}=${m}`];
    const f = `\\log_{${bs}} ${bs ** m}+\\log_{${bs}} ${bs ** e}=\\log_{${bs}} ${bs ** m + bs ** e}`;
    return choice({ k: "log", n, role, d, fam: "log-wrong", tags: ["reasoning"], prompt: WHICH_WRONG, right: tex(f), wrong: t.map((s) => tex(s)),
      hints: [P("로그의 합은 진수의 곱으로, 차는 진수의 나눗셈으로 바뀌어요.", "Tổng logarit bằng logarit của tích, hiệu bằng logarit của thương."), P("각 식의 값을 직접 계산해 확인해 보세요.", "Hãy tự tính giá trị từng đẳng thức để kiểm tra.")], expl: P(`$\\log_{${bs}}A+\\log_{${bs}}B=\\log_{${bs}}AB$ 이므로 진수는 더하는 것이 아니라 곱해야 해요.`, `$\\log_{${bs}}A+\\log_{${bs}}B=\\log_{${bs}}AB$ nên đối số phải nhân với nhau chứ không cộng.`) }); };
  const grow = (n, role, d, start, factor, t) => numeric({ k: "log", n, role, d, fam: "log-grow", tags: ["context", "multistep"], prompt: P(`어떤 세균은 1시간마다 ${factor}배로 늘어납니다. 처음 ${start}마리였다면 ${start * factor ** t}마리가 되는 것은 몇 시간 후일까요? ${ONE.ko}`, `Một loài vi khuẩn cứ mỗi 1 giờ tăng gấp ${factor} lần. Ban đầu có ${start} con thì sau bao nhiêu giờ có ${start * factor ** t} con? ${ONE.vi}`), value: t,
    hints: [P(`$t$시간 후의 개체 수는 $${start}\\times ${factor}^t$ 예요.`, `Sau $t$ giờ số con là $${start}\\times ${factor}^t$.`), P(`$${factor}^t=${factor ** t}$ 에서 $t$를 구해요.`, `Giải $${factor}^t=${factor ** t}$ để tìm $t$.`)], expl: P(`$${start}\\times ${factor}^t=${start * factor ** t}$ 에서 $${factor}^t=${factor ** t}$, $t=${t}$.`, `Từ $${start}\\times ${factor}^t=${start * factor ** t}$ ta có $${factor}^t=${factor ** t}$, suy ra $t=${t}$.`) });
  const logSum = (n, role, d, bs, p, q, r, k) => numeric({ k: "log", n, role, d, fam: "log-sum", tags: ["multistep", "reasoning"], prompt: P(`${tex(`\\log_{${bs}} ${p}+\\log_{${bs}} ${q}-\\log_{${bs}} ${r}`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\log_{${bs}} ${p}+\\log_{${bs}} ${q}-\\log_{${bs}} ${r}`)} là bao nhiêu? ${ONE.vi}`), value: k,
    hints: [P("하나의 로그로 합쳐요: $\\log_a\\frac{pq}{r}$", "Gộp thành một logarit: $\\log_a\\frac{pq}{r}$."), P(`진수를 계산하면 ${(p * q) / r} 이에요.`, `Đối số tính được là ${(p * q) / r}.`)], expl: P(`$\\log_{${bs}}\\frac{${p}\\times ${q}}{${r}}=\\log_{${bs}} ${(p * q) / r}=${k}$.`, `$\\log_{${bs}}\\frac{${p}\\times ${q}}{${r}}=\\log_{${bs}} ${(p * q) / r}=${k}$.`) });
  const l1 = [logVal(1, "core", 1, 2, 4), expLaw(2, "core", 2, 3, 5, 2, 4), wrongLog(3, "core", 2, 2, 2, 3), grow(4, "core", 3, 100, 2, 6), logSum(5, "core", 3, 3, 12, 9, 4, 3)];
  logVal("v1", "variant", 1, 3, 3); expLaw("v2", "variant", 2, 2, 6, 3, 5); wrongLog("v3", "variant", 2, 3, 1, 2); grow("v4", "variant", 3, 50, 3, 4);
  logVal("d1", "diagnostic", 1, 5, 2); expLaw("d2", "diagnostic", 2, 7, 4, 3, 2); logSum("d3", "diagnostic", 4, 2, 12, 8, 3, 5);

  /* ------------------------------ 2. trigonometric functions ------------------------------ */
  const toDeg = (n, role, d, k, m) => numeric({ k: "trig", n, role, d, fam: "trig-deg", prompt: P(`$\\theta=\\dfrac{${k === 1 ? "" : k}\\pi}{${m}}$ (라디안)를 도(°)로 나타내면 몇 도일까요? ${ONE.ko}`, `$\\theta=\\dfrac{${k === 1 ? "" : k}\\pi}{${m}}$ (rad) bằng bao nhiêu độ? ${ONE.vi}`), value: (180 * k) / m,
    hints: [P("$\\pi$ 라디안은 $180^\\circ$ 예요.", "$\\pi$ radian bằng $180^\\circ$."), P(`$180^\\circ\\times \\frac{${k}}{${m}}$`, `$180^\\circ\\times \\frac{${k}}{${m}}$`)], expl: P(`$180^\\circ\\times \\frac{${k}}{${m}}=${(180 * k) / m}^\\circ$.`, `$180^\\circ\\times \\frac{${k}}{${m}}=${(180 * k) / m}^\\circ$.`) });
  const special = (n, role, d) => numeric({ k: "trig", n, role, d, fam: "trig-value", tags: ["multistep"], prompt: P(`${tex("\\sin 30^\\circ+\\cos 60^\\circ+\\tan 45^\\circ")} 의 값은? ${ONE.ko}`, `Giá trị của ${tex("\\sin 30^\\circ+\\cos 60^\\circ+\\tan 45^\\circ")} là bao nhiêu? ${ONE.vi}`), value: 2,
    hints: [P("$\\sin 30^\\circ=\\frac12,\\ \\cos 60^\\circ=\\frac12,\\ \\tan 45^\\circ=1$", "$\\sin 30^\\circ=\\frac12,\\ \\cos 60^\\circ=\\frac12,\\ \\tan 45^\\circ=1$."), P("세 값을 더해요.", "Cộng ba giá trị lại.")], expl: P("$\\frac12+\\frac12+1=2$.", "$\\frac12+\\frac12+1=2$.") });
  const quadrant = (n, role, d, quad) => { const names = ["제1", "제2", "제3", "제4"]; const sg = [[1, 1, 1], [1, -1, -1], [-1, -1, 1], [-1, 1, -1]][quad - 1]; const ok = [T("$\\sin\\theta>0$", "$\\sin\\theta>0$"), T("$\\cos\\theta>0$", "$\\cos\\theta>0$"), T("$\\tan\\theta>0$", "$\\tan\\theta>0$")]; const bad = [T("$\\sin\\theta<0$", "$\\sin\\theta<0$"), T("$\\cos\\theta<0$", "$\\cos\\theta<0$"), T("$\\tan\\theta<0$", "$\\tan\\theta<0$")];
    const list = [0, 1, 2].map((i) => (sg[i] > 0 ? ok[i] : bad[i])); const falseOne = (sg[0] > 0 ? bad[0] : ok[0]);
    return choice({ k: "trig", n, role, d, fam: "trig-sign", tags: ["reasoning"], prompt: P(`$\\theta$ 가 ${names[quad - 1]}사분면의 각일 때, 옳지 않은 것은?`, `Khi $\\theta$ là góc thuộc góc phần tư thứ ${quad}, nhận xét nào KHÔNG đúng?`), right: falseOne, wrong: list,
      hints: [P("각 사분면에서 $\\sin,\\ \\cos,\\ \\tan$ 의 부호를 떠올려 보세요 (모두·사인·탄젠트·코사인).", "Hãy nhớ dấu của $\\sin,\\ \\cos,\\ \\tan$ ở từng góc phần tư."), P("단위원에서 점의 좌표 $(\\cos\\theta,\\ \\sin\\theta)$ 의 부호를 보면 돼요.", "Nhìn dấu của tọa độ $(\\cos\\theta,\\ \\sin\\theta)$ của điểm trên đường tròn đơn vị.")], expl: P(`${names[quad - 1]}사분면에서는 ${falseOne === ok[0] ? "$\\sin\\theta<0$" : "$\\sin\\theta>0$"} 이므로, 반대로 말한 보기가 옳지 않아요.`, `Ở góc phần tư thứ ${quad}, ${falseOne === ok[0] ? "$\\sin\\theta<0$" : "$\\sin\\theta>0$"} nên phát biểu ngược lại là sai.`) }); };
  const wheel = (n, role, d, R, H, deg) => numeric({ k: "trig", n, role, d, fam: "trig-wheel", tags: ["context", "multistep"], prompt: P(`반지름이 ${R} m이고 중심의 높이가 ${H} m인 대관람차가 있습니다. 칸의 높이가 $h=${H}+${R}\\sin\\theta$ (m)로 주어질 때, $\\theta=${deg}^\\circ$ 인 위치의 높이는 몇 m일까요? ${ONE.ko}`, `Vòng đu quay có bán kính ${R} m và tâm ở độ cao ${H} m. Độ cao của cabin là $h=${H}+${R}\\sin\\theta$ (m). Tại vị trí $\\theta=${deg}^\\circ$ thì cabin ở độ cao bao nhiêu mét? ${ONE.vi}`), value: H + R * (deg === 30 ? 0.5 : 1),
    hints: [P(`$\\sin ${deg}^\\circ=${deg === 30 ? "\\frac12" : "1"}$ 이에요.`, `$\\sin ${deg}^\\circ=${deg === 30 ? "\\frac12" : "1"}$.`), P(`${H}+${R}×$\\sin ${deg}^\\circ$ 를 계산해요.`, `Tính ${H}+${R}×$\\sin ${deg}^\\circ$.`)], expl: P(`$${H}+${R}\\times ${deg === 30 ? "\\frac12" : "1"}=${H + R * (deg === 30 ? 0.5 : 1)}$ (m).`, `$${H}+${R}\\times ${deg === 30 ? "\\frac12" : "1"}=${H + R * (deg === 30 ? 0.5 : 1)}$ (m).`) });
  const sinFn = (n, role, d, a, bb, c) => { const kk = 2 / bb; return numeric({ k: "trig", n, role, d, fam: "trig-graph", tags: ["multistep", "reasoning"], prompt: P(`함수 ${tex(`y=${a}\\sin ${bb === 1 ? "" : bb}x${term(c)}`)} 의 최댓값을 $M$, 주기를 $k\\pi$ 라 할 때 $M+k$의 값은? ${ONE.ko}`, `Hàm số ${tex(`y=${a}\\sin ${bb === 1 ? "" : bb}x${term(c)}`)} có giá trị lớn nhất là $M$ và chu kỳ là $k\\pi$. Tính $M+k$. ${ONE.vi}`), value: a + c + kk,
    hints: [P("$y=a\\sin bx+c$ 의 최댓값은 $|a|+c$, 주기는 $\\frac{2\\pi}{|b|}$ 예요.", "Hàm $y=a\\sin bx+c$ có giá trị lớn nhất $|a|+c$ và chu kỳ $\\frac{2\\pi}{|b|}$."), P(`주기는 $\\frac{2\\pi}{${bb}}=${kk}\\pi$ 예요.`, `Chu kỳ là $\\frac{2\\pi}{${bb}}=${kk}\\pi$.`)], expl: P(`$M=${a + c}$, $k=${kk}$ 이므로 $M+k=${a + c + kk}$.`, `$M=${a + c}$, $k=${kk}$ nên $M+k=${a + c + kk}$.`) }); };
  const l2 = [toDeg(1, "core", 1, 1, 6), special(2, "core", 2), quadrant(3, "core", 2, 2), wheel(4, "core", 2, 10, 12, 30), sinFn(5, "core", 3, 3, 2, 1)];
  toDeg("v1", "variant", 1, 2, 3); quadrant("v2", "variant", 2, 3); wheel("v3", "variant", 2, 20, 22, 30); sinFn("v4", "variant", 3, 2, 1, -1);
  toDeg("d1", "diagnostic", 1, 3, 4); quadrant("d2", "diagnostic", 3, 4); sinFn("d3", "diagnostic", 4, 4, 2, 3);

  /* ------------------------------ 3. sequences ------------------------------ */
  const arith = (n, role, d, a1, dd, k) => numeric({ k: "seq", n, role, d, fam: "seq-arith", prompt: P(`첫째항이 ${a1}, 공차가 ${dd}인 등차수열의 제${k}항은? ${ONE.ko}`, `Số hạng thứ ${k} của cấp số cộng có số hạng đầu ${a1} và công sai ${dd} là bao nhiêu? ${ONE.vi}`), value: a1 + (k - 1) * dd,
    hints: [P("일반항 $a_n=a+(n-1)d$ 를 써요.", "Dùng công thức số hạng tổng quát $a_n=a+(n-1)d$."), P(`${a1}+(${k}-1)×${dd}`, `${a1}+(${k}-1)×${dd}`)], expl: P(`$a_{${k}}=${a1}+${k - 1}\\times ${dd}=${a1 + (k - 1) * dd}$.`, `$a_{${k}}=${a1}+${k - 1}\\times ${dd}=${a1 + (k - 1) * dd}$.`) });
  const geo = (n, role, d, a1, r, k) => numeric({ k: "seq", n, role, d, fam: "seq-geo", prompt: P(`첫째항이 ${a1}, 공비가 ${r}인 등비수열의 제${k}항은? ${ONE.ko}`, `Số hạng thứ ${k} của cấp số nhân có số hạng đầu ${a1} và công bội ${r} là bao nhiêu? ${ONE.vi}`), value: a1 * r ** (k - 1),
    hints: [P("일반항 $a_n=ar^{n-1}$ 을 써요.", "Dùng công thức số hạng tổng quát $a_n=ar^{n-1}$."), P(`${a1}×${r}^${k - 1}`, `${a1}×${r}^${k - 1}`)], expl: P(`$a_{${k}}=${a1}\\times ${r}^{${k - 1}}=${a1 * r ** (k - 1)}$.`, `$a_{${k}}=${a1}\\times ${r}^{${k - 1}}=${a1 * r ** (k - 1)}$.`) });
  const kind = (n, role, d, wantGeo) => { const A = T("$2,\\ 5,\\ 8,\\ 11,\\ \\cdots$", "$2,\\ 5,\\ 8,\\ 11,\\ \\cdots$"), G = T("$3,\\ 6,\\ 12,\\ 24,\\ \\cdots$", "$3,\\ 6,\\ 12,\\ 24,\\ \\cdots$"), Sq = T("$1,\\ 4,\\ 9,\\ 16,\\ \\cdots$", "$1,\\ 4,\\ 9,\\ 16,\\ \\cdots$"), Fb = T("$1,\\ 1,\\ 2,\\ 3,\\ \\cdots$", "$1,\\ 1,\\ 2,\\ 3,\\ \\cdots$");
    return choice({ k: "seq", n, role, d, fam: "seq-kind", tags: ["reasoning"], prompt: wantGeo ? P("다음 중 등비수열은?", "Dãy số nào sau đây là cấp số nhân?") : P("다음 중 등차수열은?", "Dãy số nào sau đây là cấp số cộng?"), right: wantGeo ? G : A, wrong: wantGeo ? [A, Sq, Fb] : [G, Sq, Fb],
      hints: [P("이웃한 두 항의 차가 일정하면 등차, 비가 일정하면 등비예요.", "Hiệu hai số hạng liên tiếp không đổi là cấp số cộng, tỉ số không đổi là cấp số nhân."), P("각 수열에서 차와 비를 구해 보세요.", "Hãy tính hiệu và tỉ số trong từng dãy.")], expl: wantGeo ? P("$3,\\ 6,\\ 12,\\ 24$ 는 이웃한 항의 비가 항상 2예요.", "Dãy $3,\\ 6,\\ 12,\\ 24$ có tỉ số hai số hạng liên tiếp luôn bằng 2.") : P("$2,\\ 5,\\ 8,\\ 11$ 은 이웃한 항의 차가 항상 3이에요.", "Dãy $2,\\ 5,\\ 8,\\ 11$ có hiệu hai số hạng liên tiếp luôn bằng 3.") }); };
  const saving = (n, role, d, first, step, months) => numeric({ k: "seq", n, role, d, fam: "seq-saving", tags: ["context", "multistep"], prompt: P(`첫 달에 ${first}만 원을 저금하고 다음 달부터 매달 ${step}만 원씩 더 저금합니다. ${months}개월 동안 저금한 금액은 모두 몇 만 원일까요? ${ONE.ko}`, `Tháng đầu tiết kiệm ${first} chục nghìn đồng, từ tháng sau mỗi tháng gửi thêm ${step} chục nghìn đồng so với tháng trước. Sau ${months} tháng tiết kiệm được tổng cộng bao nhiêu chục nghìn đồng? ${ONE.vi}`), value: (months * (2 * first + (months - 1) * step)) / 2,
    hints: [P("매달 저금액은 등차수열이에요. 합의 공식 $S_n=\\frac{n\\{2a+(n-1)d\\}}{2}$ 를 써요.", "Số tiền mỗi tháng lập thành cấp số cộng; dùng $S_n=\\frac{n\\{2a+(n-1)d\\}}{2}$."), P(`$a=${first},\\ d=${step},\\ n=${months}$`, `$a=${first},\\ d=${step},\\ n=${months}$`)], expl: P(`$S_{${months}}=\\frac{${months}\\times(${2 * first}+${(months - 1) * step})}{2}=${(months * (2 * first + (months - 1) * step)) / 2}$.`, `$S_{${months}}=\\frac{${months}\\times(${2 * first}+${(months - 1) * step})}{2}=${(months * (2 * first + (months - 1) * step)) / 2}$.`) });
  const sumFromTerm = (n, role, d, a1, dd, k) => { const ak = a1 + (k - 1) * dd; return numeric({ k: "seq", n, role, d, fam: "seq-sum", tags: ["multistep", "reasoning"], prompt: P(`첫째항이 ${a1}인 등차수열의 제${k}항이 ${ak}일 때, 첫째항부터 제${k}항까지의 합은? ${ONE.ko}`, `Cấp số cộng có số hạng đầu ${a1} và số hạng thứ ${k} bằng ${ak}. Tổng ${k} số hạng đầu là bao nhiêu? ${ONE.vi}`), value: (k * (a1 + ak)) / 2,
    hints: [P("처음과 끝 항을 알면 $S_n=\\frac{n(a+l)}{2}$ 로 바로 구할 수 있어요.", "Biết số hạng đầu và cuối thì dùng ngay $S_n=\\frac{n(a+l)}{2}$."), P(`$n=${k},\\ a=${a1},\\ l=${ak}$`, `$n=${k},\\ a=${a1},\\ l=${ak}$`)], expl: P(`$S_{${k}}=\\frac{${k}\\times(${a1}+${ak})}{2}=${(k * (a1 + ak)) / 2}$.`, `$S_{${k}}=\\frac{${k}\\times(${a1}+${ak})}{2}=${(k * (a1 + ak)) / 2}$.`) }); };
  const l3 = [arith(1, "core", 1, 3, 4, 10), geo(2, "core", 2, 2, 3, 5), kind(3, "core", 2, true), saving(4, "core", 3, 10, 5, 12), sumFromTerm(5, "core", 3, 2, 4, 8)];
  arith("v1", "variant", 1, 5, -2, 8); geo("v2", "variant", 2, 5, 2, 6); kind("v3", "variant", 2, false); saving("v4", "variant", 3, 20, 10, 6);
  arith("d1", "diagnostic", 1, 7, 3, 20); geo("d2", "diagnostic", 2, 3, 2, 7); sumFromTerm("d3", "diagnostic", 4, 5, 3, 10);

  /* ------------------------------ 4. limits ------------------------------ */
  const limPoly = (n, role, d, a, c, x0) => numeric({ k: "lim", n, role, d, fam: "lim-poly", prompt: P(`${tex(`\\lim_{x\\to ${x0}}(${a}x${term(c)})`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\lim_{x\\to ${x0}}(${a}x${term(c)})`)} là bao nhiêu? ${ONE.vi}`), value: a * x0 + c,
    hints: [P("다항함수는 $x$ 대신 극한값을 그대로 대입해요.", "Với hàm đa thức chỉ cần thay trực tiếp giá trị của $x$."), P(`$${a}\\times ${x0}${term(c)}$`, `$${a}\\times ${x0}${term(c)}$`)], expl: P(`$${a}\\times ${x0}${term(c)}=${a * x0 + c}$.`, `$${a}\\times ${x0}${term(c)}=${a * x0 + c}$.`) });
  const limFrac = (n, role, d, a) => numeric({ k: "lim", n, role, d, fam: "lim-frac", tags: ["multistep"], prompt: P(`${tex(`\\lim_{x\\to ${a}}\\frac{x^2-${a * a}}{x-${a}}`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\lim_{x\\to ${a}}\\frac{x^2-${a * a}}{x-${a}}`)} là bao nhiêu? ${ONE.vi}`), value: 2 * a,
    hints: [P("그냥 대입하면 $\\frac00$ 꼴이에요. 분자를 인수분해해 약분해요.", "Thay trực tiếp được dạng $\\frac00$; hãy phân tích tử số rồi rút gọn."), P(`$x^2-${a * a}=(x-${a})(x+${a})$`, `$x^2-${a * a}=(x-${a})(x+${a})$`)], expl: P(`$\\lim (x+${a})=${2 * a}$.`, `$\\lim (x+${a})=${2 * a}$.`) });
  const continuous = (n, role, d, m, x0) => { const a = (m + 2) * x0 - 1 - x0; return numeric({ k: "lim", n, role, d, fam: "lim-cont", tags: ["reasoning", "multistep"], prompt: P(`함수 $f(x)=\\begin{cases} x+a & (x<${x0}) \\\\ ${m + 2}x-1 & (x\\ge ${x0}) \\end{cases}$ 가 $x=${x0}$ 에서 연속일 때, 상수 $a$의 값은? ${ONE.ko}`, `Hàm số $f(x)=\\begin{cases} x+a & (x<${x0}) \\\\ ${m + 2}x-1 & (x\\ge ${x0}) \\end{cases}$ liên tục tại $x=${x0}$. Tìm hằng số $a$. ${ONE.vi}`), value: a,
    hints: [P("연속이면 좌극한과 우극한, 함숫값이 모두 같아요.", "Liên tục thì giới hạn trái, giới hạn phải và giá trị hàm bằng nhau."), P(`${x0}+a = ${m + 2}×${x0}−1 로 식을 세워요.`, `Lập phương trình ${x0}+a = ${m + 2}×${x0}−1.`)], expl: P(`$${x0}+a=${(m + 2) * x0 - 1}$ 이므로 $a=${a}$.`, `Từ $${x0}+a=${(m + 2) * x0 - 1}$ ta có $a=${a}$.`) }); };
  const drug = (n, role, d, p, q, r, s) => numeric({ k: "lim", n, role, d, fam: "lim-drug", tags: ["context", "multistep"], prompt: P(`약을 먹은 지 $t$시간 후 혈중 농도가 $C(t)=\\dfrac{${p}t+${q}}{${r}t+${s}}$ (mg/L)일 때, 시간이 아주 오래 지나면 농도는 어떤 값에 가까워질까요? ${ONE.ko}`, `Sau $t$ giờ uống thuốc, nồng độ trong máu là $C(t)=\\dfrac{${p}t+${q}}{${r}t+${s}}$ (mg/L). Khi thời gian rất lớn, nồng độ tiến gần tới giá trị nào? ${ONE.vi}`), value: p / r,
    hints: [P("분모와 분자를 $t$로 나누고 $t\\to\\infty$ 를 생각해요.", "Chia cả tử và mẫu cho $t$ rồi cho $t\\to\\infty$."), P("$\\frac1t\\to 0$ 이에요.", "$\\frac1t\\to 0$.")], expl: P(`$\\frac{${p}+${q}/t}{${r}+${s}/t}\\to \\frac{${p}}{${r}}=${p / r}$.`, `$\\frac{${p}+${q}/t}{${r}+${s}/t}\\to \\frac{${p}}{${r}}=${p / r}$.`) });
  const sqrtLim = (n, role, d, a) => numeric({ k: "lim", n, role, d, fam: "lim-sqrt", tags: ["multistep", "reasoning"], prompt: P(`${tex(`\\lim_{x\\to\\infty}\\left(\\sqrt{x^2+${a}x}-x\\right)`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\lim_{x\\to\\infty}\\left(\\sqrt{x^2+${a}x}-x\\right)`)} là bao nhiêu? ${ONE.vi}`), value: a / 2,
    hints: [P("$\\infty-\\infty$ 꼴이에요. 분자를 유리화해요(켤레식을 곱해요).", "Dạng $\\infty-\\infty$; hãy nhân với biểu thức liên hợp."), P(`$\\frac{${a}x}{\\sqrt{x^2+${a}x}+x}$ 의 분모와 분자를 $x$ 로 나눠요.`, `Chia tử và mẫu của $\\frac{${a}x}{\\sqrt{x^2+${a}x}+x}$ cho $x$.`)], expl: P(`$\\frac{${a}}{\\sqrt{1+${a}/x}+1}\\to \\frac{${a}}{2}=${a / 2}$.`, `$\\frac{${a}}{\\sqrt{1+${a}/x}+1}\\to \\frac{${a}}{2}=${a / 2}$.`) });
  const l4 = [limPoly(1, "core", 1, 3, 1, 2), limFrac(2, "core", 2, 3), continuous(3, "core", 2, 1, 1), drug(4, "core", 2, 6, 5, 2, 1), sqrtLim(5, "core", 3, 8)];
  limPoly("v1", "variant", 1, 2, -5, 4); limFrac("v2", "variant", 2, 5); continuous("v3", "variant", 2, 2, 2); drug("v4", "variant", 2, 9, 4, 3, 2);
  limPoly("d1", "diagnostic", 1, 5, 2, 3); limFrac("d2", "diagnostic", 3, 7); sqrtLim("d3", "diagnostic", 4, 12);

  /* ------------------------------ 5. derivatives ------------------------------ */
  const diffAt = (n, role, d, cs, x0) => { const m = cs.length - 1; const dc = cs.slice(0, -1).map((c, i) => c * (m - i)); return numeric({ k: "der", n, role, d, fam: "der-value", prompt: P(`$f(x)=${poly(cs)}$ 일 때 $f'(${x0})$ 의 값은? ${ONE.ko}`, `Với $f(x)=${poly(cs)}$, giá trị của $f'(${x0})$ là bao nhiêu? ${ONE.vi}`), value: evalP(dc, x0),
    hints: [P("$(x^n)'=nx^{n-1}$ 을 항마다 적용해요.", "Áp dụng $(x^n)'=nx^{n-1}$ cho từng hạng tử."), P(`$f'(x)=${poly(dc)}$`, `$f'(x)=${poly(dc)}$.`)], expl: P(`$f'(x)=${poly(dc)}$ 이므로 $f'(${x0})=${evalP(dc, x0)}$.`, `$f'(x)=${poly(dc)}$ nên $f'(${x0})=${evalP(dc, x0)}$.`) }); };
  const tangentY = (n, role, d, bb, cc, x0) => { const f = (x) => x * x + bb * x + cc; const m = 2 * x0 + bb; const y0 = f(x0); const ic = y0 - m * x0;
    return numeric({ k: "der", n, role, d, fam: "der-tangent", tags: ["multistep"], prompt: P(`곡선 $y=${poly([1, bb, cc])}$ 위의 $x=${x0}$ 인 점에서의 접선이 $y$축과 만나는 점의 $y$좌표는? ${ONE.ko}`, `Tiếp tuyến của đường cong $y=${poly([1, bb, cc])}$ tại điểm có $x=${x0}$ cắt trục tung tại điểm có tung độ bao nhiêu? ${ONE.vi}`), value: ic,
      hints: [P("접선의 기울기는 $f'(x_0)$, 접점은 $(x_0,\\ f(x_0))$ 예요.", "Hệ số góc tiếp tuyến là $f'(x_0)$, tiếp điểm là $(x_0,\\ f(x_0))$."), P(`기울기 ${m}, 접점 $(${x0},\\ ${y0})$ 로 직선의 식을 세워요.`, `Hệ số góc ${m}, tiếp điểm $(${x0},\\ ${y0})$; lập phương trình đường thẳng.`)], expl: P(`접선: $y-${y0}=${m}(x-${x0})$, $y$절편은 $${y0}-${m * x0}=${ic}$.`, `Tiếp tuyến: $y-${y0}=${m}(x-${x0})$, tung độ gốc là $${y0}-${m * x0}=${ic}$.`) }); };
  const decreasing = (n, role, d, r) => { const iv = (l, h) => tex(`${l}<x<${h}`); return choice({ k: "der", n, role, d, fam: "der-mono", tags: ["reasoning"], prompt: P(`함수 ${tex(`f(x)=x^3-${3 * r * r}x`)} 가 감소하는 $x$의 구간은?`, `Hàm số ${tex(`f(x)=x^3-${3 * r * r}x`)} nghịch biến trên khoảng nào của $x$?`), right: iv(-r, r), wrong: [P(`$x<${-r}$ 또는 $x>${r}$`, `$x<${-r}$ hoặc $x>${r}$`), iv(0, r), iv(-r, 0)],
      hints: [P("$f'(x)<0$ 인 구간에서 함수는 감소해요.", "Hàm số nghịch biến ở những khoảng mà $f'(x)<0$."), P(`$f'(x)=3x^2-${3 * r * r}=3(x-${r})(x+${r})$`, `$f'(x)=3x^2-${3 * r * r}=3(x-${r})(x+${r})$.`)], expl: P(`$f'(x)<0$ 에서 $${-r}<x<${r}$ 이에요.`, `Từ $f'(x)<0$ ta có $${-r}<x<${r}$.`) }); };
  const velocity = (n, role, d, r1, r2) => { const A = 3, Bc = -3 * (r1 + r2), C = 3 * r1 * r2; return numeric({ k: "der", n, role, d, fam: "der-velocity", tags: ["context", "multistep"], prompt: P(`수직선 위를 움직이는 점의 위치가 $s(t)=t^3${term(-1.5 * (r1 + r2), "t^2")}${term(C, "t")}$ 일 때, 속도가 0이 되는 시각 중 더 늦은 시각은? (단, $t>0$) ${ONE.ko}`, `Vị trí của một điểm chuyển động trên trục số là $s(t)=t^3${term(-1.5 * (r1 + r2), "t^2")}${term(C, "t")}$. Trong các thời điểm vận tốc bằng 0 (với $t>0$), thời điểm muộn hơn là? ${ONE.vi}`), value: Math.max(r1, r2),
    hints: [P("속도는 위치의 도함수 $v(t)=s'(t)$ 예요.", "Vận tốc là đạo hàm của vị trí: $v(t)=s'(t)$."), P(`$v(t)=${A}t^2${term(Bc, "t")}${term(C)}=0$ 을 풀어요.`, `Giải $v(t)=${A}t^2${term(Bc, "t")}${term(C)}=0$.`)], expl: P(`$v(t)=3(t-${r1})(t-${r2})$ 이므로 $t=${r1}$ 또는 $t=${r2}$. 더 늦은 시각은 ${Math.max(r1, r2)}.`, `$v(t)=3(t-${r1})(t-${r2})$ nên $t=${r1}$ hoặc $t=${r2}$. Thời điểm muộn hơn là ${Math.max(r1, r2)}.`) }); };
  const localMax = (n, role, d, r1, r2, c0) => { const p = (-3 * (r1 + r2)) / 2, q = 3 * r1 * r2; const cs = [1, p, q, c0]; const lo = Math.min(r1, r2); return numeric({ k: "der", n, role, d, fam: "der-extreme", tags: ["multistep", "reasoning"], prompt: P(`함수 $f(x)=${poly(cs)}$ 의 극댓값은? ${ONE.ko}`, `Giá trị cực đại của hàm số $f(x)=${poly(cs)}$ là bao nhiêu? ${ONE.vi}`), value: evalP(cs, lo),
    hints: [P("$f'(x)=0$ 이 되는 $x$ 를 찾고, $f'$ 의 부호가 +에서 −로 바뀌는 곳을 골라요.", "Tìm $x$ để $f'(x)=0$ rồi chọn điểm mà $f'$ đổi dấu từ + sang −."), P(`$f'(x)=3(x-${r1})(x-${r2})$ 이므로 작은 쪽 ${lo} 에서 극대예요.`, `$f'(x)=3(x-${r1})(x-${r2})$ nên cực đại tại nghiệm nhỏ hơn là ${lo}.`)], expl: P(`$x=${lo}$ 에서 극대이고 극댓값은 $f(${lo})=${evalP(cs, lo)}$.`, `Hàm đạt cực đại tại $x=${lo}$ và giá trị cực đại là $f(${lo})=${evalP(cs, lo)}$.`) }); };
  const l5 = [diffAt(1, "core", 1, [3, 2, 0], 1), tangentY(2, "core", 2, -4, 5, 3), decreasing(3, "core", 2, 1), velocity(4, "core", 2, 1, 3), localMax(5, "core", 3, -1, 3, 1)];
  diffAt("v1", "variant", 1, [1, 0, -4, 2], 2); tangentY("v2", "variant", 2, 2, -1, 2); decreasing("v3", "variant", 2, 2); velocity("v4", "variant", 2, 2, 4); localMax("v5", "variant", 3, -2, 2, 3);
  diffAt("d1", "diagnostic", 1, [5, -3, 1], 2); decreasing("d2", "diagnostic", 3, 3); localMax("d3", "diagnostic", 4, -3, 1, 4);

  K.course({
    slug: "algebra-calculus-1", title: T("고2 수학: 로그·삼각함수·수열·극한·미분", "Toán lớp 11: Logarit, lượng giác, dãy số, giới hạn và đạo hàm"),
    world: { name: T("미적분 정상", "Đỉnh giải tích"), emoji: "🗻", tagline: T("지수와 로그에서 출발해 미분의 정상까지 올라가요.", "Từ lũy thừa và logarit lên tới đỉnh của đạo hàm.") }, unitTitle: T("고2 수학", "Toán lớp 11"),
    lessons: [
      K.lesson(1, "log", T("지수와 로그", "Lũy thừa và logarit"), T("$\\log_a b=x \\iff a^x=b$. 로그의 합은 진수의 곱, 차는 진수의 나눗셈이에요. 지수적 증가는 $a\\cdot r^t$ 로 나타내요.", "$\\log_a b=x \\iff a^x=b$. Tổng logarit là logarit của tích, hiệu là logarit của thương. Tăng trưởng mũ biểu diễn bằng $a\\cdot r^t$."), T("$\\log_2 8+\\log_2 4=\\log_2 32=5$", "$\\log_2 8+\\log_2 4=\\log_2 32=5$"), l1),
      K.lesson(2, "trig", T("삼각함수", "Hàm số lượng giác"), T("$\\pi$ 라디안 $=180^\\circ$. 사분면마다 $\\sin,\\ \\cos,\\ \\tan$ 의 부호가 달라요. $y=a\\sin bx+c$ 는 최댓값 $|a|+c$, 주기 $\\frac{2\\pi}{|b|}$ 예요.", "$\\pi$ radian $=180^\\circ$. Dấu của $\\sin,\\ \\cos,\\ \\tan$ thay đổi theo góc phần tư. Hàm $y=a\\sin bx+c$ có giá trị lớn nhất $|a|+c$ và chu kỳ $\\frac{2\\pi}{|b|}$."), T("$\\dfrac{\\pi}{6}=30^\\circ$", "$\\dfrac{\\pi}{6}=30^\\circ$"), l2),
      K.lesson(3, "seq", T("등차수열과 등비수열", "Cấp số cộng và cấp số nhân"), T("$a_n=a+(n-1)d$, $a_n=ar^{n-1}$. 등차수열의 합은 $S_n=\\frac{n(a+l)}{2}$ 예요.", "$a_n=a+(n-1)d$, $a_n=ar^{n-1}$. Tổng cấp số cộng: $S_n=\\frac{n(a+l)}{2}$."), T("$2,\\ 5,\\ 8,\\ \\cdots$ 의 제10항 $=29$", "Số hạng thứ 10 của $2,\\ 5,\\ 8,\\ \\cdots$ là $29$"), l3),
      K.lesson(4, "lim", T("함수의 극한과 연속", "Giới hạn và liên tục"), T("$\\frac00$ 꼴은 인수분해해 약분하고, $x\\to\\infty$ 에서는 최고차항으로 나눠요. 연속이면 좌극한·우극한·함숫값이 모두 같아요.", "Dạng $\\frac00$ thì phân tích và rút gọn; khi $x\\to\\infty$ chia cho số hạng bậc cao nhất. Liên tục khi giới hạn trái, phải và giá trị hàm bằng nhau."), T("$\\lim_{x\\to 3}\\frac{x^2-9}{x-3}=6$", "$\\lim_{x\\to 3}\\frac{x^2-9}{x-3}=6$"), l4),
      K.lesson(5, "der", T("미분과 그 활용", "Đạo hàm và ứng dụng"), T("$(x^n)'=nx^{n-1}$. $f'(a)$ 는 접선의 기울기이고, $f'$ 의 부호로 증가·감소와 극값을 알 수 있어요. 속도는 위치의 도함수예요.", "$(x^n)'=nx^{n-1}$. $f'(a)$ là hệ số góc tiếp tuyến; dấu của $f'$ cho biết khoảng đồng biến, nghịch biến và cực trị. Vận tốc là đạo hàm của vị trí."), T("$(x^3-3x)'=3x^2-3$", "$(x^3-3x)'=3x^2-3$"), l5),
    ],
  });
}
