import { T, tex, poly, fracTex, makeMathKit, ONE, WHICH_WRONG } from "./math-kit.mjs";

const P = T;
const FRAC = T("(분수는 0.48 처럼 소수로 써도 돼요)", "(có thể nhập phân số dưới dạng số thập phân, ví dụ 0,48)");
/** n = k^2 * m with m square-free: returns [k, m]. */
const simp = (n) => { let k = 1, m = n; for (let i = 2; i * i <= m; i++) while (m % (i * i) === 0) { m /= i * i; k *= i; } return [k, m]; };

/** Middle 3: square roots, expansion and factoring, quadratic equations, quadratic functions, trigonometric ratios. */
export function m3(b) {
  const S = { sqrt: "m.m3.sqrt", fact: "m.m3.fact", quad: "m.m3.quad", qfunc: "m.m3.qfunc", trig: "m.m3.trig" };
  b.skill(S.sqrt, T("제곱근과 실수", "Căn bậc hai và số thực"));
  b.skill(S.fact, T("다항식의 곱셈과 인수분해", "Nhân đa thức và phân tích thành nhân tử"), S.sqrt);
  b.skill(S.quad, T("이차방정식", "Phương trình bậc hai"), S.fact);
  b.skill(S.qfunc, T("이차함수와 그래프", "Hàm số bậc hai và đồ thị"), S.quad);
  b.skill(S.trig, T("삼각비", "Tỉ số lượng giác"), S.qfunc);
  const K = makeMathKit(b, "m3", S);
  const { numeric, choice } = K;

  /* ------------------------------ 1. square roots ------------------------------ */
  const root = (n, role, d, r) => numeric({ k: "sqrt", n, role, d, fam: "sqrt-value", prompt: P(`${tex(`\\sqrt{${r * r}}`)} 의 값은? ${ONE.ko}`, `Giá trị của ${tex(`\\sqrt{${r * r}}`)} là bao nhiêu? ${ONE.vi}`), value: r,
    hints: [P("제곱해서 그 수가 되는 양수를 찾아요.", "Tìm số dương mà bình phương lên bằng số đó."), P(`${r}×${r}=${r * r}`, `${r}×${r}=${r * r}`)], expl: P(`${r}의 제곱이 ${r * r}이므로 $\\sqrt{${r * r}}=${r}$.`, `${r}² = ${r * r} nên $\\sqrt{${r * r}}=${r}$.`) });
  const garden = (n, role, d, side) => numeric({ k: "sqrt", n, role, d, fam: "sqrt-garden", tags: ["context", "multistep"], prompt: P(`넓이가 ${side * side} m²인 정사각형 모양의 밭이 있습니다. 이 밭의 둘레는 몇 m일까요? ${ONE.ko}`, `Một thửa ruộng hình vuông có diện tích ${side * side} m². Chu vi thửa ruộng là bao nhiêu mét? ${ONE.vi}`), value: 4 * side,
    hints: [P("정사각형의 한 변은 넓이의 제곱근이에요.", "Cạnh hình vuông là căn bậc hai của diện tích."), P("둘레 = 한 변 × 4", "Chu vi = cạnh × 4.")], expl: P(`한 변은 $\\sqrt{${side * side}}=${side}$ m, 둘레는 ${side}×4=${4 * side} m.`, `Cạnh là $\\sqrt{${side * side}}=${side}$ m, chu vi là ${side}×4=${4 * side} m.`) });
  const trueRoot = (n, role, d, a) => choice({ k: "sqrt", n, role, d, fam: "sqrt-true", tags: ["reasoning"], prompt: P("다음 중 옳은 것은?", "Đẳng thức nào sau đây đúng?"), right: tex(`\\sqrt{(-${a})^2}=${a}`),
    wrong: [tex(`\\sqrt{(-${a})^2}=-${a}`), tex(`(-\\sqrt{${a}})^2=-${a}`), tex(`\\sqrt{${a * a}}=\\pm ${a}`)],
    hints: [P("$\\sqrt{\\ }$ 는 음이 아닌 제곱근만 나타내요.", "Ký hiệu $\\sqrt{\\ }$ chỉ căn bậc hai không âm."), P("괄호 안을 먼저 계산해 보세요.", "Hãy tính phần trong ngoặc trước.")], expl: P(`$\\sqrt{(-${a})^2}=\\sqrt{${a * a}}=${a}$ 이므로 첫 번째 식이 옳아요.`, `$\\sqrt{(-${a})^2}=\\sqrt{${a * a}}=${a}$ nên đẳng thức đầu tiên đúng.`) });
  const rationalize = (n, role, d, num_, m) => { const [k, mm] = [num_ / m, m]; return numeric({ k: "sqrt", n, role, d, fam: "sqrt-rat", tags: ["multistep"], prompt: P(`${tex(`\\frac{${num_}}{\\sqrt{${m}}}`)} 을 분모를 유리화하여 ${tex("a\\sqrt{b}")} 꼴로 나타낼 때 $a+b$의 값은? (단, $b$는 가장 작은 자연수) ${ONE.ko}`, `Trục căn thức ở mẫu của ${tex(`\\frac{${num_}}{\\sqrt{${m}}}`)} và viết dưới dạng ${tex("a\\sqrt{b}")}; tính $a+b$ (với $b$ là số tự nhiên nhỏ nhất). ${ONE.vi}`), value: k + mm,
    hints: [P(`분모와 분자에 $\\sqrt{${m}}$ 를 곱해요.`, `Nhân cả tử và mẫu với $\\sqrt{${m}}$.`), P("약분해서 $a\\sqrt{b}$ 꼴로 정리해요.", "Rút gọn rồi viết về dạng $a\\sqrt{b}$.")], expl: P(`${tex(`\\frac{${num_}}{\\sqrt{${m}}}=\\frac{${num_}\\sqrt{${m}}}{${m}}=${k}\\sqrt{${m}}`)} 이므로 $a+b=${k}+${m}=${k + m}$.`, `${tex(`\\frac{${num_}}{\\sqrt{${m}}}=\\frac{${num_}\\sqrt{${m}}}{${m}}=${k}\\sqrt{${m}}`)} nên $a+b=${k}+${m}=${k + m}$.`) }); };
  const radicalSum = (n, role, d, a, c, e) => { // sqrt(a) + sqrt(c) - sqrt(e) all multiples of the same radical
    const [ka, ma] = simp(a), [kc, mc_] = simp(c), [ke, me] = simp(e); if (ma !== mc_ || ma !== me) throw new Error("radicalSum: different radicals");
    return numeric({ k: "sqrt", n, role, d, fam: "sqrt-sum", tags: ["multistep", "reasoning"], prompt: P(`${tex(`\\sqrt{${a}}+\\sqrt{${c}}-\\sqrt{${e}} = k\\sqrt{${ma}}`)} 일 때 $k$의 값은? ${ONE.ko}`, `Nếu ${tex(`\\sqrt{${a}}+\\sqrt{${c}}-\\sqrt{${e}} = k\\sqrt{${ma}}`)} thì $k$ bằng bao nhiêu? ${ONE.vi}`), value: ka + kc - ke,
      hints: [P("각 제곱근을 $\\sqrt{" + ma + "}$ 의 배수로 바꿔요.", "Đưa từng căn về dạng bội của $\\sqrt{" + ma + "}$."), P("그다음 계수끼리 더하고 빼요.", "Sau đó cộng trừ các hệ số.")], expl: P(`${tex(`${ka}\\sqrt{${ma}}+${kc}\\sqrt{${ma}}-${ke}\\sqrt{${ma}}=${ka + kc - ke}\\sqrt{${ma}}`)}.`, `${tex(`${ka}\\sqrt{${ma}}+${kc}\\sqrt{${ma}}-${ke}\\sqrt{${ma}}=${ka + kc - ke}\\sqrt{${ma}}`)}.`) }); };
  const simpMc = (n, role, d, v) => { const [k, m] = simp(v); return choice({ k: "sqrt", n, role, d, fam: "sqrt-simp", prompt: P(`${tex(`\\sqrt{${v}}`)} 을 간단히 하면?`, `Rút gọn ${tex(`\\sqrt{${v}}`)}.`), right: tex(`${k}\\sqrt{${m}}`), wrong: [tex(`${k * 2}\\sqrt{${m}}`), tex(`${m}\\sqrt{${k}}`), tex(`${k}\\sqrt{${m * 2}}`)],
    hints: [P("제곱수인 약수를 찾아 근호 밖으로 꺼내요.", "Tìm ước là số chính phương rồi đưa ra ngoài dấu căn."), P(`${v} = ${k * k} × ${m}`, `${v} = ${k * k} × ${m}`)], expl: P(`$\\sqrt{${v}}=\\sqrt{${k * k}\\times ${m}}=${k}\\sqrt{${m}}$.`, `$\\sqrt{${v}}=\\sqrt{${k * k}\\times ${m}}=${k}\\sqrt{${m}}$.`) }); };
  const l1 = [root(1, "core", 1, 7), garden(2, "core", 2, 12), trueRoot(3, "core", 2, 5), rationalize(4, "core", 3, 12, 6), radicalSum(5, "core", 3, 12, 27, 3)];
  root("v1", "variant", 1, 9); trueRoot("v2", "variant", 2, 4); simpMc("v3", "variant", 2, 72); garden("v4", "variant", 2, 15);
  root("d1", "diagnostic", 1, 11); simpMc("d2", "diagnostic", 2, 50); rationalize("d3", "diagnostic", 4, 10, 5);

  /* ------------------------------ 2. expansion and factoring ------------------------------ */
  const expand = (n, role, d, a, c) => numeric({ k: "fact", n, role, d, fam: "fact-expand", prompt: P(`${tex(`(x+${a})(x+${c}) = x^2+px+q`)} 일 때 $p+q$의 값은? ${ONE.ko}`, `Nếu ${tex(`(x+${a})(x+${c}) = x^2+px+q`)} thì $p+q$ bằng bao nhiêu? ${ONE.vi}`), value: a + c + a * c,
    hints: [P("분배법칙으로 네 항을 모두 곱해요.", "Dùng tính chất phân phối để nhân đủ bốn hạng tử."), P("$x$의 계수는 $a+c$, 상수항은 $ac$ 예요.", "Hệ số của $x$ là $a+c$, hằng số là $ac$.")], expl: P(`${tex(`x^2+${a + c}x+${a * c}`)} 이므로 $p+q=${a + c}+${a * c}=${a + c + a * c}$.`, `Kết quả ${tex(`x^2+${a + c}x+${a * c}`)} nên $p+q=${a + c}+${a * c}=${a + c + a * c}$.`) });
  const factor = (n, role, d, a, c) => { const rt = (p, q) => tex(`(x${p >= 0 ? "+" : ""}${p})(x${q >= 0 ? "+" : ""}${q})`);
    return choice({ k: "fact", n, role, d, fam: "fact-factor", prompt: P(`${tex(`x^2${a + c >= 0 ? "+" : ""}${a + c}x${a * c >= 0 ? "+" : ""}${a * c}`)} 을 인수분해하면?`, `Phân tích ${tex(`x^2${a + c >= 0 ? "+" : ""}${a + c}x${a * c >= 0 ? "+" : ""}${a * c}`)} thành nhân tử.`), right: rt(a, c), wrong: [rt(-a, -c), rt(a, -c), rt(-a, c)].filter((s) => s !== rt(a, c)),
      hints: [P("곱이 상수항, 합이 $x$의 계수인 두 수를 찾아요.", "Tìm hai số có tích bằng hằng số và tổng bằng hệ số của $x$."), P(`곱이 ${a * c}, 합이 ${a + c}인 두 수`, `Hai số có tích ${a * c} và tổng ${a + c}.`)], expl: P(`합이 ${a + c}, 곱이 ${a * c}인 두 수는 ${a}, ${c} 이므로 ${rt(a, c)}.`, `Hai số có tổng ${a + c}, tích ${a * c} là ${a} và ${c} nên ${rt(a, c)}.`) }); };
  const wrongId = (n, role, d, a) => { const items = [`(x+${a})^2=x^2+${2 * a}x+${a * a}`, `(x-${a + 1})^2=x^2-${2 * (a + 1)}x+${(a + 1) ** 2}`, `(x+${a + 2})(x-${a + 2})=x^2-${(a + 2) ** 2}`];
    return choice({ k: "fact", n, role, d, fam: "fact-wrong", tags: ["reasoning"], prompt: WHICH_WRONG, right: tex(`(x+${a})^2=x^2+${a * a}`), wrong: items.map((s) => tex(s)),
      hints: [P("곱셈 공식에서 가운데 항($2ab$)이 빠지지 않았는지 확인해요.", "Kiểm tra xem hạng tử giữa ($2ab$) có bị bỏ sót không."), P("$(a+b)^2=a^2+2ab+b^2$", "$(a+b)^2=a^2+2ab+b^2$")], expl: P(`$(x+${a})^2=x^2+${2 * a}x+${a * a}$ 이어야 해요. 가운데 항 ${2 * a}x 가 빠졌어요.`, `Phải là $(x+${a})^2=x^2+${2 * a}x+${a * a}$. Bài làm đã bỏ mất hạng tử giữa ${2 * a}x.`) }); };
  const rectArea = (n, role, d, a, x0) => numeric({ k: "fact", n, role, d, fam: "fact-area", tags: ["context", "multistep"], prompt: P(`가로가 $(x+${a})$ cm, 세로가 $(x-${a})$ cm인 직사각형이 있습니다. $x=${x0}$ 일 때 넓이는 몇 cm²일까요? ${ONE.ko}`, `Hình chữ nhật có chiều dài $(x+${a})$ cm và chiều rộng $(x-${a})$ cm. Khi $x=${x0}$ thì diện tích bằng bao nhiêu cm²? ${ONE.vi}`), value: x0 * x0 - a * a,
    hints: [P("합과 차의 곱셈 공식 $(a+b)(a-b)=a^2-b^2$ 을 써 보세요.", "Dùng hằng đẳng thức $(a+b)(a-b)=a^2-b^2$."), P(`넓이 = $x^2-${a * a}$ 에 $x=${x0}$ 대입`, `Diện tích = $x^2-${a * a}$, thay $x=${x0}$.`)], expl: P(`넓이는 $x^2-${a * a}$ 이므로 $${x0}^2-${a * a}=${x0 * x0 - a * a}$ (cm²).`, `Diện tích là $x^2-${a * a}$ nên $${x0}^2-${a * a}=${x0 * x0 - a * a}$ (cm²).`) });
  const perfect = (n, role, d, r) => numeric({ k: "fact", n, role, d, fam: "fact-square", tags: ["multistep", "reasoning"], prompt: P(`${tex(`x^2+kx+${r * r}`)} 이 완전제곱식이 되도록 하는 양수 $k$의 값은? ${ONE.ko}`, `Tìm số dương $k$ để ${tex(`x^2+kx+${r * r}`)} là bình phương của một nhị thức. ${ONE.vi}`), value: 2 * r,
    hints: [P("$(x+a)^2=x^2+2ax+a^2$ 꼴이어야 해요.", "Biểu thức phải có dạng $(x+a)^2=x^2+2ax+a^2$."), P(`$a^2=${r * r}$ 에서 $a$를 구해요.`, `Từ $a^2=${r * r}$ tìm $a$.`)], expl: P(`$a^2=${r * r}$ 이므로 $a=${r}$, $k=2a=${2 * r}$.`, `Vì $a^2=${r * r}$ nên $a=${r}$, $k=2a=${2 * r}$.`) });
  const l2 = [expand(1, "core", 1, 2, 3), factor(2, "core", 2, 2, 5), wrongId(3, "core", 2, 3), rectArea(4, "core", 3, 5, 12), perfect(5, "core", 3, 6)];
  expand("v1", "variant", 1, 4, 1); factor("v2", "variant", 2, -3, 7); wrongId("v3", "variant", 2, 4); perfect("v4", "variant", 3, 4);
  expand("d1", "diagnostic", 2, 3, 4); factor("d2", "diagnostic", 3, -2, -6);

  /* ------------------------------ 3. quadratic equations ------------------------------ */
  const bigger = (n, role, d, r1, r2) => numeric({ k: "quad", n, role, d, fam: "quad-roots", prompt: P(`이차방정식 ${tex(`${poly([1, -(r1 + r2), r1 * r2])}=0`)} 의 두 근 중 큰 근은? ${ONE.ko}`, `Phương trình ${tex(`${poly([1, -(r1 + r2), r1 * r2])}=0`)} có hai nghiệm; nghiệm lớn hơn là bao nhiêu? ${ONE.vi}`), value: Math.max(r1, r2),
    hints: [P("좌변을 인수분해해요.", "Phân tích vế trái thành nhân tử."), P("$AB=0$ 이면 $A=0$ 또는 $B=0$ 이에요.", "Nếu $AB=0$ thì $A=0$ hoặc $B=0$.")], expl: P(`$(x${-r1 >= 0 ? "+" : ""}${-r1})(x${-r2 >= 0 ? "+" : ""}${-r2})=0$ 이므로 $x=${r1}$ 또는 $x=${r2}$. 큰 근은 ${Math.max(r1, r2)}.`, `$(x${-r1 >= 0 ? "+" : ""}${-r1})(x${-r2 >= 0 ? "+" : ""}${-r2})=0$ nên $x=${r1}$ hoặc $x=${r2}$. Nghiệm lớn hơn là ${Math.max(r1, r2)}.`) });
  const disc = (n, role, d, bb, cc) => { const D = bb * bb - 4 * cc; const names = [T("서로 다른 두 실근", "hai nghiệm thực phân biệt"), T("중근 (한 개의 실근)", "nghiệm kép (một nghiệm thực)"), T("실근이 없다", "vô nghiệm thực"), T("무수히 많은 실근", "vô số nghiệm thực")]; const at = D > 0 ? 0 : D === 0 ? 1 : 2;
    return choice({ k: "quad", n, role, d, fam: "quad-disc", tags: ["reasoning"], prompt: P(`이차방정식 ${tex(`x^2${bb >= 0 ? "+" : ""}${bb}x${cc >= 0 ? "+" : ""}${cc}=0`)} 의 근에 대한 설명으로 옳은 것은?`, `Nhận xét nào đúng về nghiệm của phương trình ${tex(`x^2${bb >= 0 ? "+" : ""}${bb}x${cc >= 0 ? "+" : ""}${cc}=0`)}?`), right: names[at], wrong: names.filter((_, i) => i !== at),
      hints: [P("판별식 $D=b^2-4ac$ 의 부호를 확인해요.", "Xét dấu của biệt thức $D=b^2-4ac$."), P(`$D=${bb}^2-4\\times ${cc}=${D}$`, `$D=${bb}^2-4\\times ${cc}=${D}$`)], expl: P(`$D=${D}$ 이므로 ${names[at].ko}.`, `$D=${D}$ nên phương trình có ${names[at].vi}.`) }); };
  const rectEq = (n, role, d, w, dif) => numeric({ k: "quad", n, role, d, fam: "quad-rect", tags: ["context", "multistep"], prompt: P(`가로가 세로보다 ${dif} cm 더 긴 직사각형의 넓이가 ${w * (w + dif)} cm² 입니다. 세로의 길이는 몇 cm일까요? ${ONE.ko}`, `Hình chữ nhật có chiều dài hơn chiều rộng ${dif} cm và diện tích ${w * (w + dif)} cm². Chiều rộng là bao nhiêu cm? ${ONE.vi}`), value: w,
    hints: [P(`세로를 $x$ cm로 놓으면 가로는 $(x+${dif})$ cm예요.`, `Gọi chiều rộng là $x$ cm thì chiều dài là $(x+${dif})$ cm.`), P(`$x(x+${dif})=${w * (w + dif)}$ 을 풀어요. 길이는 양수예요.`, `Giải $x(x+${dif})=${w * (w + dif)}$; độ dài phải dương.`)], expl: P(`$x^2+${dif}x-${w * (w + dif)}=0$, $(x-${w})(x+${w + dif})=0$ 이고 $x>0$ 이므로 $x=${w}$.`, `$x^2+${dif}x-${w * (w + dif)}=0$, $(x-${w})(x+${w + dif})=0$ và $x>0$ nên $x=${w}$.`) });
  const vieta = (n, role, d, r1, r2) => numeric({ k: "quad", n, role, d, fam: "quad-vieta", tags: ["multistep", "reasoning"], prompt: P(`이차방정식 ${tex(`x^2-${r1 + r2}x+k=0`)} 의 두 근의 차가 ${r2 - r1}일 때, 상수 $k$의 값은? ${ONE.ko}`, `Phương trình ${tex(`x^2-${r1 + r2}x+k=0`)} có hiệu hai nghiệm bằng ${r2 - r1}. Tìm hằng số $k$. ${ONE.vi}`), value: r1 * r2,
    hints: [P(`두 근을 $\\alpha,\\ \\beta$ 라 하면 $\\alpha+\\beta=${r1 + r2}$, $\\alpha-\\beta=${r2 - r1}$ 이에요.`, `Gọi hai nghiệm là $\\alpha,\\ \\beta$ thì $\\alpha+\\beta=${r1 + r2}$ và $\\alpha-\\beta=${r2 - r1}$.`), P("두 근을 구한 뒤 근과 계수의 관계 $\\alpha\\beta=k$ 를 써요.", "Tìm hai nghiệm rồi dùng hệ thức Vi-ét $\\alpha\\beta=k$.")], expl: P(`두 근은 ${r1}, ${r2} 이므로 $k=${r1}\\times ${r2}=${r1 * r2}$.`, `Hai nghiệm là ${r1} và ${r2} nên $k=${r1}\\times ${r2}=${r1 * r2}$.`) });
  const squareRoot = (n, role, d, r) => numeric({ k: "quad", n, role, d, fam: "quad-sq", prompt: P(`이차방정식 ${tex(`(x-${r})^2=${(r + 2) ** 2 - 0}`)} 의 해 중 큰 값은? ${ONE.ko}`, `Phương trình ${tex(`(x-${r})^2=${(r + 2) ** 2}`)} có hai nghiệm; nghiệm lớn hơn là bao nhiêu? ${ONE.vi}`), value: r + (r + 2),
    hints: [P("양변에 제곱근을 씌우면 $x-a=\\pm\\sqrt{k}$ 예요.", "Lấy căn hai vế: $x-a=\\pm\\sqrt{k}$."), P("큰 쪽은 +를 선택해요.", "Nghiệm lớn hơn ứng với dấu +.")], expl: P(`$x-${r}=\\pm ${r + 2}$ 이므로 $x=${r + (r + 2)}$ 또는 $x=${r - (r + 2)}$. 큰 근은 ${r + (r + 2)}.`, `$x-${r}=\\pm ${r + 2}$ nên $x=${r + (r + 2)}$ hoặc $x=${r - (r + 2)}$. Nghiệm lớn hơn là ${r + (r + 2)}.`) });
  const l3 = [bigger(1, "core", 1, 3, -2), bigger(2, "core", 2, 2, 5), disc(3, "core", 2, -6, 9), rectEq(4, "core", 3, 6, 3), vieta(5, "core", 3, 2, 5)];
  bigger("v1", "variant", 1, 1, 4); disc("v2", "variant", 2, 2, 5); rectEq("v3", "variant", 3, 5, 2); squareRoot("v4", "variant", 2, 3);
  bigger("d1", "diagnostic", 2, -3, 4); disc("d2", "diagnostic", 3, 5, 4); vieta("d3", "diagnostic", 4, 1, 6);

  /* ------------------------------ 4. quadratic functions ------------------------------ */
  const vertexForm = (n, role, d, a, p, q) => numeric({ k: "qfunc", n, role, d, fam: "qfunc-vertex", prompt: P(`이차함수 ${tex(`y=${a === 1 ? "" : a === -1 ? "-" : a}(x${-p >= 0 ? "+" : ""}${-p})^2${q >= 0 ? "+" : ""}${q}`)} 의 꼭짓점의 좌표를 $(p,\\ q)$ 라 할 때 $p+q$의 값은? ${ONE.ko}`, `Đỉnh của parabol ${tex(`y=${a === 1 ? "" : a === -1 ? "-" : a}(x${-p >= 0 ? "+" : ""}${-p})^2${q >= 0 ? "+" : ""}${q}`)} là $(p,\\ q)$. Tính $p+q$. ${ONE.vi}`), value: p + q,
    hints: [P("$y=a(x-p)^2+q$ 의 꼭짓점은 $(p,\\ q)$ 예요.", "Đỉnh của $y=a(x-p)^2+q$ là $(p,\\ q)$."), P("괄호 안 부호에 주의해요: $x-3$ 이면 $p=3$.", "Chú ý dấu trong ngoặc: $x-3$ thì $p=3$.")], expl: P(`꼭짓점은 $(${p},\\ ${q})$ 이므로 $p+q=${p + q}$.`, `Đỉnh là $(${p},\\ ${q})$ nên $p+q=${p + q}$.`) });
  const completeSq = (n, role, d, bb, cc) => { const p = -bb / 2, q = cc - (bb * bb) / 4; return numeric({ k: "qfunc", n, role, d, fam: "qfunc-complete", tags: ["multistep"], prompt: P(`이차함수 ${tex(`y=x^2${bb >= 0 ? "+" : ""}${bb}x${cc >= 0 ? "+" : ""}${cc}`)} 의 꼭짓점의 $y$좌표는? ${ONE.ko}`, `Tung độ đỉnh của parabol ${tex(`y=x^2${bb >= 0 ? "+" : ""}${bb}x${cc >= 0 ? "+" : ""}${cc}`)} là bao nhiêu? ${ONE.vi}`), value: q,
    hints: [P("완전제곱식 $y=(x-p)^2+q$ 꼴로 고쳐요.", "Đưa về dạng bình phương hoàn chỉnh $y=(x-p)^2+q$."), P(`$x$의 계수 ${bb}의 절반 ${bb / 2}을 이용해요.`, `Dùng một nửa hệ số ${bb} của $x$, tức ${bb / 2}.`)], expl: P(`$y=(x${-p >= 0 ? "+" : ""}${-p})^2${q >= 0 ? "+" : ""}${q}$ 이므로 꼭짓점의 $y$좌표는 ${q}.`, `$y=(x${-p >= 0 ? "+" : ""}${-p})^2${q >= 0 ? "+" : ""}${q}$ nên tung độ đỉnh là ${q}.`) }); };
  const maxMin = (n, role, d, a, p, q) => { const maxim = a < 0; const stmt = (ok, kind, val, xp) => T(`$x=${xp}$ 일 때 ${kind === "max" ? "최댓값" : "최솟값"} ${val}`, `Khi $x=${xp}$ thì có ${kind === "max" ? "giá trị lớn nhất" : "giá trị nhỏ nhất"} ${val}`);
    return choice({ k: "qfunc", n, role, d, fam: "qfunc-ext", tags: ["reasoning"], prompt: P(`이차함수 ${tex(`y=${a}(x-${p})^2+${q}`)} 에 대한 설명으로 옳은 것은?`, `Nhận xét nào đúng về hàm số ${tex(`y=${a}(x-${p})^2+${q}`)}?`), right: stmt(1, maxim ? "max" : "min", q, p), wrong: [stmt(0, maxim ? "min" : "max", q, p), stmt(0, maxim ? "max" : "min", q, -p), stmt(0, maxim ? "min" : "max", p, q)],
      hints: [P("$a$의 부호가 그래프의 볼록한 방향을 정해요.", "Dấu của $a$ quyết định hướng bề lõm của parabol."), P("$a<0$ 이면 꼭짓점에서 최댓값, $a>0$ 이면 최솟값이에요.", "Nếu $a<0$ thì đỉnh cho giá trị lớn nhất, nếu $a>0$ thì cho giá trị nhỏ nhất.")], expl: P(`$a=${a}${maxim ? "<" : ">"}0$ 이므로 ${maxim ? "위" : "아래"}로 볼록하고, 꼭짓점 $(${p},\\ ${q})$ 에서 ${maxim ? "최댓값" : "최솟값"} ${q}.`, `Vì $a=${a}${maxim ? "<" : ">"}0$ nên parabol quay ${maxim ? "xuống" : "lên"} và đạt ${maxim ? "giá trị lớn nhất" : "giá trị nhỏ nhất"} ${q} tại đỉnh $(${p},\\ ${q})$.`) }); };
  const ball = (n, role, d, v0, g2) => { const t = v0 / (2 * g2); const hmax = v0 * t - g2 * t * t; return numeric({ k: "qfunc", n, role, d, fam: "qfunc-ball", tags: ["context", "multistep"], prompt: P(`공을 던진 지 $t$초 후의 높이가 $h=-${g2}t^2+${v0}t$ (m)일 때, 공이 올라가는 최고 높이는 몇 m일까요? ${ONE.ko}`, `Sau $t$ giây ném, độ cao của quả bóng là $h=-${g2}t^2+${v0}t$ (m). Độ cao lớn nhất của quả bóng là bao nhiêu mét? ${ONE.vi}`), value: hmax,
    hints: [P("꼭짓점의 $t$좌표는 $-\\frac{b}{2a}$ 예요.", "Hoành độ đỉnh là $-\\frac{b}{2a}$."), P("그 $t$를 식에 대입해 높이를 구해요.", "Thay giá trị $t$ đó vào công thức để tìm độ cao.")], expl: P(`$t=${t}$ 일 때 $h=-${g2}\\times ${t}^2+${v0}\\times ${t}=${hmax}$ (m).`, `Khi $t=${t}$ thì $h=-${g2}\\times ${t}^2+${v0}\\times ${t}=${hmax}$ (m).`) }); };
  const fromRoots = (n, role, d, r1, r2, y0) => { const a = y0 / (r1 * r2); const xm = (r1 + r2) / 2; const ym = a * (xm - r1) * (xm - r2);
    return numeric({ k: "qfunc", n, role, d, fam: "qfunc-roots", tags: ["multistep", "reasoning"], prompt: P(`이차함수의 그래프가 $x$축과 $(${r1},\\ 0)$, $(${r2},\\ 0)$ 에서 만나고 $y$축과 $(0,\\ ${y0})$ 에서 만날 때, 꼭짓점의 $y$좌표는? ${ONE.ko}`, `Parabol cắt trục hoành tại $(${r1},\\ 0)$ và $(${r2},\\ 0)$, cắt trục tung tại $(0,\\ ${y0})$. Tung độ đỉnh là bao nhiêu? ${ONE.vi}`), value: ym,
      hints: [P(`$y=a(x-${r1})(x-${r2})$ 로 놓고 $(0,\\ ${y0})$ 를 대입해 $a$를 구해요.`, `Đặt $y=a(x-${r1})(x-${r2})$ rồi thay $(0,\\ ${y0})$ để tìm $a$.`), P("꼭짓점의 $x$좌표는 두 근의 중점이에요.", "Hoành độ đỉnh là trung điểm của hai nghiệm.")], expl: P(`$a=${a}$, 꼭짓점의 $x$좌표 ${xm}에서 $y=${ym}$.`, `Tìm được $a=${a}$; tại hoành độ đỉnh ${xm} ta có $y=${ym}$.`) }); };
  const l4 = [vertexForm(1, "core", 1, 2, 3, 5), completeSq(2, "core", 2, -6, 8), maxMin(3, "core", 2, -2, 1, 3), ball(4, "core", 2, 20, 5), fromRoots(5, "core", 3, 1, 3, 6)];
  vertexForm("v1", "variant", 1, 1, -2, 4); maxMin("v2", "variant", 2, 3, 2, 1); ball("v3", "variant", 2, 30, 5); completeSq("v4", "variant", 2, 4, 7);
  vertexForm("d1", "diagnostic", 2, -1, 4, -3); completeSq("d2", "diagnostic", 3, -8, 10); fromRoots("d3", "diagnostic", 4, 2, 4, 16);

  /* ------------------------------ 5. trigonometric ratios ------------------------------ */
  const sinRatio = (n, role, d, a, c) => { const h = Math.round(Math.sqrt(a * a + c * c)); if (h * h !== a * a + c * c) throw new Error("not a Pythagorean triple"); const f = (x, y) => tex(fracTex(x, y));
    return choice({ k: "trig", n, role, d, fam: "trig-ratio", prompt: P(`직각삼각형 ABC에서 $\\angle C=90^\\circ$, $\\overline{AC}=${c}$, $\\overline{BC}=${a}$, $\\overline{AB}=${h}$ 일 때 $\\sin A$의 값은?`, `Tam giác ABC có $\angle C=90^\circ$, $AC=${c}$, $BC=${a}$, $AB=${h}$. Giá trị của $\\sin A$ là?`), right: f(a, h), wrong: [f(c, h), f(a, c), f(h, a)].filter((s) => s !== f(a, h)),
      hints: [P("$\\sin A = \\frac{\\text{높이} }{\\text{빗변} }$. 각 A의 대변을 찾아요.", "$\\sin A=\\frac{\\text{cạnh đối} }{\\text{cạnh huyền} }$. Hãy tìm cạnh đối của góc A."), P(`각 A의 대변은 $\\overline{BC}=${a}$ 예요.`, `Cạnh đối của góc A là $BC=${a}$.`)], expl: P(`$\\sin A=\\frac{${a}}{${h}}$${a === h ? "" : ""}.`, `$\\sin A=\\frac{${a}}{${h}}$.`) }); };
  const opp = (n, role, d, hyp) => numeric({ k: "trig", n, role, d, fam: "trig-solve", prompt: P(`직각삼각형에서 빗변의 길이가 ${hyp}이고 한 예각의 크기가 $30^\\circ$ 일 때, 이 각의 대변의 길이는? ${ONE.ko}`, `Trong tam giác vuông có cạnh huyền ${hyp} và một góc nhọn $30^\\circ$, cạnh đối của góc đó dài bao nhiêu? ${ONE.vi}`), value: hyp / 2,
    hints: [P("$\\sin 30^\\circ=\\frac12$ 을 이용해요.", "Dùng $\\sin 30^\\circ=\\frac12$."), P("대변 = 빗변 × $\\sin 30^\\circ$", "Cạnh đối = cạnh huyền × $\\sin 30^\\circ$.")], expl: P(`대변 $=${hyp}\\times \\sin 30^\\circ=${hyp}\\times \\frac12=${hyp / 2}$.`, `Cạnh đối $=${hyp}\\times \\sin 30^\\circ=${hyp}\\times \\frac12=${hyp / 2}$.`) });
  const compare = (n, role, d, which) => { const stmts = [tex("\\sin 30^\\circ=\\cos 60^\\circ"), tex("\\tan 45^\\circ=1"), tex("\\sin 90^\\circ=1"), tex("\\cos 0^\\circ=1")]; const bad = [tex("\\sin 60^\\circ=\\frac12"), tex("\\cos 45^\\circ=1"), tex("\\tan 30^\\circ=\\sqrt3"), tex("\\sin 45^\\circ=\\cos 30^\\circ")];
    return choice({ k: "trig", n, role, d, fam: "trig-true", tags: ["reasoning"], prompt: P("다음 중 옳은 것은?", "Đẳng thức nào sau đây đúng?"), right: stmts[which], wrong: bad.slice(which, which + 3).concat(bad).slice(0, 3),
      hints: [P("특수각(30°, 45°, 60°)의 삼각비 값을 떠올려 보세요.", "Hãy nhớ giá trị lượng giác của các góc đặc biệt (30°, 45°, 60°)."), P("$\\sin x=\\cos(90^\\circ-x)$", "$\\sin x=\\cos(90^\\circ-x)$")], expl: P(`옳은 것은 ${stmts[which]} 이에요.`, `Đẳng thức đúng là ${stmts[which]}.`) }); };
  const ladder = (n, role, d, len) => numeric({ k: "trig", n, role, d, fam: "trig-ladder", tags: ["context", "multistep"], prompt: P(`길이 ${len} m의 사다리를 벽에 기대어 지면과 $30^\\circ$ 를 이루게 했습니다. 사다리가 벽에 닿은 곳의 높이는 몇 m일까요? ${ONE.ko}`, `Một chiếc thang dài ${len} m dựa vào tường, tạo với mặt đất góc $30^\\circ$. Đầu thang chạm tường ở độ cao bao nhiêu mét? ${ONE.vi}`), value: len / 2,
    hints: [P("사다리는 빗변, 벽의 높이는 $30^\\circ$ 의 대변이에요.", "Thang là cạnh huyền, độ cao trên tường là cạnh đối của góc $30^\\circ$."), P("높이 = 길이 × $\\sin 30^\\circ$", "Độ cao = chiều dài × $\\sin 30^\\circ$.")], expl: P(`높이 $=${len}\\times \\frac12=${len / 2}$ (m).`, `Độ cao $=${len}\\times \\frac12=${len / 2}$ (m).`) });
  const sinCos = (n, role, d, o, a) => { const h = Math.round(Math.sqrt(o * o + a * a)); return numeric({ k: "trig", n, role, d, fam: "trig-product", tags: ["multistep", "reasoning"], prompt: P(`예각 $A$에 대하여 $\\tan A=\\frac{${o}}{${a}}$ 일 때 $\\sin A\\times \\cos A$의 값은? ${FRAC.ko}`, `Với góc nhọn $A$ có $\\tan A=\\frac{${o}}{${a}}$, giá trị của $\\sin A\\times \\cos A$ là bao nhiêu? ${FRAC.vi}`), value: round4((o / h) * (a / h)), tol: 0.001,
    hints: [P(`대변 ${o}, 밑변 ${a}인 직각삼각형을 그려 빗변을 구해요.`, `Vẽ tam giác vuông có cạnh đối ${o}, cạnh kề ${a} rồi tìm cạnh huyền.`), P(`빗변은 ${h} 이므로 $\\sin A=\\frac{${o}}{${h}}$, $\\cos A=\\frac{${a}}{${h}}$`, `Cạnh huyền là ${h} nên $\\sin A=\\frac{${o}}{${h}}$, $\\cos A=\\frac{${a}}{${h}}$.`)], expl: P(`$\\frac{${o}}{${h}}\\times\\frac{${a}}{${h}}=\\frac{${o * a}}{${h * h}}$ (≈ ${round4((o * a) / (h * h))}).`, `$\\frac{${o}}{${h}}\\times\\frac{${a}}{${h}}=\\frac{${o * a}}{${h * h}}$ (≈ ${round4((o * a) / (h * h))}).`) }); };
  const l5 = [sinRatio(1, "core", 1, 4, 3), opp(2, "core", 2, 10), compare(3, "core", 2, 0), ladder(4, "core", 2, 12), sinCos(5, "core", 3, 3, 4)];
  sinRatio("v1", "variant", 1, 5, 12); opp("v2", "variant", 2, 16); compare("v3", "variant", 2, 1); ladder("v4", "variant", 2, 8);
  sinRatio("d1", "diagnostic", 2, 8, 6); compare("d2", "diagnostic", 3, 3); sinCos("d3", "diagnostic", 4, 5, 12);

  K.course({
    slug: "roots-quadratics-trig", title: T("중3 수학: 제곱근·이차식·삼각비", "Toán lớp 9: Căn thức, bậc hai và lượng giác"),
    world: { name: T("이차함수 언덕", "Đồi hàm bậc hai"), emoji: "⛰️", tagline: T("제곱근에서 출발해 포물선 꼭대기와 삼각형의 비밀까지 올라가요.", "Từ căn bậc hai lên đỉnh parabol và bí mật của tam giác vuông.") }, unitTitle: T("중3 수학", "Toán lớp 9"),
    lessons: [
      K.lesson(1, "sqrt", T("제곱근과 실수", "Căn bậc hai và số thực"), T("$\\sqrt{a}$ 는 제곱하여 $a$가 되는 음이 아닌 수예요. 근호 안의 제곱수는 밖으로 꺼내고, 분모의 근호는 유리화해요.", "$\\sqrt{a}$ là số không âm có bình phương bằng $a$. Đưa thừa số chính phương ra ngoài căn và trục căn thức ở mẫu."), T("$\\sqrt{72}=6\\sqrt{2}$", "$\\sqrt{72}=6\\sqrt{2}$"), l1),
      K.lesson(2, "fact", T("곱셈 공식과 인수분해", "Hằng đẳng thức và phân tích nhân tử"), T("$(a+b)^2=a^2+2ab+b^2$, $(a+b)(a-b)=a^2-b^2$. 인수분해는 곱셈 공식을 거꾸로 쓰는 일이에요.", "$(a+b)^2=a^2+2ab+b^2$, $(a+b)(a-b)=a^2-b^2$. Phân tích nhân tử là dùng ngược các hằng đẳng thức."), T("$x^2+5x+6=(x+2)(x+3)$", "$x^2+5x+6=(x+2)(x+3)$"), l2),
      K.lesson(3, "quad", T("이차방정식", "Phương trình bậc hai"), T("인수분해로 $AB=0$ 꼴을 만들어 풀어요. 판별식 $D=b^2-4ac$ 로 근의 개수를 알 수 있고, 근과 계수의 관계도 쓸 수 있어요.", "Phân tích thành $AB=0$ để giải. Biệt thức $D=b^2-4ac$ cho biết số nghiệm và có thể dùng hệ thức Vi-ét."), T("$x^2-5x+6=0 \\Rightarrow x=2$ 또는 $3$", "$x^2-5x+6=0 \\Rightarrow x=2$ hoặc $3$"), l3),
      K.lesson(4, "qfunc", T("이차함수와 그래프", "Hàm số bậc hai và đồ thị"), T("$y=a(x-p)^2+q$ 의 꼭짓점은 $(p,\\ q)$, $a$의 부호가 볼록한 방향을 정해요. 완전제곱식으로 바꾸면 꼭짓점을 찾을 수 있어요.", "Đỉnh của $y=a(x-p)^2+q$ là $(p,\\ q)$; dấu của $a$ quyết định hướng bề lõm. Đưa về bình phương hoàn chỉnh để tìm đỉnh."), T("$y=x^2-4x+3=(x-2)^2-1$", "$y=x^2-4x+3=(x-2)^2-1$"), l4),
      K.lesson(5, "trig", T("삼각비", "Tỉ số lượng giác"), T("직각삼각형에서 $\\sin A=\\frac{\\text{대변} }{\\text{빗변} }$, $\\cos A=\\frac{\\text{밑변} }{\\text{빗변} }$, $\\tan A=\\frac{\\text{대변} }{\\text{밑변} }$ 예요.", "Trong tam giác vuông: $\\sin A=\\frac{\\text{đối} }{\\text{huyền} }$, $\\cos A=\\frac{\\text{kề} }{\\text{huyền} }$, $\\tan A=\\frac{\\text{đối} }{\\text{kề} }$."), T("$\\sin 30^\\circ=\\dfrac12,\\ \\cos 60^\\circ=\\dfrac12$", "$\\sin 30^\\circ=\\dfrac12,\\ \\cos 60^\\circ=\\dfrac12$"), l5),
    ],
  });
}
const round4 = (x) => Number(x.toFixed(4));
