import { T } from "./lib.mjs";
import { H, W, makeEnglish } from "./english-helpers.mjs";

const lessonOf = (grade) => (n, sk, S, title, concept, example, core, challenge) => ({ id: `en-${grade}-l${n}`, title, concept, example, skills: [S[sk]], core, challenge });
const first = (w) => T(`첫 단어: ${w}`, `Từ đầu tiên: ${w}`);

function kit(b, grade, S) {
  const E = makeEnglish(b, grade, S);
  /** Fill-in choice with an optional meaning cue in parentheses. */
  const choose = (sk, n, role, d, fam, sentence, items, correct, hints, expl, cue) => E.mc({
    sk, n, role, d, fam, items, correct, hints, expl, tags: ["grammar"],
    prompt: cue ? T(`빈칸에 알맞은 말을 고르세요: ${sentence} (${cue.ko})`, `Chọn từ thích hợp cho chỗ trống: ${sentence} (${cue.vi})`) : T(`빈칸에 알맞은 말을 고르세요: ${sentence}`, `Chọn từ thích hợp cho chỗ trống: ${sentence}`),
  });
  const ord = (sk, n, role, d, fam, meaning, words, hints, expl) => E.order({ sk, n, role, d, fam, meaning, words, tags: ["grammar"], hints, expl });
  /** A question asked in English ("Which word means ...?"): the instruction around it is localised, the question and the options stay English. */
  const ask = (sk, n, role, d, fam, question, items, hints, expl) => E.mc({
    sk, n, role, d, fam, items, correct: 0, hints, expl, tags: ["vocab"],
    prompt: T(`다음 질문에 알맞은 답을 고르세요: ${question}`, `Chọn đáp án đúng cho câu hỏi sau: ${question}`),
  });
  const meaning = (sk, n, role, d, fam, w, others) => E.mc({
    sk, n, role, d, fam, prompt: T(`'${w.en}'의 뜻은?`, `'${w.en}' nghĩa là gì?`), items: [T(w.ko, w.vi), ...others.map((o) => T(o.ko, o.vi))], correct: 0, audio: w.en, tags: ["vocab"],
    hints: [H.sound, H.first(w.en)], expl: T(`${w.en} = ${w.ko}`, `${w.en} = ${w.vi}`),
  });
  const rewrite = (sk, n, role, d, fam, sentence, instruction, accepted, hints, expl) => E.write({
    sk, n, role, d, fam, type: "short_answer", accepted, tags: ["grammar"], hints, expl,
    prompt: T(`${instruction.ko} ${sentence}`, `${instruction.vi} ${sentence}`),
  });
  const read = (sk, n, role, d, fam, passage, q, items, correct, hintT, expl) => E.mc({
    sk, n, role, d, fam, items, correct, tags: ["reading"], expl,
    prompt: T(`글을 읽고 답하세요. "${passage}" 질문: ${q}`, `Đọc đoạn văn rồi trả lời. "${passage}" Câu hỏi: ${q}`),
    hints: [T("질문의 낱말을 글에서 먼저 찾아보세요.", "Hãy tìm trước trong đoạn văn các từ có trong câu hỏi."), hintT],
  });
  return { ...E, choose, ord, ask, meaning, rewrite, read };
}

/* ================================ Elementary 4 ================================ */
export function e4(b) {
  const S = { tense: "e.e4.tense", qneg: "e.e4.qneg", adj: "e.e4.adj", prep: "e.e4.prep", read: "e.e4.read" };
  b.skill(S.tense, T("현재·과거·미래", "Hiện tại, quá khứ và tương lai"));
  b.skill(S.qneg, T("의문문과 부정문", "Câu hỏi và câu phủ định"), S.tense);
  b.skill(S.adj, T("모양과 느낌을 나타내는 말", "Từ miêu tả"), S.tense);
  b.skill(S.prep, T("장소를 나타내는 말", "Giới từ chỉ vị trí"), S.adj);
  b.skill(S.read, T("짧은 글 읽기", "Đọc đoạn văn ngắn"), S.qneg);
  const K = kit(b, "e4", S);
  const lesson = lessonOf("e4");

  const t1 = K.choose("tense", 1, "core", 1, "e4-future", "Tomorrow I ____ my grandmother.", ["will visit", "visited", "visits", "visiting"], 0, [T("tomorrow는 '내일'이에요. 앞으로 할 일이에요.", "tomorrow là ngày mai, việc sẽ xảy ra."), T("미래는 will + 동사원형으로 말해요.", "Thì tương lai dùng will + động từ nguyên mẫu.")], T("I will visit my grandmother. = 나는 할머니를 찾아뵐 거예요.", "I will visit my grandmother. = Mình sẽ đi thăm bà."));
  const t2 = K.choose("tense", 2, "core", 1, "e4-past", "Yesterday she ____ a cake.", ["baked", "bake", "bakes", "will bake"], 0, [T("yesterday는 지난 일이에요.", "yesterday là việc đã xảy ra."), T("과거에는 -ed를 붙여요.", "Quá khứ thường thêm -ed.")], T("She baked a cake. = 그녀는 케이크를 구웠어요.", "She baked a cake. = Cô ấy đã nướng một chiếc bánh."));
  const t3 = K.choose("tense", 3, "core", 2, "e4-present", "I ____ TV every night.", ["watch", "watched", "will watch", "watching"], 0, [T("every night은 '매일 밤'이에요. 반복되는 일이에요.", "every night là mỗi tối, việc lặp lại."), T("반복되는 일은 현재형을 써요.", "Việc lặp lại dùng thì hiện tại.")], T("I watch TV every night. = 나는 매일 밤 TV를 봐요.", "I watch TV every night. = Mình xem TV mỗi tối."));
  const t4 = K.write({ sk: "tense", n: 4, d: 2, fam: "e4-future", type: "fill_blank", prompt: T("빈칸에 알맞은 단어를 쓰세요: Next week, we will ____ to Busan. (가다)", "Điền từ thích hợp: Next week, we will ____ to Busan. (đi)"), accepted: ["go"], tags: ["grammar"], hints: [T("will 다음에는 동사원형이 와요.", "Sau will là động từ nguyên mẫu."), H.first("go")], expl: T("We will go to Busan. = 우리는 부산에 갈 거예요.", "We will go to Busan. = Chúng mình sẽ đi Busan.") });
  const t5 = K.ord("tense", 5, "core", 3, "e4-future", T("나는 내일 이모를 방문할 거예요.", "Ngày mai mình sẽ đến thăm dì."), ["I", "will", "visit", "my", "aunt", "tomorrow"], [first("I"), T("will 다음에 동사원형 visit이 와요.", "Sau will là động từ nguyên mẫu visit.")], T("I will visit my aunt tomorrow. = 나는 내일 이모를 방문할 거예요.", "I will visit my aunt tomorrow. = Ngày mai mình sẽ đến thăm dì."));
  K.choose("tense", "v1", "variant", 1, "e4-future", "Tomorrow we ____ to the zoo.", ["will go", "went", "goes", "going"], 0, [T("tomorrow는 미래예요.", "tomorrow là tương lai."), T("will + 동사원형을 써요.", "Dùng will + động từ nguyên mẫu.")], T("We will go to the zoo. = 우리는 동물원에 갈 거예요.", "We will go to the zoo. = Chúng mình sẽ đi sở thú.")); K.choose("tense", "v2", "variant", 2, "e4-past", "Last week he ____ his friend.", ["called", "call", "calls", "will call"], 0, [T("last week는 '지난주'예요.", "last week là tuần trước."), T("-ed를 붙여요.", "Thêm -ed.")], T("He called his friend. = 그는 친구에게 전화했어요.", "He called his friend. = Anh ấy đã gọi cho bạn."));
  K.choose("tense", "d1", "diagnostic", 1, undefined, "Tomorrow it ____ rain.", ["will", "did", "does", "is"], 0, [T("tomorrow는 미래예요.", "tomorrow là tương lai."), T("미래는 will을 써요.", "Tương lai dùng will.")], T("It will rain tomorrow. = 내일 비가 올 거예요.", "It will rain tomorrow. = Ngày mai trời sẽ mưa."));

  const q1 = K.choose("qneg", 1, "core", 1, "e4-question", "____ you like pizza?", ["Do", "Does", "Are", "Is"], 0, [T("주어가 you일 때 일반동사 질문은 Do로 시작해요.", "Khi chủ ngữ là you, câu hỏi với động từ thường bắt đầu bằng Do."), T("like는 일반동사예요.", "like là động từ thường.")], T("Do you like pizza? = 너는 피자를 좋아하니?", "Do you like pizza? = Bạn có thích pizza không?"));
  const q2 = K.choose("qneg", 2, "core", 1, "e4-negative", "She ____ like milk.", ["doesn't", "don't", "isn't", "not"], 0, [T("주어가 She일 때는 doesn't를 써요.", "Chủ ngữ là She thì dùng doesn't."), T("doesn't 다음에는 동사원형이 와요.", "Sau doesn't là động từ nguyên mẫu.")], T("She doesn't like milk. = 그녀는 우유를 좋아하지 않아요.", "She doesn't like milk. = Cô ấy không thích sữa."));
  const q3 = K.ord("qneg", 3, "core", 2, "e4-question", T("너는 축구를 하니?", "Bạn có chơi bóng đá không?"), ["Do", "you", "play", "soccer"], [first("Do"), T("Do you ...? 는 '너는 ...하니?'예요.", "Do you ...? nghĩa là Bạn có ... không?")], T("Do you play soccer? = 너는 축구를 하니?", "Do you play soccer? = Bạn có chơi bóng đá không?"));
  const q4 = K.choose("qneg", 4, "core", 2, "e4-negative", "I ____ have a pet.", ["don't", "doesn't", "isn't", "not"], 0, [T("주어가 I일 때는 don't를 써요.", "Chủ ngữ là I thì dùng don't."), T("don't 다음에는 동사원형이 와요.", "Sau don't là động từ nguyên mẫu.")], T("I don't have a pet. = 나는 반려동물이 없어요.", "I don't have a pet. = Mình không có thú cưng."));
  const q5 = K.ord("qneg", 5, "core", 3, "e4-negative", T("그는 양파를 좋아하지 않아요.", "Anh ấy không thích hành tây."), ["He", "does", "not", "like", "onions"], [first("He"), T("does not 다음에는 동사원형 like가 와요.", "Sau does not là động từ nguyên mẫu like.")], T("He does not like onions. = 그는 양파를 좋아하지 않아요.", "He does not like onions. = Anh ấy không thích hành tây."));
  K.choose("qneg", "v1", "variant", 1, "e4-question", "____ they play tennis?", ["Do", "Does", "Is", "Are"], 0, [T("주어가 they일 때 일반동사 질문은 Do로 시작해요.", "Chủ ngữ là they thì câu hỏi với động từ thường bắt đầu bằng Do."), T("play는 일반동사예요.", "play là động từ thường.")], T("Do they play tennis? = 그들은 테니스를 치니?", "Do they play tennis? = Họ có chơi tennis không?")); K.choose("qneg", "v2", "variant", 2, "e4-negative", "He ____ eat fish.", ["doesn't", "don't", "isn't", "aren't"], 0, [T("주어가 He일 때는 doesn't를 써요.", "Chủ ngữ là He thì dùng doesn't."), T("doesn't 다음에는 동사원형이 와요.", "Sau doesn't là động từ nguyên mẫu.")], T("He doesn't eat fish. = 그는 생선을 먹지 않아요.", "He doesn't eat fish. = Anh ấy không ăn cá."));
  K.choose("qneg", "d1", "diagnostic", 2, undefined, "____ she like dogs?", ["Does", "Do", "Is", "Are"], 0, [T("주어가 she일 때는 Does로 시작해요.", "Chủ ngữ là she thì bắt đầu bằng Does."), T("like는 일반동사예요.", "like là động từ thường.")], T("Does she like dogs? = 그녀는 개를 좋아하니?", "Does she like dogs? = Cô ấy có thích chó không?"));

  const AD = { cold: W("cold", "차가운", "lạnh"), hot: W("hot", "뜨거운", "nóng"), big: W("big", "큰", "to"), small: W("small", "작은", "nhỏ"), happy: W("happy", "행복한", "vui"), sad: W("sad", "슬픈", "buồn") };
  const j1 = K.meaning("adj", 1, "core", 1, "e4-meaning", AD.cold, [AD.hot, AD.big, AD.happy]);
  const j2 = K.mc({ sk: "adj", n: 2, d: 1, fam: "e4-toen", prompt: T("'큰'을 영어로 하면?", "Từ tiếng Anh của 'to, lớn' là gì?"), items: ["big", "small", "hot", "sad"], correct: 0, tags: ["vocab"], hints: [H.letters("big"), H.first("big")], expl: T("큰 = big", "to, lớn = big") });
  const j3 = K.mc({ sk: "adj", n: 3, d: 2, fam: "e4-opposite", prompt: T("'hot'의 반대말은?", "Từ trái nghĩa với 'hot' là gì?"), items: ["cold", "big", "happy", "tall"], correct: 0, tags: ["vocab"], hints: [T("뜨거운 것의 반대는 차가운 것이에요.", "Ngược với nóng là lạnh."), H.sound], expl: T("hot(뜨거운) ↔ cold(차가운)", "hot (nóng) ↔ cold (lạnh)") });
  const j4 = K.write({ sk: "adj", n: 4, d: 2, fam: "e4-toen", type: "fill_blank", prompt: T("빈칸에 알맞은 단어를 쓰세요: The elephant is ____ . (크다)", "Điền từ thích hợp: The elephant is ____ . (to, lớn)"), accepted: ["big"], tags: ["vocab"], hints: [T("코끼리를 떠올려 보세요.", "Hãy nghĩ đến con voi."), H.first("big")], expl: T("The elephant is big. = 코끼리는 커요.", "The elephant is big. = Con voi to lớn.") });
  const j5 = K.choose("adj", 5, "core", 3, "e4-opposite", "The ice cream is ____ .", ["cold", "hot", "sad", "tall"], 0, [T("아이스크림은 차가워요.", "Kem thì lạnh."), T("hot은 '뜨거운'이에요.", "hot nghĩa là nóng.")], T("The ice cream is cold. = 아이스크림은 차가워요.", "The ice cream is cold. = Kem thì lạnh."));
  K.meaning("adj", "v1", "variant", 1, "e4-meaning", AD.hot, [AD.cold, AD.small, AD.sad]); K.mc({ sk: "adj", n: "v2", role: "variant", d: 2, fam: "e4-opposite", prompt: T("'happy'의 반대말은?", "Từ trái nghĩa với 'happy' là gì?"), items: ["sad", "big", "cold", "tall"], correct: 0, tags: ["vocab"], hints: [T("행복한 것의 반대는 슬픈 것이에요.", "Ngược với vui là buồn."), H.sound], expl: T("happy(행복한) ↔ sad(슬픈)", "happy (vui) ↔ sad (buồn)") });
  K.meaning("adj", "d1", "diagnostic", 1, undefined, AD.small, [AD.big, AD.hot, AD.happy]);

  const pp = (n, role, d, fam, sentence, items, correct, cue, hints, expl) => K.choose("prep", n, role, d, fam, sentence, items, correct, hints, expl, cue);
  const pr1 = pp(1, "core", 1, "e4-place", "The book is ____ the desk.", ["on", "in", "under", "behind"], 0, T("책상 위에", "trên bàn"), [T("on은 '~ 위에'예요.", "on nghĩa là ở trên.")].concat(H.sound), T("on the desk = 책상 위에", "on the desk = trên bàn"));
  const pr2 = pp(2, "core", 1, "e4-place", "The ball is ____ the box.", ["in", "on", "under", "behind"], 0, T("상자 안에", "trong hộp"), [T("in은 '~ 안에'예요.", "in nghĩa là ở trong.")].concat(H.sound), T("in the box = 상자 안에", "in the box = trong hộp"));
  const pr3 = pp(3, "core", 2, "e4-place", "The cat is ____ the chair.", ["under", "on", "in", "at"], 0, T("의자 아래에", "dưới ghế"), [T("under는 '~ 아래에'예요.", "under nghĩa là ở dưới.")].concat(H.sound), T("under the chair = 의자 아래에", "under the chair = dưới ghế"));
  const pr4 = pp(4, "core", 2, "e4-place2", "The cat is ____ the door.", ["behind", "on", "in", "at"], 0, T("문 뒤에", "sau cánh cửa"), [T("behind는 '~ 뒤에'예요.", "behind nghĩa là ở phía sau.")].concat(H.sound), T("behind the door = 문 뒤에", "behind the door = sau cánh cửa"));
  const pr5 = K.ord("prep", 5, "core", 3, "e4-place2", T("내 가방은 의자 아래에 있어요.", "Cặp của mình ở dưới ghế."), ["My", "bag", "is", "under", "a", "chair"], [first("My"), T("under는 '아래에'예요.", "under nghĩa là ở dưới.")], T("My bag is under a chair. = 내 가방은 의자 아래에 있어요.", "My bag is under a chair. = Cặp của mình ở dưới ghế."));
  pp("v1", "variant", 1, "e4-place", "The pen is ____ the bag.", ["in", "on", "under", "behind"], 0, T("가방 안에", "trong cặp"), [T("in은 '~ 안에'예요.", "in nghĩa là ở trong.")].concat(H.sound), T("in the bag = 가방 안에", "in the bag = trong cặp")); pp("v2", "variant", 2, "e4-place2", "The dog is ____ the tree.", ["behind", "on", "in", "at"], 0, T("나무 뒤에", "sau cái cây"), [T("behind는 '~ 뒤에'예요.", "behind nghĩa là ở phía sau.")].concat(H.sound), T("behind the tree = 나무 뒤에", "behind the tree = sau cái cây"));
  pp("d1", "diagnostic", 1, undefined, "The cup is ____ the table.", ["on", "in", "under", "behind"], 0, T("탁자 위에", "trên bàn"), [T("on은 '~ 위에'예요.", "on nghĩa là ở trên.")].concat(H.sound), T("on the table = 탁자 위에", "on the table = trên bàn"));
  pp("d2", "diagnostic", 2, undefined, "The shoes are ____ the bed.", ["under", "on", "in", "at"], 0, T("침대 아래에", "dưới giường"), [T("under는 '~ 아래에'예요.", "under nghĩa là ở dưới.")].concat(H.sound), T("under the bed = 침대 아래에", "under the bed = dưới giường"));

  const A = "Today is Sunday. Mina goes to the park with her dog. The dog runs fast. Then Mina eats a sandwich under a big tree.";
  const r1 = K.read("read", 1, "core", 1, "e4-read", A, "Where does Mina go?", ["To the park", "To school", "To the zoo", "To the shop"], 0, T("'goes to ...'를 찾아보세요.", "Hãy tìm 'goes to ...'."), T("Mina goes to the park. = 미나는 공원에 가요.", "Mina goes to the park. = Mina đi đến công viên."));
  const r2 = K.read("read", 2, "core", 1, "e4-read", A, "Who goes with Mina?", ["Her dog", "Her cat", "Her friend", "Her mother"], 0, T("'with ...'를 찾아보세요.", "Hãy tìm 'with ...'."), T("with her dog = 그녀의 개와 함께", "with her dog = cùng với con chó của cô ấy"));
  const r3 = K.read("read", 3, "core", 2, "e4-read", A, "What does Mina eat?", ["A sandwich", "An apple", "A cake", "Pizza"], 0, T("'eats ...'를 찾아보세요.", "Hãy tìm 'eats ...'."), T("Mina eats a sandwich. = 미나는 샌드위치를 먹어요.", "Mina eats a sandwich. = Mina ăn một chiếc sandwich."));
  const r4 = K.tf({ sk: "read", n: 4, d: 2, fam: "e4-read", truth: false, prompt: T(`글을 읽고 맞는지 고르세요. "${A}" 문장: Mina eats the sandwich in the house.`, `Đọc đoạn văn rồi chọn đúng hay sai. "${A}" Câu: Mina eats the sandwich in the house.`), tags: ["reading"], hints: [T("글에서 샌드위치를 먹는 장소를 찾아보세요.", "Hãy tìm nơi Mina ăn sandwich."), T("under a big tree를 확인해요.", "Hãy xem cụm under a big tree.")], expl: T("미나는 집이 아니라 큰 나무 아래에서 먹어요.", "Mina ăn dưới một cái cây to, không phải trong nhà.") });
  const r5 = K.read("read", 5, "core", 3, "e4-read", A, "Where does Mina eat the sandwich?", ["Under a big tree", "On a chair", "In the house", "Behind the door"], 0, T("'under ...'를 찾아보세요.", "Hãy tìm 'under ...'."), T("Mina eats a sandwich under a big tree. = 미나는 큰 나무 아래에서 샌드위치를 먹어요.", "Mina eats a sandwich under a big tree. = Mina ăn sandwich dưới một cái cây to."));
  K.read("read", "v1", "variant", 1, "e4-read", A, "What day is it today?", ["Sunday", "Monday", "Friday", "Saturday"], 0, T("첫 문장을 읽어 보세요.", "Hãy đọc câu đầu tiên."), T("Today is Sunday. = 오늘은 일요일이에요.", "Today is Sunday. = Hôm nay là Chủ nhật.")); K.read("read", "v2", "variant", 2, "e4-read", A, "How does the dog run?", ["Fast", "Slowly", "Quietly", "Sadly"], 0, T("'The dog runs ...'를 찾아보세요.", "Hãy tìm 'The dog runs ...'."), T("The dog runs fast. = 개는 빨리 달려요.", "The dog runs fast. = Con chó chạy nhanh."));
  K.read("read", "d1", "diagnostic", 2, undefined, A, "Which animal is in the story?", ["A dog", "A cat", "A bird", "A fish"], 0, T("글에 나오는 동물을 찾아보세요.", "Hãy tìm con vật trong đoạn văn."), T("글에는 dog(개)가 나와요.", "Trong đoạn văn có con chó (dog)."));

  b.course({
    id: "english-e4", grade: "E4", title: T("초4 영어 · 시제, 질문과 부정, 설명하는 말", "Tiếng Anh Lớp 4 · Thì, câu hỏi, phủ định và từ miêu tả"),
    world: { name: T("Grammar Garden", "Vườn Ngữ Pháp"), emoji: "🌳", tagline: T("문장의 규칙을 하나씩 심어요", "Gieo từng quy tắc của câu") },
    unit: { id: "english-e4-u1", title: T("시제, 질문과 부정, 꾸미는 말, 위치, 읽기", "Thì, câu hỏi và phủ định, từ miêu tả, vị trí, đọc hiểu") },
    lessons: [
      lesson(1, "tense", S, T("현재·과거·미래", "Hiện tại, quá khứ và tương lai"), T("지금·반복은 **현재형**, 지난 일은 **-ed**, 앞으로 할 일은 **will + 동사원형**으로 말해요.", "Việc đang xảy ra hoặc lặp lại dùng **hiện tại**, việc đã xảy ra thêm **-ed**, việc sẽ xảy ra dùng **will + động từ nguyên mẫu**."), T("I will visit my aunt tomorrow.", "I will visit my aunt tomorrow."), [t1, t2, t3, t4], t5),
      lesson(2, "qneg", S, T("의문문과 부정문", "Câu hỏi và câu phủ định"), T("묻는 말은 **Do/Does**로 시작하고, 아니라고 말할 때는 **don't/doesn't**를 써요.", "Câu hỏi bắt đầu bằng **Do/Does**, câu phủ định dùng **don't/doesn't**."), T("Do you like pizza? I don't like onions.", "Do you like pizza? I don't like onions."), [q1, q2, q3, q4], q5),
      lesson(3, "adj", S, T("모양과 느낌을 나타내는 말", "Từ miêu tả"), T("big(큰), small(작은), hot(뜨거운), cold(차가운)처럼 모습이나 느낌을 설명하는 말이에요.", "Các từ miêu tả như big (to), small (nhỏ), hot (nóng), cold (lạnh)."), T("The ice cream is cold.", "The ice cream is cold."), [j1, j2, j3, j4], j5),
      lesson(4, "prep", S, T("장소를 나타내는 말", "Giới từ chỉ vị trí"), T("**on**(위에), **in**(안에), **under**(아래에), **behind**(뒤에)로 물건의 위치를 말해요.", "Dùng **on** (trên), **in** (trong), **under** (dưới), **behind** (sau) để nói vị trí của đồ vật."), T("The book is on the desk.", "The book is on the desk."), [pr1, pr2, pr3, pr4], pr5),
      lesson(5, "read", S, T("짧은 글 읽기", "Đọc đoạn văn ngắn"), T("누가, 어디서, 무엇을 했는지 글에서 찾아 답해요.", "Tìm trong đoạn văn xem ai, ở đâu, làm gì để trả lời."), T("Mina goes to the park.", "Mina goes to the park."), [r1, r2, r3, r4], r5),
    ],
  });
}

/* ================================ Elementary 5 ================================ */
export function e5(b) {
  const S = { gram: "e.e5.gram", comp: "e.e5.comp", future: "e.e5.future", transform: "e.e5.transform", read: "e.e5.read" };
  b.skill(S.gram, T("관사·복수형·There is/are", "Mạo từ, số nhiều, There is/are"));
  b.skill(S.comp, T("비교하는 말", "So sánh"), S.gram);
  b.skill(S.future, T("미래 표현", "Diễn đạt tương lai"), S.gram);
  b.skill(S.transform, T("문장 바꿔 쓰기", "Viết lại câu"), S.future);
  b.skill(S.read, T("글 이해하기", "Đọc hiểu"), S.transform);
  const K = kit(b, "e5", S);
  const lesson = lessonOf("e5");
  const ch = (sk, n, role, d, fam, sentence, items, hints, expl, cue) => K.choose(sk, n, role, d, fam, sentence, items, 0, hints, expl, cue);

  const g1 = ch("gram", 1, "core", 1, "e5-article", "I have ____ apple.", ["an", "a", "the", "two"], [T("apple은 모음 소리 [ae]로 시작해요.", "apple bắt đầu bằng âm nguyên âm."), T("모음 소리 앞에는 an을 써요.", "Trước âm nguyên âm dùng an.")], T("an apple = 사과 한 개", "an apple = một quả táo"));
  const g2 = ch("gram", 2, "core", 1, "e5-plural", "One box, two ____ .", ["boxes", "boxs", "box", "boxies"], [T("x로 끝나는 낱말은 -es를 붙여요.", "Từ kết thúc bằng x thì thêm -es."), T("box → boxes", "box → boxes")], T("two boxes = 상자 두 개", "two boxes = hai cái hộp"));
  const g3 = ch("gram", 3, "core", 2, "e5-there", "There ____ three books on the desk.", ["are", "is", "am", "be"], [T("books는 여러 개(복수)예요.", "books là số nhiều."), T("복수에는 There are를 써요.", "Số nhiều dùng There are.")], T("There are three books. = 책이 세 권 있어요.", "There are three books. = Có ba quyển sách."));
  const g4 = ch("gram", 4, "core", 2, "e5-article", "I see ____ elephant.", ["an", "a", "the", "two"], [T("elephant는 모음 소리로 시작해요.", "elephant bắt đầu bằng âm nguyên âm."), T("모음 소리 앞에는 an을 써요.", "Trước âm nguyên âm dùng an.")], T("an elephant = 코끼리 한 마리", "an elephant = một con voi"));
  const g5 = ch("gram", 5, "core", 3, "e5-there", "There ____ a cat under the table.", ["is", "are", "am", "be"], [T("a cat은 한 마리(단수)예요.", "a cat là số ít."), T("단수에는 There is를 써요.", "Số ít dùng There is.")], T("There is a cat. = 고양이가 한 마리 있어요.", "There is a cat. = Có một con mèo."));
  ch("gram", "v1", "variant", 1, "e5-article", "She has ____ orange.", ["an", "a", "the", "two"], [T("orange는 모음 소리로 시작해요.", "orange bắt đầu bằng âm nguyên âm."), T("모음 소리 앞에는 an을 써요.", "Trước âm nguyên âm dùng an.")], T("an orange = 오렌지 한 개", "an orange = một quả cam")); ch("gram", "v2", "variant", 2, "e5-plural", "One watch, two ____ .", ["watches", "watchs", "watch", "watchies"], [T("ch로 끝나는 낱말은 -es를 붙여요.", "Từ kết thúc bằng ch thì thêm -es."), T("watch → watches", "watch → watches")], T("two watches = 시계 두 개", "two watches = hai chiếc đồng hồ"));
  ch("gram", "d2", "diagnostic", 2, undefined, "There ____ two cats in the garden.", ["are", "is", "am", "be"], [T("cats는 여러 마리(복수)예요.", "cats là số nhiều."), T("복수에는 There are를 써요.", "Số nhiều dùng There are.")], T("There are two cats. = 고양이가 두 마리 있어요.", "There are two cats. = Có hai con mèo."));
  ch("gram", "d1", "diagnostic", 1, undefined, "This is ____ umbrella.", ["an", "a", "the", "two"], [T("umbrella는 모음 소리로 시작해요.", "umbrella bắt đầu bằng âm nguyên âm."), T("모음 소리 앞에는 an을 써요.", "Trước âm nguyên âm dùng an.")], T("an umbrella = 우산 한 개", "an umbrella = một cái ô"));

  const c1 = ch("comp", 1, "core", 1, "e5-er", "Tom is ____ than Ben.", ["taller", "tall", "tallest", "more tall"], [T("두 사람을 비교할 때는 -er을 붙여요.", "So sánh hai người thì thêm -er."), T("than은 '~보다'예요.", "than nghĩa là hơn.")], T("Tom is taller than Ben. = 톰은 벤보다 키가 커요.", "Tom is taller than Ben. = Tom cao hơn Ben."));
  const c2 = ch("comp", 2, "core", 1, "e5-er", "This bag is ____ than that one.", ["heavier", "heavy", "heaviest", "more heavy"], [T("y로 끝나면 y를 i로 바꾸고 -er을 붙여요.", "Từ kết thúc bằng y thì đổi y thành i rồi thêm -er."), T("heavy → heavier", "heavy → heavier")], T("This bag is heavier. = 이 가방이 더 무거워요.", "This bag is heavier. = Cái cặp này nặng hơn."), T("더 무겁다", "nặng hơn"));
  const c3 = ch("comp", 3, "core", 2, "e5-est", "Mt. Everest is the ____ mountain in the world.", ["highest", "higher", "high", "most high"], [T("'the ... in the world'는 가장 ~한 것을 말해요.", "'the ... in the world' nói về cái nhất."), T("-est를 붙여요.", "Thêm -est.")], T("the highest mountain = 가장 높은 산", "the highest mountain = ngọn núi cao nhất"));
  const c4 = ch("comp", 4, "core", 2, "e5-more", "This book is ____ interesting than that book.", ["more", "most", "very", "much"], [T("긴 낱말은 -er 대신 more를 앞에 붙여요.", "Từ dài thì dùng more thay cho -er."), T("more ... than = ~보다 더 ...", "more ... than = ... hơn")], T("more interesting than = ~보다 더 재미있는", "more interesting than = thú vị hơn"));
  const c5 = K.ord("comp", 5, "core", 3, "e5-er", T("내 개는 네 고양이보다 커요.", "Chó của mình to hơn mèo của bạn."), ["My", "dog", "is", "bigger", "than", "your", "cat"], [first("My"), T("bigger than은 '~보다 더 큰'이에요.", "bigger than nghĩa là to hơn.")], T("My dog is bigger than your cat. = 내 개는 네 고양이보다 커요.", "My dog is bigger than your cat. = Chó của mình to hơn mèo của bạn."));
  ch("comp", "v1", "variant", 1, "e5-er", "A rabbit is ____ than a turtle.", ["faster", "fast", "fastest", "more fast"], [T("두 동물을 비교할 때는 -er을 붙여요.", "So sánh hai con vật thì thêm -er."), T("than은 '~보다'예요.", "than nghĩa là hơn.")], T("A rabbit is faster. = 토끼가 더 빨라요.", "A rabbit is faster. = Thỏ nhanh hơn.")); ch("comp", "v2", "variant", 2, "e5-est", "She is the ____ student in my class.", ["smartest", "smarter", "smart", "most smart"], [T("'the ... in my class'는 가장 ~한 사람을 말해요.", "'the ... in my class' nói về người nhất."), T("-est를 붙여요.", "Thêm -est.")], T("the smartest student = 가장 똑똑한 학생", "the smartest student = học sinh thông minh nhất"));
  ch("comp", "d1", "diagnostic", 2, undefined, "My brother is ____ than me.", ["older", "old", "oldest", "more old"], [T("두 사람을 비교할 때는 -er을 붙여요.", "So sánh hai người thì thêm -er."), T("than은 '~보다'예요.", "than nghĩa là hơn.")], T("My brother is older than me. = 우리 형은 나보다 나이가 많아요.", "My brother is older than me. = Anh trai mình hơn tuổi mình."));

  const f1 = ch("future", 1, "core", 1, "e5-goingto", "I am ____ to visit Jeju tomorrow.", ["going", "go", "goes", "will"], [T("be going to + 동사원형은 '~할 예정이다'예요.", "be going to + động từ nguyên mẫu nghĩa là sắp/định làm."), T("am 다음에는 going이 와요.", "Sau am là going.")], T("I am going to visit Jeju. = 나는 제주에 갈 예정이에요.", "I am going to visit Jeju. = Mình sắp đi thăm Jeju."));
  const f2 = ch("future", 2, "core", 1, "e5-will", "It will ____ tomorrow.", ["rain", "rains", "rained", "raining"], [T("will 다음에는 동사원형이 와요.", "Sau will là động từ nguyên mẫu."), T("-s나 -ed를 붙이지 않아요.", "Không thêm -s hay -ed.")], T("It will rain tomorrow. = 내일 비가 올 거예요.", "It will rain tomorrow. = Ngày mai trời sẽ mưa."));
  const f3 = K.write({ sk: "future", n: 3, d: 2, fam: "e5-will", type: "fill_blank", prompt: T("빈칸에 알맞은 단어를 쓰세요: Next Sunday, we ____ go camping. (~할 것이다)", "Điền từ thích hợp: Next Sunday, we ____ go camping. (sẽ)"), accepted: ["will"], tags: ["grammar"], hints: [T("미래를 나타내는 말이에요.", "Đây là từ chỉ tương lai."), H.first("will")], expl: T("We will go camping. = 우리는 캠핑을 갈 거예요.", "We will go camping. = Chúng mình sẽ đi cắm trại.") });
  const f4 = K.ord("future", 4, "core", 2, "e5-goingto", T("그녀는 영어를 공부할 예정이에요.", "Cô ấy sắp học tiếng Anh."), ["She", "is", "going", "to", "study", "English"], [first("She"), T("is going to 다음에 동사원형이 와요.", "Sau is going to là động từ nguyên mẫu.")], T("She is going to study English. = 그녀는 영어를 공부할 예정이에요.", "She is going to study English. = Cô ấy sắp học tiếng Anh."));
  const f5 = ch("future", 5, "core", 3, "e5-goingto", "What are you going to ____ tomorrow?", ["do", "does", "did", "doing"], [T("going to 다음에는 동사원형이 와요.", "Sau going to là động từ nguyên mẫu."), T("do가 동사원형이에요.", "do là động từ nguyên mẫu.")], T("What are you going to do? = 너는 무엇을 할 거니?", "What are you going to do? = Bạn định làm gì?"));
  ch("future", "v1", "variant", 1, "e5-goingto", "We are ____ to play soccer.", ["going", "go", "goes", "will"], [T("be going to + 동사원형이에요.", "Cấu trúc be going to + động từ nguyên mẫu."), T("are 다음에는 going이 와요.", "Sau are là going.")], T("We are going to play soccer. = 우리는 축구를 할 예정이에요.", "We are going to play soccer. = Chúng mình sắp chơi bóng đá.")); ch("future", "v2", "variant", 2, "e5-will", "He will ____ his homework.", ["do", "does", "did", "doing"], [T("will 다음에는 동사원형이 와요.", "Sau will là động từ nguyên mẫu."), T("do가 동사원형이에요.", "do là động từ nguyên mẫu.")], T("He will do his homework. = 그는 숙제를 할 거예요.", "He will do his homework. = Anh ấy sẽ làm bài tập."));
  ch("future", "d1", "diagnostic", 1, undefined, "I will ____ you tomorrow.", ["call", "calls", "called", "calling"], [T("will 다음에는 동사원형이 와요.", "Sau will là động từ nguyên mẫu."), T("-s나 -ed를 붙이지 않아요.", "Không thêm -s hay -ed.")], T("I will call you tomorrow. = 내일 전화할게요.", "I will call you tomorrow. = Ngày mai mình sẽ gọi cho bạn."));

  const NEG = T("다음 문장을 부정문으로 바꿔 쓰세요.", "Viết lại câu sau thành câu phủ định.");
  const QST = T("다음 문장을 의문문으로 바꿔 쓰세요.", "Viết lại câu sau thành câu hỏi.");
  const x1 = ch("transform", 1, "core", 1, "e5-neg", "I like carrots. → I ____ like carrots.", ["don't", "doesn't", "isn't", "not"], [T("주어가 I이고 like는 일반동사예요.", "Chủ ngữ là I và like là động từ thường."), T("don't + 동사원형이에요.", "don't + động từ nguyên mẫu.")], T("I don't like carrots. = 나는 당근을 좋아하지 않아요.", "I don't like carrots. = Mình không thích cà rốt."));
  const x2 = ch("transform", 2, "core", 1, "e5-question", "You are a student. → ____ you a student?", ["Are", "Do", "Is", "Am"], [T("be동사 문장은 be동사를 앞으로 보내요.", "Câu có động từ be thì đưa be lên đầu để hỏi."), T("you 다음에는 are를 써요.", "Sau you dùng are.")], T("Are you a student? = 너는 학생이니?", "Are you a student? = Bạn là học sinh phải không?"));
  const x3 = ch("transform", 3, "core", 2, "e5-neg", "He played soccer. → He ____ play soccer.", ["didn't", "doesn't", "don't", "isn't"], [T("played는 과거형이에요. 과거 부정은 didn't를 써요.", "played là quá khứ, phủ định quá khứ dùng didn't."), T("didn't 다음에는 동사원형이 와요.", "Sau didn't là động từ nguyên mẫu.")], T("He didn't play soccer. = 그는 축구를 하지 않았어요.", "He didn't play soccer. = Anh ấy đã không chơi bóng đá."));
  const x4 = K.rewrite("transform", 4, "core", 2, "e5-neg", "I am happy.", NEG, ["I am not happy", "I'm not happy"], [T("am 뒤에 not을 붙여요.", "Thêm not sau am."), T("I am not happy. 처럼 써요.", "Viết thành I am not happy.")], T("I am not happy. = 나는 행복하지 않아요.", "I am not happy. = Mình không vui."));
  const x5 = K.rewrite("transform", 5, "core", 3, "e5-question", "She likes dogs.", QST, ["Does she like dogs"], [T("Does로 시작하고 동사는 원형으로 써요.", "Bắt đầu bằng Does và dùng động từ nguyên mẫu."), T("likes → like", "likes → like")], T("Does she like dogs? = 그녀는 개를 좋아하니?", "Does she like dogs? = Cô ấy có thích chó không?"));
  ch("transform", "v1", "variant", 1, "e5-neg", "She likes fish. → She ____ like fish.", ["doesn't", "don't", "isn't", "didn't"], [T("주어가 She이고 현재형이에요.", "Chủ ngữ là She và thì hiện tại."), T("doesn't + 동사원형이에요.", "doesn't + động từ nguyên mẫu.")], T("She doesn't like fish. = 그녀는 생선을 좋아하지 않아요.", "She doesn't like fish. = Cô ấy không thích cá.")); K.rewrite("transform", "v2", "variant", 2, "e5-neg", "He is tall.", NEG, ["He is not tall", "He isn't tall"], [T("is 뒤에 not을 붙여요.", "Thêm not sau is."), T("He is not tall. 처럼 써요.", "Viết thành He is not tall.")], T("He is not tall. = 그는 키가 크지 않아요.", "He is not tall. = Anh ấy không cao."));
  ch("transform", "d1", "diagnostic", 2, undefined, "They are happy. → ____ they happy?", ["Are", "Do", "Is", "Does"], [T("be동사 문장은 be동사를 앞으로 보내요.", "Câu có động từ be thì đưa be lên đầu để hỏi."), T("they 다음에는 are를 써요.", "Sau they dùng are.")], T("Are they happy? = 그들은 행복하니?", "Are they happy? = Họ có vui không?"));

  const P = "Ken lives in Busan. He has two sisters. His older sister is a teacher. His younger sister is going to start school next month. On weekends, they usually go to the beach.";
  const r1 = K.read("read", 1, "core", 1, "e5-read", P, "Where does Ken live?", ["In Busan", "In Seoul", "In Jeju", "In Daegu"], 0, T("'lives in ...'를 찾아보세요.", "Hãy tìm 'lives in ...'."), T("Ken lives in Busan. = 켄은 부산에 살아요.", "Ken lives in Busan. = Ken sống ở Busan."));
  const r2 = K.read("read", 2, "core", 1, "e5-read", P, "How many sisters does Ken have?", ["Two", "One", "Three", "Four"], 0, T("'has two sisters'를 찾아보세요.", "Hãy tìm 'has two sisters'."), T("Ken has two sisters. = 켄은 여동생·누나가 둘 있어요.", "Ken has two sisters. = Ken có hai chị em gái."));
  const r3 = K.read("read", 3, "core", 2, "e5-read", P, "What is Ken's older sister?", ["A teacher", "A nurse", "A student", "A doctor"], 0, T("'older sister is ...'를 찾아보세요.", "Hãy tìm 'older sister is ...'."), T("His older sister is a teacher. = 누나는 선생님이에요.", "His older sister is a teacher. = Chị gái của anh ấy là giáo viên."));
  const r4 = K.read("read", 4, "core", 2, "e5-read", P, "When is the younger sister going to start school?", ["Next month", "Tomorrow", "Next year", "Yesterday"], 0, T("'is going to ...'를 찾아보세요.", "Hãy tìm 'is going to ...'."), T("She is going to start school next month. = 다음 달에 학교에 들어갈 예정이에요.", "She is going to start school next month. = Em gái sắp vào học tháng sau."));
  const r5 = K.read("read", 5, "core", 3, "e5-read", P, "Where do they usually go on weekends?", ["To the beach", "To the park", "To the zoo", "To the shop"], 0, T("'On weekends'를 찾아보세요.", "Hãy tìm 'On weekends'."), T("On weekends, they usually go to the beach. = 주말에 그들은 보통 해변에 가요.", "On weekends, they usually go to the beach. = Cuối tuần họ thường đi biển."));
  K.read("read", "v1", "variant", 1, "e5-read", P, "Who is a teacher?", ["Ken's older sister", "Ken", "Ken's mother", "Ken's friend"], 0, T("'is a teacher'를 찾아보세요.", "Hãy tìm 'is a teacher'."), T("His older sister is a teacher. = 누나는 선생님이에요.", "His older sister is a teacher. = Chị gái là giáo viên.")); K.read("read", "v2", "variant", 2, "e5-read", P, "How often do they go to the beach?", ["On weekends", "Every day", "Never", "On Mondays"], 0, T("'usually'는 '보통'이에요.", "'usually' nghĩa là thường."), T("On weekends = 주말마다", "On weekends = vào cuối tuần"));
  K.read("read", "d1", "diagnostic", 2, undefined, P, "Which city does Ken live in?", ["Busan", "Seoul", "Jeju", "Incheon"], 0, T("'lives in ...'를 찾아보세요.", "Hãy tìm 'lives in ...'."), T("Ken lives in Busan. = 켄은 부산에 살아요.", "Ken lives in Busan. = Ken sống ở Busan."));

  b.course({
    id: "english-e5", grade: "E5", title: T("초5 영어 · 문법 넓히기와 비교, 미래, 바꿔 쓰기", "Tiếng Anh Lớp 5 · Mở rộng ngữ pháp, so sánh, tương lai và viết lại câu"),
    world: { name: T("Comparison Cliffs", "Vách Đá So Sánh"), emoji: "🧗", tagline: T("비교하며 한 걸음씩 올라가요", "Leo lên từng bước bằng cách so sánh") },
    unit: { id: "english-e5-u1", title: T("관사와 복수형, 비교, 미래, 문장 바꿔 쓰기, 읽기", "Mạo từ và số nhiều, so sánh, tương lai, viết lại câu, đọc hiểu") },
    lessons: [
      lesson(1, "gram", S, T("관사·복수형·There is/are", "Mạo từ, số nhiều, There is/are"), T("모음 소리 앞에는 **an**, 자음 소리 앞에는 **a**를 써요. 하나면 **There is**, 여러 개면 **There are**를 써요.", "Trước âm nguyên âm dùng **an**, trước âm phụ âm dùng **a**. Một vật dùng **There is**, nhiều vật dùng **There are**."), T("an apple, two boxes, There are three books.", "an apple, two boxes, There are three books."), [g1, g2, g3, g4], g5),
      lesson(2, "comp", S, T("비교하는 말", "So sánh"), T("둘을 비교할 때는 **-er + than**, 가장 ~한 것은 **the -est**를 써요. 긴 낱말은 **more**를 써요.", "So sánh hai thứ dùng **-er + than**, cái nhất dùng **the -est**. Từ dài dùng **more**."), T("Tom is taller than Ben.", "Tom is taller than Ben."), [c1, c2, c3, c4], c5),
      lesson(3, "future", S, T("미래 표현", "Diễn đạt tương lai"), T("앞으로 할 일은 **will + 동사원형** 또는 **be going to + 동사원형**으로 말해요.", "Việc sẽ làm diễn đạt bằng **will + động từ nguyên mẫu** hoặc **be going to + động từ nguyên mẫu**."), T("I am going to visit Jeju.", "I am going to visit Jeju."), [f1, f2, f3, f4], f5),
      lesson(4, "transform", S, T("문장 바꿔 쓰기", "Viết lại câu"), T("부정문은 **not / don't / doesn't / didn't**를, 의문문은 **Are / Do / Does**를 문장 앞에 써요.", "Câu phủ định dùng **not / don't / doesn't / didn't**, câu hỏi đặt **Are / Do / Does** ở đầu câu."), T("I am happy. → I am not happy.", "I am happy. → I am not happy."), [x1, x2, x3, x4], x5),
      lesson(5, "read", S, T("글 이해하기", "Đọc hiểu"), T("긴 글은 누가·어디·언제·무엇을에 밑줄을 치듯 찾아 읽으면 쉬워요.", "Với đoạn văn dài, hãy tìm ai, ở đâu, khi nào, làm gì thì sẽ dễ hơn."), T("Ken lives in Busan.", "Ken lives in Busan."), [r1, r2, r3, r4], r5),
    ],
  });
}

/* ================================ Elementary 6 ================================ */
export function e6(b) {
  const S = { tense: "e.e6.tense", modal: "e.e6.modal", vocab: "e.e6.vocab", clause: "e.e6.clause", read: "e.e6.read" };
  b.skill(S.tense, T("시제 총정리", "Tổng ôn các thì"));
  b.skill(S.modal, T("can, must, should, may", "can, must, should, may"), S.tense);
  b.skill(S.vocab, T("낱말 넓히기", "Mở rộng vốn từ"), S.tense);
  b.skill(S.clause, T("이어 주는 말", "Từ nối câu"), S.modal);
  b.skill(S.read, T("문단 읽기", "Đọc đoạn văn"), S.clause);
  const K = kit(b, "e6", S);
  const lesson = lessonOf("e6");
  const ch = (sk, n, role, d, fam, sentence, items, hints, expl, cue) => K.choose(sk, n, role, d, fam, sentence, items, 0, hints, expl, cue);

  const t1 = ch("tense", 1, "core", 1, "e6-ing", "Look! The baby ____ now.", ["is sleeping", "sleeps", "slept", "will sleep"], [T("Look!과 now는 '지금 하는 일'을 말해요.", "Look! và now nói về việc đang xảy ra."), T("현재진행형은 be + -ing예요.", "Thì hiện tại tiếp diễn là be + -ing.")], T("The baby is sleeping now. = 아기가 지금 자고 있어요.", "The baby is sleeping now. = Em bé đang ngủ."));
  const t2 = ch("tense", 2, "core", 1, "e6-past", "I ____ my homework last night.", ["did", "do", "does", "doing"], [T("last night은 '어젯밤'이에요. 과거예요.", "last night là tối qua, thì quá khứ."), T("do의 과거형은 did예요.", "Quá khứ của do là did.")], T("I did my homework. = 나는 숙제를 했어요.", "I did my homework. = Mình đã làm bài tập."));
  const t3 = ch("tense", 3, "core", 2, "e6-present", "She usually ____ at six.", ["gets up", "got up", "is getting up", "will get up"], [T("usually는 '보통'이에요. 반복되는 일이에요.", "usually nghĩa là thường, việc lặp lại."), T("주어가 She이므로 동사에 -s를 붙여요.", "Chủ ngữ là She nên động từ thêm -s.")], T("She usually gets up at six. = 그녀는 보통 6시에 일어나요.", "She usually gets up at six. = Cô ấy thường thức dậy lúc 6 giờ."));
  const t4 = K.write({ sk: "tense", n: 4, d: 2, fam: "e6-ing", type: "fill_blank", prompt: T("빈칸에 알맞은 단어를 쓰세요: They are ____ in the park now. (play)", "Điền từ thích hợp: They are ____ in the park now. (play)"), accepted: ["playing"], tags: ["grammar"], hints: [T("are 다음에는 동사 + -ing가 와요.", "Sau are là động từ + -ing."), H.first("playing")], expl: T("They are playing in the park. = 그들은 공원에서 놀고 있어요.", "They are playing in the park. = Họ đang chơi trong công viên.") });
  const t5 = ch("tense", 5, "core", 3, "e6-future", "By next year, I ____ 13 years old.", ["will be", "am", "was", "being"], [T("next year는 '내년'이에요. 미래예요.", "next year là năm sau, tương lai."), T("will be는 '~이 될 것이다'예요.", "will be nghĩa là sẽ là.")], T("I will be 13 years old. = 나는 내년에 13살이 될 거예요.", "I will be 13 years old. = Sang năm mình sẽ 13 tuổi."));
  ch("tense", "v1", "variant", 1, "e6-ing", "Be quiet! My father ____ .", ["is working", "works", "worked", "will work"], [T("지금 하고 있는 일이에요.", "Việc đang xảy ra."), T("현재진행형은 be + -ing예요.", "Thì hiện tại tiếp diễn là be + -ing.")], T("My father is working. = 아빠는 일하고 계세요.", "My father is working. = Bố đang làm việc.")); ch("tense", "v2", "variant", 2, "e6-past", "We ____ to the museum yesterday.", ["went", "go", "goes", "going"], [T("yesterday는 과거예요.", "yesterday là quá khứ."), T("go의 과거형은 went예요.", "Quá khứ của go là went.")], T("We went to the museum. = 우리는 박물관에 갔어요.", "We went to the museum. = Chúng mình đã đi bảo tàng."));
  ch("tense", "d1", "diagnostic", 2, undefined, "He ____ breakfast every day.", ["eats", "ate", "is eating", "will eat"], [T("every day는 반복되는 일이에요.", "every day là việc lặp lại."), T("주어가 He이므로 -s를 붙여요.", "Chủ ngữ là He nên thêm -s.")], T("He eats breakfast every day. = 그는 매일 아침을 먹어요.", "He eats breakfast every day. = Anh ấy ăn sáng mỗi ngày."));

  const m1 = ch("modal", 1, "core", 1, "e6-can", "I ____ swim.", ["can", "cans", "am can", "canning"], [T("can 다음에는 동사원형이 와요.", "Sau can là động từ nguyên mẫu."), T("can은 '~할 수 있다'예요.", "can nghĩa là có thể.")], T("I can swim. = 나는 수영할 수 있어요.", "I can swim. = Mình biết bơi."));
  const m2 = ch("modal", 2, "core", 1, "e6-must", "You ____ be quiet in the library.", ["must", "can", "may", "will"], [T("must는 '반드시 ~해야 한다'예요.", "must nghĩa là bắt buộc phải."), T("도서관에서는 꼭 지켜야 하는 규칙이에요.", "Đây là quy tắc bắt buộc trong thư viện.")], T("You must be quiet. = 조용히 해야 해요.", "You must be quiet. = Bạn phải giữ yên lặng."));
  const m3 = ch("modal", 3, "core", 2, "e6-may", "____ I open the window?", ["May", "Must", "Will", "Do"], [T("'~해도 될까요?'라고 허락을 구할 때 May I ...?를 써요.", "Xin phép thì dùng May I ...?"), T("May I open ...? = 열어도 될까요?", "May I open ...? = Mình mở ... được không?")], T("May I open the window? = 창문을 열어도 될까요?", "May I open the window? = Mình mở cửa sổ được không?"));
  const m4 = ch("modal", 4, "core", 2, "e6-should", "You ____ brush your teeth every day.", ["should", "may", "can", "will"], [T("should는 '~하는 게 좋다'예요.", "should nghĩa là nên."), T("좋은 습관을 권할 때 써요.", "Dùng khi khuyên làm điều tốt.")], T("You should brush your teeth. = 매일 이를 닦는 게 좋아요.", "You should brush your teeth. = Bạn nên đánh răng mỗi ngày."));
  const m5 = K.ord("modal", 5, "core", 3, "e6-must", T("여기서 달리면 안 돼요.", "Không được chạy ở đây."), ["You", "must", "not", "run", "here"], [first("You"), T("must not은 '~하면 안 된다'예요.", "must not nghĩa là không được.")], T("You must not run here. = 여기서 뛰면 안 돼요.", "You must not run here. = Bạn không được chạy ở đây."));
  ch("modal", "v1", "variant", 1, "e6-can", "She ____ play the piano.", ["can", "cans", "is can", "canning"], [T("can 다음에는 동사원형이 와요.", "Sau can là động từ nguyên mẫu."), T("주어가 She여도 can에는 -s를 붙이지 않아요.", "Dù chủ ngữ là She, can vẫn không thêm -s.")], T("She can play the piano. = 그녀는 피아노를 칠 수 있어요.", "She can play the piano. = Cô ấy biết chơi piano.")); ch("modal", "v2", "variant", 2, "e6-should", "You ____ drink more water.", ["should", "may", "can", "must not"], [T("should는 '~하는 게 좋다'예요.", "should nghĩa là nên."), T("건강에 좋은 일을 권해요.", "Khuyên làm điều tốt cho sức khỏe.")], T("You should drink more water. = 물을 더 마시는 게 좋아요.", "You should drink more water. = Bạn nên uống nhiều nước hơn."));
  ch("modal", "d1", "diagnostic", 2, undefined, "He ____ speak English well.", ["can", "cans", "is can", "canning"], [T("can 다음에는 동사원형이 와요.", "Sau can là động từ nguyên mẫu."), T("can은 '~할 수 있다'예요.", "can nghĩa là có thể.")], T("He can speak English well. = 그는 영어를 잘해요.", "He can speak English well. = Anh ấy nói tiếng Anh giỏi."));

  const v1 = K.ask("vocab", 1, "core", 1, "e6-synonym", "Which word means almost the same as 'big'?", ["large", "small", "tiny", "short"], [T("'big'은 '큰'이에요. 비슷한 뜻의 낱말을 찾아요.", "'big' nghĩa là to. Hãy tìm từ gần nghĩa."), T("large는 '큰'이에요.", "large nghĩa là to, lớn.")], T("big ≈ large (큰)", "big ≈ large (to, lớn)"));
  const v2 = K.ask("vocab", 2, "core", 1, "e6-antonym", "Which word is the opposite of 'happy'?", ["sad", "glad", "kind", "tall"], [T("반대말을 찾아요.", "Hãy tìm từ trái nghĩa."), T("sad는 '슬픈'이에요.", "sad nghĩa là buồn.")], T("happy(행복한) ↔ sad(슬픈)", "happy (vui) ↔ sad (buồn)"));
  const v3 = K.meaning("vocab", 3, "core", 2, "e6-meaning", W("borrow", "빌리다", "mượn"), [W("lend", "빌려주다", "cho mượn"), W("return", "돌려주다", "trả lại"), W("buy", "사다", "mua")]);
  const v4 = K.write({ sk: "vocab", n: 4, d: 2, fam: "e6-antonym", type: "fill_blank", prompt: T("빈칸에 알맞은 단어를 쓰세요: The opposite of 'early' is ____ . (늦은)", "Điền từ thích hợp: The opposite of 'early' is ____ . (muộn)"), accepted: ["late"], tags: ["vocab"], hints: [T("early는 '이른'이에요. 반대는 '늦은'이에요.", "early nghĩa là sớm. Ngược lại là muộn."), H.first("late")], expl: T("early(이른) ↔ late(늦은)", "early (sớm) ↔ late (muộn)") });
  const v5 = K.ask("vocab", 5, "core", 3, "e6-synonym", "Which word means almost the same as 'beautiful'?", ["pretty", "ugly", "angry", "heavy"], [T("'beautiful'은 '아름다운'이에요.", "'beautiful' nghĩa là đẹp."), T("pretty는 '예쁜'이에요.", "pretty nghĩa là xinh, đẹp.")], T("beautiful ≈ pretty (아름다운, 예쁜)", "beautiful ≈ pretty (đẹp, xinh)"));
  K.ask("vocab", "v1", "variant", 1, "e6-synonym", "Which word means almost the same as 'small'?", ["little", "large", "huge", "long"], [T("'small'은 '작은'이에요.", "'small' nghĩa là nhỏ."), T("little은 '작은'이에요.", "little nghĩa là nhỏ.")], T("small ≈ little (작은)", "small ≈ little (nhỏ)")); K.ask("vocab", "v2", "variant", 2, "e6-antonym", "Which word is the opposite of 'hot'?", ["cold", "warm", "sunny", "dry"], [T("반대말을 찾아요.", "Hãy tìm từ trái nghĩa."), T("cold는 '차가운'이에요.", "cold nghĩa là lạnh.")], T("hot(뜨거운) ↔ cold(차가운)", "hot (nóng) ↔ cold (lạnh)"));
  K.ask("vocab", "d2", "diagnostic", 2, undefined, "Which word is the opposite of 'open'?", ["close", "break", "build", "carry"], [T("열다의 반대는 닫다예요.", "Ngược với mở là đóng."), T("close는 '닫다'예요.", "close nghĩa là đóng.")], T("open(열다) ↔ close(닫다)", "open (mở) ↔ close (đóng)"));
  K.meaning("vocab", "d1", "diagnostic", 1, undefined, W("library", "도서관", "thư viện"), [W("hospital", "병원", "bệnh viện"), W("airport", "공항", "sân bay"), W("bakery", "빵집", "tiệm bánh")]);

  const k1 = ch("clause", 1, "core", 1, "e6-because", "I stayed home ____ it rained.", ["because", "but", "or", "so"], [T("이유를 말할 때는 because를 써요.", "Nói lý do thì dùng because."), T("because는 '왜냐하면'이에요.", "because nghĩa là bởi vì.")], T("I stayed home because it rained. = 비가 와서 집에 있었어요.", "I stayed home because it rained. = Mình ở nhà vì trời mưa."));
  const k2 = ch("clause", 2, "core", 1, "e6-if", "If it rains, I ____ stay home.", ["will", "did", "was", "am"], [T("If 문장에서 앞으로의 일은 will로 말해요.", "Trong câu If, kết quả trong tương lai dùng will."), T("will + 동사원형이에요.", "will + động từ nguyên mẫu.")], T("If it rains, I will stay home. = 비가 오면 집에 있을 거예요.", "If it rains, I will stay home. = Nếu trời mưa, mình sẽ ở nhà."));
  const k3 = ch("clause", 3, "core", 2, "e6-so", "I was tired, ____ I went to bed early.", ["so", "because", "but", "or"], [T("결과를 말할 때는 so를 써요.", "Nói kết quả thì dùng so."), T("so는 '그래서'예요.", "so nghĩa là vì vậy.")], T("I was tired, so I went to bed early. = 피곤해서 일찍 잤어요.", "I was tired, so I went to bed early. = Mình mệt nên đi ngủ sớm."));
  const k4 = ch("clause", 4, "core", 2, "e6-but", "She is smart ____ shy.", ["but", "because", "so", "if"], [T("서로 다른 내용을 이을 때는 but을 써요.", "Nối hai ý trái ngược thì dùng but."), T("but은 '하지만'이에요.", "but nghĩa là nhưng.")], T("She is smart but shy. = 그녀는 똑똑하지만 수줍음이 많아요.", "She is smart but shy. = Cô ấy thông minh nhưng nhút nhát."));
  const k5 = K.ord("clause", 5, "core", 3, "e6-when", T("내가 집에 왔을 때 어두웠어요.", "Khi mình về đến nhà thì trời đã tối."), ["When", "I", "got", "home", "it", "was", "dark"], [first("When"), T("When은 '~할 때'예요.", "When nghĩa là khi.")], T("When I got home, it was dark. = 내가 집에 왔을 때 어두웠어요.", "When I got home, it was dark. = Khi mình về đến nhà thì trời đã tối."));
  ch("clause", "v1", "variant", 1, "e6-because", "He is happy ____ he got a gift.", ["because", "but", "or", "if"], [T("이유를 말할 때는 because를 써요.", "Nói lý do thì dùng because."), T("because는 '왜냐하면'이에요.", "because nghĩa là bởi vì.")], T("He is happy because he got a gift. = 선물을 받아서 행복해요.", "He is happy because he got a gift. = Anh ấy vui vì được tặng quà.")); ch("clause", "v2", "variant", 2, "e6-but", "I like pizza, ____ I don't like onions.", ["but", "because", "so", "or"], [T("서로 다른 내용을 이을 때는 but을 써요.", "Nối hai ý trái ngược thì dùng but."), T("but은 '하지만'이에요.", "but nghĩa là nhưng.")], T("I like pizza, but I don't like onions. = 피자는 좋아하지만 양파는 싫어해요.", "I like pizza, but I don't like onions. = Mình thích pizza nhưng không thích hành tây."));
  ch("clause", "d1", "diagnostic", 2, undefined, "I was hungry, ____ I ate lunch.", ["so", "because", "but", "if"], [T("결과를 말할 때는 so를 써요.", "Nói kết quả thì dùng so."), T("so는 '그래서'예요.", "so nghĩa là vì vậy.")], T("I was hungry, so I ate lunch. = 배고파서 점심을 먹었어요.", "I was hungry, so I ate lunch. = Mình đói nên đã ăn trưa."));

  const P = "Last Saturday, Jina and her brother went to a science museum. They saw a big dinosaur and learned about space. Jina was tired because they walked a lot, but she was very happy. Next weekend, they are going to visit a zoo.";
  const r1 = K.read("read", 1, "core", 1, "e6-read", P, "Where did Jina and her brother go last Saturday?", ["To a science museum", "To a zoo", "To a park", "To a library"], 0, T("'went to ...'를 찾아보세요.", "Hãy tìm 'went to ...'."), T("They went to a science museum. = 그들은 과학관에 갔어요.", "They went to a science museum. = Họ đã đến bảo tàng khoa học."));
  const r2 = K.read("read", 2, "core", 1, "e6-read", P, "What did they see?", ["A big dinosaur", "A blue whale", "A small bird", "A red car"], 0, T("'saw ...'를 찾아보세요.", "Hãy tìm 'saw ...'."), T("They saw a big dinosaur. = 그들은 큰 공룡을 봤어요.", "They saw a big dinosaur. = Họ đã nhìn thấy một con khủng long lớn."));
  const r3 = K.read("read", 3, "core", 2, "e6-read", P, "Why was Jina tired?", ["Because they walked a lot", "Because she was sick", "Because she woke up late", "Because it rained"], 0, T("'because'를 찾아보세요.", "Hãy tìm từ 'because'."), T("Jina was tired because they walked a lot. = 많이 걸어서 지나는 피곤했어요.", "Jina was tired because they walked a lot. = Jina mệt vì họ đã đi bộ nhiều."));
  const r4 = K.tf({ sk: "read", n: 4, d: 2, fam: "e6-read", truth: true, prompt: T(`글을 읽고 맞는지 고르세요. "${P}" 문장: Jina was happy.`, `Đọc đoạn văn rồi chọn đúng hay sai. "${P}" Câu: Jina was happy.`), tags: ["reading"], hints: [T("'but she was very happy'를 찾아보세요.", "Hãy tìm 'but she was very happy'."), T("tired와 happy는 달라요.", "tired và happy là hai từ khác nhau.")], expl: T("지나는 피곤했지만 매우 행복했어요.", "Jina mệt nhưng rất vui.") });
  const r5 = K.read("read", 5, "core", 3, "e6-read", P, "What are they going to do next weekend?", ["Visit a zoo", "Go to school", "Stay home", "Play soccer"], 0, T("'are going to ...'를 찾아보세요.", "Hãy tìm 'are going to ...'."), T("They are going to visit a zoo. = 그들은 동물원에 갈 예정이에요.", "They are going to visit a zoo. = Họ sắp đi thăm sở thú."));
  K.read("read", "v1", "variant", 1, "e6-read", P, "What did they learn about?", ["Space", "Cooking", "Music", "Sports"], 0, T("'learned about ...'를 찾아보세요.", "Hãy tìm 'learned about ...'."), T("They learned about space. = 그들은 우주에 대해 배웠어요.", "They learned about space. = Họ đã học về vũ trụ.")); K.read("read", "v2", "variant", 2, "e6-read", P, "Who went to the museum with Jina?", ["Her brother", "Her mother", "Her teacher", "Her friend"], 0, T("첫 문장을 읽어 보세요.", "Hãy đọc câu đầu tiên."), T("Jina and her brother went to a science museum. = 지나와 오빠는 과학관에 갔어요.", "Jina and her brother went to a science museum. = Jina và anh trai đã đến bảo tàng khoa học."));
  K.read("read", "d1", "diagnostic", 2, undefined, P, "When did they go to the museum?", ["Last Saturday", "Next weekend", "Yesterday", "Last year"], 0, T("글의 첫 낱말을 보세요.", "Hãy xem các từ đầu tiên của đoạn văn."), T("Last Saturday = 지난 토요일", "Last Saturday = thứ Bảy tuần trước"));

  b.course({
    id: "english-e6", grade: "E6", title: T("초6 영어 · 중학교 준비", "Tiếng Anh Lớp 6 · Chuẩn bị lên cấp trung học"),
    world: { name: T("Bridge to Middle School", "Cây Cầu Lên Cấp Hai"), emoji: "🌉", tagline: T("지금까지 배운 것을 튼튼히 이어요", "Nối vững chắc những gì đã học") },
    unit: { id: "english-e6-u1", title: T("시제 총정리, 조동사, 낱말, 이어 주는 말, 문단 읽기", "Ôn các thì, động từ khuyết thiếu, từ vựng, từ nối, đọc đoạn văn") },
    lessons: [
      lesson(1, "tense", S, T("시제 총정리", "Tổng ôn các thì"), T("지금 하는 일은 **be + -ing**, 지난 일은 **과거형**, 앞으로 할 일은 **will / be going to**로 말해요.", "Việc đang làm dùng **be + -ing**, việc đã xảy ra dùng **quá khứ**, việc sẽ làm dùng **will / be going to**."), T("The baby is sleeping now.", "The baby is sleeping now."), [t1, t2, t3, t4], t5),
      lesson(2, "modal", S, T("can, must, should, may", "can, must, should, may"), T("**can**(할 수 있다), **must**(해야 한다), **should**(하는 게 좋다), **may**(해도 된다) 다음에는 동사원형이 와요.", "Sau **can** (có thể), **must** (phải), **should** (nên), **may** (được phép) là động từ nguyên mẫu."), T("You should brush your teeth.", "You should brush your teeth."), [m1, m2, m3, m4], m5),
      lesson(3, "vocab", S, T("낱말 넓히기", "Mở rộng vốn từ"), T("비슷한 뜻의 낱말과 반대말을 함께 익히면 낱말이 두 배로 늘어요.", "Học từ đồng nghĩa và trái nghĩa cùng nhau sẽ làm vốn từ tăng gấp đôi."), T("big ≈ large, happy ↔ sad", "big ≈ large, happy ↔ sad"), [v1, v2, v3, v4], v5),
      lesson(4, "clause", S, T("이어 주는 말", "Từ nối câu"), T("**because**(이유), **so**(결과), **but**(반대), **if**(만약), **when**(~할 때)으로 문장을 이어요.", "Nối câu bằng **because** (lý do), **so** (kết quả), **but** (đối lập), **if** (nếu), **when** (khi)."), T("I was tired, so I went to bed early.", "I was tired, so I went to bed early."), [k1, k2, k3, k4], k5),
      lesson(5, "read", S, T("문단 읽기", "Đọc đoạn văn"), T("여러 문장으로 된 글을 읽고 누가·언제·왜 했는지 찾아 답해요.", "Đọc đoạn văn nhiều câu và tìm xem ai, khi nào, vì sao làm điều đó."), T("Jina was tired because they walked a lot.", "Jina was tired because they walked a lot."), [r1, r2, r3, r4], r5),
    ],
  });
}
