// Vietnamese overlay for the EXISTING middle-school demo content (lib/learn/content/demo/*.json). Same shape as the generated overlay:
//   { skills, courses, units, lessons, questions }. Formulas (LaTeX) are copied unchanged; answer keys and option ids are never touched.
const r = String.raw;
const Q = (prompt, hints, explanation, options) => ({ prompt, hints, explanation, ...(options ? { options } : {}) });

export const viDemoMath = {
  skills: { "m.int": "Tính toán với số nguyên", "m.expr": "Giá trị của biểu thức", "m.prop": "Tính chất của đẳng thức", "m.solve": "Giải phương trình bậc nhất", "m.word": "Giải bài toán bằng phương trình" },
  courses: { "math-m1-algebra": { title: "Toán Lớp 7 · Phương trình bậc nhất", world: { name: "Rừng Đại Số", tagline: "Khám phá khu rừng của chữ và biểu thức" } } },
  units: { "math-m1-linear-eq": "Phương trình bậc nhất" },
  lessons: {
    "math-l1": { title: "Tính giá trị của biểu thức", concept: "Thay số vào chữ gọi là **thế**. Kết quả sau khi thế và tính là **giá trị của biểu thức**. Khi thế số âm, hãy đặt trong ngoặc để ít nhầm hơn.", example: r`Khi $x=3$, $2x+1$ bằng $2\times3+1=7$.` },
    "math-l2": { title: "Tính chất của đẳng thức", concept: "Đẳng thức giống như một **chiếc cân**. Cộng, trừ cùng một số vào hai vế, hoặc nhân, chia hai vế cho cùng một số khác 0 thì cân vẫn thăng bằng.", example: r`Trừ $5$ ở cả hai vế của $x+5=9$ ta được $x=4$.` },
    "math-l3": { title: "Giải phương trình bậc nhất", concept: r`Chuyển các số hạng chứa $x$ sang một vế, các số sang vế còn lại (**chuyển vế**). Khi chuyển vế thì đổi dấu. Cuối cùng chia cho hệ số của $x$ là xong!`, example: r`$2x+1=9 \Rightarrow 2x=8 \Rightarrow x=4$` },
    "math-l4": { title: "Giải toán bằng phương trình", concept: r`Với bài toán có lời văn: **đặt ẩn $x$ cho đại lượng cần tìm** → viết đề bài thành phương trình → giải → kiểm tra đáp số có phù hợp với điều kiện không.`, example: r`Gấp $3$ lần một số rồi cộng $2$ được $14$ → $3x+2=14$ → $x=4$` },
  },
  questions: {
    "m-expr-1": Q(r`Khi $x=3$, giá trị của $2x+1$ là?`, [r`Hãy thay $3$ vào vị trí của $x$.`, r`Tính $2\times 3$ trước rồi cộng $1$.`], r`Thế $x=3$ ta được $2\times3+1=6+1=7$.`),
    "m-expr-2": Q(r`Khi $x=-2$, hãy tính giá trị của $3x+4$.`, [r`Khi thế số âm, hãy viết trong ngoặc: $3\times(-2)+4$.`, r`$3\times(-2)=-6$. Cộng thêm $4$ thì được bao nhiêu?`], r`$3\times(-2)+4=-6+4=-2$.`),
    "m-expr-3": Q(r`Khi $a=4,\ b=-1$, hãy tính giá trị của $2a-3b$.`, [r`Thế từng giá trị của $a$ và $b$ để được $2\times4-3\times(-1)$.`, r`Trừ một số âm thành cộng: $8-(-3)$.`], r`$2\times4-3\times(-1)=8+3=11$.`),
    "m-expr-4": Q(r`Khi $x=-1$, giá trị của $x^2+2x$ là?`, [r`$x^2$ là $(-1)\times(-1)$.`, r`Tính $x^2=1$ và $2x=-2$ rồi cộng lại.`], r`$(-1)^2+2\times(-1)=1-2=-1$.`),
    "m-expr-5": Q(r`Khi $x=\dfrac12$, hãy tính giá trị của $4x^2-2x+1$.`, [r`$x^2=\dfrac14$.`, r`Hãy dùng $4\times\dfrac14=1$ và $2\times\dfrac12=1$.`], r`$4\times\dfrac14-2\times\dfrac12+1=1-1+1=1$.`),
    "m-expr-v1": Q(r`Khi $x=5$, hãy tính giá trị của $3x-2$.`, [r`Thế $5$ vào vị trí của $x$.`, r`Hãy tính $3\times5-2$.`], r`$3\times5-2=15-2=13$.`),
    "m-expr-v2": Q(r`Khi $x=-4$, hãy tính giá trị của $2x+9$.`, [r`Hãy viết $2\times(-4)+9$.`, r`$2\times(-4)=-8$.`], r`$2\times(-4)+9=-8+9=1$.`),
    "m-expr-v3": Q(r`Khi $x=-3$, hãy tính giá trị của $4x+5$.`, [r`Hãy tính $4\times(-3)+5$.`, r`$4\times(-3)=-12$.`], r`$4\times(-3)+5=-12+5=-7$.`),
    "m-expr-v4": Q(r`Khi $x=-2$, hãy tính giá trị của $x^2-3x$.`, [r`$x^2$ là $(-2)\times(-2)$.`, r`Hãy tính $4-3\times(-2)$.`], r`$(-2)^2-3\times(-2)=4+6=10$.`),
    "m-prop-1": Q(r`Nếu $a=b$ thì $a+3=b+3$. Đúng hay sai?`, [`Cộng cùng một số vào hai vế thì đẳng thức có còn đúng không?`, `Hãy tưởng tượng đặt thêm cùng một khối lượng vào hai đĩa cân.`], `Cộng cùng một số vào hai vế thì đẳng thức vẫn đúng. Vì vậy đáp án là Đúng (O).`),
    "m-prop-2": Q(r`Trừ $5$ ở cả hai vế của $x+5=9$ thì được?`, [`Trừ cùng một số ở hai vế thì đẳng thức vẫn đúng.`, r`Vế trái thành $x+5-5=x$. Vế phải là $9-5$.`], r`$x+5-5=9-5$ nên $x=4$.`),
    "m-prop-3": Q(r`Nhân cả hai vế của $\dfrac{x}{3}=4$ với $3$ thì được?`, [`Để mất phép chia, hãy nhân với cùng một số.`, r`Vế trái là $\dfrac{x}{3}\times3=x$.`], r`$\dfrac{x}{3}\times3=4\times3$ nên $x=12$.`),
    "m-prop-4": Q(r`Khẳng định nào về tính chất của đẳng thức là KHÔNG đúng? (với $a=b$)`, [`Có một số cần chú ý khi chia.`, r`Điều gì xảy ra nếu $c=0$?`], r`Không thể chia cho $0$, nên chỉ chia hai vế cho $c$ khi $c\neq0$.`, { c: r`$\dfrac{a}{c}=\dfrac{b}{c}$ (c là số bất kỳ)` }),
    "m-prop-5": Q(r`Dùng tính chất của đẳng thức để tìm $x$ trong $2x-3=7$.`, [r`Trước hết cộng $3$ vào hai vế để được $2x=10$.`, `Sau đó chia cả hai vế cho $2$.`.replace("$2$", "2")], r`$2x=10$ nên $x=5$.`),
    "m-prop-v1": Q(r`Nếu $a=b$ thì $a-5=b-5$. Đúng hay sai?`, [`Trừ cùng một số ở hai vế thì đẳng thức có còn đúng không?`, `Hãy tưởng tượng bớt cùng một khối lượng ở hai đĩa cân.`], `Trừ cùng một số ở hai vế thì đẳng thức vẫn đúng.`),
    "m-prop-v2": Q(r`Cộng $2$ vào cả hai vế của $x-2=6$ thì được?`, [`Cộng cùng một số vào hai vế.`, r`$x-2+2=x$.`], r`$x-2+2=6+2$ nên $x=8$.`),
    "m-solve-1": Q(r`Biết $x+7=12$, hãy tìm $x$.`, [r`Chuyển $7$ sang vế phải thì đổi dấu.`, r`$x=12-7$`], r`$x=12-7=5$.`),
    "m-solve-2": Q(r`Biết $3x=-12$, hãy tìm $x$.`, [r`Chia cả hai vế cho $3$.`, r`Hãy tính $-12\div3$.`], r`$x=-12\div3=-4$.`),
    "m-solve-3": Q(r`Biết $2x+1=9$, hãy tìm $x$.`, [r`Trước hết chuyển $+1$ sang vế phải.`, `Ta được $2x=8$. Bây giờ chia hai vế thì được bao nhiêu?`.replace("$2x=8$", "2x=8")], r`$2x=9-1=8$, do đó $x=4$.`),
    "m-solve-4": Q(r`Biết $5x-4=3x+6$, hãy tìm $x$.`, [`Gom các số hạng chứa $x$ sang vế trái, các số sang vế phải (chuyển vế).`, r`$5x-3x=6+4$.`], r`$5x-3x=6+4$, $2x=10$ nên $x=5$.`),
    "m-solve-5": Q(r`Biết $\dfrac{x-1}{2}=\dfrac{x+2}{3}$, hãy tìm $x$.`, [`Nhân hai vế với bội chung nhỏ nhất của mẫu số $2$ và $3$, tức là $6$.`, r`Hãy khai triển $3(x-1)=2(x+2)$.`], r`$3x-3=2x+4$ nên $x=7$.`),
    "m-solve-v1": Q(r`Biết $x-3=8$, hãy tìm $x$.`, [r`Chuyển $-3$ sang vế phải thì thành $+3$.`, r`$x=8+3$`], r`$x=8+3=11$.`),
    "m-solve-v2": Q(r`Biết $4x+3=19$, hãy tìm $x$.`, [r`Trước hết chuyển $+3$ sang vế phải.`, r`$4x=16$`], r`$4x=19-3=16$, do đó $x=4$.`),
    "m-solve-v3": Q(r`Biết $6x-5=2x+15$, hãy tìm $x$.`, [`Gom số hạng chứa $x$ sang vế trái, các số sang vế phải.`, r`$6x-2x=15+5$`], r`$4x=20$ nên $x=5$.`),
    "m-word-1": Q(r`Gấp $3$ lần một số rồi cộng $2$ được $14$. Gọi số đó là $x$, phương trình đúng là?`, [`Hãy viết "gấp 3 lần một số" thành biểu thức trước.`, r`Cộng $2$ vào $3x$ thì được $14$.`], r`Gấp $3$ lần số đó là $3x$, cộng $2$ được $14$ nên $3x+2=14$.`),
    "m-word-2": Q(r`Tổng của hai số tự nhiên liên tiếp là $25$. Hãy tìm số bé.`, [r`Gọi số bé là $x$ thì số lớn là $x+1$.`, r`$x+(x+1)=25$`], r`$2x+1=25$, $2x=24$, $x=12$.`),
    "m-word-3": Q(r`Một quả táo giá $800$ đồng, một quả quýt giá $500$ đồng. Mua $3$ quả táo và $x$ quả quýt hết $3900$ đồng. Hỏi đã mua bao nhiêu quả quýt?`, [r`Tiền táo là $800\times3=2400$ đồng.`, r`$2400+500x=3900$`], r`$500x=1500$ nên $x=3$, tức là $3$ quả quýt.`),
    "m-word-4": Q(r`Hiện nay bố $42$ tuổi, con $10$ tuổi. Sau bao nhiêu năm thì tuổi bố gấp $2$ lần tuổi con?`, [r`Sau $x$ năm, bố $42+x$ tuổi, con $10+x$ tuổi.`, r`$42+x=2(10+x)$`], r`$42+x=20+2x$ nên $x=22$, tức là sau $22$ năm.`),
    "m-word-5": Q(r`Đi từ nhà đến trường với vận tốc $3\,\text{km/h}$ thì lâu hơn đi với vận tốc $4\,\text{km/h}$ là $10$ phút. Quãng đường từ nhà đến trường dài bao nhiêu $\text{km}$?`, [r`Thời gian = quãng đường ÷ vận tốc. $10$ phút là $\dfrac16$ giờ.`, r`Hãy giải $\dfrac{x}{3}-\dfrac{x}{4}=\dfrac16$.`], r`$\dfrac{x}{12}=\dfrac16$ nên $x=2$, quãng đường dài $2\,\text{km}$.`),
    "m-word-v1": Q(r`Gấp $2$ lần một số rồi cộng $5$ được $17$. Hãy tìm số đó.`, [r`Gọi số đó là $x$ thì $2x+5=17$.`, r`$2x=12$`], r`$2x=12$ nên $x=6$.`),
    "m-word-v2": Q(r`Tổng của hai số tự nhiên liên tiếp là $31$. Hãy tìm số bé.`, [r`Gọi số bé là $x$ thì $x+(x+1)=31$.`, r`$2x=30$`], r`$2x+1=31$ nên $x=15$.`),
    "m-diag-int1": Q(r`Hãy tính $(-3)+(-5)$.`, [`Cộng hai số cùng dấu thì cộng giá trị tuyệt đối và giữ nguyên dấu.`, r`Lấy $3+5=8$ rồi thêm dấu âm.`], r`$(-3)+(-5)=-8$.`),
    "m-diag-int2": Q(r`Hãy tính $-12\div3+5$.`, [`Tính phép chia trước.`, r`$-12\div3=-4$.`], r`$-4+5=1$.`),
    "m-diag-expr1": Q(r`Khi $x=-3$, hãy tính giá trị của $2x+7$.`, [r`Hãy viết $2\times(-3)+7$.`, r`$2\times(-3)=-6$`], r`$-6+7=1$.`),
    "m-diag-expr2": Q(r`Khi $x=2$, hãy tính giá trị của $x^2-3x$.`, [r`$x^2=4$, $3x=6$.`, r`$4-6$`], r`$2^2-3\times2=4-6=-2$.`),
    "m-diag-prop1": Q(r`Cộng $4$ vào cả hai vế của $x-4=6$ thì được?`, [`Cộng cùng một số vào hai vế thì đẳng thức vẫn đúng.`, r`$x-4+4=x$`], r`$x=6+4=10$.`),
    "m-diag-prop2": Q(r`Từ $2x=10$, cách dùng tính chất của đẳng thức nào là đúng?`, [r`Muốn bỏ số $2$ đứng trước $x$ thì làm thế nào?`, `Số đang nhân thì bỏ đi bằng phép chia.`], r`Chia cả hai vế cho hệ số $2$ của $x$ ta được $x=5$.`, { a: r`Chia cả hai vế cho $2$`, b: r`Cộng $2$ vào cả hai vế`, c: r`Trừ $10$ ở cả hai vế`, d: r`Nhân cả hai vế với $0$` }),
    "m-diag-solve1": Q(r`Biết $2x-5=9$, hãy tìm $x$.`, [r`Chuyển $-5$ sang vế phải.`, r`$2x=14$`], r`$2x=14$ nên $x=7$.`),
    "m-diag-solve2": Q(r`Biết $3x+4=x+12$, hãy tìm $x$.`, [r`Gom số hạng chứa $x$ sang vế trái.`, r`$3x-x=12-4$`], r`$2x=8$ nên $x=4$.`),
    "m-diag-word1": Q(r`Gấp $4$ lần một số rồi trừ $3$ được $17$. Hãy tìm số đó.`, [r`Gọi số đó là $x$ thì $4x-3=17$.`, r`$4x=20$`], r`$4x=20$ nên $x=5$.`),
    "m-diag-word2": Q(r`Tổng của ba số tự nhiên liên tiếp là $42$. Hãy tìm số bé nhất.`, [r`Gọi số bé nhất là $x$ thì ba số là $x,\ x+1,\ x+2$.`, r`$3x+3=42$`], r`$3x+3=42$, $3x=39$, $x=13$.`),
  },
};

const O = (obj) => obj;
export const viDemoEnglish = {
  skills: { "e.vocab": "Từ vựng hằng ngày", "e.be": "Động từ be", "e.pres": "Động từ thường ở thì hiện tại", "e.plural": "Danh từ số nhiều", "e.order": "Sắp xếp câu" },
  courses: { "en-m1-basics": { title: "Tiếng Anh Lớp 7 · Ngữ pháp và từ vựng cơ bản", world: { name: "Làng Từ Vựng", tagline: "Bắt đầu từ ngôi làng của từ và câu" } } },
  units: { "en-m1-unit1": "Từ vựng và ngữ pháp cơ bản" },
  lessons: {
    "en-l1": { title: "Học từ vựng hằng ngày", concept: "Những từ hay dùng sẽ được nhớ lâu nếu bạn học **âm thanh + nghĩa + cách viết** cùng lúc. Hãy bấm nút loa để nghe phát âm.", example: "library = thư viện / desk = bàn học / milk = sữa" },
    "en-l2": { title: "Động từ be: am / are / is", concept: "Động từ be thay đổi theo chủ ngữ. **I → am**, **he / she / it → is**, **you / we / they → are**.", example: "I am a student. She is my friend. They are in the classroom." },
    "en-l3": { title: "Động từ thường ở thì hiện tại", concept: "Khi chủ ngữ là **he / she / it (ngôi thứ ba số ít)** thì thêm **-s / -es** vào động từ. Kết thúc bằng -ch, -sh, -s, -x, -o thì thêm -es; phụ âm + y thì đổi y thành i rồi thêm -es!", example: "go → goes / watch → watches / study → studies" },
    "en-l4": { title: "Số nhiều và đặt câu", concept: "Danh từ từ hai trở lên thường thêm **-s**, kết thúc bằng -x thì thêm **-es**, danh từ số nhiều bất quy tắc phải học riêng. Câu có thứ tự **chủ ngữ → động từ → phần còn lại**.", example: "book → books / box → boxes / child → children" },
  },
  questions: {
    "e-vocab-1": Q("'library' nghĩa là gì?", ["li-brar-y, hãy nghĩ đến nơi có nhiều sách.", "Đó là nơi để mượn sách."], "library nghĩa là 'thư viện'.", { a: "thư viện", b: "bệnh viện", c: "nhà hàng", d: "công viên" }),
    "e-vocab-2": Q("Từ nào sau đây có nghĩa là 'trường học'?", ["Đó là từ bắt đầu bằng chữ s.", "Đó là nơi học sinh đến để học."], "school nghĩa là 'trường học'."),
    "e-vocab-3": Q("Hãy viết 'cái bàn học' bằng tiếng Anh.", ["Từ có bốn chữ cái, bắt đầu bằng d.", "d _ s k"], "'Cái bàn học' là desk."),
    "e-vocab-4": Q("I drink ____ in the morning. (sữa)", ["Hãy nghĩ xem 'sữa' là gì trong tiếng Anh.", "m _ l k"], "I drink milk in the morning. (Mình uống sữa vào buổi sáng.)"),
    "e-vocab-5": Q("She is very ____. She always helps her friends.", ["Người luôn giúp đỡ bạn bè là người như thế nào?", "Hãy chọn từ có nghĩa là 'tốt bụng'."], "Vì ngữ cảnh là 'luôn giúp đỡ bạn bè' nên kind (tốt bụng) là phù hợp."),
    "e-vocab-v1": Q("'teacher' nghĩa là gì?", ["Đó là người dạy chúng ta ở trường.", "teach (dạy) + er (người)"], "teacher nghĩa là 'giáo viên'.", { a: "giáo viên", b: "bác sĩ", c: "cảnh sát", d: "đầu bếp" }),
    "e-vocab-v2": Q("Hãy viết 'cái cặp' bằng tiếng Anh.", ["Từ có ba chữ cái, bắt đầu bằng b.", "b _ g"], "'Cái cặp' là bag."),
    "e-be-1": Q("I ____ a student. (chọn am / are / is)", ["Có một động từ be dùng với chủ ngữ I.", "Sau I là am."], "I luôn đi với am: I am a student."),
    "e-be-2": Q("She ____ my friend.", ["Chủ ngữ She là ngôi thứ ba số ít.", "Động từ be dùng với he / she / it là gì?"], "Với ngôi thứ ba số ít (She) ta dùng is: She is my friend."),
    "e-be-3": Q("They ____ in the classroom.", ["They là chủ ngữ số nhiều.", "Chủ ngữ số nhiều (we, you, they) dùng are."], "They là số nhiều nên dùng are: They are in the classroom."),
    "e-be-4": Q("My brother ____ tall. (am / are / is)", ["My brother là một người. Đó là ngôi thứ mấy?", "Ngôi thứ ba số ít → is"], "My brother = he nên dùng is: My brother is tall."),
    "e-be-5": Q("Câu nào sau đây đúng?", ["Hãy kiểm tra từng cặp chủ ngữ và động từ be.", "I-am, you-are, he-is, we-are"], "Chỉ We are ready. có chủ ngữ và động từ be khớp nhau."),
    "e-be-v1": Q("You ____ smart. (am / are / is)", ["You rất đặc biệt: dù số ít vẫn dùng cùng một động từ be.", "you-are"], "You luôn đi với are: You are smart."),
    "e-be-v2": Q("It ____ a cat.", ["It là ngôi thứ ba số ít.", "he/she/it → is"], "It is a cat."),
    "e-pres-1": Q("He ____ to school every day.", ["He là ngôi thứ ba số ít.", "Hãy thêm -s/-es vào động từ thường."], "Thì hiện tại, ngôi thứ ba số ít: go → goes."),
    "e-pres-2": Q("She ____ (watch) TV at night.", ["watch kết thúc bằng -ch.", "Động từ kết thúc bằng -ch thì thêm -es."], "watch → watches (kết thúc bằng -ch, -sh, -s, -x, -o thì thêm -es)."),
    "e-pres-3": Q("My dad ____ coffee every morning.", ["My dad = he.", "'Mỗi sáng' là thói quen ở hiện tại."], "Thói quen dùng thì hiện tại, chủ ngữ ngôi thứ ba số ít nên là drinks."),
    "e-pres-4": Q("Câu 'She study English.' là một câu đúng. Đúng hay sai?", ["She là ngôi thứ ba số ít. Động từ cần thêm gì?", "study kết thúc bằng phụ âm + y."], "Động từ kết thúc bằng phụ âm + y thì đổi y thành i rồi thêm -es: She studies English."),
    "e-pres-5": Q("The baby ____ (cry) a lot.", ["cry kết thúc bằng phụ âm + y.", "Đổi y thành i rồi thêm es."], "cry → cries."),
    "e-pres-v1": Q("He ____ (play) soccer on Sundays.", ["Động từ kết thúc bằng nguyên âm + y thì chỉ thêm -s.", "play + s"], "play → plays (nguyên âm + y chỉ thêm -s)."),
    "e-pres-v2": Q("She ____ her homework after school.", ["do cũng đổi dạng ở ngôi thứ ba số ít.", "do → does"], "Ngôi thứ ba số ít: do → does."),
    "e-plural-1": Q("Số nhiều của 'book' là?", ["Hầu hết danh từ chỉ cần thêm -s.", "book + s"], "Số nhiều theo quy tắc: book → books."),
    "e-plural-2": Q("one box → two ____", ["box kết thúc bằng -x.", "Danh từ kết thúc bằng -x thì thêm -es."], "box → boxes."),
    "e-plural-3": Q("Hãy viết số nhiều của 'child'.", ["Đây là số nhiều bất quy tắc.", "child + ren"], "child → children (bất quy tắc)."),
    "e-order-1": Q("Bấm các từ theo đúng thứ tự để tạo thành câu.", ["Câu bắt đầu theo thứ tự 'ai → làm gì'.", "Bắt đầu bằng chủ ngữ She."], "She reads a book every day. (Cô ấy đọc sách mỗi ngày.)"),
    "e-order-2": Q("Bấm các từ theo đúng thứ tự để tạo thành câu.", ["Chủ ngữ là 'My mother'.", "Tính từ delicious đứng trước danh từ soup."], "My mother makes delicious soup. (Mẹ mình nấu món súp ngon.)"),
    "e-plural-v1": Q("Số nhiều của 'city' là?", ["Đây là danh từ kết thúc bằng phụ âm + y.", "Đổi y thành i rồi thêm -es."], "city → cities."),
    "e-order-v1": Q("Bấm các từ theo đúng thứ tự để tạo thành câu.", ["Bắt đầu bằng chủ ngữ We.", "Sau We là động từ."], "We play games. (Chúng mình chơi trò chơi.)"),
    "e-diag-vocab1": Q("'apple' nghĩa là gì?", ["Đây là tên một loại quả. Thường có màu đỏ.", "a-pp-le"], "apple nghĩa là 'quả táo'.", { a: "quả táo", b: "quả chuối", c: "quả nho", d: "quả dưa hấu" }),
    "e-diag-vocab2": Q("Hãy viết 'cửa sổ' bằng tiếng Anh.", ["Bắt đầu bằng chữ w.", "w _ n d _ w"], "'Cửa sổ' là window."),
    "e-diag-be1": Q("We ____ friends. (am / are / is)", ["We là chủ ngữ số nhiều.", "we-are"], "We are friends."),
    "e-diag-be2": Q("____ your parents at home?", ["your parents là số nhiều.", "Trong câu hỏi, động từ be được đưa lên đầu."], "Chủ ngữ số nhiều → Are your parents at home?"),
    "e-diag-pres1": Q("She ____ music.", ["She là ngôi thứ ba số ít.", "Thêm s vào cuối động từ."], "She likes music."),
    "e-diag-pres2": Q("He ____ (go) to work by bus.", ["Động từ kết thúc bằng -o.", "go + es"], "go → goes."),
    "e-diag-plural1": Q("Số nhiều của 'leaf' là?", ["Danh từ kết thúc bằng -f thường đổi f thành v.", "f → ves"], "leaf → leaves."),
    "e-diag-order1": Q("Bấm các từ theo đúng thứ tự để tạo thành câu.", ["Bắt đầu bằng chủ ngữ.", "Chủ ngữ → động từ → tân ngữ"], "She likes dogs."),
    "e-diag-pres3": Q("Which sentence is correct?", ["Động từ kết thúc bằng -ch.", "-es"], "watch → watches."),
  },
};
void O;
