import type { Site } from "@/lib/learn/types";

/**
 * The site's logo: the LIFE.HELP logo with MATH / ENGLISH set in the empty band above "LIFE"
 * (public/logos/logo-<site>.png, generated by scripts/generate_learn_logos.js). The visible mark is the image; the site name stays
 * available to screen readers (and tests) as hidden text.
 */
export function BrandLogo({ site, name, size = 44 }: { site: Site; name: string; size?: number }) {
  return (
    <>
      {/* eslint-disable-next-line @next/next/no-img-element -- a small static brand image; no image optimisation pipeline is involved */}
      <img className="l-logo" src={`/logos/logo-${site}.png`} alt="" width={size} height={size} decoding="async" />
      <span className="l-sr">{name}</span>
    </>
  );
}
