/**
 * Canonical Korean of every English reading passage (keyed by the exact English passage as it appears in the question prompt; the English
 * stays in the question). `PASSAGE_KO[passage][i]` is the Korean of sentence i of `splitSentences(passage)` (lib/learn/listen/segments.ts).
 * SERVER ONLY: a passage's Korean helps answer its question, so the API sends it with the attempt feedback once the question is solved or
 * revealed, never before (tests/learn/listening-content.test.ts fails if a client component imports this module).
 * Authored and reviewed for LIFE.HELP (docs/learning/english-bilingual-listening-inventory.md); never machine-translated at runtime.
 */
export const PASSAGE_KO: Readonly<Record<string, readonly string[]>> = {
  // ---- elementary (E1-E6)
  "Mina has a cat. The cat is white.": ["미나는 고양이가 있어요.", "그 고양이는 하얀색이에요."],
  "Tom likes apples. He eats an apple every day.": ["톰은 사과를 좋아해요.", "그는 매일 사과를 하나 먹어요."],
  "I have a bag. It is blue.": ["나는 가방이 있어요.", "그것은 파란색이에요."],
  "Ben has two balls. One is red. One is blue.": ["벤은 공이 두 개 있어요.", "하나는 빨간색이에요.", "하나는 파란색이에요."],
  "Amy has a dog. The dog is brown.": ["에이미는 개가 있어요.", "그 개는 갈색이에요."],
  "I like milk. I drink milk every morning.": ["나는 우유를 좋아해요.", "나는 매일 아침 우유를 마셔요."],
  "Sam has a ball. The ball is green.": ["샘은 공이 있어요.", "그 공은 초록색이에요."],
  "Jin gets up at seven. He brushes his teeth. Then he eats breakfast.": ["진은 7시에 일어나요.", "그는 이를 닦아요.", "그다음에 그는 아침을 먹어요."],
  "Yesterday Mina visited her grandmother. They cooked dinner together. It was fun.": ["어제 미나는 할머니를 찾아갔어요.", "그들은 함께 저녁을 요리했어요.", "재미있었어요."],
  "Today is Sunday. Mina goes to the park with her dog. The dog runs fast. Then Mina eats a sandwich under a big tree.": ["오늘은 일요일이에요.", "미나는 자기 개와 함께 공원에 가요.", "그 개는 빨리 달려요.", "그다음에 미나는 큰 나무 아래에서 샌드위치를 먹어요."],
  "Ken lives in Busan. He has two sisters. His older sister is a teacher. His younger sister is going to start school next month. On weekends, they usually go to the beach.": ["켄은 부산에 살아요.", "그는 여자 형제가 두 명 있어요.", "그의 누나는 선생님이에요.", "그의 여동생은 다음 달에 학교에 들어갈 거예요.", "주말에 그들은 보통 해변에 가요."],
  "Last Saturday, Jina and her brother went to a science museum. They saw a big dinosaur and learned about space. Jina was tired because they walked a lot, but she was very happy. Next weekend, they are going to visit a zoo.": ["지난 토요일에 지나는 남자 형제와 함께 과학관에 갔어요.", "그들은 큰 공룡을 보고 우주에 대해 배웠어요.", "그들이 많이 걸어서 지나는 피곤했지만, 아주 행복했어요.", "다음 주말에 그들은 동물원에 갈 거예요."],
  "I have two red apples and one green apple.": ["나는 빨간 사과 두 개와 초록 사과 한 개가 있어요."],
  "Tom's bag is the color of the sky.": ["톰의 가방은 하늘과 같은 색이에요."],
  "I write with it. It has a point. It is in my bag.": ["나는 그것으로 글씨를 써요.", "그것은 끝이 뾰족해요.", "그것은 내 가방 안에 있어요."],
  "Stand up and close the door.": ["일어나서 문을 닫으세요."],
  "I see a big animal. It has a long nose. It is gray.": ["나는 큰 동물을 봐요.", "그것은 코가 길어요.", "그것은 회색이에요."],
  "Mina has two pets. One says \"woof\". The other lives in water.": ["미나는 반려동물이 두 마리 있어요.", "한 마리는 \"멍멍\" 하고 소리를 내요.", "다른 한 마리는 물속에 살아요."],
  "Sam has a dog. The dog is brown. It likes to run in the park.": ["샘은 개가 있어요.", "그 개는 갈색이에요.", "그 개는 공원에서 달리는 것을 좋아해요."],
  "Tom and Mina are friends. They play soccer together. He is fast, and she is smart.": ["톰과 미나는 친구예요.", "그들은 함께 축구를 해요.", "그는 빠르고, 그녀는 똑똑해요."],
  "The dog is under the table. It is sleeping.": ["개가 탁자 아래에 있어요.", "그 개는 자고 있어요."],
  "Jin gets up at seven. He eats breakfast at seven thirty. He goes to school at eight.": ["진은 7시에 일어나요.", "그는 7시 30분에 아침을 먹어요.", "그는 8시에 학교에 가요."],
  "Mina goes to bed at ten. She gets up at six.": ["미나는 10시에 잠자리에 들어요.", "그녀는 6시에 일어나요."],
  "Mina has a new bike. She rides it to school every day. Today it is raining, so she walks.": ["미나는 새 자전거가 있어요.", "그녀는 매일 그것을 타고 학교에 가요.", "오늘은 비가 와서 그녀는 걸어가요."],
  "The ball is in the box. The box is under the bed.": ["공은 상자 안에 있어요.", "상자는 침대 아래에 있어요."],
  "The book is on the desk. The pen is under the desk.": ["책은 책상 위에 있어요.", "펜은 책상 아래에 있어요."],
  "Tom is hungry. He opens the refrigerator, but it is empty. So he goes to the store and buys bread and milk.": ["톰은 배가 고파요.", "그는 냉장고를 열지만, 냉장고는 비어 있어요.", "그래서 그는 가게에 가서 빵과 우유를 사요."],
  "Tom is 150 cm tall. Ben is 145 cm tall. Mina is 155 cm tall.": ["톰은 키가 150cm예요.", "벤은 키가 145cm예요.", "미나는 키가 155cm예요."],
  "Mina wants to buy a gift for her mother. She has 10,000 won. A scarf costs 8,000 won and a hat costs 12,000 won. She buys the scarf.": ["미나는 엄마에게 드릴 선물을 사고 싶어요.", "그녀는 10,000원이 있어요.", "스카프는 8,000원이고 모자는 12,000원이에요.", "그녀는 스카프를 사요."],
  "It was a very tiny puppy. I could hold it in one hand.": ["그것은 아주 작은 강아지였어요.", "나는 그 강아지를 한 손으로 안을 수 있었어요."],
  "Last week, Jiho joined a school cooking club. At first, he burned the eggs and the kitchen smelled bad. But he did not give up. After two weeks of practice, he made a perfect omelet for his family.": ["지난주에 지호는 학교 요리 동아리에 들어갔어요.", "처음에 그는 달걀을 태웠고 부엌에서 나쁜 냄새가 났어요.", "하지만 그는 포기하지 않았어요.", "2주 동안 연습한 뒤에 그는 가족을 위해 완벽한 오믈렛을 만들었어요."],
  // ---- secondary (M2-H3)
  "Jisu moved to Daegu in 2021. It is 2026 now.": ["지수는 2021년에 대구로 이사했다.", "지금은 2026년이다."],
  "Ben likes swimming. He wants to join the swimming team, but he has not decided when to start.": ["벤은 수영을 좋아한다.", "그는 수영 팀에 들어가고 싶지만, 언제 시작할지는 아직 정하지 않았다."],
  "Amy is 150 cm tall. Ben is 158 cm tall. Chris is 154 cm tall.": ["에이미는 키가 150cm이다.", "벤은 키가 158cm이다.", "크리스는 키가 154cm이다."],
  "A bike costs $120. A scooter costs $180. A skateboard costs $90.": ["자전거는 120달러이다.", "스쿠터는 180달러이다.", "스케이트보드는 90달러이다."],
  "Mina joined the school choir last month. She practices every Tuesday and Thursday after school. Next week, the choir will sing at the city festival. Mina is excited but also a little nervous.": ["미나는 지난달에 학교 합창단에 들어갔다.", "그녀는 매주 화요일과 목요일 방과 후에 연습한다.", "다음 주에 합창단은 시 축제에서 노래할 것이다.", "미나는 신이 나면서도 조금 긴장된다."],
  "Many students use their phones during class. This makes it hard to listen to the teacher. Some schools now ask students to keep their phones in a box until lunch. As a result, students talk more with each other.": ["많은 학생들이 수업 중에 휴대폰을 사용한다.", "이것은 선생님 말씀을 듣기 어렵게 만든다.", "이제 일부 학교는 학생들에게 점심시간까지 휴대폰을 상자에 보관하도록 요청한다.", "그 결과, 학생들은 서로 더 많이 대화한다."],
  "Tom doesn't have a car, so he takes the bus every day.": ["톰은 차가 없어서 매일 버스를 탄다."],
  "The girl dancing on the stage is my cousin. The song played at the party was her favorite.": ["무대 위에서 춤추고 있는 소녀는 내 사촌이다.", "파티에서 연주된 노래는 그녀가 가장 좋아하는 곡이었다."],
  "Dear Mr. Kim, I am writing to ask about the swimming class on Saturday. Last week, the class was cancelled because of heavy rain. Could you tell me if it will be held this Saturday? Thank you. Best regards, Hana": ["김 선생님께, 토요일 수영 수업에 대해 여쭤보려고 글을 씁니다.", "지난주에는 폭우 때문에 수업이 취소되었습니다.", "이번 토요일에는 수업이 열리는지 알려 주시겠어요?", "감사합니다.", "하나 드림"],
  "Sam checked the sky again and put on his raincoat. He took an umbrella from the closet, too. Then he looked at his watch and hurried out the door.": ["샘은 하늘을 다시 확인하고 비옷을 입었다.", "그는 옷장에서 우산도 꺼냈다.", "그런 다음 그는 시계를 보고 서둘러 문밖으로 나갔다."],
  "Yuna started playing the piano in 2018. She still plays it every day. It is 2026 now.": ["유나는 2018년에 피아노를 치기 시작했다.", "그녀는 지금도 매일 피아노를 친다.", "지금은 2026년이다."],
  "People often think that being busy means being successful. However, research shows that people who take regular breaks solve problems faster and make fewer mistakes. Rest is not a waste of time; it is part of good work.": ["사람들은 흔히 바쁜 것이 성공한 것이라고 생각한다.", "그러나 연구에 따르면 규칙적으로 쉬는 사람들이 문제를 더 빨리 해결하고 실수를 더 적게 한다.", "휴식은 시간 낭비가 아니라 좋은 일의 일부이다."],
  "Ann didn't wear a coat, so she caught a cold.": ["앤은 코트를 입지 않아서 감기에 걸렸다."],
  "No matter how tired Jin is, he always finishes his homework.": ["진은 아무리 피곤해도 항상 숙제를 끝낸다."],
  "Lena was reluctant to speak in public. She never raised her hand, and her voice shook whenever she presented.": ["레나는 사람들 앞에서 말하기를 꺼렸다.", "그녀는 한 번도 손을 들지 않았고, 발표할 때마다 목소리가 떨렸다."],
  "I can't bear this noise any longer.": ["나는 이 소음을 더 이상 참을 수 없다."],
  "The scientist's claim was met with skepticism. Many experts doubted the results and asked for more evidence.": ["그 과학자의 주장은 회의적인 반응에 부딪혔다.", "많은 전문가들이 그 결과를 의심했고 더 많은 증거를 요구했다."],
  "The new law is controversial. Some people support it strongly, while others oppose it just as strongly.": ["새 법은 논란이 많다.", "어떤 사람들은 그것을 강하게 지지하는 반면, 다른 사람들은 그만큼 강하게 반대한다."],
  "Honeybees communicate by dancing. When a bee finds food, it returns to the hive and performs a 'waggle dance'. The angle of the dance shows the direction of the food, and its length shows the distance. In this way, the whole colony can find food quickly.": ["꿀벌은 춤으로 의사소통한다.", "벌은 먹이를 찾으면 벌집으로 돌아와 '8자 춤'을 춘다.", "춤의 각도는 먹이의 방향을 나타내고, 춤의 길이는 거리를 나타낸다.", "이런 방식으로 무리 전체가 먹이를 빨리 찾을 수 있다."],
  "Attention, all residents: the water supply will be turned off on Friday from 9 a.m. to 1 p.m. for pipe repairs. Please store enough water in advance. We apologize for any inconvenience.": ["주민 여러분, 알려 드립니다: 배관 수리를 위해 금요일 오전 9시부터 오후 1시까지 물 공급이 중단됩니다.", "미리 물을 충분히 받아 두시기 바랍니다.", "불편을 드려 죄송합니다."],
  "(A) Then she put the cake in the oven. (B) First, Mia mixed flour, eggs, and sugar.": ["(A) 그런 다음 그녀는 케이크를 오븐에 넣었다.", "(B) 먼저 미아는 밀가루, 달걀, 설탕을 섞었다."],
  "(A) As a result, the fish population slowly recovered. (B) Last year, the town banned fishing in the river for six months. (C) For years, too many fish had been caught, and the river was almost empty.": ["(A) 그 결과, 물고기 개체 수가 서서히 회복되었다.", "(B) 작년에 그 마을은 6개월 동안 강에서 낚시를 금지했다.", "(C) 수년 동안 너무 많은 물고기가 잡혀서 강은 거의 텅 비어 있었다."],
  "Sam was nervous about his first day at the new school. (A) He took a deep breath and walked in. (B) However, a friendly girl smiled and showed him the way. (C) At the gate, he saw crowds of strange faces.": ["샘은 새 학교에서의 첫날이 긴장되었다.", "(A) 그는 심호흡을 하고 걸어 들어갔다.", "(B) 그러나 한 친절한 소녀가 미소를 지으며 그에게 길을 알려 주었다.", "(C) 정문에서 그는 낯선 얼굴들이 무리 지어 있는 것을 보았다."],
  "(A) Finally, they reached the top. (B) At dawn, the group began to climb.": ["(A) 마침내 그들은 정상에 도착했다.", "(B) 새벽에 그 일행은 오르기 시작했다."],
  "(A) After that, we had dinner. (B) First, we visited the museum.": ["(A) 그다음에 우리는 저녁을 먹었다.", "(B) 먼저 우리는 박물관을 방문했다."],
  "Jack missed the deadline again. His boss said, \"This is the last straw.\" Jack was fired the next day.": ["잭은 또 마감 기한을 놓쳤다.", "그의 상사가 말했다. \"이제 더는 못 참겠어.\"", "잭은 다음 날 해고되었다."],
  "Many cities are building green roofs, which are roofs covered with plants. These roofs keep buildings cooler in summer and warmer in winter, so they reduce energy use. They also absorb rainwater, which helps prevent floods. Although green roofs cost more to build, they save money in the long run.": ["많은 도시들이 식물로 덮인 지붕, 즉 녹색 지붕을 만들고 있다.", "이 지붕은 여름에는 건물을 더 시원하게, 겨울에는 더 따뜻하게 유지해서 에너지 사용을 줄인다.", "이 지붕은 또한 빗물을 흡수해서 홍수를 막는 데 도움이 된다.", "녹색 지붕은 짓는 데 비용이 더 들지만, 장기적으로는 돈을 절약해 준다."],
};
