# scripts/build_el_pt_complete.py
import json
import os

MESSAGES_DIR = os.path.join(os.path.dirname(__file__), '..', 'messages')

with open(os.path.join(MESSAGES_DIR, 'en.json'), 'r', encoding='utf-8') as f:
    en = json.load(f)

# Load already started script
exec(open(os.path.join(os.path.dirname(__file__), 'create_pt_el.py'), encoding='utf-8').read())

# Tech
pt['tech'] = {
  "title": "Strefa Especialista",
  "login": "Login do Especialista",
  "headline": "Conecte-se diretamente com clientes da sua região",
  "customers": "Clientes",
  "requests": "Chamados",
  "mobile": "Acesso Fácil por Celular",
  "settlement": "Pagamento Rápido",
  "register": "Cadastro de Especialista",
  "helper": "Especialista",
  "helperLogin": "Login de Especialista",
  "officialPartners": "Parceiros Oficiais LIFE.HELP",
  "subheadline": "Sem burocracia ou necessidade de documentos complexos. Obtenha uma chave de acesso segura válida por 3 meses com apenas seu número de celular.",
  "startHelper": "Comece como Especialista",
  "hotline": "Linha Direta",
  "signInDesc": "Digite seu número de celular cadastrado para entrar na sua strefa de trabalho.",
  "invalidPhoneError": "Por favor, insira um número de telefone válido.",
  "phoneLabel": "Número de Celular",
  "getCode": "Obter Código de Acesso",
  "backToHome": "Voltar à Página do Especialista",
  "helperService": "Serviço de Especialistas LIFE.HELP",
  "verifyAndLogin": "Verificar e Entrar como Especialista",
  "codeSentSuccess": "recebeu o código de verificação.",
  "changePhone": "Alterar número de celular",
  "statusActiveShort": "Disponível para Atendimento",
  "statusPausedShort": "Temporariamente Pausado",
  "clickToToggle": "Clique para alternar",
  "securitySessionNotice": "Sessão de Segurança de 3 Meses: chave de acesso aleatória de 90 dias emitida via celular",
  "securitySessionExpiry": "Expiração da Sessão de Segurança",
  "securitySessionExpired": "Sessão de Segurança Expirada",
  "autoMaintainedDays": "dias mantidos automaticamente",
  "operatingRegions": "Regiões de Atendimento",
  "instantDispatchConnected": "Conexão Imediata com o Cliente",
  "registeredServices": "Serviços Cadastrados",
  "categoriesRegisteredCount": "categorias registradas",
  "editableInWorkspace": "Editável na Área de Trabalho",
  "openWorkspaceBtn": "Gerenciar Minha Área de Trabalho",
  "bilingualMode": "Bilíngue (Coreano)",
  "monolingualMode": "Um só idioma",
  "bilingualToggleHint": "Modo bilíngue (Clique para modo de um idioma)",
  "hotlineNotice": "Linha Direta do Sistema Principal",
  "monolingualToggleHint": "Modo de um idioma (Clique para modo bilíngue)",
  "headlineLead": "Conecte-se diretamente com clientes na sua região",
  "actAsHelper": "Trabalhe como especialista profissional",
  "helperPortal": "Portal do Especialista",
  "registerTab": "Cadastrar Novo Especialista",
  "loginTab": "Login de Especialista Cadastrado",
  "newHelperRegTitle": "Cadastro de Novo Especialista (Acesso Seguro de 3 Meses)",
  "existingHelperLoginTitle": "Login de Especialista Existente",
  "newHelperRegDesc": "Sem necessidade de documentos complexos. Trabalhe livremente por 3 meses apenas com seu número de celular.",
  "existingHelperLoginDesc": "Insira sua chave de acesso de 3 meses para entrar diretamente no seu painel.",
  "accessKeyLabel": "Chave de Acesso Dedicada de 3 Meses",
  "loginWithAccessKey": "Entrar com Chave de Segurança (Válida por 90 dias)",
  "loginKeyNotice": "Insira a chave de 3 meses recebida por SMS para acessar sua área de trabalho imediatamente.",
  "lostCodeBtn": "Perdeu seu código?",
  "reissueCodeTitle": "Reemitir Chave de 3 Meses pelo Telefone",
  "getAccessKeyBtn": "Obter Chave de Segurança de 3 Meses",
  "registerAndStart": "Cadastrar e Iniciar Atendimentos",
  "selectServices": "Selecionar Categorias de Serviços",
  "selectServicesDesc": "Selecione todas as categorias que pode atender (você pode editar depois).",
  "selectedCount": " selecionadas",
  "helperNameLabel": "Nome ou Apelido do Especialista",
  "agreeTerms": "Li os regulamentos e diretrizes de segurança da LIFE.HELP e me comprometo a prestar um serviço pontual e cortês.",
  "keySentNotice": "Chave de acesso enviada com sucesso por SMS",
  "issuedAccessKey": "Chave de Acesso de 3 Meses Emitida",
  "copy": "Copiar",
  "copied": "Copiado!",
  "backToTechHome": "Voltar ao Início do Especialista",
  "verifying": "Verificando...",
  "changePhoneBtn": "Alterar",
  "enterAccessKeyError": "Por favor, insira sua chave de segurança de 3 meses.",
  "enterNameError": "Por favor, insira seu nome ou apelido de atendimento.",
  "selectServiceError": "Selecione pelo menos uma categoria de serviço.",
  "agreeTermsError": "É necessário concordar com os regulamentos e regras de segurança."
}

el['tech'] = {
  "title": "Χώρος Εργασίας Τεχνικού",
  "login": "Σύνδεση Τεχνικού",
  "headline": "Συνδεθείτε απευθείας με πελάτες στην περιοχή σας",
  "customers": "Πελάτες",
  "requests": "Αιτήματα",
  "mobile": "Εύκολη Πρόσβαση από Κινητό",
  "settlement": "Γρήγορη Εκκαθάριση",
  "register": "Εγγραφή Τεχνικού",
  "helper": "Ειδικός Τεχνικός",
  "helperLogin": "Σύνδεση Τεχνικού",
  "officialPartners": "Επίσημοι Συνεργάτες LIFE.HELP",
  "subheadline": "Χωρίς πολύπλοκα έγγραφα ή γραφειοκρατία. Αποκτήστε κωδικό ασφαλούς πρόσβασης διάρκειας 3 μηνών μόνο με τον αριθμό του κινητού σας.",
  "startHelper": "Ξεκινήστε ως Ειδικός Τεχνικός",
  "hotline": "Γραμμή Άμεσης Βοήθειας",
  "signInDesc": "Εισαγάγετε τον καταχωρημένο αριθμό κινητού σας για να συνδεθείτε.",
  "invalidPhoneError": "Παρακαλώ εισαγάγετε έγκυρο αριθμό τηλεφώνου.",
  "phoneLabel": "Αριθμός Κινητού",
  "getCode": "Λήψη Κωδικού Πρόσβασης",
  "backToHome": "Επιστροφή στην Αρχική Τεχνικού",
  "helperService": "Υπηρεσία Τεχνικών LIFE.HELP",
  "verifyAndLogin": "Επαλήθευση & Σύνδεση Τεχνικού",
  "codeSentSuccess": "έχει σταλεί κωδικός επαλήθευσης.",
  "changePhone": "Αλλαγή αριθμού τηλεφώνου",
  "statusActiveShort": "Διαθέσιμος για Αποστολή",
  "statusPausedShort": "Σε Προσωρινή Παύση",
  "clickToToggle": "Κάντε κλικ για εναλλαγή",
  "securitySessionNotice": "Συνεδρία Ασφαλείας 3 Μηνών: τυχαίος κωδικός πρόσβασης 90 ημερών μέσω κινητού",
  "securitySessionExpiry": "Λήξη Συνεδρίας Ασφαλείας",
  "securitySessionExpired": "Η Συνεδρία Ασφαλείας Έληξε",
  "autoMaintainedDays": "ημέρες αυτόματης διατήρησης",
  "operatingRegions": "Περιοχές Εξυπηρέτησης",
  "instantDispatchConnected": "Άμεση Σύνδεση με Πελάτη",
  "registeredServices": "Καταχωρημένες Υπηρεσίες",
  "categoriesRegisteredCount": "κατηγορίες καταχωρημένες",
  "editableInWorkspace": "Επεξεργάσιμο στον Χώρο Εργασίας",
  "openWorkspaceBtn": "Διαχείριση Χώρου Εργασίας",
  "bilingualMode": "Δίγλωσσο (Κορεατικά)",
  "monolingualMode": "Μία γλώσσα",
  "bilingualToggleHint": "Δίγλωσση λειτουργία (Κλικ για λειτουργία μίας γλώσσας)",
  "hotlineNotice": "Κύρια Γραμμή Υποστήριξης Συστήματος",
  "monolingualToggleHint": "Λειτουργία μίας γλώσσας (Κλικ για δίγλωσση)",
  "headlineLead": "Συνδεθείτε απευθείας με πελάτες στην περιοχή σας",
  "actAsHelper": "Εργαστείτε ως επαγγελματίας τεχνικός",
  "helperPortal": "Πύλη Τεχνικού",
  "registerTab": "Εγγραφή Νέου Τεχνικού",
  "loginTab": "Σύνδεση Υπάρχοντος Τεχνικού",
  "newHelperRegTitle": "Εγγραφή Νέου Τεχνικού (3μηνη Ασφαλής Πρόσβαση)",
  "existingHelperLoginTitle": "Σύνδεση Εγγεγραμμένου Τεχνικού",
  "newHelperRegDesc": "Δεν απαιτείται αριθμός ταυτότητας. Εργαστείτε ελεύθερα για 3 μήνες μόνο με τον αριθμό του κινητού σας.",
  "existingHelperLoginDesc": "Εισαγάγετε τον ειδικό 3μηνο κωδικό πρόσβασης για να εισέλθετε στον χώρο εργασίας σας.",
  "accessKeyLabel": "Ειδικός Κωδικός Πρόσβασης 3 Μηνών",
  "loginWithAccessKey": "Σύνδεση με Κωδικό Ασφαλείας (Ισχύς 90 ημέρες)",
  "loginKeyNotice": "Εισαγάγετε τον 3μηνο κωδικό που λάβατε μέσω SMS για άμεση πρόσβαση στον χώρο εργασίας.",
  "lostCodeBtn": "Χάσατε τον κωδικό σας;",
  "reissueCodeTitle": "Επανέκδοση 3μηνου Κωδικού μέσω Τηλεφώνου",
  "getAccessKeyBtn": "Λήψη Κωδικού Ασφαλείας 3 Μηνών",
  "registerAndStart": "Εγγραφή & Έναρξη Υπηρεσίας",
  "selectServices": "Επιλογή Κατηγοριών Υπηρεσιών",
  "selectServicesDesc": "Επιλέξτε όλες τις κατηγορίες που μπορείτε να εξυπηρετήσετε (μπορείτε να τις αλλάξετε αργότερα).",
  "selectedCount": " επιλέχθηκαν",
  "helperNameLabel": "Όνομα ή Ψευδώνυμο Τεχνικού",
  "agreeTerms": "Έχω διαβάσει τους κανονισμούς και τις οδηγίες ασφαλείας του LIFE.HELP και δεσμεύομαι για άμεση και ευγενική εξυπηρέτηση.",
  "keySentNotice": "Ο κωδικός πρόσβασης στάλθηκε επιτυχώς με SMS",
  "issuedAccessKey": "Εκδόθηκε Κωδικός Πρόσβασης 3 Μηνών",
  "copy": "Αντιγραφή",
  "copied": "Αντιγράφηκε!",
  "backToTechHome": "Επιστροφή στην Αρχική Τεχνικού",
  "verifying": "Επαλήθευση...",
  "changePhoneBtn": "Αλλαγή",
  "enterAccessKeyError": "Παρακαλώ εισαγάγετε τον 3μηνο κωδικό ασφαλείας σας.",
  "enterNameError": "Παρακαλώ εισαγάγετε το όνομα ή το ψευδώνυμο εργασίας σας.",
  "selectServiceError": "Επιλέξτε τουλάχιστον μία κατηγορία υπηρεσίας.",
  "agreeTermsError": "Παρακαλώ συμφωνήστε με τους κανονισμούς και τους κανόνες ασφαλείας."
}

# Workspace
pt['workspace'] = {
  "title": "Área de Trabalho do Especialista",
  "mainHome": "Página Principal",
  "helperHonorific": "Especialista",
  "verifiedHelper": "Especialista Verificado",
  "securitySessionBadge": "Sessão de Segurança de 3 Meses",
  "daysRemaining": "dias restantes",
  "signedDate": "Data do Contrato",
  "viewContract": "Ver Cópia do Contrato",
  "logout": "Sair",
  "availTitle": "Status de Disponibilidade em Tempo Real",
  "statusActive": "Disponível para Atendimento",
  "statusPaused": "Pausado (Em Pausa)",
  "descActive": "Você está aberto para novos chamados de serviço.",
  "descPaused": "Os chamados estão pausados. Reative quando estiver pronto.",
  "btnPause": "Pausar Disponibilidade",
  "btnResume": "Retomar Atividade",
  "hotlineTitle": "Linhas Diretas Principais de Atendimento",
  "hotlineDesc": "Se o acesso ao app estiver indisponível ou houver urgências (acidentes, mudanças de região), ligue imediatamente.",
  "team1": "Linha Direta Equipe 1 (Urgência)",
  "team2": "Linha Direta Equipe 2 (Padrão)",
  "call": "Ligar",
  "sms": "SMS",
  "servicesTitle": "Gerenciamento de Categorias de Serviços",
  "servicesDesc": "Clique para desativar serviços indisponíveis ou adicionar novas categorias em tempo real.",
  "categoriesActive": "Categorias Ativas",
  "serviceActive": "Ativa",
  "serviceDisabled": "Desativada",
  "regionsTitle": "Regiões Operacionais de Atendimento",
  "regionsDesc": "Clique em ✕ para remover regiões que não pode visitar, ou adicione novas áreas.",
  "regionsCount": "Regiões Definidas",
  "addRegionBtn": "Adicionar Região",
  "removeRegionTitle": "Remover Região",
  "scheduleTitle": "Horário Disponível",
  "dayMon": "Seg",
  "dayTue": "Ter",
  "dayWed": "Qua",
  "dayThu": "Qui",
  "dayFri": "Sex",
  "daySat": "Sáb",
  "daySun": "Dom",
  "setHours": "Horários Configurados",
  "hours24": "Atendimento Imediato 24 Horas",
  "contractTitle": "Cópia do Acordo de Parceria LIFE.HELP",
  "contractName": "Nome",
  "contractPhone": "Telefone",
  "contractResidentId": "Identificação de Acesso",
  "contractSignedAt": "Data de Assinatura",
  "contractClauseTitle": "Cláusulas Principais do Contrato",
  "contractClauseDesc": "Sem coleta de documentos de identidade. Parceria profissional livre mantida por chave de segurança móvel de 3 meses.",
  "contractSignature": "Assinatura do Especialista: Verificado e Aceito Online",
  "close": "Fechar",
  "minServiceAlert": "É necessário manter pelo menos uma categoria de serviço ativa.",
  "serviceRemoved": "Serviço removido.",
  "serviceAdded": "Serviço adicionado.",
  "regionAdded": "Região adicionada com sucesso.",
  "minRegionAlert": "É necessário manter pelo menos uma região de atendimento.",
  "regionRemoved": "Região removida com sucesso.",
  "minDayAlert": "Pelo menos um dia da semana deve estar ativado.",
  "daysUpdated": "Escala de trabalho atualizada.",
  "logoutConfirm": "Deseja realmente sair da área de trabalho?",
  "activeTitle": "Ativo (Disponível para Atendimento)",
  "activeDesc": "Você está aberto para novos chamados. Mude para pausado sempre que fizer uma pausa.",
  "pausedTitle": "Pausado (Em Pausa)",
  "pausedDesc": "Os chamados estão em pausa. Reative para ativo quando estiver pronto para trabalhar.",
  "resumeBtn": "Retomar Atividade",
  "pauseBtn": "Pausar Disponibilidade",
  "adminChat": "Contatar Administração",
  "openAdminChat": "Ver Mensagens e Responder",
  "adminChatTitle": "Chat Online 1:1 com a Administração",
  "adminChatOnline": "ONLINE",
  "adminChatRecipient": "Destinatário: Especialista",
  "adminChatEmpty": "Nenhuma mensagem trocada com a administração.",
  "adminChatEmptyHint": "Envie dúvidas ou emergências aqui; um administrador responderá.",
  "adminChatPlaceholder": "Digite sua mensagem para a administração...",
  "adminChatSend": "Enviar",
  "calendarTitle": "Calendário Mensal de Atendimentos (Configuração de Folgas)",
  "calendarDesc": "Os dias de acordo com a programação semanal são marcados como ativos. Clique em qualquer data para desmarcar e definir como folga.",
  "calendarThisMonth": "Este Mês",
  "calendarNextMonth": "Próximo Mês",
  "calendarAvailable": "Disponível",
  "calendarDayOff": "Folga",
  "calendarDays": "dias",
  "calendarReset": "Redefinir Folgas",
  "calendarExclusionsTitle": "Folgas individuais definidas:",
  "calendarNoExclusions": "Nenhuma folga individual definida (ativo em todos os dias configurados)",
  "calendarDayActive": "Dia de Trabalho",
  "calendarDayScheduledOff": "Folga Regular",
  "calendarEdit": "Alterar",
  "calendarClose": "Fechar",
  "workingHoursDetailTitle": "Horário de Trabalho por Dia da Semana",
  "workingHoursDesc": "Ative os dias disponíveis da semana e defina horários de trabalho individuais por dia.",
  "customHours": "Horários Personalizados (Intervalos de 30 min)",
  "shift1": "1º Turno",
  "shift2": "2º Turno",
  "breakTime": "Horário de Intervalo",
  "hasBreak": "Incluir Intervalo",
  "startTime": "Início",
  "endTime": "Fim",
  "totalWork": "Total de Horas de Trabalho",
  "saveHours": "Salvar Horários",
  "monthUnit": "mês",
  "adminChatRecipientCounselor": "Destinatário: Atendente",
  "adminNoticeBanner": "[Mensagem da Administração]",
  "unreadCount": "não lidas",
  "preset24Hours": "Atendimento imediato disponível 24 horas",
  "presetDay": "Diurno (09:00 ~ 18:00)",
  "presetNight": "Noturno e Emergência (18:00 ~ 09:00 dia seguinte)",
  "presetMorning": "Manhã (09:00 ~ 13:00)",
  "presetAfternoon": "Tarde (13:00 ~ 18:00)"
}

el['workspace'] = {
  "title": "Χώρος Εργασίας Τεχνικού",
  "mainHome": "Αρχική Σελίδα",
  "helperHonorific": "Ειδικός Τεχνικός",
  "verifiedHelper": "Πιστοποιημένος Τεχνικός",
  "securitySessionBadge": "Συνεδρία Ασφαλείας 3 Μηνών",
  "daysRemaining": "ημέρες απομένουν",
  "signedDate": "Ημερομηνία υπογραφής",
  "viewContract": "Προβολή Αντιγράφου Σύμβασης",
  "logout": "Αποσύνδεση",
  "availTitle": "Κατάσταση Διαθεσιμότητας σε Πραγματικό Χρόνο",
  "statusActive": "Διαθέσιμος για Αποστολή",
  "statusPaused": "Σε Παύση (Σε Διάλειμμα)",
  "descActive": "Είστε έτοιμοι να δεχτείτε νέα αιτήματα εξυπηρέτησης.",
  "descPaused": "Οι κλήσεις εξυπηρέτησης έχουν διακοπεί προσωρινά. Επανέλθετε σε ενεργή κατάσταση όταν είστε έτοιμοι.",
  "btnPause": "Παύση Διαθεσιμότητας",
  "btnResume": "Επαναφορά σε Ενεργό",
  "hotlineTitle": "Κύριες Γραμμές Άμεσης Επικοινωνίας",
  "hotlineDesc": "Σε περίπτωση αδυναμίας πρόσβασης στην εφαρμογή ή επειγόντων περιστατικών (ατυχήματα, αλλαγή περιοχής), καλέστε μας άμεσα.",
  "team1": "Γραμμή Ομάδας 1 (Επείγον)",
  "team2": "Γραμμή Ομάδας 2 (Κανονικό)",
  "call": "Κλήση",
  "sms": "SMS",
  "servicesTitle": "Διαχείριση Κατηγοριών Υπηρεσιών",
  "servicesDesc": "Κάντε κλικ για να αφαιρέσετε μη διαθέσιμες υπηρεσίες ή να προσθέσετε νέες σε πραγματικό χρόνο.",
  "categoriesActive": "Ενεργές Κατηγορίες",
  "serviceActive": "Ενεργή",
  "serviceDisabled": "Απενεργοποιημένη",
  "regionsTitle": "Περιοχές Επιχειρησιακής Δράσης",
  "regionsDesc": "Κάντε κλικ στο ✕ για να αφαιρέσετε περιοχές ή προσθέστε νέες διαθέσιμες περιοχές.",
  "regionsCount": "Ορισμένες Περιοχές",
  "addRegionBtn": "Προσθήκη Περιοχής",
  "removeRegionTitle": "Αφαίρεση Περιοχής",
  "scheduleTitle": "Διαθέσιμο Πρόγραμμα",
  "dayMon": "Δευ",
  "dayTue": "Τρί",
  "dayWed": "Τετ",
  "dayThu": "Πέμ",
  "dayFri": "Παρ",
  "daySat": "Σάβ",
  "daySun": "Κυρ",
  "setHours": "Καθορισμένες Ώρες",
  "hours24": "24ωρη Άμεση Επέμβαση",
  "contractTitle": "Αντίγραφο Συμφωνητικού Συνεργασίας LIFE.HELP",
  "contractName": "Όνομα",
  "contractPhone": "Τηλέφωνο",
  "contractResidentId": "Κωδικός Πρόσβασης",
  "contractSignedAt": "Ημερομηνία Υπογραφής",
  "contractClauseTitle": "Βασικοί Όροι Σύμβασης",
  "contractClauseDesc": "Χωρίς συλλογή αριθμών ταυτότητας. Ελεύθερη επαγγελματική συνεργασία με 3μηνο κωδικό πρόσβασης κινητού.",
  "contractSignature": "Υπογραφή Τεχνικού: Ηλεκτρονικά Επαληθευμένη",
  "close": "Κλείσιμο",
  "minServiceAlert": "Πρέπει να παραμείνει τουλάχιστον μία ενεργή κατηγορία υπηρεσιών.",
  "serviceRemoved": "Η υπηρεσία αφαιρέθηκε.",
  "serviceAdded": "Η υπηρεσία προστέθηκε.",
  "regionAdded": "Η περιοχή προστέθηκε επιτυχώς.",
  "minRegionAlert": "Πρέπει να παραμείνει τουλάχιστον μία περιοχή εξυπηρέτησης.",
  "regionRemoved": "Η περιοχή αφαιρέθηκε επιτυχώς.",
  "minDayAlert": "Πρέπει να είναι ενεργή τουλάχιστον μία ημέρα της εβδομάδας.",
  "daysUpdated": "Το πρόγραμμα ημερών ενημερώθηκε.",
  "logoutConfirm": "Είστε βέβαιοι ότι θέλετε να αποσυνδεθείτε από τον χώρο εργασίας;",
  "activeTitle": "Ενεργός (Διαθέσιμος για Αποστολή)",
  "activeDesc": "Είστε διαθέσιμοι για νέα αιτήματα. Θέστε σε παύση όταν κάνετε διάλειμμα.",
  "pausedTitle": "Σε Παύση (Σε Διάλειμμα)",
  "pausedDesc": "Οι κλήσεις είναι σε παύση. Ενεργοποιήστε ξανά όταν είστε έτοιμοι για εργασία.",
  "resumeBtn": "Επαναφορά σε Ενεργό",
  "pauseBtn": "Παύση Διαθεσιμότητας",
  "adminChat": "Επικοινωνία με Κεντρικά",
  "openAdminChat": "Προβολή Μηνυμάτων & Απάντηση",
  "adminChatTitle": "1:1 Ζωντανή Συνομιλία με Κεντρικά",
  "adminChatOnline": "ONLINE",
  "adminChatRecipient": "Παραλήπτης: Τεχνικός",
  "adminChatEmpty": "Δεν υπάρχουν μηνύματα με τα κεντρικά.",
  "adminChatEmptyHint": "Αφήστε τυχόν ερωτήματα ή επείγοντα περιστατικά εδώ. Ο διαχειριστής θα τα εξετάσει.",
  "adminChatPlaceholder": "Πληκτρολογήστε απάντηση στα κεντρικά...",
  "adminChatSend": "Αποστολή",
  "calendarTitle": "Μηνιαίο Ημερολόγιο Αποστολών (Ρύθμιση Ρεπό)",
  "calendarDesc": "Οι ημέρες σύμφωνα με το εβδομαδιαίο πρόγραμμα σημειώνονται αυτόματα ως ενεργές. Κάντε κλικ σε οποιαδήποτε ημερομηνία για να την ορίσετε ως ρεπό.",
  "calendarThisMonth": "Τρέχων μήνας",
  "calendarNextMonth": "Επόμενος μήνας",
  "calendarAvailable": "Διαθέσιμο",
  "calendarDayOff": "Ρεπό",
  "calendarDays": "ημέρες",
  "calendarReset": "Επαναφορά Ρεπό",
  "calendarExclusionsTitle": "Μεμονωμένες εξαιρέσεις ρεπό:",
  "calendarNoExclusions": "Δεν έχουν οριστεί μεμονωμένα ρεπό (ενεργό σε όλες τις προγραμματισμένες ημέρες)",
  "calendarDayActive": "Ενεργό",
  "calendarDayScheduledOff": "Προγραμματισμένο ρεπό",
  "calendarEdit": "Αλλαγή",
  "calendarClose": "Κλείσιμο",
  "workingHoursDetailTitle": "Ώρες Εργασίας ανά Ημέρα Εβδομάδας",
  "workingHoursDesc": "Ενεργοποιήστε τις διαθέσιμες ημέρες της εβδομάδας και ορίστε μεμονωμένες ώρες εργασίας ανά ημέρα.",
  "customHours": "Προσαρμοσμένα Διαστήματα (Ανά 30 λεπτά)",
  "shift1": "1η Βάρδια",
  "shift2": "2η Βάρδια",
  "breakTime": "Ώρα Διαλείμματος",
  "hasBreak": "Συμπερίληψη Διαλείμματος",
  "startTime": "Ώρα Έναρξης",
  "endTime": "Ώρα Λήξης",
  "totalWork": "Συνολικές Ώρες Εργασίας",
  "saveHours": "Αποθήκευση Ωραρίου",
  "monthUnit": "μήνας",
  "adminChatRecipientCounselor": "Παραλήπτης: Σύμβουλος",
  "adminNoticeBanner": "[Μήνυμα Διαχειριστή]",
  "unreadCount": "μη αναγνωσμένα",
  "preset24Hours": "24ωρη άμεση επέμβαση διαθέσιμη",
  "presetDay": "Ημερήσιο (09:00 ~ 18:00)",
  "presetNight": "Νυχτερινό & Επείγον (18:00 ~ 09:00 επόμενης ημέρας)",
  "presetMorning": "Πρωινό (09:00 ~ 13:00)",
  "presetAfternoon": "Απογευματινό (13:00 ~ 18:00)"
}

# Chat
pt['chat'] = {
  "title": "Chat de Atendimento Multilíngue ao Vivo",
  "tag": "Suporte em Tempo Real no Seu Idioma",
  "desc": "Converse diretamente com nossos atendentes nativos e obtenha ajuda rápida.",
  "counselorPortal": "Portal do Atendente",
  "dutyCount": "Atendentes de Plantão",
  "dutyPreparing": "Preparando Atendimento",
  "dutyStatus": "Status do Plantão",
  "allDutyNotice": "Atendentes nativos prontos para ajudar.",
  "startTitle": "Iniciar Consulta",
  "startDesc": "Insira seu nome e idioma preferido para conectar-se.",
  "nameLabel": "Seu Nome",
  "namePlaceholder": "Digite seu nome",
  "langLabel": "Idioma Preferido",
  "langHint": "Selecione o idioma em que deseja ser atendido.",
  "inquiryLabel": "Assunto da Consulta",
  "inquiryPlaceholder": "Descreva brevemente sua dúvida ou problema...",
  "enterRoom": "Entrar na Sala de Chat",
  "guideTitle": "Como Funciona",
  "guide1": "Conectamos você a atendentes nativos em tempo real.",
  "guide2": "Tire dúvidas sobre serviços residenciais, orçamentos e agendamentos.",
  "guide3": "Comunicação clara sem barreiras linguísticas.",
  "counselorRecruit": "Trabalhe Conosco como Atendente",
  "counselorRecruitDesc": "Ajude pessoas da sua comunidade e ganhe renda extra com flexibilidade.",
  "counselorPortalBtn": "Acessar Portal do Atendente →",
  "recentChats": "Conversas Recentes",
  "chatting": "Em Atendimento",
  "waiting": "Aguardando",
  "closed": "Encerrado",
  "connecting": "Conectando...",
  "statusConnected": "Conectado",
  "statusWaiting": "Aguardando Atendente",
  "statusClosed": "Atendimento Encerrado",
  "customer": "Cliente",
  "endChat": "Encerrar Chat",
  "leaveRoom": "Sair da Sala",
  "inputPlaceholder": "Digite sua mensagem...",
  "send": "Enviar",
  "closedNotice": "Este chat foi encerrado.",
  "tabLogin": "Login de Atendente",
  "tabRegister": "Cadastro de Novo Atendente",
  "loginTitle": "Entrar como Atendente",
  "loginDesc": "Insira seu telefone para acessar o painel de atendimento.",
  "registerTitle": "Cadastre-se como Atendente",
  "registerDesc": "Junte-se à nossa equipe de atendimento multilíngue.",
  "phoneLabel": "Número de Telefone",
  "sendSmsBtn": "Enviar Código SMS",
  "retype": "Digitar Novamente",
  "smsSentNotice": "Código de verificação enviado por SMS.",
  "authCodeLabel": "Código de Verificação",
  "counselorNameLabel": "Nome do Atendente",
  "counselorNamePlaceholder": "Digite seu nome completo",
  "regionLabel": "Região de Atuação",
  "specialtyLabel": "Especialidade",
  "specialtyPlaceholder": "Ex.: Suporte geral, moradia, reparos...",
  "langsLabel": "Idiomas de Atendimento",
  "agreeLabel": "Concordo com os termos e regras de privacidade.",
  "loginSubmit": "Entrar no Painel",
  "registerSubmit": "Concluir Cadastro",
  "backToCustomerChat": "Voltar ao Chat do Cliente",
  "duty": "Em Plantão",
  "breakStatus": "Em Pausa",
  "logout": "Sair",
  "langSettings": "Configurações de Idioma",
  "searchLang": "Buscar idioma...",
  "waitingQueue": "Fila de Espera",
  "noWaiting": "Nenhum cliente aguardando no momento.",
  "acceptBtn": "Aceitar Chamado",
  "myActiveChats": "Meus Atendimentos Ativos",
  "noActive": "Nenhum atendimento ativo no momento.",
  "quickReplies": "Respostas Rápidas",
  "quickHello": "Saudação",
  "quickTech": "Especialista",
  "quickHousing": "Moradia",
  "replyPlaceholder": "Digite uma resposta rápida...",
  "emptyWorkspace": "Nenhuma conversa selecionada",
  "emptyWorkspaceSub": "Selecione uma conversa na lista para começar.",
  "workstationTitle": "Estação de Atendimento",
  "chattingWith": "Conversando com",
  "sessionStart": "Início da Sessão",
  "securitySessionBadge": "Sessão Segura de 3 Meses",
  "daysRemaining": "dias restantes",
  "langsActive": "Idiomas Ativos",
  "inquiryDefault": "Consulta Geral",
  "chatStarted": "Chat iniciado",
  "quickHelloText": "Olá! Como posso ajudar você hoje?",
  "quickTechText": "Um especialista qualificado está disponível para atender sua região.",
  "quickHousingText": "Temos opções de moradia disponíveis. Qual localização prefere?",
  "counselorRole": "Atendente",
  "nativeConsultation": "Atendimento no Idioma Nativo",
  "nativeConsultationCenter": "Central de Atendimento Multilíngue",
  "screenLabel": "Tela de Atendimento",
  "syncWithWeb": "Sincronizado com a Web",
  "quickSelect": "Seleção Rápida",
  "counselorReadyCount": "Atendentes Prontos",
  "counselorAutoMatch": "Conexão Automática Inteligente",
  "langIndependentDesc": "Comunicação fluida em qualquer língua.",
  "verifying": "Verificando...",
  "loginKeyNotice": "Insira o código de segurança recebido para acessar.",
  "registerAsNewCounselor": "Cadastre-se como Novo Atendente",
  "lostCode": "Perdeu seu código?",
  "reissuePhoneTitle": "Reemissão de Código",
  "sendingCode": "Enviando código...",
  "getCode": "Obter Código",
  "copied": "Copiado!",
  "copy": "Copiar",
  "securityCodeSentNotice": "Código de segurança enviado com sucesso.",
  "accessKeyTitle": "Chave de Acesso Pessoal",
  "expiryNotice": "Válida por 90 dias com renovação automática.",
  "selectedLangsCount": "idiomas selecionados"
}

el['chat'] = {
  "title": "Ζωντανή Πολύγλωσση Συνομιλία",
  "tag": "Υποστήριξη σε Πραγματικό Χρόνο στη Γλώσσα σας",
  "desc": "Συνομιλήστε απευθείας με τους φυσικούς ομιλητές μας για άμεση βοήθεια.",
  "counselorPortal": "Πύλη Συμβούλου",
  "dutyCount": "Σύμβουλοι σε Υπηρεσία",
  "dutyPreparing": "Προετοιμασία Υπηρεσίας",
  "dutyStatus": "Κατάσταση Υπηρεσίας",
  "allDutyNotice": "Σύμβουλοι έτοιμοι να σας εξυπηρετήσουν.",
  "startTitle": "Έναρξη Συνομιλίας",
  "startDesc": "Εισαγάγετε το όνομα και την προτιμώμενη γλώσσα σας.",
  "nameLabel": "Το Όνομά σας",
  "namePlaceholder": "Εισαγάγετε το όνομά σας",
  "langLabel": "Προτιμώμενη Γλώσσα",
  "langHint": "Επιλέξτε τη γλώσσα στην οποία θέλετε να επικοινωνήσετε.",
  "inquiryLabel": "Θέμα Ερώτησης",
  "inquiryPlaceholder": "Περιγράψτε συνοπτικά την ερώτηση ή το πρόβλημά σας...",
  "enterRoom": "Είσοδος στο Chat",
  "guideTitle": "Πώς Λειτουργεί",
  "guide1": "Σας συνδέουμε με συμβούλους στη μητρική σας γλώσσα.",
  "guide2": "Ρωτήστε για οικιακές επισκευές, κόστος και προγραμματισμό.",
  "guide3": "Άμεση επικοινωνία χωρίς γλωσσικά εμπόδια.",
  "counselorRecruit": "Γίνετε Σύμβουλος",
  "counselorRecruitDesc": "Βοηθήστε την κοινότητά σας και κερδίστε επιπλέον εισόδημα με ευελιξία.",
  "counselorPortalBtn": "Πύλη Συμβούλου →",
  "recentChats": "Πρόσφατες Συνομιλίες",
  "chatting": "Σε Εξέλιξη",
  "waiting": "Σε Αναμονή",
  "closed": "Ολοκληρώθηκε",
  "connecting": "Σύνδεση...",
  "statusConnected": "Συνδέθηκε",
  "statusWaiting": "Αναμονή για Σύμβουλο",
  "statusClosed": "Η Συνομιλία Έληξε",
  "customer": "Πελάτης",
  "endChat": "Τερματισμός Chat",
  "leaveRoom": "Έξοδος",
  "inputPlaceholder": "Πληκτρολογήστε μήνυμα...",
  "send": "Αποστολή",
  "closedNotice": "Αυτή η συνομιλία έχει ολοκληρωθεί.",
  "tabLogin": "Σύνδεση Συμβούλου",
  "tabRegister": "Εγγραφή Νέου Συμβούλου",
  "loginTitle": "Σύνδεση Συμβούλου",
  "loginDesc": "Εισαγάγετε το τηλέφωνό σας για πρόσβαση στον πίνακα συμβούλου.",
  "registerTitle": "Εγγραφή Συμβούλου",
  "registerDesc": "Γίνετε μέλος της πολύγλωσσης ομάδας υποστήριξής μας.",
  "phoneLabel": "Αριθμός Τηλεφώνου",
  "sendSmsBtn": "Αποστολή SMS Επαλήθευσης",
  "retype": "Επανεισαγωγή",
  "smsSentNotice": "Ο κωδικός επαλήθευσης στάλθηκε με SMS.",
  "authCodeLabel": "Κωδικός Επαλήθευσης",
  "counselorNameLabel": "Όνομα Συμβούλου",
  "counselorNamePlaceholder": "Εισαγάγετε το ονοματεπώνυμό σας",
  "regionLabel": "Περιοχή Δραστηριότητας",
  "specialtyLabel": "Ειδικότητα",
  "specialtyPlaceholder": "π.χ. Γενική υποστήριξη, στέγαση, επισκευές...",
  "langsLabel": "Γλώσσες Εξυπηρέτησης",
  "agreeLabel": "Συμφωνώ με τους όρους και την πολιτική απορρήτου.",
  "loginSubmit": "Σύνδεση",
  "registerSubmit": "Ολοκλήρωση Εγγραφής",
  "backToCustomerChat": "Επιστροφή στο Chat Πελάτη",
  "duty": "Σε Υπηρεσία",
  "breakStatus": "Σε Διάλειμμα",
  "logout": "Αποσύνδεση",
  "langSettings": "Ρυθμίσεις Γλωσσών",
  "searchLang": "Αναζήτηση γλώσσας...",
  "waitingQueue": "Ουρά Αναμονής",
  "noWaiting": "Δεν υπάρχουν πελάτες σε αναμονή.",
  "acceptBtn": "Αποδοχή",
  "myActiveChats": "Ενεργές Συνομιλίες μου",
  "noActive": "Δεν υπάρχουν ενεργές συνομιλίες.",
  "quickReplies": "Γρήγορες Απαντήσεις",
  "quickHello": "Χαιρετισμός",
  "quickTech": "Τεχνικός",
  "quickHousing": "Στέγαση",
  "replyPlaceholder": "Πληκτρολογήστε γρήγορη απάντηση...",
  "emptyWorkspace": "Δεν έχει επιλεγεί συνομιλία",
  "emptyWorkspaceSub": "Επιλέξτε μια συνομιλία από τη λίστα για να ξεκινήσετε.",
  "workstationTitle": "Σταθμός Εργασίας Συμβούλου",
  "chattingWith": "Συνομιλία με",
  "sessionStart": "Έναρξη Συνεδρίας",
  "securitySessionBadge": "Συνεδρία Ασφαλείας 3 Μηνών",
  "daysRemaining": "ημέρες απομένουν",
  "langsActive": "Ενεργές Γλώσσες",
  "inquiryDefault": "Γενικό Ερώτημα",
  "chatStarted": "Η συνομιλία ξεκίνησε",
  "quickHelloText": "Γεια σας! Πώς μπορώ να σας βοηθήσω σήμερα;",
  "quickTechText": "Ένας εξειδικευμένος τεχνικός είναι άμεσα διαθέσιμος στην περιοχή σας.",
  "quickHousingText": "Έχουμε διαθέσιμες επιλογές στέγασης. Ποια περιοχή προτιμάτε;",
  "counselorRole": "Σύμβουλος",
  "nativeConsultation": "Εξυπηρέτηση στη Μητρική Γλώσσα",
  "nativeConsultationCenter": "Πολύγλωσσο Κέντρο Εξυπηρέτησης",
  "screenLabel": "Οθόνη Συμβούλου",
  "syncWithWeb": "Συγχρονισμένο με το Web",
  "quickSelect": "Γρήγορη Επιλογή",
  "counselorReadyCount": "Διαθέσιμοι Σύμβουλοι",
  "counselorAutoMatch": "Έξυπνη Αυτόματη Σύνδεση",
  "langIndependentDesc": "Άνετη επικοινωνία σε οποιαδήποτε γλώσσα.",
  "verifying": "Επαλήθευση...",
  "loginKeyNotice": "Εισαγάγετε τον κωδικό ασφαλείας για είσοδο.",
  "registerAsNewCounselor": "Εγγραφή ως Νέος Σύμβουλος",
  "lostCode": "Χάσατε τον κωδικό;",
  "reissuePhoneTitle": "Επανέκδοση Κωδικού",
  "sendingCode": "Αποστολή κωδικού...",
  "getCode": "Λήψη Κωδικού",
  "copied": "Αντιγράφηκε!",
  "copy": "Αντιγραφή",
  "securityCodeSentNotice": "Ο κωδικός ασφαλείας στάλθηκε επιτυχώς.",
  "accessKeyTitle": "Προσωπικός Κωδικός Πρόσβασης",
  "expiryNotice": "Ισχύει για 90 ημέρες με αυτόματη ανανέωση.",
  "selectedLangsCount": "γλώσσες επιλέχθηκαν"
}

# Admin
pt['admin'] = {
  "title": "Painel de Administração",
  "login": "Login do Administrador",
  "description": "Gerenciamento e controle operacional da plataforma.",
  "customers": "Clientes",
  "technicians": "Especialistas",
  "orders": "Chamados",
  "assignment": "Atribuição",
  "payments": "Pagamentos",
  "settlements": "Repasses",
  "complaints": "Reclamações",
  "statistics": "Estatísticas",
  "brandTitle": "Administração LIFE.HELP",
  "loginTitle": "Login do Administrador",
  "loginDesc": "Acesso restrito à equipe operacional e administrativa.",
  "loginAccountLabel": "Conta / E-mail",
  "loginPasswordLabel": "Senha",
  "loginSubmitBtn": "Entrar no Painel",
  "loginVerifying": "Verificando credenciais...",
  "loginQuickFill": "Preenchimento Rápido de Teste",
  "loginTestHint": "Ambiente seguro de testes e monitoramento.",
  "loginBackHome": "Voltar ao Início",
  "loginFooter": "LIFE.HELP Centro de Operações",
  "loginError": "Credenciais incorretas.",
  "sessionVerifying": "Verificando sessão de administrador...",
  "mainHome": "Página Inicial",
  "helperWs": "Área de Trabalho do Especialista",
  "counselorWs": "Área de Trabalho do Atendente",
  "logout": "Sair",
  "tabHelpers": "Especialistas",
  "tabCounselors": "Atendentes",
  "tabRequests": "Chamados",
  "tabMessages": "Mensagens",
  "tabReviews": "Avaliações",
  "statHelpers": "Total de Especialistas",
  "statCounselors": "Total de Atendentes",
  "statRequests": "Total de Chamados",
  "statSecurityKeys": "Chaves Ativas",
  "statMessages": "Mensagens Trocadas",
  "unitPersons": "pessoas",
  "unitCases": "casos",
  "unitIssued": "emitidas",
  "statusActive": "Ativo",
  "statusPaused": "Pausado",
  "statusDuty": "De Plantão",
  "statusBreak": "Em Pausa",
  "statusPending": "Pendente",
  "statusDispatched": "Despachado",
  "statusCompleted": "Concluído",
  "statusAllNormal": "Todos Normais",
  "statusWithin14Days": "Expira em 14 Dias",
  "statusAllRead": "Todas Lidas",
  "statusUnread": "Não Lidas",
  "filterAll": "Todos",
  "filterActive": "Ativos",
  "filterPaused": "Pausados",
  "filterExpiring": "Expirando",
  "filterDuty": "De Plantão",
  "filterBreak": "Em Pausa",
  "filterPending": "Pendentes",
  "filterDispatched": "Despachados",
  "filterCompleted": "Concluídos",
  "searchHelperPlaceholder": "Buscar especialista por nome, telefone...",
  "searchCounselorPlaceholder": "Buscar atendente por nome, idioma...",
  "searchRequestPlaceholder": "Buscar chamado por endereço, serviço...",
  "searchHelperAssignPlaceholder": "Buscar especialista para atribuir...",
  "thHelperInfo": "Informações do Especialista",
  "thOperatingRegion": "Região de Atuação",
  "thServices": "Categorias de Serviços",
  "thSecuritySession": "Sessão de Segurança (3 Meses)",
  "thWorkStatus": "Status de Atendimento",
  "thManageContact": "Gerenciar / Contatar",
  "thCounselorInfo": "Informações do Atendente",
  "thCounselorLanguages": "Idiomas / Especialidades",
  "thCounselorStatus": "Status do Plantão",
  "thCounselorSession": "Sessão de Segurança",
  "thRequestId": "ID do Chamado",
  "thRequestDetails": "Detalhes / Endereço",
  "thDispatchStatus": "Status do Envio",
  "thCreatedAt": "Recebido em",
  "thAction": "Ações",
  "btnAssignHelper": "Atribuir Especialista",
  "btnReassignHelper": "Reatribuir Especialista",
  "btnComplete": "Concluir Chamado",
  "btnCancelDispatch": "Cancelar Envio",
  "btnDelete": "Excluir",
  "btnDirectMessage": "Mensagem Direta 1:1",
  "btnSendMessage": "Enviar Mensagem",
  "btnConfirmAssign": "Confirmar Atribuição e Enviar Ordem",
  "btnClose": "Fechar",
  "assignModalTitle": "Atribuição de Especialista para Chamado de Emergência",
  "assignModalDesc": "Selecione o especialista mais adequado para a região e o serviço solicitado.",
  "assignRecommendBadge": "Região Compatível (Recomendado)",
  "assignNotice": "Ao atribuir, o endereço e os detalhes do chamado serão enviados instantaneamente via chat 1:1.",
  "chatPartnerList": "Parceiros Conectados",
  "chatPlaceholder": "Digite sua mensagem (Pressione Enter para enviar)...",
  "chatQuickTemplates": "Modelos Rápidos de Mensagem",
  "templateDispatch": "🚨 Ordem de Atendimento de Emergência",
  "templateDispatchText": "Um chamado urgente foi registrado na sua região. Por favor, confirme sua disponibilidade imediata.",
  "templateKeyRenewal": "🛡️ Aviso de Renovação de Chave",
  "templateKeyRenewalText": "Sua chave de acesso de 3 meses expira em 14 dias. Renove para manter o acesso.",
  "templateStatusCheck": "⏰ Verificação de Status",
  "templateStatusCheckText": "Por favor, verifique e confirme seu status de disponibilidade no sistema.",
  "templateScheduleCheck": "📅 Atualização de Escala",
  "templateScheduleCheckText": "Por favor, revise sua escala de trabalho e folgas no calendário da sua área de trabalho.",
  "reviewCenter": "Central de Avaliações de Clientes",
  "reviewAverage": "Média de Avaliações",
  "reviewCount": "Total de Avaliações",
  "reviewEmpty": "Nenhuma avaliação de cliente registrada ainda.",
  "reviewCustomer": "Avaliação do Cliente",
  "reviewService": "Serviço",
  "noHelpers": "Nenhum especialista encontrado com esses critérios.",
  "noCounselors": "Nenhum atendente encontrado com esses critérios.",
  "noRequests": "Nenhum chamado encontrado com esses critérios.",
  "noMessages": "Nenhuma mensagem encontrada.",
  "selectPartnerToChat": "Selecione um parceiro à esquerda para iniciar a conversa.",
  "allServices": "Todos os Serviços",
  "registeredServicesLabel": "Serviços Registrados",
  "messageSentSuccess": "Mensagem enviada com sucesso para ",
  "partnerChat": "Contato Online com Parceiro",
  "securityKeyLabel": "Chave de Segurança de 3 Meses",
  "daysLeft": "dias restantes",
  "renewalRequired": "Renovação Necessária",
  "expiresAtLabel": "Expira em",
  "activeRegionLabel": "Regiões Ativas",
  "serviceCategoryLabel": "Serviços",
  "weeklyScheduleLabel": "Escala Semanal",
  "standardHoursLabel": "Horário Padrão",
  "hours24": "Atendimento Imediato 24 Horas",
  "individualDayOffLabel": "Folgas Individuais (Este Mês/Próximo Mês)",
  "unspecifiedRegion": "Nenhuma região especificada",
  "unselectedService": "Nenhum serviço selecionado",
  "counselorRegionLabel": "Área de Cobertura",
  "counselorNationwide": "Nacional",
  "counselorSpecialtyLabel": "Especialidade",
  "counselorSpecialtyDefault": "Apoio Multilíngue de Emergência",
  "counselorLangsLabel": "Idiomas Atendidos",
  "customerPhoneLabel": "Telefone do Cliente",
  "dispatchLocationLabel": "Local do Atendimento",
  "requestDescLabel": "Descrição do Problema",
  "attachedPhotosLabel": "Fotos Anexadas",
  "assignedHelperLabel": "Especialista Atribuído",
  "dispatchTimeLabel": "Atribuído em",
  "emergencyNotified": "Notificação de Emergência Enviada",
  "directChat1to1": "Chat 1:1",
  "btnRevertPending": "Voltar para Pendente",
  "matchedRegionBadge": "Região Compatível",
  "matchedServiceBadge": "Serviço Compatível",
  "helpersSubheader": "Especialistas Parceiros",
  "counselorsSubheader": "Atendentes Parceiros",
  "reviewDesc": "Gerenciamento de avaliações enviadas pelos clientes.",
  "reviewEmailSent": "Enviado para contact@life.help",
  "reviewRecipient": "Destinatário:",
  "reviewAnonymous": "Anônimo",
  "toastDeleted": "Item excluído com sucesso.",
  "toastCompleted": "Chamado concluído com sucesso.",
  "toastReverted": "Chamado retornado para pendente.",
  "toastCancelled": "Envio cancelado.",
  "toastAssigned": "Especialista atribuído com sucesso!",
  "deleteConfirm": "Tem certeza de que deseja excluir este item?"
}

el['admin'] = {
  "title": "Σύστημα Διαχειριστή",
  "login": "Σύνδεση Διαχειριστή",
  "description": "Διαχείριση και επιχειρησιακός έλεγχος της πλατφόρμας.",
  "customers": "Πελάτες",
  "technicians": "Τεχνικοί",
  "orders": "Αιτήματα",
  "assignment": "Ανάθεση",
  "payments": "Πληρωμές",
  "settlements": "Εκκαθαρίσεις",
  "complaints": "Παράπονα",
  "statistics": "Στατιστικά",
  "brandTitle": "Διαχείριση LIFE.HELP",
  "loginTitle": "Σύνδεση Διαχειριστή",
  "loginDesc": "Αποκλειστική πρόσβαση για την ομάδα διαχείρισης.",
  "loginAccountLabel": "Λογαριασμός / Email",
  "loginPasswordLabel": "Κωδικός Πρόσβασης",
  "loginSubmitBtn": "Σύνδεση στο Σύστημα",
  "loginVerifying": "Επαλήθευση στοιχείων...",
  "loginQuickFill": "Γρήγορη Συμπλήρωση Δοκιμής",
  "loginTestHint": "Ασφαλές περιβάλλον δοκιμών και παρακολούθησης.",
  "loginBackHome": "Επιστροφή στην Αρχική",
  "loginFooter": "LIFE.HELP Κέντρο Επιχειρήσεων",
  "loginError": "Λανθασμένα στοιχεία σύνδεσης.",
  "sessionVerifying": "Επαλήθευση συνεδρίας διαχειριστή...",
  "mainHome": "Αρχική Σελίδα",
  "helperWs": "Χώρος Εργασίας Τεχνικού",
  "counselorWs": "Χώρος Εργασίας Συμβούλου",
  "logout": "Αποσύνδεση",
  "tabHelpers": "Τεχνικοί",
  "tabCounselors": "Σύμβουλοι",
  "tabRequests": "Αιτήματα",
  "tabMessages": "Μηνύματα",
  "tabReviews": "Αξιολογήσεις",
  "statHelpers": "Σύνολο Τεχνικών",
  "statCounselors": "Σύνολο Συμβούλων",
  "statRequests": "Σύνολο Αιτημάτων",
  "statSecurityKeys": "Ενεργοί Κωδικοί",
  "statMessages": "Μηνύματα",
  "unitPersons": "άτομα",
  "unitCases": "περιπτώσεις",
  "unitIssued": "εκδόθηκαν",
  "statusActive": "Ενεργός",
  "statusPaused": "Σε Παύση",
  "statusDuty": "Σε Υπηρεσία",
  "statusBreak": "Σε Διάλειμμα",
  "statusPending": "Εκκρεμεί",
  "statusDispatched": "Απεστάλη",
  "statusCompleted": "Ολοκληρώθηκε",
  "statusAllNormal": "Όλα Κανονικά",
  "statusWithin14Days": "Λήγει σε 14 ημέρες",
  "statusAllRead": "Όλα Αναγνωσμένα",
  "statusUnread": "Μη Αναγνωσμένα",
  "filterAll": "Όλα",
  "filterActive": "Ενεργά",
  "filterPaused": "Σε Παύση",
  "filterExpiring": "Λήγουν Σύντομα",
  "filterDuty": "Σε Υπηρεσία",
  "filterBreak": "Σε Διάλειμμα",
  "filterPending": "Εκκρεμή",
  "filterDispatched": "Απεσταλμένα",
  "filterCompleted": "Ολοκληρωμένα",
  "searchHelperPlaceholder": "Αναζήτηση τεχνικού με όνομα, τηλέφωνο...",
  "searchCounselorPlaceholder": "Αναζήτηση συμβούλου με όνομα, γλώσσα...",
  "searchRequestPlaceholder": "Αναζήτηση αιτήματος με διεύθυνση, υπηρεσία...",
  "searchHelperAssignPlaceholder": "Αναζήτηση τεχνικού για ανάθεση...",
  "thHelperInfo": "Στοιχεία Τεχνικού",
  "thOperatingRegion": "Περιοχή Δραστηριότητας",
  "thServices": "Κατηγορίες Υπηρεσιών",
  "thSecuritySession": "Συνεδρία Ασφαλείας (3 Μηνών)",
  "thWorkStatus": "Κατάσταση Εργασίας",
  "thManageContact": "Διαχείριση / Επικοινωνία",
  "thCounselorInfo": "Στοιχεία Συμβούλου",
  "thCounselorLanguages": "Γλώσσες / Ειδικότητα",
  "thCounselorStatus": "Κατάσταση Υπηρεσίας",
  "thCounselorSession": "Συνεδρία Ασφαλείας",
  "thRequestId": "ID Αιτήματος",
  "thRequestDetails": "Λεπτομέρειες / Διεύθυνση",
  "thDispatchStatus": "Κατάσταση Αποστολής",
  "thCreatedAt": "Ελήφθη στις",
  "thAction": "Ενέργειες",
  "btnAssignHelper": "Ανάθεση Τεχνικού",
  "btnReassignHelper": "Επαναανάθεση Τεχνικού",
  "btnComplete": "Ολοκλήρωση",
  "btnCancelDispatch": "Ακύρωση Αποστολής",
  "btnDelete": "Διαγραφή",
  "btnDirectMessage": "1:1 Μήνυμα",
  "btnSendMessage": "Αποστολή",
  "btnConfirmAssign": "Επιβεβαίωση Ανάθεσης & Αποστολή Εντολής",
  "btnClose": "Κλείσιμο",
  "assignModalTitle": "Ανάθεση Τεχνικού Επείγουσας Ανάγκης",
  "assignModalDesc": "Επιλέξτε τον κατάλληλο τεχνικό βάσει περιοχής και ζητούμενης υπηρεσίας.",
  "assignRecommendBadge": "Ταίριασμα Περιοχής (Προτείνεται)",
  "assignNotice": "Μετά την ανάθεση, τα στοιχεία του πελάτη αποστέλλονται άμεσα στον τεχνικό μέσω 1:1 chat.",
  "chatPartnerList": "Συνδεδεμένοι Συνεργάτες",
  "chatPlaceholder": "Πληκτρολογήστε μήνυμα (Πατήστε Enter για αποστολή)...",
  "chatQuickTemplates": "Γρήγορα Πρότυπα Μηνυμάτων",
  "templateDispatch": "🚨 Επείγουσα Εντολή Επέμβασης",
  "templateDispatchText": "Καταχωρήθηκε επείγον αίτημα στην περιοχή σας. Παρακαλώ επιβεβαιώστε άμεση διαθεσιμότητα.",
  "templateKeyRenewal": "🛡️ Ειδοποίηση Ανανέωσης Κωδικού",
  "templateKeyRenewalText": "Ο 3μηνος κωδικός πρόσβασής σας λήγει σε 14 ημέρες. Παρακαλώ ανανεώστε τον.",
  "templateStatusCheck": "⏰ Έλεγχος Κατάστασης",
  "templateStatusCheckText": "Παρακαλώ επιβεβαιώστε την κατάσταση διαθεσιμότητάς σας στο σύστημα.",
  "templateScheduleCheck": "📅 Ενημέρωση Προγράμματος",
  "templateScheduleCheckText": "Παρακαλώ ελέγξτε και ενημερώστε το πρόγραμμά σας και τις ημέρες ρεπό στο ημερολόγιο.",
  "reviewCenter": "Κέντρο Αξιολογήσεων Πελατών",
  "reviewAverage": "Μέση Βαθμολογία",
  "reviewCount": "Σύνολο Αξιολογήσεων",
  "reviewEmpty": "Δεν υπάρχουν ακόμη αξιολογήσεις πελατών.",
  "reviewCustomer": "Αξιολόγηση Πελάτη",
  "reviewService": "Υπηρεσία",
  "noHelpers": "Δεν βρέθηκαν τεχνικοί με αυτά τα κριτήρια.",
  "noCounselors": "Δεν βρέθηκαν σύμβουλοι με αυτά τα κριτήρια.",
  "noRequests": "Δεν βρέθηκαν αιτήματα με αυτά τα κριτήρια.",
  "noMessages": "Δεν βρέθηκαν μηνύματα.",
  "selectPartnerToChat": "Επιλέξτε έναν συνεργάτη από τα αριστερά για να ξεκινήσετε συνομιλία.",
  "allServices": "Όλες οι Υπηρεσίες",
  "registeredServicesLabel": "Καταχωρημένες Υπηρεσίες",
  "messageSentSuccess": "Το μήνυμα στάλθηκε επιτυχώς στον/στην ",
  "partnerChat": "Ηλεκτρονική Επαφή Συνεργάτη",
  "securityKeyLabel": "Κωδικός Ασφαλείας 3 Μηνών",
  "daysLeft": "ημέρες απομένουν",
  "renewalRequired": "Απαιτείται Ανανέωση",
  "expiresAtLabel": "Λήγει στις",
  "activeRegionLabel": "Ενεργές Περιοχές",
  "serviceCategoryLabel": "Υπηρεσίες",
  "weeklyScheduleLabel": "Εβδομαδιαίο Πρόγραμμα",
  "standardHoursLabel": "Κανονικές Ώρες",
  "hours24": "24ωρη Άμεση Επέμβαση",
  "individualDayOffLabel": "Μεμονωμένα Ρεπό (Τρέχων/Επόμενος Μήνας)",
  "unspecifiedRegion": "Χωρίς καθορισμένη περιοχή",
  "unselectedService": "Χωρίς επιλεγμένη υπηρεσία",
  "counselorRegionLabel": "Περιοχή Κάλυψης",
  "counselorNationwide": "Πανελλαδικά",
  "counselorSpecialtyLabel": "Ειδικότητα",
  "counselorSpecialtyDefault": "Πολύγλωσση Υποστήριξη Επείγουσας Ανάγκης",
  "counselorLangsLabel": "Υποστηριζόμενες Γλώσσες",
  "customerPhoneLabel": "Τηλέφωνο Πελάτη",
  "dispatchLocationLabel": "Τοποθεσία Αποστολής",
  "requestDescLabel": "Περιγραφή Προβλήματος",
  "attachedPhotosLabel": "Συνημμένες Φωτογραφίες",
  "assignedHelperLabel": "Ανατεθειμένος Τεχνικός",
  "dispatchTimeLabel": "Ώρα Ανάθεσης",
  "emergencyNotified": "Επείγουσα Ειδοποίηση Στάλθηκε",
  "directChat1to1": "1:1 Chat",
  "btnRevertPending": "Επαναφορά σε Εκκρεμές",
  "matchedRegionBadge": "Ταίριασμα Περιοχής",
  "matchedServiceBadge": "Ταίριασμα Υπηρεσίας",
  "helpersSubheader": "Συνεργάτες Τεχνικοί",
  "counselorsSubheader": "Συνεργάτες Σύμβουλοι",
  "reviewDesc": "Διαχείριση των αξιολογήσεων που υποβλήθηκαν από τους πελάτες.",
  "reviewEmailSent": "Στάλθηκε στο contact@life.help",
  "reviewRecipient": "Παραλήπτης:",
  "reviewAnonymous": "Ανώνυμο",
  "toastDeleted": "Το στοιχείο διαγράφηκε επιτυχώς.",
  "toastCompleted": "Το αίτημα ολοκληρώθηκε επιτυχώς.",
  "toastReverted": "Το αίτημα επανήλθε σε κατάσταση εκκρεμότητας.",
  "toastCancelled": "Η αποστολή ακυρώθηκε.",
  "toastAssigned": "Ο τεχνικός ανατέθηκε επιτυχώς!",
  "deleteConfirm": "Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτό το στοιχείο;"
}

# Verify key parity with en
print("Checking keys for pt:")
for s in en:
    missing_pt = set(en[s].keys()) - set(pt[s].keys())
    if missing_pt:
        print(f"  pt missing in {s}:", missing_pt)
    missing_el = set(en[s].keys()) - set(el[s].keys())
    if missing_el:
        print(f"  el missing in {s}:", missing_el)

# Save pt.json and el.json
with open(os.path.join(MESSAGES_DIR, 'pt.json'), 'w', encoding='utf-8') as f:
    json.dump(pt, f, ensure_ascii=False, indent=2)
    f.write('\n')

with open(os.path.join(MESSAGES_DIR, 'el.json'), 'w', encoding='utf-8') as f:
    json.dump(el, f, ensure_ascii=False, indent=2)
    f.write('\n')

print("Successfully generated pt.json and el.json!")

