# scripts/dict_european.py
# Complete European translations for tech and workspace:
# pl, de, fr, es, it, nl, da, sv, no, ru, uk

EUROPEAN_TECH_WS = {
  "pl": {
    "tech": {
      "headlineLead": "Bezpośrednio łącz się z klientami w Twojej okolicy",
      "actAsHelper": "profesjonalny fachowiec",
      "securitySessionNotice": "3-miesięczna sesja bezpieczeństwa: 90-dniowy losowy klucz dostępu wydawany na numer telefonu",
      "securitySessionExpiry": "Wygasanie sesji bezpieczeństwa",
      "securitySessionExpired": "Sesja bezpieczeństwa wygasła",
      "autoMaintainedDays": "dni automatycznego utrzymania",
      "operatingRegions": "Obszar działalności",
      "instantDispatchConnected": "Natychmiastowe połączenie z klientem",
      "registeredServices": "Zarejestrowane usługi",
      "categoriesRegisteredCount": "kategorie zarejestrowane",
      "editableInWorkspace": "Możliwość edycji w strefie fachowca",
      "openWorkspaceBtn": "Zarządzaj moją strefą fachowca",
      "statusActiveShort": "Dostępny do wyjazdów",
      "statusPausedShort": "Tymczasowo wstrzymany",
      "clickToToggle": "Kliknij, aby przełączyć",
      "hotlineNotice": "Główna linia wsparcia systemu",
      "helperPortal": "Portal Fachowca",
      "registerTab": "Rejestracja nowego fachowca",
      "loginTab": "Logowanie zarejestrowanego fachowca",
      "newHelperRegTitle": "Rejestracja nowego fachowca (3-miesięczny bezpieczny dostęp)",
      "existingHelperLoginTitle": "Logowanie zarejestrowanego fachowca",
      "newHelperRegDesc": "Bez konieczności podawania numeru PESEL. Pracuj swobodnie przez 3 miesiące tylko z numerem telefonu.",
      "existingHelperLoginDesc": "Wprowadź swój 3-miesięczny dedykowany klucz dostępu, aby wejść do strefy fachowca.",
      "accessKeyLabel": "3-miesięczny dedykowany klucz dostępu",
      "loginWithAccessKey": "Zaloguj się kluczem bezpieczeństwa (ważny 90 dni)",
      "loginKeyNotice": "Wprowadź 3-miesięczny klucz dostępu otrzymany przez SMS, aby natychmiast przejść do strefy fachowca.",
      "lostCodeBtn": "Zgubiłeś kod dostępu?",
      "reissueCodeTitle": "Ponowne wydanie klucza przez telefon",
      "getAccessKeyBtn": "Uzyskaj 3-miesięczny klucz bezpieczeństwa",
      "registerAndStart": "Zarejestruj się i rozpocznij usługę",
      "selectServices": "Wybierz kategorie usług",
      "selectServicesDesc": "Wybierz wszystkie kategorie, które możesz obsługiwać (możesz to zmienić w każdej chwili).",
      "selectedCount": " wybrano",
      "helperNameLabel": "Imię lub pseudonim fachowca",
      "agreeTerms": "Zapoznałem się z regulaminem i zasadami bezpieczeństwa LIFE.HELP i deklaruję rzetelną obsługę.",
      "keySentNotice": "Klucz dostępu wysłano pomyślnie SMS-em",
      "issuedAccessKey": "Wydany 3-miesięczny klucz dostępu",
      "copy": "Kopiuj",
      "copied": "Skopiowano!",
      "backToTechHome": "Powrót do strony głównej fachowca",
      "verifying": "Weryfikacja...",
      "changePhoneBtn": "Zmień numer",
      "enterAccessKeyError": "Wprowadź 3-miesięczny klucz bezpieczeństwa.",
      "enterNameError": "Wprowadź swoje imię lub pseudonim.",
      "selectServiceError": "Wybierz przynajmniej jedną kategorię usług.",
      "agreeTermsError": "Wymagana jest akceptacja regulaminu."
    },
    "workspace": {
      "title": "Strefa Fachowca",
      "mainHome": "← LIFE.HELP Strona główna",
      "helperHonorific": "Fachowiec",
      "verifiedHelper": "Zweryfikowany Fachowiec",
      "securitySessionBadge": "3-miesięczna sesja bezpieczeństwa",
      "daysRemaining": "dni pozostało",
      "signedDate": "Data podpisania",
      "viewContract": "Zobacz umowę elektroniczną",
      "logout": "Wyloguj się",
      "availTitle": "Zarządzanie dostępnością w czasie rzeczywistym",
      "statusActive": "Aktywny (Gotowy do wyjazdu)",
      "statusPaused": "Wstrzymany (Przerwa)",
      "descActive": "Jesteś obecnie dostępny do nowych zleceń. Przełącz na przerwę, gdy odpoczywasz.",
      "descPaused": "Przyjmowanie zleceń jest wstrzymane. Włącz ponownie, gdy będziesz gotowy do pracy.",
      "btnPause": "⏸ Wstrzymaj dostępność",
      "btnResume": "🟢 Wznów aktywność",
      "activeTitle": "Aktywny (Gotowy do wyjazdu)",
      "activeDesc": "Jesteś obecnie dostępny do nowych zleceń. Przełącz na przerwę, gdy odpoczywasz.",
      "pausedTitle": "Wstrzymany (Przerwa)",
      "pausedDesc": "Przyjmowanie zleceń jest wstrzymane. Włącz ponownie, gdy będziesz gotowy do pracy.",
      "resumeBtn": "🟢 Wznów aktywność",
      "pauseBtn": "⏸ Wstrzymaj dostępność",
      "hotlineTitle": "Główne infolinie dyspozytorskie",
      "hotlineDesc": "W razie problemów z aplikacją lub nagłych zmian (wypadek, zmiana rejonu) skontaktuj się z nami niezwłocznie.",
      "team1": "Infolinia Zespół 1 (Pilne)",
      "team2": "Infolinia Zespół 2 (Standard)",
      "call": "Zadzwoń",
      "sms": "SMS",
      "servicesTitle": "Zarządzanie kategoriami usług",
      "servicesDesc": "Kliknij, aby usunąć niedostępne usługi lub dodać nowe kwalifikacje w czasie rzeczywistym.",
      "categoriesActive": "Kategorie aktywne",
      "serviceActive": "Dostępna",
      "serviceDisabled": "Wyłączona",
      "regionsTitle": "Obsługiwane regiony wyjazdowe",
      "regionsDesc": "Kliknij ✕, aby usunąć region, w którym nie możesz działać, lub dodaj nowe obszary.",
      "regionsCount": "Ustawione regiony",
      "addRegionBtn": "Dodaj rejon wyjazdowy",
      "removeRegionTitle": "Usuń region",
      "scheduleTitle": "Harmonogram dostępności",
      "setHours": "Ustawione godziny",
      "hours24": "Gotowość do natychmiastowego wyjazdu 24/7",
      "contractTitle": "Kopia umowy powierzenia zadań LIFE.HELP",
      "contractName": "Imię i nazwisko",
      "contractPhone": "Numer telefonu",
      "contractResidentId": "PESEL / Identyfikator (zamaskowany)",
      "contractSignedAt": "Data i godzina zawarcia",
      "contractClauseTitle": "Klauzula zobowiązań i zgłaszania zmian",
      "contractClauseDesc": "Fachowiec zobowiązuje się do niezwłocznego powiadomienia centrali o niemożności pracy, zmianie kategorii usług lub rejonu.",
      "contractSignature": "Podpis elektroniczny potwierdzony",
      "close": "Zamknij",
      "minServiceAlert": "Wymagana jest przynajmniej jedna aktywna kategoria usług.",
      "serviceRemoved": "Kategoria usług została usunięta.",
      "serviceAdded": "Dodano nową kategorię usług.",
      "regionAdded": "Dodano nowy rejon wyjazdowy.",
      "minRegionAlert": "Wymagany jest przynajmniej jeden obsługiwany region.",
      "regionRemoved": "Rejon został usunięty.",
      "minDayAlert": "Wybierz przynajmniej jeden dzień aktywności.",
      "daysUpdated": "Harmonogram dni pracy został zaktualizowany.",
      "logoutConfirm": "Czy na pewno chcesz się wylogować ze strefy fachowca?",
      "adminChat": "Kontakt z administratorem",
      "openAdminChat": "Wiadomości od administratora",
      "adminChatTitle": "Czat 1:1 z administratorem centrali",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Odbiorca: Fachowiec",
      "adminChatEmpty": "Brak wiadomości od administratora.",
      "adminChatEmptyHint": "Zostaw zapytanie lub zgłoś sytuację awaryjną; administrator wkrótce odpowie.",
      "adminChatPlaceholder": "Wpisz wiadomość do administratora...",
      "adminChatSend": "Wyślij",
      "calendarClose": "Zamknij",
      "monthUnit": "Miesiąc",
      "adminChatRecipientCounselor": "Odbiorca: Konsultant",
      "adminNoticeBanner": "[Komunikat Centrali]",
      "unreadCount": "nieprzeczytanych",
      "preset24Hours": "24h natychmiastowa dyspozycyjność",
      "presetDay": "Dzienny (09:00 ~ 18:00)",
      "presetNight": "Nocny i awaryjny (18:00 ~ 09:00)",
      "presetMorning": "Poranny (09:00 ~ 13:00)",
      "presetAfternoon": "Popołudniowy (13:00 ~ 18:00)"
    }
  },
  "de": {
    "tech": {
      "headlineLead": "Direkt mit Kunden in Ihrer Nähe verbinden",
      "actAsHelper": "professionelle Fachkraft",
      "securitySessionNotice": "3-Monats-Sicherheitssitzung: 90-Tage-Zufalls-Sicherheitsschlüssel per Mobilfunknummer",
      "securitySessionExpiry": "Ablauf der Sicherheitssitzung",
      "securitySessionExpired": "Sicherheitssitzung abgelaufen",
      "autoMaintainedDays": "Tage automatisch erhalten",
      "operatingRegions": "Einsatzgebiete",
      "instantDispatchConnected": "Sofortige Kundenverbindung",
      "registeredServices": "Registrierte Dienstleistungen",
      "categoriesRegisteredCount": "Kategorien registriert",
      "editableInWorkspace": "Im Arbeitsbereich bearbeitbar",
      "openWorkspaceBtn": "Meinen Arbeitsbereich verwalten",
      "statusActiveShort": "Einsatzbereit",
      "statusPausedShort": "Vorübergehend pausiert",
      "clickToToggle": "Klicken zum Umschalten",
      "hotlineNotice": "Haupt-Support-Hotline des Systems"
    },
    "workspace": {
      "title": "Fachkraft-Arbeitsbereich",
      "mainHome": "← LIFE.HELP Startseite",
      "helperHonorific": "Fachkraft",
      "verifiedHelper": "Geprüfte Fachkraft",
      "securitySessionBadge": "3-Monate-Sicherheitssitzung",
      "daysRemaining": "Tage verbleibend",
      "signedDate": "Vertragsdatum",
      "viewContract": "Elektronischen Vertrag anzeigen",
      "logout": "Abmelden",
      "availTitle": "Echtzeit-Verfügbarkeitsverwaltung",
      "statusActive": "Aktiv (Sofort einsatzbereit)",
      "statusPaused": "Pausiert (Pause)",
      "descActive": "Sie sind für neue Einsätze verfügbar. Bei Pausen bitte umschalten.",
      "descPaused": "Einsatzvermittlung ist derzeit pausiert. Bei Arbeitsbereitschaft wieder aktivieren.",
      "btnPause": "⏸ Verfügbarkeit pausieren",
      "btnResume": "🟢 Verfügbarkeit aktivieren",
      "activeTitle": "Aktiv (Sofort einsatzbereit)",
      "activeDesc": "Sie sind für neue Einsätze verfügbar. Bei Pausen bitte umschalten.",
      "pausedTitle": "Pausiert (Pause)",
      "pausedDesc": "Einsatzvermittlung ist derzeit pausiert. Bei Arbeitsbereitschaft wieder aktivieren.",
      "resumeBtn": "🟢 Verfügbarkeit aktivieren",
      "pauseBtn": "⏸ Verfügbarkeit pausieren",
      "hotlineTitle": "Haupt-Dispositions-Hotlines",
      "hotlineDesc": "Bei Problemen mit der App oder dringenden Änderungen kontaktieren Sie uns bitte sofort.",
      "team1": "Hotline Team 1 (Dringend)",
      "team2": "Hotline Team 2 (Standard)",
      "call": "Anrufen",
      "sms": "SMS",
      "servicesTitle": "Dienstleistungskategorien verwalten",
      "servicesDesc": "Klicken Sie hier, um nicht verfügbare Dienste zu entfernen oder neue hinzuzufügen.",
      "categoriesActive": "Kategorien aktiv",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Deaktiviert",
      "regionsTitle": "Aktive Einsatzregionen",
      "regionsDesc": "Klicken Sie auf ✕, um Regionen zu entfernen, oder fügen Sie neue Einsatzorte hinzu.",
      "regionsCount": "Regionen eingestellt",
      "addRegionBtn": "Einsatzregion hinzufügen",
      "removeRegionTitle": "Region entfernen",
      "scheduleTitle": "Verfügbarkeitsplan",
      "setHours": "Eingestellte Arbeitszeiten",
      "hours24": "24h sofortige Einsatzbereitschaft",
      "contractTitle": "Kopie des elektronischen LIFE.HELP Partnervertrags",
      "contractName": "Vollständiger Name",
      "contractPhone": "Mobilnummer",
      "contractResidentId": "ID-Nummer (maskiert)",
      "contractSignedAt": "Vertragsabschlussdatum",
      "contractClauseTitle": "Verpflichtungs- und Mitteilungsklausel",
      "contractClauseDesc": "Die Fachkraft verpflichtet sich, Ausfälle oder Änderungen der Einsatzgebiete umgehend zu melden.",
      "contractSignature": "Elektronische Signatur bestätigt",
      "close": "Schließen",
      "minServiceAlert": "Mindestens eine Dienstleistungskategorie muss aktiv bleiben.",
      "serviceRemoved": "Dienstleistung wurde entfernt.",
      "serviceAdded": "Neue Dienstleistungskategorie hinzugefügt.",
      "regionAdded": "Einsatzgebiet erfolgreich hinzugefügt.",
      "minRegionAlert": "Mindestens eine Einsatzregion muss ausgewählt sein.",
      "regionRemoved": "Region wurde entfernt.",
      "minDayAlert": "Mindestens ein Arbeitstag muss ausgewählt sein.",
      "daysUpdated": "Arbeitstage wurden aktualisiert.",
      "logoutConfirm": "Möchten Sie sich wirklich aus dem Arbeitsbereich abmelden?",
      "adminChat": "Kontakt zur Zentrale",
      "openAdminChat": "Nachrichten der Zentrale",
      "adminChatTitle": "1:1-Online-Chat mit der Zentrale",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Empfänger: Fachkraft",
      "adminChatEmpty": "Keine Nachrichten von der Zentrale vorhanden.",
      "adminChatEmptyHint": "Hinterlassen Sie Anfragen oder Notfallmeldungen hier; die Zentrale prüft diese zeitnah.",
      "adminChatPlaceholder": "Nachricht an die Zentrale eingeben...",
      "adminChatSend": "Senden",
      "calendarClose": "Schließen",
      "monthUnit": "Monat",
      "adminChatRecipientCounselor": "Empfänger: Berater",
      "adminNoticeBanner": "[Mitteilung der Zentrale]",
      "unreadCount": "ungelesen",
      "preset24Hours": "24h sofort einsatzbereit",
      "presetDay": "Tagsüber (09:00 ~ 18:00)",
      "presetNight": "Nachts & Notdienst (18:00 ~ 09:00)",
      "presetMorning": "Vormittags (09:00 ~ 13:00)",
      "presetAfternoon": "Nachmittags (13:00 ~ 18:00)"
    }
  },
  "fr": {
    "tech": {
      "headlineLead": "Connectez-vous directement avec des clients près de chez vous",
      "actAsHelper": "professionnel qualifié",
      "securitySessionNotice": "Session sécurisée de 3 mois: clé d'accès aléatoire de 90 jours émise via numéro mobile",
      "securitySessionExpiry": "Expiration de la session de sécurité",
      "securitySessionExpired": "Session de sécurité expirée",
      "autoMaintainedDays": "jours maintenus automatiquement",
      "operatingRegions": "Zones d'intervention",
      "instantDispatchConnected": "Connexion client immédiate",
      "registeredServices": "Services enregistrés",
      "categoriesRegisteredCount": "catégories enregistrées",
      "editableInWorkspace": "Modifiable dans l'espace pro",
      "openWorkspaceBtn": "Gérer mon espace professionnel",
      "statusActiveShort": "Prêt pour intervention",
      "statusPausedShort": "Temporairement en pause",
      "clickToToggle": "Cliquer pour basculer",
      "hotlineNotice": "Ligne d'assistance principale du système"
    },
    "workspace": {
      "title": "Espace Professionnel",
      "mainHome": "← Accueil LIFE.HELP",
      "helperHonorific": "Professionnel",
      "verifiedHelper": "Professionnel vérifié",
      "securitySessionBadge": "Session sécurisée de 3 mois",
      "daysRemaining": "jours restants",
      "signedDate": "Date du contrat",
      "viewContract": "Voir le contrat électronique",
      "logout": "Déconnexion",
      "availTitle": "Gestion de disponibilité en temps réel",
      "statusActive": "Actif (Disponible pour intervention)",
      "statusPaused": "En pause (Repos)",
      "descActive": "Vous êtes prêt pour de nouvelles interventions. Basculez en pause lors d'un repos.",
      "descPaused": "Les affectations sont actuellement en pause. Réactivez dès que vous êtes disponible.",
      "btnPause": "⏸ Mettre en pause",
      "btnResume": "🟢 Réactiver disponibilité",
      "activeTitle": "Actif (Disponible pour intervention)",
      "activeDesc": "Vous êtes prêt pour de nouvelles interventions. Basculez en pause lors d'un repos.",
      "pausedTitle": "En pause (Repos)",
      "pausedDesc": "Les affectations sont actuellement en pause. Réactivez dès que vous êtes disponible.",
      "resumeBtn": "🟢 Réactiver disponibilité",
      "pauseBtn": "⏸ Mettre en pause",
      "hotlineTitle": "Lignes directes de dispatching",
      "hotlineDesc": "En cas d'indisponibilité ou d'urgence, veuillez contacter immédiatement notre équipe.",
      "team1": "Ligne Équipe 1 (Urgent)",
      "team2": "Ligne Équipe 2 (Standard)",
      "call": "Appeler",
      "sms": "SMS",
      "servicesTitle": "Gestion des catégories de services",
      "servicesDesc": "Cliquez pour retirer des services ou ajouter de nouvelles compétences en temps réel.",
      "categoriesActive": "Catégories actives",
      "serviceActive": "Actif",
      "serviceDisabled": "Désactivé",
      "regionsTitle": "Zones d'intervention actives",
      "regionsDesc": "Cliquez sur ✕ pour retirer une zone ou ajoutez de nouveaux secteurs.",
      "regionsCount": "Zones configurées",
      "addRegionBtn": "Ajouter une zone",
      "removeRegionTitle": "Retirer la zone",
      "scheduleTitle": "Planning de disponibilité",
      "setHours": "Horaires définis",
      "hours24": "Disponible 24h/24 pour intervention immédiate",
      "contractTitle": "Copie du contrat électronique de partenariat LIFE.HELP",
      "contractName": "Nom complet",
      "contractPhone": "Numéro de mobile",
      "contractResidentId": "Numéro d'identité (masqué)",
      "contractSignedAt": "Date et heure de signature",
      "contractClauseTitle": "Clause d'engagement et de notification",
      "contractClauseDesc": "Le professionnel s'engage à notifier immédiatement tout empêchement ou changement de secteur.",
      "contractSignature": "Signature électronique validée",
      "close": "Fermer",
      "minServiceAlert": "Au moins une catégorie de service doit être maintenue.",
      "serviceRemoved": "Catégorie retirée avec succès.",
      "serviceAdded": "Nouvelle catégorie ajoutée.",
      "regionAdded": "Zone ajoutée aux interventions.",
      "minRegionAlert": "Au moins une zone doit être configurée.",
      "regionRemoved": "Zone retirée avec succès.",
      "minDayAlert": "Au moins un jour de travail doit être sélectionné.",
      "daysUpdated": "Jours de disponibilité mis à jour.",
      "logoutConfirm": "Voulez-vous vraiment vous déconnecter de votre espace ?",
      "adminChat": "Contact Administration",
      "openAdminChat": "Messages de l'administration",
      "adminChatTitle": "Contact 1:1 en direct avec l'administration",
      "adminChatOnline": "EN LIGNE",
      "adminChatRecipient": "Destinataire: Professionnel",
      "adminChatEmpty": "Aucun message échangé avec l'administration.",
      "adminChatEmptyHint": "Laissez vos questions ou signalements d'urgence ici; l'administration les traitera rapidement.",
      "adminChatPlaceholder": "Votre message à l'administration...",
      "adminChatSend": "Envoyer",
      "calendarClose": "Fermer",
      "monthUnit": "Mois",
      "adminChatRecipientCounselor": "Destinataire: Conseiller",
      "adminNoticeBanner": "[Notification Administration]",
      "unreadCount": "non lus",
      "preset24Hours": "Intervention immédiate 24h/24",
      "presetDay": "Journée (09:00 ~ 18:00)",
      "presetNight": "Nuit & Urgences (18:00 ~ 09:00)",
      "presetMorning": "Matin (09:00 ~ 13:00)",
      "presetAfternoon": "Après-midi (13:00 ~ 18:00)"
    }
  },
  "es": {
    "tech": {
      "headlineLead": "Conéctese directamente con clientes en su área",
      "actAsHelper": "técnico profesional",
      "securitySessionNotice": "Sesión de seguridad de 3 meses: clave de acceso aleatoria de 90 días emitida por móvil",
      "securitySessionExpiry": "Caducidad de sesión de seguridad",
      "securitySessionExpired": "Sesión de seguridad caducada",
      "autoMaintainedDays": "días mantenidos automáticamente",
      "operatingRegions": "Regiones de atención",
      "instantDispatchConnected": "Conexión inmediata con clientes",
      "registeredServices": "Servicios registrados",
      "categoriesRegisteredCount": "categorías registradas",
      "editableInWorkspace": "Editable en el panel de trabajo",
      "openWorkspaceBtn": "Gestionar mi panel de trabajo",
      "statusActiveShort": "Disponible para servicios",
      "statusPausedShort": "Pausado temporalmente",
      "clickToToggle": "Haga clic para alternar",
      "hotlineNotice": "Línea de soporte principal del sistema"
    },
    "workspace": {
      "title": "Panel del Profesional",
      "mainHome": "← Inicio LIFE.HELP",
      "helperHonorific": "Especialista",
      "verifiedHelper": "Especialista verificado",
      "securitySessionBadge": "Sesión de seguridad de 3 meses",
      "daysRemaining": "días restantes",
      "signedDate": "Fecha del contrato",
      "viewContract": "Ver contrato electrónico",
      "logout": "Cerrar sesión",
      "availTitle": "Gestión de disponibilidad en tiempo real",
      "statusActive": "Activo (Disponible para servicios)",
      "statusPaused": "En pausa (Descanso)",
      "descActive": "Está listo para recibir nuevas solicitudes. Pause cuando descanse.",
      "descPaused": "Las solicitudes están temporalmente pausadas. Reactive al estar listo.",
      "btnPause": "⏸ Pausar disponibilidad",
      "btnResume": "🟢 Reanudar activo",
      "activeTitle": "Activo (Disponible para servicios)",
      "activeDesc": "Está listo para recibir nuevas solicitudes. Pause cuando descanse.",
      "pausedTitle": "En pausa (Descanso)",
      "pausedDesc": "Las solicitudes están temporalmente pausadas. Reactive al estar listo.",
      "resumeBtn": "🟢 Reanudar activo",
      "pauseBtn": "⏸ Pausar disponibilidad",
      "hotlineTitle": "Líneas de atención de despacho",
      "hotlineDesc": "En caso de emergencia o cambios imprevistos, contáctenos inmediatamente.",
      "team1": "Línea Equipo 1 (Urgente)",
      "team2": "Línea Equipo 2 (Estándar)",
      "call": "Llamar",
      "sms": "SMS",
      "servicesTitle": "Gestión de categorías de servicios",
      "servicesDesc": "Haga clic para eliminar servicios o añadir nuevas categorías en tiempo real.",
      "categoriesActive": "Categorías activas",
      "serviceActive": "Activo",
      "serviceDisabled": "Inactivo",
      "regionsTitle": "Regiones operativas de servicio",
      "regionsDesc": "Haga clic en ✕ para eliminar regiones o añada nuevas zonas de cobertura.",
      "regionsCount": "Regiones configuradas",
      "addRegionBtn": "Añadir región de servicio",
      "removeRegionTitle": "Eliminar región",
      "scheduleTitle": "Horario de disponibilidad",
      "setHours": "Horario configurado",
      "hours24": "Disponible 24 horas para despacho inmediato",
      "contractTitle": "Copia del contrato electrónico de encargo LIFE.HELP",
      "contractName": "Nombre completo",
      "contractPhone": "Número de teléfono",
      "contractResidentId": "Documento de identidad (enmascarado)",
      "contractSignedAt": "Fecha y hora de suscripción",
      "contractClauseTitle": "Cláusula de obligaciones y notificación",
      "contractClauseDesc": "El técnico se compromete a notificar de inmediato cualquier indisponibilidad o cambio de zona.",
      "contractSignature": "Firma electrónica verificada",
      "close": "Cerrar",
      "minServiceAlert": "Debe mantenerse al menos una categoría activa.",
      "serviceRemoved": "Categoría de servicio eliminada.",
      "serviceAdded": "Nueva categoría añadida con éxito.",
      "regionAdded": "Región añadida a la cobertura.",
      "minRegionAlert": "Debe haber al menos una región configurada.",
      "regionRemoved": "Región eliminada de la cobertura.",
      "minDayAlert": "Seleccione al menos un día de actividad.",
      "daysUpdated": "Días de disponibilidad actualizados.",
      "logoutConfirm": "¿Está seguro de que desea cerrar sesión en el panel?",
      "adminChat": "Contacto con administración",
      "openAdminChat": "Ver mensajes de administración",
      "adminChatTitle": "Contacto 1:1 en línea con administración",
      "adminChatOnline": "EN LÍNEA",
      "adminChatRecipient": "Destinatario: Especialista",
      "adminChatEmpty": "No hay mensajes intercambiados con la administración.",
      "adminChatEmptyHint": "Deje sus dudas o emergencias aquí; el administrador las revisará en breve.",
      "adminChatPlaceholder": "Escriba un mensaje para la administración...",
      "adminChatSend": "Enviar",
      "calendarClose": "Cerrar",
      "monthUnit": "Mes",
      "adminChatRecipientCounselor": "Destinatario: Asesor",
      "adminNoticeBanner": "[Aviso de Administración]",
      "unreadCount": "no leídos",
      "preset24Hours": "24h despacho inmediato",
      "presetDay": "Diurno (09:00 ~ 18:00)",
      "presetNight": "Nocturno y emergencias (18:00 ~ 09:00)",
      "presetMorning": "Mañana (09:00 ~ 13:00)",
      "presetAfternoon": "Tarde (13:00 ~ 18:00)"
    }
  },
  "it": {
    "tech": {
      "headlineLead": "Connettiti direttamente con i clienti nella tua zona",
      "actAsHelper": "professionista qualificato",
      "securitySessionNotice": "Sessione di sicurezza di 3 mesi: chiave di accesso casuale di 90 giorni emessa via cellulare",
      "securitySessionExpiry": "Scadenza sessione di sicurezza",
      "securitySessionExpired": "Sessione di sicurezza scaduta",
      "autoMaintainedDays": "giorni mantenuti automaticamente",
      "operatingRegions": "Zone di intervento",
      "instantDispatchConnected": "Connessione immediata con i clienti",
      "registeredServices": "Servizi registrati",
      "categoriesRegisteredCount": "categorie registrate",
      "editableInWorkspace": "Modificabile nell'area di lavoro",
      "openWorkspaceBtn": "Gestisci la mia area di lavoro",
      "statusActiveShort": "Disponibile per interventi",
      "statusPausedShort": "Temporaneamente in pausa",
      "clickToToggle": "Fai clic per cambiare",
      "hotlineNotice": "Linea di supporto principale del sistema",
      "helperPortal": "Portale del Professionista",
      "registerTab": "Registrazione nuovo professionista",
      "loginTab": "Accesso professionista registrato",
      "newHelperRegTitle": "Registrazione nuovo professionista (Accesso sicuro di 3 mesi)",
      "existingHelperLoginTitle": "Accesso professionista registrato",
      "newHelperRegDesc": "Senza codice fiscale: lavora liberamente per 3 mesi usando solo il tuo numero di cellulare.",
      "existingHelperLoginDesc": "Inserisci il tuo codice di sicurezza di 3 mesi per accedere immediatamente alla tua area.",
      "accessKeyLabel": "Chiave di accesso dedicata di 3 mesi",
      "loginWithAccessKey": "Accedi con chiave di sicurezza (valida 90 giorni)",
      "loginKeyNotice": "Inserisci la chiave ricevuta via SMS per accedere subito all'area di lavoro.",
      "lostCodeBtn": "Hai smarrito il codice?",
      "reissueCodeTitle": "Riemissione codice di 3 mesi via telefono",
      "getAccessKeyBtn": "Ottieni la chiave di accesso di 3 mesi",
      "registerAndStart": "Registrati e inizia l'attività",
      "selectServices": "Seleziona le categorie di servizio",
      "selectServicesDesc": "Seleziona tutte le categorie che puoi gestire (modificabili in seguito nell'area di lavoro).",
      "selectedCount": " selezionati",
      "helperNameLabel": "Nome del professionista (Nome d'arte o reale)",
      "agreeTerms": "Confermo di aver letto i regolamenti e le norme di sicurezza LIFE.HELP e garantisco un servizio puntuale.",
      "keySentNotice": "Chiave inviata con successo via SMS",
      "issuedAccessKey": "Chiave di accesso di 3 mesi emessa",
      "copy": "Copia",
      "copied": "Copiato!",
      "backToTechHome": "Torna alla pagina principale",
      "verifying": "Verifica in corso...",
      "changePhoneBtn": "Modifica numero",
      "enterAccessKeyError": "Inserisci la chiave di accesso di 3 mesi.",
      "enterNameError": "Inserisci il tuo nome o pseudonimo.",
      "selectServiceError": "Seleziona almeno una categoria di servizio.",
      "agreeTermsError": "È richiesta l'accettazione del regolamento."
    },
    "workspace": {
      "title": "Area di Lavoro Professionista",
      "mainHome": "← Home LIFE.HELP",
      "helperHonorific": "Professionista",
      "verifiedHelper": "Professionista verificato",
      "securitySessionBadge": "Sessione di sicurezza di 3 mesi",
      "daysRemaining": "giorni rimanenti",
      "signedDate": "Data del contratto",
      "viewContract": "Visualizza contratto elettronico",
      "logout": "Disconnetti",
      "availTitle": "Gestione disponibilità in tempo reale",
      "statusActive": "Attivo (Disponibile per interventi)",
      "statusPaused": "In pausa (Riposo)",
      "descActive": "Sei pronto per ricevere chiamate. Imposta la pausa durante il riposo.",
      "descPaused": "Le chiamate sono temporaneamente sospese. Riattiva quando sei pronto a lavorare.",
      "btnPause": "⏸ Metti in pausa",
      "btnResume": "🟢 Riattiva disponibilità",
      "activeTitle": "Attivo (Disponibile per interventi)",
      "activeDesc": "Sei pronto per ricevere chiamate. Imposta la pausa durante il riposo.",
      "pausedTitle": "In pausa (Riposo)",
      "pausedDesc": "Le chiamate sono temporaneamente sospese. Riattiva quando sei pronto a lavorare.",
      "resumeBtn": "🟢 Riattiva disponibilità",
      "pauseBtn": "⏸ Metti in pausa",
      "hotlineTitle": "Linee dirette di dispatching",
      "hotlineDesc": "In caso di problemi con l'app o variazioni urgenti, contattaci subito.",
      "team1": "Linea Team 1 (Urgente)",
      "team2": "Linea Team 2 (Standard)",
      "call": "Chiama",
      "sms": "SMS",
      "servicesTitle": "Gestione categorie di servizio",
      "servicesDesc": "Fai clic per rimuovere o aggiungere categorie in tempo reale.",
      "categoriesActive": "Categorie attive",
      "serviceActive": "Attivo",
      "serviceDisabled": "Disattivato",
      "regionsTitle": "Aree operative di servizio",
      "regionsDesc": "Fai clic su ✕ per rimuovere un'area o aggiungi nuove zone di copertura.",
      "regionsCount": "Aree configurate",
      "addRegionBtn": "Aggiungi area di servizio",
      "removeRegionTitle": "Rimuovi area",
      "scheduleTitle": "Orario di disponibilità",
      "setHours": "Orario impostato",
      "hours24": "Disponibilità 24/7 per intervento immediato",
      "contractTitle": "Copia del contratto di incarico elettronico LIFE.HELP",
      "contractName": "Nome e cognome",
      "contractPhone": "Numero di cellulare",
      "contractResidentId": "Codice identificativo (mascherato)",
      "contractSignedAt": "Data e ora di sottoscrizione",
      "contractClauseTitle": "Clausola di impegno e notifica variazioni",
      "contractClauseDesc": "Il professionista si impegna a notificare tempestivamente qualsiasi indisponibilità o variazione di zona.",
      "contractSignature": "Firma elettronica verificata",
      "close": "Chiudi",
      "minServiceAlert": "Almeno una categoria di servizio deve rimanere attiva.",
      "serviceRemoved": "Categoria rimossa con successo.",
      "serviceAdded": "Nuova categoria aggiunta.",
      "regionAdded": "Area aggiunta alla copertura.",
      "minRegionAlert": "È necessaria almeno un'area operativa.",
      "regionRemoved": "Area rimossa dalla copertura.",
      "minDayAlert": "Seleziona almeno un giorno di lavoro.",
      "daysUpdated": "Giorni di disponibilità aggiornati.",
      "logoutConfirm": "Vuoi davvero uscire dalla sessione di lavoro?",
      "adminChat": "Contatto amministrazione",
      "openAdminChat": "Messaggi dell'amministrazione",
      "adminChatTitle": "Chat 1:1 con l'amministrazione centrale",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Destinatario: Professionista",
      "adminChatEmpty": "Nessun messaggio con l'amministrazione.",
      "adminChatEmptyHint": "Lascia le tue domande o segnalazioni qui; l'amministrazione risponderà a breve.",
      "adminChatPlaceholder": "Scrivi un messaggio all'amministrazione...",
      "adminChatSend": "Invia",
      "calendarClose": "Chiudi",
      "monthUnit": "Mese",
      "adminChatRecipientCounselor": "Destinatario: Consulente",
      "adminNoticeBanner": "[Avviso Amministrazione]",
      "unreadCount": "non letti",
      "preset24Hours": "24h intervento immediato",
      "presetDay": "Diurno (09:00 ~ 18:00)",
      "presetNight": "Notturno & Emergenze (18:00 ~ 09:00)",
      "presetMorning": "Mattina (09:00 ~ 13:00)",
      "presetAfternoon": "Pomeriggio (13:00 ~ 18:00)"
    }
  },
  "nl": {
    "tech": {
      "headlineLead": "Direct verbinding met klanten in uw regio",
      "actAsHelper": "professionele vakman",
      "securitySessionNotice": "3-maanden veiligheidssessie: 90-dagen willekeurige toegangssleutel via mobiel nummer",
      "securitySessionExpiry": "Vervaldatum beveiligingssessie",
      "securitySessionExpired": "Beveiligingssessie verlopen",
      "autoMaintainedDays": "dagen automatisch behouden",
      "operatingRegions": "Werkgebieden",
      "instantDispatchConnected": "Directe klantverbinding",
      "registeredServices": "Geregistreerde diensten",
      "categoriesRegisteredCount": "categorieën geregistreerd",
      "editableInWorkspace": "Aanpasbaar in werkpaneel",
      "openWorkspaceBtn": "Mijn werkpaneel beheren",
      "statusActiveShort": "Beschikbaar voor ritten",
      "statusPausedShort": "Tijdelijk gepauzeerd",
      "clickToToggle": "Klik om te wisselen",
      "hotlineNotice": "Primaire hulplijn van het systeem",
      "helperPortal": "Vakmanportaal",
      "registerTab": "Nieuwe vakmanregistratie",
      "loginTab": "Inloggen bestaande vakman",
      "newHelperRegTitle": "Nieuwe vakmanregistratie (3 maanden veilige toegang)",
      "existingHelperLoginTitle": "Inloggen geregistreerde vakman",
      "newHelperRegDesc": "Geen BSN vereist. Werk 3 maanden vrij met alleen uw mobiele nummer.",
      "existingHelperLoginDesc": "Voer uw 3-maandelijkse toegangscode in om direct in te loggen.",
      "accessKeyLabel": "Toegangscode voor 3 maanden",
      "loginWithAccessKey": "Inloggen met beveiligingscode (90 dagen geldig)",
      "loginKeyNotice": "Voer de per sms ontvangen code in om direct naar uw werkpaneel te gaan.",
      "lostCodeBtn": "Toegangscode kwijt?",
      "reissueCodeTitle": "Code opnieuw aanvragen via mobiel",
      "getAccessKeyBtn": "3-maanden beveiligingscode aanvragen",
      "registerAndStart": "Registreren & Starten",
      "selectServices": "Selecteer dienstcategorieën",
      "selectServicesDesc": "Kies alle diensten die u kunt uitvoeren (later aanpasbaar).",
      "selectedCount": " geselecteerd",
      "helperNameLabel": "Naam of bijnaam van vakman",
      "agreeTerms": "Ik ga akkoord met de service- en veiligheidsvoorwaarden van LIFE.HELP.",
      "keySentNotice": "Toegangscode succesvol verzonden via sms",
      "issuedAccessKey": "Uitgegeven toegangscode voor 3 maanden",
      "copy": "Kopiëren",
      "copied": "Gekopieerd!",
      "backToTechHome": "Terug naar startpagina",
      "verifying": "Verifiëren...",
      "changePhoneBtn": "Nummer wijzigen",
      "enterAccessKeyError": "Voer uw 3-maanden beveiligingscode in.",
      "enterNameError": "Voer uw naam of bijnaam in.",
      "selectServiceError": "Selecteer ten minste één dienstcategorie.",
      "agreeTermsError": "U moet akkoord gaan met de voorwaarden."
    },
    "workspace": {
      "title": "Werkpaneel Vakman",
      "mainHome": "← LIFE.HELP Startpagina",
      "helperHonorific": "Vakman",
      "verifiedHelper": "Geverifieerde Vakman",
      "securitySessionBadge": "3-maanden beveiligingssessie",
      "daysRemaining": "dagen resterend",
      "signedDate": "Contractdatum",
      "viewContract": "Elektronisch contract inzien",
      "logout": "Uitloggen",
      "availTitle": "Realtime beschikbaarheidsbeheer",
      "statusActive": "Actief (Beschikbaar voor ritten)",
      "statusPaused": "Gepauzeerd (Pauze)",
      "descActive": "U bent klaar voor nieuwe opdrachten. Schakel naar pauze bij rust.",
      "descPaused": "Oproepen zijn tijdelijk gepauzeerd. Activeer zodra u klaar bent om te werken.",
      "btnPause": "⏸ Beschikbaarheid pauzeren",
      "btnResume": "🟢 Beschikbaarheid hervatten",
      "activeTitle": "Actief (Beschikbaar voor ritten)",
      "activeDesc": "U bent klaar voor nieuwe opdrachten. Schakel naar pauze bij rust.",
      "pausedTitle": "Gepauzeerd (Pauze)",
      "pausedDesc": "Oproepen zijn tijdelijk gepauzeerd. Activeer zodra u klaar bent om te werken.",
      "resumeBtn": "🟢 Beschikbaarheid hervatten",
      "pauseBtn": "⏸ Beschikbaarheid pauzeren",
      "hotlineTitle": "Hoofdtelefoonlijnen voor dispatch",
      "hotlineDesc": "Bij problemen met de app of noodsituaties neemt u direct contact op.",
      "team1": "Hulplijn Team 1 (Spoed)",
      "team2": "Hulplijn Team 2 (Standaard)",
      "call": "Bellen",
      "sms": "SMS",
      "servicesTitle": "Dienstcategorieën beheren",
      "servicesDesc": "Klik om diensten uit te sluiten of nieuwe kwalificaties realtime toe te voegen.",
      "categoriesActive": "Categorieën actief",
      "serviceActive": "Actief",
      "serviceDisabled": "Uitgeschakeld",
      "regionsTitle": "Werkgebieden",
      "regionsDesc": "Klik op ✕ om een gebied te verwijderen of voeg nieuwe regio's toe.",
      "regionsCount": "Gebieden ingesteld",
      "addRegionBtn": "Werkgebied toevoegen",
      "removeRegionTitle": "Gebied verwijderen",
      "scheduleTitle": "Beschikbaarheidsrooster",
      "setHours": "Ingestelde uren",
      "hours24": "24/7 direct inzetbaar",
      "contractTitle": "Kopie van LIFE.HELP elektronische overeenkomst",
      "contractName": "Volledige naam",
      "contractPhone": "Mobiel nummer",
      "contractResidentId": "Identificatienummer (gemaskeerd)",
      "contractSignedAt": "Ondertekeningstijdstip",
      "contractClauseTitle": "Verplichtings- en meldingsclausule",
      "contractClauseDesc": "De vakman verplicht zich om wijzigingen in beschikbaarheid of werkgebied direct te melden.",
      "contractSignature": "Elektronische handtekening bevestigd",
      "close": "Sluiten",
      "minServiceAlert": "Er moet minimaal één actieve dienstcategorie overblijven.",
      "serviceRemoved": "Dienstcategorie is verwijderd.",
      "serviceAdded": "Nieuwe categorie succesvol toegevoegd.",
      "regionAdded": "Gebied toegevoegd aan werkzones.",
      "minRegionAlert": "Minimaal één regio moet ingesteld zijn.",
      "regionRemoved": "Gebied is verwijderd.",
      "minDayAlert": "Selecteer minimaal één werkdag.",
      "daysUpdated": "Beschikbaarheidsdagen zijn bijgewerkt.",
      "logoutConfirm": "Weet u zeker dat u wilt uitloggen uit uw sessie?",
      "adminChat": "Contact met administratie",
      "openAdminChat": "Berichten van beheerder",
      "adminChatTitle": "1:1 Live chat met de centrale",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Ontvanger: Vakman",
      "adminChatEmpty": "Geen berichten uitgewisseld met de centrale.",
      "adminChatEmptyHint": "Laat hier uw vragen of spoedmeldingen achter; de beheerder reageert z.s.m.",
      "adminChatPlaceholder": "Typ bericht voor beheerder...",
      "adminChatSend": "Verzenden",
      "calendarClose": "Sluiten",
      "monthUnit": "Maand",
      "adminChatRecipientCounselor": "Ontvanger: Adviseur",
      "adminNoticeBanner": "[Centrale Mededeling]",
      "unreadCount": "ongelezen",
      "preset24Hours": "24u directe inzetbaarheid",
      "presetDay": "Overdag (09:00 ~ 18:00)",
      "presetNight": "Nacht & Spoed (18:00 ~ 09:00)",
      "presetMorning": "Ochtend (09:00 ~ 13:00)",
      "presetAfternoon": "Middag (13:00 ~ 18:00)"
    }
  },
  "da": {
    "tech": {
      "headlineLead": "Forbind direkte med kunder i dit nærområde",
      "actAsHelper": "professionel fagperson",
      "securitySessionNotice": "3-måneders sikkerhedssession: 90-dages tilfældig adgangsnøgle udstedt via mobilnummer",
      "securitySessionExpiry": "Udløb af sikkerhedssession",
      "securitySessionExpired": "Sikkerhedssession udløbet",
      "autoMaintainedDays": "dage vedligeholdt automatisk",
      "operatingRegions": "Betjeningsområder",
      "instantDispatchConnected": "Øjeblikkelig kundekontakt",
      "registeredServices": "Registrerede tjenester",
      "categoriesRegisteredCount": "kategorier registreret",
      "editableInWorkspace": "Kan redigeres i arbejdsrummet",
      "openWorkspaceBtn": "Administrer mit arbejdsrum",
      "statusActiveShort": "Klar til udkald",
      "statusPausedShort": "Midlertidigt sat på pause",
      "clickToToggle": "Klik for at skifte",
      "hotlineNotice": "Systemets primære support-hotline",
      "hotline": "Akut hotline",
      "helperPortal": "Fagpersonsportal",
      "registerTab": "Ny registrering",
      "loginTab": "Log ind for eksisterende",
      "newHelperRegTitle": "Ny registrering (3 måneders sikker adgang)",
      "existingHelperLoginTitle": "Log ind som eksisterende fagperson",
      "newHelperRegDesc": "Intet CPR-nummer påkrævet. Arbejd frit i 3 måneder med blot dit mobilnummer.",
      "existingHelperLoginDesc": "Indtast din 3-måneders adgangskode for at logge ind med det samme.",
      "accessKeyLabel": "3-måneders dedikeret adgangskode",
      "loginWithAccessKey": "Log ind med sikkerhedskode (gyldig i 90 dage)",
      "loginKeyNotice": "Indtast adgangskoden modtaget via SMS for at gå til arbejdsrummet.",
      "lostCodeBtn": "Mistet adgangskode?",
      "reissueCodeTitle": "Genudsted kode via mobilnummer",
      "getAccessKeyBtn": "Modtag 3-måneders sikkerhedskode",
      "registerAndStart": "Registrer og start",
      "selectServices": "Vælg servicekategorier",
      "selectServicesDesc": "Vælg alle kategorier, du kan varetage (kan opdateres senere).",
      "selectedCount": " valgt",
      "helperNameLabel": "Navn eller kaldenavn",
      "agreeTerms": "Jeg accepterer LIFE.HELP-retningslinjer og sikkerhedsregler.",
      "keySentNotice": "Adgangskode afsendt via SMS",
      "issuedAccessKey": "Udstedt 3-måneders adgangskode",
      "copy": "Kopiér",
      "copied": "Kopieret!",
      "backToTechHome": "Tilbage til forsiden",
      "verifying": "Bekræfter...",
      "changePhoneBtn": "Skift nummer",
      "enterAccessKeyError": "Indtast venligst din adgangskode.",
      "enterNameError": "Indtast venligst dit navn.",
      "selectServiceError": "Vælg mindst én kategori.",
      "agreeTermsError": "Accept af betingelser er påkrævet."
    },
    "workspace": {
      "title": "Fagpersons Arbejdsrum",
      "mainHome": "← LIFE.HELP Forside",
      "helperHonorific": "Fagperson",
      "verifiedHelper": "Verificeret fagperson",
      "securitySessionBadge": "3-måneders sikkerhedssession",
      "daysRemaining": "dage tilbage",
      "signedDate": "Kontraktdato",
      "viewContract": "Vis elektronisk kontrakt",
      "logout": "Log ud",
      "availTitle": "Styring af tilgængelighed i realtid",
      "statusActive": "Aktiv (Klar til udkald)",
      "statusPaused": "På pause (Pause)",
      "descActive": "Du er åben for nye udkald. Skift til pause, når du holder fri.",
      "descPaused": "Udkald er midlertidigt sat på pause. Slå til igen, når du er klar.",
      "btnPause": "⏸ Sæt på pause",
      "btnResume": "🟢 Genoptag aktiv",
      "activeTitle": "Aktiv (Klar til udkald)",
      "activeDesc": "Du er åben for nye udkald. Skift til pause, når du holder fri.",
      "pausedTitle": "På pause (Pause)",
      "pausedDesc": "Udkald er midlertidigt sat på pause. Slå til igen, når du er klar.",
      "resumeBtn": "🟢 Genoptag aktiv",
      "pauseBtn": "⏸ Sæt på pause",
      "hotlineTitle": "Primære vagtcentral-hotlines",
      "hotlineDesc": "Kontakt os straks ved app-problemer eller akutte ændringer.",
      "team1": "Hotline Team 1 (Akut)",
      "team2": "Hotline Team 2 (Standard)",
      "call": "Ring",
      "sms": "SMS",
      "servicesTitle": "Administrer servicekategorier",
      "servicesDesc": "Klik for at fjerne utilgængelige ydelser eller tilføje nye.",
      "categoriesActive": "Aktive kategorier",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Deaktiveret",
      "regionsTitle": "Betjente regioner",
      "regionsDesc": "Klik på ✕ for at fjerne områder eller tilføj nye zoner.",
      "regionsCount": "Regioner konfigureret",
      "addRegionBtn": "Tilføj betjeningsområde",
      "removeRegionTitle": "Fjern region",
      "scheduleTitle": "Tilgængelighedsplan",
      "setHours": "Indstillede arbejdstider",
      "hours24": "24/7 øjeblikkelig udkaldsberedskab",
      "contractTitle": "Kopi af LIFE.HELP elektronisk aftale",
      "contractName": "Fulde navn",
      "contractPhone": "Mobilnummer",
      "contractResidentId": "ID-nummer (maskeret)",
      "contractSignedAt": "Underskrivelsestidspunkt",
      "contractClauseTitle": "Forpligtelses- og underretningsklausul",
      "contractClauseDesc": "Fagpersonen forpligter sig til omgående at melde forfald eller ændringer i områder.",
      "contractSignature": "Elektronisk underskrift bekræftet",
      "close": "Luk",
      "minServiceAlert": "Mindst én servicekategori skal forblive aktiv.",
      "serviceRemoved": "Kategori er fjernet.",
      "serviceAdded": "Ny kategori tilføjet.",
      "regionAdded": "Område tilføjet dækningen.",
      "minRegionAlert": "Mindst én region skal vælges.",
      "regionRemoved": "Område fjernet.",
      "minDayAlert": "Vælg mindst én arbejdsdag.",
      "daysUpdated": "Arbejdsdage opdateret.",
      "logoutConfirm": "Vil du logge ud af arbejdsrummet?",
      "adminChat": "Kontakt ledelsen",
      "openAdminChat": "Beskeder fra ledelsen",
      "adminChatTitle": "1:1 Live chat med centralen",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Modtager: Fagperson",
      "adminChatEmpty": "Ingen beskeder fra ledelsen.",
      "adminChatEmptyHint": "Send spørgsmål eller hastebeskeder her; vi svarer hurtigst muligt.",
      "adminChatPlaceholder": "Skriv besked til ledelsen...",
      "adminChatSend": "Send",
      "calendarClose": "Luk",
      "monthUnit": "Måned",
      "adminChatRecipientCounselor": "Modtager: Rådgiver",
      "adminNoticeBanner": "[Besked fra centralen]",
      "unreadCount": "ulæste",
      "preset24Hours": "24 timers akutberedskab",
      "presetDay": "Dagtimer (09:00 ~ 18:00)",
      "presetNight": "Nat & Akut (18:00 ~ 09:00)",
      "presetMorning": "Formiddag (09:00 ~ 13:00)",
      "presetAfternoon": "Eftermiddag (13:00 ~ 18:00)"
    }
  },
  "sv": {
    "tech": {
      "headlineLead": "Koppla direkt ihop med kunder i ditt närområde",
      "actAsHelper": "professionell specialist",
      "securitySessionNotice": "3-månaders säkerhetssession: 90-dagars slumpmässig åtkomstnyckel via mobilnummer",
      "securitySessionExpiry": "Säkerhetssessionens utgång",
      "securitySessionExpired": "Säkerhetssessionen har gått ut",
      "autoMaintainedDays": "dagar bibehålls automatiskt",
      "operatingRegions": "Tjänsteområden",
      "instantDispatchConnected": "Omedelbar kundkontakt",
      "registeredServices": "Registrerade tjänster",
      "categoriesRegisteredCount": "kategorier registrerade",
      "editableInWorkspace": "Kan redigeras i arbetsytan",
      "openWorkspaceBtn": "Hantera min arbetsyta",
      "statusActiveShort": "Tillgänglig för uppdrag",
      "statusPausedShort": "Tillfälligt pausad",
      "clickToToggle": "Klicka för att växla",
      "hotlineNotice": "Systemets primära support-hotline",
      "helperPortal": "Specialistportal",
      "registerTab": "Nyregistrering",
      "loginTab": "Inloggning för registrerad",
      "newHelperRegTitle": "Nyregistrering (3 månaders säker åtkomst)",
      "existingHelperLoginTitle": "Inloggning för befintlig specialist",
      "newHelperRegDesc": "Inget personnummer krävs. Arbeta fritt i 3 månader med enbart ditt mobilnummer.",
      "existingHelperLoginDesc": "Ange din 3-månaderskod för att logga in direkt.",
      "accessKeyLabel": "Dedikerad åtkomstkod för 3 månader",
      "loginWithAccessKey": "Logga in med säkerhetskod (giltig i 90 dagar)",
      "loginKeyNotice": "Ange koden från SMS för att komma direkt till din arbetsyta.",
      "lostCodeBtn": "Förlorat koden?",
      "reissueCodeTitle": "Återutfärda kod via mobilnummer",
      "getAccessKeyBtn": "Få 3-månaders säkerhetskod",
      "registerAndStart": "Registrera och börja arbeta",
      "selectServices": "Välj tjänstekategorier",
      "selectServicesDesc": "Välj alla kategorier du behärskar (kan uppdateras senare).",
      "selectedCount": " valda",
      "helperNameLabel": "Namn eller smeknamn",
      "agreeTerms": "Jag godkänner villkoren och säkerhetsreglerna för LIFE.HELP.",
      "keySentNotice": "Åtkomstkod skickad via SMS",
      "issuedAccessKey": "Utfärdad 3-månaderskod",
      "copy": "Kopiera",
      "copied": "Kopierat!",
      "backToTechHome": "Tillbaka till startsidan",
      "verifying": "Verifierar...",
      "changePhoneBtn": "Ändra nummer",
      "enterAccessKeyError": "Ange din åtkomstkod.",
      "enterNameError": "Ange ditt namn.",
      "selectServiceError": "Välj minst en kategori.",
      "agreeTermsError": "Du måste godkänna villkoren."
    },
    "workspace": {
      "title": "Specialistens Arbetsyta",
      "mainHome": "← LIFE.HELP Startsida",
      "helperHonorific": "Specialisten",
      "verifiedHelper": "Verifierad specialist",
      "securitySessionBadge": "3-månaders säkerhetssession",
      "daysRemaining": "dagar kvar",
      "signedDate": "Avtalsdatum",
      "viewContract": "Visa elektroniskt avtal",
      "logout": "Logga ut",
      "availTitle": "Hantering av tillgänglighet i realtid",
      "statusActive": "Aktiv (Tillgänglig för uppdrag)",
      "statusPaused": "Pausad (Rast)",
      "descActive": "Du är tillgänglig för nya uppdrag. Växla till paus när du vilar.",
      "descPaused": "Uppdrag är tillfälligt pausade. Aktivera igen när du är redo att arbeta.",
      "btnPause": "⏸ Pausa tillgänglighet",
      "btnResume": "🟢 Återuppta aktiv",
      "activeTitle": "Aktiv (Tillgänglig för uppdrag)",
      "activeDesc": "Du är tillgänglig för nya uppdrag. Växla till paus när du vilar.",
      "pausedTitle": "Pausad (Rast)",
      "pausedDesc": "Uppdrag är tillfälligt pausade. Aktivera igen när du är redo att arbeta.",
      "resumeBtn": "🟢 Återuppta aktiv",
      "pauseBtn": "⏸ Pausa tillgänglighet",
      "hotlineTitle": "Vaktcentralens kontaktlinjer",
      "hotlineDesc": "Vid tekniska problem eller akuta händelser, kontakta oss omedelbart.",
      "team1": "Hotline Team 1 (Akut)",
      "team2": "Hotline Team 2 (Standard)",
      "call": "Ring",
      "sms": "SMS",
      "servicesTitle": "Hantera tjänstekategorier",
      "servicesDesc": "Klicka för att ta bort tjänster eller lägga till nya i realtid.",
      "categoriesActive": "Aktiva kategorier",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Inaktiverad",
      "regionsTitle": "Aktiva verksamhetsområden",
      "regionsDesc": "Klicka på ✕ för att ta bort områden eller lägg till nya zoner.",
      "regionsCount": "Områden konfigurerade",
      "addRegionBtn": "Lägg till område",
      "removeRegionTitle": "Ta bort område",
      "scheduleTitle": "Tillgänglighetsschema",
      "setHours": "Inställda arbetstider",
      "hours24": "24/7 omedelbar beredskap",
      "contractTitle": "Kopia av LIFE.HELP elektroniskt avtal",
      "contractName": "Fullständigt namn",
      "contractPhone": "Mobilnummer",
      "contractResidentId": "ID-nummer (maskerat)",
      "contractSignedAt": "Tidpunkt för undertecknande",
      "contractClauseTitle": "Förpliktelse- och underrättelseklausul",
      "contractClauseDesc": "Specialisten förbinder sig att omedelbart meddela frånvaro eller förändringar i verksamhetsområde.",
      "contractSignature": "Elektronisk signatur bekräftad",
      "close": "Stäng",
      "minServiceAlert": "Minst en tjänstekategori måste förbli aktiv.",
      "serviceRemoved": "Kategori borttagen.",
      "serviceAdded": "Ny kategori har lagts till.",
      "regionAdded": "Område har lagts till.",
      "minRegionAlert": "Minst ett område måste vara inställt.",
      "regionRemoved": "Område borttaget.",
      "minDayAlert": "Välj minst en arbetsdag.",
      "daysUpdated": "Arbetsdagar har uppdaterats.",
      "logoutConfirm": "Är du säker på att du vill logga ut från arbetsytan?",
      "adminChat": "Kontakt med ledningen",
      "openAdminChat": "Meddelanden från ledningen",
      "adminChatTitle": "1:1 Live chatt med centralen",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Mottagare: Specialist",
      "adminChatEmpty": "Inga meddelanden med centralen.",
      "adminChatEmptyHint": "Lämna frågor eller akuta ärenden här; vi svarar så fort vi kan.",
      "adminChatPlaceholder": "Skriv meddelande till ledningen...",
      "adminChatSend": "Skicka",
      "calendarClose": "Stäng",
      "monthUnit": "Månad",
      "adminChatRecipientCounselor": "Mottagare: Rådgivare",
      "adminNoticeBanner": "[Centralt Meddelande]",
      "unreadCount": "olästa",
      "preset24Hours": "24h direkt utryckningsberedskap",
      "presetDay": "Dagtid (09:00 ~ 18:00)",
      "presetNight": "Natt & Akut (18:00 ~ 09:00)",
      "presetMorning": "Förmiddag (09:00 ~ 13:00)",
      "presetAfternoon": "Eftermiddag (13:00 ~ 18:00)"
    }
  },
  "no": {
    "tech": {
      "headlineLead": "Koble direkte til kunder i ditt nærområde",
      "actAsHelper": "profesjonell fagperson",
      "securitySessionNotice": "3-måneders sikkerhetsøkt: 90-dagers tilfeldig tilgangsnøkkel utstedt via mobilnummer",
      "securitySessionExpiry": "Utløp for sikkerhetsøkt",
      "securitySessionExpired": "Sikkerhetsøkten er utløpt",
      "autoMaintainedDays": "dager opprettholdt automatisk",
      "operatingRegions": "Tjenesteområder",
      "instantDispatchConnected": "Umiddelbar kundekontakt",
      "registeredServices": "Registrerte tjenester",
      "categoriesRegisteredCount": "kategorier registrert",
      "editableInWorkspace": "Kan redigeres i arbeidsområdet",
      "openWorkspaceBtn": "Administrer mitt arbeidsområde",
      "statusActiveShort": "Klar for uttrykning",
      "statusPausedShort": "Midlertidig satt på pause",
      "clickToToggle": "Klikk for å bytte",
      "hotlineNotice": "Systemets primære støttetelefon",
      "hotline": "Akutt-hotline",
      "helperPortal": "Fagpersonportal",
      "registerTab": "Nyregistrering",
      "loginTab": "Logg inn for registrert",
      "newHelperRegTitle": "Nyregistrering (3 måneders sikker tilgang)",
      "existingHelperLoginTitle": "Logg inn som registrert fagperson",
      "newHelperRegDesc": "Ingen personnummer påkrevd. Jobb fritt i 3 måneder med kun mobilnummeret ditt.",
      "existingHelperLoginDesc": "Skriv inn din 3-måneders tilgangskode for å logge inn umiddelbart.",
      "accessKeyLabel": "Dedikert tilgangskode for 3 måneder",
      "loginWithAccessKey": "Logg inn med sikkerhetskode (gyldig i 90 dager)",
      "loginKeyNotice": "Skriv inn koden mottatt på SMS for å gå direkte til arbeidsområdet.",
      "lostCodeBtn": "Mistet koden?",
      "reissueCodeTitle": "Få tilsendt ny kode på mobil",
      "getAccessKeyBtn": "Motta 3-måneders sikkerhetskode",
      "registerAndStart": "Registrer og start",
      "selectServices": "Velg tjenestekategorier",
      "selectServicesDesc": "Velg alle kategorier du kan utføre (kan endres senere).",
      "selectedCount": " valgt",
      "helperNameLabel": "Navn eller kallenavn",
      "agreeTerms": "Jeg godtar vilkårene og sikkerhetsreglene til LIFE.HELP.",
      "keySentNotice": "Tilgangskode sendt på SMS",
      "issuedAccessKey": "Utstedt 3-månederskode",
      "copy": "Kopier",
      "copied": "Kopiert!",
      "backToTechHome": "Tilbake til startsiden",
      "verifying": "Bekrefter...",
      "changePhoneBtn": "Endre nummer",
      "enterAccessKeyError": "Skriv inn tilgangskoden din.",
      "enterNameError": "Skriv inn navnet ditt.",
      "selectServiceError": "Velg minst én kategori.",
      "agreeTermsError": "Du må godta vilkårene."
    },
    "workspace": {
      "title": "Fagpersonens Arbeidsområde",
      "mainHome": "← LIFE.HELP Forside",
      "helperHonorific": "Fagperson",
      "verifiedHelper": "Verifisert fagperson",
      "securitySessionBadge": "3-måneders sikkerhetsøkt",
      "daysRemaining": "dager igjen",
      "signedDate": "Kontraktdato",
      "viewContract": "Vis elektronisk kontrakt",
      "logout": "Logg ut",
      "availTitle": "Sanntidsstyring av tilgjengelighet",
      "statusActive": "Aktiv (Klar for utrykning)",
      "statusPaused": "På pause (Pause)",
      "descActive": "Du er tilgjengelig for nye oppdrag. Bytt til pause når du hviler.",
      "descPaused": "Oppdrag er midlertidig satt på pause. Slå på igjen når du er klar.",
      "btnPause": "⏸ Pause tilgjengelighet",
      "btnResume": "🟢 Gjenoppta aktiv",
      "activeTitle": "Aktiv (Klar for utrykning)",
      "activeDesc": "Du er tilgjengelig for nye oppdrag. Bytt til pause når du hviler.",
      "pausedTitle": "På pause (Pause)",
      "pausedDesc": "Oppdrag er midlertidig satt på pause. Slå på igjen når du er klar.",
      "resumeBtn": "🟢 Gjenoppta aktiv",
      "pauseBtn": "⏸ Pause tilgjengelighet",
      "hotlineTitle": "Vaktsentralens hovedlinjer",
      "hotlineDesc": "Ved app-problemer eller akutte endringer, ta kontakt umiddelbart.",
      "team1": "Hotline Team 1 (Akutt)",
      "team2": "Hotline Team 2 (Standard)",
      "call": "Ring",
      "sms": "SMS",
      "servicesTitle": "Administrer tjenestekategorier",
      "servicesDesc": "Klikk for å fjerne tjenester eller legge til nye i sanntid.",
      "categoriesActive": "Aktive kategorier",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Deaktivert",
      "regionsTitle": "Aktive oppdragsområder",
      "regionsDesc": "Klikk på ✕ for å fjerne områder eller legg til nye soner.",
      "regionsCount": "Områder konfigurert",
      "addRegionBtn": "Legg til område",
      "removeRegionTitle": "Fjern område",
      "scheduleTitle": "Tilgjengelighetsplan",
      "setHours": "Innstilt arbeidstid",
      "hours24": "24/7 umiddelbar beredskap",
      "contractTitle": "Kopi av LIFE.HELP elektronisk avtale",
      "contractName": "Fullt navn",
      "contractPhone": "Mobilnummer",
      "contractResidentId": "ID-nummer (maskert)",
      "contractSignedAt": "Tidspunkt for signering",
      "contractClauseTitle": "Forpliktelses- og varslingsklausul",
      "contractClauseDesc": "Fagpersonen forplikter seg til umiddelbart å varsle om fravær eller endringer i oppdragsområde.",
      "contractSignature": "Elektronisk signatur bekreftet",
      "close": "Lukk",
      "minServiceAlert": "Minst én tjenestekategori må forbli aktiv.",
      "serviceRemoved": "Kategori fjernet.",
      "serviceAdded": "Ny kategori lagt til.",
      "regionAdded": "Område lagt til.",
      "minRegionAlert": "Minst ett område må være konfigurert.",
      "regionRemoved": "Område fjernet.",
      "minDayAlert": "Velg minst én arbeidsdag.",
      "daysUpdated": "Arbeidsdager oppdatert.",
      "logoutConfirm": "Er du sikker på at du vil logge ut fra arbeidsområdet?",
      "adminChat": "Kontakt ledelsen",
      "openAdminChat": "Meldinger fra ledelsen",
      "adminChatTitle": "1:1 Direktekontakt med sentralen",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Mottaker: Fagperson",
      "adminChatEmpty": "Ingen meldinger utvekslet med ledelsen.",
      "adminChatEmptyHint": "Legg igjen spørsmål eller hastemeldinger her; vi svarer så snart som mulig.",
      "adminChatPlaceholder": "Skriv melding til ledelsen...",
      "adminChatSend": "Send",
      "calendarClose": "Lukk",
      "monthUnit": "Måned",
      "adminChatRecipientCounselor": "Mottaker: Rådgiver",
      "adminNoticeBanner": "[Sentral Varsling]",
      "unreadCount": "uleste",
      "preset24Hours": "24t akuttberedskap",
      "presetDay": "Dagtid (09:00 ~ 18:00)",
      "presetNight": "Natt & Akutt (18:00 ~ 09:00)",
      "presetMorning": "Formiddag (09:00 ~ 13:00)",
      "presetAfternoon": "Ettermiddag (13:00 ~ 18:00)"
    }
  },
  "ru": {
    "tech": {
      "headlineLead": "Прямая связь с клиентами в вашем районе",
      "actAsHelper": "профессиональный мастер",
      "securitySessionNotice": "3-месячная сессия безопасности: 90-дневный случайный ключ доступа по номеру телефона",
      "securitySessionExpiry": "Истечение сессии безопасности",
      "securitySessionExpired": "Сессия безопасности истекла",
      "autoMaintainedDays": "дней автоматического продления",
      "operatingRegions": "Регионы обслуживания",
      "instantDispatchConnected": "Мгновенная связь с клиентом",
      "registeredServices": "Зарегистрированные услуги",
      "categoriesRegisteredCount": "категорий зарегистрировано",
      "editableInWorkspace": "Редактируется в рабочем кабинете",
      "openWorkspaceBtn": "Управление моим кабинетом",
      "statusActiveShort": "Готов к выезду",
      "statusPausedShort": "Временно на паузе",
      "clickToToggle": "Нажмите для переключения",
      "hotlineNotice": "Основная горячая линия системы"
    },
    "workspace": {
      "title": "Кабинет Мастера",
      "mainHome": "← Главная LIFE.HELP",
      "helperHonorific": "Мастер",
      "verifiedHelper": "Проверенный мастер",
      "securitySessionBadge": "3-месячная сессия безопасности",
      "daysRemaining": "дней осталось",
      "signedDate": "Дата договора",
      "viewContract": "Электронный договор",
      "logout": "Выйти",
      "availTitle": "Управление доступностью в реальном времени",
      "statusActive": "Активен (Готов к выезду)",
      "statusPaused": "На паузе (Перерыв)",
      "descActive": "Вы принимаете новые вызовы. Переключите на паузу во время отдыха.",
      "descPaused": "Прием заказов приостановлен. Включите активность, когда будете готовы работать.",
      "btnPause": "⏸ Приостановить доступность",
      "btnResume": "🟢 Возобновить выезды",
      "activeTitle": "Активен (Готов к выезду)",
      "activeDesc": "Вы принимаете новые вызовы. Переключите на паузу во время отдыха.",
      "pausedTitle": "На паузе (Перерыв)",
      "pausedDesc": "Прием заказов приостановлен. Включите активность, когда будете готовы работать.",
      "resumeBtn": "🟢 Возобновить выезды",
      "pauseBtn": "⏸ Приостановить доступность",
      "hotlineTitle": "Горячая линия диспетчерской службы",
      "hotlineDesc": "При сбоях в приложении или срочных изменениях немедленно свяжитесь с нами.",
      "team1": "Линия Группы 1 (Срочно)",
      "team2": "Линия Группы 2 (Стандарт)",
      "call": "Позвонить",
      "sms": "SMS",
      "servicesTitle": "Управление категориями услуг",
      "servicesDesc": "Нажмите, чтобы исключить или добавить категории услуг в реальном времени.",
      "categoriesActive": "Активные категории",
      "serviceActive": "Активно",
      "serviceDisabled": "Отключено",
      "regionsTitle": "Зоны обслуживания",
      "regionsDesc": "Нажмите ✕, чтобы убрать район, или добавьте новые зоны выезда.",
      "regionsCount": "Районов настроено",
      "addRegionBtn": "Добавить район выезда",
      "removeRegionTitle": "Удалить район",
      "scheduleTitle": "График доступности",
      "setHours": "Установленные часы",
      "hours24": "Круглосуточный мгновенный выезд 24/7",
      "contractTitle": "Копия электронного договора LIFE.HELP",
      "contractName": "ФИО",
      "contractPhone": "Номер мобильного телефона",
      "contractResidentId": "Идентификатор (скрыт)",
      "contractSignedAt": "Дата и время заключения",
      "contractClauseTitle": "Обязательства и уведомление об изменениях",
      "contractClauseDesc": "Мастер обязуется немедленно уведомить диспетчерскую при невозможности выезда или смене района.",
      "contractSignature": "Электронная подпись подтверждена",
      "close": "Закрыть",
      "minServiceAlert": "Должна быть активна хотя бы одна категория услуг.",
      "serviceRemoved": "Категория услуг исключена.",
      "serviceAdded": "Новая категория добавлена.",
      "regionAdded": "Район добавлен в зону обслуживания.",
      "minRegionAlert": "Необходимо указать хотя бы один район.",
      "regionRemoved": "Район исключен.",
      "minDayAlert": "Выберите хотя бы один рабочий день.",
      "daysUpdated": "Дни выездов обновлены.",
      "logoutConfirm": "Вы действительно хотите выйти из кабинета?",
      "adminChat": "Связь с администрацией",
      "openAdminChat": "Сообщения от администрации",
      "adminChatTitle": "Онлайн-чат 1:1 с центральным диспетчером",
      "adminChatOnline": "ОНЛАЙН",
      "adminChatRecipient": "Получатель: Мастер",
      "adminChatEmpty": "Нет сообщений от администрации.",
      "adminChatEmptyHint": "Оставьте вопрос или срочное обращение здесь; диспетчер оперативно ответит.",
      "adminChatPlaceholder": "Введите сообщение для диспетчера...",
      "adminChatSend": "Отправить",
      "calendarClose": "Закрыть",
      "monthUnit": "Месяц",
      "adminChatRecipientCounselor": "Получатель: Консультант",
      "adminNoticeBanner": "[Сообщение Центра]",
      "unreadCount": "непрочитанных",
      "preset24Hours": "Круглосуточно 24/7",
      "presetDay": "Дневной (09:00 ~ 18:00)",
      "presetNight": "Ночной и экстренный (18:00 ~ 09:00)",
      "presetMorning": "Утренний (09:00 ~ 13:00)",
      "presetAfternoon": "Дневной (13:00 ~ 18:00)"
    }
  },
  "uk": {
    "tech": {
      "headlineLead": "Прямий зв'язок із клієнтами у вашому районі",
      "actAsHelper": "професійний фахівець",
      "securitySessionNotice": "3-місячна сесія безпеки: 90-денний випадковий ключ доступу за номером телефону",
      "securitySessionExpiry": "Закінчення сесії безпеки",
      "securitySessionExpired": "Сесія безпеки закінчилася",
      "autoMaintainedDays": "днів автоматичного продовження",
      "operatingRegions": "Регіони обслуговування",
      "instantDispatchConnected": "Миттєвий зв'язок із клієнтом",
      "registeredServices": "Зареєстровані послуги",
      "categoriesRegisteredCount": "категорій зареєстровано",
      "editableInWorkspace": "Редагується в робочому кабінеті",
      "openWorkspaceBtn": "Керування моїм кабінетом",
      "statusActiveShort": "Готовий до виїзду",
      "statusPausedShort": "Тимчасово на паузі",
      "clickToToggle": "Натисніть для перемикання",
      "hotlineNotice": "Головна гаряча лінія системи",
      "helperPortal": "Портал Фахівця",
      "registerTab": "Реєстрація нового фахівця",
      "loginTab": "Вхід для зареєстрованих",
      "newHelperRegTitle": "Реєстрація нового фахівця (3-місячний безпечний доступ)",
      "existingHelperLoginTitle": "Вхід для зареєстрованого фахівця",
      "newHelperRegDesc": "Без податкового номера. Працюйте вільно 3 місяці лише за номером телефону.",
      "existingHelperLoginDesc": "Введіть свій 3-місячний код доступу для миттєвого входу.",
      "accessKeyLabel": "3-місячний ключ безпеки",
      "loginWithAccessKey": "Увійти за ключем безпеки (діє 90 днів)",
      "loginKeyNotice": "Введіть код з SMS для швидкого доступу до кабінету.",
      "lostCodeBtn": "Втратили код?",
      "reissueCodeTitle": "Перевипустити код за номером телефону",
      "getAccessKeyBtn": "Отримати 3-місячний код доступу",
      "registerAndStart": "Зареєструватися та розпочати роботу",
      "selectServices": "Оберіть категорії послуг",
      "selectServicesDesc": "Виберіть усі послуги, які ви можете надавати (можна змінити згодом).",
      "selectedCount": " обрано",
      "helperNameLabel": "Ім'я або позивний фахівця",
      "agreeTerms": "Погоджуюся з правилами та нормами безпеки LIFE.HELP.",
      "keySentNotice": "Ключ доступу успішно надіслано в SMS",
      "issuedAccessKey": "Виданий 3-місячний ключ доступу",
      "copy": "Копіювати",
      "copied": "Скопійовано!",
      "backToTechHome": "Назад на головну",
      "verifying": "Перевірка...",
      "changePhoneBtn": "Змінити номер",
      "enterAccessKeyError": "Введіть ключ доступу.",
      "enterNameError": "Введіть своє ім'я.",
      "selectServiceError": "Оберіть хоча б одну категорію.",
      "agreeTermsError": "Потрібно погодитися з правилами."
    },
    "workspace": {
      "title": "Кабінет Фахівця",
      "mainHome": "← Головна LIFE.HELP",
      "helperHonorific": "Фахівець",
      "verifiedHelper": "Перевірений фахівець",
      "securitySessionBadge": "3-місячна сесія безпеки",
      "daysRemaining": "днів залишилося",
      "signedDate": "Дата договору",
      "viewContract": "Переглянути електронний договір",
      "logout": "Вийти",
      "availTitle": "Керування доступністю в реальному часі",
      "statusActive": "Активний (Готовий до виїзду)",
      "statusPaused": "На паузі (Перерва)",
      "descActive": "Ви приймаєте нові виклики. Перемкніть на паузу під час відпочинку.",
      "descPaused": "Прийом замовлень призупинено. Увімкніть активність, коли будете готові.",
      "btnPause": "⏸ Призупинити доступність",
      "btnResume": "🟢 Відновити виїзди",
      "activeTitle": "Активний (Готовий до виїзду)",
      "activeDesc": "Ви приймаєте нові виклики. Перемкніть на паузу під час відпочинку.",
      "pausedTitle": "На паузі (Перерва)",
      "pausedDesc": "Прийом замовлень призупинено. Увімкніть активність, коли будете готові.",
      "resumeBtn": "🟢 Відновити виїзди",
      "pauseBtn": "⏸ Призупинити доступність",
      "hotlineTitle": "Гарячі лінії диспетчерської служби",
      "hotlineDesc": "У разі збоїв у застосунку або термінових змін негайно зв'яжіться з нами.",
      "team1": "Лінія Команди 1 (Терміново)",
      "team2": "Лінія Команди 2 (Стандарт)",
      "call": "Зателефонувати",
      "sms": "SMS",
      "servicesTitle": "Керування категоріями послуг",
      "servicesDesc": "Натисніть, щоб вилучити або додати послуги в реальному часі.",
      "categoriesActive": "Активні категорії",
      "serviceActive": "Активно",
      "serviceDisabled": "Вимкнено",
      "regionsTitle": "Зони обслуговування",
      "regionsDesc": "Натисніть ✕, щоб вилучити район, або додайте нові зони.",
      "regionsCount": "Районів налаштовано",
      "addRegionBtn": "Додати район виїзду",
      "removeRegionTitle": "Вилучити район",
      "scheduleTitle": "Графік доступності",
      "setHours": "Встановлені години",
      "hours24": "Цілодобовий негайний виїзд 24/7",
      "contractTitle": "Копія електронного договору LIFE.HELP",
      "contractName": "ПІБ",
      "contractPhone": "Номер мобільного телефону",
      "contractResidentId": "Ідентифікатор (приховано)",
      "contractSignedAt": "Дата та час підписання",
      "contractClauseTitle": "Зобов'язання та повідомлення про зміни",
      "contractClauseDesc": "Фахівець зобов'язується негайно повідомити диспетчера про неможливість виїзду або зміну району.",
      "contractSignature": "Електронний підпис підтверджено",
      "close": "Закрити",
      "minServiceAlert": "Має бути активна хоча б одна категорія послуг.",
      "serviceRemoved": "Категорію послуг вилучено.",
      "serviceAdded": "Нову категорію успішно додано.",
      "regionAdded": "Район додано до зони обслуговування.",
      "minRegionAlert": "Потрібно налаштувати хоча б один район.",
      "regionRemoved": "Район вилучено.",
      "minDayAlert": "Оберіть хоча б один робочий день.",
      "daysUpdated": "Робочі дні оновлено.",
      "logoutConfirm": "Ви дійсно бажаєте вийти з кабінету фахівця?",
      "adminChat": "Зв'язок із адміністрацією",
      "openAdminChat": "Повідомлення від адміністрації",
      "adminChatTitle": "Онлайн-чат 1:1 із центральним диспетчером",
      "adminChatOnline": "ОНЛАЙН",
      "adminChatRecipient": "Одержувач: Фахівець",
      "adminChatEmpty": "Немає повідомлень від адміністрації.",
      "adminChatEmptyHint": "Залиште запитання або термінове звернення тут; ми оперативно відповімо.",
      "adminChatPlaceholder": "Введіть повідомлення для диспетчера...",
      "adminChatSend": "Надіслати",
      "calendarClose": "Закрити",
      "monthUnit": "Місяць",
      "adminChatRecipientCounselor": "Одержувач: Консультант",
      "adminNoticeBanner": "[Оповіщення Центру]",
      "unreadCount": "непрочитаних",
      "preset24Hours": "Цілодобово 24/7",
      "presetDay": "Денний (09:00 ~ 18:00)",
      "presetNight": "Нічний та екстрений (18:00 ~ 09:00)",
      "presetMorning": "Ранковий (09:00 ~ 13:00)",
      "presetAfternoon": "Денний (13:00 ~ 18:00)"
    }
  }
}
