# scripts/dict_all_remaining.py
# Complete dictionary updates for tech and workspace across all languages

ALL_TECH_WS = {
  "id": {
    "tech": {
      "operatingRegions": "Wilayah Layanan",
      "instantDispatchConnected": "Koneksi Langsung Pelanggan",
      "registeredServices": "Layanan Terdaftar",
      "categoriesRegisteredCount": "kategori terdaftar",
      "editableInWorkspace": "Dapat diubah di panel teknisi",
      "openWorkspaceBtn": "Kelola Panel Teknisi Saya",
      "securitySessionNotice": "Sesi Keamanan 3 Bulan: kunci akses acak 90 hari diterbitkan via ponsel",
      "securitySessionExpiry": "Masa Kedaluwarsa Sesi Keamanan",
      "securitySessionExpired": "Sesi Keamanan Kedaluwarsa",
      "autoMaintainedDays": "hari dipertahankan otomatis",
      "statusActiveShort": "Siap Melayani",
      "statusPausedShort": "Dijeda Sementara",
      "clickToToggle": "Klik untuk beralih",
      "hotlineNotice": "Saluran Siaga Utama Sistem"
    },
    "workspace": {
      "activeTitle": "Aktif (Siap Melayani)",
      "activeDesc": "Anda siap menerima panggilan baru. Ubah ke jeda saat istirahat.",
      "pauseBtn": "Jeda Ketersediaan",
      "pausedTitle": "Dijeda (Istirahat)",
      "pausedDesc": "Panggilan ditunda sementara. Aktifkan kembali saat siap bekerja.",
      "resumeBtn": "Lanjutkan Aktif",
      "hotlineTitle": "Saluran Siaga Utama Dispatch",
      "hotlineDesc": "Jika akses aplikasi bermasalah atau ada perubahan darurat, segera hubungi tim kami.",
      "team1": "Hotline Tim 1 (Darurat)",
      "team2": "Hotline Tim 2 (Standar)",
      "call": "Panggil",
      "sms": "SMS",
      "servicesTitle": "Manajemen Kategori Layanan",
      "servicesDesc": "Klik untuk menghapus layanan atau menambah kategori baru secara real-time.",
      "categoriesActive": "Kategori Aktif",
      "serviceActive": "Aktif",
      "serviceDisabled": "Nonaktif",
      "regionsTitle": "Wilayah Operasional Layanan",
      "regionsDesc": "Klik ✕ untuk menghapus wilayah, atau tambahkan area baru.",
      "regionsCount": "Wilayah Ditetapkan",
      "addRegionBtn": "Tambah Wilayah"
    }
  },
  "th": {
    "tech": {
      "operatingRegions": "พื้นที่ให้บริการ",
      "instantDispatchConnected": "เชื่อมต่อลูกค้าทันที",
      "registeredServices": "บริการที่ลงทะเบียน",
      "categoriesRegisteredCount": "หมวดหมู่ที่ลงทะเบียน",
      "editableInWorkspace": "แก้ไขได้ในหน้าช่าง",
      "openWorkspaceBtn": "จัดการหน้าพื้นที่ทำงานของฉัน",
      "securitySessionNotice": "เซสชันความปลอดภัย 3 เดือน: รหัสเข้าถึง 90 วันออกให้ผ่านเบอร์มือถือ",
      "securitySessionExpiry": "วันหมดอายุเซสชันความปลอดภัย",
      "securitySessionExpired": "เซสชันความปลอดภัยหมดอายุแล้ว",
      "autoMaintainedDays": "วันรักษาสถานะอัตโนมัติ",
      "statusActiveShort": "พร้อมออกปฏิบัติงาน",
      "statusPausedShort": "หยุดพักชั่วคราว",
      "clickToToggle": "คลิกเพื่อสลับสถานะ",
      "hotlineNotice": "สายด่วนหลักของระบบ"
    },
    "workspace": {
      "activeTitle": "เปิดใช้งาน (พร้อมออกปฏิบัติงาน)",
      "activeDesc": "คุณเปิดรับงานบริการใหม่ได้ตลอดเวลา เปลี่ยนเป็นพักเมื่อต้องการหยุดพัก",
      "pauseBtn": "หยุดพักชั่วคราว",
      "pausedTitle": "พักการทำงาน (ช่วงพัก)",
      "pausedDesc": "ระงับการเรียกงานชั่วคราว สลับกลับเป็นพร้อมทำงานเมื่อต้องการรับงาน",
      "resumeBtn": "กลับมาพร้อมทำงาน",
      "hotlineTitle": "สายด่วนแจ้งสถานะการออกปฏิบัติงาน",
      "hotlineDesc": "หากเข้าแอปไม่ได้หรือมีเหตุฉุกเฉิน โปรดติดต่อทีมงานทันที",
      "team1": "สายด่วนทีม 1 (ด่วน)",
      "team2": "สายด่วนทีม 2 (ทั่วไป)",
      "call": "โทร",
      "sms": "SMS",
      "servicesTitle": "จัดการหมวดหมู่บริการ",
      "servicesDesc": "คลิกเพื่อนำบริการที่ไม่พร้อมออก หรือเพิ่มหมวดหมู่ใหม่ได้ทันที",
      "categoriesActive": "หมวดหมู่ที่พร้อมทำงาน",
      "serviceActive": "พร้อมบริการ",
      "serviceDisabled": "ปิดบริการ",
      "regionsTitle": "พื้นที่ออกปฏิบัติงาน",
      "regionsDesc": "คลิก ✕ เพื่อลบพื้นที่ หรือเพิ่มพื้นที่ที่พร้อมให้บริการใหม่",
      "regionsCount": "พื้นที่ที่ตั้งค่าไว้",
      "addRegionBtn": "เพิ่มพื้นที่"
    }
  },
  "tr": {
    "tech": {
      "headlineLead": "Bölgenizdeki müşterilerle doğrudan bağlantı kurun",
      "operatingRegions": "Hizmet Bölgeleri",
      "instantDispatchConnected": "Müşteri ile Anında Bağlantı",
      "registeredServices": "Kayıtlı Hizmetler",
      "categoriesRegisteredCount": "kategori kayıtlı",
      "editableInWorkspace": "Usta panelinde düzenlenebilir",
      "openWorkspaceBtn": "Usta Panelimi Yönet",
      "securitySessionNotice": "3 Aylık Güvenlik Oturumu: cep telefonu ile verilen 90 günlük rastgele erişim anahtarı",
      "securitySessionExpiry": "Güvenlik Oturumu Bitişi",
      "securitySessionExpired": "Güvenlik Oturumu Sona Erdi",
      "autoMaintainedDays": "gün otomatik korunur",
      "statusActiveShort": "Göreve Hazır",
      "statusPausedShort": "Geçici Olarak Molada",
      "clickToToggle": "Değiştirmek için tıkla",
      "hotlineNotice": "Ana Sistem Yardım Hattı"
    },
    "workspace": {
      "activeTitle": "Aktif (Göreve Hazır)",
      "activeDesc": "Şu anda yeni görev çağrılarına açıksınız. Mola verdiğinizde duraklatın.",
      "pauseBtn": "Mola Ver",
      "pausedTitle": "Duraklatıldı (Molada)",
      "pausedDesc": "Görev çağrıları geçici olarak duraklatıldı. Hazır olduğunuzda aktifleştirin.",
      "resumeBtn": "Aktif Et",
      "hotlineTitle": "Ana Görev Durumu Yardım Hatları",
      "hotlineDesc": "Uygulamaya erişilemezse veya acil bir durum oluşursa hemen bizi arayın.",
      "team1": "1. Ekip Hattı (Acil)",
      "team2": "2. Ekip Hattı (Standart)",
      "call": "Ara",
      "sms": "SMS",
      "servicesTitle": "Hizmet Kategorisi Yönetimi",
      "servicesDesc": "Hizmetleri kaldırmak veya yeni kategoriler eklemek için tıklayın.",
      "categoriesActive": "Aktif Kategoriler",
      "serviceActive": "Aktif",
      "serviceDisabled": "Devre Dışı",
      "regionsTitle": "Hizmet Verilen Bölgeler",
      "regionsDesc": "Bölgeleri kaldırmak için ✕ işaretine tıklayın veya yeni alanlar ekleyin.",
      "regionsCount": "Ayarlanan Bölgeler",
      "addRegionBtn": "Bölge Ekle"
    }
  },
  "nl": {
    "tech": {
      "headlineLead": "Maak direct verbinding met klanten in uw omgeving",
      "operatingRegions": "Werkgebieden",
      "instantDispatchConnected": "Directe klantverbinding",
      "registeredServices": "Geregistreerde diensten",
      "categoriesRegisteredCount": "categorieën geregistreerd",
      "editableInWorkspace": "Aanpasbaar in vakmanruimte",
      "openWorkspaceBtn": "Mijn vakmanruimte beheren",
      "securitySessionNotice": "3-maanden beveiligingssessie: 90-dagen willekeurige toegangssleutel via mobiel nummer",
      "securitySessionExpiry": "Verval beveiligingssessie",
      "securitySessionExpired": "Beveiligingssessie verlopen",
      "autoMaintainedDays": "dagen automatisch behouden",
      "statusActiveShort": "Klaar voor inzet",
      "statusPausedShort": "Tijdelijk gepauzeerd",
      "clickToToggle": "Klik om te wisselen",
      "hotlineNotice": "Hoofdsysteem-hotline"
    },
    "workspace": {
      "activeTitle": "Actief (Beschikbaar voor dispatch)",
      "activeDesc": "U bent beschikbaar voor nieuwe opdrachten. Schakel naar pauze als u rust neemt.",
      "pauseBtn": "Beschikbaarheid pauzeren",
      "pausedTitle": "Gepauzeerd (Pauze)",
      "pausedDesc": "Oproepen zijn tijdelijk gepauzeerd. Activeer opnieuw als u klaar bent.",
      "resumeBtn": "Actief hervatten",
      "hotlineTitle": "Belangrijkste dispatch-hotlines",
      "hotlineDesc": "Neem direct contact op bij problemen met de app of urgente wijzigingen.",
      "team1": "Team 1 Hotline (Urgent)",
      "team2": "Team 2 Hotline (Standaard)",
      "call": "Bellen",
      "sms": "SMS",
      "servicesTitle": "Beheer van dienstcategorieën",
      "servicesDesc": "Klik om diensten te verwijderen of realtime nieuwe categorieën toe te voegen.",
      "categoriesActive": "Actieve categorieën",
      "serviceActive": "Actief",
      "serviceDisabled": "Uitgeschakeld",
      "regionsTitle": "Actieve werkregio's",
      "regionsDesc": "Klik op ✕ om regio's te verwijderen of voeg nieuwe gebieden toe.",
      "regionsCount": "Ingestelde regio's",
      "addRegionBtn": "Regio toevoegen"
    }
  },
  "sv": {
    "tech": {
      "headlineLead": "Anslut direkt till kunder i ditt närområde",
      "operatingRegions": "Verksamhetsområden",
      "instantDispatchConnected": "Direkt kundkoppling",
      "registeredServices": "Registrerade tjänster",
      "categoriesRegisteredCount": "kategorier registrerade",
      "editableInWorkspace": "Kan redigeras i hantverkarpanelen",
      "openWorkspaceBtn": "Hantera min hantverkarpanel",
      "securitySessionNotice": "3-månaders säkerhetssession: 90-dagars slumpmässig åtkomstnyckel via mobilnummer",
      "securitySessionExpiry": "Säkerhetssession upphör",
      "securitySessionExpired": "Säkerhetssessionen har upphört",
      "autoMaintainedDays": "dagar bibehålls automatiskt",
      "statusActiveShort": "Tillgänglig för utryckning",
      "statusPausedShort": "Tillfälligt pausad",
      "clickToToggle": "Klicka för att växla",
      "hotlineNotice": "Huvudsystemets jourlinje"
    },
    "workspace": {
      "activeTitle": "Aktiv (Tillgänglig för utryckning)",
      "activeDesc": "Du är tillgänglig för nya uppdrag. Pausa vid rast.",
      "pauseBtn": "Pausa tillgänglighet",
      "pausedTitle": "Pausad (Paus)",
      "pausedDesc": "Utryckningssamtal är pausade. Återaktivera när du är redo.",
      "resumeBtn": "Återuppta aktiv",
      "hotlineTitle": "Jourlinjer för utryckningsstatus",
      "hotlineDesc": "Kontakta vårt team omedelbart vid appproblem eller akuta ändringar.",
      "team1": "Team 1 Jourlinje (Akut)",
      "team2": "Team 2 Jourlinje (Standard)",
      "call": "Ring",
      "sms": "SMS",
      "servicesTitle": "Hantering av tjänstekategorier",
      "servicesDesc": "Klicka för att ta bort tjänster eller lägga till nya kategorier i realtid.",
      "categoriesActive": "Aktiva kategorier",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Inaktiverad",
      "regionsTitle": "Aktiva tjänsteområden",
      "regionsDesc": "Klicka på ✕ för att ta bort områden, eller lägg till nya tillgängliga områden.",
      "regionsCount": "Inställda regioner",
      "addRegionBtn": "Lägg till region"
    }
  },
  "da": {
    "tech": {
      "headlineLead": "Opret direkte forbindelse til kunder i dit nærområde",
      "operatingRegions": "Serviceområder",
      "instantDispatchConnected": "Direkte kundeforbindelse",
      "registeredServices": "Registrerede tjenester",
      "categoriesRegisteredCount": "kategorier registreret",
      "editableInWorkspace": "Kan redigeres i håndværkerpanelet",
      "openWorkspaceBtn": "Administrer mit håndværkerpanel",
      "securitySessionNotice": "3-måneders sikkerhedssession: 90-dages tilfældig adgangsnøgle via mobilnummer",
      "securitySessionExpiry": "Sikkerhedssession udløber",
      "securitySessionExpired": "Sikkerhedssession udløbet",
      "autoMaintainedDays": "dage opretholdes automatisk",
      "statusActiveShort": "Klar til udrykning",
      "statusPausedShort": "Midlertidigt sat på pause",
      "clickToToggle": "Klik for at skifte",
      "hotlineNotice": "Hovedsystemets hotline"
    },
    "workspace": {
      "activeTitle": "Aktiv (Klar til udrykning)",
      "activeDesc": "Du er tilgængelig for nye opgaver. Skift til pause ved hvil.",
      "pauseBtn": "Sæt på pause",
      "pausedTitle": "Sat på pause (Pause)",
      "pausedDesc": "Opkald er sat på pause. Genaktiver, når du er klar.",
      "resumeBtn": "Genoptag aktiv",
      "hotlineTitle": "Udrykningshotlines",
      "hotlineDesc": "Kontakt os straks, hvis du ikke har app-adgang, eller ved akutte ændringer.",
      "team1": "Team 1 Hotline (Akut)",
      "team2": "Team 2 Hotline (Standard)",
      "call": "Ring",
      "sms": "SMS",
      "servicesTitle": "Styring af servicekategorier",
      "servicesDesc": "Klik for at fjerne utilgængelige tjenester eller tilføje nye kategorier.",
      "categoriesActive": "Aktive kategorier",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Deaktiveret",
      "regionsTitle": "Aktive serviceområder",
      "regionsDesc": "Klik på ✕ for at fjerne områder, eller tilføj nye tilgængelige områder.",
      "regionsCount": "Angivne regioner",
      "addRegionBtn": "Tilføj region"
    }
  },
  "no": {
    "tech": {
      "headlineLead": "Koble deg direkte til kunder i ditt nærområde",
      "operatingRegions": "Tjenesteområder",
      "instantDispatchConnected": "Direkte kundekontakt",
      "registeredServices": "Registrerte tjenester",
      "categoriesRegisteredCount": "kategorier registrert",
      "editableInWorkspace": "Kan redigeres i håndverkerpanelet",
      "openWorkspaceBtn": "Administrer mitt håndverkerpanel",
      "securitySessionNotice": "3-måneders sikkerhetsøkt: 90-dagers tilfeldig tilgangsnøkkel via mobilnummer",
      "securitySessionExpiry": "Sikkerhetsøkt utløper",
      "securitySessionExpired": "Sikkerhetsøkt utløpt",
      "autoMaintainedDays": "dager opprettholdes automatisk",
      "statusActiveShort": "Klar for utrykning",
      "statusPausedShort": "Midlertidig satt på pause",
      "clickToToggle": "Klikk for å veksle",
      "hotlineNotice": "Hovedsystemets hotline"
    },
    "workspace": {
      "activeTitle": "Aktiv (Klar for utrykning)",
      "activeDesc": "Du er tilgjengelig for nye oppdrag. Sett på pause når du tar en pause.",
      "pauseBtn": "Sett på pause",
      "pausedTitle": "Pauset (På pause)",
      "pausedDesc": "Oppdrag er midlertidig pauset. Aktiver igjen når du er klar.",
      "resumeBtn": "Gjenoppta aktiv",
      "hotlineTitle": "Utrykningshotlines",
      "hotlineDesc": "Kontakt oss umiddelbart ved manglende app-tilgang eller akutte endringer.",
      "team1": "Team 1 Hotline (Akutt)",
      "team2": "Team 2 Hotline (Standard)",
      "call": "Ring",
      "sms": "SMS",
      "servicesTitle": "Administrasjon av tjenestekategorier",
      "servicesDesc": "Klikk for å fjerne tjenester eller legge til nye kategorier i sanntid.",
      "categoriesActive": "Aktive kategorier",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Deaktivert",
      "regionsTitle": "Aktive oppdragsområder",
      "regionsDesc": "Klikk ✕ for å fjerne områder, eller legg til nye tilgjengelige områder.",
      "regionsCount": "Angitte regioner",
      "addRegionBtn": "Legg til region"
    }
  },
  "ar": {
    "tech": {
      "operatingRegions": "مناطق الخدمة",
      "instantDispatchConnected": "اتصال فوري بالعملاء",
      "registeredServices": "الخدمات المسجلة",
      "categoriesRegisteredCount": "فئات مسجلة",
      "editableInWorkspace": "قابلة للتعديل في مساحة العمل",
      "openWorkspaceBtn": "إدارة مساحة العمل الخاصة بي",
      "securitySessionNotice": "جلسة أمان لمدة 3 أشهر: مفتاح وصول عشوائي لمدة 90 يومًا عبر رقم الهاتف",
      "securitySessionExpiry": "انتهاء جلسة الأمان",
      "securitySessionExpired": "انتهت جلسة الأمان",
      "autoMaintainedDays": "أيام يتم الحفاظ عليها تلقائيًا",
      "statusActiveShort": "متاح للانطلاق",
      "statusPausedShort": "متوقف مؤقتًا",
      "clickToToggle": "انقر للتبديل",
      "hotlineNotice": "الخط الساخن للنظام الرئيسي"
    },
    "workspace": {
      "activeTitle": "نشط (متاح للانطلاق)",
      "activeDesc": "أنت متاح حاليًا لطلبات الخدمة الجديدة. يمكنك التبديل إلى الإيقاف المؤقت عند أخذ استراحة.",
      "pauseBtn": "إيقاف مؤقت",
      "pausedTitle": "متوقف مؤقتًا (في استراحة)",
      "pausedDesc": "تم إيقاف مكالمات الخدمة مؤقتًا. عد إلى الحالة النشطة عندما تكون جاهزًا.",
      "resumeBtn": "استئناف النشاط",
      "hotlineTitle": "الخطوط الساخنة لحالات الانطلاق",
      "hotlineDesc": "إذا تعذر الوصول إلى التطبيق أو حدثت تغييرات طارئة، يرجى الاتصال بنا على الفور.",
      "team1": "خط ساخن الفريق 1 (عاجل)",
      "team2": "خط ساخن الفريق 2 (عادي)",
      "call": "اتصال",
      "sms": "SMS",
      "servicesTitle": "إدارة فئات الخدمات",
      "servicesDesc": "انقر لإزالة الخدمات غير المتاحة أو إضافة فئات جديدة فورًا.",
      "categoriesActive": "فئات نشطة",
      "serviceActive": "نشط",
      "serviceDisabled": "معطل",
      "regionsTitle": "مناطق الخدمة التشغيلية",
      "regionsDesc": "انقر فوق ✕ لإزالة المناطق التي لا يمكنك زيارتها، أو أضف مناطق جديدة.",
      "regionsCount": "المناطق المحددة",
      "addRegionBtn": "إضافة منطقة"
    }
  },
  "arz": {
    "tech": {
      "headlineLead": "تواصل علطول مع الزباين القريبين منك",
      "operatingRegions": "مناطق الخدمة",
      "instantDispatchConnected": "اتصال فوري بالزباين",
      "registeredServices": "الخدمات المسجلة",
      "categoriesRegisteredCount": "فئات متسجلة",
      "editableInWorkspace": "تقدر تعدلها من صفحة الشغل",
      "openWorkspaceBtn": "إدارة صفحة الشغل بتاعتي",
      "securitySessionNotice": "جلسة أمان 3 شهور: كود عشوائي لمدة 90 يوم بيتبعت على الموبايل",
      "securitySessionExpiry": "ميعاد انتهاء جلسة الأمان",
      "securitySessionExpired": "جلسة الأمان انتهت",
      "autoMaintainedDays": "أيام متسجلة تلقائيًا",
      "statusActiveShort": "جاهز للشغل",
      "statusPausedShort": "واخد بريك مؤقت",
      "clickToToggle": "دوس علشان تبدل",
      "hotlineNotice": "الخط الساخن الرئيسي"
    },
    "workspace": {
      "activeTitle": "نشط (جاهز للانطلاق)",
      "activeDesc": "أنت متاح للطلبات الجديدة. تقدر توقف مؤقتًا لما تاخد بريك.",
      "pauseBtn": "إيقاف مؤقت",
      "pausedTitle": "متوقف مؤقتًا (بريك)",
      "pausedDesc": "المكالمات متوقفة مؤقتًا. ارجع للنشاط لما تكون جاهز للشغل.",
      "resumeBtn": "ارجع للشغل",
      "hotlineTitle": "الخطوط الساخنة للطوارئ",
      "hotlineDesc": "لو في مشكلة في التطبيق أو أي طوارئ كلمنا علطول.",
      "team1": "خط فريق 1 (طوارئ)",
      "team2": "خط فريق 2 (عادي)",
      "call": "اتصال",
      "sms": "SMS",
      "servicesTitle": "إدارة فئات الخدمات",
      "servicesDesc": "دوس علشان تشيل أو تزود خدمات في أي وقت.",
      "categoriesActive": "فئات شغالة",
      "serviceActive": "نشط",
      "serviceDisabled": "ملغي",
      "regionsTitle": "مناطق الخدمة بتاعتك",
      "regionsDesc": "دوس ✕ علشان تشيل منطقة أو زود مناطق جديدة.",
      "regionsCount": "المناطق المحددة",
      "addRegionBtn": "إضافة منطقة"
    }
  },
  "fa": {
    "tech": {
      "headlineLead": "ارتباط مستقیم با مشتریان در اطراف شما",
      "operatingRegions": "مناطق ارائه خدمات",
      "instantDispatchConnected": "اتصال فوری با مشتری",
      "registeredServices": "خدمات ثبت‌شده",
      "categoriesRegisteredCount": "دسته‌بندی ثبت‌شده",
      "editableInWorkspace": "قابل ویرایش در پنل متخصص",
      "openWorkspaceBtn": "مدیریت پنل کاری من",
      "securitySessionNotice": "نشست امنیتی ۳ ماهه: کلید دسترسی تصادفی ۹۰ روزه از طریق تلفن همراه",
      "securitySessionExpiry": "انقضای نشست امنیتی",
      "securitySessionExpired": "نشست امنیتی منقضی شد",
      "autoMaintainedDays": "روز حفظ خودکار",
      "statusActiveShort": "آماده اعزام",
      "statusPausedShort": "توقف موقت",
      "clickToToggle": "برای تغییر کلیک کنید",
      "hotlineNotice": "خط مستقیم اصلی سامانه"
    },
    "workspace": {
      "activeTitle": "فعال (آماده اعزام)",
      "activeDesc": "شما در حال حاضر آماده پذیرش سفارش‌های جدید هستید. در زمان استراحت متوقف کنید.",
      "pauseBtn": "توقف موقت فعالیت",
      "pausedTitle": "متوقف شده (در حال استراحت)",
      "pausedDesc": "دریافت تماس‌ها متوقف شده است. پس از آمادگی مجدداً فعال کنید.",
      "resumeBtn": "شروع مجدد فعالیت",
      "hotlineTitle": "خطوط ارتباطی فوری اعزام",
      "hotlineDesc": "در صورت عدم دسترسی به برنامه یا موارد اضطراری سریعاً با ما تماس بگیرید.",
      "team1": "خط تیم ۱ (فوری)",
      "team2": "خط تیم ۲ (عادی)",
      "call": "تماس",
      "sms": "پیامک",
      "servicesTitle": "مدیریت دسته‌بندی خدمات",
      "servicesDesc": "برای حذف خدمات یا افزودن خدمات جدید کلیک کنید.",
      "categoriesActive": "دسته‌های فعال",
      "serviceActive": "فعال",
      "serviceDisabled": "غیرفعال",
      "regionsTitle": "مناطق فعال کاری",
      "regionsDesc": "برای حذف مناطق روی ✕ کلیک کنید یا مناطق جدید اضافه کنید.",
      "regionsCount": "مناطق تعیین‌شده",
      "addRegionBtn": "افزودن منطقه"
    }
  },
  "he": {
    "tech": {
      "headlineLead": "התחבר ישירות ללקוחות באזור שלך",
      "operatingRegions": "אזורי שירות",
      "instantDispatchConnected": "חיבור מיידי ללקוחות",
      "registeredServices": "שירותים רשומים",
      "categoriesRegisteredCount": "קטגוריות רשומות",
      "editableInWorkspace": "ניתן לעריכה באזור האישי",
      "openWorkspaceBtn": "ניהול האזור האישי שלי",
      "securitySessionNotice": "סשן אבטחה ל-3 חודשים: מפתח גישה אקראי ל-90 יום נשלח לנייד",
      "securitySessionExpiry": "פקיעת סשן אבטחה",
      "securitySessionExpired": "סשן האבטחה פג תוקף",
      "autoMaintainedDays": "ימים נשמרים אוטומטית",
      "statusActiveShort": "זמין ליציאה",
      "statusPausedShort": "מושהה זמנית",
      "clickToToggle": "לחץ לשינוי",
      "hotlineNotice": "מוקד מערכת ראשי"
    },
    "workspace": {
      "activeTitle": "פעיל (זמין ליציאות)",
      "activeDesc": "אתה זמין כעת לקריאות חדשות. העבר להשהיה כשאתה יוצא להפסקה.",
      "pauseBtn": "השהה זמינות",
      "pausedTitle": "מושהה (בהפסקה)",
      "pausedDesc": "קריאות שירות מושהות כרגע. הפעל מחדש כשתהיה מוכן לעבודה.",
      "resumeBtn": "חזור לפעילות",
      "hotlineTitle": "מוקדי חירום ליציאות",
      "hotlineDesc": "אם הגישה לאפליקציה אינה זמינה או שחלים שינויים דחופים, צור קשר מיידית.",
      "team1": "מוקד צוות 1 (דחוף)",
      "team2": "מוקד צוות 2 (רגיל)",
      "call": "התקשר",
      "sms": "SMS",
      "servicesTitle": "ניהול קטגוריות שירות",
      "servicesDesc": "לחץ להסרת שירותים או להוספת קטגוריות חדשות בזמן אמת.",
      "categoriesActive": "קטגוריות פעילות",
      "serviceActive": "פעיל",
      "serviceDisabled": "מושבת",
      "regionsTitle": "אזורי פעילות",
      "regionsDesc": "לחץ על ✕ להסרת אזורים, או הוסף אזורים חדשים.",
      "regionsCount": "אזורים מוגדרים",
      "addRegionBtn": "הוסף אזור"
    }
  },
  "hi": {
    "tech": {
      "operatingRegions": "सेवा क्षेत्र",
      "instantDispatchConnected": "ग्राहकों से त्वरित संपर्क",
      "registeredServices": "पंजीकृत सेवाएँ",
      "categoriesRegisteredCount": "श्रेणियाँ पंजीकृत",
      "editableInWorkspace": "कार्यक्षेत्र में संपादन योग्य",
      "openWorkspaceBtn": "मेरा कार्यक्षेत्र प्रबंधित करें",
      "securitySessionNotice": "3-महीने का सुरक्षा सत्र: मोबाइल नंबर के माध्यम से 90-दिन की रैंडम एक्सेस कुंजी जारी",
      "securitySessionExpiry": "सुरक्षा सत्र समाप्ति",
      "securitySessionExpired": "सुरक्षा सत्र समाप्त हो गया",
      "autoMaintainedDays": "दिन स्वतः सुरक्षित",
      "statusActiveShort": "सेवा के लिए तैयार",
      "statusPausedShort": "अस्थायी रूप से रोका गया",
      "clickToToggle": "बदलने के लिए क्लिक करें",
      "hotlineNotice": "मुख्य प्रणाली हॉटलाइन"
    },
    "workspace": {
      "activeTitle": "सक्रिय (सेवा के लिए तैयार)",
      "activeDesc": "आप वर्तमान में नए सेवा अनुरोधों के लिए उपलब्ध हैं। ब्रेक के समय इसे रोकें।",
      "pauseBtn": "उपलब्धता रोकें",
      "pausedTitle": "रोका गया (विश्राम में)",
      "pausedDesc": "सेवा कॉल अभी रोके गए हैं। काम के लिए तैयार होने पर फिर से सक्रिय करें।",
      "resumeBtn": "पुनः सक्रिय करें",
      "hotlineTitle": "प्राथमिक सेवा हॉटलाइन",
      "hotlineDesc": "यदि ऐप तक पहुंच अनुपलब्ध है या तत्काल परिवर्तन होते हैं, तो तुरंत हमारी टीम से संपर्क करें।",
      "team1": "टीम 1 हॉटलाइन (आपातकालीन)",
      "team2": "टीम 2 हॉटलाइन (सामान्य)",
      "call": "कॉल करें",
      "sms": "SMS",
      "servicesTitle": "सेवा श्रेणी प्रबंधन",
      "servicesDesc": "अनुपलब्ध सेवाओं को हटाने या वास्तविक समय में नई श्रेणियां जोड़ने के लिए क्लिक करें।",
      "categoriesActive": "सक्रिय श्रेणियां",
      "serviceActive": "सक्रिय",
      "serviceDisabled": "निष्क्रिय",
      "regionsTitle": "परिचालन सेवा क्षेत्र",
      "regionsDesc": "उन क्षेत्रों को हटाने के लिए ✕ पर क्लिक करें जहां आप नहीं जा सकते, या नए क्षेत्र जोड़ें।",
      "regionsCount": "निर्धारित क्षेत्र",
      "addRegionBtn": "क्षेत्र जोड़ें"
    }
  },
  "bn": {
    "tech": {
      "headlineLead": "আপনার কাছের গ্রাহকদের সাথে সরাসরি যুক্ত হোন",
      "operatingRegions": "কাজের এলাকা",
      "instantDispatchConnected": "গ্রাহকদের সাথে তাৎক্ষণিক সংযোগ",
      "registeredServices": "নিবন্ধিত সেবাসমূহ",
      "categoriesRegisteredCount": "বিভাগ নিবন্ধিত",
      "editableInWorkspace": "ওয়ার্কস্পেসে পরিবর্তনযোগ্য",
      "openWorkspaceBtn": "আমার ওয়ার্কস্পেস পরিচালনা করুন",
      "securitySessionNotice": "৩ মাসের নিরাপত্তা সেশন: মোবাইল নম্বরে ৯০ দিনের র্যান্ডম অ্যাক্সেস কি প্রদান",
      "securitySessionExpiry": "নিরাপত্তা সেশনের মেয়াদ",
      "securitySessionExpired": "নিরাপত্তা সেশনের মেয়াদ শেষ",
      "autoMaintainedDays": "দিন স্বয়ংক্রিয়ভাবে রক্ষিত",
      "statusActiveShort": "কাজের জন্য প্রস্তুত",
      "statusPausedShort": "সাময়িক বিরতি",
      "clickToToggle": "টগল করতে ক্লিক করুন",
      "hotlineNotice": "প্রধান সিস্টেম হটলাইন"
    },
    "workspace": {
      "activeTitle": "সক্রিয় (কাজের জন্য প্রস্তুত)",
      "activeDesc": "আপনি বর্তমানে নতুন কাজের অনুরোধ গ্রহণের জন্য উন্মুক্ত রয়েছেন।",
      "pauseBtn": "উপলব্ধতা বিরতি দিন",
      "pausedTitle": "বিরতিতে (কাজে নেই)",
      "pausedDesc": "কাজের কল বর্তমানে স্থগিত রয়েছে। প্রস্তুত হলে আবার চালু করুন।",
      "resumeBtn": "পুনরায় সক্রিয় করুন",
      "hotlineTitle": "জরুরি হটলাইনসমূহ",
      "hotlineDesc": "অ্যাপে অ্যাক্সেস না থাকলে বা জরুরি পরিবর্তন হলে অবিলম্বে যোগাযোগ করুন।",
      "team1": "টিম ১ হটলাইন (জরুরি)",
      "team2": "টিম ২ হটলাইন (সাধারণ)",
      "call": "কল করুন",
      "sms": "SMS",
      "servicesTitle": "সেবা বিভাগ পরিচালনা",
      "servicesDesc": "সেবা অপসারণ করতে বা রিয়েল-টাইমে নতুন বিভাগ যোগ করতে ক্লিক করুন।",
      "categoriesActive": "সক্রিয় বিভাগসমূহ",
      "serviceActive": "সক্রিয়",
      "serviceDisabled": "নিষ্ক্রিয়",
      "regionsTitle": "কাজের আওতাভুক্ত এলাকা",
      "regionsDesc": "এলাকা বাদ দিতে ✕ ক্লিক করুন অথবা নতুন এলাকা যোগ করুন।",
      "regionsCount": "নির্ধারিত এলাকাসমূহ",
      "addRegionBtn": "এলাকা যোগ করুন"
    }
  },
  "ne": {
    "tech": {
      "headlineLead": "तपाईंको नजिकका ग्राहकहरूसँग सिधै जोडिनुहोस्",
      "operatingRegions": "सेवा क्षेत्रहरू",
      "instantDispatchConnected": "ग्राहकहरूसँग तत्काल सम्पर्क",
      "registeredServices": "दर्ता गरिएका सेवाहरू",
      "categoriesRegisteredCount": "श्रेणीहरू दर्ता",
      "editableInWorkspace": "कार्यक्षेत्रमा सम्पादन गर्न सकिने",
      "openWorkspaceBtn": "मेरो कार्यक्षेत्र व्यवस्थापन गर्नुहोस्",
      "securitySessionNotice": "३-महिने सुरक्षा सत्र: मोबाइल नम्बर मार्फत ९०-दिने पहुँच कुञ्जी जारी",
      "securitySessionExpiry": "सुरक्षा सत्र समाप्ति",
      "securitySessionExpired": "सुरक्षा सत्र समाप्त भयो",
      "autoMaintainedDays": "दिन स्वतः कायम",
      "statusActiveShort": "खटिन तयार",
      "statusPausedShort": "अस्थायी रूपमा रोकिएको",
      "clickToToggle": "परिवर्तन गर्न क्लिक गर्नुहोस्",
      "hotlineNotice": "मुख्य प्रणाली हटलाइन"
    },
    "workspace": {
      "activeTitle": "सक्रिय (खटिन तयार)",
      "activeDesc": "तपाईं हाल नयाँ सेवा कलहरूको लागि उपलब्ध हुनुहुन्छ।",
      "pauseBtn": "उपलब्धता रोक्नुहोस्",
      "pausedTitle": "रोकिएको (विश्राममा)",
      "pausedDesc": "सेवा कलहरू हाल रोकिएका छन्। तयार हुँदा पुनः सक्रिय गर्नुहोस्।",
      "resumeBtn": "पुनः सक्रिय गर्नुहोस्",
      "hotlineTitle": "प्राथमिक हटलाइनहरू",
      "hotlineDesc": "एप पहुँचमा समस्या भएमा वा आपतकालीन परिवर्तन भएमा तुरुन्त सम्पर्क गर्नुहोस्।",
      "team1": "टोली १ हटलाइन (आपतकालीन)",
      "team2": "टोली २ हटलाइन (मानक)",
      "call": "कल गर्नुहोस्",
      "sms": "SMS",
      "servicesTitle": "सेवा श्रेणी व्यवस्थापन",
      "servicesDesc": "अनुपलब्ध सेवा हटाउन वा नयाँ श्रेणी थप्न क्लिक गर्नुहोस्।",
      "categoriesActive": "सक्रिय श्रेणीहरू",
      "serviceActive": "सक्रिय",
      "serviceDisabled": "निष्क्रिय",
      "regionsTitle": "सञ्चालन सेवा क्षेत्रहरू",
      "regionsDesc": "क्षेत्र हटाउन ✕ मा क्लिक गर्नुहोस् वा नयाँ क्षेत्र थप्नुहोस्।",
      "regionsCount": "सेट गरिएका क्षेत्रहरू",
      "addRegionBtn": "क्षेत्र थप्नुहोस्"
    }
  },
  "km": {
    "tech": {
      "headlineLead": "ភ្ជាប់ទំនាក់ទំនងផ្ទាល់ជាមួយអតិថិជននៅជិតអ្នក",
      "operatingRegions": "តំបន់បម្រើសេវា",
      "instantDispatchConnected": "ការតភ្ជាប់ភ្លាមៗជាមួយអតិថិជន",
      "registeredServices": "សេវាកម្មដែលបានចុះឈ្មោះ",
      "categoriesRegisteredCount": "ប្រភេទសេវាកម្មបានចុះឈ្មោះ",
      "editableInWorkspace": "អាចកែសម្រួលបាននៅក្នុងកន្លែងធ្វើការ",
      "openWorkspaceBtn": "គ្រប់គ្រងកន្លែងធ្វើការរបស់ខ្ញុំ",
      "securitySessionNotice": "សម័យសុវត្ថិភាព 3 ខែ៖ លេខកូដចូលប្រើចៃដន្យ 90 ថ្ងៃត្រូវបានចេញតាមលេខទូរស័ព្ទ",
      "securitySessionExpiry": "កាលបរិច្ឆេទផុតកំណត់នៃសម័យសុវត្ថិភាព",
      "securitySessionExpired": "សម័យសុវត្ថិភាពបានផុតកំណត់",
      "autoMaintainedDays": "ថ្ងៃត្រូវបានរក្សាទុកដោយស្វ័យប្រវត្តិ",
      "statusActiveShort": "ត្រៀមខ្លួនចេញធ្វើការ",
      "statusPausedShort": "ផ្អាកបណ្តោះអាសន្ន",
      "clickToToggle": "ចុចដើម្បីប្តូរ",
      "hotlineNotice": "ខ្សែទូរស័ព្ទទាន់ហេតុការណ៍ចម្បង"
    },
    "workspace": {
      "activeTitle": "សកម្ម (ត្រៀមខ្លួនចេញធ្វើការ)",
      "activeDesc": "អ្នកកំពុងបើកទទួលការហៅសេវាកម្មថ្មីៗ។ សូមប្តូរទៅផ្អាកនៅពេលសម្រាក។",
      "pauseBtn": "ផ្អាកភាពទំនេរ",
      "pausedTitle": "បានផ្អាក (កំពុងសម្រាក)",
      "pausedDesc": "ការហៅសេវាកម្មត្រូវបានផ្អាកបណ្តោះអាសន្ន។ សូមបើកសកម្មឡើងវិញនៅពេលរួចរាល់។",
      "resumeBtn": "បន្តសកម្មភាពឡើងវិញ",
      "hotlineTitle": "ខ្សែទូរស័ព្ទទាន់ហេតុការណ៍ចម្បង",
      "hotlineDesc": "ប្រសិនបើមិនអាចចូលប្រើកម្មវិធីបាន ឬមានការផ្លាស់ប្តូរបន្ទាន់ សូមទាក់ទងមកយើងខ្ញុំភ្លាមៗ។",
      "team1": "ក្រុមទី 1 ទូរស័ព្ទទាន់ហេតុការណ៍ (បន្ទាន់)",
      "team2": "ក្រុមទី 2 ទូរស័ព្ទទាន់ហេតុការណ៍ (ធម្មតា)",
      "call": "ហៅទូរស័ព្ទ",
      "sms": "SMS",
      "servicesTitle": "ការគ្រប់គ្រងប្រភេទសេវាកម្ម",
      "servicesDesc": "ចុចដើម្បីលុបសេវាដែលមិនទំនេរ ឬបន្ថែមប្រភេទថ្មីបានភ្លាមៗ។",
      "categoriesActive": "ប្រភេទសេវាសកម្ម",
      "serviceActive": "សកម្ម",
      "serviceDisabled": "បិទ",
      "regionsTitle": "តំបន់បម្រើសេវាកម្ម",
      "regionsDesc": "ចុច ✕ ដើម្បីលុបតំបន់ ឬបន្ថែមតំបន់ដែលមានថ្មី។",
      "regionsCount": "តំបន់ដែលបានកំណត់",
      "addRegionBtn": "បន្ថែមតំបន់"
    }
  },
  "my": {
    "tech": {
      "headlineLead": "သင့်အနီးရှိ ဝယ်ယူသူများနှင့် တိုက်ရိုက်ချိတ်ဆက်ပါ",
      "operatingRegions": "ဝန်ဆောင်မှုပေးသော ဒေသများ",
      "instantDispatchConnected": "ဝယ်ယူသူများနှင့် တိုက်ရိုက်ချိတ်ဆက်မှု",
      "registeredServices": "မှတ်ပုံတင်ထားသော ဝန်ဆောင်မှုများ",
      "categoriesRegisteredCount": "အမျိုးအစား မှတ်ပုံတင်ထားသည်",
      "editableInWorkspace": "လုပ်ငန်းခွင်တွင် ပြင်ဆင်နိုင်သည်",
      "openWorkspaceBtn": "ကျွန်ုပ်၏ လုပ်ငန်းခွင် စီမံရန်",
      "securitySessionNotice": "၃ လ လုံခြုံရေးကာလ- ဖုန်းနံပါတ်ဖြင့် ထုတ်ပေးသော ၉၀ ရက် ဝင်ရောက်ခွင့်ကုဒ်",
      "securitySessionExpiry": "လုံခြုံရေးကာလ ကုန်ဆုံးရက်",
      "securitySessionExpired": "လုံခြုံရေးကာလ ကုန်ဆုံးသွားပါပြီ",
      "autoMaintainedDays": "ရက် အလိုအလျောက် ထိန်းသိမ်းထားသည်",
      "statusActiveShort": "အလုပ်ဆင်းရန် အဆင်သင့်",
      "statusPausedShort": "ခေတ္တရပ်နားထားသည်",
      "clickToToggle": "ပြောင်းလဲရန် နှိပ်ပါ",
      "hotlineNotice": "ပင်မ ဟော့လိုင်း"
    },
    "workspace": {
      "activeTitle": "အလုပ်လုပ်နေသည် (ထွက်ခွာရန် အဆင်သင့်)",
      "activeDesc": "လက်ရှိတွင် ဝန်ဆောင်မှုအသစ်များ လက်ခံရန် အဆင်သင့်ဖြစ်နေပါသည်။",
      "pauseBtn": "အလုပ် ခေတ္တရပ်နားရန်",
      "pausedTitle": "ရပ်နားထားသည် (နားနေချိန်)",
      "pausedDesc": "ခေါ်ဆိုမှုများကို ခေတ္တရပ်ထားသည်။ အဆင်သင့်ဖြစ်ပါက ပြန်ဖွင့်ပါ။",
      "resumeBtn": "ပြန်လည်စတင်ရန်",
      "hotlineTitle": "အရေးပေါ် ဟော့လိုင်းများ",
      "hotlineDesc": "အက်ပ်သုံးမရခြင်း သို့မဟုတ် အရေးပေါ်ကိစ္စများရှိပါက ချက်ချင်းဆက်သွယ်ပါ။",
      "team1": "အဖွဲ့ ၁ ဟော့လိုင်း (အရေးပေါ်)",
      "team2": "အဖွဲ့ ၂ ဟော့လိုင်း (ပုံမှန်)",
      "call": "ခေါ်ဆိုရန်",
      "sms": "SMS",
      "servicesTitle": "ဝန်ဆောင်မှု အမျိုးအစားများ စီမံခန့်ခွဲမှု",
      "servicesDesc": "ဝန်ဆောင်မှုများ ပိတ်ရန် သို့မဟုတ် အသစ်ထည့်ရန် နှိပ်ပါ။",
      "categoriesActive": "လက်ရှိ ဖွင့်ထားသော အမျိုးအစားများ",
      "serviceActive": "ဖွင့်ထားသည်",
      "serviceDisabled": "ပိတ်ထားသည်",
      "regionsTitle": "ဝန်ဆောင်မှုပေးသော နေရာများ",
      "regionsDesc": "နေရာပယ်ဖျက်ရန် ✕ နှိပ်ပါ သို့မဟုတ် နေရာသစ်ထည့်ပါ။",
      "regionsCount": "သတ်မှတ်ထားသော နေရာများ",
      "addRegionBtn": "နေရာ ထည့်ရန်"
    }
  },
  "mn": {
    "tech": {
      "headlineLead": "Ойр орчмын үйлчлүүлэгчидтэй шууд холбогдох",
      "operatingRegions": "Үйлчилгээний бүс",
      "instantDispatchConnected": "Үйлчлүүлэгчтэй шууд холбогдох",
      "registeredServices": "Бүртгэлтэй үйлчилгээ",
      "categoriesRegisteredCount": "төрөл бүртгэгдсэн",
      "editableInWorkspace": "Мастерын хэсэгт засах боломжтой",
      "openWorkspaceBtn": "Өөрийн ажлын хэсгийг удирдах",
      "securitySessionNotice": "3 сарын аюулгүй байдлын хугацаа: гар утсаар олгосон 90 хоногийн нэвтрэх түлхүүр",
      "securitySessionExpiry": "Аюулгүй байдлын хугацаа дуусах",
      "securitySessionExpired": "Аюулгүй байдлын хугацаа дууссан",
      "autoMaintainedDays": "хоног автоматаар хадгалагдана",
      "statusActiveShort": "Дуудлагад бэлэн",
      "statusPausedShort": "Түр завсарласан",
      "clickToToggle": "Сэлгэхийн тулд дарна уу",
      "hotlineNotice": "Үндсэн системийн лавлах утас"
    },
    "workspace": {
      "activeTitle": "Идэвхтэй (Дуудлагад бэлэн)",
      "activeDesc": "Шинэ захиалга авахад бэлэн байна. Завсарлага авахдаа түр зогсооно уу.",
      "pauseBtn": "Түр зогсоох",
      "pausedTitle": "Түр зогссон (Амарч байгаа)",
      "pausedDesc": "Дуудлага хүлээн авахыг түр зогсоосон. Бэлэн болмогц идэвхжүүлнэ үү.",
      "resumeBtn": "Үйл ажиллагааг сэргээх",
      "hotlineTitle": "Шуурхай холбоо барих утас",
      "hotlineDesc": "Аппликейшнд нэвтрэх боломжгүй эсвэл яаралтай асуудал гарвал бидэнтэй шууд холбогдоно уу.",
      "team1": "Баг 1 лавлах утас (Яаралтай)",
      "team2": "Баг 2 лавлах утас (Энгийн)",
      "call": "Залгах",
      "sms": "SMS",
      "servicesTitle": "Үйлчилгээний төрлийн удирдлага",
      "servicesDesc": "Үйлчилгээ хасах эсвэл шинэ төрөл нэмэхийн тулд дарна уу.",
      "categoriesActive": "Идэвхтэй төрлүүд",
      "serviceActive": "Идэвхтэй",
      "serviceDisabled": "Идэвхгүй",
      "regionsTitle": "Үйлчилгээ үзүүлэх бүсүүд",
      "regionsDesc": "Бүс хасахын тулд ✕ дээр дарна уу эсвэл шинэ бүс нэмнэ үү.",
      "regionsCount": "Тохируулсан бүсүүд",
      "addRegionBtn": "Бүс нэмэх"
    }
  },
  "uz": {
    "tech": {
      "headlineLead": "Yaqin atrofdagi mijozlar bilan to'g'ridan-to'g'ri bog'laning",
      "operatingRegions": "Xizmat ko'rsatish hududlari",
      "instantDispatchConnected": "Mijoz bilan tezkor aloqa",
      "registeredServices": "Ro'yxatdan o'tgan xizmatlar",
      "categoriesRegisteredCount": "toifa ro'yxatdan o'tgan",
      "editableInWorkspace": "Usta panelida tahrirlash mumkin",
      "openWorkspaceBtn": "Ish panelimni boshqarish",
      "securitySessionNotice": "3 oylik xavfsizlik sessiyasi: mobil raqam orqali berilgan 90 kunlik tasodifiy kirish kaliti",
      "securitySessionExpiry": "Xavfsizlik sessiyasining tugash muddati",
      "securitySessionExpired": "Xavfsizlik sessiyasi muddati tugagan",
      "autoMaintainedDays": "kun avtomatik saqlanadi",
      "statusActiveShort": "Chaqiruvga tayyor",
      "statusPausedShort": "Vaqtincha tanaffusda",
      "clickToToggle": "O'zgartirish uchun bosing",
      "hotlineNotice": "Asosiy tizim ishonch telefoni"
    },
    "workspace": {
      "activeTitle": "Faol (Chaqiruvga tayyor)",
      "activeDesc": "Yangi xizmat chaqiruvlari uchun ochiqsiz. Dam olayotganda tanaffusga o'ting.",
      "pauseBtn": "Mavjudlikni to'xtatib turish",
      "pausedTitle": "To'xtatilgan (Tanaffusda)",
      "pausedDesc": "Chaqiruvlar vaqtincha to'xtatildi. Ishga tayyor bo'lgach yana yoqing.",
      "resumeBtn": "Faollikni tiklash",
      "hotlineTitle": "Tezkor aloqa ishonch telefonlari",
      "hotlineDesc": "Ilovaga kirish imkoni bo'lmasa yoki favqulodda holatlarda darhol biz bilan bog'laning.",
      "team1": "1-guruh liniyasi (Shoshilinch)",
      "team2": "2-guruh liniyasi (Standart)",
      "call": "Qo'ng'iroq",
      "sms": "SMS",
      "servicesTitle": "Xizmat toifalarini boshqarish",
      "servicesDesc": "Xizmatlarni o'chirish yoki yangi toifalarni qo'shish uchun bosing.",
      "categoriesActive": "Faol toifalar",
      "serviceActive": "Faol",
      "serviceDisabled": "O'chirilgan",
      "regionsTitle": "Xizmat ko'rsatish hududlari",
      "regionsDesc": "Hududni o'chirish uchun ✕ belgisini bosing yoki yangi hudud qo'shing.",
      "regionsCount": "Belgilangan hududlar",
      "addRegionBtn": "Hudud qo'shish"
    }
  },
  "kk": {
    "tech": {
      "headlineLead": "Жақын маңдағы клиенттермен тікелей байланысыңыз",
      "operatingRegions": "Қызмет көрсету аймақтары",
      "instantDispatchConnected": "Клиентпен лезде байланыс",
      "registeredServices": "Тіркелген қызметтер",
      "categoriesRegisteredCount": "санат тіркелген",
      "editableInWorkspace": "Шебер кабинетінде өзгертуге болады",
      "openWorkspaceBtn": "Шебер кабинетімді басқару",
      "securitySessionNotice": "3 айлық қауіпсіздік сессиясы: ұялы телефон арқылы берілген 90 күндік кездейсоқ кіру кілті",
      "securitySessionExpiry": "Қауіпсіздік сессиясының аяқталуы",
      "securitySessionExpired": "Қауіпсіздік сессиясы аяқталды",
      "autoMaintainedDays": "күн автоматты түрде сақталады",
      "statusActiveShort": "Шақыруға дайын",
      "statusPausedShort": "Уақытша үзілісте",
      "clickToToggle": "Ауыстыру үшін басыңыз",
      "hotlineNotice": "Негізгі жүйе желісі"
    },
    "workspace": {
      "activeTitle": "Белсенді (Шақыруға дайын)",
      "activeDesc": "Жаңа қызмет шақыруларына ашықсыз. Демалған кезде үзіліске ауысыңыз.",
      "pauseBtn": "Қолжетімділікті кідірту",
      "pausedTitle": "Кідіртілген (Үзілісте)",
      "pausedDesc": "Шақырулар уақытша тоқтатылды. Жұмысқа дайын болғанда қайта қосыңыз.",
      "resumeBtn": "Белсенділікті жалғастыру",
      "hotlineTitle": "Шұғыл байланыс желілері",
      "hotlineDesc": "Қолданбаға кіре алмасаңыз немесе шұғыл өзгерістер болса, дереу хабарласыңыз.",
      "team1": "1-топ байланыс желісі (Шұғыл)",
      "team2": "2-топ байланыс желісі (Қалыпты)",
      "call": "Қоңырау шалу",
      "sms": "SMS",
      "servicesTitle": "Қызмет санаттарын басқару",
      "servicesDesc": "Қызметтерді жою немесе нақты уақытта жаңа санаттар қосу үшін басыңыз.",
      "categoriesActive": "Белсенді санаттар",
      "serviceActive": "Белсенді",
      "serviceDisabled": "Өшірілген",
      "regionsTitle": "Қызмет көрсету аймақтары",
      "regionsDesc": "Аймақты жою үшін ✕ басыңыз немесе жаңа қолжетімді аймақ қосыңыз.",
      "regionsCount": "Орнатылған аймақтар",
      "addRegionBtn": "Аймақ қосу"
    }
  },
  "ta": {
    "tech": {
      "headlineLead": "உங்கள் அருகில் உள்ள வாடிக்கையாளர்களுடன் நேரடியாக இணையுங்கள்",
      "operatingRegions": "சேவை பகுதிகள்",
      "instantDispatchConnected": "வாடிக்கையாளருடன் உடனடி இணைப்பு",
      "registeredServices": "பதிவு செய்யப்பட்ட சேவைகள்",
      "categoriesRegisteredCount": "பிரிவுகள் பதிவு செய்யப்பட்டுள்ளன",
      "editableInWorkspace": "பணியிடத்தில் மாற்றியமைக்கலாம்",
      "openWorkspaceBtn": "எனது பணியிடத்தை நிர்வகி",
      "securitySessionNotice": "3 மாத பாதுகாப்பு அமர்வு: மொபைல் மூலம் 90 நாட்கள் அணுகல் சாவி வழங்கப்படுகிறது",
      "securitySessionExpiry": "பாதுகாப்பு அமர்வு காலாவதி",
      "securitySessionExpired": "பாதுகாப்பு அமர்வு காலாவதியானது",
      "autoMaintainedDays": "நாட்கள் தானாகவே பராமரிக்கப்படும்",
      "statusActiveShort": "சேவைக்கு தயார்",
      "statusPausedShort": "தற்காலிக இடைநிறுத்தம்",
      "clickToToggle": "மாற்ற கிளிக் செய்யவும்",
      "hotlineNotice": "முதன்மை கணினி உதவி எண்"
    },
    "workspace": {
      "activeTitle": "செயலில் (சேவைக்கு தயார்)",
      "activeDesc": "புதிய சேவை அழைப்புகளைப் பெற நீங்கள் தயார் நிலையில் உள்ளீர்கள்.",
      "pauseBtn": "கிடைக்கும் நிலையை இடைநிறுத்து",
      "pausedTitle": "இடைநிறுத்தப்பட்டது (இடைவேளையில்)",
      "pausedDesc": "சேவை அழைப்புகள் தற்காலிகமாக நிறுத்தப்பட்டுள்ளன. தயார் ஆனதும் இயக்கவும்.",
      "resumeBtn": "மீண்டும் தொடங்கு",
      "hotlineTitle": "முதன்மை அவசர உதவி எண்கள்",
      "hotlineDesc": "பயன்பாட்டை அணுக முடியாவிட்டால் உடனடியாக எங்களைத் தொடர்பு கொள்ளவும்.",
      "team1": "குழு 1 உதவி எண் (அவசரம்)",
      "team2": "குழு 2 உதவி எண் (வழக்கமான)",
      "call": "அழைக்கவும்",
      "sms": "SMS",
      "servicesTitle": "சேவை பிரிவுகள் மேலாண்மை",
      "servicesDesc": "சேவைகளை நீக்க அல்லது புதிய பிரிவுகளை சேர்க்க கிளிக் செய்யவும்.",
      "categoriesActive": "செயலில் உள்ள பிரிவுகள்",
      "serviceActive": "செயலில்",
      "serviceDisabled": "முடக்கப்பட்டது",
      "regionsTitle": "சேவை பகுதிகள்",
      "regionsDesc": "பகுதிகளை நீக்க ✕ கிளிக் செய்யவும் அல்லது புதிய பகுதிகளை சேர்க்கவும்.",
      "regionsCount": "அமைக்கப்பட்ட பகுதிகள்",
      "addRegionBtn": "பகுதியைச் சேர்"
    }
  },
  "si": {
    "tech": {
      "headlineLead": "ඔබ අසල සිටින පාරිභෝගිකයන් සමඟ සෘජුවම සම්බන්ධ වන්න",
      "operatingRegions": "සේවා කලාප",
      "instantDispatchConnected": "පාරිභෝගිකයා සමඟ ක්ෂණික සම්බන්ධතාවය",
      "registeredServices": "ලියාපදිංචි සේවාවන්",
      "categoriesRegisteredCount": "කාණ්ඩ ලියාපදිංචි කර ඇත",
      "editableInWorkspace": "කාර්ය අවකාශය තුළ සංස්කරණය කළ හැක",
      "openWorkspaceBtn": "මගේ කාර්ය අවකාශය කළමනාකරණය කරන්න",
      "securitySessionNotice": "මාස 3 ක ආරක්ෂක සැසිය: ජංගම දුරකථනය හරහා දින 90 ක ප්‍රවේශ යතුරක් නිකුත් කෙරේ",
      "securitySessionExpiry": "ආරක්ෂක සැසිය කල් ඉකුත්වීම",
      "securitySessionExpired": "ආරක්ෂක සැසිය කල් ඉකුත් විය",
      "autoMaintainedDays": "දින ස්වයංක්‍රීයව පවත්වාගෙන යනු ලැබේ",
      "statusActiveShort": "සේවාවට සූදානම්",
      "statusPausedShort": "තාවකාලිකව විරාම කර ඇත",
      "clickToToggle": "මාරු කිරීමට ක්ලික් කරන්න",
      "hotlineNotice": "ප්‍රධාන පද්ධති ක්ෂණික ඇමතුම් අංකය"
    },
    "workspace": {
      "activeTitle": "ක්‍රියාකාරී (සේවාවට සූදානම්)",
      "activeDesc": "ඔබ නව සේවා ඇමතුම් ලබා ගැනීමට සූදානම්ව සිටී.",
      "pauseBtn": "ලබා ගත හැකි බව විරාම කරන්න",
      "pausedTitle": "විරාම කර ඇත (විවේකයේ)",
      "pausedDesc": "සේවා ඇමතුම් තාවකාලිකව විරාම කර ඇත. සූදානම් වූ විට නැවත ක්‍රියාත්මක කරන්න.",
      "resumeBtn": "නැවත ක්‍රියාත්මක කරන්න",
      "hotlineTitle": "ප්‍රධාන ක්ෂණික ඇමතුම්",
      "hotlineDesc": "යෙදුමට ප්‍රවේශ විය නොහැකි නම් වහාම අප අමතන්න.",
      "team1": "කණ්ඩායම 1 ක්ෂණික ඇමතුම (හදිසි)",
      "team2": "කණ්ඩායම 2 ක්ෂණික ඇමතුම (සාමාන්‍ය)",
      "call": "අමතන්න",
      "sms": "SMS",
      "servicesTitle": "සේවා කාණ්ඩ කළමනාකරණය",
      "servicesDesc": "සේවා ඉවත් කිරීමට හෝ නව කාණ්ඩ එක් කිරීමට ක්ලික් කරන්න.",
      "categoriesActive": "ක්‍රියාකාරී කාණ්ඩ",
      "serviceActive": "ක්‍රියාකාරී",
      "serviceDisabled": "අක්‍රියයි",
      "regionsTitle": "සේවා සපයන ප්‍රදේශ",
      "regionsDesc": "ප්‍රදේශ ඉවත් කිරීමට ✕ ක්ලික් කරන්න හෝ නව ප්‍රදේශ එක් කරන්න.",
      "regionsCount": "සැකසූ ප්‍රදේශ",
      "addRegionBtn": "ප්‍රදේශය එක් කරන්න"
    }
  },
  "am": {
    "tech": {
      "headlineLead": "በአቅራቢያዎ ካሉ ደንበኞች ጋር በቀጥታ ይገናኙ",
      "operatingRegions": "የአገልግሎት ክልሎች",
      "instantDispatchConnected": "ፈጣን የደንበኛ ግንኙነት",
      "registeredServices": "የተመዘገቡ አገልግሎቶች",
      "categoriesRegisteredCount": "ምድቦች ተመዝግበዋል",
      "editableInWorkspace": "በስራ ቦታው ላይ ሊስተካከል የሚችል",
      "openWorkspaceBtn": "የስራ ቦታዬን አስተዳድር",
      "securitySessionNotice": "የ 3 ወራት የደህንነት ክፍለ ጊዜ፡ በሞባይል ስልክ የተሰጠ የ 90 ቀናት መዳረሻ ቁልፍ",
      "securitySessionExpiry": "የደህንነት ክፍለ ጊዜ ማብቂያ",
      "securitySessionExpired": "የደህንነት ክፍለ ጊዜ አልቋል",
      "autoMaintainedDays": "ቀናት በራስ-ሰር ይጠበቃሉ",
      "statusActiveShort": "ለአገልግሎት ዝግጁ",
      "statusPausedShort": "ለጊዜው ቆሟል",
      "clickToToggle": "ለመቀየር ይጫኑ",
      "hotlineNotice": "ዋና የስርዓት ስልክ መስመር"
    },
    "workspace": {
      "activeTitle": "ንቁ (ለስራ ዝግጁ)",
      "activeDesc": "አዲስ የጥሪ ጥያቄዎችን ለመቀበል ዝግጁ ነዎት። በእረፍት ጊዜ ለአፍታ ያቁሙ።",
      "pauseBtn": "ዝግጁነትን ለአፍታ አቁም",
      "pausedTitle": "ቆሟል (በእረፍት ላይ)",
      "pausedDesc": "ጥሪዎች ለጊዜው ቆመዋል። ዝግጁ ሲሆኑ እንደገና ያግብሩ።",
      "resumeBtn": "ስራ ጀምር",
      "hotlineTitle": "ዋና የአደጋ ጊዜ ስልክ መስመሮች",
      "hotlineDesc": "መተግበሪያውን መጠቀም ካልቻሉ ወይም አስቸኳይ ለውጦች ካሉ ወዲያውኑ ይደውሉልን።",
      "team1": "ቡድን 1 የስልክ መስመር (አስቸኳይ)",
      "team2": "ቡድን 2 የስልክ መስመር (መደበኛ)",
      "call": "ደውል",
      "sms": "SMS",
      "servicesTitle": "የአገልግሎት ምድቦች አስተዳደር",
      "servicesDesc": "አገልግሎቶችን ለማስወገድ ወይም አዳዲስ ምድቦችን ለመጨመር ይጫኑ።",
      "categoriesActive": "ንቁ ምድቦች",
      "serviceActive": "ንቁ",
      "serviceDisabled": "የቦዘነ",
      "regionsTitle": "የአገልግሎት ሽፋን ክልሎች",
      "regionsDesc": "ክልሎችን ለማስወገድ ✕ ይጫኑ ወይም አዲስ ክልሎችን ያክሉ።",
      "regionsCount": "የተመረጡ ክልሎች",
      "addRegionBtn": "ክልል አክል"
    }
  },
  "tet": {
    "tech": {
      "headlineLead": "Liga diretamente ho kliente sira besik ita-boot",
      "operatingRegions": "Área Atendimentu",
      "instantDispatchConnected": "Ligasaun direta ho kliente",
      "registeredServices": "Servisu Rejistadu",
      "categoriesRegisteredCount": "kategoria rejistadu",
      "editableInWorkspace": "Belle hadi'a iha espasu serbisu",
      "openWorkspaceBtn": "Maneja Ha'u-nia Espasu Serbisu",
      "securitySessionNotice": "Sesaun Seguransa Fulan 3: xave asesu loron 90 emiti liuhosi númeru telemóvel",
      "securitySessionExpiry": "Sesaun Seguransa Remata",
      "securitySessionExpired": "Sesaun Seguransa Remata Ona",
      "autoMaintainedDays": "loron mantein automatikamente",
      "statusActiveShort": "Prontu atu Atende",
      "statusPausedShort": "Pausa Temporáriu",
      "clickToToggle": "Klike atu muda",
      "hotlineNotice": "Linha Apoiu Prinsipál"
    },
    "workspace": {
      "activeTitle": "Ativu (Prontu atu Atende)",
      "activeDesc": "Ita-boot prontu atu simu pedidu servisu foun. Muda ba pausa bainhira deskansa.",
      "pauseBtn": "Pausa Disponibilidade",
      "pausedTitle": "Pausadu (Deskansa)",
      "pausedDesc": "Xamada servisu nian temporariamente para. Ativa fali bainhira prontu atu serbisu.",
      "resumeBtn": "Kontinua Ativu",
      "hotlineTitle": "Linha Direta Prinsipál ba Emerjénsia",
      "hotlineDesc": "Se la konsege asesu ba aplikasaun ka iha mudansa urjente, kontaktu kedas ami.",
      "team1": "Hotline Ekipa 1 (Urjente)",
      "team2": "Hotline Ekipa 2 (Padrão)",
      "call": "Liafuan / Xamada",
      "sms": "SMS",
      "servicesTitle": "Maneja Kategoria Servisu",
      "servicesDesc": "Klike atu hasai servisu ka aumenta kategoria foun iha tempu reál.",
      "categoriesActive": "Kategoria Ativu",
      "serviceActive": "Ativu",
      "serviceDisabled": "Dezativadu",
      "regionsTitle": "Área Operasionál ba Atendimentu",
      "regionsDesc": "Klike ✕ atu hasai área, ka aumenta área foun ne'ebé disponivel.",
      "regionsCount": "Área Konfiguradu",
      "addRegionBtn": "Aumenta Área"
    }
  }
}

