# scripts/dict_weekdays.py

WEEKDAYS_ALL = {
  "ko": {"dayMon": "월", "dayTue": "화", "dayWed": "수", "dayThu": "목", "dayFri": "금", "daySat": "토", "daySun": "일"},
  "en": {"dayMon": "Mon", "dayTue": "Tue", "dayWed": "Wed", "dayThu": "Thu", "dayFri": "Fri", "daySat": "Sat", "daySun": "Sun"},
  "vi": {"dayMon": "T2", "dayTue": "T3", "dayWed": "T4", "dayThu": "T5", "dayFri": "T6", "daySat": "T7", "daySun": "CN"},
  "zh-Hans": {"dayMon": "周一", "dayTue": "周二", "dayWed": "周三", "dayThu": "周四", "dayFri": "周五", "daySat": "周六", "daySun": "周日"},
  "zh-Hant": {"dayMon": "週一", "dayTue": "週二", "dayWed": "週三", "dayThu": "週四", "dayFri": "週五", "daySat": "週六", "daySun": "週日"},
  "ja": {"dayMon": "月", "dayTue": "火", "dayWed": "水", "dayThu": "木", "dayFri": "金", "daySat": "土", "daySun": "日"},
  "pl": {"dayMon": "Pon", "dayTue": "Wt", "dayWed": "Śr", "dayThu": "Czw", "dayFri": "Pt", "daySat": "Sob", "daySun": "Niedz"},
  "de": {"dayMon": "Mo", "dayTue": "Di", "dayWed": "Mi", "dayThu": "Do", "dayFri": "Fr", "daySat": "Sa", "daySun": "So"},
  "fr": {"dayMon": "Lun", "dayTue": "Mar", "dayWed": "Mer", "dayThu": "Jeu", "dayFri": "Ven", "daySat": "Sam", "daySun": "Dim"},
  "es": {"dayMon": "Lun", "dayTue": "Mar", "dayWed": "Mié", "dayThu": "Jue", "dayFri": "Vie", "daySat": "Sáb", "daySun": "Dom"},
  "it": {"dayMon": "Lun", "dayTue": "Mar", "dayWed": "Mer", "dayThu": "Gio", "dayFri": "Ven", "daySat": "Sab", "daySun": "Dom"},
  "pt": {"dayMon": "Seg", "dayTue": "Ter", "dayWed": "Qua", "dayThu": "Qui", "dayFri": "Sex", "daySat": "Sáb", "daySun": "Dom"},
  "el": {"dayMon": "Δευ", "dayTue": "Τρί", "dayWed": "Τετ", "dayThu": "Πέμ", "dayFri": "Παρ", "daySat": "Σάβ", "daySun": "Κυρ"},
  "ru": {"dayMon": "Пн", "dayTue": "Вт", "dayWed": "Ср", "dayThu": "Чт", "dayFri": "Пт", "daySat": "Сб", "daySun": "Вс"},
  "uk": {"dayMon": "Пн", "dayTue": "Вт", "dayWed": "Ср", "dayThu": "Чт", "dayFri": "Пт", "daySat": "Сб", "daySun": "Нд"},
  "kk": {"dayMon": "Дс", "dayTue": "Сс", "dayWed": "Ср", "dayThu": "Бс", "dayFri": "Жм", "daySat": "Сб", "daySun": "Жс"},
  "uz": {"dayMon": "Dush", "dayTue": "Sesh", "dayWed": "Chor", "dayThu": "Pay", "dayFri": "Juma", "daySat": "Shan", "daySun": "Yak"},
  "mn": {"dayMon": "Дав", "dayTue": "Мяг", "dayWed": "Лха", "dayThu": "Пүр", "dayFri": "Баа", "daySat": "Бям", "daySun": "Ням"},
  "id": {"dayMon": "Sen", "dayTue": "Sel", "dayWed": "Rab", "dayThu": "Kam", "dayFri": "Jum", "daySat": "Sab", "daySun": "Min"},
  "th": {"dayMon": "จันทร์", "dayTue": "อังคาร", "dayWed": "พุธ", "dayThu": "พฤหัส", "dayFri": "ศุกร์", "daySat": "เสาร์", "daySun": "อาทิตย์"},
  "my": {"dayMon": "တနင်္လာ", "dayTue": "အင်္ဂါ", "dayWed": "ဗုဒ္ဓဟူး", "dayThu": "ကြာသပတေး", "dayFri": "သောကြာ", "daySat": "စနေ", "daySun": "တနင်္ဂနွေ"},
  "km": {"dayMon": "ចន្ទ", "dayTue": "អង្គារ", "dayWed": "ពុធ", "dayThu": "ព្រហ", "dayFri": "សុក្រ", "daySat": "សៅរ៍", "daySun": "អាទិត្យ"},
  "hi": {"dayMon": "सोम", "dayTue": "मंगल", "dayWed": "बुध", "dayThu": "गुरु", "dayFri": "शुक्र", "daySat": "शनि", "daySun": "रवि"},
  "ne": {"dayMon": "सोम", "dayTue": "मङ्गल", "dayWed": "बुध", "dayThu": "बिही", "dayFri": "शुक्र", "daySat": "शनि", "daySun": "आइत"},
  "bn": {"dayMon": "সোম", "dayTue": "মঙ্গল", "dayWed": "বুধ", "dayThu": "বৃহস্পতি", "dayFri": "শুক্র", "daySat": "শনি", "daySun": "রবি"},
  "ta": {"dayMon": "திங்", "dayTue": "செவ்", "dayWed": "புதன்", "dayThu": "வியா", "dayFri": "வெள்", "daySat": "சனி", "daySun": "ஞாயிறு"},
  "si": {"dayMon": "සඳුදා", "dayTue": "අඟහ", "dayWed": "බදාදා", "dayThu": "බ්‍රහස්", "dayFri": "සිකු", "daySat": "සෙන", "daySun": "ඉරිදා"},
  "ar": {"dayMon": "الإثنين", "dayTue": "الثلاثاء", "dayWed": "الأربعاء", "dayThu": "الخميس", "dayFri": "الجمعة", "daySat": "السبت", "daySun": "الأحد"},
  "arz": {"dayMon": "الإثنين", "dayTue": "الثلاثاء", "dayWed": "الأربعاء", "dayThu": "الخميس", "dayFri": "الجمعة", "daySat": "السبت", "daySun": "الأحد"},
  "fa": {"dayMon": "دوشنبه", "dayTue": "سه‌شنبه", "dayWed": "چهارشنبه", "dayThu": "پنج‌شنبه", "dayFri": "جمعه", "daySat": "شنبه", "daySun": "یکشنبه"},
  "he": {"dayMon": "שני", "dayTue": "שלישי", "dayWed": "רביעי", "dayThu": "חמישי", "dayFri": "שישי", "daySat": "שבת", "daySun": "ראשון"},
  "tr": {"dayMon": "Pzt", "dayTue": "Sal", "dayWed": "Çar", "dayThu": "Per", "dayFri": "Cum", "daySat": "Cmt", "daySun": "Paz"},
  "nl": {"dayMon": "Ma", "dayTue": "Di", "dayWed": "Wo", "dayThu": "Do", "dayFri": "Vr", "daySat": "Za", "daySun": "Zo"},
  "sv": {"dayMon": "Mån", "dayTue": "Tis", "dayWed": "Ons", "dayThu": "Tor", "dayFri": "Fre", "daySat": "Lör", "daySun": "Sön"},
  "da": {"dayMon": "Man", "dayTue": "Tir", "dayWed": "Ons", "dayThu": "Tor", "dayFri": "Fre", "daySat": "Lør", "daySun": "Søn"},
  "no": {"dayMon": "Man", "dayTue": "Tir", "dayWed": "Ons", "dayThu": "Tor", "dayFri": "Fre", "daySat": "Lør", "daySun": "Søn"},
  "am": {"dayMon": "ሰኞ", "dayTue": "ማክሰኞ", "dayWed": "ረቡዕ", "dayThu": "ሐሙስ", "dayFri": "አርብ", "daySat": "ቅዳሜ", "daySun": "እሑድ"},
  "tet": {"dayMon": "Seg", "dayTue": "Ters", "dayWed": "Kuart", "dayThu": "Kinta", "dayFri": "Sesta", "daySat": "Sábadu", "daySun": "Dom"}
}

