# scripts/dict_tech_workspace.py
# Tech and Workspace key updates for all languages

TECH_WS_UPDATES = {
  "pl": {
    "tech": {
      "headlineLead": "Bezpośrednio łącz się z klientami w Twojej okolicy",
      "actAsHelper": "profesjonalny fachowiec",
      "securitySessionNotice": "3-miesięczna sesja bezpieczeństwa: 90-dniowy losowy klucz dostępu wydawany na numer telefonu",
      "securitySessionExpiry": "Wygasanie sesji bezpieczeństwa",
      "securitySessionExpired": "Sesja bezpieczeństwa wygasła",
      "autoMaintainedDays": "dni automatycznego utrzymania",
      "operatingRegions": "Obszar działalności",
      "instantDispatchConnected": "Natychmiastowe połączenie z klientem",
      "registeredServices": "Zarejestrowane usługi",
      "categoriesRegisteredCount": "kategorie zarejestrowane",
      "editableInWorkspace": "Możliwość edycji w strefie fachowca",
      "openWorkspaceBtn": "Zarządzaj moją strefą fachowca",
      "statusActiveShort": "Dostępny do wyjazdów",
      "statusPausedShort": "Tymczasowo wstrzymany",
      "clickToToggle": "Kliknij, aby przełączyć",
      "hotlineNotice": "Główna linia wsparcia systemu",
      "helperPortal": "Portal Fachowca",
      "registerTab": "Rejestracja nowego fachowca",
      "loginTab": "Logowanie zarejestrowanego fachowca",
      "newHelperRegTitle": "Rejestracja nowego fachowca (3-miesięczny bezpieczny dostęp)",
      "existingHelperLoginTitle": "Logowanie zarejestrowanego fachowca",
      "newHelperRegDesc": "Bez konieczności podawania numeru PESEL. Pracuj swobodnie przez 3 miesiące tylko z numerem telefonu.",
      "existingHelperLoginDesc": "Wprowadź swój 3-miesięczny dedykowany klucz dostępu, aby wejść do strefy fachowca.",
      "accessKeyLabel": "3-miesięczny dedykowany klucz dostępu",
      "loginWithAccessKey": "Zaloguj się kluczem bezpieczeństwa (ważny 90 dni)",
      "loginKeyNotice": "Wprowadź 3-miesięczny klucz dostępu otrzymany przez SMS, aby natychmiast przejść do strefy fachowca.",
      "lostCodeBtn": "Zgubiłeś kod dostępu?",
      "reissueCodeTitle": "Ponowne wydanie klucza przez telefon",
      "getAccessKeyBtn": "Uzyskaj 3-miesięczny klucz bezpieczeństwa",
      "registerAndStart": "Zarejestruj się i rozpocznij usługę",
      "selectServices": "Wybierz kategorie usług",
      "selectServicesDesc": "Wybierz wszystkie kategorie, które możesz obsługiwać (możesz to zmienić w każdej chwili).",
      "selectedCount": " wybrano",
      "helperNameLabel": "Imię lub pseudonim fachowca",
      "agreeTerms": "Zapoznałem się z regulaminem i zasadami bezpieczeństwa LIFE.HELP i deklaruję rzetelną obsługę.",
      "keySentNotice": "Klucz dostępu wysłano pomyślnie",
      "issuedAccessKey": "Wydany 3-miesięczny klucz dostępu",
      "copy": "Kopiuj",
      "copied": "Skopiowano!",
      "backToTechHome": "Powrót do strony fachowca",
      "verifying": "Weryfikacja...",
      "changePhoneBtn": "Zmień",
      "enterAccessKeyError": "Wprowadź 3-miesięczny klucz bezpieczeństwa.",
      "enterNameError": "Wprowadź swoje imię lub pseudonim.",
      "selectServiceError": "Wybierz przynajmniej jedną kategorię usług.",
      "agreeTermsError": "Wymagana jest akceptacja regulaminu."
    },
    "workspace": {
      "activeTitle": "Aktywny (Gotowy do wyjazdu)",
      "activeDesc": "Jesteś obecnie dostępny do nowych zleceń. Przełącz na pauzę, gdy robisz przerwę.",
      "pauseBtn": "Wstrzymaj dostępność",
      "pausedTitle": "Wstrzymany (Przerwa)",
      "pausedDesc": "Przyjmowanie wezwań jest wstrzymane. Włącz ponownie, gdy będziesz gotowy do pracy.",
      "resumeBtn": "Wznów aktywność",
      "hotlineTitle": "Główne infolinie dyspozytorskie",
      "hotlineDesc": "W razie braku dostępu do aplikacji lub pilnych zmian natychmiast skontaktuj się z naszym zespołem.",
      "team1": "Infolinia Zespół 1 (Pilne)",
      "team2": "Infolinia Zespół 2 (Standard)",
      "call": "Zadzwoń",
      "sms": "SMS",
      "servicesTitle": "Zarządzanie kategoriami usług",
      "servicesDesc": "Kliknij, aby usunąć niedostępne usługi lub dodać nowe w czasie rzeczywistym.",
      "categoriesActive": "Aktywne kategorie",
      "serviceActive": "Aktywna",
      "serviceDisabled": "Wyłączona",
      "regionsTitle": "Obsługiwane regiony wyjazdowe",
      "regionsDesc": "Kliknij ✕, aby usunąć region, lub dodaj nowe dostępne obszary.",
      "regionsCount": "Ustawione regiony",
      "addRegionBtn": "Dodaj region"
    }
  },
  "de": {
    "tech": {
      "securitySessionNotice": "3-Monats-Sicherheitssitzung: 90-Tage-Zufallszugriffsschlüssel per Mobilfunknummer ausgestellt",
      "securitySessionExpiry": "Ablauf der Sicherheitssitzung",
      "securitySessionExpired": "Sicherheitssitzung abgelaufen",
      "autoMaintainedDays": "Tage automatisch aufrechterhalten",
      "operatingRegions": "Einsatzgebiete",
      "instantDispatchConnected": "Direkte Kundenverbindung",
      "registeredServices": "Registrierte Dienstleistungen",
      "categoriesRegisteredCount": "Kategorien registriert",
      "editableInWorkspace": "Im Handwerkerbereich bearbeitbar",
      "openWorkspaceBtn": "Meinen Handwerkerbereich verwalten",
      "statusActiveShort": "Bereit für Einsätze",
      "statusPausedShort": "Vorübergehend pausiert",
      "clickToToggle": "Klicken zum Umschalten",
      "hotlineNotice": "Hauptsystem-Hotline"
    },
    "workspace": {
      "activeTitle": "Aktiv (Einsatzbereit)",
      "activeDesc": "Sie sind derzeit für neue Einsätze verfügbar. Wechseln Sie bei Pausen in den Pause-Modus.",
      "pauseBtn": "Verfügbarkeit pausieren",
      "pausedTitle": "Pausiert (In Pause)",
      "pausedDesc": "Einsatzanrufe sind derzeit pausiert. Schalten Sie zurück, wenn Sie arbeitsbereit sind.",
      "resumeBtn": "Wieder aktivieren",
      "hotlineTitle": "Haupt-Einsatzhotlines",
      "hotlineDesc": "Falls kein App-Zugriff möglich ist oder dringende Änderungen auftreten, kontaktieren Sie uns bitte sofort.",
      "team1": "Team 1 Hotline (Dringend)",
      "team2": "Team 2 Hotline (Standard)",
      "call": "Anrufen",
      "sms": "SMS",
      "servicesTitle": "Verwaltung der Leistungskategorien",
      "servicesDesc": "Klicken Sie, um Dienste zu entfernen oder neue Kategorien in Echtzeit hinzuzufügen.",
      "categoriesActive": "Aktive Kategorien",
      "serviceActive": "Aktiv",
      "serviceDisabled": "Deaktiviert",
      "regionsTitle": "Einsatzregionen",
      "regionsDesc": "Klicken Sie auf ✕, um Regionen zu entfernen, oder fügen Sie neue Einsatzgebiete hinzu.",
      "regionsCount": "Festgelegte Regionen",
      "addRegionBtn": "Region hinzufügen"
    }
  },
  "fr": {
    "tech": {
      "securitySessionNotice": "Session de sécurité de 3 mois : clé d'accès aléatoire de 90 jours émise par numéro de mobile",
      "securitySessionExpiry": "Expiration de la session de sécurité",
      "securitySessionExpired": "Session de sécurité expirée",
      "autoMaintainedDays": "jours maintenus automatiquement",
      "operatingRegions": "Zones d'intervention",
      "instantDispatchConnected": "Connexion client instantanée",
      "registeredServices": "Services enregistrés",
      "categoriesRegisteredCount": "catégories enregistrées",
      "editableInWorkspace": "Modifiable dans l'espace artisan",
      "openWorkspaceBtn": "Gérer mon espace artisan",
      "statusActiveShort": "Disponible pour intervention",
      "statusPausedShort": "Temporairement en pause",
      "clickToToggle": "Cliquer pour basculer",
      "hotlineNotice": "Ligne d'assistance principale"
    },
    "workspace": {
      "activeTitle": "Actif (Disponible pour intervention)",
      "activeDesc": "Vous êtes actuellement disponible pour de nouvelles interventions. Mettez en pause pendant vos temps de repos.",
      "pauseBtn": "Mettre en pause",
      "pausedTitle": "En pause (En pause)",
      "pausedDesc": "Les appels d'intervention sont suspendus. Réactivez dès que vous êtes prêt à travailler.",
      "resumeBtn": "Reprendre l'activité",
      "hotlineTitle": "Lignes directes d'urgence",
      "hotlineDesc": "En cas d'impossibilité d'accéder à l'application ou d'urgence, contactez notre équipe immédiatement.",
      "team1": "Ligne Équipe 1 (Urgent)",
      "team2": "Ligne Équipe 2 (Standard)",
      "call": "Appeler",
      "sms": "SMS",
      "servicesTitle": "Gestion des catégories de services",
      "servicesDesc": "Cliquez pour retirer des services indisponibles ou en ajouter de nouveaux en temps réel.",
      "categoriesActive": "Catégories actives",
      "serviceActive": "Actif",
      "serviceDisabled": "Désactivé",
      "regionsTitle": "Zones d'intervention",
      "regionsDesc": "Cliquez sur ✕ pour retirer des zones, ou ajoutez de nouveaux secteurs disponibles.",
      "regionsCount": "Régions définies",
      "addRegionBtn": "Ajouter une région"
    }
  },
  "es": {
    "tech": {
      "securitySessionNotice": "Sesión de seguridad de 3 meses: clave de acceso aleatoria de 90 días emitida por móvil",
      "securitySessionExpiry": "Vencimiento de sesión de seguridad",
      "securitySessionExpired": "Sesión de seguridad vencida",
      "autoMaintainedDays": "días mantenidos automáticamente",
      "operatingRegions": "Regiones de servicio",
      "instantDispatchConnected": "Conexión inmediata con clientes",
      "registeredServices": "Servicios registrados",
      "categoriesRegisteredCount": "categorías registradas",
      "editableInWorkspace": "Editable en el panel de técnico",
      "openWorkspaceBtn": "Administrar mi panel de técnico",
      "statusActiveShort": "Disponible para salidas",
      "statusPausedShort": "En pausa temporal",
      "clickToToggle": "Haz clic para cambiar",
      "hotlineNotice": "Línea de soporte principal"
    },
    "workspace": {
      "activeTitle": "Activo (Disponible para salidas)",
      "activeDesc": "Estás disponible para nuevos avisos. Cambia a pausa cuando descanses.",
      "pauseBtn": "Pausar disponibilidad",
      "pausedTitle": "En pausa (En descanso)",
      "pausedDesc": "Los avisos de salida están pausados. Reactívalo cuando estés listo para trabajar.",
      "resumeBtn": "Reanudar actividad",
      "hotlineTitle": "Líneas directas de emergencia",
      "hotlineDesc": "Si no puedes acceder a la app o surge algún imprevisto urgente, contáctanos de inmediato.",
      "team1": "Línea Equipo 1 (Urgente)",
      "team2": "Línea Equipo 2 (Estándar)",
      "call": "Llamar",
      "sms": "SMS",
      "servicesTitle": "Gestión de categorías de servicios",
      "servicesDesc": "Haz clic para quitar servicios no disponibles o agregar nuevas categorías en tiempo real.",
      "categoriesActive": "Categorías activas",
      "serviceActive": "Activo",
      "serviceDisabled": "Desactivado",
      "regionsTitle": "Regiones de servicio activas",
      "regionsDesc": "Haz clic en ✕ para eliminar regiones o añade nuevas áreas disponibles.",
      "regionsCount": "Regiones configuradas",
      "addRegionBtn": "Agregar región"
    }
  },
  "it": {
    "tech": {
      "headlineLead": "Connettiti direttamente con i clienti nella tua zona",
      "securitySessionNotice": "Sessione di sicurezza di 3 mesi: chiave di accesso di 90 giorni emessa via cellulare",
      "securitySessionExpiry": "Scadenza sessione di sicurezza",
      "securitySessionExpired": "Sessione di sicurezza scaduta",
      "autoMaintainedDays": "giorni mantenuti automaticamente",
      "operatingRegions": "Zone di intervento",
      "instantDispatchConnected": "Connessione immediata con i clienti",
      "registeredServices": "Servizi registrati",
      "categoriesRegisteredCount": "categorie registrate",
      "editableInWorkspace": "Modificabile nell'area tecnico",
      "openWorkspaceBtn": "Gestisci la mia area tecnico",
      "statusActiveShort": "Disponibile per interventi",
      "statusPausedShort": "Temporaneamente in pausa",
      "clickToToggle": "Clicca per cambiare",
      "hotlineNotice": "Linea di supporto principale"
    },
    "workspace": {
      "activeTitle": "Attivo (Disponibile per interventi)",
      "activeDesc": "Sei attualmente disponibile per nuovi interventi. Metti in pausa durante i tuoi momenti di riposo.",
      "pauseBtn": "Sospendi disponibilità",
      "pausedTitle": "In pausa (In riposo)",
      "pausedDesc": "Le chiamate sono sospese. Riattiva quando sei pronto per lavorare.",
      "resumeBtn": "Riprendi attività",
      "hotlineTitle": "Linee dirette di emergenza",
      "hotlineDesc": "Se non riesci ad accedere all'app o si verificano urgenze, contattaci immediatamente.",
      "team1": "Linea Team 1 (Urgente)",
      "team2": "Linea Team 2 (Standard)",
      "call": "Chiama",
      "sms": "SMS",
      "servicesTitle": "Gestione categorie di servizio",
      "servicesDesc": "Clicca per rimuovere servizi non disponibili o aggiungere nuove categorie in tempo reale.",
      "categoriesActive": "Categorie attive",
      "serviceActive": "Attivo",
      "serviceDisabled": "Disattivato",
      "regionsTitle": "Zone operative di intervento",
      "regionsDesc": "Clicca su ✕ per rimuovere zone o aggiungi nuove aree disponibili.",
      "regionsCount": "Regioni impostate",
      "addRegionBtn": "Aggiungi regione"
    }
  },
  "ru": {
    "tech": {
      "securitySessionNotice": "3-месячная сессия безопасности: 90-дневный ключ доступа по номеру телефона",
      "securitySessionExpiry": "Истечение срока сессии безопасности",
      "securitySessionExpired": "Срок сессии безопасности истек",
      "autoMaintainedDays": "дней автоматического поддержания",
      "operatingRegions": "Регионы выезда",
      "instantDispatchConnected": "Мгновенная связь с клиентом",
      "registeredServices": "Зарегистрированные услуги",
      "categoriesRegisteredCount": "категории зарегистрировано",
      "editableInWorkspace": "Редактируется в кабинете мастера",
      "openWorkspaceBtn": "Управление кабинетом мастера",
      "statusActiveShort": "Доступен для выездов",
      "statusPausedShort": "Временно на паузе",
      "clickToToggle": "Нажмите для переключения",
      "hotlineNotice": "Основная горячая линия системы"
    },
    "workspace": {
      "activeTitle": "Активен (Готов к выездам)",
      "activeDesc": "Вы принимаете новые заказы. Переключите на паузу во время перерыва.",
      "pauseBtn": "Приостановить доступность",
      "pausedTitle": "На паузе (Перерыв)",
      "pausedDesc": "Прием вызовов временно приостановлен. Включите активность, когда будете готовы.",
      "resumeBtn": "Возобновить активность",
      "hotlineTitle": "Горячие линии диспетчера",
      "hotlineDesc": "Если нет доступа к приложению или возникли срочные изменения, немедленно свяжитесь с нами.",
      "team1": "Линия Команда 1 (Срочно)",
      "team2": "Линия Команда 2 (Обычная)",
      "call": "Позвонить",
      "sms": "SMS",
      "servicesTitle": "Управление категориями услуг",
      "servicesDesc": "Нажмите, чтобы отключить недоступные услуги или добавить новые категории.",
      "categoriesActive": "Активные категории",
      "serviceActive": "Активна",
      "serviceDisabled": "Отключена",
      "regionsTitle": "Рабочие регионы выезда",
      "regionsDesc": "Нажмите ✕, чтобы удалить регион, или добавьте новые доступные районы.",
      "regionsCount": "Установленные регионы",
      "addRegionBtn": "Добавить регион"
    }
  },
  "uk": {
    "tech": {
      "headlineLead": "Прямий зв'язок із клієнтами поруч із вами",
      "securitySessionNotice": "3-місячна безпечна сесія: 90-денний ключ доступу за номером телефону",
      "securitySessionExpiry": "Закінчення безпечної сесії",
      "securitySessionExpired": "Безпечна сесія закінчилася",
      "autoMaintainedDays": "днів автоматичного підтримання",
      "operatingRegions": "Регіони виїздів",
      "instantDispatchConnected": "Миттєвий зв'язок із клієнтом",
      "registeredServices": "Зареєстровані послуги",
      "categoriesRegisteredCount": "категорій зареєстровано",
      "editableInWorkspace": "Змінюється в кабінеті майстра",
      "openWorkspaceBtn": "Керувати кабінетом майстра",
      "statusActiveShort": "Доступний для виїздів",
      "statusPausedShort": "Тимчасово на паузі",
      "clickToToggle": "Натисніть для перемикання",
      "hotlineNotice": "Головна гаряча лінія системи"
    },
    "workspace": {
      "activeTitle": "Активний (Готовий до виїздів)",
      "activeDesc": "Ви доступні для нових замовлень. Перемикайтеся на паузу під час відпочинку.",
      "pauseBtn": "Призупинити доступність",
      "pausedTitle": "На паузі (Перерва)",
      "pausedDesc": "Прийом викликів призупинено. Увімкніть активність, коли будете готові до роботи.",
      "resumeBtn": "Відновити активність",
      "hotlineTitle": "Горячі лінії диспетчера",
      "hotlineDesc": "У разі відсутності доступу до додатку або термінових змін негайно зателефонуйте нам.",
      "team1": "Лінія Команда 1 (Терміново)",
      "team2": "Лінія Команда 2 (Звичайна)",
      "call": "Зателефонувати",
      "sms": "SMS",
      "servicesTitle": "Керування категоріями послуг",
      "servicesDesc": "Натисніть, щоб видалити недоступні послуги або додати нові в реальному часі.",
      "categoriesActive": "Активні категорії",
      "serviceActive": "Активна",
      "serviceDisabled": "Вимкнена",
      "regionsTitle": "Регіони обслуговування",
      "regionsDesc": "Натисніть ✕, щоб прибрати регіон, або додайте нові доступні райони.",
      "regionsCount": "Встановлені регіони",
      "addRegionBtn": "Додати регіон"
    }
  }
}

