# scripts/dict_remaining_languages.py
# Complete translations for remaining languages:
# am, ar, arz, bn, fa, he, kk, km, mn, my, ne, si, ta, tet, tr

REMAINING_TECH_WS = {
  "ar": {
    "workspace": {
      "mainHome": "← الصفحة الرئيسية لـ LIFE.HELP",
      "securitySessionBadge": "جلسة أمان مدتها 3 أشهر",
      "daysRemaining": "أيام متبقية",
      "viewContract": "عرض العقد الإلكتروني",
      "logout": "تسجيل الخروج",
      "availTitle": "إدارة التوفر في الوقت الفعلي",
      "statusActive": "نشط (جاهز للانطلاق)",
      "statusPaused": "متوقف مؤقتاً (استراحة)",
      "descActive": "أنت جاهز لتلقي طلبات جديدة. قم بالتبديل إلى الإيقاف المؤقت عند أخذ استراحة.",
      "descPaused": "تلقي الطلبات متوقف مؤقتاً. أعد التفعيل عندما تكون مستعداً للعمل.",
      "btnPause": "⏸ إيقاف التوفر مؤقتاً",
      "btnResume": "🟢 استئناف النشاط",
      "removeRegionTitle": "إزالة المنطقة",
      "setHours": "الساعات المحددة",
      "contractName": "الاسم الكامل",
      "contractPhone": "رقم الهاتف المحمول",
      "contractResidentId": "رقم الهوية (مخفي)",
      "contractSignedAt": "تاريخ ووقت التوقيع",
      "contractClauseTitle": "بند الالتزام والإخطار بالتغييرات",
      "contractClauseDesc": "يلتزم الفني بإخطار المركز فوراً في حالة عدم القدرة على العمل أو تغيير المنطقة أو الخدمة.",
      "contractSignature": "تم التحقق من التوقيع الإلكتروني",
      "close": "إغلاق",
      "minServiceAlert": "يجب الحفاظ على فئة خدمة واحدة على الأقل.",
      "serviceRemoved": "تمت إزالة فئة الخدمة.",
      "serviceAdded": "تمت إضافة فئة خدمة جديدة.",
      "regionAdded": "تمت إضافة المنطقة إلى نطاق العمل.",
      "minRegionAlert": "يجب تعيين منطقة عمل واحدة على الأقل.",
      "regionRemoved": "تمت إزالة المنطقة من نطاق العمل.",
      "minDayAlert": "يجب تحديد يوم عمل واحد على الأقل.",
      "daysUpdated": "تم تحديث أيام العمل.",
      "logoutConfirm": "هل أنت متأكد من رغبتك في تسجيل الخروج من مساحة العمل؟",
      "adminChat": "الاتصال بالإدارة المركزية",
      "openAdminChat": "رسائل الإدارة",
      "adminChatTitle": "محادثة مباشرة 1:1 مع الإدارة",
      "adminChatOnline": "متصل",
      "adminChatRecipient": "المستلم: الفني",
      "adminChatEmpty": "لا توجد رسائل متبادلة مع الإدارة.",
      "adminChatEmptyHint": "اترك استفساراتك أو البلاغات العاجلة هنا وسيقوم المسؤول بمراجعتها.",
      "adminChatPlaceholder": "اكتب رسالة إلى الإدارة...",
      "adminChatSend": "إرسال",
      "calendarClose": "إغلاق",
      "monthUnit": "شهر",
      "adminChatRecipientCounselor": "المستلم: المستشار",
      "adminNoticeBanner": "[إشعار الإدارة المركزية]",
      "unreadCount": "غير مقروءة",
      "preset24Hours": "جاهزية فورية 24 ساعة",
      "presetDay": "نهاري (09:00 ~ 18:00)",
      "presetNight": "ليلي وطوارئ (18:00 ~ 09:00)",
      "presetMorning": "صباحي (09:00 ~ 13:00)",
      "presetAfternoon": "مسائي (13:00 ~ 18:00)"
    }
  },
  "arz": {
    "tech": {
      "accessKeyLabel": "رمز الدخول المخصص لـ 3 شهور",
      "loginWithAccessKey": "تسجيل الدخول برمز الأمان (صالح 90 يوم)",
      "loginKeyNotice": "اكتب رمز الدخول المخصص اللي وصلك في رسالة SMS عشان تدخل فوراً لمساحة شغلك.",
      "lostCodeBtn": "ضيعت الرمز؟",
      "reissueCodeTitle": "إعادة إصدار الرمز برقم الموبايل",
      "getAccessKeyBtn": "الحصول على رمز أمان لـ 3 شهور",
      "registerAndStart": "سجل وابدأ الشغل برمز الـ 3 شهور",
      "selectServices": "اختار مجالات الخدمات",
      "selectServicesDesc": "اختار كل الخدمات اللي تقدر تنفذها (تقدر تعدلها بعدين من مساحة العمل).",
      "selectedCount": " تم اختيارهم",
      "helperNameLabel": "اسم الفني (الاسم الحقيقي أو المستعار)",
      "agreeTerms": "أنا موافق على شروط السلامة وتعليمات العمل في LIFE.HELP.",
      "keySentNotice": "تم إرسال رمز الدخول في رسالة SMS",
      "issuedAccessKey": "رمز الدخول الصادر لـ 3 شهور",
      "copy": "نسخ",
      "copied": "تم النسخ!",
      "backToTechHome": "الرجوع لصفحة الفني الرئيسية",
      "verifying": "جاري التحقق...",
      "changePhoneBtn": "تغيير الرقم",
      "enterAccessKeyError": "من فضلك اكتب رمز الأمان الخاص بك.",
      "enterNameError": "من فضلك اكتب اسمك.",
      "selectServiceError": "اختار على الأقل خدمة واحدة.",
      "agreeTermsError": "لازم توافق على الشروط والأحكام."
    },
    "workspace": {
      "mainHome": "← الرئيسية لـ LIFE.HELP",
      "securitySessionBadge": "جلسة أمان 3 شهور",
      "daysRemaining": "أيام فاضلة",
      "signedDate": "تاريخ العقد",
      "viewContract": "عرض العقد الإلكتروني",
      "logout": "خروج",
      "availTitle": "إدارة التوفر فورياً",
      "statusActive": "شغال (جاهز للطلبات)",
      "statusPaused": "موقف مؤقتاً (استراحة)",
      "descActive": "أنت متاح للطلبات الجديدة دلوقتي. وقف النشاط وقت راحتك.",
      "descPaused": "استقبال الطلبات واقف مؤقتاً. شغله تاني لما تكون جاهز.",
      "btnPause": "⏸ وقف مؤقتاً",
      "btnResume": "🟢 شغل النشاط تاني",
      "removeRegionTitle": "مسح المنطقة",
      "setHours": "الساعات المحددة",
      "contractName": "الاسم بالكامل",
      "contractPhone": "رقم الموبايل",
      "contractResidentId": "الرقم القومي (مخفي)",
      "contractSignedAt": "تاريخ ووقت الإمضاء",
      "contractClauseTitle": "بند الالتزام والإبلاغ",
      "contractClauseDesc": "الفني ملتزم بتبليغ الإدارة فوراً لو مش قادر ينزل أو غير منطقته.",
      "contractSignature": "التوقيع الإلكتروني متأكد",
      "close": "قفل",
      "minServiceAlert": "لازم تفضل خدمة واحدة على الأقل نشطة.",
      "serviceRemoved": "الخدمة اتشالت.",
      "serviceAdded": "اتضافت خدمة جديدة.",
      "regionAdded": "المنطقة اتضافت لمنطقة الشغل.",
      "minRegionAlert": "لازم تحدد منطقة واحدة على الأقل.",
      "regionRemoved": "المنطقة اتشالت.",
      "minDayAlert": "اختار على الأقل يوم واحد.",
      "daysUpdated": "أيام الشغل اتحدثت.",
      "logoutConfirm": "متأكد إنك عايز تخرج من مساحة الشغل؟",
      "adminChat": "تواصل مع الإدارة",
      "openAdminChat": "رسايل الإدارة",
      "adminChatTitle": "شات مباشر 1:1 مع الإدارة",
      "adminChatOnline": "أونلاين",
      "adminChatRecipient": "المستلم: الفني",
      "adminChatEmpty": "مفيش رسايل مع الإدارة.",
      "adminChatEmptyHint": "سيب سؤالك أو بلاغك هنا والإدارة هترد بسرعة.",
      "adminChatPlaceholder": "اكتب رسالتك للإدارة...",
      "adminChatSend": "ابعت",
      "calendarClose": "قفل",
      "monthUnit": "شهر",
      "adminChatRecipientCounselor": "المستلم: المستشار",
      "adminNoticeBanner": "[تنبيه الإدارة]",
      "unreadCount": "مش مقروءة",
      "preset24Hours": "جاهز 24 ساعة طوارئ",
      "presetDay": "بالنهار (09:00 ~ 18:00)",
      "presetNight": "بالليل وطوارئ (18:00 ~ 09:00)",
      "presetMorning": "الصبح (09:00 ~ 13:00)",
      "presetAfternoon": "بعد الظهر (13:00 ~ 18:00)"
    }
  },
  "tr": {
    "workspace": {
      "mainHome": "← LIFE.HELP Ana Sayfa",
      "securitySessionBadge": "3 Aylık Güvenlik Oturumu",
      "daysRemaining": "gün kaldı",
      "signedDate": "Sözleşme Tarihi",
      "viewContract": "Elektronik Sözleşmeyi Görüntüle",
      "logout": "Çıkış Yap",
      "availTitle": "Gerçek Zamanlı Müsaitlik Yönetimi",
      "statusActive": "Aktif (Göreve Hazır)",
      "statusPaused": "Duraklatıldı (Mola)",
      "descActive": "Yeni görev çağrılarına açıksınız. Mola verdiğinizde duraklatma moduna geçin.",
      "descPaused": "Görev çağrıları geçici olarak duraklatıldı. Çalışmaya hazır olduğunuzda tekrar aktif edin.",
      "btnPause": "⏸ Müsaitliği Duraklat",
      "btnResume": "🟢 Aktif Duruma Geç",
      "removeRegionTitle": "Bölgeyi Kaldır",
      "setHours": "Belirlenen Çalışma Saatleri",
      "contractName": "Ad Soyad",
      "contractPhone": "Cep Telefonu Numarası",
      "contractResidentId": "Kimlik No (Maskelenmiş)",
      "contractSignedAt": "Sözleşme İmzalanma Zamanı",
      "contractClauseTitle": "Yükümlülük ve Bildirim Maddesi",
      "contractClauseDesc": "Teknisyen, geçici olarak çalışamadığında veya bölge değişikliğinde durumu derhal merkeze bildirmeyi taahhüt eder.",
      "contractSignature": "Elektronik İmza Onaylandı",
      "close": "Kapat",
      "minServiceAlert": "En az bir hizmet kategorisi aktif kalmalıdır.",
      "serviceRemoved": "Hizmet kategorisi kaldırıldı.",
      "serviceAdded": "Yeni hizmet kategorisi eklendi.",
      "regionAdded": "Bölge hizmet alanına eklendi.",
      "minRegionAlert": "En az bir hizmet bölgesi seçilmelidir.",
      "regionRemoved": "Bölge hizmet alanından kaldırıldı.",
      "minDayAlert": "En az bir çalışma günü seçilmelidir.",
      "daysUpdated": "Çalışma günleri güncellendi.",
      "logoutConfirm": "Çalışma alanından çıkış yapmak istediğinize emin misiniz?",
      "adminChat": "Merkez Yönetim İletişimi",
      "openAdminChat": "Yönetici Mesajları",
      "adminChatTitle": "Merkez ile 1:1 Canlı İletişim",
      "adminChatOnline": "ÇEVRİMİÇİ",
      "adminChatRecipient": "Alıcı: Teknisyen",
      "adminChatEmpty": "Merkez yönetim ile iletilmiş mesaj yok.",
      "adminChatEmptyHint": "Sorularınızı veya acil durumları buradan iletebilirsiniz; yöneticimiz en kısa sürede inceleyecektir.",
      "adminChatPlaceholder": "Yöneticiye mesajınızı yazın...",
      "adminChatSend": "Gönder",
      "calendarClose": "Kapat",
      "monthUnit": "Ay",
      "adminChatRecipientCounselor": "Alıcı: Danışman",
      "adminNoticeBanner": "[Merkez Duyurusu]",
      "unreadCount": "okunmamış",
      "preset24Hours": "24 saat anında müdahale",
      "presetDay": "Gündüz (09:00 ~ 18:00)",
      "presetNight": "Gece ve Acil (18:00 ~ 09:00)",
      "presetMorning": "Sabah (09:00 ~ 13:00)",
      "presetAfternoon": "Öğleden Sonra (13:00 ~ 18:00)"
    }
  },
  "hi": {
    "workspace": {
      "mainHome": "← LIFE.HELP मुख्य पृष्ठ",
      "securitySessionBadge": "3 महीने का सुरक्षा सत्र",
      "daysRemaining": "दिन शेष",
      "viewContract": "ई-अनुबंध देखें",
      "logout": "लॉग आउट",
      "availTitle": "वास्तविक समय उपलब्धता प्रबंधन",
      "statusActive": "सक्रिय (ड्यूटी के लिए उपलब्ध)",
      "statusPaused": "विराम पर (अवकाश)",
      "descActive": "आप नई सेवा कॉलों के लिए उपलब्ध हैं। विश्राम के समय विराम पर स्विच करें।",
      "descPaused": "सेवा कॉल अस्थायी रूप से रुकी हुई हैं। तैयार होने पर पुनः सक्रिय करें।",
      "btnPause": "⏸ उपलब्धता रोकें",
      "btnResume": "🟢 पुनः सक्रिय करें",
      "adminChat": "मुख्यालय व्यवस्थापक से संपर्क",
      "openAdminChat": "संदेश देखें व उत्तर दें",
      "adminChatTitle": "मुख्यालय व्यवस्थापक 1:1 ऑनलाइन चैट",
      "adminChatOnline": "ऑनलाइन",
      "adminChatRecipient": "प्राप्तकर्ता: सहायक",
      "adminChatEmpty": "मुख्यालय से कोई संदेश नहीं है।",
      "adminChatEmptyHint": "पूछताछ या आपातकालीन संदेश यहाँ छोड़ें; व्यवस्थापक शीघ्र समीक्षा करेंगे।",
      "adminChatPlaceholder": "व्यवस्थापक को संदेश लिखें...",
      "adminChatSend": "भेजें",
      "calendarClose": "बंद करें",
      "monthUnit": "माह",
      "adminChatRecipientCounselor": "प्राप्तकर्ता: परामर्शदाता",
      "adminNoticeBanner": "[मुख्यालय सूचना]",
      "unreadCount": "अपठित",
      "preset24Hours": "24 घंटे त्वरित सेवा",
      "presetDay": "दिन का समय (09:00 ~ 18:00)",
      "presetNight": "रात व आपातकालीन (18:00 ~ 09:00)",
      "presetMorning": "सुबह (09:00 ~ 13:00)",
      "presetAfternoon": "दोपहर (13:00 ~ 18:00)"
    }
  },
  "bn": {
    "tech": {
      "accessKeyLabel": "৩ মাসের অ্যাক্সেস কী",
      "loginWithAccessKey": "নিরাপত্তা কোড দিয়ে লগইন (৯০ দিন কার্যকর)",
      "loginKeyNotice": "এসএমএসে প্রাপ্ত ৩ মাসের অ্যাক্সেস কোডটি লিখুন।",
      "lostCodeBtn": "কোড হারিয়েছেন?",
      "reissueCodeTitle": "মোবাইল নম্বরে কোড পুনঃপ্রদান",
      "getAccessKeyBtn": "৩ মাসের নিরাপত্তা কোড নিন",
      "registerAndStart": "নিবন্ধন করুন এবং সেবা শুরু করুন",
      "selectServices": "সেবা ক্ষেত্র নির্বাচন করুন",
      "selectServicesDesc": "আপনার দক্ষতার ক্ষেত্রগুলো বেছে নিন (পরে পরিবর্তন সম্ভব)।",
      "selectedCount": " টি নির্বাচিত",
      "helperNameLabel": "সহায়তাকারীর নাম (আসল বা ডাকনাম)",
      "agreeTerms": "আমি LIFE.HELP-এর নিয়ম ও নিরাপত্তা নীতিমালা মেনে চলার অঙ্গীকার করছি।",
      "keySentNotice": "এসএমএসে অ্যাক্সেস কোড পাঠানো হয়েছে",
      "issuedAccessKey": "প্রদত্ত ৩ মাসের অ্যাক্সেস কোড",
      "copy": "কপি",
      "copied": "কপি হয়েছে!",
      "backToTechHome": "মূল পৃষ্ঠায় ফিরে যান",
      "verifying": "যাচাই করা হচ্ছে...",
      "changePhoneBtn": "নম্বর পরিবর্তন",
      "enterAccessKeyError": "দয়া করে ৩ মাসের অ্যাক্সেস কোড দিন।",
      "enterNameError": "দয়া করে আপনার নাম লিখুন।",
      "selectServiceError": "কমপক্ষে একটি সেবা নির্বাচন করুন।",
      "agreeTermsError": "নিয়মাবলীতে সম্মতি দেওয়া আবশ্যক।"
    },
    "workspace": {
      "mainHome": "← LIFE.HELP মূল পাতা",
      "securitySessionBadge": "৩ মাসের নিরাপত্তা সেশন",
      "daysRemaining": "দিন বাকি",
      "signedDate": "চুক্তির তারিখ",
      "viewContract": "ইলেকট্রনিক চুক্তি দেখুন",
      "logout": "লগ আউট",
      "availTitle": "রিয়েল-টাইম প্রাপ্যতা পরিচালনা",
      "statusActive": "সক্রিয় (সেবা প্রদানে প্রস্তুত)",
      "statusPaused": "বিরতি (সাময়িক বন্ধ)",
      "descActive": "আপনি নতুন কল গ্রহণের জন্য উপলব্ধ। বিশ্রামের সময় বিরতিতে স্যুইচ করুন।",
      "descPaused": "কল সাময়িকভাবে বন্ধ আছে। প্রস্তুত হলে আবার সক্রিয় করুন।",
      "btnPause": "⏸ সাময়িক বিরতি",
      "btnResume": "🟢 পুনরায় সক্রিয় করুন",
      "adminChat": "প্রধান কার্যালয় যোগাযোগ",
      "openAdminChat": "বার্তা দেখুন ও উত্তর দিন",
      "adminChatTitle": "প্রশাসকের সাথে ১:১ চ্যাট",
      "adminChatOnline": "অনলাইন",
      "adminChatRecipient": "প্রাপক: সহায়তাকারী",
      "adminChatEmpty": "কোনো বার্তা নেই।",
      "adminChatEmptyHint": "জরুরি তথ্য বা প্রশ্ন এখানে লিখুন; প্রশাসক দ্রুত উত্তর দেবেন।",
      "adminChatPlaceholder": "বার্তা লিখুন...",
      "adminChatSend": "পাঠান",
      "calendarClose": "বন্ধ করুন",
      "monthUnit": "মাস",
      "adminChatRecipientCounselor": "প্রাপক: পরামর্শক",
      "adminNoticeBanner": "[প্রধান কার্যালয়ের বিজ্ঞপ্তি]",
      "unreadCount": "অপঠিত",
      "preset24Hours": "২৪ ঘণ্টা সার্বক্ষণিক সেবা",
      "presetDay": "দিনের শিফট (০৯:০০ ~ ১৮:০০)",
      "presetNight": "রাতের ও জরুরি (১৮:০০ ~ ০৯:০০)",
      "presetMorning": "সকাল (০৯:০০ ~ ১৩:০০)",
      "presetAfternoon": "দুপুর (১৩:০০ ~ ১৮:০০)"
    }
  },
  "fa": {
    "tech": {
      "accessKeyLabel": "کلید دسترسی اختصاصی ۳ ماهه",
      "loginWithAccessKey": "ورود با کد امنیتی (اعتبار ۹۰ روز)",
      "loginKeyNotice": "کد امنیتی دریافت شده از پیامک را برای ورود فوری به میز کار وارد کنید.",
      "lostCodeBtn": "کد را فراموش کرده‌اید؟",
      "reissueCodeTitle": "صدور مجدد کد با شماره همراه",
      "getAccessKeyBtn": "دریافت کد امنیتی ۳ ماهه",
      "registerAndStart": "ثبت نام و شروع فعالیت",
      "selectServices": "انتخاب حوزه‌های خدمات",
      "selectServicesDesc": "تمامی خدماتی که می‌توانید ارائه دهید را انتخاب کنید.",
      "selectedCount": " مورد انتخاب شد",
      "helperNameLabel": "نام متخصص (نام مستعار یا واقعی)",
      "agreeTerms": "قوانین و اصول ایمنی LIFE.HELP را می‌پذیرم و به خدمت‌رسانی متعهد می‌شوم.",
      "keySentNotice": "کد دسترسی از طریق پیامک ارسال شد",
      "issuedAccessKey": "کد دسترسی ۳ ماهه صادر شده",
      "copy": "کپی",
      "copied": "کپی شد!",
      "backToTechHome": "بازگشت به صفحه اصلی",
      "verifying": "در حال بررسی...",
      "changePhoneBtn": "تغییر شماره",
      "enterAccessKeyError": "لطفاً کد امنیتی ۳ ماهه را وارد کنید.",
      "enterNameError": "لطفاً نام خود را وارد کنید.",
      "selectServiceError": "حداقل یک حوزه خدمت را انتخاب کنید.",
      "agreeTermsError": "پذیرش شرایط و قوانین الزامی است."
    },
    "workspace": {
      "mainHome": "← صفحه اصلی LIFE.HELP",
      "securitySessionBadge": "نشست امنیتی ۳ ماهه",
      "daysRemaining": "روز باقی‌مانده",
      "signedDate": "تاریخ قرارداد",
      "viewContract": "مشاهده قرارداد الکترونیک",
      "logout": "خروج",
      "availTitle": "مدیریت وضعیت دسترسی بلادرنگ",
      "statusActive": "فعال (آماده اعزام)",
      "statusPaused": "متوقف موقت (استراحت)",
      "descActive": "شما آماده دریافت درخواست‌های جدید هستید. در زمان استراحت وضعیت را تغییر دهید.",
      "descPaused": "دریافت درخواست‌ها متوقف شده است. در صورت آمادگی دوباره فعال کنید.",
      "btnPause": "⏸ توقف موقت دسترسی",
      "btnResume": "🟢 فعال‌سازی مجدد",
      "adminChat": "ارتباط با مدیر مرکزی",
      "openAdminChat": "مشاهده پیام‌ها و پاسخ",
      "adminChatTitle": "گفتگوی ۱:۱ با مدیر مرکزی",
      "adminChatOnline": "آنلاین",
      "adminChatRecipient": "گیرنده: متخصص",
      "adminChatEmpty": "پیامی با مدیر مرکزی رد و بدل نشده است.",
      "adminChatEmptyHint": "سؤالات یا موارد اضطراری را اینجا بنویسید؛ مدیر بررسی خواهد کرد.",
      "adminChatPlaceholder": "پیام خود را بنویسید...",
      "adminChatSend": "ارسال",
      "calendarClose": "بستن",
      "monthUnit": "ماه",
      "adminChatRecipientCounselor": "گیرنده: مشاور",
      "adminNoticeBanner": "[اطلاعیه مدیریت مرکزی]",
      "unreadCount": "خوانده نشده",
      "preset24Hours": "آمادگی ۲۴ ساعته برای اعزام",
      "presetDay": "روزانه (۰۹:۰۰ تا ۱۸:۰۰)",
      "presetNight": "شبانه و اضطراری (۱۸:۰۰ تا ۰۹:۰۰)",
      "presetMorning": "صبح (۰۹:۰۰ تا ۱۳:۰۰)",
      "presetAfternoon": "بعدازظهر (۱۳:۰۰ تا ۱۸:۰۰)"
    }
  },
  "he": {
    "tech": {
      "accessKeyLabel": "מפתח גישה מאובטח ל-3 חודשים",
      "loginWithAccessKey": "כניסה עם קוד אבטחה (בתוקף ל-90 יום)",
      "loginKeyNotice": "הזן את קוד הגישה שקיבלת ב-SMS לכניסה מיידית למרחב העבודה.",
      "lostCodeBtn": "איבדת את הקוד?",
      "reissueCodeTitle": "הנפקה חוזרת של הקוד לפי מספר נייד",
      "getAccessKeyBtn": "קבלת קוד אבטחה ל-3 חודשים",
      "registerAndStart": "הרשמה והתחלת פעילות",
      "selectServices": "בחירת תחומי שירות",
      "selectServicesDesc": "בחר את כל התחומים שבהם תוכל להעניק שירות.",
      "selectedCount": " נבחרו",
      "helperNameLabel": "שם איש המקצוע (שם מלא או כינוי)",
      "agreeTerms": "קראתי ואני מאשר את כללי הפעילות והבטיחות של LIFE.HELP.",
      "keySentNotice": "קוד הגישה נשלח בהצלחה ב-SMS",
      "issuedAccessKey": "קוד גישה ל-3 חודשים שהונפק",
      "copy": "העתק",
      "copied": "הועתק!",
      "backToTechHome": "חזרה לדף המבוא",
      "verifying": "מאמת פרטים...",
      "changePhoneBtn": "שינוי מספר",
      "enterAccessKeyError": "נא להזין את קוד האבטחה.",
      "enterNameError": "נא להזין שם.",
      "selectServiceError": "נא לבחור לפחות תחום שירות אחד.",
      "agreeTermsError": "יש לאשר את תנאי השירות."
    },
    "workspace": {
      "mainHome": "← דף הבית LIFE.HELP",
      "securitySessionBadge": "סשן אבטחה של 3 חודשים",
      "daysRemaining": "ימים נותרו",
      "signedDate": "תאריך החוזה",
      "viewContract": "צפייה בחוזה האלקטרוני",
      "logout": "התנתקות",
      "availTitle": "ניהול זמינות בזמן אמת",
      "statusActive": "פעיל (זמין לקריאות)",
      "statusPaused": "מושהה (בהפסקה)",
      "descActive": "אתה זמין לקבלת קריאות חדשות. העבר להשהיה בעת מנוחה.",
      "descPaused": "קבלת הקריאות מושהית כעת. החזר לפעיל כשתהיה מוכן לעבוד.",
      "btnPause": "⏸ השהה זמינות",
      "btnResume": "🟢 חזור לזמינות פעילה",
      "adminChat": "יצירת קשר עם ההנהלה",
      "openAdminChat": "הודעות מההנהלה",
      "adminChatTitle": "צ'אט 1:1 ישיר עם ההנהלה",
      "adminChatOnline": "מחובר",
      "adminChatRecipient": "נמען: מומחה",
      "adminChatEmpty": "אין הודעות מההנהלה.",
      "adminChatEmptyHint": "השאר פניות או דיווחי חירום כאן; המנהל יבדוק בהקדם.",
      "adminChatPlaceholder": "הקלד הודעה להנהלה...",
      "adminChatSend": "שלח",
      "calendarClose": "סגור",
      "monthUnit": "חודש",
      "adminChatRecipientCounselor": "נמען: יועץ",
      "adminNoticeBanner": "[הודעת הנהלה ראשית]",
      "unreadCount": "לא נקראו",
      "preset24Hours": "זמינות 24/7 להגעה מיידית",
      "presetDay": "יום (09:00 ~ 18:00)",
      "presetNight": "לילה וחירום (18:00 ~ 09:00)",
      "presetMorning": "בוקר (09:00 ~ 13:00)",
      "presetAfternoon": "אחר הצהריים (13:00 ~ 18:00)"
    }
  },
  "kk": {
    "tech": {
      "accessKeyLabel": "3 айлық арнайы қауіпсіздік коды",
      "loginWithAccessKey": "Қауіпсіздік кодымен кіру (90 күн жарамды)",
      "loginKeyNotice": "SMS арқылы алған кодты жұмыс кабинетіне кіру үшін енгізіңіз.",
      "lostCodeBtn": "Кодты ұмыттыңыз ба?",
      "reissueCodeTitle": "Нөмір бойынша кодты қайта алу",
      "getAccessKeyBtn": "3 айлық кіру кодын алу",
      "registerAndStart": "Тіркелу және жұмысты бастау",
      "selectServices": "Қызмет санаттарын таңдаңыз",
      "selectServicesDesc": "Орындай алатын барлық қызметтерді белгілеңіз.",
      "selectedCount": " таңдалды",
      "helperNameLabel": "Маманның аты-жөні",
      "agreeTerms": "LIFE.HELP ережелері мен қауіпсіздік талаптарымен келісемін.",
      "keySentNotice": "Кіру коды SMS арқылы сәтті жіберілді",
      "issuedAccessKey": "Берілген 3 айлық қауіпсіздік коды",
      "copy": "Көшіру",
      "copied": "Көшірілді!",
      "backToTechHome": "Басты бетке қайту",
      "verifying": "Тексерілуде...",
      "changePhoneBtn": "Нөмірді өзгерту",
      "enterAccessKeyError": "Қауіпсіздік кодын енгізіңіз.",
      "enterNameError": "Атыңызды енгізіңіз.",
      "selectServiceError": "Кемінде бір қызмет түрін таңдаңыз.",
      "agreeTermsError": "Ережелермен келісу міндетті."
    },
    "workspace": {
      "mainHome": "← LIFE.HELP Басты бет",
      "securitySessionBadge": "3 айлық қауіпсіздік сессиясы",
      "daysRemaining": "күн қалды",
      "signedDate": "Келісімшарт күні",
      "viewContract": "Электрондық келісімшартты көру",
      "logout": "Шығу",
      "availTitle": "Нақты уақыттағы қолжетімділікті басқару",
      "statusActive": "Белсенді (Шығуға дайын)",
      "statusPaused": "Кідіртілді (Үзіліс)",
      "descActive": "Сіз жаңа шақыртуларды қабылдауға дайынсыз. Демалғанда кідіртуге ауыстырыңыз.",
      "descPaused": "Шақыртулар уақытша тоқтатылды. Дайын болғанда қайта қосыңыз.",
      "btnPause": "⏸ Қолжетімділікті кідірту",
      "btnResume": "🟢 Қайта белсенді ету",
      "adminChat": "Орталық әкімшілікпен байланыс",
      "openAdminChat": "Хабарламаларды көру",
      "adminChatTitle": "Әкімшімен 1:1 онлайн байланыс",
      "adminChatOnline": "ОНЛАЙН",
      "adminChatRecipient": "Алушы: Маман",
      "adminChatEmpty": "Әкімшіліктен хабарлама жоқ.",
      "adminChatEmptyHint": "Сұрақтарыңыз немесе шұғыл хабарламаларды осында қалдырыңыз.",
      "adminChatPlaceholder": "Әкімшіге хабарлама жазу...",
      "adminChatSend": "Жіберу",
      "calendarClose": "Жабу",
      "monthUnit": "Ай",
      "adminChatRecipientCounselor": "Алушы: Кеңесші",
      "adminNoticeBanner": "[Орталық Хабарламасы]",
      "unreadCount": "оқылмаған",
      "preset24Hours": "24 сағат шұғыл дайындық",
      "presetDay": "Күндізгі (09:00 ~ 18:00)",
      "presetNight": "Түнгі және шұғыл (18:00 ~ 09:00)",
      "presetMorning": "Таңертеңгі (09:00 ~ 13:00)",
      "presetAfternoon": "Түстен кейінгі (13:00 ~ 18:00)"
    }
  },
  "uz": {
    "tech": {
      "accessKeyLabel": "3 oylik maxsus kirish kodi",
      "loginWithAccessKey": "Xavfsizlik kodi bilan kirish (90 kun amal qiladi)",
      "loginKeyNotice": "SMS orqali olingan 3 oylik kodni kiritib, darhol ish paneliga kiring.",
      "lostCodeBtn": "Kodni unutdingizmi?",
      "reissueCodeTitle": "Telefon raqami orqali kodni qayta olish",
      "getAccessKeyBtn": "3 oylik xavfsizlik kodini olish",
      "registerAndStart": "Ro'yxatdan o'tish va ish boshlash",
      "selectServices": "Xizmat turlarini tanlang",
      "selectServicesDesc": "Bajara oladigan barcha xizmat yo'nalishlarini belgilang.",
      "selectedCount": " ta tanlandi",
      "helperNameLabel": "Usta ismi (taxallus yoki haqiqiy ism)",
      "agreeTerms": "LIFE.HELP qoidalari va xavfsizlik talablariga roziman.",
      "keySentNotice": "Kirish kodi SMS orqali yuborildi",
      "issuedAccessKey": "Berilgan 3 oylik kirish kodi",
      "copy": "Nusxalash",
      "copied": "Nusxalandi!",
      "backToTechHome": "Bosh sahifaga qaytish",
      "verifying": "Tekshirilmoqda...",
      "changePhoneBtn": "Raqamni o'zgartirish",
      "enterAccessKeyError": "Iltimos, xavfsizlik kodini kiriting.",
      "enterNameError": "Iltimos, ismingizni kiriting.",
      "selectServiceError": "Kamida bitta xizmat turini tanlang.",
      "agreeTermsError": "Qoidalarga rozilik bildirish shart."
    },
    "workspace": {
      "mainHome": "← LIFE.HELP Bosh sahifa",
      "securitySessionBadge": "3 oylik xavfsizlik sessiyasi",
      "daysRemaining": "kun qoldi",
      "signedDate": "Shartnoma sanasi",
      "viewContract": "Elektron shartnomani ko'rish",
      "logout": "Chiqish",
      "availTitle": "Haqiqiy vaqtda faollikni boshqarish",
      "statusActive": "Faol (Chaqiruvga tayyor)",
      "statusPaused": "To'xtatilgan (Tanaffus)",
      "descActive": "Siz yangi buyurtmalarni qabul qilishga tayyorsiz. Dam olayotganda to'xtatib turing.",
      "descPaused": "Buyurtmalar vaqtincha to'xtatildi. Ishga tayyor bo'lgach, yana yoqing.",
      "btnPause": "⏸ Faollikni to'xtatish",
      "btnResume": "🟢 Faollikni tiklash",
      "adminChat": "Markaziy ma'muriyat bilan aloqa",
      "openAdminChat": "Xabarlarni ko'rish",
      "adminChatTitle": "Ma'muriyat bilan 1:1 onlayn suhbat",
      "adminChatOnline": "ONLAYN",
      "adminChatRecipient": "Qabul qiluvchi: Usta",
      "adminChatEmpty": "Ma'muriyatdan xabarlar yo'q.",
      "adminChatEmptyHint": "Savollar yoki favqulodda xabarlarni shu yerda qoldiring.",
      "adminChatPlaceholder": "Ma'muriyatga xabar yozing...",
      "adminChatSend": "Yuborish",
      "calendarClose": "Yopish",
      "monthUnit": "Oy",
      "adminChatRecipientCounselor": "Qabul qiluvchi: Maslahatchi",
      "adminNoticeBanner": "[Markaziy Xabarnoma]",
      "unreadCount": "o'qilmagan",
      "preset24Hours": "24 soatlik tezkor tayyorgarlik",
      "presetDay": "Kunduzgi (09:00 ~ 18:00)",
      "presetNight": "Tungi va favqulodda (18:00 ~ 09:00)",
      "presetMorning": "Ertalabki (09:00 ~ 13:00)",
      "presetAfternoon": "Tushdan keyingi (13:00 ~ 18:00)"
    }
  },
  "am": {
    "tech": {
      "accessKeyLabel": "የ 3 ወር የተለየ የመግቢያ ቁልፍ",
      "loginWithAccessKey": "በደህንነት ኮድ ይግቡ (ለ 90 ቀናት የሚቆይ)",
      "loginKeyNotice": "በኤስኤምኤስ የተላከውን የ 3 ወር ኮድ ያስገቡ።",
      "lostCodeBtn": "ኮዱ ጠፍቶብዎታል?",
      "reissueCodeTitle": "በስልክ ቁጥር ኮድ እንደገና ማግኘት",
      "getAccessKeyBtn": "የ 3 ወር የደህንነት ኮድ ያግኙ",
      "registerAndStart": "ይመዝገቡ እና ስራ ይጀምሩ",
      "selectServices": "የአገልግሎት ዘርፎችን ይምረጡ",
      "selectServicesDesc": "መስራት የሚችሉባቸውን አገልግሎቶች ይምረጡ።",
      "selectedCount": " ተመርጠዋል",
      "helperNameLabel": "የባለሙያ ስም",
      "agreeTerms": "የ LIFE.HELP ደንቦችን እና የደህንነት መመሪያዎችን አከብራለሁ።",
      "keySentNotice": "የመግቢያ ኮድ በኤስኤምኤስ ተልኳል",
      "issuedAccessKey": "የተሰጠው የ 3 ወር መግቢያ ኮድ",
      "copy": "ገልብጥ",
      "copied": "ተገልብጧል!",
      "backToTechHome": "ወደ ዋና ገጽ ተመለስ",
      "verifying": "በማረጋገጥ ላይ...",
      "changePhoneBtn": "ቁጥር ቀይር",
      "enterAccessKeyError": "እባክዎ የደህንነት ኮዱን ያስገቡ።",
      "enterNameError": "እባክዎ ስምዎን ያስገቡ።",
      "selectServiceError": "ቢያንስ አንድ አገልግሎት ይምረጡ።",
      "agreeTermsError": "ደንቦችን መቀበል ግዴታ ነው።"
    },
    "workspace": {
      "mainHome": "← LIFE.HELP ዋና ገጽ",
      "securitySessionBadge": "የ 3 ወር የደህንነት ክፍለ ጊዜ",
      "daysRemaining": "ቀናት ቀርተዋል",
      "signedDate": "የውል ቀን",
      "viewContract": "ኤሌክትሮኒክ ውል ይመልከቱ",
      "logout": "ውጣ",
      "availTitle": "የስራ ዝግጁነት አስተዳደር",
      "statusActive": "ዝግጁ (ለጥሪ ክፍት)",
      "statusPaused": "ለጊዜው የቆመ (እረፍት)",
      "descActive": "አዳዲስ ጥሪዎችን ለመቀበል ዝግጁ ነዎት። ሲያርፉ ወደ ማቆም ይቀይሩ።",
      "descPaused": "ጥሪዎችን መቀበል ለጊዜው ቆሟል። ሲዘጋጁ መልሰው ያብሩ።",
      "btnPause": "⏸ ዝግጁነትን አቁም",
      "btnResume": "🟢 ዝግጁነትን ቀጥል",
      "adminChat": "ከዋና አስተዳደር ጋር መገናኘት",
      "openAdminChat": "መልዕክቶችን ይመልከቱ",
      "adminChatTitle": "ከአስተዳዳሪ ጋር 1:1 ውይይት",
      "adminChatOnline": "በመስመር ላይ",
      "adminChatRecipient": "ተቀባይ: ባለሙያ",
      "adminChatEmpty": "ምንም መልዕክት የለም።",
      "adminChatEmptyHint": "ጥያቄዎችን እዚህ ይጻፉ፤ አስተዳዳሪው ወዲያውኑ ይመለከተዋል።",
      "adminChatPlaceholder": "መልዕክት ይጻፉ...",
      "adminChatSend": "ላክ",
      "calendarClose": "ዝጋ",
      "monthUnit": "ወር",
      "adminChatRecipientCounselor": "ተቀባይ: አማካሪ",
      "adminNoticeBanner": "[የዋና አስተዳደር ማስታወቂያ]",
      "unreadCount": "ያልተነበቡ",
      "preset24Hours": "24 ሰዓት ፈጣን ዝግጁነት",
      "presetDay": "ቀን (09:00 ~ 18:00)",
      "presetNight": "ማታ እና ድንገተኛ (18:00 ~ 09:00)",
      "presetMorning": "ጠዋት (09:00 ~ 13:00)",
      "presetAfternoon": "ከሰዓት (13:00 ~ 18:00)"
    }
  },
  "mn": {
    "tech": {
      "accessKeyLabel": "3 сарын тусгай нэвтрэх код",
      "loginWithAccessKey": "Аюулгүй байдлын кодоор нэвтрэх (90 хоног хүчинтэй)",
      "loginKeyNotice": "SMS-ээр ирсэн 3 сарын кодоо оруулан ажлын талбартаа нэвтэрнэ үү.",
      "lostCodeBtn": "Кодоо мартсан уу?",
      "reissueCodeTitle": "Утасны дугаараар код дахин авах",
      "getAccessKeyBtn": "3 сарын аюулгүй байдлын код авах",
      "registerAndStart": "Бүртгүүлж, үйлчилгээ эхлүүлэх",
      "selectServices": "Үйлчилгээний чиглэлээ сонгох",
      "selectServicesDesc": "Гүйцэтгэх боломжтой бүх чиглэлээ сонгоно уу.",
      "selectedCount": " сонгогдсон",
      "helperNameLabel": "Мэргэжилтний нэр",
      "agreeTerms": "LIFE.HELP-ийн журам болон аюулгүй байдлын дүрмийг зөвшөөрч байна.",
      "keySentNotice": "Нэвтрэх кодыг SMS-ээр амжилттай илгээлээ",
      "issuedAccessKey": "Олгогдсон 3 сарын нэвтрэх код",
      "copy": "Хуулах",
      "copied": "Хуулагдлаа!",
      "backToTechHome": "Нүүр хуудас руу буцах",
      "verifying": "Шалгаж байна...",
      "changePhoneBtn": "Дугаар солих",
      "enterAccessKeyError": "Аюулгүй байдлын кодоо оруулна уу.",
      "enterNameError": "Нэрээ оруулна уу.",
      "selectServiceError": "Дор хаяж нэг үйлчилгээ сонгоно уу.",
      "agreeTermsError": "Нөхцөлийг зөвшөөрөх шаардлагатай."
    },
    "workspace": {
      "mainHome": "← LIFE.HELP Нүүр хуудас",
      "securitySessionBadge": "3 сарын аюулгүй байдлын сесс",
      "daysRemaining": "хоног үлдсэн",
      "signedDate": "Гэрээний огноо",
      "viewContract": "Цахим гэрээ үзэх",
      "logout": "Гарах",
      "availTitle": "Бэлэн байдлын тохиргоо",
      "statusActive": "Идэвхтэй (Дуудлагад бэлэн)",
      "statusPaused": "Түр зогссон (Амарч буй)",
      "descActive": "Та шинэ дуудлага хүлээн авахад бэлэн байна. Амрах үедээ түр зогсооно уу.",
      "descPaused": "Дуудлага хүлээн авалт түр зогссон. Бэлэн болмогц дахин идэвхжүүлнэ үү.",
      "btnPause": "⏸ Түр зогсоох",
      "btnResume": "🟢 Идэвхжүүлэх",
      "adminChat": "Төв удирдлагатай холбогдох",
      "openAdminChat": "Зурвас харах",
      "adminChatTitle": "Админтай 1:1 онлайн чат",
      "adminChatOnline": "ОНЛАЙН",
      "adminChatRecipient": "Хүлээн авагч: Мэргэжилтэн",
      "adminChatEmpty": "Админаас ирсэн зурвас алга.",
      "adminChatEmptyHint": "Асуулт эсвэл яаралтай хүсэлтээ энд үлдээнэ үү.",
      "adminChatPlaceholder": "Зурвас бичих...",
      "adminChatSend": "Илгээх",
      "calendarClose": "Хаах",
      "monthUnit": "Сар",
      "adminChatRecipientCounselor": "Хүлээн авагч: Зөвлөх",
      "adminNoticeBanner": "[Төвийн Мэдэгдэл]",
      "unreadCount": "уншаагүй",
      "preset24Hours": "24 цагийн бэлэн байдал",
      "presetDay": "Өдрийн (09:00 ~ 18:00)",
      "presetNight": "Шөнийн ба яаралтай (18:00 ~ 09:00)",
      "presetMorning": "Өглөөний (09:00 ~ 13:00)",
      "presetAfternoon": "Үдээс хойшхи (13:00 ~ 18:00)"
    }
  },
  "ne": {
    "tech": {
      "accessKeyLabel": "३ महिनाको समर्पित पहुँच कुञ्जी",
      "loginWithAccessKey": "सुरक्षा कोडद्वारा लगइन (९० दिन मान्य)",
      "loginKeyNotice": "एसएमएसमा प्राप्त ३ महिनाको कोड प्रविष्ट गरी तुरुन्त कार्यक्षेत्रमा प्रवेश गर्नुहोस्।",
      "lostCodeBtn": "कोड हराउनुभयो?",
      "reissueCodeTitle": "मोबाइल नम्बरबाट कोड पुनः प्राप्त गर्नुहोस्",
      "getAccessKeyBtn": "३ महिनाको सुरक्षा कोड प्राप्त गर्नुहोस्",
      "registerAndStart": "दर्ता गरी सेवा सुरु गर्नुहोस्",
      "selectServices": "सेवा क्षेत्रहरू छान्नुहोस्",
      "selectServicesDesc": "तपाईंले गर्न सक्ने सबै सेवाहरू छान्नुहोस्।",
      "selectedCount": " छानिएको",
      "helperNameLabel": "सहयोगीको नाम",
      "agreeTerms": "म LIFE.HELP का नियम र सुरक्षा निर्देशनहरू स्वीकार गर्दछु।",
      "keySentNotice": "पहुँच कोड एसएमएसद्वारा पठाइयो",
      "issuedAccessKey": "जारी गरिएको ३ महिनाको कोड",
      "copy": "प्रतिलिपि",
      "copied": "प्रतिलिपि भयो!",
      "backToTechHome": "मुख्य पृष्ठमा फर्कनुहोस्",
      "verifying": "प्रमाणीकरण हुँदैछ...",
      "changePhoneBtn": "नम्बर परिवर्तन",
      "enterAccessKeyError": "कृपया सुरक्षा कोड प्रविष्ट गर्नुहोस्।",
      "enterNameError": "कृपया आफ्नो नाम लेख्नुहोस्।",
      "selectServiceError": "कम्तिमा एउटा सेवा क्षेत्र छान्नुहोस्।",
      "agreeTermsError": "सर्तहरू स्वीकार गर्न आवश्यक छ।"
    },
    "workspace": {
      "mainHome": "← LIFE.HELP गृहपृष्ठ",
      "securitySessionBadge": "३ महिनाको सुरक्षा सत्र",
      "daysRemaining": "दिन बाँकी",
      "signedDate": "सम्झौता मिति",
      "viewContract": "विद्युतीय सम्झौता हेर्नुहोस्",
      "logout": "लगआउट",
      "availTitle": "उपलब्धता व्यवस्थापन",
      "statusActive": "सक्रिय (सेवाका लागि उपलब्ध)",
      "statusPaused": "रोकिएको (विश्राम)",
      "descActive": "तपाईं नयाँ सेवा कलहरूका लागि उपलब्ध हुनुहुन्छ। आराम गर्दा रोक्नुहोस्।",
      "descPaused": "सेवा कलहरू अस्थायी रूपमा रोकिएका छन्। तयार भएपछि पुनः सक्रिय गर्नुहोस्।",
      "btnPause": "⏸ उपलब्धता रोक्नुहोस्",
      "btnResume": "🟢 पुनः सक्रिय गर्नुहोस्",
      "adminChat": "केन्द्रीय प्रशासकसँग सम्पर्क",
      "openAdminChat": "सन्देश हेर्नुहोस्",
      "adminChatTitle": "प्रशासकसँग १:१ अनलाइन च्याट",
      "adminChatOnline": "अनलाइन",
      "adminChatRecipient": "प्राप्तकर्ता: सहयोगी",
      "adminChatEmpty": "कुनै सन्देश छैन।",
      "adminChatEmptyHint": "आफ्ना प्रश्न वा आकस्मिक जानकारी यहाँ लेख्नुहोस्।",
      "adminChatPlaceholder": "सन्देश लेख्नुहोस्...",
      "adminChatSend": "पठाउनुहोस्",
      "calendarClose": "बन्द गर्नुहोस्",
      "monthUnit": "महिना",
      "adminChatRecipientCounselor": "प्राप्तकर्ता: परामर्शदाता",
      "adminNoticeBanner": "[केन्द्रीय सूचना]",
      "unreadCount": "नपढिएका",
      "preset24Hours": "२४ घण्टा द्रुत सेवा",
      "presetDay": "दिउँसो (०९:०० ~ १८:००)",
      "presetNight": "राती र आकस्मिक (१८:०० ~ ०९:००)",
      "presetMorning": "बिहान (०९:०० ~ १३:००)",
      "presetAfternoon": "अपराह्न (१३:०० ~ १८:००)"
    }
  },
  "my": {
    "tech": {
      "accessKeyLabel": "၃ လ သီးသန့် အသုံးပြုခွင့်ကုဒ်",
      "loginWithAccessKey": "လုံခြုံရေးကုဒ်ဖြင့် ဝင်ရောက်ရန် (ရက် ၉၀ သက်တမ်းရှိ)",
      "loginKeyNotice": "SMS ဖြင့်ရရှိသော ၃ လ သက်တမ်းရှိ ကုဒ်ကို ရိုက်ထည့်ပါ။",
      "lostCodeBtn": "ကုဒ် ပျောက်ဆုံးသွားပါသလား?",
      "reissueCodeTitle": "ဖုန်းနံပါတ်ဖြင့် ကုဒ်ပြန်လည်ထုတ်ယူရန်",
      "getAccessKeyBtn": "၃ လ လုံခြုံရေးကုဒ် ရယူရန်",
      "registerAndStart": "မှတ်ပုံတင်ပြီး ဝန်ဆောင်မှုစတင်ရန်",
      "selectServices": "ဝန်ဆောင်မှုနယ်ပယ် ရွေးချယ်ပါ",
      "selectServicesDesc": "သင်ဆောင်ရွက်နိုင်သော ဝန်ဆောင်မှုများကို ရွေးချယ်ပါ။",
      "selectedCount": " ခု ရွေးချယ်ထားသည်",
      "helperNameLabel": "ကျွမ်းကျင်သူ အမည်",
      "agreeTerms": "LIFE.HELP စည်းမျဉ်းများနှင့် လုံခြုံရေးစည်းကမ်းများကို သဘောတူပါသည်။",
      "keySentNotice": "ဝင်ရောက်ခွင့်ကုဒ်ကို SMS ဖြင့် ပို့ပြီးပါပြီ",
      "issuedAccessKey": "ထုတ်ပေးထားသော ၃ လ သက်တမ်းရှိကုဒ်",
      "copy": "ကူးယူရန်",
      "copied": "ကူးယူပြီးပါပြီ!",
      "backToTechHome": "ပင်မစာမျက်နှာသို့ ပြန်သွားရန်",
      "verifying": "အတည်ပြုနေသည်...",
      "changePhoneBtn": "နံပါတ်ပြောင်းရန်",
      "enterAccessKeyError": "လုံခြုံရေးကုဒ်ကို ရိုက်ထည့်ပါ။",
      "enterNameError": "သင့်အမည်ကို ရိုက်ထည့်ပါ။",
      "selectServiceError": "အနည်းဆုံး ဝန်ဆောင်မှုတစ်ခု ရွေးချယ်ပါ။",
      "agreeTermsError": "စည်းကမ်းချက်များကို သဘောတူရန် လိုအပ်ပါသည်။"
    },
    "workspace": {
      "mainHome": "← LIFE.HELP ပင်မစာမျက်နှာ",
      "securitySessionBadge": "၃ လ လုံခြုံရေးအပိုင်း",
      "daysRemaining": "ရက် ကျန်ရှိသည်",
      "signedDate": "စာချုပ်ချုပ်ဆိုသည့်ရက်စွဲ",
      "viewContract": "အီလက်ထရွန်းနစ်စာချုပ် ကြည့်ရှုရန်",
      "logout": "ထွက်ရန်",
      "availTitle": "အချိန်နှင့်တပြေးညီ လုပ်ဆောင်နိုင်မှု စီမံခန့်ခွဲခြင်း",
      "statusActive": "အဆင်သင့်ရှိသည် (အလုပ်လက်ခံနိုင်)",
      "statusPaused": "ခေတ္တရပ်နားထားသည် (နားချိန်)",
      "descActive": "ခေါ်ဆိုမှုများကို လက်ခံရန် အဆင်သင့်ရှိပါသည်။ နားချိန်တွင် ခေတ္တရပ်နားထားပါ။",
      "descPaused": "ခေါ်ဆိုမှုများကို ခေတ္တရပ်နားထားပါသည်။ အဆင်သင့်ဖြစ်ပါက ပြန်လည်ဖွင့်ပါ။",
      "btnPause": "⏸ ခေတ္တရပ်နားရန်",
      "btnResume": "🟢 ပြန်လည်စတင်ရန်",
      "adminChat": "ရုံးချုပ် စီမံခန့်ခွဲသူထံ ဆက်သွယ်ရန်",
      "openAdminChat": "မက်ဆေ့ခ်ျ ကြည့်ရန်",
      "adminChatTitle": "စီမံခန့်ခွဲသူနှင့် တိုက်ရိုက်စကားပြောဆိုခြင်း",
      "adminChatOnline": "လိုင်းပေါ်ရှိသည်",
      "adminChatRecipient": "လက်ခံသူ: ကျွမ်းကျင်သူ",
      "adminChatEmpty": "မက်ဆေ့ခ်ျ မရှိသေးပါ။",
      "adminChatEmptyHint": "မေးမြန်းစရာများ သို့မဟုတ် အရေးပေါ်အခြေအနေများကို ဤနေရာတွင် ရေးသားနိုင်ပါသည်။",
      "adminChatPlaceholder": "မက်ဆေ့ခ်ျ ရေးသားရန်...",
      "adminChatSend": "ပေးပို့ရန်",
      "calendarClose": "ပိတ်ရန်",
      "monthUnit": "လ",
      "adminChatRecipientCounselor": "လက်ခံသူ: အကြံပေး",
      "adminNoticeBanner": "[ရုံးချုပ် အသိပေးချက်]",
      "unreadCount": "မဖတ်ရသေးပါ",
      "preset24Hours": "၂၄ နာရီ အရေးပေါ်အသင့်ရှိမှု",
      "presetDay": "နေ့ပိုင်း (၀၉:၀၀ ~ ၁၈:၀၀)",
      "presetNight": "ညပိုင်းနှင့် အရေးပေါ် (၁၈:၀၀ ~ ၀၉:၀၀)",
      "presetMorning": "မနက်ပိုင်း (၀၉:၀၀ ~ ၁၃:၀၀)",
      "presetAfternoon": "နေ့လယ်ပိုင်း (၁၃:၀၀ ~ ၁၈:၀၀)"
    }
  },
  "km": {
    "tech": {
      "accessKeyLabel": "កូដចូលប្រើប្រាស់រយៈពេល ៣ ខែ",
      "loginWithAccessKey": "ចូលដោយប្រើកូដសុវត្ថិភាព (សុពលភាព ៩០ ថ្ងៃ)",
      "loginKeyNotice": "បញ្ចូលកូដសុវត្ថិភាពដែលទទួលបានតាម SMS ដើម្បីចូលទៅកាន់កន្លែងការងារភ្លាមៗ។",
      "lostCodeBtn": "បាត់កូដមែនទេ?",
      "reissueCodeTitle": "ស្នើសុំកូដឡើងវិញតាមលេខទូរស័ព្ទ",
      "getAccessKeyBtn": "ទទួលកូដសុវត្ថិភាព ៣ ខែ",
      "registerAndStart": "ចុះឈ្មោះ និងចាប់ផ្តើមសេវាកម្ម",
      "selectServices": "ជ្រើសរើសប្រភេទសេវាកម្ម",
      "selectServicesDesc": "ជ្រើសរើសជំនាញទាំងអស់ដែលអ្នកអាចធ្វើបាន។",
      "selectedCount": " បានជ្រើសរើស",
      "helperNameLabel": "ឈ្មោះអ្នកជំនាញ",
      "agreeTerms": "ខ្ញុំយល់ព្រមតាមលក្ខខណ្ឌ និងវិធានការសុវត្ថិភាពរបស់ LIFE.HELP។",
      "keySentNotice": "កូដត្រូវបានផ្ញើតាម SMS ដោយជោគជ័យ",
      "issuedAccessKey": "កូដចូលប្រើប្រាស់ ៣ ខែដែលបានចេញ",
      "copy": "ចម្លង",
      "copied": "បានចម្លង!",
      "backToTechHome": "ត្រឡប់ទៅទំព័រដើម",
      "verifying": "កំពុងផ្ទៀងផ្ទាត់...",
      "changePhoneBtn": "ប្តូរលេខទូរស័ព្ទ",
      "enterAccessKeyError": "សូមបញ្ចូលកូដសុវត្ថិភាព។",
      "enterNameError": "សូមបញ្ចូលឈ្មោះរបស់អ្នក។",
      "selectServiceError": "សូមជ្រើសរើសយ៉ាងហោចណាស់សេវាកម្មមួយ។",
      "agreeTermsError": "តម្រូវឱ្យយល់ព្រមតាមលក្ខខណ្ឌ។"
    },
    "workspace": {
      "mainHome": "← ទំព័រដើម LIFE.HELP",
      "securitySessionBadge": "សម័យសុវត្ថិភាព ៣ ខែ",
      "daysRemaining": "ថ្ងៃនៅសល់",
      "signedDate": "កាលបរិច្ឆេទកិច្ចសន្យា",
      "viewContract": "មើលកិច្ចសន្យាអេឡិចត្រូនិក",
      "logout": "ចាកចេញ",
      "availTitle": "ការគ្រប់គ្រងភាពអាចរកបានភ្លាមៗ",
      "statusActive": "សកម្ម (ត្រៀមខ្លួនទទួលការហៅ)",
      "statusPaused": "ផ្អាកបណ្តោះអាសន្ន (សម្រាក)",
      "descActive": "អ្នករួចរាល់ដើម្បីទទួលការហៅថ្មី។ សូមផ្អាកនៅពេលសម្រាក។",
      "descPaused": "ការហៅត្រូវបានផ្អាកបណ្តោះអាសន្ន។ បើកឡើងវិញនៅពេលរួចរាល់។",
      "btnPause": "⏸ ផ្អាកភាពអាចរកបាន",
      "btnResume": "🟢 បន្តសកម្មភាពឡើងវិញ",
      "adminChat": "ទាក់ទងរដ្ឋបាលកណ្តាល",
      "openAdminChat": "មើលសារ និងឆ្លើយតប",
      "adminChatTitle": "ជជែកផ្ទាល់ ១:១ ជាមួយរដ្ឋបាល",
      "adminChatOnline": "អនឡាញ",
      "adminChatRecipient": "អ្នកទទួល: អ្នកជំនាញ",
      "adminChatEmpty": "មិនមានសារពីការិយាល័យកណ្តាលទេ។",
      "adminChatEmptyHint": "ទុកសំណួរ ឬរបាយការណ៍បន្ទាន់នៅទីនេះ រដ្ឋបាលនឹងពិនិត្យភ្លាមៗ។",
      "adminChatPlaceholder": "វាយបញ្ចូលសារទៅរដ្ឋបាល...",
      "adminChatSend": "ផ្ញើ",
      "calendarClose": "បិទ",
      "monthUnit": "ខែ",
      "adminChatRecipientCounselor": "អ្នកទទួល: ទីប្រឹក្សា",
      "adminNoticeBanner": "[សេចក្តីជូនដំណឹងពីរដ្ឋបាល]",
      "unreadCount": "មិនទាន់អាន",
      "preset24Hours": "ត្រៀមខ្លួនបន្ទាន់ ២៤ ម៉ោង",
      "presetDay": "ពេលថ្ងៃ (០៩:០០ ~ ១៨:០០)",
      "presetNight": "ពេលយប់ និងបន្ទាន់ (១៨:០០ ~ ០៩:០០)",
      "presetMorning": "ពេលព្រឹក (០៩:០០ ~ ១៣:០០)",
      "presetAfternoon": "ពេលរសៀល (១៣:០០ ~ ១៨:០០)"
    }
  },
  "ta": {
    "tech": {
      "accessKeyLabel": "3 மாத பிரத்யேக அணுகல் குறியீடு",
      "loginWithAccessKey": "பாதுகாப்புக் குறியீட்டுடன் உள்நுழைக (90 நாட்கள் செல்லுபடியாகும்)",
      "loginKeyNotice": "SMS மூலம் பெறப்பட்ட 3 மாத அணுகல் குறியீட்டை உள்ளிடவும்.",
      "lostCodeBtn": "குறியீட்டை மறந்துவிட்டீர்களா?",
      "reissueCodeTitle": "மொபைல் எண் மூலம் குறியீட்டை மீண்டும் பெறுக",
      "getAccessKeyBtn": "3 மாத பாதுகாப்புக் குறியீட்டைப் பெறுக",
      "registerAndStart": "பதிவு செய்து பணியைத் தொடங்குங்கள்",
      "selectServices": "சேவைத் துறைகளைத் தேர்ந்தெடுக்கவும்",
      "selectServicesDesc": "நீங்கள் செய்யக்கூடிய அனைத்து சேவைகளையும் தேர்ந்தெடுக்கவும்.",
      "selectedCount": " தேர்ந்தெடுக்கப்பட்டது",
      "helperNameLabel": "பணியாளரின் பெயர்",
      "agreeTerms": "LIFE.HELP விதிமுறைகள் மற்றும் பாதுகாப்பு வழிகாட்டுதல்களை ஏற்கிறேன்.",
      "keySentNotice": "அணுகல் குறியீடு SMS மூலம் அனுப்பப்பட்டது",
      "issuedAccessKey": "வழங்கப்பட்ட 3 மாத அணுகல் குறியீடு",
      "copy": "நகலெடு",
      "copied": "நகலெடுக்கப்பட்டது!",
      "backToTechHome": "முகப்புப் பக்கத்திற்குத் திரும்பு",
      "verifying": "சரிபார்க்கிறது...",
      "changePhoneBtn": "எண்ணை மாற்றுக",
      "enterAccessKeyError": "பாதுகாப்புக் குறியீட்டை உள்ளிடவும்.",
      "enterNameError": "உங்கள் பெயரை உள்ளிடவும்.",
      "selectServiceError": "குறைந்தது ஒரு சேவையைத் தேர்ந்தெடுக்கவும்.",
      "agreeTermsError": "விதிமுறைகளை ஏற்றுக்கொள்வது அவசியம்."
    },
    "workspace": {
      "mainHome": "← LIFE.HELP முதன்மைப் பக்கம்",
      "securitySessionBadge": "3 மாத பாதுகாப்பு அமர்வு",
      "daysRemaining": "நாட்கள் மீதமுள்ளன",
      "signedDate": "ஒப்பந்தத் தேதி",
      "viewContract": "மின்னணு ஒப்பந்தத்தைப் பார்க்கவும்",
      "logout": "வெளியேறு",
      "availTitle": "நிகழ்நேரக் கிடைக்கும் தன்மை மேலாண்மை",
      "statusActive": "செயலில் (பணிக்குத் தயார்)",
      "statusPaused": "இடைநிறுத்தப்பட்டது (ஓய்வு)",
      "descActive": "புதிய அழைப்புகளைப் பெறத் தயார். ஓய்வு எடுக்கும் போது இடைநிறுத்தவும்.",
      "descPaused": "அழைப்புகள் தற்காலிகமாக நிறுத்தப்பட்டுள்ளன. தயாரானதும் இயக்கவும்.",
      "btnPause": "⏸ இடைநிறுத்து",
      "btnResume": "🟢 மீண்டும் தொடங்கு",
      "adminChat": "தலைமையக நிர்வாகத் தொடர்பு",
      "openAdminChat": "செய்திகளைப் பார்க்கவும்",
      "adminChatTitle": "நிர்வாகத்துடன் 1:1 நேரடி அரட்டை",
      "adminChatOnline": "ஆன்லைன்",
      "adminChatRecipient": "பெறுநர்: பணியாளர்",
      "adminChatEmpty": "செய்திகள் எதுவும் இல்லை.",
      "adminChatEmptyHint": "உங்கள் கேள்விகளை இங்கே தெரிவிக்கலாம்; நிர்வாகம் விரைவில் பதிலளிக்கும்.",
      "adminChatPlaceholder": "செய்தியை உள்ளிடவும்...",
      "adminChatSend": "அனுப்பு",
      "calendarClose": "மூடு",
      "monthUnit": "மாதம்",
      "adminChatRecipientCounselor": "பெறுநர்: ஆலோசகர்",
      "adminNoticeBanner": "[தலைமையக அறிவிப்பு]",
      "unreadCount": "படிக்காதவை",
      "preset24Hours": "24 மணி நேர உடனடி சேவை",
      "presetDay": "பகல் (09:00 ~ 18:00)",
      "presetNight": "இரவு & அவசரம் (18:00 ~ 09:00)",
      "presetMorning": "காலை (09:00 ~ 13:00)",
      "presetAfternoon": "மதியம் (13:00 ~ 18:00)"
    }
  },
  "si": {
    "tech": {
      "accessKeyLabel": "මාස 3 ක ප්‍රවේශ කේතය",
      "loginWithAccessKey": "ආරක්ෂක කේතයෙන් පිවිසෙන්න (දින 90 ක් වලංගුයි)",
      "loginKeyNotice": "SMS මගින් ලැබුණු මාස 3 ක කේතය ඇතුළත් කරන්න.",
      "lostCodeBtn": "කේතය අමතක වුනාද?",
      "reissueCodeTitle": "දුරකථන අංකයෙන් කේතය නැවත ලබා ගන්න",
      "getAccessKeyBtn": "මාස 3 ක ආරක්ෂක කේතය ලබා ගන්න",
      "registerAndStart": "ලියාපදිංචි වී සේවාව අරඹන්න",
      "selectServices": "සේවා ක්ෂේත්‍ර තෝරන්න",
      "selectServicesDesc": "ඔබට කළ හැකි සියලු සේවා තෝරන්න.",
      "selectedCount": " ක් තෝරාගෙන ඇත",
      "helperNameLabel": "කාර්මික ශිල්පියාගේ නම",
      "agreeTerms": "LIFE.HELP නීති සහ ආරක්ෂක උපදෙස් වලට එකඟ වෙමි.",
      "keySentNotice": "ප්‍රවේශ කේතය SMS මගින් එවන ලදී",
      "issuedAccessKey": "නිකුත් කළ මාස 3 ක ප්‍රවේශ කේතය",
      "copy": "පිටපත් කරන්න",
      "copied": "පිටපත් විය!",
      "backToTechHome": "ප්‍රධාන පිටුවට",
      "verifying": "තහවුරු කරමින්...",
      "changePhoneBtn": "අංකය වෙනස් කරන්න",
      "enterAccessKeyError": "ආරක්ෂක කේතය ඇතුළත් කරන්න.",
      "enterNameError": "ඔබේ නම ඇතුළත් කරන්න.",
      "selectServiceError": "අවම වශයෙන් එක් සේවාවක් තෝරන්න.",
      "agreeTermsError": "කොන්දේසි වලට එකඟ විය යුතුය."
    },
    "workspace": {
      "mainHome": "← LIFE.HELP ප්‍රධාන පිටුව",
      "securitySessionBadge": "මාස 3 ක ආරක්ෂක සැසිය",
      "daysRemaining": "දින ඉතිරිව ඇත",
      "signedDate": "ගිවිසුම් දිනය",
      "viewContract": "විද්‍යුත් ගිවිසුම බලන්න",
      "logout": "පිටවන්න",
      "availTitle": "තථ්‍ය කාලීන සේවා සූදානම",
      "statusActive": "ක්‍රියාකාරී (සේවාවට සූදානම්)",
      "statusPaused": "තාවකාලිකව නවතා ඇත (විවේකය)",
      "descActive": "නව ඇමතුම් ලබා ගැනීමට සූදානම්. විවේක ගන්නා විට නවත්වන්න.",
      "descPaused": "ඇමතුම් තාවකාලිකව නවතා ඇත. සූදානම් වූ පසු නැවත ක්‍රියාත්මක කරන්න.",
      "btnPause": "⏸ තාවකාලිකව නවත්වන්න",
      "btnResume": "🟢 නැවත ක්‍රියාත්මක කරන්න",
      "adminChat": "ප්‍රධාන කාර්යාලය හා සම්බන්ධ වන්න",
      "openAdminChat": "පණිවිඩ බලන්න",
      "adminChatTitle": "පරිපාලක සමඟ 1:1 සජීවී කතාබස්",
      "adminChatOnline": "සක්‍රීයයි",
      "adminChatRecipient": "ලබන්නා: කාර්මික ශිල්පී",
      "adminChatEmpty": "පණිවිඩ නැත.",
      "adminChatEmptyHint": "ගැටළු මෙහි සටහන් කරන්න; පරිපාලක ඉක්මනින් පිළිතුරු දෙනු ඇත.",
      "adminChatPlaceholder": "පණිවිඩය ටයිප් කරන්න...",
      "adminChatSend": "යවන්න",
      "calendarClose": "වසන්න",
      "monthUnit": "මාසය",
      "adminChatRecipientCounselor": "ලබන්නා: උපදේශක",
      "adminNoticeBanner": "[ප්‍රධාන කාර්යාලයේ නිවේදනය]",
      "unreadCount": "නොකියවූ",
      "preset24Hours": "පැය 24 ක්ෂණික සේවය",
      "presetDay": "දවල් (09:00 ~ 18:00)",
      "presetNight": "රාත්‍රී සහ හදිසි (18:00 ~ 09:00)",
      "presetMorning": "උදෑසන (09:00 ~ 13:00)",
      "presetAfternoon": "සවස (13:00 ~ 18:00)"
    }
  },
  "tet": {
    "tech": {
      "accessKeyLabel": "Xave Asesu Espesiál ba Fulan 3",
      "loginWithAccessKey": "Tama ho Kódigu Seguransa (Validu loron 90)",
      "loginKeyNotice": "Hatama kódigu asesu ne'ebé simu liuhosi SMS atu tama kedas ba espasu servisu.",
      "lostCodeBtn": "Lakon kódigu?",
      "reissueCodeTitle": "Husu fali kódigu liuhosi númeru telemóvel",
      "getAccessKeyBtn": "Hetan Kódigu Seguransa Fulan 3",
      "registerAndStart": "Rejistu & Hahú Servisu",
      "selectServices": "Hili Kategoria Servisu nian",
      "selectServicesDesc": "Hili área hotu ne'ebé ita bele halo.",
      "selectedCount": " hili ona",
      "helperNameLabel": "Naran Tékniku (Apelidu ka naran loloos)",
      "agreeTerms": "Ha'u simu regra no matadalan seguransa LIFE.HELP nian.",
      "keySentNotice": "Kódigu asesu haruka ona liuhosi SMS",
      "issuedAccessKey": "Kódigu asesu fulan 3 ne'ebé fó sai",
      "copy": "Kopia",
      "copied": "Kopia ona!",
      "backToTechHome": "Fila ba Pájina Inisiál",
      "verifying": "Verifika daudaun...",
      "changePhoneBtn": "Troka Númeru",
      "enterAccessKeyError": "Favór hatama kódigu seguransa.",
      "enterNameError": "Favór hatama ita-boot nia naran.",
      "selectServiceError": "Hili pelumenus kategoria servisu ida.",
      "agreeTermsError": "Tenke simu termu no kondisaun sira."
    },
    "workspace": {
      "mainHome": "← Pájina Prinsipál LIFE.HELP",
      "securitySessionBadge": "Sesaun Seguransa Fulan 3",
      "daysRemaining": "loron restu",
      "signedDate": "Data Kontratu",
      "viewContract": "Haree Kontratu Eletróniku",
      "logout": "Sai",
      "availTitle": "Jestaun Disponibilidade Tempu Real",
      "statusActive": "Ativu (Prontu ba servisu)",
      "statusPaused": "Pausa (Deskansa)",
      "descActive": "Ita prontu atu simu xamada foun. Troka ba pausa bainhira deskansa.",
      "descPaused": "Xamada sira pausa provizóriu. Ativa fali bainhira prontu atu servisu.",
      "btnPause": "⏸ Pausa Disponibilidade",
      "btnResume": "🟢 Kontinua Ativu",
      "adminChat": "Kontaktu Administrasaun Sentrál",
      "openAdminChat": "Haree Mensajen sira",
      "adminChatTitle": "Xat 1:1 ho Administrasaun Sentrál",
      "adminChatOnline": "ON-LINE",
      "adminChatRecipient": "Simu-na'in: Tékniku",
      "adminChatEmpty": "Laiha mensajen ho administrasaun.",
      "adminChatEmptyHint": "Husik pergunta ka kazu emerjénsia iha ne'e; administrasaun sei haree.",
      "adminChatPlaceholder": "Hakerek mensajen ba administrasaun...",
      "adminChatSend": "Haruka",
      "calendarClose": "Taka",
      "monthUnit": "Fulan",
      "adminChatRecipientCounselor": "Simu-na'in: Konsulente",
      "adminNoticeBanner": "[Avizu husi Sentrál]",
      "unreadCount": "seidauk lee",
      "preset24Hours": "Prontu 24 oras ba emerjénsia",
      "presetDay": "Loron (09:00 ~ 18:00)",
      "presetNight": "Kalan & Emerjénsia (18:00 ~ 09:00)",
      "presetMorning": "Dader (09:00 ~ 13:00)",
      "presetAfternoon": "Lokraik (13:00 ~ 18:00)"
    }
  }
}
