# scripts/dict_asian.py
# Complete Asian languages tech and workspace dictionary:
# zh-Hant, id, th, hi, ne, bn, ta, si, km, my, mn, kk, uz, tet

ASIAN_TECH_WS = {
  "zh-Hant": {
    "tech": {
      "headlineLead": "直接與您附近的客戶快速對接",
      "actAsHelper": "專業師傅",
      "securitySessionNotice": "3個月安全會話：透過手機號碼發行90天隨機安全訪問金鑰",
      "securitySessionExpiry": "安全會話到期日",
      "securitySessionExpired": "安全會話已到期",
      "autoMaintainedDays": "天自動維持有效",
      "operatingRegions": "服務營運區域",
      "instantDispatchConnected": "即時客戶呼叫對接",
      "registeredServices": "已註冊服務項目",
      "categoriesRegisteredCount": "個服務項目已註冊",
      "editableInWorkspace": "可在師傅工作台即時調整",
      "openWorkspaceBtn": "管理我的師傅工作台",
      "statusActiveShort": "可立即出動",
      "statusPausedShort": "暫停接單中",
      "clickToToggle": "點擊切換狀態",
      "hotlineNotice": "總部主要調度支援專線",
      "helperPortal": "師傅專區入口",
      "registerTab": "新師傅註冊申請",
      "loginTab": "已註冊師傅登入",
      "newHelperRegTitle": "新師傅註冊（3個月安全訪問）",
      "existingHelperLoginTitle": "已註冊師傅登入",
      "newHelperRegDesc": "無需輸入身分證字號，僅憑手機號碼即可自由開展3個月的服務活動。",
      "existingHelperLoginDesc": "輸入您獲取的3個月專用安全碼即可直接登入，無需額外驗證。",
      "accessKeyLabel": "3個月專用安全碼 (Access Key)",
      "loginWithAccessKey": "使用3個月安全碼登入（90天維持）",
      "loginKeyNotice": "輸入簡訊收到的3個月專用安全碼，即可立即進入師傅工作台。",
      "lostCodeBtn": "遺失安全碼了嗎？",
      "reissueCodeTitle": "透過手機號碼重新發行3個月代碼",
      "getAccessKeyBtn": "取得3個月安全訪問碼",
      "registerAndStart": "以3個月安全碼註冊並開始接單",
      "selectServices": "選擇可提供服務的項目",
      "selectServicesDesc": "請點選所有您可以出動解決的領域（後續可在工作台中調整）。",
      "selectedCount": " 個已選擇",
      "helperNameLabel": "師傅姓名（暱稱或真實姓名）",
      "agreeTerms": "我已確認 LIFE.HELP 師傅活動規範與安全準則，並承諾提供迅速且親切的客戶服務。（不收集身分證字號）",
      "keySentNotice": "簡訊發送完成",
      "issuedAccessKey": "發行的3個月安全訪問碼 (Access Key)",
      "copy": "複製",
      "copied": "已複製！",
      "backToTechHome": "返回師傅介紹首頁",
      "verifying": "正在驗證登入...",
      "changePhoneBtn": "更換號碼",
      "enterAccessKeyError": "請輸入3個月專用安全碼。",
      "enterNameError": "請輸入師傅姓名或暱稱。",
      "selectServiceError": "請至少選擇一個可服務的項目領域。",
      "agreeTermsError": "請同意師傅活動規範及安全守則。"
    },
    "workspace": {
      "title": "師傅工作台",
      "mainHome": "← LIFE.HELP 首頁",
      "helperHonorific": "師傅",
      "verifiedHelper": "認證師傅",
      "securitySessionBadge": "3個月安全會話",
      "daysRemaining": "天剩餘",
      "signedDate": "簽約日期",
      "viewContract": "查看電子合約書",
      "logout": "登出",
      "availTitle": "即時出動狀態管理",
      "statusActive": "可立即出動（接單中）",
      "statusPaused": "暫時休息（暫停接單）",
      "descActive": "客戶呼叫時可立即為您安排對接與派單。若有個人事務或休息時，請隨時切換為暫停狀態。",
      "descPaused": "目前派單服務已暫停。當您準備好再次工作時，請重新切換為出動中。",
      "btnPause": "⏸ 暫停接單",
      "btnResume": "🟢 恢復出動狀態",
      "activeTitle": "可立即出動（接單中）",
      "activeDesc": "客戶呼叫時可立即為您安排對接與派單。若有個人事務或休息時，請隨時切換為暫停狀態。",
      "pausedTitle": "暫時休息（暫停接單）",
      "pausedDesc": "目前派單服務已暫停。當您準備好再次工作時，請重新切換為出動中。",
      "resumeBtn": "🟢 恢復出動狀態",
      "pauseBtn": "⏸ 暫停接單",
      "hotlineTitle": "調度系統主要變動通報熱線",
      "hotlineDesc": "若 App 無法連線或發生緊急變動（無法出動、移動區域、事故等），請立即撥打以下電話。",
      "team1": "主要系統 1組（緊急專線）",
      "team2": "主要系統 2組（一般專線）",
      "call": "通話",
      "sms": "簡訊",
      "servicesTitle": "服務項目領域即時變更",
      "servicesDesc": "點擊即可剔除無法服務的項目，或點擊即時新增具備資格的全新服務領域。",
      "categoriesActive": "個領域啟用中",
      "serviceActive": "可出動",
      "serviceDisabled": "已停用",
      "regionsTitle": "出動責任區域管理",
      "regionsDesc": "點擊 ✕ 即可剔除無法前往的區域，並可自由新增可前往的周邊區域。",
      "regionsCount": "個區域已設定",
      "addRegionBtn": "新增出動區域",
      "removeRegionTitle": "移除區域",
      "scheduleTitle": "出動時間表",
      "setHours": "已設定時段",
      "hours24": "24小時全年無休即時出動",
      "contractTitle": "LIFE.HELP 委託合作電子合約書副本",
      "contractName": "姓名",
      "contractPhone": "手機號碼",
      "contractResidentId": "身分證字號（已遮罩）",
      "contractSignedAt": "合約簽訂時間",
      "contractClauseTitle": "承諾義務與狀況通報條款",
      "contractClauseDesc": "師傅承諾若遇暫時無法工作、服務領域或區域變動，將立即透過系統通報。",
      "contractSignature": "電子簽名確認",
      "close": "關閉",
      "minServiceAlert": "必須至少保留一個可服務項目領域。",
      "serviceRemoved": "該服務領域已成功排除。",
      "serviceAdded": "已即時新增全新服務領域。",
      "regionAdded": "區域已新增至出動責任範圍。",
      "minRegionAlert": "至少需設定一個活動區域。",
      "regionRemoved": "已自出動範圍中排除該區域。",
      "minDayAlert": "至少需選擇一天活動日。",
      "daysUpdated": "出動星期設定已更新。",
      "logoutConfirm": "您確定要登出師傅工作台嗎？",
      "adminChat": "聯繫總部管理員",
      "openAdminChat": "查看訊息與回覆",
      "adminChatTitle": "總部管理員 1:1 線上專線",
      "adminChatOnline": "在線",
      "adminChatRecipient": "收件人：師傅",
      "adminChatEmpty": "尚無與總部管理員溝通的訊息記錄。",
      "adminChatEmptyHint": "若有諮詢或緊急狀況請留言，管理員將儘快為您確認。",
      "adminChatPlaceholder": "輸入要向管理員傳達的訊息...",
      "adminChatSend": "傳送",
      "calendarClose": "關閉",
      "monthUnit": "月",
      "adminChatRecipientCounselor": "收件人：諮詢專員",
      "adminNoticeBanner": "[總部管理員公告]",
      "unreadCount": "則未讀",
      "preset24Hours": "24小時即時出動",
      "presetDay": "日間 (09:00 ~ 18:00)",
      "presetNight": "夜間與緊急 (18:00 ~ 隔日 09:00)",
      "presetMorning": "上午 (09:00 ~ 13:00)",
      "presetAfternoon": "下午 (13:00 ~ 18:00)"
    }
  },
  "id": {
    "tech": {
      "headlineLead": "Terhubung langsung dengan pelanggan di sekitar Anda",
      "actAsHelper": "teknisi profesional",
      "securitySessionNotice": "Sesi Keamanan 3 Bulan: kunci akses acak 90 hari diterbitkan via ponsel",
      "securitySessionExpiry": "Masa Kedaluwarsa Sesi Keamanan",
      "securitySessionExpired": "Sesi Keamanan Kedaluwarsa",
      "autoMaintainedDays": "hari dipertahankan otomatis",
      "operatingRegions": "Wilayah Layanan",
      "instantDispatchConnected": "Koneksi Langsung Pelanggan",
      "registeredServices": "Layanan Terdaftar",
      "categoriesRegisteredCount": "kategori terdaftar",
      "editableInWorkspace": "Dapat diubah di panel teknisi",
      "openWorkspaceBtn": "Kelola Panel Teknisi Saya",
      "statusActiveShort": "Siap Melayani",
      "statusPausedShort": "Dijeda Sementara",
      "clickToToggle": "Klik untuk beralih",
      "hotlineNotice": "Saluran Siaga Utama Sistem",
      "helperPortal": "Portal Teknisi",
      "registerTab": "Pendaftaran Teknisi Baru",
      "loginTab": "Masuk Teknisi Terdaftar",
      "newHelperRegTitle": "Pendaftaran Teknisi Baru (Akses Aman 3 Bulan)",
      "existingHelperLoginTitle": "Masuk Teknisi Terdaftar",
      "newHelperRegDesc": "Tanpa NIK/KTP. Bekerja bebas selama 3 bulan hanya dengan nomor ponsel.",
      "existingHelperLoginDesc": "Masukkan kode keamanan 3 bulan Anda untuk langsung masuk.",
      "accessKeyLabel": "Kode Akses Khusus 3 Bulan",
      "loginWithAccessKey": "Masuk dengan Kode Keamanan (Berlaku 90 hari)",
      "loginKeyNotice": "Masukkan kode 3 bulan yang diterima via SMS untuk langsung masuk ke panel.",
      "lostCodeBtn": "Lupa kode akses?",
      "reissueCodeTitle": "Terbitkan ulang kode melalui nomor ponsel",
      "getAccessKeyBtn": "Dapatkan Kode Keamanan 3 Bulan",
      "registerAndStart": "Daftar & Mulai dengan Kode 3 Bulan",
      "selectServices": "Pilih Kategori Layanan",
      "selectServicesDesc": "Pilih semua kategori keahlian Anda (dapat diubah nanti).",
      "selectedCount": " dipilih",
      "helperNameLabel": "Nama Teknisi (Nama panggilan atau asli)",
      "agreeTerms": "Saya menyetujui ketentuan kerja dan standar keselamatan LIFE.HELP.",
      "keySentNotice": "Kode akses berhasil dikirim via SMS",
      "issuedAccessKey": "Kode Akses 3 Bulan yang Diterbitkan",
      "copy": "Salin",
      "copied": "Tersalin!",
      "backToTechHome": "Kembali ke Beranda Teknisi",
      "verifying": "Memverifikasi...",
      "changePhoneBtn": "Ganti Nomor",
      "enterAccessKeyError": "Silakan masukkan kode akses 3 bulan.",
      "enterNameError": "Silakan masukkan nama teknisi.",
      "selectServiceError": "Pilih minimal satu kategori layanan.",
      "agreeTermsError": "Harap menyetujui aturan dan ketentuan keselamatan."
    },
    "workspace": {
      "title": "Panel Kerja Teknisi",
      "mainHome": "← Beranda LIFE.HELP",
      "helperHonorific": "Teknisi",
      "verifiedHelper": "Teknisi Terverifikasi",
      "securitySessionBadge": "Sesi Keamanan 3 Bulan",
      "daysRemaining": "hari tersisa",
      "signedDate": "Tanggal Kontrak",
      "viewContract": "Lihat Kontrak Elektronik",
      "logout": "Keluar",
      "availTitle": "Kelola Ketersediaan Real-Time",
      "statusActive": "Aktif (Siap Melayani)",
      "statusPaused": "Dijeda (Istirahat)",
      "descActive": "Anda siap menerima panggilan baru. Ubah ke jeda saat istirahat.",
      "descPaused": "Panggilan ditunda sementara. Aktifkan kembali saat siap bekerja.",
      "btnPause": "⏸ Jeda Ketersediaan",
      "btnResume": "🟢 Lanjutkan Aktif",
      "activeTitle": "Aktif (Siap Melayani)",
      "activeDesc": "Anda siap menerima panggilan baru. Ubah ke jeda saat istirahat.",
      "pausedTitle": "Dijeda (Istirahat)",
      "pausedDesc": "Panggilan ditunda sementara. Aktifkan kembali saat siap bekerja.",
      "resumeBtn": "🟢 Lanjutkan Aktif",
      "pauseBtn": "⏸ Jeda Ketersediaan",
      "hotlineTitle": "Saluran Siaga Utama Dispatch",
      "hotlineDesc": "Jika akses aplikasi bermasalah atau ada keadaan darurat, hubungi kami.",
      "team1": "Hotline Tim 1 (Darurat)",
      "team2": "Hotline Tim 2 (Standar)",
      "call": "Panggil",
      "sms": "SMS",
      "servicesTitle": "Manajemen Kategori Layanan",
      "servicesDesc": "Klik untuk menghapus atau menambah kategori secara real-time.",
      "categoriesActive": "Kategori Aktif",
      "serviceActive": "Aktif",
      "serviceDisabled": "Nonaktif",
      "regionsTitle": "Wilayah Operasional Layanan",
      "regionsDesc": "Klik ✕ untuk menghapus wilayah atau tambahkan area baru.",
      "regionsCount": "Wilayah Dikonfigurasi",
      "addRegionBtn": "Tambah Wilayah Layanan",
      "removeRegionTitle": "Hapus Wilayah",
      "scheduleTitle": "Jadwal Ketersediaan",
      "setHours": "Jam yang Ditentukan",
      "hours24": "Siap melayani 24 jam nonstop",
      "contractTitle": "Salinan Kontrak Elektronik LIFE.HELP",
      "contractName": "Nama Lengkap",
      "contractPhone": "Nomor Ponsel",
      "contractResidentId": "Nomor ID (Disamarkan)",
      "contractSignedAt": "Waktu Penandatanganan",
      "contractClauseTitle": "Klausul Komitmen dan Notifikasi Perubahan",
      "contractClauseDesc": "Teknisi berkewajiban segera memberitahu jika berhalangan atau berpindah area.",
      "contractSignature": "Tanda Tangan Elektronik Terverifikasi",
      "close": "Tutup",
      "minServiceAlert": "Minimal satu kategori layanan harus aktif.",
      "serviceRemoved": "Kategori layanan telah dihapus.",
      "serviceAdded": "Kategori layanan baru berhasil ditambahkan.",
      "regionAdded": "Wilayah berhasil ditambahkan.",
      "minRegionAlert": "Minimal satu wilayah harus dipilih.",
      "regionRemoved": "Wilayah telah dihapus.",
      "minDayAlert": "Pilih minimal satu hari kerja.",
      "daysUpdated": "Jadwal hari kerja diperbarui.",
      "logoutConfirm": "Apakah Anda yakin ingin keluar dari panel kerja?",
      "adminChat": "Kontak Admin Pusat",
      "openAdminChat": "Pesan dari Admin",
      "adminChatTitle": "Obrolan 1:1 dengan Admin Pusat",
      "adminChatOnline": "ONLINE",
      "adminChatRecipient": "Penerima: Teknisi",
      "adminChatEmpty": "Belum ada pesan dengan admin pusat.",
      "adminChatEmptyHint": "Tinggalkan pertanyaan atau laporan darurat; admin akan segera meninjaunya.",
      "adminChatPlaceholder": "Ketik pesan untuk admin...",
      "adminChatSend": "Kirim",
      "calendarClose": "Tutup",
      "monthUnit": "Bulan",
      "adminChatRecipientCounselor": "Penerima: Konselor",
      "adminNoticeBanner": "[Pengumuman Admin Pusat]",
      "unreadCount": "belum dibaca",
      "preset24Hours": "Siaga darurat 24 jam",
      "presetDay": "Siang (09:00 ~ 18:00)",
      "presetNight": "Malam & Darurat (18:00 ~ 09:00)",
      "presetMorning": "Pagi (09:00 ~ 13:00)",
      "presetAfternoon": "Sore (13:00 ~ 18:00)"
    }
  },
  "th": {
    "tech": {
      "headlineLead": "เชื่อมต่อกับลูกค้าในพื้นที่ของคุณโดยตรง",
      "actAsHelper": "ช่างผู้เชี่ยวชาญ",
      "securitySessionNotice": "เซสชันความปลอดภัย 3 เดือน: รหัสสุ่ม 90 วันผ่านเบอร์มือถือ",
      "securitySessionExpiry": "วันหมดอายุเซสชันความปลอดภัย",
      "securitySessionExpired": "เซสชันความปลอดภัยหมดอายุแล้ว",
      "autoMaintainedDays": "วันคงสถานะอัตโนมัติ",
      "operatingRegions": "พื้นที่ให้บริการ",
      "instantDispatchConnected": "เชื่อมต่อลูกค้าทันที",
      "registeredServices": "บริการที่ลงทะเบียน",
      "categoriesRegisteredCount": "หมวดหมู่ที่ลงทะเบียน",
      "editableInWorkspace": "แก้ไขได้ในพื้นที่ทำงาน",
      "openWorkspaceBtn": "จัดการพื้นที่ทำงานของฉัน",
      "statusActiveShort": "พร้อมให้บริการ",
      "statusPausedShort": "หยุดรับงานชั่วคราว",
      "clickToToggle": "คลิกเพื่อสลับสถานะ",
      "hotlineNotice": "สายด่วนสนับสนุนหลักของระบบ"
    },
    "workspace": {
      "title": "พื้นที่ทำงานของช่าง",
      "mainHome": "← หน้าหลัก LIFE.HELP",
      "helperHonorific": "คุณช่าง",
      "verifiedHelper": "ช่างที่ผ่านการยืนยัน",
      "securitySessionBadge": "เซสชันความปลอดภัย 3 เดือน",
      "daysRemaining": "วันคงเหลือ",
      "signedDate": "วันที่ทำสัญญา",
      "viewContract": "ดูสัญญาอิเล็กทรอนิกส์",
      "logout": "ออกจากระบบ",
      "availTitle": "การจัดการสถานะความพร้อมแบบเรียลไทม์",
      "statusActive": "พร้อมทำงาน (เปิดรับงาน)",
      "statusPaused": "หยุดชั่วคราว (พักงาน)",
      "descActive": "พร้อมรับงานทันที กรุณาสลับเป็นหยุดชั่วคราวเมื่อต้องการพักผ่อน",
      "descPaused": "หยุดรับการเรียกงานชั่วคราว สลับกลับมาเปิดเมื่อพร้อมรับงาน",
      "btnPause": "⏸ หยุดพักชั่วคราว",
      "btnResume": "🟢 พร้อมรับงานทันที",
      "activeTitle": "พร้อมทำงาน (เปิดรับงาน)",
      "activeDesc": "พร้อมรับงานทันที กรุณาสลับเป็นหยุดชั่วคราวเมื่อต้องการพักผ่อน",
      "pausedTitle": "หยุดชั่วคราว (พักงาน)",
      "pausedDesc": "หยุดรับการเรียกงานชั่วคราว สลับกลับมาเปิดเมื่อพร้อมรับงาน",
      "resumeBtn": "🟢 พร้อมรับงานทันที",
      "pauseBtn": "⏸ หยุดพักชั่วคราว",
      "hotlineTitle": "สายด่วนประสานงานหลัก",
      "hotlineDesc": "หากพบปัญหาหรือการเปลี่ยนแปลงเร่งด่วน โปรดติดต่อทันที",
      "team1": "สายด่วนทีม 1 (ฉุกเฉิน)",
      "team2": "สายด่วนทีม 2 (ทั่วไป)",
      "call": "โทร",
      "sms": "SMS",
      "servicesTitle": "จัดการหมวดหมู่บริการ",
      "servicesDesc": "คลิกเพื่อยกเลิกหรือเพิ่มหมวดหมู่บริการแบบเรียลไทม์",
      "categoriesActive": "หมวดหมู่ที่เปิดใช้งาน",
      "serviceActive": "เปิดใช้งาน",
      "serviceDisabled": "ปิดใช้งาน",
      "regionsTitle": "พื้นที่ให้บริการ",
      "regionsDesc": "คลิก ✕ เพื่อลบพื้นที่ หรือเพิ่มพื้นที่ใหม่",
      "regionsCount": "พื้นที่ที่ตั้งค่าไว้",
      "addRegionBtn": "เพิ่มพื้นที่ให้บริการ",
      "removeRegionTitle": "ลบพื้นที่",
      "scheduleTitle": "ตารางเวลาที่พร้อมให้บริการ",
      "setHours": "ช่วงเวลาที่ตั้งไว้",
      "hours24": "พร้อมให้บริการฉุกเฉิน 24 ชั่วโมง",
      "contractTitle": "สำเนาสัญญาอิเล็กทรอนิกส์ LIFE.HELP",
      "contractName": "ชื่อ-นามสกุล",
      "contractPhone": "เบอร์โทรศัพท์มือถือ",
      "contractResidentId": "หมายเลขบัตร (ปกปิด)",
      "contractSignedAt": "วันและเวลาที่ลงนาม",
      "contractClauseTitle": "ข้อกำหนดและหน้าที่ในการแจ้งเตือน",
      "contractClauseDesc": "ช่างตกลงที่จะแจ้งเจ้าหน้าที่ทันทีหากไม่สามารถทำงานหรือเปลี่ยนพื้นที่ได้",
      "contractSignature": "ยืนยันลายเซ็นอิเล็กทรอนิกส์แล้ว",
      "close": "ปิด",
      "minServiceAlert": "ต้องมีบริการที่เปิดอยู่อย่างน้อย 1 หมวดหมู่",
      "serviceRemoved": "ลบหมวดหมู่บริการแล้ว",
      "serviceAdded": "เพิ่มหมวดหมู่บริการใหม่แล้ว",
      "regionAdded": "เพิ่มพื้นที่ให้บริการแล้ว",
      "minRegionAlert": "ต้องเลือกพื้นที่อย่างน้อย 1 แห่ง",
      "regionRemoved": "ลบพื้นที่เรียบร้อยแล้ว",
      "minDayAlert": "ต้องเลือกวันทำงานอย่างน้อย 1 วัน",
      "daysUpdated": "อัปเดตวันทำงานเรียบร้อยแล้ว",
      "logoutConfirm": "คุณต้องการออกจากระบบหรือไม่?",
      "adminChat": "ติดต่อผู้ดูแลระบบ",
      "openAdminChat": "ข้อความจากผู้ดูแล",
      "adminChatTitle": "แชท 1:1 กับฝ่ายสนับสนุนส่วนกลาง",
      "adminChatOnline": "ออนไลน์",
      "adminChatRecipient": "ผู้รับ: ช่าง",
      "adminChatEmpty": "ไม่มีข้อความกับผู้ดูแลระบบ",
      "adminChatEmptyHint": "ฝากข้อความหรือแจ้งเหตุฉุกเฉินไว้ เจ้าหน้าที่จะตรวจสอบทันที",
      "adminChatPlaceholder": "พิมพ์ข้อความถึงผู้ดูแลระบบ...",
      "adminChatSend": "ส่ง",
      "calendarClose": "ปิด",
      "monthUnit": "เดือน",
      "adminChatRecipientCounselor": "ผู้รับ: เจ้าหน้าที่ให้คำปรึกษา",
      "adminNoticeBanner": "[ประกาศจากส่วนกลาง]",
      "unreadCount": "ยังไม่ได้อ่าน",
      "preset24Hours": "พร้อมบริการ 24 ชั่วโมง",
      "presetDay": "กลางวัน (09:00 ~ 18:00)",
      "presetNight": "กลางคืนและฉุกเฉิน (18:00 ~ 09:00)",
      "presetMorning": "เช้า (09:00 ~ 13:00)",
      "presetAfternoon": "บ่าย (13:00 ~ 18:00)"
    }
  }
}

