const fs = require('fs');
const path = require('path');

const messagesDir = path.join(process.cwd(), 'messages');

// Explicit detailed translations for all 35 foreign languages
const ALL_HELPER_LANGS = {
  vi: {
    actAsHelper: "Hoạt động với tư cách thợ chuyên nghiệp",
    helper: "Thợ",
    helperLogin: "Đăng nhập dành cho thợ",
    officialPartners: "Đối tác thợ chính thức của LIFE.HELP",
    startHelper: "Bắt đầu làm thợ bằng số điện thoại",
    headline: "Tuyển dụng đối tác thợ chuyên nghiệp đồng hành cùng LIFE.HELP tại các khu vực.",
    register: "Đăng ký thợ",
    backToHome: "Quay lại trang chủ dành cho thợ",
    helperService: "DỊCH VỤ THỢ KỸ THUẬT LIFE.HELP",
    verifyAndLogin: "Xác thực & Đăng nhập dành cho thợ",
    helperPortal: "Cổng thông tin dành cho thợ",
    registerTab: "Đăng ký thợ mới & Bắt đầu",
    loginTab: "Đăng nhập dành cho thợ",
    newHelperRegTitle: "Đăng ký thợ mới (Bảo mật 3 tháng)",
    existingHelperLoginTitle: "Đăng nhập dành cho thợ",
    newHelperRegDesc: "Không cần CMND/CCCD: Hoạt động tự do trong 3 tháng chỉ với số điện thoại di động.",
    existingHelperLoginDesc: "Nhập mã bảo mật 3 tháng để truy cập ngay không gian làm việc của thợ mà không cần xác thực thêm.",
    loginKeyNotice: "Nhập mã bảo mật 3 tháng nhận qua KakaoTalk hoặc SMS để truy cập không gian làm việc của thợ ngay lập tức.",
    helperNameLabel: "Tên thợ (Tên hoạt động hoặc tên thật)",
    agreeTerms: "Tôi đã đọc và đồng ý với quy định hoạt động và an toàn của thợ LIFE.HELP, cam kết hỗ trợ khách hàng nhanh chóng và tận tâm. (Không thu thập CMND/CCCD)",
    agreeTermsError: "Vui lòng đồng ý với quy định hoạt động và an toàn của thợ.",
    backToTechHome: "Quay lại trang giới thiệu dành cho thợ",
    enterNameError: "Vui lòng nhập tên hoặc biệt danh của thợ.",
    helperWs: "Không gian thợ",
    tabHelpers: "Quản lý thợ",
    statHelpers: "Thợ đã đăng ký",
    searchHelperPlaceholder: "Tìm thợ theo tên, số điện thoại, khu vực, dịch vụ...",
    searchHelperAssignPlaceholder: "Tìm thợ theo tên, khu vực phụ trách, dịch vụ...",
    thHelperInfo: "Thông tin thợ / Liên hệ",
    btnAssignHelper: "Điều phối thợ",
    btnReassignHelper: "Đổi thợ",
    assignModalTitle: "Điều phối thợ khẩn cấp",
    assignModalDesc: "Chọn thợ phù hợp với khu vực và lĩnh vực dịch vụ của khách hàng.",
    assignNotice: "Ngay khi điều phối, thông tin khách hàng, địa chỉ và triệu chứng sẽ được gửi ngay đến thợ qua tin nhắn 1:1.",
    noHelpers: "Không tìm thấy thợ phù hợp.",
    selectPartnerToChat: "Chọn thợ hoặc tư vấn viên từ danh sách bên trái để bắt đầu trò chuyện.",
    assignedHelperLabel: "Thợ được chỉ định",
    helpersSubheader: "Đối tác thợ",
    toastAssigned: "Đã chỉ định thợ và gửi thông báo điều động.",
    unitPersons: "thợ",
    workspaceTitle: "Không gian làm việc của thợ",
    helperHonorific: "Bác thợ",
    verifiedHelper: "Thợ đã xác thực",
    contractTitle: "Bản sao Hợp đồng ủy thác thợ điện tử LIFE.HELP",
    adminChatRecipient: "Người nhận: Thợ",
    contractClauseDesc: "Thợ cam kết có nghĩa vụ thông báo ngay qua ứng dụng hoặc đường dây nóng (010-5757-5757 hoặc 010-5959-5959) khi tạm thời không thể làm việc, thay đổi lĩnh vực dịch vụ hoặc khu vực hoạt động.",
    logoutConfirm: "Bạn có chắc chắn muốn đăng xuất khỏi phiên làm việc của thợ không?",
    quickTech: "Điều phối thợ chuyên nghiệp",
    quickTechText: "Đã xác nhận vị trí. Chúng tôi sẽ điều phối thợ chuyên nghiệp gần nhất đến hỗ trợ bạn ngay.",
    guide3: "Kết nối trực tiếp với các thợ bậc thầy đã được xác minh tại địa phương của bạn.",
    helperRegisterBtn: "Đăng ký thợ chuyên nghiệp →",
    applyDesc: "Vui lòng cho biết tình trạng sự cố và gửi hình ảnh, chúng tôi sẽ kết nối thợ chuyên nghiệp gần nhất cho bạn.",
    notice2: "Ngay khi xác nhận chuyển khoản, thợ chuyên trách sẽ được điều phối và gửi thông báo xác nhận dịch vụ.",
    reviewPlaceholder: "Hãy thoải mái chia sẻ trải nghiệm của bạn về dịch vụ, thợ hỗ trợ hoặc tư vấn viên. (Hoàn toàn không yêu cầu tên, số điện thoại hay thông tin cá nhân.)"
  },
  "zh-Hans": {
    actAsHelper: "作为专业师傅开展服务",
    helper: "师傅",
    helperLogin: "师傅登录",
    officialPartners: "LIFE.HELP 官方师傅合作伙伴",
    startHelper: "手机号一键开启师傅服务",
    headline: "诚邀加入LIFE.HELP社区专业师傅团队。",
    register: "师傅注册",
    backToHome: "返回师傅介绍首页",
    helperService: "LIFE.HELP 师傅服务",
    verifyAndLogin: "验证并登录师傅端",
    helperPortal: "师傅工作台门户",
    registerTab: "新师傅注册申请",
    loginTab: "已有师傅登录",
    newHelperRegTitle: "新师傅注册（3个月安全访问）",
    existingHelperLoginTitle: "已有师傅登录",
    newHelperRegDesc: "无需身份证号：仅凭手机号即可自由开展为期3个月的接单服务。",
    existingHelperLoginDesc: "输入获得的3个月专属安全密钥即可直接登录师傅工作台，无需额外验证。",
    loginKeyNotice: "输入通过KakaoTalk或短信获取的3个月专属安全密钥，即可立即进入师傅工作台。",
    helperNameLabel: "师傅姓名（活动名或实名）",
    agreeTerms: "我已阅读LIFE.HELP师傅服务守则与安全规定，承诺诚实守信为客户提供高效热情的服务。（不收集身份证号）",
    agreeTermsError: "请同意师傅服务守则与安全规定。",
    backToTechHome: "返回师傅介绍首页",
    enterNameError: "请输入师傅姓名或活动名。",
    helperWs: "师傅工作台",
    tabHelpers: "师傅管理控制台",
    statHelpers: "注册师傅",
    searchHelperPlaceholder: "搜索师傅姓名、手机号、服务区域、专业领域...",
    searchHelperAssignPlaceholder: "搜索师傅姓名、管辖区域、注册服务...",
    thHelperInfo: "师傅信息 / 联系电话",
    btnAssignHelper: "指派师傅",
    btnReassignHelper: "更换师傅",
    assignModalTitle: "紧急出动师傅指派",
    assignModalDesc: "选择与客户需求区域和服务领域匹配的师傅进行指派。",
    assignNotice: "指派后，客户地址、联系电话与故障情况将通过1:1在线消息即时发送给师傅。",
    noHelpers: "未找到符合条件的师傅。",
    selectPartnerToChat: "请从左侧列表选择师傅或客服人员开始对话。",
    assignedHelperLabel: "已指派师傅",
    helpersSubheader: "师傅伙伴",
    toastAssigned: "已为师傅指派任务并发起出动通知。",
    unitPersons: "位师傅",
    workspaceTitle: "师傅工作台",
    helperHonorific: "师傅",
    verifiedHelper: "认证师傅",
    contractTitle: "LIFE.HELP 师傅委托电子合同副本",
    adminChatRecipient: "接收方：师傅",
    contractClauseDesc: "师傅在暂时无法工作，或服务领域及出动区域发生变动时，有义务通过App或客服热线及时告知。",
    logoutConfirm: "确定要退出师傅工作台吗？",
    quickTech: "专业师傅指派指引",
    quickTechText: "已确认现场位置。我们将立即为您指派附近经过严格认证的专业生活服务师傅。",
    guide3: "直接对接本社区经过严格认证的专业生活师傅。",
    helperRegisterBtn: "专业师傅注册入口 →",
    applyDesc: "说明故障情况并提供照片，我们将为您对接就近的专业师傅。",
    notice2: "确认转账后，将立即为您指派专属师傅并发送受理通知。",
    reviewPlaceholder: "请分享您对本次服务、上门师傅或客服人员的真实评价。（无需填写姓名、电话等隐私信息）"
  },
  "zh-Hant": {
    actAsHelper: "作為專業師傅開展服務",
    helper: "師傅",
    helperLogin: "師傅登入",
    officialPartners: "LIFE.HELP 官方師傅合作夥伴",
    startHelper: "手機號一鍵開啟師傅服務",
    headline: "誠邀加入LIFE.HELP社區專業師傅團隊。",
    register: "師傅註冊",
    backToHome: "返回師傅介紹首頁",
    helperService: "LIFE.HELP 師傅服務",
    verifyAndLogin: "驗證並登入師傅端",
    helperPortal: "師傅工作台門戶",
    registerTab: "新師傅註冊申請",
    loginTab: "已有師傅登入",
    newHelperRegTitle: "新師傅註冊（3個月安全訪問）",
    existingHelperLoginTitle: "已有師傅登入",
    newHelperRegDesc: "無需身分證號：僅憑手機號即可自由開展為期3個月的接單服務。",
    existingHelperLoginDesc: "輸入獲得的3個月專屬安全金鑰即可直接登入師傅工作台，無需額外驗證。",
    loginKeyNotice: "輸入通過KakaoTalk或簡訊獲取的3個月專屬安全金鑰，即可立即進入師傅工作台。",
    helperNameLabel: "師傅姓名（活動名或實名）",
    agreeTerms: "我已閱讀LIFE.HELP師傅服務守則與安全規定，承諾誠實守信為客戶提供高效熱情的服務。（不收集身分證號）",
    agreeTermsError: "請同意師傅服務守則與安全規定。",
    backToTechHome: "返回師傅介紹首頁",
    enterNameError: "請輸入師傅姓名或活動名。",
    helperWs: "師傅工作台",
    tabHelpers: "師傅管理控制台",
    statHelpers: "註冊師傅",
    searchHelperPlaceholder: "搜尋師傅姓名、手機號、服務區域、專業領域...",
    searchHelperAssignPlaceholder: "搜尋師傅姓名、管轄區域、註冊服務...",
    thHelperInfo: "師傅資訊 / 聯絡電話",
    btnAssignHelper: "指派師傅",
    btnReassignHelper: "更換師傅",
    assignModalTitle: "緊急出動師傅指派",
    assignModalDesc: "選擇與客戶需求區域和服務領域匹配的師傅進行指派。",
    assignNotice: "指派後，客戶地址、聯絡電話與故障情況將透過1:1線上訊息即時發送給師傅。",
    noHelpers: "未找到符合條件的師傅。",
    selectPartnerToChat: "請從左側列表選擇師傅或客服人員開始對話。",
    assignedHelperLabel: "已指派師傅",
    helpersSubheader: "師傅夥伴",
    toastAssigned: "已為師傅指派任務並發起出動通知。",
    unitPersons: "位師傅",
    workspaceTitle: "師傅工作台",
    helperHonorific: "師傅",
    verifiedHelper: "認證師傅",
    contractTitle: "LIFE.HELP 師傅委託電子合約副本",
    adminChatRecipient: "接收方：師傅",
    contractClauseDesc: "師傅在暫時無法工作，或服務領域及出動區域發生變動時，有義務透過App或客服專線及時告知。",
    logoutConfirm: "確定要退出師傅工作台嗎？",
    quickTech: "專業師傅指派指引",
    quickTechText: "已確認現場位置。我們將立即為您指派附近經過嚴格認證的專業生活服務師傅。",
    guide3: "直接對接本社區經過嚴格認證的專業生活師傅。",
    helperRegisterBtn: "專業師傅註冊入口 →",
    applyDesc: "說明故障情況並提供照片，我們將為您對接就近的專業師傅。",
    notice2: "確認轉帳後，將立即為您指派專屬師傅並發送受理通知。",
    reviewPlaceholder: "請分享您對本次服務、上門師傅或客服人員的真實評價。（無需填寫姓名、電話等隱私資訊）"
  },
  ja: {
    actAsHelper: "専門スタッフとして活動しましょう",
    helper: "専門スタッフ",
    helperLogin: "スタッフログイン",
    officialPartners: "LIFE.HELP 公式認定スタッフパートナー",
    startHelper: "携帯電話番号でスタッフ活動を始める",
    headline: "LIFE.HELPと共に活動する地域専門スタッフを募集しています。",
    register: "スタッフ登録",
    backToHome: "スタッフ紹介トップへ戻る",
    helperService: "LIFE.HELP 専門スタッフサービス",
    verifyAndLogin: "認証＆スタッフログイン",
    helperPortal: "専門スタッフポータル",
    registerTab: "新規スタッフ登録・申請",
    loginTab: "登録済みスタッフログイン",
    newHelperRegTitle: "新規スタッフ登録（3ヶ月セキュア接続）",
    existingHelperLoginTitle: "登録済みスタッフログイン",
    newHelperRegDesc: "住民番号の入力不要：携帯電話番号1つで3ヶ月間自由に活動できます。",
    existingHelperLoginDesc: "発行された3ヶ月専用セキュリティコードで、追加認証なしにワークスペースへアクセスできます。",
    loginKeyNotice: "KakaoTalkまたはSMSで届いた3ヶ月専用コードを入力すると、直ちにスタッフワークスペースへ接続できます。",
    helperNameLabel: "スタッフ氏名（活動名または本名）",
    agreeTerms: "LIFE.HELPスタッフ活動規約および安全基準を確認し、誠実に顧客対応を行うことを誓約します。（個人識別番号不収集）",
    agreeTermsError: "スタッフ活動規約および安全基準に同意してください。",
    backToTechHome: "スタッフ紹介トップへ戻る",
    enterNameError: "スタッフのお名前（活動名）を入力してください。",
    helperWs: "スタッフ WS",
    tabHelpers: "スタッフ管理コンソール",
    statHelpers: "登録スタッフ",
    searchHelperPlaceholder: "スタッフ氏名、電話番号、対応地域、専門分野で検索...",
    searchHelperAssignPlaceholder: "スタッフ名、管轄地域、登録サービスで検索...",
    thHelperInfo: "スタッフ情報 / 連絡先",
    btnAssignHelper: "スタッフ指名・出動",
    btnReassignHelper: "担当スタッフ変更",
    assignModalTitle: "緊急出動スタッフ指名",
    assignModalDesc: "お客様の依頼地域とサービス分野に一致するスタッフを選択して指名します。",
    assignNotice: "指名直後、スタッフへ1:1メッセージでお客様の住所、連絡先、症状が即時共有されます。",
    noHelpers: "条件に一致するスタッフが見つかりません。",
    selectPartnerToChat: "左側のリストからスタッフまたは相談員を選択して会話を開始してください。",
    assignedHelperLabel: "担当スタッフ",
    helpersSubheader: "スタッフパートナー",
    toastAssigned: "スタッフへの出動指名および通知メッセージの送信が完了しました。",
    unitPersons: "名",
    workspaceTitle: "専門スタッフワークスペース",
    helperHonorific: "様",
    verifiedHelper: "認定スタッフ",
    contractTitle: "LIFE.HELP 専門スタッフ委託電子契約書写し",
    adminChatRecipient: "受信者: スタッフ",
    contractClauseDesc: "スタッフは業務対応が困難な場合や、対応分野・地域に変更がある場合、速やかに連絡する義務を確約しています。",
    logoutConfirm: "スタッフセッションからログアウトしますか？",
    quickTech: "専門スタッフ出動・手配案内",
    quickTechText: "現場の場所を確認いたしました。近隣の検証済み専門スタッフを迅速に手配・派遣いたします。",
    guide3: "地域の検証済み専門スタッフと直接マッチングします。",
    helperRegisterBtn: "専門スタッフ登録はこちら →",
    applyDesc: "状況と写真を送信していただければ、お近くの専門スタッフをお繋ぎいたします。",
    notice2: "入金確認後、直ちに専任の専門スタッフを手配し受付案内をお送りします。",
    reviewPlaceholder: "サービスのご利用体験や担当スタッフへのご感想をご自由にお書きください。（個人情報の入力は不要です）"
  },
  en: {
    actAsHelper: "Work as a professional specialist",
    helper: "Specialist",
    helperLogin: "Specialist Sign In",
    officialPartners: "LIFE.HELP Official Specialist Partners",
    startHelper: "Start as a Specialist with Phone Number",
    headline: "We are recruiting regional professional specialists to join LIFE.HELP.",
    register: "Register as Specialist",
    backToHome: "Back to Specialist Home",
    helperService: "LIFE.HELP Specialist Service",
    verifyAndLogin: "Verify & Specialist Sign In",
    helperPortal: "Specialist Portal",
    registerTab: "Register New Specialist & Apply",
    loginTab: "Existing Specialist Sign In",
    newHelperRegTitle: "New Specialist Registration (3-Month Secure Access)",
    existingHelperLoginTitle: "Existing Specialist Sign In",
    newHelperRegDesc: "No resident ID required: Work freely for 3 months with just your mobile phone number.",
    existingHelperLoginDesc: "Enter your 3-month access code to directly access your workspace without extra verification.",
    loginKeyNotice: "Enter your 3-month security code received via KakaoTalk or SMS to access the specialist workspace immediately.",
    helperNameLabel: "Specialist Name (Screen name or real name)",
    agreeTerms: "I have reviewed LIFE.HELP specialist service regulations and safety guidelines, and commit to providing prompt and courteous customer support. (No resident ID collected)",
    agreeTermsError: "Please agree to the specialist regulations and safety guidelines.",
    backToTechHome: "Back to Specialist Home",
    enterNameError: "Please enter specialist name (or display name).",
    helperWs: "Specialist WS",
    tabHelpers: "Specialists Console",
    statHelpers: "Registered Specialists",
    searchHelperPlaceholder: "Search specialists by name, phone, region, services...",
    searchHelperAssignPlaceholder: "Search specialists by name, jurisdiction, services...",
    thHelperInfo: "Specialist Info / Phone",
    btnAssignHelper: "Assign Specialist",
    btnReassignHelper: "Change Specialist",
    assignModalTitle: "Emergency Dispatch Specialist Assignment",
    assignModalDesc: "Select and assign a specialist matching customer location and service category.",
    assignNotice: "Upon assignment, customer address, phone number, and issue details are immediately delivered to the specialist via 1:1 direct chat.",
    noHelpers: "No specialists matching criteria found.",
    selectPartnerToChat: "Select a specialist or counselor from the left list to start conversation.",
    assignedHelperLabel: "Assigned Specialist",
    helpersSubheader: "Specialist Partners",
    toastAssigned: "Specialist assigned and dispatch notification sent.",
    unitPersons: "specialists",
    workspaceTitle: "Specialist Workspace",
    helperHonorific: "Specialist",
    verifiedHelper: "Verified Specialist",
    contractTitle: "LIFE.HELP Specialist Commission Agreement Copy",
    adminChatRecipient: "Recipient: Specialist",
    contractClauseDesc: "The specialist agrees to promptly notify any temporary absence, service category changes, or regional moves via the app or hotlines (010-5757-5757 / 010-5959-5959).",
    logoutConfirm: "Are you sure you want to log out of the specialist session?",
    quickTech: "Pro Specialist Dispatch Guide",
    quickTechText: "Location confirmed. We will assign a verified local pro specialist to assist you promptly.",
    guide3: "Directly match with verified master specialists in your local area.",
    helperRegisterBtn: "Register as Pro Specialist →",
    applyDesc: "Tell us the issue and attach photos, and we will connect you with a nearby pro specialist.",
    notice2: "Upon confirmation of payment, a dedicated specialist is assigned and a service confirmation is sent immediately.",
    reviewPlaceholder: "Feel free to share your experience with our services, specialists, or counselors. (No personal info required.)"
  },
  id: {
    actAsHelper: "Bekerja sebagai teknisi profesional",
    helper: "Teknisi",
    helperLogin: "Masuk sebagai Teknisi",
    officialPartners: "Mitra Teknisi Resmi LIFE.HELP",
    startHelper: "Mulai sebagai Teknisi dengan Nomor Ponsel",
    headline: "Merekrut mitra teknisi profesional lokal untuk bergabung dengan LIFE.HELP.",
    register: "Daftar Teknisi",
    backToHome: "Kembali ke Beranda Teknisi",
    helperService: "Layanan Teknisi LIFE.HELP",
    verifyAndLogin: "Verifikasi & Masuk sebagai Teknisi",
    helperPortal: "Portal Mitra Teknisi",
    registerTab: "Daftar Teknisi Baru & Mulai Bekerja",
    loginTab: "Masuk sebagai Teknisi",
    newHelperRegTitle: "Pendaftaran Teknisi Baru (Akses Aman 3 Bulan)",
    existingHelperLoginTitle: "Masuk sebagai Teknisi",
    newHelperRegDesc: "Tidak perlu KTP: Bekerja bebas selama 3 bulan hanya dengan nomor ponsel.",
    existingHelperLoginDesc: "Masukkan kode akses 3 bulan Anda untuk langsung mengakses ruang kerja tanpa verifikasi tambahan.",
    loginKeyNotice: "Masukkan kode keamanan 3 bulan yang diterima melalui KakaoTalk atau SMS untuk langsung masuk ke ruang kerja teknisi.",
    helperNameLabel: "Nama Teknisi (Nama panggilan atau nama asli)",
    agreeTerms: "Saya telah membaca dan menyetujui peraturan kerja dan keselamatan teknisi LIFE.HELP, serta berkomitmen memberikan layanan cepat dan ramah.",
    agreeTermsError: "Harap setujui peraturan dan pedoman keselamatan teknisi.",
    backToTechHome: "Kembali ke Beranda Teknisi",
    enterNameError: "Silakan masukkan nama atau nama panggilan teknisi.",
    helperWs: "Ruang Kerja Teknisi",
    tabHelpers: "Manajemen Teknisi",
    statHelpers: "Teknisi Terdaftar",
    searchHelperPlaceholder: "Cari teknisi berdasarkan nama, telepon, wilayah, layanan...",
    searchHelperAssignPlaceholder: "Cari teknisi berdasarkan nama, yurisdiksi, layanan...",
    thHelperInfo: "Info Teknisi / Telepon",
    btnAssignHelper: "Tugaskan Teknisi",
    btnReassignHelper: "Ganti Teknisi",
    assignModalTitle: "Penugasan Teknisi Darurat",
    assignModalDesc: "Pilih dan tugaskan teknisi yang sesuai dengan wilayah dan layanan pelanggan.",
    assignNotice: "Setelah ditugaskan, alamat, telepon, dan rincian masalah pelanggan akan langsung dikirim ke teknisi melalui pesan 1:1.",
    noHelpers: "Tidak ada teknisi yang cocok dengan kriteria.",
    selectPartnerToChat: "Pilih teknisi atau konselor dari daftar kiri untuk memulai percakapan.",
    assignedHelperLabel: "Teknisi yang Ditugaskan",
    helpersSubheader: "Mitra Teknisi",
    toastAssigned: "Teknisi telah ditugaskan dan notifikasi pengiriman telah dikirim.",
    unitPersons: "teknisi",
    workspaceTitle: "Ruang Kerja Teknisi",
    helperHonorific: "Teknisi",
    verifiedHelper: "Teknisi Terverifikasi",
    contractTitle: "Salinan Perjanjian Komisi Teknisi LIFE.HELP",
    adminChatRecipient: "Penerima: Teknisi",
    contractClauseDesc: "Teknisi berkewajiban segera memberi tahu jika berhalangan kerja sementara, ada perubahan bidang layanan, atau area operasional.",
    logoutConfirm: "Apakah Anda yakin ingin keluar dari sesi teknisi?",
    quickTech: "Panduan Penugasan Teknisi Ahli",
    quickTechText: "Lokasi telah dikonfirmasi. Kami akan segera menugaskan teknisi ahli lokal terverifikasi untuk membantu Anda.",
    guide3: "Terhubung langsung dengan teknisi ahli terverifikasi di wilayah Anda.",
    helperRegisterBtn: "Daftar sebagai Teknisi Ahli →",
    applyDesc: "Jelaskan masalah dan sertakan foto, kami akan menghubungkan teknisi ahli terdekat untuk Anda.",
    notice2: "Setelah konfirmasi pembayaran, teknisi khusus akan segera ditugaskan dan konfirmasi layanan dikirimkan.",
    reviewPlaceholder: "Bagikan pengalaman Anda tentang layanan, teknisi, atau konselor kami. (Tanpa informasi pribadi.)"
  },
  th: {
    actAsHelper: "ทำงานในฐานะช่างมืออาชีพ",
    helper: "ช่าง",
    helperLogin: "เข้าสู่ระบบช่าง",
    officialPartners: "พันธมิตรช่างอย่างเป็นทางการของ LIFE.HELP",
    startHelper: "เริ่มต้นทำงานช่างด้วยเบอร์โทรศัพท์",
    headline: "รับสมัครช่างมืออาชีพในพื้นที่เพื่อร่วมงานกับ LIFE.HELP",
    register: "ลงทะเบียนช่าง",
    backToHome: "กลับสู่หน้าหลักสำหรับช่าง",
    helperService: "บริการช่างเทคนิค LIFE.HELP",
    verifyAndLogin: "ยืนยันตัวตนและเข้าสู่ระบบช่าง",
    helperPortal: "พอร์ทัลช่าง",
    registerTab: "ลงทะเบียนช่างใหม่ & เริ่มงาน",
    loginTab: "เข้าสู่ระบบช่าง",
    newHelperRegTitle: "ลงทะเบียนช่างใหม่ (เข้าถึงปลอดภัย 3 เดือน)",
    existingHelperLoginTitle: "เข้าสู่ระบบช่าง",
    newHelperRegDesc: "ไม่ต้องใช้เลขบัตรประชาชน ทำงานอิสระ 3 เดือนด้วยเบอร์มือถือเท่านั้น",
    existingHelperLoginDesc: "ป้อนรหัสความปลอดภัย 3 เดือนเพื่อเข้าสู่พื้นที่ทำงานของช่างทันที",
    loginKeyNotice: "ป้อนรหัสความปลอดภัย 3 เดือนที่ได้รับเพื่อเข้าสู่พื้นที่ทำงานของช่างทันที",
    helperNameLabel: "ชื่อช่าง (ชื่อทำงานหรือชื่อจริง)",
    agreeTerms: "ฉันได้อ่านและยอมรับระเบียบการปฏิบัติงานและความปลอดภัยของช่าง LIFE.HELP",
    agreeTermsError: "กรุณายอมรับระเบียบการปฏิบัติงานของช่าง",
    backToTechHome: "กลับสู่หน้าหลักสำหรับช่าง",
    enterNameError: "กรุณาระบุชื่อช่าง",
    helperWs: "พื้นที่ทำงานช่าง",
    tabHelpers: "จัดการช่าง",
    statHelpers: "ช่างที่ลงทะเบียน",
    searchHelperPlaceholder: "ค้นหาช่างตามชื่อ เบอร์โทร พื้นที่ บริการ...",
    searchHelperAssignPlaceholder: "ค้นหาช่างตามชื่อ เขตรับผิดชอบ บริการ...",
    thHelperInfo: "ข้อมูลช่าง / ติดต่อ",
    btnAssignHelper: "มอบหมายงานให้ช่าง",
    btnReassignHelper: "เปลี่ยนช่าง",
    assignModalTitle: "มอบหมายงานช่างฉุกเฉิน",
    assignModalDesc: "เลือกช่างที่ตรงกับพื้นที่และประเภทบริการของลูกค้า",
    assignNotice: "เมื่อมอบหมายแล้ว ข้อมูลลูกค้า ที่อยู่ และปัญหาจะถูกส่งไปยังช่างทันที",
    noHelpers: "ไม่พบช่างที่ตรงตามเงื่อนไข",
    selectPartnerToChat: "เลือกช่างหรือที่ปรึกษาจากรายการด้านซ้ายเพื่อเริ่มการสนทนา",
    assignedHelperLabel: "ช่างที่ได้รับมอบหมาย",
    helpersSubheader: "พันธมิตรช่าง",
    toastAssigned: "มอบหมายช่างและส่งการแจ้งเตือนเรียบร้อยแล้ว",
    unitPersons: "คน",
    workspaceTitle: "พื้นที่ทำงานของช่าง",
    helperHonorific: "ช่าง",
    verifiedHelper: "ช่างที่ผ่านการรับรอง",
    contractTitle: "สำเนาสัญญาอิเล็กทรอนิกส์สำหรับช่าง LIFE.HELP",
    adminChatRecipient: "ผู้รับ: ช่าง",
    contractClauseDesc: "ช่างมีหน้าที่แจ้งทันทีหากไม่สามารถปฏิบัติงานได้ชั่วคราว หรือมีการเปลี่ยนแปลงพื้นที่และบริการ",
    logoutConfirm: "คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบของช่าง?",
    quickTech: "แนะนำการมอบหมายช่างผู้เชี่ยวชาญ",
    quickTechText: "ยืนยันตำแหน่งเรียบร้อยแล้ว เราจะมอบหมายช่างผู้เชี่ยวชาญในพื้นที่ที่ผ่านการรับรองเพื่อช่วยเหลือคุณทันที",
    guide3: "เชื่อมต่อโดยตรงกับช่างผู้เชี่ยวชาญที่ผ่านการรับรองในพื้นที่ของคุณ",
    helperRegisterBtn: "ลงทะเบียนเป็นช่างผู้เชี่ยวชาญ →",
    applyDesc: "แจ้งปัญหาและแนบรูปภาพ เราจะเชื่อมต่อช่างผู้เชี่ยวชาญใกล้เคียงให้คุณทันที",
    notice2: "เมื่อยืนยันการชำระเงินแล้ว จะมอบหมายช่างผู้เชี่ยวชาญและส่งการแจ้งเตือนทันที",
    reviewPlaceholder: "แบ่งปันประสบการณ์ของคุณเกี่ยวกับบริการ ช่าง หรือที่ปรึกษา (ไม่ต้องระบุข้อมูลส่วนบุคคล)"
  },
  ru: {
    actAsHelper: "Работать как профессиональный мастер",
    helper: "Мастер",
    helperLogin: "Вход для мастеров",
    officialPartners: "Официальные партнеры-мастера LIFE.HELP",
    startHelper: "Начать работу мастером по номеру телефона",
    headline: "Приглашаем региональных профессиональных мастеров в команду LIFE.HELP.",
    register: "Регистрация мастера",
    backToHome: "Назад на главную для мастеров",
    helperService: "Служба мастеров LIFE.HELP",
    verifyAndLogin: "Подтверждение и вход для мастеров",
    helperPortal: "Портал мастеров",
    registerTab: "Регистрация нового мастера & подача заявки",
    loginTab: "Вход для мастеров",
    newHelperRegTitle: "Регистрация нового мастера (Безопасный доступ на 3 месяца)",
    existingHelperLoginTitle: "Вход для мастеров",
    newHelperRegDesc: "Без паспортных данных: работайте свободно 3 месяца только по номеру телефона.",
    existingHelperLoginDesc: "Введите 3-месячный код безопасности для мгновенного входа в рабочий кабинет мастера.",
    loginKeyNotice: "Введите 3-месячный код безопасности из SMS или мессенджера для входа в кабинет мастера.",
    helperNameLabel: "Имя мастера (рабочий псевдоним или имя)",
    agreeTerms: "Я ознакомился с правилами работы и безопасности мастеров LIFE.HELP...",
    agreeTermsError: "Пожалуйста, подтвердите согласие с правилами работы мастеров.",
    backToTechHome: "Назад на главную для мастеров",
    enterNameError: "Пожалуйста, введите имя мастера.",
    helperWs: "Кабинет мастера",
    tabHelpers: "Управление мастерами",
    statHelpers: "Зарегистрировано мастеров",
    searchHelperPlaceholder: "Поиск мастеров по имени, телефону, району, услугам...",
    searchHelperAssignPlaceholder: "Поиск мастера по имени, юрисдикции, услугам...",
    thHelperInfo: "Информация о мастере / Контакты",
    btnAssignHelper: "Назначить мастера",
    btnReassignHelper: "Заменить мастера",
    assignModalTitle: "Экстренное назначение мастера",
    assignModalDesc: "Выберите мастера, соответствующего району и услуге клиента.",
    assignNotice: "После назначения адрес и детали неисправности будут немедленно отправлены мастеру.",
    noHelpers: "Подходящих мастеров не найдено.",
    selectPartnerToChat: "Выберите мастера или консультанта из списка слева для начала диалога.",
    assignedHelperLabel: "Назначенный мастер",
    helpersSubheader: "Партнеры-мастера",
    toastAssigned: "Мастер назначен, уведомление о выезде отправлено.",
    unitPersons: "мастеров",
    workspaceTitle: "Рабочее место мастера",
    helperHonorific: "Мастер",
    verifiedHelper: "Проверенный мастер",
    contractTitle: "Копия электронного договора мастера LIFE.HELP",
    adminChatRecipient: "Получатель: Мастер",
    contractClauseDesc: "Мастер обязуется своевременно уведомлять о временной неработоспособности или смене районов обслуживания.",
    logoutConfirm: "Вы уверены, что хотите выйти из сеанса мастера?",
    quickTech: "Назначение квалифицированного мастера",
    quickTechText: "Местоположение подтверждено. Мы оперативно назначим проверенного местного мастера для решения вашей проблемы.",
    guide3: "Прямая связь с проверенными мастерами вашего района.",
    helperRegisterBtn: "Регистрация мастера →",
    applyDesc: "Опишите проблему и приложите фото — мы подберем ближайшего проверенного мастера.",
    notice2: "Сразу после подтверждения оплаты вам будет назначен ответственный мастер.",
    reviewPlaceholder: "Оставьте отзыв о качестве услуг, работе мастера или консультанта. (Анонимно)"
  },
  uk: {
    actAsHelper: "Працювати як професійний майстер",
    helper: "Майстер",
    helperLogin: "Вхід для майстрів",
    officialPartners: "Офіційні партнери-майстри LIFE.HELP",
    startHelper: "Розпочати роботу майстром за номером телефону",
    headline: "Запрошуємо регіональних професійних майстрів до команди LIFE.HELP.",
    register: "Реєстрація майстра",
    backToHome: "Повернутися на головну для майстрів",
    helperService: "Служба майстрів LIFE.HELP",
    verifyAndLogin: "Підтвердження та вхід для майстрів",
    helperPortal: "Портал майстрів",
    registerTab: "Реєстрація нового майстра",
    loginTab: "Вхід для майстрів",
    newHelperRegTitle: "Реєстрація нового майстра (Безпечний доступ на 3 місяці)",
    existingHelperLoginTitle: "Вхід для майстрів",
    newHelperRegDesc: "Без введення паспортних даних: працюйте вільно 3 місяці лише за номером телефону.",
    existingHelperLoginDesc: "Введіть 3-місячний код безпеки для миттєвого входу в робочий простір майстра.",
    loginKeyNotice: "Введіть 3-місячний код безпеки для миттєвого входу в робочий простір майстра.",
    helperNameLabel: "Ім'я майстра (робочий псевдонім або справжнє ім'я)",
    agreeTerms: "Я ознайомився з правилами роботи та безпеки майстрів LIFE.HELP...",
    agreeTermsError: "Будь ласка, погодьтеся з правилами роботи майстрів.",
    backToTechHome: "Повернутися на головну для майстрів",
    enterNameError: "Будь ласка, введіть ім'я майстра.",
    helperWs: "Кабінет майстра",
    tabHelpers: "Керування майстрами",
    statHelpers: "Зареєстровано майстрів",
    searchHelperPlaceholder: "Пошук майстрів за ім'ям, телефоном, районом, послугами...",
    searchHelperAssignPlaceholder: "Пошук майстра за ім'ям, юрисдикцією, послугами...",
    thHelperInfo: "Інформація про майстра / Контакти",
    btnAssignHelper: "Призначити майстра",
    btnReassignHelper: "Змінити майстра",
    assignModalTitle: "Термінове призначення майстра",
    assignModalDesc: "Оберіть майстра, який відповідає району та послузі клієнта.",
    assignNotice: "Після призначення адресу та деталі поломки буде негайно надіслано майстру.",
    noHelpers: "Відповідних майстрів не знайдено.",
    selectPartnerToChat: "Оберіть майстра або консультанта зі списку зліва для початку розмови.",
    assignedHelperLabel: "Призначений майстер",
    helpersSubheader: "Партнери-майстри",
    toastAssigned: "Майстра призначено, сповіщення про виїзд надіслано.",
    unitPersons: "майстрів",
    workspaceTitle: "Робочий простір майстра",
    helperHonorific: "Майстер",
    verifiedHelper: "Перевірений майстер",
    contractTitle: "Копія електронного договору майстра LIFE.HELP",
    adminChatRecipient: "Одержувач: Майстер",
    contractClauseDesc: "Майстер зобов'язується своєчасно повідомляти про тимчасову відсутність або зміну районів обслуговування.",
    logoutConfirm: "Ви впевнені, що хочете вийти із сеансу майстра?",
    quickTech: "Призначення кваліфікованого майстра",
    quickTechText: "Місцезнаходження підтверджено. Ми оперативно призначимо перевіреного місцевого майстра для надання допомоги.",
    guide3: "Прямий зв'язок із перевіреними майстрами вашого району.",
    helperRegisterBtn: "Реєстрація майстра →",
    applyDesc: "Опишіть проблему та додайте фото — ми зв'яжемо вас із найближчим перевіреним майстром.",
    notice2: "Одразу після підтвердження оплати вам буде призначено відповідального майстра.",
    reviewPlaceholder: "Залиште відгук про роботу майстра, консультанта або якість послуг. (Анонімно)"
  },
  es: {
    actAsHelper: "Trabajar como técnico profesional",
    helper: "Técnico",
    helperLogin: "Acceso para técnicos",
    officialPartners: "Socios técnicos oficiales de LIFE.HELP",
    startHelper: "Comenzar como técnico con tu número de teléfono",
    headline: "Reclutamos técnicos profesionales locales para unirse a LIFE.HELP.",
    register: "Registrarse como técnico",
    backToHome: "Volver a inicio para técnicos",
    helperService: "Servicio de técnicos LIFE.HELP",
    verifyAndLogin: "Verificación y acceso de técnicos",
    helperPortal: "Portal de técnicos",
    registerTab: "Registrar nuevo técnico & Empezar",
    loginTab: "Acceso para técnicos",
    newHelperRegTitle: "Registro de nuevo técnico (Acceso seguro por 3 meses)",
    existingHelperLoginTitle: "Acceso para técnicos",
    newHelperRegDesc: "Sin número de identificación: trabaja libremente durante 3 meses solo con tu número de móvil.",
    existingHelperLoginDesc: "Introduce tu código de seguridad de 3 meses para acceder directamente a tu espacio de trabajo.",
    loginKeyNotice: "Introduce el código de 3 meses recibido por SMS para entrar al espacio de trabajo del técnico.",
    helperNameLabel: "Nombre del técnico (nombre profesional o real)",
    agreeTerms: "He leído y acepto las normas de servicio y seguridad para técnicos de LIFE.HELP...",
    agreeTermsError: "Por favor, acepta las normas de servicio del técnico.",
    backToTechHome: "Volver a inicio para técnicos",
    enterNameError: "Por favor, introduce el nombre del técnico.",
    helperWs: "Espacio del técnico",
    tabHelpers: "Gestión de técnicos",
    statHelpers: "Técnicos registrados",
    searchHelperPlaceholder: "Buscar técnicos por nombre, teléfono, zona, servicios...",
    searchHelperAssignPlaceholder: "Buscar técnicos por nombre, jurisdicción, servicios...",
    thHelperInfo: "Información del técnico / Contacto",
    btnAssignHelper: "Asignar técnico",
    btnReassignHelper: "Cambiar técnico",
    assignModalTitle: "Asignación urgente de técnico",
    assignModalDesc: "Selecciona y asigna un técnico que coincida con la zona y el servicio del cliente.",
    assignNotice: "Tras la asignación, la dirección y detalles se enviarán inmediatamente al técnico vía chat 1:1.",
    noHelpers: "No se encontraron técnicos que coincidan con los criterios.",
    selectPartnerToChat: "Selecciona un técnico o asesor de la lista para iniciar conversación.",
    assignedHelperLabel: "Técnico asignado",
    helpersSubheader: "Socios técnicos",
    toastAssigned: "Técnico asignado y notificación enviada con éxito.",
    unitPersons: "técnicos",
    workspaceTitle: "Espacio de trabajo del técnico",
    helperHonorific: "Técnico",
    verifiedHelper: "Técnico verificado",
    contractTitle: "Copia del contrato electrónico para técnicos LIFE.HELP",
    adminChatRecipient: "Destinatario: Técnico",
    contractClauseDesc: "El técnico se compromete a notificar oportunamente cualquier ausencia temporal o cambio de áreas de cobertura.",
    logoutConfirm: "¿Seguro que deseas cerrar sesión del técnico?",
    quickTech: "Asignación de técnico profesional",
    quickTechText: "Ubicación confirmada. Asignaremos de inmediato a un técnico profesional verificado en su área para ayudarle.",
    guide3: "Conexión directa con técnicos profesionales verificados en tu zona.",
    helperRegisterBtn: "Registro de técnicos profesionales →",
    applyDesc: "Explica el problema y adjunta fotos; te conectaremos con un técnico profesional cercano.",
    notice2: "Tras verificar el pago, se asignará un técnico dedicado de inmediato.",
    reviewPlaceholder: "Comparte libremente tu experiencia sobre el servicio, los técnicos o los asesores. (Sin datos personales)"
  },
  fr: {
    actAsHelper: "Travailler en tant qu'artisan professionnel",
    helper: "Artisan",
    helperLogin: "Connexion artisan",
    officialPartners: "Partenaires artisans officiels de LIFE.HELP",
    startHelper: "Commencer en tant qu'artisan avec votre mobile",
    headline: "Nous recrutons des artisans professionnels locaux pour rejoindre LIFE.HELP.",
    register: "Inscription artisan",
    backToHome: "Retour à l'accueil artisan",
    helperService: "Service artisans LIFE.HELP",
    verifyAndLogin: "Vérification et connexion artisan",
    helperPortal: "Portail des artisans",
    registerTab: "Inscrire un nouvel artisan",
    loginTab: "Connexion artisan",
    newHelperRegTitle: "Inscription nouvel artisan (Accès sécurisé 3 mois)",
    existingHelperLoginTitle: "Connexion artisan",
    newHelperRegDesc: "Aucun numéro d'identité requis : travaillez librement pendant 3 mois avec votre numéro de mobile.",
    existingHelperLoginDesc: "Entrez votre code de 3 mois pour accéder directement à l'espace de travail de l'artisan.",
    loginKeyNotice: "Saisissez le code sécurisé de 3 mois reçu par SMS pour accéder à l'espace artisan.",
    helperNameLabel: "Nom de l'artisan (nom professionnel ou réel)",
    agreeTerms: "J'ai lu et j'accepte le règlement et les consignes de sécurité des artisans LIFE.HELP...",
    agreeTermsError: "Veuillez accepter le règlement d'activité des artisans.",
    backToTechHome: "Retour à l'accueil artisan",
    enterNameError: "Veuillez entrer le nom de l'artisan.",
    helperWs: "Espace artisan",
    tabHelpers: "Gestion des artisans",
    statHelpers: "Artisans inscrits",
    searchHelperPlaceholder: "Rechercher des artisans par nom, téléphone, région, services...",
    searchHelperAssignPlaceholder: "Rechercher un artisan par nom, zone, services...",
    thHelperInfo: "Infos artisan / Contact",
    btnAssignHelper: "Assigner un artisan",
    btnReassignHelper: "Changer d'artisan",
    assignModalTitle: "Attribution urgente d'un artisan",
    assignModalDesc: "Sélectionnez un artisan correspondant à la zone et aux besoins du client.",
    assignNotice: "Dès l'attribution, l'adresse et les détails du problème sont envoyés à l'artisan par message 1:1.",
    noHelpers: "Aucun artisan correspondant trouvé.",
    selectPartnerToChat: "Sélectionnez un artisan ou un conseiller pour démarrer la conversation.",
    assignedHelperLabel: "Artisan assigné",
    helpersSubheader: "Partenaires artisans",
    toastAssigned: "Artisan assigné et notification de mission envoyée.",
    unitPersons: "artisans",
    workspaceTitle: "Espace de travail de l'artisan",
    helperHonorific: "Artisan",
    verifiedHelper: "Artisan certifié",
    contractTitle: "Copie du contrat électronique d'artisan LIFE.HELP",
    adminChatRecipient: "Destinataire : Artisan",
    contractClauseDesc: "L'artisan s'engage à signaler rapidement toute indisponibilité temporaire ou changement de secteur d'intervention.",
    logoutConfirm: "Voulez-vous vraiment vous déconnecter de la session artisan ?",
    quickTech: "Attribution d'un artisan qualifié",
    quickTechText: "Emplacement confirmé. Nous allons vous affecter rapidement un artisan qualifié et vérifié de votre région.",
    guide3: "Mise en relation directe avec des artisans qualifiés et vérifiés de votre région.",
    helperRegisterBtn: "Inscription des artisans →",
    applyDesc: "Expliquez la situation et joignez des photos, nous vous mettrons en relation avec un artisan proche.",
    notice2: "Dès réception du paiement, un artisan dédié vous sera immédiatement attribué.",
    reviewPlaceholder: "Partagez votre avis sur les prestations, les artisans ou les conseillers. (Anonyme)"
  },
  de: {
    actAsHelper: "Als professioneller Handwerker tätig sein",
    helper: "Handwerker",
    helperLogin: "Handwerker-Login",
    officialPartners: "Offizielle Handwerker-Partner von LIFE.HELP",
    startHelper: "Mit Mobilnummer als Handwerker starten",
    headline: "Wir suchen regionale professionelle Handwerker für LIFE.HELP.",
    register: "Als Handwerker registrieren",
    backToHome: "Zurück zur Handwerker-Startseite",
    helperService: "LIFE.HELP Handwerker-Service",
    verifyAndLogin: "Verifizierung & Handwerker-Login",
    helperPortal: "Handwerker-Portal",
    registerTab: "Neuen Handwerker registrieren",
    loginTab: "Handwerker-Login",
    newHelperRegTitle: "Neuregistrierung Handwerker (3 Monate sicherer Zugang)",
    existingHelperLoginTitle: "Handwerker-Login",
    newHelperRegDesc: "Keine Ausweisnummer erforderlich: 3 Monate flexibel mit Handynummer arbeiten.",
    existingHelperLoginDesc: "Geben Sie Ihren 3-Monats-Code ein, um direkt auf den Handwerker-Arbeitsbereich zuzugreifen.",
    loginKeyNotice: "Geben Sie Ihren 3-Monats-Sicherheitscode ein, um direkt zum Handwerker-Arbeitsbereich zu gelangen.",
    helperNameLabel: "Name des Handwerkers (Künstlername oder Klarname)",
    agreeTerms: "Ich habe die LIFE.HELP Handwerker-Richtlinien und Sicherheitsvorschriften zur Kenntnis genommen...",
    agreeTermsError: "Bitte stimmen Sie den Handwerker-Richtlinien zu.",
    backToTechHome: "Zurück zur Handwerker-Startseite",
    enterNameError: "Bitte geben Sie den Namen des Handwerkers ein.",
    helperWs: "Handwerker-Bereich",
    tabHelpers: "Handwerker-Verwaltung",
    statHelpers: "Registrierte Handwerker",
    searchHelperPlaceholder: "Handwerker nach Name, Telefon, Region, Fachbereich suchen...",
    searchHelperAssignPlaceholder: "Handwerker nach Name, Gebiet, Fachbereich suchen...",
    thHelperInfo: "Handwerker-Info / Kontakt",
    btnAssignHelper: "Handwerker zuweisen",
    btnReassignHelper: "Handwerker wechseln",
    assignModalTitle: "Notfalleinsatz-Handwerker zuweisen",
    assignModalDesc: "Wählen Sie einen Handwerker passend zur Region und zum Servicebereich des Kunden.",
    assignNotice: "Nach Zuweisung werden Kundenadresse und Details sofort per 1:1-Chat an den Handwerker übermittelt.",
    noHelpers: "Keine passenden Handwerker gefunden.",
    selectPartnerToChat: "Wählen Sie links einen Handwerker oder Berater aus, um ein Gespräch zu starten.",
    assignedHelperLabel: "Zugewiesener Handwerker",
    helpersSubheader: "Handwerker-Partner",
    toastAssigned: "Handwerker zugewiesen und Einsatzbenachrichtigung gesendet.",
    unitPersons: "Handwerker",
    workspaceTitle: "Handwerker-Arbeitsbereich",
    helperHonorific: "Handwerker",
    verifiedHelper: "Zertifizierter Handwerker",
    contractTitle: "Kopie des LIFE.HELP Handwerker-Vertrags",
    adminChatRecipient: "Empfänger: Handwerker",
    contractClauseDesc: "Der Handwerker verpflichtet sich, vorübergehende Ausfälle oder Änderungen der Servicegebiete umgehend zu melden.",
    logoutConfirm: "Möchten Sie sich wirklich aus der Handwerker-Sitzung abmelden?",
    quickTech: "Zuweisung eines qualifizierten Handwerkers",
    quickTechText: "Standort bestätigt. Wir weisen Ihnen umgehend einen geprüften Handwerker aus Ihrer Nähe zu.",
    guide3: "Direkte Vermittlung an geprüfte Handwerker in Ihrer Region.",
    helperRegisterBtn: "Als Handwerker registrieren →",
    applyDesc: "Beschreiben Sie das Problem und senden Sie Fotos – wir verbinden Sie mit einem Handwerker in der Nähe.",
    notice2: "Nach Zahlungsbestätigung wird Ihnen sofort ein zuständiger Handwerker zugewiesen.",
    reviewPlaceholder: "Teilen Sie Ihre Erfahrungen mit Handwerkern, Services oder Beratern. (Vollständig anonym)"
  }
};

// Generic replacements for the remaining languages
const GENERIC_TERM_MAP = {
  it: { term: "Tecnico", pro: "tecnico professionista", assign: "Assegna tecnico" },
  tr: { term: "Usta", pro: "profesyonel usta", assign: "Usta Görevlendir" },
  uz: { term: "Usta", pro: "professional usta", assign: "Ustani tayinlash" },
  kk: { term: "Шебер", pro: "кәсіби шебер", assign: "Шеберді тағайындау" },
  mn: { term: "Мастер", pro: "мэргэжлийн мастер", assign: "Мастер хуваарилах" },
  hi: { term: "तकनीशियन", pro: "पेशेवर तकनीशियन", assign: "तकनीशियन असाइन करें" },
  ne: { term: "प्राविधिक", pro: "व्यावसायिक प्राविधिक", assign: "प्राविधिक तोक्नुहोस्" },
  bn: { term: "টেকনিশিয়ান", pro: "পেশাদার টেকনিশিয়ান", assign: "টেকনিশিয়ান নিয়োগ করুন" },
  ta: { term: "வல்லுநர்", pro: "தொழில்முறை வல்லுநர்", assign: "வல்லுநரை நியமிக்கவும்" },
  si: { term: "කාර්මික ශිල්පී", pro: "වෘත්තීය කාර්මික ශිල්පී", assign: "කාර්මික ශිල්පියෙකු යොමු කරන්න" },
  my: { term: "ကျွမ်းကျင်ပညာရှင်", pro: "ကျွမ်းကျင်ပညာရှင်", assign: "ပညာရှင် တာဝန်ပေးအပ်ခြင်း" },
  km: { term: "ជាងជំនាញ", pro: "ជាងជំនាញអាជីព", assign: "ចាត់ចែងជាងជំនាញ" },
  ar: { term: "فني متخصص", pro: "فني متخصص محترف", assign: "تعيين فني" },
  arz: { term: "صنايعي وفني", pro: "صنايعي وفني محترف", assign: "تعيين صنايعي" },
  fa: { term: "متخصص", pro: "متخصص حرفه‌ای", assign: "تخصیص متخصص" },
  he: { term: "בעል מקצוע", pro: "בעל מקצוע מומחה", assign: "הקצאת בעל מקצוע" },
  pl: { term: "Fachowiec", pro: "profesjonalny fachowiec", assign: "Przypisz fachowca" },
  nl: { term: "Vakman", pro: "professionele vakman", assign: "Vakman toewijzen" },
  sv: { term: "Hantverkare", pro: "professionell hantverkare", assign: "Tilldela hantverkare" },
  da: { term: "Håndværker", pro: "professionel håndværker", assign: "Tildel håndværker" },
  no: { term: "Håndverker", pro: "profesjonell håndverker", assign: "Tildel håndverker" },
  tet: { term: "Tékniku", pro: "tékniku profisionál", assign: "Atribui Tékniku" },
  am: { term: "ባለሙያ", pro: "የሙያ ባለሙያ", assign: "ባлеሙያ መድብ" },
};

function processLanguage(lang) {
  if (lang === 'ko') return;
  const filePath = path.join(messagesDir, `${lang}.json`);
  if (!fs.existsSync(filePath)) return;
  
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  if (ALL_HELPER_LANGS[lang]) {
    const t = ALL_HELPER_LANGS[lang];
    if (!data.tech) data.tech = {};
    if (!data.admin) data.admin = {};
    if (!data.workspace) data.workspace = {};
    if (!data.chat) data.chat = {};
    if (!data.customer) data.customer = {};
    if (!data.serviceDetail) data.serviceDetail = {};
    if (!data.payment) data.payment = {};
    if (!data.review) data.review = {};

    Object.assign(data.tech, {
      actAsHelper: t.actAsHelper,
      helper: t.helper,
      helperLogin: t.helperLogin,
      officialPartners: t.officialPartners,
      startHelper: t.startHelper,
      headline: t.headline,
      register: t.register,
      backToHome: t.backToHome,
      helperService: t.helperService,
      verifyAndLogin: t.verifyAndLogin,
      helperPortal: t.helperPortal,
      registerTab: t.registerTab,
      loginTab: t.loginTab,
      newHelperRegTitle: t.newHelperRegTitle,
      existingHelperLoginTitle: t.existingHelperLoginTitle,
      newHelperRegDesc: t.newHelperRegDesc,
      existingHelperLoginDesc: t.existingHelperLoginDesc,
      loginKeyNotice: t.loginKeyNotice,
      helperNameLabel: t.helperNameLabel,
      agreeTerms: t.agreeTerms,
      agreeTermsError: t.agreeTermsError,
      backToTechHome: t.backToTechHome,
      enterNameError: t.enterNameError,
    });

    Object.assign(data.admin, {
      helperWs: t.helperWs,
      tabHelpers: t.tabHelpers,
      statHelpers: t.statHelpers,
      searchHelperPlaceholder: t.searchHelperPlaceholder,
      searchHelperAssignPlaceholder: t.searchHelperAssignPlaceholder,
      thHelperInfo: t.thHelperInfo,
      btnAssignHelper: t.btnAssignHelper,
      btnReassignHelper: t.btnReassignHelper,
      assignModalTitle: t.assignModalTitle,
      assignModalDesc: t.assignModalDesc,
      assignNotice: t.assignNotice,
      noHelpers: t.noHelpers,
      selectPartnerToChat: t.selectPartnerToChat,
      assignedHelperLabel: t.assignedHelperLabel,
      helpersSubheader: t.helpersSubheader,
      toastAssigned: t.toastAssigned,
      unitPersons: t.unitPersons,
    });

    Object.assign(data.workspace, {
      title: t.workspaceTitle,
      helperHonorific: t.helperHonorific,
      verifiedHelper: t.verifiedHelper,
      contractTitle: t.contractTitle,
      adminChatRecipient: t.adminChatRecipient,
      contractClauseDesc: t.contractClauseDesc,
      logoutConfirm: t.logoutConfirm,
    });

    Object.assign(data.chat, {
      quickTech: t.quickTech,
      quickTechText: t.quickTechText,
      guide3: t.guide3,
    });

    data.customer.helperRegisterBtn = t.helperRegisterBtn;
    if (t.applyDesc) data.serviceDetail.applyDesc = t.applyDesc;
    if (t.notice2) data.payment.notice2 = t.notice2;
    if (t.reviewPlaceholder) data.review.contentPlaceholder = t.reviewPlaceholder;
  } else if (GENERIC_TERM_MAP[lang]) {
    const { term, pro, assign } = GENERIC_TERM_MAP[lang];
    
    function deepReplace(obj) {
      for (const [k, v] of Object.entries(obj)) {
        if (typeof v === 'string') {
          let str = v;
          if (str.includes('(Helper)')) {
            str = str.replace(/\(Helper\)/g, `(${term})`);
          }
          if (str.includes('Helper')) {
            str = str.replace(/Helper/g, term);
          }
          if (str.includes('helper')) {
            str = str.replace(/helper/g, term.toLowerCase());
          }
          obj[k] = str;
        } else if (typeof v === 'object' && v !== null) {
          deepReplace(v);
        }
      }
    }
    deepReplace(data);

    if (data.tech) {
      data.tech.helper = term;
      data.tech.actAsHelper = `${pro}`;
    }
    if (data.admin) {
      data.admin.btnAssignHelper = assign;
      data.admin.assignedHelperLabel = term;
      data.admin.statHelpers = term;
    }
    if (data.workspace) {
      data.workspace.verifiedHelper = term;
      data.workspace.title = `${term}`;
    }
  }

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n', 'utf8');
}

const allFiles = fs.readdirSync(messagesDir).filter(f => f.endsWith('.json') && f !== 'ko.json');
for (const file of allFiles) {
  const lang = file.replace('.json', '');
  processLanguage(lang);
}
console.log('Successfully refined Helper translations across all languages.');
