// scripts/update_38_languages.js
const fs = require('fs');
const path = require('path');

const MESSAGES_DIR = path.join(__dirname, '..', 'messages');

// 1. Weekday translations for all 38 languages (0: Mon, 1: Tue, 2: Wed, 3: Thu, 4: Fri, 5: Sat, 6: Sun)
const WEEKDAY_TRANSLATIONS = {
  ko: ["월", "화", "수", "목", "금", "토", "일"],
  en: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  vi: ["T2", "T3", "T4", "T5", "T6", "T7", "CN"],
  "zh-Hans": ["周一", "周二", "周三", "周四", "周五", "周六", "周日"],
  "zh-Hant": ["週一", "週二", "週三", "週四", "週五", "週六", "週日"],
  ja: ["月", "火", "水", "木", "金", "土", "日"],
  pl: ["Pon", "Wt", "Śr", "Czw", "Pt", "Sob", "Niedz"],
  de: ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
  fr: ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"],
  es: ["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"],
  it: ["Lun", "Mar", "Mer", "Gio", "Ven", "Sab", "Dom"],
  pt: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
  el: ["Δευ", "Τρί", "Τετ", "Πέμ", "Παρ", "Σάβ", "Κυρ"],
  ru: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"],
  uk: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Нд"],
  kk: ["Дс", "Сс", "Ср", "Бс", "Жм", "Сб", "Жс"],
  uz: ["Dush", "Sesh", "Chor", "Pay", "Juma", "Shan", "Yak"],
  mn: ["Дав", "Мяг", "Лха", "Пүр", "Баа", "Бям", "Ням"],
  id: ["Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min"],
  th: ["จันทร์", "อังคาร", "พุธ", "พฤหัส", "ศุกร์", "เสาร์", "อาทิตย์"],
  my: ["တနင်္လာ", "အင်္ဂါ", "ဗုဒ္ဓဟူး", "ကြာသပတေး", "သောကြာ", "စနေ", "တနင်္ဂနွေ"],
  km: ["ចន្ទ", "អង្គារ", "ពុធ", "ព្រហ", "សុក្រ", "សៅរ៍", "អាទិត្យ"],
  hi: ["सोम", "मंगल", "बुध", "गुरु", "शुक्र", "शनि", "रवि"],
  ne: ["सोम", "मङ्गल", "बुध", "बिही", "शुक्र", "शनि", "आइत"],
  bn: ["সোম", "মঙ্গল", "বুধ", "বৃহস্পতি", "শুক্র", "শনি", "রবি"],
  ta: ["திங்", "செவ்", "புதன்", "வியா", "வெள்", "சனி", "ஞாயிறு"],
  si: ["සඳුදා", "අඟහ", "බදාදා", "බ්‍රහස්", "සිකු", "සෙන", "ඉරිදා"],
  ar: ["الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت", "الأحد"],
  arz: ["الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت", "الأحد"],
  fa: ["دوشنبه", "سه‌شنبه", "چهارشنبه", "پنج‌شنبه", "جمعه", "شنبه", "یکشنبه"],
  he: ["שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת", "ראשון"],
  tr: ["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"],
  nl: ["Ma", "Di", "Wo", "Do", "Vr", "Za", "Zo"],
  sv: ["Mån", "Tis", "Ons", "Tor", "Fre", "Lör", "Sön"],
  da: ["Man", "Tir", "Ons", "Tor", "Fre", "Lør", "Søn"],
  no: ["Man", "Tir", "Ons", "Tor", "Fre", "Lør", "Søn"],
  am: ["ሰኞ", "ማክሰኞ", "ረቡዕ", "ሐሙስ", "አርብ", "ቅዳሜ", "እሑድ"],
  tet: ["Seg", "Ters", "Kuart", "Kinta", "Sesta", "Sábadu", "Dom"],
};

// 2. Calendar and Workspace core updates
const CALENDAR_UPDATES = {
  ko: {
    calendarTitle: "월간 출동 달력 (당월 및 익월 개별 휴무일 설정)",
    calendarDesc: "기본 설정된 활동 요일은 자동으로 '출동 가능'으로 표시됩니다. 일할 수 없는 날짜를 클릭하여 체크 해제(휴무 지정)하세요.",
    calendarThisMonth: "당월",
    calendarNextMonth: "익월",
    calendarAvailable: "출동 가능",
    calendarDayOff: "개별 휴무",
    calendarDays: "일",
    calendarReset: "휴무 초기화",
    calendarExclusionsTitle: "개별 설정된 휴무일:",
    calendarNoExclusions: "등록된 개별 휴무일 없음 (기본 요일 전체 활동)",
    calendarDayActive: "근무일",
    calendarDayScheduledOff: "정기 휴무",
    calendarEdit: "변경",
    workingHoursDetailTitle: "요일별 근무 시간 상세 설정",
    workingHoursDesc: "활동 가능한 요일을 활성화하고, 요일별 개별 근무 시간대를 지정할 수 있습니다.",
    signedDate: "계약일",
    defaultSchedule: "기본 시간대",
  },
  en: {
    calendarTitle: "Monthly Dispatch Calendar (Day-Off Toggle)",
    calendarDesc: "Days matching weekly settings are auto-marked as active. Click any date to uncheck and set as Day Off.",
    calendarThisMonth: "This Month",
    calendarNextMonth: "Next Month",
    calendarAvailable: "Available",
    calendarDayOff: "Day Off",
    calendarDays: "days",
    calendarReset: "Reset Exclusions",
    calendarExclusionsTitle: "Individual Day-Off Exclusions:",
    calendarNoExclusions: "No individual exclusions set (active on all configured weekdays)",
    calendarDayActive: "Active",
    calendarDayScheduledOff: "Scheduled Off",
    calendarEdit: "Edit",
    workingHoursDetailTitle: "Working Hours by Weekday",
    workingHoursDesc: "Activate available days of the week and set individual working hours per day.",
    signedDate: "Contract Date",
    defaultSchedule: "Default Hours",
  },
  vi: {
    calendarTitle: "Lịch điều phối theo tháng (Cài đặt ngày nghỉ riêng)",
    calendarDesc: "Các ngày theo lịch tuần được tự động đánh dấu là sẵn sàng. Nhấp vào ngày bất kỳ để bỏ chọn và đặt làm ngày nghỉ.",
    calendarThisMonth: "Tháng này",
    calendarNextMonth: "Tháng sau",
    calendarAvailable: "Sẵn sàng",
    calendarDayOff: "Ngày nghỉ",
    calendarDays: "ngày",
    calendarReset: "Đặt lại ngày nghỉ",
    calendarExclusionsTitle: "Danh sách ngày nghỉ riêng:",
    calendarNoExclusions: "Không có ngày nghỉ riêng (hoạt động theo toàn bộ lịch tuần)",
    calendarDayActive: "Ngày làm",
    calendarDayScheduledOff: "Nghỉ định kỳ",
    calendarEdit: "Thay đổi",
    workingHoursDetailTitle: "Cài đặt giờ làm việc chi tiết theo thứ",
    workingHoursDesc: "Kích hoạt các ngày trong tuần có thể làm việc và đặt khung giờ làm việc riêng cho từng ngày.",
    signedDate: "Ngày ký hợp đồng",
    defaultSchedule: "Khung giờ mặc định",
  },
  "zh-Hans": {
    calendarTitle: "月度出动日历（当月及次月个人休息日设置）",
    calendarDesc: "符合每周常规设置的日期会自动标记为可出动。点击任意日期取消勾选并设为休息日。",
    calendarThisMonth: "当月",
    calendarNextMonth: "次月",
    calendarAvailable: "可出动",
    calendarDayOff: "个人休息",
    calendarDays: "天",
    calendarReset: "重置休息日",
    calendarExclusionsTitle: "已设置的个人休息日：",
    calendarNoExclusions: "未设置个人休息日（按每周日程全勤）",
    calendarDayActive: "工作日",
    calendarDayScheduledOff: "常规休息",
    calendarEdit: "修改",
    workingHoursDetailTitle: "按星期的工作时间详细设置",
    workingHoursDesc: "激活可服务的星期，并为每天设定独立的作业时段。",
    signedDate: "签约日期",
    defaultSchedule: "默认时段",
  },
  "zh-Hant": {
    calendarTitle: "月度出勤日曆（當月及次月個人休息日設定）",
    calendarDesc: "符合每週常規設定的日期會自動標記為可出勤。點擊任意日期取消勾選並設為休息日。",
    calendarThisMonth: "當月",
    calendarNextMonth: "次月",
    calendarAvailable: "可出勤",
    calendarDayOff: "個人休息",
    calendarDays: "天",
    calendarReset: "重設休息日",
    calendarExclusionsTitle: "已設定的個人休息日：",
    calendarNoExclusions: "未設定個人休息日（按每週日程全勤）",
    calendarDayActive: "工作日",
    calendarDayScheduledOff: "常規休息",
    calendarEdit: "修改",
    workingHoursDetailTitle: "按星期的工作時間詳細設定",
    workingHoursDesc: "啟動可服務的星期，並為每天設定獨立的作業時段。",
    signedDate: "簽約日期",
    defaultSchedule: "默認時段",
  },
  ja: {
    calendarTitle: "月間出動カレンダー（当月・翌月の個別休日設定）",
    calendarDesc: "基本設定の活動曜日は自動的に「出動可能」と表示されます。活動できない日をクリックしてチェックを外し（休日に指定）、設定してください。",
    calendarThisMonth: "当月",
    calendarNextMonth: "翌月",
    calendarAvailable: "出動可能",
    calendarDayOff: "個別休日",
    calendarDays: "日",
    calendarReset: "休日リセット",
    calendarExclusionsTitle: "設定された個別休日：",
    calendarNoExclusions: "設定された個別休日はありません（曜日設定通り全日程稼働）",
    calendarDayActive: "勤務日",
    calendarDayScheduledOff: "定期休日",
    calendarEdit: "変更",
    workingHoursDetailTitle: "曜日別の勤務時間詳細設定",
    workingHoursDesc: "活動可能な曜日を有効にし、曜日ごとに個別の勤務時間帯を設定できます。",
    signedDate: "契約日",
    defaultSchedule: "基本時間帯",
  },
  pl: {
    calendarTitle: "Miesięczny kalendarz wyjazdów (Ustawienia dni wolnych)",
    calendarDesc: "Dni zgodne z harmonogramem tygodniowym są automatycznie oznaczane jako aktywne. Kliknij dowolną datę, aby odznaczyć i ustawić jako dzień wolny.",
    calendarThisMonth: "Bieżący miesiąc",
    calendarNextMonth: "Następny miesiąc",
    calendarAvailable: "Dostępny",
    calendarDayOff: "Dzień wolny",
    calendarDays: "dni",
    calendarReset: "Zresetuj dni wolne",
    calendarExclusionsTitle: "Indywidualnie wyznaczone dni wolne:",
    calendarNoExclusions: "Brak wyznaczonych dni wolnych (aktywność we wszystkie wybrane dni tygodnia)",
    calendarDayActive: "Dzień pracy",
    calendarDayScheduledOff: "Planowo wolne",
    calendarEdit: "Zmień",
    workingHoursDetailTitle: "Godziny pracy według dni tygodnia",
    workingHoursDesc: "Aktywuj dostępne dni tygodnia i ustaw indywidualne godziny pracy dla każdego dnia.",
    signedDate: "Data podpisania",
    defaultSchedule: "Domyślne godziny",
  },
  de: {
    calendarTitle: "Monatlicher Einsatzkalender (Einstellung von freien Tagen)",
    calendarDesc: "Tage, die den wöchentlichen Einstellungen entsprechen, werden automatisch als aktiv markiert. Klicken Sie auf ein Datum, um es als freien Tag festzulegen.",
    calendarThisMonth: "Dieser Monat",
    calendarNextMonth: "Nächster Monat",
    calendarAvailable: "Verfügbar",
    calendarDayOff: "Freier Tag",
    calendarDays: "Tage",
    calendarReset: "Freie Tage zurücksetzen",
    calendarExclusionsTitle: "Individuell festgelegte freie Tage:",
    calendarNoExclusions: "Keine individuellen freien Tage festgelegt (an allen konfigurierten Wochentagen aktiv)",
    calendarDayActive: "Arbeitstag",
    calendarDayScheduledOff: "Regulär frei",
    calendarEdit: "Ändern",
    workingHoursDetailTitle: "Arbeitszeiten nach Wochentagen",
    workingHoursDesc: "Aktivieren Sie verfügbare Wochentage und legen Sie individuelle Arbeitszeiten pro Tag fest.",
    signedDate: "Vertragsdatum",
    defaultSchedule: "Standardzeiten",
  },
  fr: {
    calendarTitle: "Calendrier d'intervention mensuel (Gestion des jours de congé)",
    calendarDesc: "Les jours correspondant au planning hebdomadaire sont automatiquement marqués comme actifs. Cliquez sur une date pour la définir comme jour de congé.",
    calendarThisMonth: "Ce mois-ci",
    calendarNextMonth: "Mois prochain",
    calendarAvailable: "Disponible",
    calendarDayOff: "Jour de congé",
    calendarDays: "jours",
    calendarReset: "Réinitialiser les congés",
    calendarExclusionsTitle: "Jours de congé individuels définis :",
    calendarNoExclusions: "Aucun congé individuel défini (actif tous les jours configurés)",
    calendarDayActive: "Actif",
    calendarDayScheduledOff: "Repos régulier",
    calendarEdit: "Modifier",
    workingHoursDetailTitle: "Heures de travail par jour de la semaine",
    workingHoursDesc: "Activez les jours disponibles de la semaine et définissez des horaires de travail individuels par jour.",
    signedDate: "Date de signature",
    defaultSchedule: "Horaires par défaut",
  },
  es: {
    calendarTitle: "Calendario mensual de salidas (Configuración de días libres)",
    calendarDesc: "Los días que coinciden con el horario semanal se marcan automáticamente como activos. Haz clic en cualquier fecha para fijarla como día libre.",
    calendarThisMonth: "Este mes",
    calendarNextMonth: "Próximo mes",
    calendarAvailable: "Disponible",
    calendarDayOff: "Día libre",
    calendarDays: "días",
    calendarReset: "Restablecer días libres",
    calendarExclusionsTitle: "Días libres individuales establecidos:",
    calendarNoExclusions: "No se han establecido días libres individuales (activo todos los días configurados)",
    calendarDayActive: "Día laborable",
    calendarDayScheduledOff: "Descanso regular",
    calendarEdit: "Modificar",
    workingHoursDetailTitle: "Horas de trabajo por día de la semana",
    workingHoursDesc: "Activa los días disponibles de la semana y establece horarios de trabajo individuales por día.",
    signedDate: "Fecha de contrato",
    defaultSchedule: "Horario predeterminado",
  },
  it: {
    calendarTitle: "Calendario mensile delle uscite (Impostazione giorni liberi)",
    calendarDesc: "I giorni corrispondenti alle impostazioni settimanali sono contrassegnati come attivi. Clicca su una data per impostarla come giorno libero.",
    calendarThisMonth: "Questo mese",
    calendarNextMonth: "Mese prossimo",
    calendarAvailable: "Disponibile",
    calendarDayOff: "Giorno libero",
    calendarDays: "giorni",
    calendarReset: "Reimposta giorni liberi",
    calendarExclusionsTitle: "Giorni liberi individuali impostati:",
    calendarNoExclusions: "Nessun giorno libero individuale impostato (attivo in tutti i giorni configurati)",
    calendarDayActive: "Giorno lavorativo",
    calendarDayScheduledOff: "Riposo periodico",
    calendarEdit: "Modifica",
    workingHoursDetailTitle: "Orari di lavoro per giorno della settimana",
    workingHoursDesc: "Attiva i giorni disponibili della settimana e imposta orari di lavoro individuali al giorno.",
    signedDate: "Data di stipula",
    defaultSchedule: "Orario predefinito",
  },
  pt: {
    calendarTitle: "Calendário Mensal de Atendimentos (Configuração de Folgas)",
    calendarDesc: "Os dias de acordo com a programação semanal são marcados como ativos. Clique em qualquer data para desmarcar e definir como folga.",
    calendarThisMonth: "Este Mês",
    calendarNextMonth: "Próximo Mês",
    calendarAvailable: "Disponível",
    calendarDayOff: "Folga",
    calendarDays: "dias",
    calendarReset: "Redefinir Folgas",
    calendarExclusionsTitle: "Folgas individuais definidas:",
    calendarNoExclusions: "Nenhuma folga individual definida (ativo em todos os dias configurados)",
    calendarDayActive: "Dia de Trabalho",
    calendarDayScheduledOff: "Folga Regular",
    calendarEdit: "Alterar",
    workingHoursDetailTitle: "Horário de Trabalho por Dia da Semana",
    workingHoursDesc: "Ative os dias disponíveis da semana e defina horários de trabalho individuais por dia.",
    signedDate: "Data do Contrato",
    defaultSchedule: "Horário Padrão",
  },
  el: {
    calendarTitle: "Μηνιαίο Ημερολόγιο Αποστολών (Ρύθμιση Ρεπό)",
    calendarDesc: "Οι ημέρες σύμφωνα με το εβδομαδιαίο πρόγραμμα σημειώνονται αυτόματα ως ενεργές. Κάντε κλικ σε οποιαδήποτε ημερομηνία για να την ορίσετε ως ρεπό.",
    calendarThisMonth: "Τρέχων μήνας",
    calendarNextMonth: "Επόμενος μήνας",
    calendarAvailable: "Διαθέσιμο",
    calendarDayOff: "Ρεπό",
    calendarDays: "ημέρες",
    calendarReset: "Επαναφορά Ρεπό",
    calendarExclusionsTitle: "Μεμονωμένες εξαιρέσεις ρεπό:",
    calendarNoExclusions: "Δεν έχουν οριστεί μεμονωμένα ρεπό (ενεργό σε όλες τις προγραμματισμένες ημέρες)",
    calendarDayActive: "Ενεργό",
    calendarDayScheduledOff: "Προγραμματισμένο ρεπό",
    calendarEdit: "Αλλαγή",
    workingHoursDetailTitle: "Ώρες Εργασίας ανά Ημέρα Εβδομάδας",
    workingHoursDesc: "Ενεργοποιήστε τις διαθέσιμες ημέρες της εβδομάδας και ορίστε μεμονωμένες ώρες εργασίας ανά ημέρα.",
    signedDate: "Ημερομηνία υπογραφής",
    defaultSchedule: "Προεπιλεγμένο ωράριο",
  },
  ru: {
    calendarTitle: "Ежемесячный календарь выездов (Настройка выходных)",
    calendarDesc: "Дни регулярного расписания отмечаются как доступные. Нажмите на дату, чтобы снять отметку и назначить выходной.",
    calendarThisMonth: "Текущий месяц",
    calendarNextMonth: "Следующий месяц",
    calendarAvailable: "Доступно",
    calendarDayOff: "Выходной",
    calendarDays: "дней",
    calendarReset: "Сбросить выходные",
    calendarExclusionsTitle: "Индивидуально назначенные выходные:",
    calendarNoExclusions: "Индивидуальные выходные не назначены (активен во все дни расписания)",
    calendarDayActive: "Рабочий день",
    calendarDayScheduledOff: "Плановый выходной",
    calendarEdit: "Изменить",
    workingHoursDetailTitle: "Рабочие часы по дням недели",
    workingHoursDesc: "Активируйте доступные дни недели и настройте индивидуальные рабочие часы для каждого дня.",
    signedDate: "Дата договора",
    defaultSchedule: "Стандартные часы",
  },
  uk: {
    calendarTitle: "Щомісячний календар виїздів (Налаштування вихідних)",
    calendarDesc: "Дні щотижневого графіка автоматично позначаються як робочі. Натисніть на дату, щоб зробити її вихідним днем.",
    calendarThisMonth: "Поточний місяць",
    calendarNextMonth: "Наступний місяць",
    calendarAvailable: "Доступно",
    calendarDayOff: "Вихідний",
    calendarDays: "днів",
    calendarReset: "Скинути вихідні",
    calendarExclusionsTitle: "Індивідуально встановлені вихідні:",
    calendarNoExclusions: "Індивідуальних вихідних не встановлено (активний у всі дні графіка)",
    calendarDayActive: "Робочий день",
    calendarDayScheduledOff: "Плановий вихідний",
    calendarEdit: "Змінити",
    workingHoursDetailTitle: "Робочі години за днями тижня",
    workingHoursDesc: "Активуйте доступні дні тижня та встановіть індивідуальні робочі години для кожного дня.",
    signedDate: "Дата договору",
    defaultSchedule: "Стандартні години",
  },
  kk: {
    calendarTitle: "Айлық шығу күнтізбесі (Жеке демалыс күндерін баптау)",
    calendarDesc: "Апталық кестеге сәйкес күндер белсенді болып белгіленеді. Кез келген күнді басып, демалыс ретінде белгілеңіз.",
    calendarThisMonth: "Осы ай",
    calendarNextMonth: "Келесі ай",
    calendarAvailable: "Қолжетімді",
    calendarDayOff: "Демалыс",
    calendarDays: "күн",
    calendarReset: "Демалыстарды қалпына келтіру",
    calendarExclusionsTitle: "Жеке белгіленген демалыс күндері:",
    calendarNoExclusions: "Жеке демалыс күндері орнатылмаған (барлық белгіленген күндерде белсенді)",
    calendarDayActive: "Жұмыс күні",
    calendarDayScheduledOff: "Кесте бойынша демалыс",
    calendarEdit: "Өзгерту",
    workingHoursDetailTitle: "Апта күндері бойынша жұмыс уақыты",
    workingHoursDesc: "Қолжетімді апта күндерін белсендіріп, әр күнге жеке жұмыс уақытын орнатыңыз.",
    signedDate: "Келісімшарт күні",
    defaultSchedule: "Негізгі уақыт",
  },
  uz: {
    calendarTitle: "Oylik chaqiruv taqvimi (Alohida dam olish kunlarini sozlash)",
    calendarDesc: "Haftalik jadvalga mos kunlar avtomatik tarzda faol belgilanadi. Istalgan sanani bosib, dam olish kuni qilib belgilang.",
    calendarThisMonth: "Shu oy",
    calendarNextMonth: "Keyingi oy",
    calendarAvailable: "Mavjud",
    calendarDayOff: "Dam olish kuni",
    calendarDays: "kun",
    calendarReset: "Dam olish kunlarini tiklash",
    calendarExclusionsTitle: "Belgilangan alohida dam olish kunlari:",
    calendarNoExclusions: "Alohida dam olish kunlari belgilanmagan (barcha belgilangan kunlarda faol)",
    calendarDayActive: "Ish kuni",
    calendarDayScheduledOff: "Rejali dam olish",
    calendarEdit: "O'zgartirish",
    workingHoursDetailTitle: "Hafta kunlari bo'yicha ish vaqti",
    workingHoursDesc: "Mavjud hafta kunlarini faollashtiring va har bir kun uchun alohida ish vaqtini belgilang.",
    signedDate: "Shartnoma sanasi",
    defaultSchedule: "Standart vaqt",
  },
  mn: {
    calendarTitle: "Сарын дуудлагын хуанли (Хувийн амралтын өдөр тохируулах)",
    calendarDesc: "Долоо хоногийн тохиргоотой нийцсэн өдрүүд автоматаар идэвхтэй байна. Ажиллах боломжгүй өдрөө дарж амралт болгоно уу.",
    calendarThisMonth: "Энэ сар",
    calendarNextMonth: "Дараа сар",
    calendarAvailable: "Боломжтой",
    calendarDayOff: "Амралтын өдөр",
    calendarDays: "өдөр",
    calendarReset: "Амралтын өдрийг шинэчлэх",
    calendarExclusionsTitle: "Хувьдаа тохируулсан амралтын өдрүүд:",
    calendarNoExclusions: "Хувийн амралтын өдөр тохируулаагүй (сонгосон бүх өдрүүдэд ажиллана)",
    calendarDayActive: "Ажлын өдөр",
    calendarDayScheduledOff: "Хуваарьт амралт",
    calendarEdit: "Өөрчлөх",
    workingHoursDetailTitle: "Гарагийн ажлын цагийн дэлгэрэнгүй",
    workingHoursDesc: "Ажиллах боломжтой гарагуудыг идэвхжүүлж, өдөр бүрийн ажлын цагийн хуваарийг тохируулна уу.",
    signedDate: "Гэрээ хийсэн огноо",
    defaultSchedule: "Үндсэн цаг",
  },
  id: {
    calendarTitle: "Kalender Layanan Bulanan (Pengaturan Hari Libur)",
    calendarDesc: "Hari yang sesuai jadwal mingguan ditandai aktif. Klik tanggal mana saja untuk menghapus centang dan menjadikannya hari libur.",
    calendarThisMonth: "Bulan Ini",
    calendarNextMonth: "Bulan Depan",
    calendarAvailable: "Tersedia",
    calendarDayOff: "Hari Libur",
    calendarDays: "hari",
    calendarReset: "Reset Hari Libur",
    calendarExclusionsTitle: "Daftar Hari Libur Khusus:",
    calendarNoExclusions: "Tidak ada hari libur khusus (aktif di semua hari yang dipilih)",
    calendarDayActive: "Hari Kerja",
    calendarDayScheduledOff: "Libur Rutin",
    calendarEdit: "Ubah",
    workingHoursDetailTitle: "Jam Kerja Berdasarkan Hari",
    workingHoursDesc: "Aktifkan hari kerja yang tersedia dan atur jam kerja individual per hari.",
    signedDate: "Tanggal Kontrak",
    defaultSchedule: "Jam Standar",
  },
  th: {
    calendarTitle: "ปฏิทินการออกปฏิบัติงานรายเดือน (ตั้งค่าวันหยุดส่วนตัว)",
    calendarDesc: "วันที่ตรงกับการตั้งค่ารายสัปดาห์จะถูกทำเครื่องหมายว่าพร้อมทำงาน คลิกที่วันที่ใดก็ได้เพื่อยกเลิกและตั้งเป็นวันหยุด",
    calendarThisMonth: "เดือนนี้",
    calendarNextMonth: "เดือนหน้า",
    calendarAvailable: "พร้อมทำงาน",
    calendarDayOff: "วันหยุด",
    calendarDays: "วัน",
    calendarReset: "รีเซ็ตวันหยุด",
    calendarExclusionsTitle: "รายการวันหยุดส่วนตัวที่กำหนด:",
    calendarNoExclusions: "ไม่มีวันหยุดส่วนตัวที่กำหนด (ปฏิบัติงานตามวันทำการทั้งหมด)",
    calendarDayActive: "วันทำงาน",
    calendarDayScheduledOff: "วันหยุดประจำ",
    calendarEdit: "แก้ไข",
    workingHoursDetailTitle: "ชั่วโมงการทำงานตามวันในสัปดาห์",
    workingHoursDesc: "เปิดใช้งานวันที่พร้อมทำงานในแต่ละสัปดาห์ และตั้งเวลาทำงานแยกตามแต่ละวันได้",
    signedDate: "วันที่ทำสัญญา",
    defaultSchedule: "ช่วงเวลามาตรฐาน",
  },
  my: {
    calendarTitle: "လစဉ် ထွက်ခွာမှု ပြက္ခဒိန် (တစ်ဦးချင်း အားလပ်ရက် သတ်မှတ်ချက်)",
    calendarDesc: "အပတ်စဉ်သတ်မှတ်ချက်နှင့်ကိုက်ညီသောရက်များကို အလိုအလျောက် အဆင်သင့်ဖြစ်ကြောင်း မှတ်သားထားသည်။ အားလပ်ရက်အဖြစ် သတ်မှတ်ရန် မည်သည့်ရက်ကိုမဆို နှိပ်ပါ။",
    calendarThisMonth: "ယခုလ",
    calendarNextMonth: "နောက်လ",
    calendarAvailable: "အဆင်သင့်",
    calendarDayOff: "အားလပ်ရက်",
    calendarDays: "ရက်",
    calendarReset: "အားလပ်ရက်များ ပြန်လည်သတ်မှတ်",
    calendarExclusionsTitle: "သီးသန့်သတ်မှတ်ထားသော အားလပ်ရက်များ:",
    calendarNoExclusions: "သီးသန့်အားလပ်ရက် သတ်မှတ်ထားခြင်းမရှိပါ (သတ်မှတ်ထားသော ရက်အားလုံးတွင် အလုပ်လုပ်မည်)",
    calendarDayActive: "အလုပ်လုပ်ရက်",
    calendarDayScheduledOff: "ပုံမှန်အားလပ်ရက်",
    calendarEdit: "ပြင်ဆင်ရန်",
    workingHoursDetailTitle: "ရက်အလိုက် အလုပ်ချိန် သတ်မှတ်ချက်",
    workingHoursDesc: "အဆင်သင့်ဖြစ်သော ရက်များကို ဖွင့်ပြီး တစ်ရက်ချင်းအလိုက် အလုပ်ချိန် သတ်မှတ်ပါ။",
    signedDate: "စာချုပ်ချုပ်ဆိုသည့်နေ့",
    defaultSchedule: "မူလ အလုပ်ချိန်",
  },
  km: {
    calendarTitle: "ប្រតិទិនចេញបម្រើសេវាប្រចាំខែ (ការកំណត់ថ្ងៃឈប់សម្រាកផ្ទាល់ខ្លួន)",
    calendarDesc: "ថ្ងៃដែលត្រូវនឹងការកំណត់ប្រចាំសប្តាហ៍ត្រូវបានសម្គាល់ថាអាចចេញធ្វើការបាន។ ចុចលើកាលបរិច្ឆេទណាមួយដើម្បីកំណត់ជាថ្ងៃសម្រាក។",
    calendarThisMonth: "ខែនេះ",
    calendarNextMonth: "ខែបន្ទាប់",
    calendarAvailable: "ទំនេរ",
    calendarDayOff: "ថ្ងៃឈប់សម្រាក",
    calendarDays: "ថ្ងៃ",
    calendarReset: "កំណត់ថ្ងៃសម្រាកឡើងវិញ",
    calendarExclusionsTitle: "បញ្ជីថ្ងៃឈប់សម្រាកផ្ទាល់ខ្លួន៖",
    calendarNoExclusions: "គ្មានថ្ងៃឈប់សម្រាកផ្ទាល់ខ្លួន (ធ្វើការគ្រប់ថ្ងៃតាមកាលវិភាគ)",
    calendarDayActive: "ថ្ងៃធ្វើការ",
    calendarDayScheduledOff: "ថ្ងៃសម្រាកធម្មតា",
    calendarEdit: "ផ្លាស់ប្តូរ",
    workingHoursDetailTitle: "ម៉ោងធ្វើការតាមថ្ងៃក្នុងមួយសប្តាហ៍",
    workingHoursDesc: "ធ្វើឱ្យសកម្មនូវថ្ងៃក្នុងសប្តាហ៍ដែលអាចធ្វើការបាន និងកំណត់ម៉ោងធ្វើការផ្ទាល់ខ្លួនសម្រាប់ថ្ងៃនីមួយៗ។",
    signedDate: "កាលបរិច្ឆេទកិច្ចសន្យា",
    defaultSchedule: "ម៉ោងកំណត់ដើម",
  },
  hi: {
    calendarTitle: "मासिक सेवा कैलेंडर (व्यक्तिगत अवकाश निर्धारण)",
    calendarDesc: "साप्ताहिक सेटिंग्स से मेल खाने वाले दिन स्वचालित रूप से सक्रिय चिह्नित होते हैं। अवकाश निर्धारित करने के लिए किसी भी तिथि पर क्लिक करें।",
    calendarThisMonth: "इस महीने",
    calendarNextMonth: "अगले महीने",
    calendarAvailable: "उपलब्ध",
    calendarDayOff: "अवकाश",
    calendarDays: "दिन",
    calendarReset: "अवकाश रीसेट करें",
    calendarExclusionsTitle: "निर्धारित व्यक्तिगत अवकाश सूची:",
    calendarNoExclusions: "कोई व्यक्तिगत अवकाश निर्धारित नहीं है (सभी निर्धारित दिनों में सक्रिय)",
    calendarDayActive: "कार्य दिवस",
    calendarDayScheduledOff: "नियमित अवकाश",
    calendarEdit: "बदलें",
    workingHoursDetailTitle: "सप्ताह के दिनों के अनुसार कार्य के घंटे",
    workingHoursDesc: "सप्ताह के उपलब्ध दिनों को सक्रिय करें और प्रति दिन व्यक्तिगत कार्य घंटे निर्धारित करें।",
    signedDate: "अनुबंध तिथि",
    defaultSchedule: "डिफ़ॉल्ट समय",
  },
  ne: {
    calendarTitle: "मासिक सेवा क्यालेन्डर (व्यक्तिगत बिदा सेटिङ)",
    calendarDesc: "साप्ताहिक तालिका अनुसारका दिनहरू स्वतः सक्रिय रूपमा देखाइन्छ। बिदा सेट गर्न कुनै पनि मितिमा क्लिक गर्नुहोस्।",
    calendarThisMonth: "यो महिना",
    calendarNextMonth: "अर्को महिना",
    calendarAvailable: "उपलब्ध",
    calendarDayOff: "बिदा",
    calendarDays: "दिन",
    calendarReset: "बिदा रिसेट गर्नुहोस्",
    calendarExclusionsTitle: "निर्धारित व्यक्तिगत बिदा सूची:",
    calendarNoExclusions: "कुनै व्यक्तिगत बिदा सेट गरिएको छैन (सबै निर्धारित दिनहरूमा सक्रिय)",
    calendarDayActive: "कामको दिन",
    calendarDayScheduledOff: "नियमित बिदा",
    calendarEdit: "परिवर्तन",
    workingHoursDetailTitle: "हप्ताका दिन अनुसार कामको समय",
    workingHoursDesc: "हप्ताका उपलब्ध दिनहरू सक्रिय गर्नुहोस् र प्रत्येक दिनको लागि व्यक्तिगत कामको समय निर्धारण गर्नुहोस्।",
    signedDate: "सम्झौता मिति",
    defaultSchedule: "पूर्वनिर्धारित समय",
  },
  bn: {
    calendarTitle: "মাসিক সেবা ক্যালেন্ডার (ব্যক্তিগত ছুটির দিন নির্ধারণ)",
    calendarDesc: "সাপ্তাহিক সময়সূচীর সাথে মিল থাকা দিনগুলি স্বয়ংক্রিয়ভাবে সক্রিয় হিসেবে চিহ্নিত হয়। ছুটির দিন সেট করতে যেকোনো তারিখে ক্লিক করুন।",
    calendarThisMonth: "চলতি মাস",
    calendarNextMonth: "পরবর্তী মাস",
    calendarAvailable: "উপলব্ধ",
    calendarDayOff: "ছুটির দিন",
    calendarDays: "দিন",
    calendarReset: "ছুটি রিসেট করুন",
    calendarExclusionsTitle: "নির্ধারিত ব্যক্তিগত ছুটির তালিকা:",
    calendarNoExclusions: "কোনো ব্যক্তিগত ছুটি নির্ধারিত নেই (সমস্ত নির্ধারিত দিনে সক্রিয়)",
    calendarDayActive: "কাজের দিন",
    calendarDayScheduledOff: "নিয়মিত ছুটি",
    calendarEdit: "পরিবর্তন",
    workingHoursDetailTitle: "বার অনুযায়ী কাজের সময় নির্ধারণ",
    workingHoursDesc: "সপ্তাহের উপলব্ধ দিনগুলি সক্রিয় করুন এবং প্রতিদিনের জন্য আলাদা কাজের সময় নির্ধারণ করুন।",
    signedDate: "চুক্তির তারিখ",
    defaultSchedule: "ডিফল্ট সময়",
  },
  ta: {
    calendarTitle: "மாதாந்திர சேவை நாள்காட்டி (தனிப்பட்ட விடுமுறை நாட்கள்)",
    calendarDesc: "வாராந்திர அமைப்புகளுடன் பொருந்தும் நாட்கள் தானாகவே செயலில் உள்ளதாகக் குறிக்கப்படும். விடுமுறை நாளாக அமைக்க ஏதேனும் தேதியைக் கிளிக் செய்யவும்.",
    calendarThisMonth: "இந்த மாதம்",
    calendarNextMonth: "அடுத்த மாதம்",
    calendarAvailable: "கிடைக்கும்",
    calendarDayOff: "விடுமுறை",
    calendarDays: "நாட்கள்",
    calendarReset: "விடுமுறைகளை மீட்டமை",
    calendarExclusionsTitle: "தனிப்பட்ட விடுமுறை நாட்கள் பட்டியல்:",
    calendarNoExclusions: "தனிப்பட்ட விடுமுறைகள் எதுவும் அமைக்கப்படவில்லை (அனைத்து நாட்களிலும் செயலில்)",
    calendarDayActive: "வேலை நாள்",
    calendarDayScheduledOff: "வழக்கமான விடுமுறை",
    calendarEdit: "மாற்று",
    workingHoursDetailTitle: "கிழமை வாரியாக வேலை நேரம்",
    workingHoursDesc: "வாரத்தின் கிடைக்கும் நாட்களை இயக்கி, ஒரு நாளைக்கு தனிப்பட்ட வேலை நேரங்களை அமைக்கவும்.",
    signedDate: "ஒப்பந்த தேதி",
    defaultSchedule: "இயல்புநிலை நேரம்",
  },
  si: {
    calendarTitle: "මාසික සේවා දින දර්ශනය (පුද්ගලික නිවාඩු සැකසුම)",
    calendarDesc: "සතිපතා සැකසුම් වලට ගැළපෙන දින ස්වයංක්‍රීයව ක්‍රියාකාරී ලෙස සලකුණු වේ. නිවාඩු දිනයක් ලෙස සැකසීමට ඕනෑම දිනයක් මත ක්ලික් කරන්න.",
    calendarThisMonth: "මෙම මාසය",
    calendarNextMonth: "ඊළඟ මාසය",
    calendarAvailable: "ලබා ගත හැක",
    calendarDayOff: "නිවාඩු දිනය",
    calendarDays: "දින",
    calendarReset: "නිවාඩු යළි සකසන්න",
    calendarExclusionsTitle: "පුද්ගලික නිවාඩු දින ලැයිස්තුව:",
    calendarNoExclusions: "පුද්ගලික නිවාඩු සකසා නැත (වින්‍යාසගත සියලුම සතියේ දිනවල ක්‍රියාකාරී)",
    calendarDayActive: "වැඩ කරන දිනය",
    calendarDayScheduledOff: "නියමිත නිවාඩු",
    calendarEdit: "වෙනස් කරන්න",
    workingHoursDetailTitle: "සතියේ දින අනුව වැඩ කරන වේලාවන්",
    workingHoursDesc: "ලබා ගත හැකි සතියේ දින සක්‍රිය කර දිනකට තනි වැඩ කරන වේලාවන් සකසන්න.",
    signedDate: "ගිවිසුම් දිනය",
    defaultSchedule: "සුපුරුදු වේලාව",
  },
  ar: {
    calendarTitle: "جدول الانطلاق الشهري (ضبط أيام العطل الفردية)",
    calendarDesc: "يتم تحديد الأيام المطابقة للجدول الأسبوعي تلقائيًا كأيام متاحة. انقر فوق أي تاريخ لإلغاء التحديد وتعيينه كيوم عطلة.",
    calendarThisMonth: "هذا الشهر",
    calendarNextMonth: "الشهر القادم",
    calendarAvailable: "متاح",
    calendarDayOff: "يوم عطلة",
    calendarDays: "أيام",
    calendarReset: "إعادة ضبط العطل",
    calendarExclusionsTitle: "قائمة أيام العطل الفردية المحددة:",
    calendarNoExclusions: "لم يتم تحديد أيام عطل فردية (متاح طوال الأيام المحددة)",
    calendarDayActive: "يوم عمل",
    calendarDayScheduledOff: "عطلة دورية",
    calendarEdit: "تعديل",
    workingHoursDetailTitle: "ساعات العمل حسب أيام الأسبوع",
    workingHoursDesc: "قم بتفعيل أيام الأسبوع المتاحة وحدد ساعات عمل فردية لكل يوم.",
    signedDate: "تاريخ العقد",
    defaultSchedule: "المواعيد الافتراضية",
  },
  arz: {
    calendarTitle: "جدول الانطلاق الشهري (ضبط أيام الأجازات الفردية)",
    calendarDesc: "يتم تحديد الأيام حسب الجدول الأسبوعي تلقائيًا كأيام متاحة. دوس على أي تاريخ علشان تخليه يوم أجازة.",
    calendarThisMonth: "الشهر ده",
    calendarNextMonth: "الشهر الجاي",
    calendarAvailable: "متاح",
    calendarDayOff: "يوم أجازة",
    calendarDays: "أيام",
    calendarReset: "إعادة ضبط الأجازات",
    calendarExclusionsTitle: "قائمة أيام الأجازات الفردية المحددة:",
    calendarNoExclusions: "مفيش أجازات فردية محددة (شغال كل الأيام المحددة)",
    calendarDayActive: "يوم شغل",
    calendarDayScheduledOff: "أجازة دورية",
    calendarEdit: "تعديل",
    workingHoursDetailTitle: "ساعات الشغل حسب أيام الأسبوع",
    workingHoursDesc: "فعّل أيام الأسبوع المتاحة وحدد ساعات شغل منفصلة لكل يوم.",
    signedDate: "تاريخ العقد",
    defaultSchedule: "المواعيد الافتراضية",
  },
  fa: {
    calendarTitle: "تقویم اعزام ماهانه (تنظیم روزهای مرخصی)",
    calendarDesc: "روزهای مطابق با تنظیمات هفتگی به صورت خودکار فعال می‌شوند. برای تنظیم به عنوان مرخصی روی هر تاریخی کلیک کنید.",
    calendarThisMonth: "این ماه",
    calendarNextMonth: "ماه بعد",
    calendarAvailable: "در دسترس",
    calendarDayOff: "روز مرخصی",
    calendarDays: "روز",
    calendarReset: "بازنشانی مرخصی‌ها",
    calendarExclusionsTitle: "روزهای مرخصی مشخص شده:",
    calendarNoExclusions: "روز مرخصی تعیین نشده است (فعال در تمام روزهای کاری)",
    calendarDayActive: "روز کاری",
    calendarDayScheduledOff: "تعطیلی روتین",
    calendarEdit: "تغییر",
    workingHoursDetailTitle: "ساعات کاری بر اساس روزهای هفته",
    workingHoursDesc: "روزهای در دسترس هفته را فعال کرده و ساعات کاری مجزا برای هر روز تعیین کنید.",
    signedDate: "تاریخ قرارداد",
    defaultSchedule: "ساعات پیش‌فرض",
  },
  he: {
    calendarTitle: "לוח יציאות חודשי (הגדרת ימי חופש אישיים)",
    calendarDesc: "ימים התואמים להגדרות השבועיות מסומנים אוטומטית כפעילים. לחץ על תאריך כלשהו כדי להגדיר אותו כיום חופש.",
    calendarThisMonth: "החודש",
    calendarNextMonth: "החודש הבא",
    calendarAvailable: "זמין",
    calendarDayOff: "יום חופש",
    calendarDays: "ימים",
    calendarReset: "איפוס ימי חופש",
    calendarExclusionsTitle: "ימי חופש אישיים שנקבעו:",
    calendarNoExclusions: "לא הוגדרו ימי חופש אישיים (פעיל בכל ימי השבוע שהוגדרו)",
    calendarDayActive: "יום עבודה",
    calendarDayScheduledOff: "חופש קבוע",
    calendarEdit: "שינוי",
    workingHoursDetailTitle: "שעות עבודה לפי ימי השבוע",
    workingHoursDesc: "הפעל את הימים הזמינים בשבוע והגדר שעות עבודה אישיות לכל יום.",
    signedDate: "תאריך החוזה",
    defaultSchedule: "שעות ברירת מחדל",
  },
  tr: {
    calendarTitle: "Aylık Görev Takvimi (Kişisel İzin Günü Ayarı)",
    calendarDesc: "Haftalık programa uyan günler otomatik olarak aktif işaretlenir. İzin günü olarak ayarlamak için herhangi bir tarihe tıklayın.",
    calendarThisMonth: "Bu Ay",
    calendarNextMonth: "Gelecek Ay",
    calendarAvailable: "Müsait",
    calendarDayOff: "İzin Günü",
    calendarDays: "gün",
    calendarReset: "İzinleri Sıfırla",
    calendarExclusionsTitle: "Belirlenen Kişisel İzin Günleri:",
    calendarNoExclusions: "Belirlenen kişisel izin günü yok (yapılandırılan tüm günlerde aktif)",
    calendarDayActive: "Çalışma Günü",
    calendarDayScheduledOff: "Düzenli İzin",
    calendarEdit: "Değiştir",
    workingHoursDetailTitle: "Haftanın Günlerine Göre Çalışma Saatleri",
    workingHoursDesc: "Müsait olduğunuz haftanın günlerini etkinleştirin ve her gün için ayrı çalışma saatleri belirleyin.",
    signedDate: "Sözleşme Tarihi",
    defaultSchedule: "Varsayılan Saatler",
  },
  nl: {
    calendarTitle: "Maandelijkse dispatchkalender (Vrije dagen instellen)",
    calendarDesc: "Dagen die overeenkomen met de wekelijkse planning worden automatisch als actief gemarkeerd. Klik op een datum om deze als vrije dag in te stellen.",
    calendarThisMonth: "Deze maand",
    calendarNextMonth: "Volgende maand",
    calendarAvailable: "Beschikbaar",
    calendarDayOff: "Vrije dag",
    calendarDays: "dagen",
    calendarReset: "Vrije dagen resetten",
    calendarExclusionsTitle: "Individueel ingestelde vrije dagen:",
    calendarNoExclusions: "Geen vrije dagen ingesteld (actief op alle geconfigureerde werkdagen)",
    calendarDayActive: "Werkdag",
    calendarDayScheduledOff: "Geplande vrije dag",
    calendarEdit: "Wijzigen",
    workingHoursDetailTitle: "Werktijden per dag van de week",
    workingHoursDesc: "Activeer beschikbare dagen van de week en stel individuele werktijden per dag in.",
    signedDate: "Contractdatum",
    defaultSchedule: "Standaardtijden",
  },
  sv: {
    calendarTitle: "Månatlig utryckningskalender (Inställning av lediga dagar)",
    calendarDesc: "Dagar som matchar veckoschemat markeras automatiskt som aktiva. Klicka på valfritt datum för att ange det som ledig dag.",
    calendarThisMonth: "Denna månad",
    calendarNextMonth: "Nästa månad",
    calendarAvailable: "Tillgänglig",
    calendarDayOff: "Ledig dag",
    calendarDays: "dagar",
    calendarReset: "Återställ lediga dagar",
    calendarExclusionsTitle: "Individuellt inställda lediga dagar:",
    calendarNoExclusions: "Inga individuella lediga dagar inställda (aktiv alla schemalagda dagar)",
    calendarDayActive: "Arbetsdag",
    calendarDayScheduledOff: "Schemalagd ledighet",
    calendarEdit: "Ändra",
    workingHoursDetailTitle: "Arbetstider per veckodag",
    workingHoursDesc: "Aktivera tillgängliga veckodagar och ställ in individuella arbetstider per dag.",
    signedDate: "Avtalsdatum",
    defaultSchedule: "Standardtider",
  },
  da: {
    calendarTitle: "Månedlig udrykningskalender (Indstilling af fridage)",
    calendarDesc: "Dage, der matcher den ugentlige tidsplan, markeres automatisk som aktive. Klik på en dato for at indstille den som fridag.",
    calendarThisMonth: "Denne måned",
    calendarNextMonth: "Næste måned",
    calendarAvailable: "Tilgængelig",
    calendarDayOff: "Fridag",
    calendarDays: "dage",
    calendarReset: "Nulstil fridage",
    calendarExclusionsTitle: "Individuelt indstillede fridage:",
    calendarNoExclusions: "Ingen individuelle fridage indstillet (aktiv alle planlagte dage)",
    calendarDayActive: "Arbejdsdag",
    calendarDayScheduledOff: "Planlagt fri",
    calendarEdit: "Rediger",
    workingHoursDetailTitle: "Arbejdstider efter ugedage",
    workingHoursDesc: "Aktivér tilgængelige ugedage, og indstil individuelle arbejdstider pr. dag.",
    signedDate: "Kontraktdato",
    defaultSchedule: "Standardtider",
  },
  no: {
    calendarTitle: "Månedlig utrykningskalender (Innstillinger for fridager)",
    calendarDesc: "Dager som matcher ukeplanen markeres automatisk som aktive. Klikk på en dato for å angi den som fridag.",
    calendarThisMonth: "Denne måneden",
    calendarNextMonth: "Neste måned",
    calendarAvailable: "Tilgjengelig",
    calendarDayOff: "Fridag",
    calendarDays: "dager",
    calendarReset: "Tilbakestill fridager",
    calendarExclusionsTitle: "Individuelt angitte fridager:",
    calendarNoExclusions: "Ingen individuelle fridager angitt (aktiv alle konfigurerte dager)",
    calendarDayActive: "Arbeidsdag",
    calendarDayScheduledOff: "Fast fridag",
    calendarEdit: "Endre",
    workingHoursDetailTitle: "Arbeidstider etter ukedager",
    workingHoursDesc: "Aktiver tilgjengelige ukedager og angi individuelle arbeidstider per dag.",
    signedDate: "Kontraktsdato",
    defaultSchedule: "Standardtider",
  },
  am: {
    calendarTitle: "የወርሃዊ መላኪያ የቀን መቁጠሪያ (የእረፍት ቀናት ማስተካከያ)",
    calendarDesc: "በሳምንታዊ ቅንብሮች መሰረት ቀናት በራስ-ሰር ንቁ ሆነው ምልክት ይደረግባቸዋል። እንደ እረፍት ቀን ለማዘጋጀት ማንኛውንም ቀን ይጫኑ።",
    calendarThisMonth: "ይህ ወር",
    calendarNextMonth: "ቀጣይ ወር",
    calendarAvailable: "ይገኛል",
    calendarDayOff: "የእረፍት ቀን",
    calendarDays: "ቀናት",
    calendarReset: "የእረፍት ቀናት ዳግም አስጀምር",
    calendarExclusionsTitle: "የተለዩ የእረፍት ቀናት ዝርዝር:",
    calendarNoExclusions: "ምንም የተለየ የእረፍት ቀን አልተዘጋጀም (በሁሉም ሳምንታዊ ቀናት ንቁ)",
    calendarDayActive: "የስራ ቀን",
    calendarDayScheduledOff: "መደበኛ እረፍት",
    calendarEdit: "ቀይር",
    workingHoursDetailTitle: "የስራ ሰዓታት በሳምንቱ ቀናት",
    workingHoursDesc: "የሚገኙትን የሳምንቱ ቀናት ያግብሩ እና ለእያንዳንዱ ቀን የግል የስራ ሰዓት ያዘጋጁ።",
    signedDate: "የውል ቀን",
    defaultSchedule: "ነባሪ ሰዓታት",
  },
  tet: {
    calendarTitle: "Kalendáriu Atendimentu Mensál (Konfigura Loron Deskansa)",
    calendarDesc: "Loron tuir oráriu semanál nian sei marka atu ativu automatikamente. Klike iha loron ruma atu halo nu'udar loron deskansa.",
    calendarThisMonth: "Fulan Ne'e",
    calendarNextMonth: "Fulan Oinmai",
    calendarAvailable: "Disponivel",
    calendarDayOff: "Loron Deskansa",
    calendarDays: "loron",
    calendarReset: "Halo Foun Loron Deskansa",
    calendarExclusionsTitle: "Lista Loron Deskansa Individuál:",
    calendarNoExclusions: "Laiha loron deskansa individuál (ativu iha loron sira hotu)",
    calendarDayActive: "Loron Serbisu",
    calendarDayScheduledOff: "Deskansa Regulár",
    calendarEdit: "Muda",
    workingHoursDetailTitle: "Oras Serbisu tuir Loron Semanál",
    workingHoursDesc: "Ativa loron sira ne'ebé disponivel iha semana laran no konfigura oras serbisu ba loron ida-idak.",
    signedDate: "Data Kontratu",
    defaultSchedule: "Oras Padraun",
  },
};

// 3. Tech and Workspace core UI strings
const TECH_WORKSPACE_UPDATES = {
  pl: {
    tech: {
      headlineLead: "Bezpośrednio łącz się z klientami w Twojej okolicy",
      actAsHelper: "profesjonalny fachowiec",
      securitySessionNotice: "3-miesięczna sesja bezpieczeństwa: 90-dniowy losowy klucz dostępu wydawany na numer telefonu",
      securitySessionExpiry: "Wygasanie sesji bezpieczeństwa",
      securitySessionExpired: "Sesja bezpieczeństwa wygasła",
      autoMaintainedDays: "dni automatycznego utrzymania",
      operatingRegions: "Obszar działalności",
      instantDispatchConnected: "Natychmiastowe połączenie z klientem",
      registeredServices: "Zarejestrowane usługi",
      categoriesRegisteredCount: "kategorie zarejestrowane",
      editableInWorkspace: "Możliwość edycji w strefie fachowca",
      openWorkspaceBtn: "Zarządzaj moją strefą fachowca",
      statusActiveShort: "Dostępny do wyjazdów",
      statusPausedShort: "Tymczasowo wstrzymany",
      clickToToggle: "Kliknij, aby przełączyć",
      hotlineNotice: "Główna linia wsparcia systemu",
      helperPortal: "Portal Fachowca",
      registerTab: "Rejestracja nowego fachowca",
      loginTab: "Logowanie istniejącego fachowca",
      newHelperRegTitle: "Rejestracja nowego fachowca (3-miesięczny bezpieczny dostęp)",
      existingHelperLoginTitle: "Logowanie zarejestrowanego fachowca",
      newHelperRegDesc: "Bez konieczności podawania numeru PESEL. Pracuj swobodnie przez 3 miesiące tylko z numerem telefonu.",
      existingHelperLoginDesc: "Wprowadź swój 3-miesięczny dedykowany klucz dostępu, aby wejść do strefy roboczej.",
      accessKeyLabel: "3-miesięczny dedykowany klucz dostępu",
      loginWithAccessKey: "Zaloguj się kluczem bezpieczeństwa (ważny 90 dni)",
      loginKeyNotice: "Wprowadź 3-miesięczny klucz dostępu otrzymany przez SMS/KakaoTalk, aby natychmiast przejść do strefy fachowca.",
      lostCodeBtn: "Zgubiłeś kod dostępu?",
      reissueCodeTitle: "Ponowne wydanie klucza przez telefon",
      getAccessKeyBtn: "Uzyskaj 3-miesięczny klucz bezpieczeństwa",
      registerAndStart: "Zarejestruj się i rozpocznij usługę",
      selectServices: "Wybierz kategorie usług",
      selectServicesDesc: "Wybierz wszystkie kategorie, które możesz obsługiwać (możesz to zmienić w każdej chwili).",
      selectedCount: " wybrano",
      helperNameLabel: "Imię lub pseudonim fachowca",
      agreeTerms: "Zapoznałem się z regulaminem i zasadami bezpieczeństwa LIFE.HELP i deklaruję rzetelną obsługę.",
      keySentNotice: "Klucz dostępu wysłano pomyślnie",
      issuedAccessKey: "Wydany 3-miesięczny klucz dostępu",
      copy: "Kopiuj",
      copied: "Skopiowano!",
      backToTechHome: "Powrót do strony fachowca",
      verifying: "Weryfikacja...",
      changePhoneBtn: "Zmień",
      enterAccessKeyError: "Wprowadź 3-miesięczny klucz bezpieczeństwa.",
      enterNameError: "Wprowadź swoje imię lub pseudonim.",
      selectServiceError: "Wybierz przynajmniej jedną kategorię usług.",
      agreeTermsError: "Wymagana jest akceptacja regulaminu.",
    },
    workspace: {
      activeTitle: "Aktywny (Gotowy do wyjazdu)",
      activeDesc: "Jesteś obecnie dostępny do nowych zleceń. Przełącz na pauzę, gdy robisz przerwę.",
      pauseBtn: "Wstrzymaj dostępność",
      pausedTitle: "Wstrzymany (Przerwa)",
      pausedDesc: "Przyjmowanie wezwań jest wstrzymane. Włącz ponownie, gdy będziesz gotowy do pracy.",
      resumeBtn: "Wznów aktywność",
      hotlineTitle: "Główne infolinie dyspozytorskie",
      hotlineDesc: "W razie braku dostępu do aplikacji lub pilnych zmian natychmiast skontaktuj się z naszym zespołem.",
      team1: "Infolinia Zespół 1 (Pilne)",
      team2: "Infolinia Zespół 2 (Standard)",
      call: "Zadzwoń",
      sms: "SMS",
      servicesTitle: "Zarządzanie kategoriami usług",
      servicesDesc: "Kliknij, aby usunąć niedostępne usługi lub dodać nowe w czasie rzeczywistym.",
      categoriesActive: "Aktywne kategorie",
      serviceActive: "Aktywna",
      serviceDisabled: "Wyłączona",
      regionsTitle: "Obsługiwane regiony wyjazdowe",
      regionsDesc: "Kliknij ✕, aby usunąć region, lub dodaj nowe dostępne obszary.",
      regionsCount: "Ustawione regiony",
      addRegionBtn: "Dodaj region",
      scheduleTitle: "Dostępny harmonogram",
      hours24: "Gotowość do natychmiastowego wyjazdu 24/7",
    }
  }
};

console.log('Script loaded successfully.');

